### ISSUE TITLE
Add tab_line picker to theme editor

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#10028]
From: https://github.com/mozilla/addons-frontend/issues/6963

---

Right now, there's no tab_line picker in the theme editor, which seems to be encouraging theme authors to change the accentcolor to change the tab line color, which produces inaccessible themes, since the accentcolor is used as window background.

Here's an example of a bug that this causes: bugzilla.mozilla.org/show_bug.cgi?id=1506913

See also: bugzilla.mozilla.org/show_bug.cgi?id=1508081

@eviljeff Would it be possible to add a "Tab line color" field that changes the tab_line property?

**Comment by eviljeff** [comment]
Possible, but it's a Product call if we want to add another field to an already full wizard page (to partially work around a bug in Firefox that really needs to be fixed in Firefox too).  

If so, need the "name" of the color, if "Tab Line" isn't sufficient, and a description for the tooltip similar to the other colors.

@jvillalobos

**Comment by jvillalobos** [comment]
Adding the field won't help unless theme creators know what it does and why they should favor it. And, even with bug 1508081 fixed, there's still the possibility that some themes will use the same `textcolor` and `accentcolor`.

I think we need some kind of warning for when `textcolor` and `accentcolor` are the same color, or very similar. Ideally, we should also show a preview of the findbar in the theme creation page, and in Firefox Color, since that's the UI being affected by this. That's more work than adding a field, but I think it would be more effective.

We can also try documenting this issue and reach out to designers. I'll leave that to @caitmuenster .

**Comment by jvillalobos** [comment]
Ping @caitmuenster

**Comment by caitmuenster** [comment]
I'd like to re-open this and tie it into the Outreachy project for updating the AMO Theme Generator.

**Comment by eviljeff** [comment]
This issue needs some rescoping based on @jvillalobos 's comments https://github.com/mozilla/addons-server/issues/10028#issuecomment-440425755 - just adding the tab_line property isn't the complete fix. 

Potentially also there needs to be warnings about using similar colors; a (big) update to the wizard to show the find bar (and how that affects the current rendered preview); and some documentation added for theme designers.  Likely they need to be split out into seperate issues.

**Comment by avgupt** [comment]
Can I start working on this issue once the details are figured out? @caitmuenster

**Comment by eviljeff** [comment]
moved the work about clashing colours to #17192
