### ISSUE TITLE
use id rather than username in all urls we server

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10102]
part of #8302 - all legacy pages and api responses should use the user id rather than username in urls.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

User profile URLs on the legacy pages are now including by default the user `id` instead of the `username`
Profile pages are still served if the request is made by `username`

The api also reflects these changes:
![image](https://user-images.githubusercontent.com/31961530/49810317-a798c300-fd69-11e8-9fa8-766b9281993e.png)
