### ISSUE TITLE
Unexpected search results for "websocket" searchterm

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10127]
### Describe the problem and steps to reproduce it:

I searched for the term _websocket_: https://addons.mozilla.org/en-US/firefox/search/?q=websocket&appver=64.0&platform=mac

### What happened?

The few top results look ok, but then I see lots of unrelated results:
* Language packs
* Personas Plus
* a theme about yahoo
* a spell checker
* ...

![screenshot_2018-11-30 search results for websocket add-ons for firefox en-us](https://user-images.githubusercontent.com/873258/49290218-b4363500-f4a6-11e8-8935-510db74f4e9d.png)

### What did you expect to happen?

Seeing only _websocket_ related add-ons.

**Comment by diox** [comment]
It's due to the fact that `so` is in the dictionary decompounder. It's a bad idea, because it means a search for a word containing `so` will match add-ons named `Persona Bar` or `Source Foo` for instance. And more because of fuzzy matching - that's why you get `Polish Spellchecker`!

2 letter words are too short & common to be in the dictionary decompounder.

**Comment by AlexandraMoga** [comment]
@diox I have re-verified this in prod but I could't see much of an improvement with search results for `websocket`:

![image 1](https://user-images.githubusercontent.com/31961530/49999512-b668bb00-ff9f-11e8-91f7-d29d64e2aed8.png)

**Comment by diox** [comment]
Reindex done, there is a lot fewer results now.

**Comment by AlexandraMoga** [comment]
Verified after the reindex:

![2018-12-24_11-14-26](https://user-images.githubusercontent.com/31961530/50395623-ec5f2980-076d-11e9-8bd1-14c4eb47e756.png)
