### ISSUE TITLE
i cant find ipfood 

### ISSUE THREAD

**Issue by filipusneri09** [mozilla/addons-server#10122]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy (this add-on has not been updated in years). This causes the add-on to be considered incomplete, and that's why you're seeing the error.
