### ISSUE TITLE
support ids / drop usernames from collections

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10172]
we currently only support usernames in all collection related (legacy) views, and check username, instead of id, in the collection APIs.  This needs to be changed to support either just support id, or support id and username equally so #8302 can happen

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

Collections URLs (only legacy pages) include the user id instead of the username. If the request is made by `username`, a redirect (301) to the URL containing the user `id` will occur. 

The api also reflects these changes:

![image](https://user-images.githubusercontent.com/31961530/49809629-15dc8600-fd68-11e8-8021-85f769495cb0.png)
