### ISSUE TITLE
TAARDIS: Add curation override mechanism to discovery endpoint

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#10174]
[PRD: with details of the override feature is here](https://docs.google.com/document/d/1m_zmiVh1Oq8sz4NPjEQJz5k3MJZSVdpfr6Ar2IvyQpI/edit?ts=5bd1d4bd#heading=h.jvjx2h18ebr7
).  

See [the documentation for what TAAR is expecting here](https://github.com/mozilla/taar/blob/e4efb742f2117a73cddcf9c3ad70eaa27c6a9a30/API.md#get-addon-recommendations)

It's likely this can be an addition to the existing Disco pane curation tool to provide the hint as to what data needs to be sent to TAAR to configure overrides.

The rationale behind sending data to TAAR when we want to request recommendations is that this is easier than requiring TAAR to reach into AMO's data to find this out.

*Note: since this will receive a fair amount of traffic we'll need to optimize this so that the data lookup doesn't weigh down the `Disco -> AMO -> TAAR -> AMO -> Disco` round-trip response time.*

**Comment by muffinresearch** [comment]
See also https://github.com/mozilla/addons-frontend/issues/7218 which details passing the hashed client-id that will also be passed to TAAR via the same endpoint.

**Comment by AlexandraMoga** [comment]
@diox  I've checked the documentation from the issue but I'm not 100% sure what should I test at this point.
I've noticed that you added a new field - Position override - to the Disco Pane curation tool, but I'm not sure how this works and how it is supposed to influence recommendations.
Maybe you can point me in the right direction.

**Comment by diox** [comment]
@AlexandraMoga : if `disco-recommendations` is on (it's probably off at the moment on dev), then disco pane fetches add-on recommendations from TAAR and replaces editorial content with recommendations (if there are any). When an item has an override position set, it will always be present at the top of the recommendations, regardless of what TAAR wants to recommend, independently of what's set as the normal editorial position.

At the moment you can only fully test it by [calling the API](https://addons-server.readthedocs.io/en/latest/topics/api/discovery.html#discovery-recommendations), since https://github.com/mozilla/addons-frontend/issues/7218 is not implemented yet.

**Comment by AlexandraMoga** [comment]
@diox I've tried to set the `disco-recommendations` switch on on -dev but I'm receiving an server error when I hit Enable the selected switch.

**Comment by diox** [comment]
That's https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5106161/?query=is:unresolved which would indicate that somehow you didn't pass a creation date - if there isn't one already, make one up.

**Comment by AlexandraMoga** [comment]
I've set he `disco-recommendations` switch on and I've tried to retrieve data from the [discovery API](https://addons-server.readthedocs.io/en/latest/topics/api/discovery.html#discovery-recommendations) by passing a `telemetry-client-id ` *
*Note:  when disco recommendations were implemented, we asked the TAAR team to provide some sample client IDs that will return valid data on -dev. They've given us the following samples:

00000000-0000-0000-0000-000000000000
11111111-1111-1111-1111-111111111111
22222222-2222-2222-2222-222222222222
33333333-3333-3333-3333-333333333333

All my requests are returning an internal server error
see https://addons-dev.allizom.org/api/v4/discovery/?telemetry-client-id=11111111-1111-1111-1111-111111111111
I've also tried to use my real clientID but that is returning a server error as well.

Could the TAAR -dev server be down? If so, how can we check that indeed this is causing the issue?

**Comment by diox** [comment]
Note that you need to pass a sha256 hash of your client id now, instead of the actual client id.

But as you noted, it looks like taar on dev is currently down or not behaving correctly. Traceback for the error: https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5106388/?query=is:unresolved

I need to write the API more defensively against this, and will investigate why taar is down.

**Comment by AlexandraMoga** [comment]
@diox I'm still not receiving recommendations from TAAR when I'm sending a request to the discovery api.
Here is my test method:

1. I've verified that the test clientID for -dev is returning recommendations:
https://taar.dev.mozaws.net/v1/api/recommendations/12b9377cbe7e5c94e8a70d9d23929523d14afa954793130f8a3959c7b849aca8/

2. I've made sure that some of the guids returned by TAAR actually exist on -dev (I've updated the addons or uploaded new addons entirely with the corresponding guids)

3. I've checked that `disco-recommendations` are on and there is no position override set in Admin (Position override = 0) for the Discovery Items

4. I've sent several requests to the discovery api with the test clientId added as a parameter:
https://addons-dev.allizom.org/api/v4/discovery/?telemetry-client-id=12b9377cbe7e5c94e8a70d9d23929523d14afa954793130f8a3959c7b849aca8

The results are always the addons I've added through the admin discovery tool.

**Comment by diox** [comment]
Re-opening to investigate.

**Comment by AlexandraMoga** [comment]
Recommendations are working now:

![image](https://user-images.githubusercontent.com/31961530/51236262-656f2c80-197a-11e9-8777-ec791fa5eed1.png)


@diox 
Now, for the actual tests:

1. I have added [Awesome screenshot](https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/) as the first discovery item and set Position override = 1.
Results: when I'm sending a request to the discovery API, I can see that Awesome screenshot is constantly returned among the results, **but not always on the 1st position.**

2. When all the 4 extensions featured on the discopane have an override position set, this is what happens:
a) the discovery api returns only the promoted extensions (no recommendations), but the order is not the one set by the override position, or..
b) the discovery api also brings recommended extensions, ignoring the addons that have an override position set

For the second test, I have the following set-up for the discovery items:

https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/
Awesome Screenshot Plus  - Position override = 2
AMO Admin Assistant - Position override = 3
Search by Image - Position override = 5
Tabby cat - Position override = 6
I haven't set on override position for themes.

This issue is considerably long already, so if you want to investigate this in a follow up, that's fine by me.

**Comment by diox** [comment]
Yeah, please open a new issue. This is making my head hurt already :)

**Comment by AlexandraMoga** [comment]
Filed #10415
