### ISSUE TITLE
JunpSend add on

### ISSUE THREAD

**Issue by sylvi82** [mozilla/addons-server#10188]
HI
I wanted to downland Jump Send addon but when i click on the link from their website or from Forefox one i got message - 

We're sorry, but we can't find what you're looking for.

The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

    If you typed in the address, please double check the spelling.
    If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

Or you can just jump over to some of the popular pages on our website.

    Are you interested in a list of featured add-ons?
    Do you want to search for add-ons? You may go to the search page or just use the search field above.
    If you prefer to start over, just go to the add-ons front page.

I would like to ask is there any other way to do it.
Thank you

**Comment by diox** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy and hasn't been updated in a long time. This causes the add-on to be considered incomplete, and that's why you're seeing the error. 

Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.
