### ISSUE TITLE
Split integration tests per CI build type.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#10207]
As we add more tests we add more run time. It would be a good idea to run a different amount of tests per build type on circleci so they run a bit faster.

commit: 20-30 - Devhub, upload/install, search
Master merge: 50-60 - Devhub, upload/install, search, General UI
Tag: All

Thoughts?

**Comment by EnTeQuAk** [comment]
I think we have other parts that take much more time, e.g the whole setup part and especially calling `update_permissions_from_mc` takes forever.

But, running different tests for different scenarios sounds okay for me too, we generally should run all (relevant) tests during a pull request, since that's where changes happen.

**Comment by jrbenny35** [comment]
Any thoughts on how to speed those tasks up?

**Comment by eviljeff** [comment]
Do we need `update_permissions_from_mc` for the UI tests?

**Comment by EnTeQuAk** [comment]
So, with #10371 being merged this may have gotten a few moments faster. 

> Do we need update_permissions_from_mc for the UI tests?

I don't think it's actually needed at the moment since none of the ui-tests is testing actual permission description anywhere from what I see. We should be safe to simply remove that call and see how it goes, document that properly. I think tat alone will speed up circleci tests by at least 1-2 minutes.

@jrbenny35 do you have the time to look into that?

**Comment by eviljeff** [comment]
also, just filed #10389

**Comment by jrbenny35** [comment]
I can take a look at that for sure.
