### ISSUE TITLE
"Save changes" button should not be displayed for static theme's "Manage Version" page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#10219]
Followup for https://github.com/mozilla/addons-server/issues/10189

STR:
1. Load AMO Dev and go to "Manage Version" page of a submitted static theme by clicking one of it's versions
2. Observe the page 

Expected result:
Page cannot be edited so it has a "Return to versions" button.

Actual result:
The page displays "Save changes" and "Cancel".

Notes:
This is reproducible for static themes on AMO dev and AMO stage with FF64 (Win10). 

![return to versions](https://user-images.githubusercontent.com/33448286/49993767-430b7d00-ff90-11e8-8a01-1889beaf1010.gif)

**Comment by caitmuenster** [comment]
Hey @diox, can you describe a little bit about how to fix this bug?

**Comment by diox** [comment]
The template for this page should no longer include the save button if the add-on is a static theme. It's a matter of adding the right condition to the right template, and checking that it works locally with a static theme.

**Comment by junngo** [comment]
@diox 
I wanna be checked to understand this Issue.
Functionally, I think it's already working properly [1].

This Issue is that when I click "Save changes Button", It should move to "Version Page" such as "Cancel Button"?
So It can be fixed simply by modifying it here[2]  by returning "versions page" as follows:
`return redirect(addon.get_dev_url('versions'), addon_id, addon)`

Please make sure I understand correctly.

[1]
https://github.com/mozilla/addons-server/blob/fec112e132b6d37a3f1bf74e774d813ed3e8fff1/src/olympia/devhub/templates/devhub/versions/edit.html#L138

[2]
https://github.com/mozilla/addons-server/blob/fec112e132b6d37a3f1bf74e774d813ed3e8fff1/src/olympia/devhub/views.py#L1069

**Comment by diox** [comment]
It's much more simple than that. You don't need to modify the behavior of the button, you just need to omit the button entirely from the template if the add-on is a static theme - because there is nothing to actually change on this page for static themes. (You can keep the "Cancel" button, it's useful to get back to the page with the list of versions)

**Comment by junngo** [comment]
I submitted PR to solve this issue :)

The gist of the above matter is different.
Please refer to this.
When I solved this Issue, I found problem locally.
I wanna make theme to reproduce this issue. So I try to make theme by clicking button[0].
I met foreign key error.
![foreign key error](https://user-images.githubusercontent.com/29684524/67096653-945d4c00-f1f3-11e9-8f00-da27bad86505.gif)

**Screenshot**
![foreign key](https://user-images.githubusercontent.com/29684524/67095749-a8a04980-f1f1-11e9-9ad0-3c227e1a6f32.png)

I checked the data in database.
When  adding data to 'addons_categories' table, There is no data[0] on the 'categories' table.
I'm not sure, but please refer to the content.

[0]
https://github.com/mozilla/addons-server/blob/38e2ae2a1739a0f256668982983837c26af577aa/src/olympia/devhub/forms.py#L1277

[1]
https://github.com/mozilla/addons-server/blob/38e2ae2a1739a0f256668982983837c26af577aa/src/olympia/constants/categories.py#L530

**Comment by diox** [comment]
You're missing data that should have been created when you initialized your environment. (`make initialize` step in https://addons-server.readthedocs.io/en/latest/topics/install/docker.html#setting-up-the-containers). You could try running `make populate_data` to recreate it, or reset your whole env.

**Comment by ioanarusiczki** [comment]
@diox I verified this on AMO dev with FF69(Win10) and the "Save Changes" button is no longer available. 

![Cancel](https://user-images.githubusercontent.com/33448286/67217166-fc4aa700-f42c-11e9-833c-20a99edeae40.gif)
