### ISSUE TITLE
Privacy Policy vanishes when editing description

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#10229]
### Describe the problem and steps to reproduce it:

The cliqz add-on's privacy policy vanished a few times. They managed to reproduce the behavior.

1) Go to https://addons.mozilla.org/en-US/developers/addon/cliqz/edit
2) Click Edit in the "Describe Add-on" section, then Save
3) Head over to https://addons.mozilla.org/en-US/developers/addon/cliqz/ownership and see the privacy policy is missing

### What happened?
* The "This add-on has a Privacy Policy" checkbox gets unchecked
* The privacy policy is hence no longer available

### What did you expect to happen?
The privacy policy continues to exist after editing the description

### Anything else we should know?
The default language of the add-on is German, and there are various localized fields. Maybe this is relevant. Thanks @luciancor for the report. @diox, Andreas mentioned this to you so maybe you are a good person to look into this?

**Comment by diox** [comment]
Looks like this is not even tied to translations, I can reproduce. The [`DescribeForm`](https://github.com/mozilla/addons-server/blob/99de54c2e49b976d8b46a4a96d87239500462991/src/olympia/devhub/forms.py#L607-L657) is weird, and does contain code that deletes the privacy policy under some circumstances. I suppose it's because it handles both creation and edition, and the field is not present during edition. Something is the handling of the latter case is definitely broken.

**Comment by diox** [comment]
This behavior was added in 4b46b395060dce7a053328243fb741fb94714f25 when replacing the submission flow in #3939. I think the idea was to copy what we did in `PolicyForm`, which is deleting translations when the field is emptied. The problem is, the edition view is using `DescribeForm` but doesn't provide the field, so it's always empty, and it always delete the translation.

Removing that logic doesn't break any tests, but I think it breaks an edge case when you submit or resume submission, somehow had a privacy policy set on the add-on already, and want to remove it. The better fix is probably going to be either:
- a) Handling the case where the field is not present at all in the changed data (indicating we shouldn't try to delete the translation)
- b) Adding the `has_priv` field in the edit form HTML as a hidden field.

**Comment by diox** [comment]
I've experimented with the possible solutions:
* a) Doesn't work, because as far as Django is concerned, the field is in the form - so even if it's not submitted, `has_priv` ends up in `changed_data`! 
* b) Doesn't seem to work either, we would also need the privacy policy itself to be present I think.

That leaves c) ... the different forms are already a bit of a mess, but it should be the cleanest solution...

**Comment by diox** [comment]
A fix should land on dev shortly, it'll be deployed during our next push on January 10th.

**Comment by ioanarusiczki** [comment]
@diox 
Indeed, the issue was reproducible on AMO stage (with FF64, Win10).  If "Save changes" button from "Describe Add-on" section is clicked and then I go to "Manage Authors & License" the Privacy Policy will no longer be available and the box is unchecked. Also, the Product Page will no longer display the Privacy Policy in the "More information" section. 
I verified this scenario on AMO dev (FF64, Win10) and the issue is no longer reproducible.
 I also tried to reproduce it by editing and then clicking the "Save changes" button with other sections from Edit product page, and the Manage Version page but it is not reproducible. 

AMO stage 

![amo stage privacy policy gone](https://user-images.githubusercontent.com/33448286/50482582-fd1ed200-09ef-11e9-877a-a55003c3ae7f.gif)

AMO dev - issue is fixed

![amo dev privacy policy available](https://user-images.githubusercontent.com/33448286/50482589-0a3bc100-09f0-11e9-8ad5-58cbe6d5f9d9.gif)
