### ISSUE TITLE
stop using username as a fallback when display_name isn't set

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10261]
part of #8302

**Comment by AlexandraMoga** [comment]
I wasn't able to verify this on the frontend because the display name field was made mandatory by #10265. 

I used instead the edit profile api endpoint to set a custom `username` and then I verified that the display name didn't fallback to the `username` set via the api.

![image](https://user-images.githubusercontent.com/31961530/50679547-8e9fcc80-100c-11e9-9db7-26593c2c5638.png)

The display name will remain the generic `Firefox user <userId>`

I'm marking the issue as verified fixed on AMO -dev.
