### ISSUE TITLE
drop username edit support from the API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10267]
part of #8302 - dependant on (mozilla/addons-frontend#7166)

**Comment by AlexandraMoga** [comment]
If I'm trying to update my `username` through the [PATCH accounts endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#patch--api-v4-accounts-account-(int-user_id|string-username)-), I receive a 200 response and the `username` field remains unchanged - i.e. the update has no effect.

@eviljeff  If this is the expected behavior, I can mark this issue as verified fixed.
