### ISSUE TITLE
Doplněk S3 translator nejde najit.

### ISSUE THREAD

**Issue by m-mars** [mozilla/addons-server#10277]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
This is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.
