### ISSUE TITLE
Implement files/compare API

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10323]
Follow-up from #10322 which should implement the API related to comparing two different versions of the same add-on.

**Comment by kumar303** [comment]
We would like to have some kind of field like `validation_json_url` so that we can fetch and display linter messages for the new version in the compare view. Here's an example of viewing linter messages in the compare view: https://reviewers.addons-dev.allizom.org/en-US/firefox/files/compare/255464...255463/

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with the new [compare files api](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-compare_to-(int-version_id)-)

- I've compared several versions to make sure that changes between files are captured correctly
- I've made sure that the compared files are listening to the `file` parameter sent
- I've checked that only users with appropriate permissions can retrieve results (i.e users without unlisted review access can't use the compare endpoint for unlisted addon versions)


I suppose there are many more validations to be run, but at a first check this api is looking good to me.
