### ISSUE TITLE
The trending themes section lists only LWT results in the first 40 pages

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10382]
STR:

1. Go to Themes homepage on AMO stage
2. Check the Trending section - https://addons.allizom.org/en-US/firefox/search/?sort=hotness&type=statictheme%2Cpersona

Actual result:
The first 40 pages contain only LWT

Expected result:
The first pages in the trending section should display migrated themes as well

Notes:
- reproduced on AMO stage with FF64, WIn10x64
- could be a consequence of https://github.com/mozilla/addons-server/pull/9764

**Comment by diox** [comment]
Debugging issues related to trending on dev & stage is always a complicated topic, because of the following:
- It takes 3 weeks of data for a non-lwt to become trending
- LWT compute stats differently from regular add-ons
- Dev & stage stats are always super low/unreliable because not many users visit them, and the code to sort by trending assumes hotness is > 0 for enough add-ons

**Comment by diox** [comment]
Ultimately, like most issues related to stats on dev/stage, I think the only solution will be to inject fake data/simulate fake downloads&update pings to get enough data. But this problem should be specific to dev&stage.

**Comment by eviljeff** [comment]
if this only related to dev and stage I'm going to close this as there won't be any LWT soon and its (realistically) not going to be fixed before then.
