### ISSUE TITLE
Addons installed on firefox for Android are not always able to update. 

### ISSUE THREAD

**Issue by creesch** [mozilla/addons-server#10395]
This is likely related to this frontend issue. 

https://github.com/mozilla/addons-frontend/issues/6136

### Describe the problem and steps to reproduce it:
The AMO frontend allows all webextensions to be installed regardless of them being marked compatible with Firefox for Android or not. 

### What happened?
This results in extensions that installed but not updated. Likely due to the backend through the update URL does not allow Firefox for Android to request incompatible extensions. (This is pure conjecture as I don't know how to properly check this). 

### What did you expect to happen?
I expect extensions to update as they are installed. Not having them update seems like a potential security issue in the making. 
Ideally they should not be installed but that did happen and I can only assume that it did happen with a lot of people due to how easy it is to install incompatible addons from AMO. As that is the case you don't want all those addons being blocked from updating. 

### Anything else we should know?
I first thought this was a Firefox for Android issue but got redirected [from this bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1519725) to here.

**Comment by eviljeff** [comment]
I guess a duplicate of #10398 - they both reference the same bugzilla issue

**Comment by creesch** [comment]
Sorry but no, they are related but not the same issue. The one you linked was originally also made by me but moved by willdurand.

I think that if you are able to install an addon in the first place that you should be able to update it from the same place.

**Comment by eviljeff** [comment]
Sounds like you're right - it's not a duplicate.  As per mozilla/addons-frontend#6136 ideally AMO shouldn't allow the extensions to installed the in first place because they won't work (or at least warn about it).

There's not really a fix possible here though - the update service purposely won't offer an update to Android users because it knows the new version isn't marked compatible with Android (for the scenario when an add-on might start out supporting Android for one version and then drop support in a later version).
