### ISSUE TITLE
Make python3 fixes for "amo-locales-and-signing" job

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10423]
Python 3 fixes for https://travis-ci.org/mozilla/addons-server/jobs/480441084

**Comment by diox** [comment]
In #10525 I've added this FIXME to `src/olympia/lib/crypto/tests/test_signing.py` that it'd be nice to implement as part of this issue:
```
# FIXME: need to add a test with a unicode filename inside the package
# itself, and then check the signature.
```

**Comment by diox** [comment]
Note that the job is now called `amo-lib-locales-and-signing`.

**Comment by eviljeff** [comment]
The only remaining fails in this job are in test_middleware.py - `test_source_with_wrong_unicode_get` and `test_trailing_slash_middleware`.  They're both caused by `safe_query_string` (`iri_to_uri` really) encoding special characters in the query string as two escaped characters rather than one in python2.  

I haven't yet conclusively determine which is "correct" but receiving a single character in the query string and redirecting it with two seems wrong.

If this isn't an easy fix then we could mark skipif and have all the jobs be passing under python3 (then look at the skips)

**Comment by AlexandraMoga** [comment]
Please add a qa:not needed label if there is no QA required.
Thanks
