### ISSUE TITLE
Reviewers/Browse API: Expose all related versions

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10432]
https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#browse Exposes details for a specific version but for the addons-code-manager to properly implement the version-selector we'll have to expose a list of versions that the user can diff against.

Refs https://github.com/mozilla/addons-code-manager/issues/39

**Comment by AlexandraMoga** [comment]
@EnTeQuAk I've noticed you've made some changes to the reviewers browse endpoints, namely there are two separate endpoints now (unless I haven't noticed them before):

[GET /api/v4/reviewers/addon/(int: addon_id)/versions/](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-) - for exposing a list of available add-on versions (based on user perms)

[GET /api/v4/reviewers/addon/(int: addon_id)/versions/(int: version_id)/](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-) - which is the former `/reviewers/browse/` api.  There is one behavior that needs to be clarified with regards to this endpoint, for which I filed #10731

If I'm not mistaken, the main purpose of this issue was to have a version listing endpoint, for which you implemented the [GET /api/v4/reviewers/addon/(int: addon_id)/versions/](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-)

These are the tests I've run against this endpoint:

`/api/v4/reviewers/addon/494866/versions/`
- authenticate with user that has all the available reviewer permissions => all versions, listed or unlisted, are retrieved 
- authenticate with user that has "Addons:PostReview" permissions => only listed versions are retrieved 
- authenticate with user that has no special permissions => a 403 error is returned

If there’s anything else that needs to be covered, please let me know.

**Comment by EnTeQuAk** [comment]
> If there’s anything else that needs to be covered, please let me know.

That's perfect and should cover all relevant scenarios. Thanks a lot!
