### ISSUE TITLE
The authentication dance uses a v3 endpoint (even when v4 is used at the beginning)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#10487]
When trying to log in a user (for addons-code-manager but also addons-frontend), after the FxA page, a `v3` API endpoint is used instead of `v4`:

![screen shot 2019-01-22 at 17 33 55](https://user-images.githubusercontent.com/217628/51550198-30784380-1e6c-11e9-9ba0-be9a66b4b5c0.png)

~~I don't really know why component creates this URL though, FxA maybe?~~

The URL comes from the response to an XHR call to https://oauth-stable.dev.lcip.org/v1/authorization:

```
{"code":"xxxx","state":"yyy8261:Lw","redirect":"http://localhost:3000/api/v3/accounts/authenticate/?config=local&state=yyy%3ALw&code=xxx"}
```

**Comment by eviljeff** [comment]
the redirect urls are fixed* in the fxa oauth clients so we'll need to create new ones that reference the /v4/ API endpoints

*we also mention them in addons-server [code](https://github.com/mozilla/addons-server/blob/master/src/olympia/conf/prod/settings.py#L100) but it's not actually used by fxa, only the one defined in the oauth client.

**Comment by EnTeQuAk** [comment]
> *we also mention them in addons-server code but it's not actually used by fxa, only the one defined in the oauth client.

Are you sure? At least we are also forwarding the redirect-url to fxa. Which we'll need to fix this issue because we have to dynamically redirect to v4 or v3 according to what the client wants.

**Comment by eviljeff** [comment]
okay, technically it's an optional param and is recognised by FxA (https://github.com/mozilla/fxa-auth-server/blob/master/fxa-oauth-server/docs/api.md#get-v1authorization) but "Must match URL from registration." so we can't just change it on the addons-server side because then it won't match the one registered with FxA.

**Comment by EnTeQuAk** [comment]
> so we can't just change it on the addons-server side because then it won't match the one registered with FxA.

True, but weren't we able to register multiple urls? Maybe I'm remembering wrong

**Comment by eviljeff** [comment]
we can have multiple oauth clients (we do already for the different configs).  Do we _need_ to though?  The only API clients that can use FxA auth are addons-frontend and addons-server and they're both v4 only.

**Comment by eviljeff** [comment]
we need this for #11273

**Comment by eviljeff** [comment]
We have a total of 15 clients (key+secret) which reference `api/v3` currently - because we pass on the config used as a config=xxx param there is separate url defined for each config (there are 4 configs each for local, dev, stage, plus 3 for prod).  To change them all to `api/v4` we need to create and define in settings files 15 new clients.  (If we want to return the matching api for every supported api version, we need a further 15 for `api/v5` also.  And so on for future api versions)

If we change the config name to be defined within the state string instead then we can reduce the different urls to 6:
- addons.mozilla.org/api/v4/accounts/authenticate
- addons.allizom.org/api/v4/accounts/authenticate
- addons-dev.allizom.org/api/v4/accounts/authenticate
- olympia.test/api/v4/accounts/authenticate  (?config=default for local dev)
- localhost:3000/api/v4/accounts/authenticate  (?config=local for local dev)
- localhost:3000/fxa-authenticate  (?config=amo for local dev)

It's possible local dev addons-frontend no longer requires the last 2 but, iirc, did last time I checked.

The only solution to not requiring new clients for each api version is a special version-less api endpoint (possibly only used for this auth callback).  There may be a future circumstance where we _want_ to version that api though.

**Comment by eviljeff** [comment]
@willdurand do you know if all the configs are used by frontend still?  ('amo', 'local', in addition to 'default')  I'm not clear why code-manager needed a specific config ('code-manager') either.

@EnTeQuAk @diox  any objections/comments on encoding the config name within the `state` param or creating a version-less api endpoint?  I'm not entirely convinced on the merits of doing either tbh.

Note the `/authenticate` api endpoint is _only_ called by FxA as the callback - addons-server doesn't use it internally nor does addons-frontend.

**Comment by EnTeQuAk** [comment]
Even though it's hard to imagine, versioning the `/authenticate` endpoint will only be useful in case fxa implements a breaking change and at the same time grandfathers existing configs and only calls new ones with that change (whatever it is…). Imo that would be the only scenario that makes versioning the endpoint useful :thinking:

I'm unsure how likely that is, but it certainly hasn't happened in the past and won't be happening as much as we're increasing our api versions anyway, so I wouldn't be too concerned about not versioning that particular endpoint. I'd rename it to `/fxa-authenticate-callback` maybe though, to make it clearer that that's it's sole purpose.

Regarding adding it to the state… I'm not sure I understand all the implications. The state is used to ensure that the login has been invoked by the same client that ended up with on the redirect link, e.g to avoid man-in-the-middle hacks afaik. Now, currently it would technically work (certainly not ootb, I think, correct me if I'm wrong) that you could initiate a login from within addons-server and end up being redirected to code-manager and are logged in properly. Unless I'm misunderstanding, that won't be easily possible if we bind the config to the state. Would that be a problem? I personally doubt it but it'd be worth considering - assuming I understood the whole thing right.

**Comment by eviljeff** [comment]
>Regarding adding it to the state… I'm not sure I understand all the implications. The state is used to ensure that the login has been invoked by the same client that ended up with on the redirect link, e.g to avoid man-in-the-middle hacks afaik. Now, currently it would technically work (certainly not ootb, I think, correct me if I'm wrong) that you could initiate a login from within addons-server and end up being redirected to code-manager and are logged in properly. Unless I'm misunderstanding, that won't be easily possible if we bind the config to the state. Would that be a problem? I personally doubt it but it'd be worth considering - assuming I understood the whole thing right.

Anything we do currently should still be possible - it'll just be replacing the ?config=xxx param.
Currently it works like this for a frontend call:
- frontend call to `api/v3/login/start?to=path/to/wherever` which builds the fxa_url needed and redirects to it.  
  - The fxa_url built includes the addons-server callback url (`'redirect_url'` in the addons-server FXA_CONFIG), and the state which includes the `?to=` GET param which is the client redirect url.
  - the addons-server callback url also includes a `?config=xxx` param on the end - which is why we need different fxa client ids for each config.
  - (if not a frontend call the only difference is we don't need the api call to `/api/v3/login` - the url can be redirected to directly or included in the template html for js redirects)
- fxa, after it's completed the auth, redirects to the addons-server callback url `/api/v3/authenticate/?config=xxx`.
- The `/api/v3/authenticate/` endpoint uses the `?config=xxx` param to select the correct config.  At this point the only difference between the configs on a single instance of AMO is whether skip_redirects is True or False.   Then we either redirect to the client redirect url or, if it's a registration and skip_redirects is False, the edit account profile page on frontend.

So, if we encode the config in the state we don't need separate fxa client ids because the urls won't change.  Although at that point the only difference is whether we redirect users to the edit profile page... something I'm not sure we need anyway because it was originally implemented when addons-frontend was mobile only and we'd not gotten around to implementing the edit page.  🤔 Dropping the feature of _not_ redirecting new users to set their account details on new registration would be the easy fix here.

**Comment by willdurand** [comment]
> @willdurand do you know if all the configs are used by frontend still? ('amo', 'local', in addition to 'default') 

- `local` is used by code-manager and addons-frontend for local dev
- `amo` is used by the frontend, that's the main config for all the hosted envs
- `default` seems to be related to the "uitests" env, so ping @jrbenny35 

> I'm not clear why code-manager needed a specific config ('code-manager') either.

Could it because of the redirect URLs?

**Comment by eviljeff** [comment]
> default seems to be related to the "uitests" env

`default` is the default, used everywhere else the `config=` isn't specified :)  I knew why what one was needed.

>> I'm not clear why code-manager needed a specific config ('code-manager') either.
> Could it because of the redirect URLs?

The redirect URLs are the same (v3 and v4 are functionally the same for this endpoint)

**Comment by willdurand** [comment]
> `default` is the default, used everywhere else the `config=` isn't specified :) I knew why what one was needed.

That was in the context of addons-frontend only, sorry :)

> The redirect URLs are the same (v3 and v4 are functionally the same for this endpoint)

Ok. #e also need a client id/secret pair for each service, so that's why we have `code-manager`.

**Comment by eviljeff** [comment]
> We also need a client id/secret pair for each service, so that's why we have code-manager.

After re-reading through #11015 and the linked issues I'm none the wiser _why_, exactly - why not use `default`.  But this isn't an important aspect of this issue so I'll leave that discussion to another day/issue.

**Comment by eviljeff** [comment]
QA: marking this as extra only because it needs to be verified twice - once before ops have added new fxa details, and once after.  I'll ask ops once you indicate the pass has been done.

Nothing complicated for STR - just login and logout as normal and check the site works.  

If you watch the network panel in the developer tools (like the screenshot in the issue description):
- Before ops have added new fxa clients: the api will be `/api/v4/accounts/login/start` to start and `/api/v3/accounts/authenticate` at the end.
- After ops have added new fxa clients: the api will be `/api/v4/accounts/login/start` to start and `/api/auth/authenticate-callback` at the end.

**Comment by ioanarusiczki** [comment]
@eviljeff I tested step one (before ops changes) on AMO dev with FF69(Win10) and I get:

/api/v4/accounts/login/start to start and /api/v3/accounts/authenticate at the end 

![works for me](https://user-images.githubusercontent.com/33448286/66758628-51c00a80-eea7-11e9-94af-9eb90423295b.gif)

Let me know when I can check step two. 
Thanks

**Comment by eviljeff** [comment]
@ioanarusiczki ops have replaced the addons-dev fxa client details, so addons-dev can be checked again.

**Comment by ioanarusiczki** [comment]
@eviljeff on -dev I still see `/api/v3/accounts/authenticate` at the end. 
I tried with 2 accounts, old and new one. 

![authenticate-callback](https://user-images.githubusercontent.com/33448286/66905377-6b2f9680-f00e-11e9-89c6-ae597d72d22d.png)

**Comment by ioanarusiczki** [comment]
@eviljeff Re-testing this for https://github.com/mozilla/addons-frontend/issues/8666 I've noticed now that:

Using the frontend: there is a `/api/v4/accounts/login/start` to start and `/api/auth/authenticate-callback` at the end.

Register from dev hub : `https://oauth-stable.dev.lcip.org/v1/authorization?` at start (I don't see the  /api/v4/accounts/login/start) and `/api/auth/authenticate-callback` at the end.

From code manager: `https://addons-dev.allizom.org/api/v5/accounts/login/start/` at start and `/api/auth/authenticate-callback` at the end.

![the callback](https://user-images.githubusercontent.com/33448286/66919582-434e2c00-f02a-11e9-9a27-10bbd1b73c24.png)

**Comment by eviljeff** [comment]
@ioanarusiczki addons-server needed a redeploy before, after ops added the new keys.  (I merged something earlier to trigger that but forgot to notify you)
