### ISSUE TITLE
Notify of a readonly mode in the API

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1050]
There is a READ_ONLY setting in the settings file. It looks like this on the site:

https://www.dropbox.com/s/9fd38ipi14ixynt/Screenshot%202015-12-04%2011.54.39.png?dl=0

I think we should also do something similar in the API. If there's a POST, PUT, DELETE return a 503 maybe? Would be nice to get in for our projected read-only mode on Tuesday.

**Comment by andymckay-limited-access** [comment]
This is done.

**Comment by mstriemer** [comment]
I think it would be good to come up with a more generic solution than what I did for this. My change requires adding a decorator to each endpoint that modifies the database.

**Comment by muffinresearch** [comment]
Relates to #3610

**Comment by EnTeQuAk** [comment]
This becomes much more important with #8923 and related database related changes that are required.

**Comment by EnTeQuAk** [comment]
cc @diox @kumar303 and @willdurand for a quick discussion on how this should be exposed to addons-frontend. 

The expectation here is that addons-server forbids for the amount of time where we set read-only mode any requests that are POST, PUT or DELETE. Legacy views and Devhub already handle this properly but we need the addons-frontend to be aware of that.

So it seems that returning a [503 - Service Unavailable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) is the way to go here and is what AMO already does in case of `POST` requests and `READ_ONLY` set.

I'm very open to set any additional header to make the frontend aware that this is indeed just the read-only mode and maybe send this with every GET request too temporarily so that we can show something to the user when they open any kind of form. Something like `X-AMO-Read-Only: True` or whatever works.

Any opinions about that?

**Comment by diox** [comment]
Note that a consequence of this is that we should prevent logins. Existing sessions are technically not affected, but it's probably a good thing to disallow them as well... Oh, and we should make sure devhub / reviewer tools also support this.

A 503 for write requests sound good, but we'll definitely need an extra header or something to let the frontend know so that it doesn't do the requests in the first place.

**Comment by kumar303** [comment]
A 503 should work. I suggest adding a custom `code` to the response similar [to these ones](http://addons-server.readthedocs.io/en/latest/topics/api/overview.html#unauthorized-and-permission-denied).

As soon as the frontend gets a 503 with the right error code, it could display a read-only notice at the top of the site with a *try again later* message or something.

**Comment by diox** [comment]
If we added a custom header to all responses, then as soon as the frontend receives a response indicating that the read only mode is over, it could switch back to normal mode ?

**Comment by kumar303** [comment]
> If we added a custom header to all responses

I'm not sure how that would be any different than returning a 503. 

> ...then as soon as the frontend receives a response indicating that the read only mode is over, it could switch back to normal mode ?

Were you envisioning that we would poll one of the endpoints to know when to switch back to normal? 😀

**Comment by kumar303** [comment]
Oh, duh, I get it now. The POST/PUT/etc responses would return 503s but the GET responses would return a custom header that we could look at to know if the site was back to write mode. Yes, that should be easy enough to deal with.

**Comment by willdurand** [comment]
I'd like to have a `503` along with a [`Retry-After` header](https://pretty-rfc.herokuapp.com/RFC2616#header.retry-after) to comply with the HTTP spec.

**Comment by EnTeQuAk** [comment]
> I'd like to have a 503 along with a Retry-After header to comply with the HTTP spec.

Well, `Retry-After` is not required per spec and we may not have a reasonable specifier when a downtime is supposed to be done so I'm unsure we actually want that. Randomly adding 5 minutes or so kinda feels wrong or how would you use it?

**Comment by EnTeQuAk** [comment]
We can make it configurable though to add an anticipated end of maintainance via another setting, if ops can provide this we can expose it I suppose.

**Comment by EnTeQuAk** [comment]
I must have messed up the merge, fixed in https://github.com/mozilla/addons-server/pull/9153

**Comment by willdurand** [comment]
I wish I could have posted this link before but we should not really use X- anymore: https://tools.ietf.org/html/rfc6648

**Comment by kumar303** [comment]
Thanks, Chris. Can you add documentation for this in a follow-up patch? I think a good place for it would be after the [error code section](http://addons-server.readthedocs.io/en/latest/topics/api/overview.html#unauthorized-and-permission-denied).

**Comment by EnTeQuAk** [comment]
> I wish I could have posted this link before but we should not really use X- anymore in header names: tools.ietf.org/html/rfc6648

True, I keep forgetting about that. Then maybe we should just use `AMO-Read-Only-Mode` in the future, but that's more of a cleanup I guess and shouldn't block moving forward.

> Thanks, Chris. Can you add documentation for this in a follow-up patch? I think a good place for it would be after the error code section.

Yes, I'm on it! I added some steps to the addons-frontend issue but I'll add more official docs too.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk could you please add some steps that could help with testing this implementation? 
Thank you
