### ISSUE TITLE
Double-check and fix tests that we skipped in Python 3

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10527]
We are making some tests as expected failures or skipped entirely for Python 3. Once all test jobs pass we should revisit those, some need to be fixed, some should be ok because the test no longer makes sense in python 3 but it still needs to be double checked.

**Comment by diox** [comment]
Also worth looking for FIXMEs/TODOs that may be relevant for Python 3.

**Comment by eviljeff** [comment]
There are the 5 skipif for PY3:

The middleware tests are maybe (probably) just down to differences in how urls are encoded/decoded in py3:
https://github.com/mozilla/addons-server/tree/master/src/olympia/amo/tests/test_middleware.py#L83
https://github.com/mozilla/addons-server/tree/master/src/olympia/amo/tests/test_middleware.py#L94

The zip file not failing is probably just due to improved zip file handling
https://github.com/mozilla/addons-server/tree/master/src/olympia/files/tests/test_file_viewer.py#L489

The version test failures have no obvious explanation
https://github.com/mozilla/addons-server/tree/master/src/olympia/versions/tests/test_views.py#L510
https://github.com/mozilla/addons-server/tree/master/src/olympia/versions/tests/test_views.py#L539

**Comment by eviljeff** [comment]
filed #10658 for the version test fails.
