### ISSUE TITLE
Developer unable to update description of extension

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#10559]
The BotBlocker developer team just [reported](https://reviewers.addons.mozilla.org/en-US/reviewers/review-listed/iambotblocker) that they are not able to update the description of their extension. They have attached the following gif: 

https://raw.githubusercontent.com/botblocker/img/master/problem.gif

Is this a known issue?

**Comment by AlexandraMoga** [comment]
I did not find an issue logged for this use case.

Several conditions have to be met in order to be triggered (this is the only way I was able to reproduce it at least).

Here are my steps (hope they make sense):

1. Submit a non-localized addon (package doesn't have a `_locales` folder)
2. Make sure that the addon distribution page is set to a locale different than `en-US` - i.e. https://addons.allizom.org/bs/developers/addon/submit/upload-listed
3. Once your addon is submitted, check the Localization menu from the Edit information page in DevHub - notice that your default locale is `bs` (Bosanski)
4. Change the URL locale for the Edit information page - i.e. https://addons.allizom.org/en-US/developers/addon/botblockerlocale/edit
5. Try to add an additional locale via the Localization menu, say `en-US`, and Save changes **without** actually updating the Description field
6. Switch back to the default locale in the Localization field
7. Try to update the Description => Note that it will be _None_ after changes are saved

![2019-02-01_10-46-32](https://user-images.githubusercontent.com/31961530/52112646-c439d480-260f-11e9-947c-0fbff37d56d2.gif)

@caitmuenster there is a workaround to solving this issue if the developers make sure that when they are trying to edit the description of their addon, the Edit information page is set to the same locale as the default locale - i.e. if the submission was made in `bs`, the Edit information link should point to https://addons.mozilla.org/bs/developers/addon/botblocker/edit

**Comment by botblocker** [comment]
Basically, if you add an additional locale, same as URL locale, and save without any change, description for all addon locales become "none" with that URL local.

Example:
1. Edit addon with `de` URL locale ( for example )
2. Add the same local as additional locale via the Localization menu ( `Deutsch - de` )
3. Edit addon and save without any changes in the fields

We fix our issue with a workaround that @AlexandraMoga described.

**Comment by caitmuenster** [comment]
Thank you so much, @AlexandraMoga!
