### ISSUE TITLE
Redirect /developers/ to the extension workshop

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#10612]
The extension workshop is planned to supercede the devhub landing page that you see when visiting  https://addons.mozilla.org/en-US/developers/

We would like to redirect https://addons.mozilla.org/en-US/developers/ to the extension workshop. Currently this page is different whether you are logged in or out. Since the extension workshop will link directly to https://addons.mozilla.org/en-US/developers/addons (which forces a login) I think we can safely make /developers/ a redirect to https://extensionworkshop.com/ and delete the existing logged-in/logged-out views.

This should be behind a flag.

_Note the extension workshop doesn't have localizations currently so we might want to wait until it does._

**Comment by EnTeQuAk** [comment]
I actually wonder why this is a separate site instead of replacing addons.mozilla.org/developers/ directly? SEO purposes?

**Comment by eviljeff** [comment]
Is there an addons-frontend issue to link to extensionworkshop.com in the menu there rather than a.m.o/developers?

**Comment by caitmuenster** [comment]
@EnTeQuAk We looked into that, and unfortunately, it just doesn't look feasible at this time. Some of the issues that were raised included integration with AMO and ongoing maintenance overhead by the AMO team. (We don't want ya'll to add this to your already full plates!) 

@eviljeff as far as I know, no issue has been filed to the frontend repo to change the menu, but we'll need to do that as well.

**Comment by eviljeff** [comment]
> as far as I know, no issue has been filed to the frontend repo to change the menu, but we'll need to do that as well.

I think we're doing this the wrong way around - redirects are supposed to be to cover old bookmarks/links - first priority should be changing links within the site (both addons-server and addons-frontend)

**Comment by eviljeff** [comment]
Some further thoughts on this - from a user experience perspective alone, having a flow where a logged in user would go from AMO (addons-frontend), to basically a 3rd party site (extensionworkshop.com), back to AMO again (addons-server) for their submissions seems (to me to be) entirely the opposite of improving the developer experience for an existing developer.  Each time the user clicked on the "Add-on Developer Hub" header in any edit addon screen they'd be going to a different website that doesn't know anything them as a user, and then having to go back again.

I've heard the site is static content (though never actually seen it) - can we spend some time evaluating how much work it would be to port to addons-frontend or addons-server first rather than pushing ahead?

**Comment by muffinresearch** [comment]
> I actually wonder why this is a separate site instead of replacing addons.mozilla.org/developers/ directly? SEO purposes?

Security was the original reason, since AMO engineering wasn't going to be involved in building it out.

**Comment by muffinresearch** [comment]
Closing this as wontfix since we're going to go a different route.
