### ISSUE TITLE
Add-on icon is missing from the Recent Activity feed 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10623]
STR:
1. Log in to AMO stage with a developer account
2. Go to https://addons.allizom.org/en-US/developers/feed

Actual result:
There is no icon - custom or default - next to the addon activity

Expected result:
Add-on icon is displayed

Notes:
**Edit:**  the icon is displayed if you select a specific addon activity - https://addons.allizom.org/en-US/developers/feed/teamweek-button

Reproduced on all AMO servers with FF65, Win10x64

![image](https://user-images.githubusercontent.com/31961530/52403927-85ed5b00-2ad0-11e9-812e-a98ebae40b21.png)

**Comment by diox** [comment]
I was hoping this could be a good first bug, so I researched this a bit but it's not trivial to fix in a clean way.

We pass `addons` and a `pager` of `ActivityLog` items to the template. That template then loops on each item in the pager to do this:
https://github.com/mozilla/addons-server/blob/ff58ed60353e9891ab134a93c18ad22f3b40ebbb/src/olympia/devhub/templates/devhub/addons/activity.html#L27-L27

So if there is no `addon`, we get an empty icon. There is no single `addon` here because this is a global feed of multiple add-ons. Ideally we could easily get the add-on for each activity item but it's kinda annoying to do, it's buried in `item.addonlog_set.all()[0].addon`. 

I think the fix would involve either making `AddonLog`'s `activity_log` a `OneToOneField` - making it slightly easier to access the `AddonLog` from the `ActivityLog` - or make the view fetch and pass to the template `AddonLog` instances instead of `ActivityLog`s.
