### ISSUE TITLE
Repack static themes using deprecated (69+) properties

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10627]
See #10626 for deprecated theme properties.  Any static theme using them* will need a new version creating with a fixed manifest, containing the non-deprecated properties.  We can set the min-version of this new manifest as Firefox 59.

*includes all static themes created with the wizard since the feature was launched, plus all themes migrated from LWT, so ~500k.

**Comment by AlexandraMoga** [comment]
After verifying several repacked themes, this is what I observed:
- the manifest contains references only to the new Fx 69+ properties
- theme packages are re-signed with COSE (they can be installed and update checks are also working)
- only themes that have deprecated properties are repacked into a new version

I also have some questions/remarks:
1. Was the repacking script supposed to cover all the themes with deprecated properties? I’m asking because I've found a large number which haven’t been repacked => starting from this page for example - https://addons-dev.allizom.org/en-US/firefox/search/?page=21&platform=windows&sort=updated&type=statictheme
2. Are themes with mixed old and new properties also repacked? I have the following example which didn't receive an upgrade so far: https://addons-dev.allizom.org/en-US/developers/addon/mixed-st-properties/versions
(you can check the manifest details here: https://code.addons-dev.allizom.org/en-US/browse/616603/versions/1655475/)
3. Themes with only one digit version numbers (i.e. `"version": "3"`) will receive a `.0` in the repacked version => new version is `3.0`. For [this example](https://addons-dev.allizom.org/en-US/firefox/addon/spring-green78/versions/) if a user had `version 3` installed, he won't receive an update to `3.0`. Probably this scenario is pretty rare for prod, but we could run into it nevertheless. 
4. Only approved themes will be migrated =>before the prod migration it would be good to make sure we don't have any themes using old properties pending for review

**Comment by eviljeff** [comment]
>    Was the repacking script supposed to cover all the themes with deprecated properties?

I just ran the script on some (500) to check it was working.  There was an issue (#11218) that was fixed so I'll do some more.

>    Are themes with mixed old and new properties also repacked? 

yes.

>    Themes with only one digit version numbers (i.e. "version": "3") will receive a .0 in the repacked version => new version is 3.0. For this example if a user had version 3 installed, he won't receive an update to 3.0. Probably this scenario is pretty rare for prod, but we could run into it nevertheless.

It should be `4.0` - at least that's how the code is supposed to work.  Can you log a follow-up?

>    Only approved themes will be migrated =>before the prod migration it would be good to make sure we don't have any themes using old properties pending for review

New themes using the old properties will be able to be migrated until the linter is updated with the new manifest schema so we'll have to run it again anyway after that.

**Comment by AlexandraMoga** [comment]
I've noticed an issue with previews which is happening only on stage. I've filed #11253 for it.
