### ISSUE TITLE
run addons-dev and local dev on python3

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10639]
Stage one of the python3 upgrade is complete - tests pass.
Initial testing locally doesn't throw up any errors so it's time to have addons-dev use python3.  Stage and prod will only get python3 after a sufficiently long period of time.

**Comment by diox** [comment]
Re-opening to deal with uwsgi. It's currently installed through `apt`, so the following needs to be changed:
- In both `Dockerfile.python*.deploy`, move the `RUN uwsgi...` command until after the `RUN pip...`
- Install `uwsgi` via pip, pinning it in one of our requirements files. This should ensure the version we're installing matches the python version.
- Make sure the symlinks etc are correct

Pyup will then submit PRs when we need to upgrade uwsgi, and we'll need to be extra careful because it doesn't currently impact tests or our local envs.
