### ISSUE TITLE
Page not found displayed when the user logs out from a page served by the server

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10637]
STR:

1. Log into AMO -dev on the new frontend
2. Navigate to a page in DevHub- i.e. https://addons-dev.allizom.org/en-US/developers/addons
3. Log out

Actual result:
The user lands on the following page - https://addons-dev.allizom.org/en-US/firefox/users/logout?to=/en-US/developers/. The user state is still logged in. 

Expected result:
User is successfully logged out

Notes:
- I still believe this is a regression from #10428 
- also reproduced when logging out from any other page served by the legacy site - i.e `/reviewers/` , `/statistics/`  , `/version/<number>/`

![2019-02-08_12-13-09](https://user-images.githubusercontent.com/31961530/52472382-d8e01480-2b9b-11e9-9516-77194ed98a99.gif)

**Comment by eviljeff** [comment]
Suggestion: we move https://addons-dev.allizom.org/en-US/firefox/users/logout?to=[url] to https://addons-dev.allizom.org/en-US/developers/logout?to=[url]

**Comment by diox** [comment]
A bit hackish but I suppose it'd work. Need to be careful with https://github.com/mozilla/addons-server/issues/10612 though.

**Comment by eviljeff** [comment]
I'm assuming that subpages from /developers/ will still have to work for /addons/ etc.

**Comment by diox** [comment]
Yeah, just abundance of caution on my part :)

**Comment by AlexandraMoga** [comment]
Just double-checking that you've read the notes I've added to the issue , mentioning that this is not affecting only the /developers/ pages, but all the remaining  legacy pages.

**Comment by eviljeff** [comment]
So, we're going to move the logout view (it doesn't have any visible page - it just logs you out and redirects to another page) to `developers/logout`.  The login and register views have been removed as they're not needed - every page has a sign-in button or redirects to direct to fxa if necessary.

There's a question about the old urls though (`users/logout`, `users/login`, `users/register') - should nginx or frontend redirects be added?   `users/login`, `users/register' haven't been referenced in any template/html since FxA took over auth X years ago (though there was an edge case where we redirected to users/login if your FxA login didn't work); `users/logout` was linked to for logged in users only.

^ @jvillalobos is a nginx redirect strictly required?

**Comment by jvillalobos** [comment]
`users/login` does show some activity in GA (~9K in the last month), so there should be a redirect for it. The others don't show anything significant.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF65, Win10x64

1. Logging out from `/developers/` - user is redirected to DevHub homepage
![2019-02-18_14-54-51](https://user-images.githubusercontent.com/31961530/52953248-9edaf380-338f-11e9-8740-d5f2c9a057c8.gif)

2. Logging out from `/reviewers/`, `/statistics/` - user is redirected to AMO homepage
![2019-02-18_14-56-36](https://user-images.githubusercontent.com/31961530/52953340-df3a7180-338f-11e9-8568-214c3b1eb3d3.gif)
