### ISSUE TITLE
Upgrade to django 2.0 or 2.1 or 2.2 - planning

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10652]
ref: https://www.djangoproject.com/download/#supported-versions

We're currently on django 1.11 - a LTS release which is also the last to support python 2.7.  Once we've completed the move to python3 we can upgrade to a more recent django.  Given django 2.0 is a major release ideally we'd spend our effect on the 1.11 to 2.0 migration and then pause there for some time to iron out any bugs, before moving on to 2.1.  
Unfortunately neither 2.0 or 2.1 are LTS and 2.0 will move out of security patch support at the end of Q1 (exactly when we'd probably finish the migration to 2.0 and want take a pause).  2.1 is a little better but too it moves out of mainstream support (i.e. bug fixes) at the end of Q1, and will only get security patches for 6 months longer (so end of Q3).
2.2 _is_ a LTS - so what we'd want to move to for long term stability - but isn't released until April 2019, _after_ when we'd planned to complete the django upgrades.

Options
A) Upgrade from 1.11 to 2.0; then work on upgrading 2.1 in the remainder of Q1; then move straight into upgrading to 2.2 in Q2.  Safest but we'll be upgrading django continuously for about 2/3 months - though there is a risk that if the 2.1 upgrade takes longer than expected we'll be on 2.0 in Q2, after the security support period has ended. 
B) Skip 2.0 and upgrade straight from 1.11 to 2.1.  More risky in terms of regressions and a more difficult upgrade, but possibly less work overall.  We will still need to upgrade from 2.1 to 2.2 sometime before the end of 2019.
C) Delay the 1.11 upgrade until Q2 and upgrade from 1.11 to 2.2.  Riskiest in terms of regressions, and difficultly, but possibly the least work overall.  But we're moving the work into a potentially more busy quarter, with no obvious project we could bring forward to replace it.

**Comment by EnTeQuAk** [comment]
> 2.2 _is_ a LTS - so what we'd want to move to for long term stability - but isn't released until April 2019, _after_ when we'd planned to complete the django upgrades.

Personally, I'd favour this one. Going step by step has it's advantages but Django officially supports going directly from LTS to LTS and I'd say that at least 2.1 (and 2.2 even more) will iron out many smaller edge-cases and bugs with their 100% Python 3 migration.

Going 100% Python 3 and removing any python 2 compatibility code may take some work too.

So, personally, I'd argue that we'll able to start Upgrading to Django 2.1 during Q1 and see where we get. I don't think we'll hit many of the huge problems we faced when going from 1.6 to 1.11 (via mid-steps) because I think Django didn't completely refactor templating or orm related parts again. Still, it's quite some work, so I don't think we'll be fully able to go to 2.1 in Q1 so going 2.1 would be ideal and throwing ourselves onto 2.2 is a must for Q2 then more or less.

That way we can use the not-so-busy time in Q1 and have less work to do in Q2.

**Comment by eviljeff** [comment]
> > 2.2 _is_ a LTS - so what we'd want to move to for long term stability 

> Personally, I'd favour this one.  ... I'd argue that we'll able to start Upgrading to Django 2.1 during Q1

I suppose we _could_ start work on the upgrade with a pre-release of 2.2 (the beta is out this week, and the RC is out mid-March) with the expectation we wouldn't be finished until after 2.2 final was released.

**Comment by diox** [comment]
I'd also favor jumping directly to 2.2 - maybe by doing first what you've already started doing, fixing deprecation warnings etc, bringing us as close to compatible with 2.0 or even 2.1 without actually upgrading.

**Comment by eviljeff** [comment]
We have a decision - calling this closed then.
