### ISSUE TITLE
Searching for "crashbot" shows odd results

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10654]
### Describe the problem and steps to reproduce it:

https://addons.mozilla.org/en-US/firefox/search/?q=crashbot&type=extension

### What happened?

![screenshot_2019-02-11 search results for crashbot add-ons for firefox en-us](https://user-images.githubusercontent.com/873258/52563768-9ec47c00-2e02-11e9-988a-486ca59dd112.png)

### What did you expect to happen?

Less "Dashboard" results.

### Anything else we should know?

Does our fuzzy matcher match "dashboard" for "crashbot"?

/cc @diox

**Comment by diox** [comment]
> Does our fuzzy matcher match "dashboard" for "crashbot"?

Yes. Trigrams for `dashboard`:
`das`, `ash`, `shb`, `hbo`, `boa`, `oar`, `ard`

And for `crashbot` (the other words are also taken into account, so this is a simplification):
`cra`, `ras`, `ash`, `shb`, `hbo`, `bot`

This is worth investigating because we have a `'minimum_should_match': '66%'` rule and less than 66% match, but this is super low priority.

**Comment by jvillalobos** [comment]
Still valid, it seems.
