### ISSUE TITLE
Fix app resolving with browser_specific_settings and strict min version < 48.0

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10697]
Part of https://github.com/mozilla/addons/issues/909

And a follow-up to https://github.com/mozilla/addons-server/issues/10693

If the `browser_specific_settings` key is being used and in there, `strict_min_version` is being set to something less than `48.0`, we'll run into https://github.com/mozilla/addons-server/blob/4b1a375980ef7f7fd63076df4e2848962e8890d1/src/olympia/files/utils.py#L441-L448 which then results in this app being skipped (`skip_app`) further down the line.

We don't really remember why we're even skipping apps here so I think it might be worth exploring removing that skip-section, especially since we're actually throwing a proper error via eb620654bb23a15e75dbe24519c3379bb5aa68d6

I think throwing a warning for `browser_specific_settings` being used for Firefox versions that don't support it should be something the linter validates.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF65, Win10x64

In order to verify this, I've run the following tests. For each test, I've submitted two separate addons, one using the `browser_specific_settings` key and the other using `applications`:

1. using the extension package that failed in the original issue:  `strict_min_version` set to 42.0.
**Results**: compatibility is reflected in devhub after submission, the package is signed and the extension is installable 

https://addons-dev.allizom.org/en-US/developers/addon/bss-compatibility-low/versions/1541841
![image](https://user-images.githubusercontent.com/31961530/53087839-c4dbd180-3510-11e9-9b9d-0de6b103ef72.png)

2. extensions with `strict_min_version` set to a value < 42.0: 
 **Result**: a validation error is raised, mentioning that webextension compatibility is staring from FF 42.0

3. extensions without any compatibility settings in the manifest: 
 **Results**:  
 a) mnf key set to `applications` => compatibility after submission starts from 42.0 for Firefox and 48.0 for FF for Android ([example](https://addons-dev.allizom.org/en-US/developers/addon/applications-no-compat/versions/1541849))
b) mnf key set to `browser_specific_settings` => both Firefox and FF for Android compatibilities start from 48.0 ([example](https://addons-dev.allizom.org/en-US/developers/addon/bss-no-compat/versions/1541850))
c) when neither of the two keys are used => both Firefox and FF for Android compatibilities start from 48.0 ([example](https://addons-dev.allizom.org/en-US/developers/addon/no-compat-extension/versions/1541848))

@EnTeQuAk please have a look at my results, especially to point 3, and let me know if they look fine to you. Additionally, if you think there are more scenarios to be covered, I'm happy to test this further.
