### ISSUE TITLE
Lw themes can be still processed using the Interactive Theme Queue

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#10743]
STR:
1. Load AMO dev with an admin or themes reviewer account and go to Rev Tools -> Lightweight Themes
2. In the New Themes, Themes Updates or Flagged Themes click the Interactive Theme Queue
3. Reject or Approve a theme and observe the page

Expected result:
A message that the action can no longer be processed is displayed.

Actual result:
1 theme review successfully processed (+5 points, 2686 total).  The theme is no longer displayed in the pending list.

Notes:
Reproducible on AMO dev and AMO stage with FF65(Win10).

![approved working](https://user-images.githubusercontent.com/33448286/53160765-48f58e00-35d1-11e9-90b8-0f1e0199a325.gif)

It is not reproducible when the themes are clicked individually from pending or flagged lists.

![approved not working](https://user-images.githubusercontent.com/33448286/53160398-8c033180-35d0-11e9-8e08-43457ea39b3a.gif)

**Comment by eviljeff** [comment]
The reviewer tools are _supposed_ to still work - it's the developer edit forms that were removed to stop any more LWT ending up in the review queues.  If the reviewer tools don't work we can't clear out any remaining pending LWT.

That the single page review page _isn't_ still working is the bug here, but given that it's all going in a week or so and the interactive queue still works I wouldn't bother with a bug about it.

**Comment by ioanarusiczki** [comment]
@eviljeff Alright, I thought that rev tools should freeze too at this point. My mistake then.
