### ISSUE TITLE
Update Abuse Report API with choices from the PRD

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10753]
The Abuse Report API from #10643 now has documented choices for the fields we care about in [the PRD](https://docs.google.com/document/d/1K5Th9UmpayfVMXadkxU6cDO3sFKOwYozQgyoN0WEGwY/edit?ts=5c4b6e8d#), we should implement that.

Use the occasion to use `extended-choices` to make the constants a little more easy to deal with, and don't forget documentation, including documenting `application_version` parameter that has been forgotten in #10643.

**Comment by AlexandraMoga** [comment]
Looking at the [Addon abuse report api](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#post--api-v4-abuse-report-addon-), I'm getting that the new constants have been added for the `addon_install_entry_point` and `addon_install_method` fields.

I've sent several requests, making sure that the mentioned fields will only accept the predefined values.
I've also noticed that the `appversion` field was added to the request and response json objects.
The feature continues to work as expected on the frontend.

@diox 
Some issues I've noticed:
- the `addon_install_entry_point` parameter doesn't seem to be recognized any longer, and if I'm reading the actual response correctly, this field is returned as `report_entry_point`. Obviously, in order to verify the constants for this field, I used `report_entry_point` with my requests.
- the Request Json Object has two entries for `lang`. I'm guesing here that you actually wanted to add one of them to the Response Json Object, where there is no entry for `lang` currently.
- the Response Json Object has the following definition for `appversion` - "The locale used by the client for the application". I believe this needs to be replaced with "The application version used by the client."

**Comment by diox** [comment]
> * the `addon_install_entry_point` parameter doesn't seem to be recognized any longer, and if I'm reading the actual response correctly, this field is returned as `report_entry_point`. Obviously, in order to verify the constants for this field, I used `report_entry_point` with my requests.

Yes, I renamed it because it was wrong before - it's the entry point of the report, not the add-on install.

>  * the Request Json Object has two entries for `lang`. I'm guesing here that you actually wanted to add one of them to the Response Json Object, where there is no entry for `lang` currently.

Yep, that's a typo causing this. I'll fix it.

> the Response Json Object has the following definition for `appversion` - "The locale used by the client for the application". I believe this needs to be replaced with "The application version used by the client."

Correct.

Good catches, thanks. I'll fix those.

**Comment by AlexandraMoga** [comment]
> Yes, I renamed it because it was wrong before - it's the entry point of the report, not the add-on install.

Understood. In that case we need to make sure that the same terminology is used in our API documentation

**Comment by AlexandraMoga** [comment]
@diox It looks like the `appversion` field has now an inaccurate description both in the request and response json objects.

The other changes are correct.
