### ISSUE TITLE
implement api endpoint for unsubscribing to email notifications

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10831]
see https://github.com/mozilla/addons/issues/930 and https://github.com/mozilla/addons-frontend/issues/7656 - we need API support for unsubscribe links.

**Comment by willdurand** [comment]
Can we reuse https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#notifications-update?

**Comment by eviljeff** [comment]
Maybe, but it'd be tricky - https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#notifications-update is an authenticated endpoint that requires `user_id`|`username` but the unsubscribe endpoint will have to be unauthenticated and `require token` and `hash`.  It'll be under /accounts though.

**Comment by AlexandraMoga** [comment]
I've verified the new [notifications unsubscribe](https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#post--api-v4-accounts-unsubscribe-) endpoint on AMO -dev. Here are the results:

- when valid values are sent, the changes to notification preferences are correctly applied:
![image](https://user-images.githubusercontent.com/31961530/54194745-a2145b80-44c5-11e9-8b6b-fbfdc21de031.png)

@eviljeff I'm a little confused by the documentation on the `mandatory` case, where it is stated that this field should always return **True**:
 >mandatory (boolean) – If the notification can be set by the user (should always be **True**, or an error would have been sent instead).

 Looking at the response above, `mandatory` is set to `false`, which is correct, because `reply` is not a mandatory notification. 

- when an invalid hash or token is sent, or is completely missing from the request, an error message is received:
![image](https://user-images.githubusercontent.com/31961530/54194801-bd7f6680-44c5-11e9-8a9a-7705732f6b78.png)

- when attempting to change a mandatory notification: 
![image](https://user-images.githubusercontent.com/31961530/54194868-edc70500-44c5-11e9-8381-59020a529974.png)

**Comment by eviljeff** [comment]
> I'm a little confused by the documentation on the mandatory case, where it is stated that this field should always return True:

argh! should be "always return False"

**Comment by eviljeff** [comment]
fixed in https://github.com/mozilla/addons-server/commit/9d7eeac95c74a1217f8885584c04b57fd22e09ea
