### ISSUE TITLE
Race condition between nginx and addons-frontend container

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10856]
Unfortunately there is a race condition with the `nginx` and `addons-frontend` container.

```
nginx_1            | 2019/02/25 10:16:17 [emerg] 1#1: host not found in upstream "addons-frontend:3000" in /etc/nginx/conf.d/addons.conf:110
nginx_1            | nginx: [emerg] host not found in upstream "addons-frontend:3000" in /etc/nginx/conf.d/addons.conf:110
```

This happens because addons-frontend builds and compiles the whole app when starting up which takes about a minute to complete and only after that it starts to listen on the port.

**Comment by jrbenny35** [comment]
I was running into this too. Maybe [this](https://docs.docker.com/compose/compose-file/#depends-on) could work.

**Comment by EnTeQuAk** [comment]
Not necessarily, we'll need a script that checks for a specific port. `depends_on` only checks for a container to be up - which the container is - we have to wait for addons-frontend to listen on port `3000`

**Comment by diox** [comment]
Still annoying :)

**Comment by muffinresearch** [comment]
Since AFAIK no-one is developing the frontend under docker, running it via webpack isn't necessary and also invokes file watching which has been known to cause high CPU usage under docker. If the frontend was built in the build step and the assets are served correctly it should just be a case of starting the service. 

I'm not sure how the frontend file is currently building, but it looks to be to one side of the image build because there's no mention of `yarn build` in the dockerFile. 

See also https://github.com/mozilla/addons-server/issues/9349

**Comment by diox** [comment]
@mirefly changed the `links` to a `network` in https://github.com/mozilla/addons-server/pull/13847 and that seemed to do the trick for both of us, at least :)
