### ISSUE TITLE
Remove logged-out /developers/ view

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#10911]
Blocked by:

- https://github.com/mozilla/addons-server/issues/10910
- https://github.com/mozilla/addons-server/issues/10909
- https://github.com/mozilla/addons-frontend/issues/7696

Once we have links in place /developers/ will be a logged-in view only. Hitting that view when not logged-in will start a login flow.

**Comment by caitmuenster** [comment]
Closing per discussion during today's Add-ons Cross-Functional meeting. Instead of removing the logged out view of /developers, we will update the design of logged out /developers to do two things (1) allow developers proceed to log in to AMO and (2) point to Extension Workshop for more information. 

Next steps: 
- Caitlin to investigate outsourcing design to Turtle Inc 
- Updated design will remove info that is redundant with Extension Workshop
