### ISSUE TITLE
lwt theme versioncheck is broken

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10924]
While testing https://github.com/mozilla/addons-server/issues/9941 it seems that none of the requests to the lwt version check endpoint work on dev or stage - they just return an empty 200 after ~35 seconds.

e.g. 
https://versioncheck-dev.allizom.org/en-GB/themes/update-check/286995 (a non-migrated lwt)
https://versioncheck-dev.allizom.org/en-GB/themes/update-check/60179 (a migrated lwt)

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/commit/1c8dc757edf22d4a4938041b15e531a9975a4b5d turned off `MIGRATED_LWT_UPDATES_ENABLED` which seems to fix it for migrated lwt at least.

**Comment by eviljeff** [comment]
QA: 
* extension updates **must** continue to work - lwt updates are unconnected to the extension update service but is similar code and a bug in one may indicate a bug in the other (n.b. static themes use the extension update service).
* migrated lwt, i.e. lwt that are now static themes, should 404.
* unmigrated lwt updates should work or fail in a non-terrible way.  (You can't trigger a full lwt update though as the theme editor code was removed a few weeks ago)

**Comment by AlexandraMoga** [comment]
Here are my test results for -dev and stage:

1. extension updates (background and manual checks) are working - verified for all extension types on -dev and stage

2. migrated LWTs are returning a 404, as expected:
![image](https://user-images.githubusercontent.com/31961530/54355079-dc663000-4660-11e9-91ff-6b524e945568.png)
@eviljeff I was able to verify this only on -dev. On stage, the the remaining LWTs  look broken to me, i.e all the ones I've checked were missing their header image (this is visible only after installation). Do you think that the migration script can be run again on some of these themes to produce some valid samples?

3. for unmigrated LWTs, the versioncheck endpoint seems to be returning 200:
![image](https://user-images.githubusercontent.com/31961530/54355124-f6077780-4660-11e9-8fee-879def834363.png)
Obviously, there aren't any actual updates applied because, as was mentioned in the QA steps, we no longer have the possibility to update LWTs

**Comment by eviljeff** [comment]
> On stage, the the remaining LWTs look broken to me, i.e all the ones I've checked were missing their header image (this is visible only after installation). Do you think that the migration script can be run again on some of these themes to produce some valid samples?

Any broken LWT is very likely to lead to the migration failing and the LWT being skipped.  But we don't actually need to migrate a new LWT, just use the id of one that was already migrated.
LWT 334201 was migrated to [1002419](https://addons.allizom.org/addon/1002419/), for example.

**Comment by AlexandraMoga** [comment]
@eviljeff hoping that this was the correct approach, I've modified the `lightweightThemes.usedThemes` string on stage to point to LWT Id 334201 - check full string [here](https://pastebin.com/JJL6aRyY)

Then, I've monitored the theme-update-check and noticed that the 404 is showing up:

![image](https://user-images.githubusercontent.com/31961530/54591306-a47d3500-4a32-11e9-872f-2de8e871743e.png)
