### ISSUE TITLE
Remove a recommended add-on from the list

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#11065]
If an add-on ceases to be curated it should be removed from the curated list. 

- This will mean no **new** versions will be recommended.
- The details page should be able to know that the add-on is no-longer recommended.
- It will no longer appear on the homepage which is going to be updated to only show recommended content.

During the changes we must ensure that the TAAR and RTAMO lists continue to function.

https://docs.google.com/document/d/1fRxLy7h02tn1HBIlsTU_6h9DHmN8c3N6bg4JoxHF7J8/edit#heading=h.72krrwjyp6wv

**Comment by eviljeff** [comment]
all the backend, non-reviewer related, changes to support this will be in #11275 too

**Comment by eviljeff** [comment]
QA: it's going to be difficult to test this issue in isolation - you can alter the status in admin but the outcome of new versions not being available is only going to be testable once the reviewer tools issues are completed.

**Comment by AlexandraMoga** [comment]
Similar to #11064 I was able to verify that the recommended status can be removed via a checkbox in the Discovery items admin tool. The effect of this change is then visible in the [curated list](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/), but it is not reflected elsewhere at this moment. 

I'm not adding a verified label to this issue, since not all the requirements are available for testing.
