### ISSUE TITLE
Features add-ons search flag should only return recommended add-ons

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#11068]
The featured add-ons search flag should only return recommended add-ons.

See the PRD for more info: https://docs.google.com/document/d/1fRxLy7h02tn1HBIlsTU_6h9DHmN8c3N6bg4JoxHF7J8/edit#heading=h.5kvm14zbadi2

**Comment by jvillalobos** [comment]
One thing to note here is that featured themes will still come from the collection, so this change applies to extension results only. Other than being weird, I hope that's not a problem.

**Comment by eviljeff** [comment]
@jvillalobos is it a requirement to change the `featured` search flag to mean recommended?  Adding a new flag is much cleaner.

> One thing to note here is that featured themes will still come from the collection, so this change applies to extension results only. 

Is this a short-term workaround? - i.e. are themes eventually going to be recommended also?  If we can remove the collection-backed featuring implementation it would clean up some old and weird code.

**Comment by jvillalobos** [comment]
> @jvillalobos is it a requirement to change the featured search flag to mean recommended? Adding a new flag is much cleaner.

How would that work? Having a second checkbox for Recommended?

> Is this a short-term workaround? - i.e. are themes eventually going to be recommended also?

I think we'll continue to maintain the featured themes in the collection. We've largely deferred it to the theme community, and that list will continue to work as just a selection of nice themes, rather than having the deeper review that will be part of Recommended.

**Comment by eviljeff** [comment]
> How would that work? Having a second checkbox for Recommended?

Frontend would change the checkbox (wording and the api params) to refer to Recommended rather then Featured when we were ready to launch the feature.  Afterwards we'd remove the featured flag from the API.
If it's a problem we can alias `featured` to `recommended` for now and only deprecate `featured` in a future version of the API.

**Comment by jvillalobos** [comment]
As long as it works for extensions and themes (considering that themes still have a featured collection), it doesn't make a difference to me which API flags are used.

**Comment by ioanarusiczki** [comment]
After checking on https://github.com/mozilla/addons-frontend/issues/7794 I filed https://github.com/mozilla/addons-server/issues/11419 but I think it's the same issue as described here.

**Comment by jvillalobos** [comment]
@eviljeff we discussed the Featured badge at the product level and decided to drop it and use the Recommended badge instead. So, themes in the featured themes collection will display the Recommended badge. The Featured extensions collection will no longer have any special meaning, since we'll use a different data source for Recommended extensions. The search flag should change from Featured only to Recommended only and show only Recommended results.

**Comment by diox** [comment]
@jvillalobos the interaction with the way recommendations work for the ex-featured themes is not clear to me. Would they really be considered "recommended" underneath, with the signature and special review flow ? We can cheat in AMO and display them as recommended by just checking the collection, but that wouldn't work for Firefox itself, so there would be a difference between the way they are displayed in AMO and Firefox.

**Comment by diox** [comment]
(@jvillalobos replied in the PR about this https://github.com/mozilla/addons-server/pull/11435#issuecomment-492735392)

**Comment by jvillalobos** [comment]
We mid-aired :). See my comment on https://github.com/mozilla/addons-server/pull/11435#issuecomment-492735392 and let me know if there are other details I'm missing.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- So far, all the recommended addons added from admin tools in the Discovery Items + flag for the last version appeared with the "Recommended add-ons only" search flag. 

- The themes show up too but their detail page does not display the new badge.There's https://github.com/mozilla/addons-server/pull/11435 for https://github.com/mozilla/addons-server/issues/11429 so it's possible that with those changes, the badge will show up ?

![themes with no badge yet](https://user-images.githubusercontent.com/33448286/57936107-e5c38100-78cb-11e9-89c4-be5a10508b2e.gif)

**Comment by eviljeff** [comment]
> The themes show up too but their detail page does not display the new badge.There's #11435 for #11429 so it's possible that with those changes, the badge will show up ?

Without #11435 themes _shouldn't_ show up, but I think frontend is currently translating `recommended` into `featured`.  @bobsilverberg which issues are outstanding to make the themes work as Product now want it to work?

**Comment by bobsilverberg** [comment]
https://github.com/mozilla/addons-frontend/issues/8035 will make it so that the Recommended badge appears on the details page for a Theme. Is there anything else that this needs from the frontend?

**Comment by ioanarusiczki** [comment]
@eviljeff The reason those themes show up with the recommended flag on dev is because I added them as being "Recommendable" from Discovery Items and then I marked the "Recommendation approved"  for the last version.

**Comment by eviljeff** [comment]
@ioanarusiczki oh, that will work.  Though it's expected the normal case will be themes added to a special collection by a community team, rather than adding via the admin/reviewer tools by the curation staff.

**Comment by ioanarusiczki** [comment]
@eviljeff I've done some testing for the Android platform on FF67(Android 9.0) - because the badges right now should not be available, yet the search results on `android` follows the same [rules](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-search-sort) now as for `firefox` platform. 

An example
https://addons-dev.allizom.org/en-US/firefox/search/?type=statictheme 
https://addons-dev.allizom.org/en-US/android/search/?type=statictheme
The recommended themes are promoted above the other search results if no search queries are provided.
The difference is that `android` won't show the recommended badge in the search results.

Is it alright at this phase if  "Featured" was replaced with  "Recommended" add-ons only on Android too ?
I believe the implementation of the badges will follow for this platform too sooner or later.
![recommended](https://user-images.githubusercontent.com/33448286/58427164-7f96e500-80a7-11e9-81a0-2cf6957fd6a9.png)

**Comment by eviljeff** [comment]
None (that I recall) of the addons-server issues called out Android having different criteria to Desktop Firefox so I just assumed the differences would how frontend displayed them.

>Is it alright at this phase if "Featured" was replaced with "Recommended" add-ons only on Android too ?

A frontend question imo.  In addons-server everything in the future will be recommended - the featured infrastructure will be removed after recommended is launched.

**Comment by bobsilverberg** [comment]
I guess we should check with @jvillalobos, but my understanding is similar to @eviljeff's in that, once this feature is turned on, "Featured" will no longer exist anywhere and only "Recommended" will exist. So even on Android the search form will say "Recommended add-ons only".

Can you confirm, @jvillalobos?

**Comment by jvillalobos** [comment]
Yes, I think it's okay to say Recommended for Android too.
