### ISSUE TITLE
Use the verification endpoint to verify abuse reports sent by Firefox

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#11070]
The API endpoint will be stood up here: https://github.com/mozilla/taar/issues/151

Once this is available we can query it when receiving abuse reports from Firefox.

We are not taking into account the time the add-on has been installed for, since we're not doing that we do need defer the verification check if the add-on has only just been installed to allow enough time for the telemetry data to make it back to the server.

**Comment by diox** [comment]
According to the linked issue the API is: `/v1/api/client_has_addon/{hashed_client_id}/{addon_guid}/` using the taar endpoint.
This returns an object with a `results` boolean indicating whether the client has installed the add-on or not (and optionally an `error` key if the client id is completely unknown, but we don't need that)

One challenge for testing is that this doesn't support the test client ids the recommendation endpoint uses, and because I don't have access to the prod endpoint, I'm not sure I (or QA) can test that it's working properly - I don't know how to get my Firefox to report telemetry data to stage so that taar stage instance receives it.

**Comment by diox** [comment]
My main concern is that it doesn't look like taar does anything to support add-ons that have since been de-installed by the user. By delaying the check, we handle add-ons that have been installed too recently, but we make the reverse scenario worse: a user submits an abuse report about an add-on and then uninstalls it, and by the time AMO checks whether the user has the add-on installed, it's too late, the add-on is gone for this client id and we consider the report unverified.

**Comment by jvillalobos** [comment]
I'd be in favor of dropping this work. So far we haven't had problems with abuse reports that warrant this extra verification, and we get such high volume of reports that trying to eschew them in any way would require massive spamming. It also sounds like this solution would end up discarding legitimate reports for questionable gain.

**Comment by diox** [comment]
Yeah. I was hoping implementing it would be simple enough that we could do it quickly and have real data to see if it's worth it, but it's not as straightforward as I would have liked.
