### ISSUE TITLE
Create review queues for pre-reviewed add-ons

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11072]
Part of [Review Flow for Recommended Extensions](https://docs.google.com/document/d/1kqDR2KHfbgLmaVZ-b-HgbSgpwU6eKA_D9voQkJ9M3io/edit#).

We currently have two review queues in the Static Themes and Legacy Add-ons section in `/reviewers/`, where everything requiring pre-review is lumped together. Themes will be separated in https://github.com/mozilla/addons-server/issues/11071. The following additional changes need to happen:

* [x] Rename section to Pre-Review Add-ons
* [ ] Instead of New and Updates, the new queues are Recommended and Other Pending Review.
* [x] The Recommended queue includes all extensions that are either Recommended or Pending Recommendation and have a new version pending review (no longer split into New and Updates).
* [ ] ~The Other Pending Review queue has everything else with a version pending review: legacy add-ons that still need pre-review and non-Recommended add-ons that had the manual review flag set (no longer split into New and Updates).~ #11477
* [x] Remove Theme Review Guide link.

**Comment by eviljeff** [comment]
>  Instead of New and Updates, the new queues are Recommended and Other Pending Review.
> The Other Pending Review queue has everything else with a version pending review: legacy add-ons that still need pre-review and non-Recommended add-ons that had the manual review flag set (no longer split into New and Updates).

I'm going to split out combing the existing new and update queues into a single queue into a separate issue - it's going to involve a lot of changes throughout the review tools, especially in the test suite so it'll be safer to do that separately.

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx67, Win10x64

The new Recommended queue is available under Pre-reviewe add-ons. New recommended add-ons and their consecutive versions (while the add-on is still being marked as recommended in discovery items) will appear in this queue. 
*Since there is still no special process around unlisted versions, these versions will appear in the Unlisted review queue.

![image](https://user-images.githubusercontent.com/31961530/58458541-2de76c80-8132-11e9-8372-7d16932c4c0c.png)

@eviljeff @jvillalobos 
The minimum permissions required to view and perform reviewer actions inside the Recommended queue are: `Addons:Review`, `Addons:PostReview` and `Reviews:Admin` 
Without `Reviews:Admin`  and `Addons:Review` you won't be able to see the queue on the dashboard and without `Addons:PostReview` you'll receive a 403 when attempting to open an add-on review page from the Recommended list.

**Comment by eviljeff** [comment]
Mmm, yes, I was probably a bit careless with permissions.

**Comment by jvillalobos** [comment]
Ideal: new permission called `Addons:RecommendedReview`, and corresponding user group.

Otherwise: only require `Addons:Review`.

**Comment by eviljeff** [comment]
filed #11538 for permission changes.
