### ISSUE TITLE
Switch Search Engine add-ons to Auto-Approval

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11073]
Part of [Review Flow for Recommended Extensions](https://docs.google.com/document/d/1kqDR2KHfbgLmaVZ-b-HgbSgpwU6eKA_D9voQkJ9M3io/edit#).

I believe these two add-on types currently require pre-review. Let's switch them to auto-approval, since they don't pose any significant risk and aren't getting much community activity.

**Comment by diox** [comment]
Only search engines require pre-review, language packs have been switched to auto approval a while ago (6141a51857a3211bef17abdad4b56d1071bf6981).

One thing I'm worried about is that they'll forever be at the bottom of the queue, because they don't represent an active risk to the browser itself, but they can still be hugely misleading or pose a privacy risk if the developer sets a custom URL that has ads, tracking similar things.

**Comment by EnTeQuAk** [comment]
Especially when looking at (more recent) issues like https://bugzilla.mozilla.org/show_bug.cgi?id=1538007 (ping me in IRC if you don't have access)

**Comment by eviljeff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1538007 doesn't seem to affect search engine plugins (LP are already signed as @diox mentioned) so that's not a blocker.  

@jvillalobos are you happy for us to go ahead with making search engine plugins as is or do you want some adjustments to review score weighting?  (I'm not sure _what_ we'd score on, other than bumping all of them)

**Comment by wagnerand** [comment]
Search engine plugins are never default, so I think the risk is low here, lower than langpacks, which are already auto-approved.

**Comment by jvillalobos** [comment]
Agree with Andreas, don't think further action is needed.

**Comment by jvillalobos** [comment]
I'll add that both langpacks are search engines are probably moving out of AMO in the future. Not sure if this year, but not much later than that.

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx67 Win10x64

Search tools are now auto-approved and will appear in the auto-approval queue in Reviewer Tools (normally on the last page) - an example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/eccellio-science-auto
As an observation, search tools are not going through the signing process, so there won't be any `META_INF` file generated after auto-approval.

Regarding version numbering, search tools receive a standard version number in the format `yy/mm/dd` after submission. This means that if a new version is uploaded the same day, the submission won't be possible because the current `yy/mm/dd` number is already assigned to the previous version.   I've looked in prod and it seems that we are using this format for a very long time and I couldn't find any search tools with multiple versions, so I'm guessing that, in the real world, what I've mentioned above is not much of a problem. 

@diox What do you think ^ ?

**Comment by diox** [comment]
Even if it was a big problem, I don't think we'll ever fix that before they are eventually switched to webextensions.
