### ISSUE TITLE
No validation report for listed Add-ons during submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1108]
Steps to reproduce:
1. Sign in to AMO-dev https://addons-dev.allizom.org/en-US/firefox/
2. Submit a listed Add-on (i.e. Add-on Listed 18.12.xpi)
3. Check the validation report at step 2 of submission process 

Expected results:
User can access the report.

Actual results:
The validation report is not listed.

Notes/Issues:
The validation report is listed for unlisted or bundled add-ons during step 2 of submission process. Same thing is happening if using the Add-on Validator.
Verified on FF43(Win 7). Issue is reproducing on AMO-stage, AMO-dev and AMO-prod.
Screenshot for this issue: 
![2015-12-18_0950](https://cloud.githubusercontent.com/assets/15685960/11892160/3b353492-a56e-11e5-8436-12a8f9f1e916.png)

**Comment by EnTeQuAk** [comment]
The validation report is only shown if there are any errors or warnings. If everything is fine I believe there's no need to show the report since it's just 5 green checkboxes telling you that everything is fine.

Closing as I don't believe this is something we need. You are able to see the validation reports for every version in "Manage Status & Versions" (e.g https://addons.allizom.org/en-US/developers/addon/versioncheck01/versions).
