### ISSUE TITLE
Detail view for abuse reports

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11136]
Part of the the [abuse reporting project](https://docs.google.com/document/d/1K5Th9UmpayfVMXadkxU6cDO3sFKOwYozQgyoN0WEGwY/edit#). 

When an abuse report is clicked on the list view (https://github.com/mozilla/addons-server/issues/11133), a detailed view should appear. It should have the same data and actions available in the triage tool (https://github.com/mozilla/addons-server/issues/11135). It should be accessible to users with the (new) `AbuseReports:Edit` permission.

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx67, Win10x64

- the abuse report details can be accessed with an admin account or with a user that has `AbuseReports:Edit` permissions (I've created [this group](https://addons-internal.dev.mozaws.net/en-US/admin/models/access/group/50105/change/) to test that the permission is working)


@diox the request was that the detail view should have all the information and actions available in the triage tool (#11135). The following items have not been included - at least I could not find them:
- add-on` version and author`
- `Amount of abuse reports for the add-on since its last version update`  - I have submitted a new version for an add-on and then created some abuse reports but this section is not present
- `Was the affected version reviewed by a human?` 
- `A link to the review page`
- `Skip this report and go to the next` - there is no button that fulfills this action 

Have these actions been omitted deliberately or do you plan to add them in a future patch?

**Comment by diox** [comment]
I've implemented a minimal detail page for now, the rest will be implemented when the triage tool lands in #11135 (it will be the same page)

**Comment by AlexandraMoga** [comment]
In that case, I will insist more on that when the triage tool is complete.
