### ISSUE TITLE
Show signing type on add-ons page

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1116]
Show the signing type (side-loaded or not) for versions of an add-on on the add-on details page. Currently by looking at an add-on on AMO, you've got no idea if the add-on is signed or not and you've got no idea if it can be sideloaded or not.

I'm not sure where we'd put this, maybe tuck it away under version information?

**Comment by jvillalobos** [comment]
Beta and preliminary versions get the stripped yellow install button, which indicates the version can't be side-loaded. Versions with the green button can side-load.

The exception for this would be if a reviewer or admin changes the status of a file, which leaves it in an inconsistent state because the signature doesn't change.

**Comment by andymckay** [comment]
With the changes in Firefox, I don't think this is needed anymore.
