### ISSUE TITLE
Change disco pane preview in admin tools to match Firefox's design

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11272]
When https://bugzilla.mozilla.org/show_bug.cgi?id=1540173 lands we should change the "preview" for disco pane items in the admin. It currently follows AMO's disco pane design (roughly), it should follow Firefox's design once it's up.

See also https://github.com/mozilla/addons-server/issues/11114

**Comment by Rob--W** [comment]
The patches have landed in Firefox Nightly (68.0a1 buildID 20190509214305).

To use it, set the `extensions.htmlaboutaddons.discover.enabled` pref to `true`.

- Main bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1546248
- Appearance of star ratings: https://bugzilla.mozilla.org/show_bug.cgi?id=1542262
- Notes on screenshot size: https://bugzilla.mozilla.org/show_bug.cgi?id=1546123

**Comment by eviljeff** [comment]
@diox can you explain what needs to be changed?   I don't see the difference between what's shown in the admin and in Firefox's discovery pane (other than a line return between the addon's name and "by Joe User", which seems a little trivial ?)

**Comment by diox** [comment]
The key visual difference is the trivial bit you noticed, yes. But under the hood, Firefox does not use the `heading` and `description` properties of our API, which returns HTML. Instead, if uses `description_text` and builds its own title from the add-on `name` and `authors` returned (unless it uses `heading` but strips everything after the first `<span>` ? I haven't checked).

So, to fully clean this up, we need to match this behavior, removing our support for HTML variants of the heading & description, probably remove custom heading completely in fact if Firefox is not using that.

**Comment by eviljeff** [comment]
resurrecting this now we've deleted (mozilla/addons-frontend#9379) the frontend discopane app that consumed the old html properties from the api.

**Comment by eviljeff** [comment]
@Rob--W can you confirm/point to what information is consumed in Firefox from the api endpoint https://addons-server.readthedocs.io/en/latest/topics/api/discovery.html ?

**Comment by Rob--W** [comment]
The consumer of the API in Firefox is here:
- https://searchfox.org/mozilla-central/rev/c409dd9235c133ab41eba635f906aa16e050c197/toolkit/mozapps/extensions/content/aboutaddons.js#569-599
- https://searchfox.org/mozilla-central/rev/c409dd9235c133ab41eba635f906aa16e050c197/toolkit/mozapps/extensions/internal/AddonRepository.jsm#580-663

The unit tests in Firefox [are designed to support the use case of refactoring the API response](https://searchfox.org/mozilla-central/rev/c409dd9235c133ab41eba635f906aa16e050c197/toolkit/mozapps/extensions/test/browser/browser_html_discover_view.js#12-19).
If you are interested in running the test yourself, you can [clone the repository](https://firefox-source-docs.mozilla.org/contributing/contribution_quickref.html#clone-the-sources) (with git or hg) and run the test as shown below. Feel free to ask me to run the test if you want it to be double-checked, it isn't that much of an effort.

`$ cd path/to/repo/mozilla-central`
`$ wget https://addons.allizom.org/api/v4/discovery/?lang=en-US -O toolkit/mozapps/extensions/test/browser/discovery/api_response.json`
`$ ./mach bootstrap --no-system`
(choose Artifact build for desktop)
`$ ./mach build`
`$ ./mach test toolkit/mozapps/extensions/test/browser/browser_html_discover_view.js --verbose --log-mach-verbose`

**Comment by eviljeff** [comment]
thanks Rob.
So from looking at the source, it uses `heading_text` and `description_text`; AMO's discovery api currently returns `heading`, `description`, `description_text` - i.e. we can safely drop `heading` and `description` - note also it **never returns `heading_text`**.

Assuming that we don't want to suddenly start returning a html-less version of `heading` as `heading_text` over a year later, we can drop the custom heading from the models/db/translations too.

**Comment by eviljeff** [comment]
Regarding backwards compatibility - usually if a property is dropped from a public api we are careful to shim in a suitable replacement for v3 at least (a roughly equivalent value, or `""`/`null` otherwise).  Options:
A) Don't care all at - given /discovery/ is only consumed by Firefox now, that we know of, and we know exactly what it expects in response, remove `heading` and `description` from the response entirely in v3, v4, and v5.
B) Care a little bit - return `""` in v3 (and v4?) so any consumer that expects the properties won't hard fail.
C) Care too much - move the fallback logic that generates `heading` from the addon name into the serializer so it still returns a valid value in v3 (and v4?)

**Comment by diox** [comment]
I'd lean towards B) or C) if you're really motivated.

**Comment by Rob--W** [comment]
> So from looking at the source, it uses `heading_text` and `description_text`;

On discopane-specific stuff: Yes. It also uses `addon`, but that is shared with other parts of the API.

> note also it **never returns `heading_text`**.

This is intentional. The original add-on card design prescribed a boldfaced heading text, followed by the heading description. Then there was a request to not boldface the text, and that is achieved by just omitting heading_text from the response (and having the description in `description_text`).

**Comment by willdurand** [comment]
Shouldn't we remove the discopane entirely before? There is still a version up and running in all envs.

**Comment by eviljeff** [comment]
> Shouldn't we remove the discopane entirely before? There is still a version up and running in all envs.

If we have fallback shims in place then it won't be a blocker.

**Comment by AlexandraMoga** [comment]
I've verified the `/v3/`, `/v4/` and `/v5/` discovery APIs on stage and I have the following results:

- `/api/v4/discovery/` and `/api/v5/discovery/` - `"heading"` and `"description"` fields are no longer exposed:
```
"results": [
        {          
            "description_text": "",
            "addon": {...},
            "is_recommendation": false
        }]
```
-  `/api/v3/discovery/`  - `"heading"` and `"description"` fields are still exposed:
```
"results": [
        {
            "heading": "",
            "description": "",
            "description_text": "",
            "addon": {...},
            "is_recommendation": false
        }]
```

I've also verified the about:addons (recommendations) page and I didn't see any regressions caused by the API update. 

The Discovery Items in admin tools still shows a 'Custom description' field which allows admins to change the value of the `"description_text"` returned by the API - the value which is further displayed on the about:addons page. 

I'm marking this issue as verified fixed on stage.

**Comment by eviljeff** [comment]
under `/api/v3/discovery/` the heading and description fields shouldn't be blank values - they should be sensible values: for heading, essentially the previous fallback if custom_heading wasn't set); for description the value of `description_text` but wrapped in `<blockquote>` as before.
