### ISSUE TITLE
expose recommended status in the API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11278]
The API needs to expose recommended status so Frontend can badge it appropriately.  Addon will expose `is_recommended`.  Version will expose something - probably a similar `is_recommended` field - tbc.

supports mozilla/addons-frontend#7793

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-frontend/issues/7794#issuecomment-487677708 confirms no all version page badges so no need for a per-version `is_recommended` in the API response.

**Comment by bobsilverberg** [comment]
Thanks @eviljeff. Subscribing for updates.

**Comment by AlexandraMoga** [comment]
The `is_recommended` parameter is returned in the addon detail api response, as seen in the example below:

https://addons-dev.allizom.org/api/v4/addons/addon/344147/

![image](https://user-images.githubusercontent.com/31961530/57223206-fb07f800-700d-11e9-9f59-af3c7afff7c4.png)

At this point, the value will always be `false` since the process for setting a recommended status is not yet developed. 

@eviljeff I've noticed that the `is_recommended` parameter is also returned by the addon search api, but its value is `null`. Is this expected at this point?

https://addons-dev.allizom.org/api/v4/addons/search/?q=block

![image](https://user-images.githubusercontent.com/31961530/57223835-0f4cf480-7010-11e9-992a-6e2e4510b42f.png)

**Comment by eviljeff** [comment]
> At this point, the value will always be false since the process for setting a recommended status is not yet developed.

To make an add-on recommendable you can set the flag in django admin on the add-on.  The reviewer tools support for actually approving a version and having a recommended add-on isn't developed, but you can fake that by editing the version in django admin too.  Although it may be easier to just verify this issue fully when the reviewer tools work is complete.

> @eviljeff I've noticed that the is_recommended parameter is also returned by the addon search api, but its value is null. Is this expected at this point?

It is - we need to run a reindex to set all the values to false (we decided it wasn't that important right now).

**Comment by AlexandraMoga** [comment]
> To make an add-on recommendable you can set the flag in django admin on the `DiscoveryItem`. The reviewer tools support for actually approving a version and having a recommended add-on isn't developed, but you can fake that by editing the version in django admin too. Although it may be easier to just verify this issue fully when the reviewer tools work is complete.

@eviljeff I used this workaround just to make sure that the `is_recommended` status changes to `true` if I confirm it through the `Recommendation approved` flag from [admin versions](https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/version/1688144/change/)

https://addons-dev.allizom.org/api/v4/addons/addon/awesome-screenshot-plus-/ is recommended now:
![image](https://user-images.githubusercontent.com/31961530/57288468-2ea45a00-70c2-11e9-8297-47e626cda250.png)

The status changes again to `false` if remove the `Recommendation approved` flag from admin versions.

I'm marking the issue as verified fixed on -dev.
