### ISSUE TITLE
Re-sign listed add-ons with COSE signature

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#11323]
This bug is to cover re-signing all *listed* add-ons for FF 57+ with the updated signature that has been available for new versions uploaded since the April 4th push.

From @diox on irc:

> the command used to resign add-ons still exists, it currently it resigns *all* versions *including unlisted* of *all* add-ons that are not disabled/incomplete it sends an email to developers as well see https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/crypto/tasks.py

## Open questions:

* Does we need to re-sign all versions or just latest?
* What does the email need to say?

**Comment by jvillalobos** [comment]
Signing the latest listed version should be sufficient. This won't cover some edge cases around compatibility, but those can be manually fixed by the developers.

@caitmuenster can help us with the email contents.

**Comment by caitmuenster** [comment]
Draft of email contents is available [here](https://docs.google.com/document/d/167MXie1DEXDVEM0j2V8ALC8MBSjjKqNp6Ebd9TV9gMg/edit#heading=h.g5ovjz3dh3pk).

@jvillalobos, @muffinresearch, could you review for accuracy and let me know when the re-signing date will be?

**Comment by jvillalobos** [comment]
I believe the re-signing would happen in late June / early July.

**Comment by EnTeQuAk** [comment]
Assigning myself to work on the necessary scripts

**Comment by grahamperrin** [comment]
(Ignore/delete the reference from the Waterfox issue. My bad.)

**Comment by EnTeQuAk** [comment]
QA: I haven't run this on -dev yet so that you can verify the status quo. Let me know when you're testing this and I'll run the script. Once I do, all existing, public WebExtensions that have been created before April 5th 2019 will be re-signed and have the COSE signature afterwards.

**Comment by AlexandraMoga** [comment]
I have verified the re-signing results on -dev after the script has finished running. Below is a summary of what I've observed and some question. 

I have >200 add-ons submitted on dev, so I used those to draw the following conclusions
- public add-ons with a current version submitted before April 5th have been re-signed => they can be recognized by looking at the  current version number which will look smth. like this: `x.y-signed`. The add-on package will also contain the updated signatures in the `META_INF` folder
- unlisted, disabled or Invisible versions have not been re-signed
- if a user has installed an add-on with the old signature, after the re-signing process he will receive the updated version (this was verified in about:addons)

@EnTeQuAk here are some questions:
1. You mentioned that the script might have failed to run on some versions. I did find a few examples among my add-ons which haven't been re-signed. As an observation, since we enabled COSE signing on -dev on Jan 31st (iirc),  the re-signing script has also run on add-ons that already had this signature. Not sure how much of a problem this will be in prod.
<details>
<summary> List of add-ons that haven't been re-signed </summary>

https://addons-dev.allizom.org/en-US/developers/addon/libs-unread-code-02-08/versions
https://addons-dev.allizom.org/en-US/developers/addon/privacy-badger-lex/versions
https://addons-dev.allizom.org/en-US/developers/addon/creation-date-in-addon-api/versions
https://addons-dev.allizom.org/en-US/developers/addon/bss-extension-minctcompat/versions
https://addons-dev.allizom.org/en-US/developers/addon/soundfixer/versions


</details>

2. From what I've seen, we are re-signing only the current public versions. This works fine for backwards compatibility, but I have some scenarios in mind that might not work once COSE becomes the only accepted signature:
  - a user wants to install an older version of an add-on; this version hasn't been re-signed so, in theory, he won't be able to install it
  - a developer disables/deletes the version re-signed with COSE and the next available version which becomes public has an old signature => this add-on won't be installable anymore

**Comment by EnTeQuAk** [comment]
> You mentioned that the script might have failed to run on some versions. I did find a few examples among my add-ons which haven't been re-signed. As an observation, since we enabled COSE signing on -dev on Jan 31st (iirc), the re-signing script has also run on add-ons that already had this signature. Not sure how much of a problem this will be in prod.

Yeah, the date was chosen from the deploy we did on prod, so some duplicates are expected. The overlap will be much less on prod.

> List of add-ons that haven't been re-signed

I checked them all in our logs and for exactly these add-ons I can see errors from the autograph side which means autograph was temporarily unavailable. I can try re-sign them manually a bit later today.

> From what I've seen, we are re-signing only the current public versions. This works fine for backwards compatibility, but I have some scenarios in mind that might not work once COSE becomes the only accepted signature:

You're correct, these scenarios are perfectly possible. The expectation I think is, that those edge-cases can be fixed manually by the developer by simply submitting a new version. We can also run the script manually on specific add-ons once a version got disabled and re-sign the most current one if needed. That has been deemed sufficient.

**Comment by AlexandraMoga** [comment]
I'm not adding a verified fixed label yet because we need to re-verify all these functionalities when the re-signing script will be run on stage.
