### ISSUE TITLE
Hard-delete obsolete addon types from the database

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11324]
Apparently we still have some webapps in the database:
`SELECT COUNT(*) FROM addons WHERE addons.addontype_id = 11;` returns some results on dev/stage/prod.

Looks like some are soft-deleted, some incomplete (status 11 or 0).

We should hard-delete them, as well as the associated files. The trick is that some of the linked models might also need to be hard-deleted for that to happen. It could require a multi-stages approach, with a migration removing some of the linked models for good, and then a `process_addons` task to hard-delete the add-ons themselves (if it's done in python it should clean up the relevant files for us).

-- hijacking this issue to get rid of all obsolete add-on types from the database - LWT, plugins, xul themes too

**Comment by eviljeff** [comment]
status:
- dev is done
- stage is done
- prod still to go

**Comment by eviljeff** [comment]
@bqbn I will need ops support to run this on prod.
I've just been running `sudo docker exec --user olympia -it $(sudo docker ps -f name='addons' -q) ./manage.py process_addons --task=delete_obsolete_addons --with-deleted --batch-size=50`.  

A certain number of tasks will fail with a database timeout because the sql to delete that many add-ons at once can be too be complex.  So then (after all the tasks have finished) I've run it again with a lower `--batch-size` (e.g. 33); then repeat and with a lower batch-size, and so on, (on stage the last 12 addons I ran with a batch-size of 3) until zero.  It could be started with a lower size than 50 if we want to trade overall speed for the hassle of repeatedly executing the command.

This isn't a super high priority task, but a smaller database means better performance overall (and no more old types in the db unblocks code clean-up)

**Comment by bqbn** [comment]
Please remind me to run this tomorrow (Tuesday 9/17) in the #remora channel in case I forget.

Also IIRC, we have run this `delete_obsolete_addons` task at least a couple times in -prod ever since we migrate to LWT. Why those "obsolete" addons keep coming back? Do you expect them to come back after this run?

**Comment by eviljeff** [comment]
>Also IIRC, we have run this delete_obsolete_addons task at least a couple times in -prod ever since we migrate to LWT.

This task hasn't been run before on prod - the commit to add it was only added mid-August.  We did run a similar task earlier in the year to soft-delete leftover LWT - this is hard deleting and includes additional addon types (see end of opening comment).

>  Why those "obsolete" addons keep coming back? Do you expect them to come back after this run?

They've never gone anywhere, we just ignored them as they took up space in the database and required subtle differences in code everywhere they could have been exposed.

**Comment by eviljeff** [comment]
Results of the prod first pass with `--batch-size=50` look good.  Only 4600 remaining (of 585,000).  I think we can afford to run it the second time with a relatively low batch size to delete the addons from the 92 celery tasks that failed.  

I suggest `sudo docker exec --user olympia -it $(sudo docker ps -f name='addons' -q) ./manage.py process_addons --task=delete_obsolete_addons --with-deleted --batch-size=10` @bqbn

**Comment by bqbn** [comment]
I've run it with `--batch-size=10`.

**Comment by eviljeff** [comment]
All obsolete addons are gone from prod as of 2019-09-18.
