### ISSUE TITLE
Search is not returning exact matches higher than other results

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#11371]
Steps to reproduce:
1.In AMO Stage, search for "facebook conta"

Expected results:
Facebook Container webextension should be in the first place of search suggestions

Actual results:
Facebook Container is not even in the search suggestions

Please see a video for this bug : 
![exactmatch](https://user-images.githubusercontent.com/1583842/57384855-f3855200-71b9-11e9-8afa-691009a50588.gif)

**Comment by eviljeff** [comment]
It does technically work on an exact match - "Facebook container" shows it as the first result, and it's second if you search for "container".  "Facebook conta" is a relatively low score though, possibly because (on stage) it was updated over a year ago; has 2 ratings; and no users.  The other matches also have facebook in their name and have been updated recently (because they are themes we just repacked)

**Comment by AlexandraMoga** [comment]
See also https://github.com/mozilla/addons-server/issues/10171 for more context

**Comment by eviljeff** [comment]
I think, given @AlexandraMoga 's comment, it's  a dupe to #10171
