### ISSUE TITLE
Have feature themes collection membership be treated as recommended

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11429]
(At least at first) themes aren't going to go through the same process as extensions to get recommended - they don't have code so don't need a code review so we'll reuse the existing way featured themes are selected (by membership of special collection)

**Comment by ioanarusiczki** [comment]
@eviljeff - I tested on AMO dev - FF66(Win10) and here are my results with the associated questions:

> so we'll reuse the existing way featured themes are selected (by membership of special collection)
- as far as I know the featured theme collection can be edited (if the user has rights to do so) from [admin tools](https://addons-internal.dev.mozaws.net/en-US/admin/models/bandwagon/collection/2143965/change/) or[ frontend](https://addons-dev.allizom.org/en-US/firefox/collections/4757633/featured-personas/edit/?page=1&collection_sort=added).
When a theme is added to this collection the "featured" label automatically is displayed. - will the "recommended" badge show instead of "featured" once https://github.com/mozilla/addons-frontend/issues/8035 lands? 

- right now the featured theme collection is displayed on the homepage and once the [See more](https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=statictheme) blue link is clicked there's also the "Recommended add-ons only" flag available. 
The number of themes is 9 with `?featured=true&type=statictheme` as search parameters.
Adding `recommended` ,the number of themes is 9 with `?featured=true&recommended=true&type=statictheme`. 
I receive the same results from the API ` "count": 9` for https://addons-dev.allizom.org/api/v5/addons/search/?featured=true&type=statictheme
and `"count": 9,` for making a request with the `recommended` parameter  https://addons-dev.allizom.org/api/v5/addons/search/?recommended=true&featured=true&type=statictheme

Which means that once the theme is added in the featured collection it's also considered as being recommended and nothing else needs to be done such as adding the recommendable flag from Discovery items and for it's last version which can be done but if the theme is not part of the featured collection it won't be a real use case. Did I get it right?  
Also, I can't tell if that `Recommended` flag is going away from here, that's if the `featured` is entirely removed and replaced with `recommended`. 

![featured themes from homepage](https://user-images.githubusercontent.com/33448286/58099621-b327ca00-7be4-11e9-8c9c-b20678e2454b.gif)


- a while ago I filed two issues about the featured theme collection and one I transferred it from the frontend repo to server today https://github.com/mozilla/addons-server/issues/10403 and https://github.com/mozilla/addons-server/issues/11487.

**Comment by ioanarusiczki** [comment]
https://github.com/mozilla/addons-frontend/issues/8035 has landed so
Static themes which are added to the [Featured Themes](https://addons-internal.dev.mozaws.net/en-US/admin/models/bandwagon/collection/2143965/change/) collection will automatically become Recommended (is_recommended": true) and they'll display the badge.
