### ISSUE TITLE
Allow wildcard-matching for email domains

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11484]
Follow up from #11442

**Comment by diox** [comment]
The reason we need proper wildcards and not just the `endswith` implementation is if a malicious user creates a domain that is a subset of a valid one we don't want to restrict, and they control subdomains as well:
- Developers buys `mail.com`, starts creating users with `a.mail.com`, `b.mail.com` etc
- We can't restrict `mail.com` entirely, because that would block `gmail.com` as well
- If we only restrict `@mail.com` then subdomains are allowed.

**Comment by AlexandraMoga** [comment]
The use of wildcard matching was tested in https://github.com/mozilla/addons-server/issues/11443#issuecomment-495189403, so I;m marking this issue as verified.
