### ISSUE TITLE
Add banner to user and developer facing AMO pages

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#11493]
Until we have a fix for the certificate issue, let's put up a banner on all AMO pages that face users and developers that says: 

.You may be experiencing issues with extensions and themes for Firefox. Please see https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047 for more information."

**Comment by muffinresearch** [comment]
Moving this to add-ons server since the first issue to solve is to add an API for this issue.

**Comment by eviljeff** [comment]
What existing API endpoint the messaging would be added to? Or is there a new API needed?  Or all API endpoints are supposed to return something in the headers?  @kumar303 / @willdurand what would work best for frontend?

**Comment by kumar303** [comment]
@eviljeff we would be introducing a new type of thing. I suggest an endpoint like `/site/` or something to convey site status. 

If a user is signed in (i.e. a cookie exists) then we *always* make a request to [/accounts/profile](https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#profile) on the first page load. It would be nice if that endpoint returned the data we need just so that we don't have to make an extra API request. Obviously, we'd have to make an extra API request for non-signed in users.

**Comment by vcarciu** [comment]
Verified as fixed during push yesterday.
