### ISSUE TITLE
Add-on content review should be multi-lingual and show all language versions

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#11516]
There are two related problems:
1) I can't review the content if I can't see the content. I need to see every language version in order to review all of the descriptions for the add-on.
2) My clients and I often have confusions when the language versions differ. It takes a while to figure out that the complaint I made isn't about the text they changed. This provides a bad experience for the developer.

For the most recent example see https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/buoni-sconto-amazon . I rejected the add-on and the developer was very annoyed because they had added the text I had requested. But I was seeing a different version from what they were seeing.

Yes, the developer made an error in not keeping the versions synchronized, but we need the tools to detect this case.

### What did you expect to happen?

When multiple language versions exist for an add-on each version should be shown during a content review.

**Comment by diox** [comment]
@jvillalobos to prioritize

**Comment by jvillalobos** [comment]
I can see how this can lead to confusion, but it shouldn't be all that common. Not a priority right now.

**Comment by bjherbison** [comment]
From discussion in #13044 this would be a good feature to have as multiple locales is a potential vector for allowing malware to avoid detection by reviewers, although we haven't seen evidence of this yet.

The other justification for this add-on, multi-lingual descriptions with unintentional differences, does happen occasionally but isn't a common issue.

**Comment by diox** [comment]
This raises a bunch of UX questions, so I've split this issue into two, and opened #13910 just to show translations for the add-on name. We'll deal with the other fields later here.

**Comment by bjherbison** [comment]
My original issue description of the issue said to show each version, but may be sufficient to show a list of the language versions, preferably with a link to switch to each version.

**Comment by diox** [comment]
Yeah, I had started going down that route, showing a language selector kinda like we do in devhub, but then it forces the reviewer to do a ton of clicks for add-ons with lots of translations (some popular add-ons have over 20 of them...). There are also a lot of edge cases to consider around what we should show by default, whether to honor language fallbacks or not, etc. The opposite solution would be to show all translations all the time, but that takes a lot of valuable screen space.

While we debate the merits of each approach and try to strike a good balance, #13910 will focus on just showing a list of all translations for the name, because that's simple, doesn't take too much space, and already helps a bit.
