### ISSUE TITLE
Require add-on review/moderation for the first add-on a user submits

### ISSUE THREAD

**Issue by yoasif** [mozilla/addons-server#11544]
Given the [rash of badware](https://www.ghacks.net/2019/05/29/another-malware-wave-hit-the-mozilla-firefox-extensions-store/) appearing on AMO, it'd be good to force a manual review of the first add-on uploaded by a user.

This could be prioritized on the review side to ensure that those would get reviewed first, and lend some additional throttling for people who want to post badware on AMO.

**Comment by wisniewskit** [comment]
Just some drive-by thoughts (not trying to drown the proposal in negativity, but I would want to seriously consider them).

How would this prevent someone from submitting a seemingly-useful low effort addon the first time, then serving malware as usual once they are "trusted"? Or serving a basic, good version, and then stealth-modifying it into badware in a subsequent update? That is, will this really end up being more of a tax on the badware authors than the reviewers and users of addons? Can we be relatively sure?

In addition, who will do all of these extra reviews? Will we be potentially going to be penalizing first-time addon authors in favor of established ones, while also returning to a system where the turn-around time for reviews could increase by days or weeks before an addon appears on AMO? Again, can we find a way to be relatively sure the benefits outweigh such potential risks/costs?

**Comment by jvillalobos** [comment]
Like Thomas pointed out, it wouldn't take long for malware developers to adapt and bypass that solution, which would also tax reviewers significantly and cause problems for developers because of the review bottleneck.

We have various projects aimed at controlling the spam surge, some already underway and others starting in Q3. I don't want to share many details at the moment so that they aren't worked around too quickly. Needless to say, it'll be a permanent cat-and-mouse game and we'll never be able to catch all of the bad submissions.

Blocking on review is not an option right now, unfortunately.

**Comment by yoasif** [comment]
@jvillalobos appreciate the response - it was a passing idea, and I realize that this could be gamed. Glad you have other ideas that you are working on, though! :+1:
