### ISSUE TITLE
User average rating takes deleted ratings into consideration

### ISSUE THREAD

**Issue by mymindstorm** [mozilla/addons-server#11612]
### Describe the problem and steps to reproduce it:

API says my `average_addon_rating` rating is 4.23 - https://addons.mozilla.org/api/v4/accounts/account/13468324/
My only listed addon is rated at 4.5882 - https://addons.mozilla.org/api/v4/addons/addon/authenticator@mymindstorm/

### What happened?

My avg. rating is 4.23

### What did you expect to happen?

My avg. rating is 4.6

### Anything else we should know?

I have an unlisted addon with no ratings, this might have something to do with it.

**Comment by diox** [comment]
It's actually because the `average_addon_rating` score has a bug and it takes into consideration deleted ratings.

**Comment by diox** [comment]
The fix for this will go to production next week on Thursday. After that it will take up to 24 hours for the value to be updated.

**Comment by ioanarusiczki** [comment]
@diox In order to re-create this scenario I created a new account and submitted one add-on which I previously rated and then deleted a review - now I should see in both APIs `"average": 4`

The addons API https://addons-dev.allizom.org/api/v4/addons/addon/storse34manzee67pigehopuse returns `"average": 3.25 `
For now the user profile API https://addons-dev.allizom.org/api/v4/accounts/account/10641890/ returns ` "average_addon_rating": null` . 

I believe I must wait until the value is updated too.

**Comment by diox** [comment]
Yes, the task that updates it runs every day

**Comment by ioanarusiczki** [comment]
@diox Verified on -dev 
average_addon_rating is 4 in https://addons-dev.allizom.org/api/v4/accounts/account/10641890/
