### ISSUE TITLE
The `Addons:RecommendedReview` permission should be more segregated

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11626]
Follow up for #11538 

With the implementation in #11608 the `Addons:RecommendedReview` permission doesn't offer much access when used by itself - you can't access the Reviewer Tools from it for example.
In order to make it usable, one should also have the following permissions:
  -  `Addons:Review` permission - which allows access to Reviewers dashboard and Pre-Review Add-ons, where the Recommended queue is located
  -  `Addons:PostReview` permission to be able to access an add-on review page and perform reviewer actions - Approve, Reject, Reply etc.

We should try to adjust the `Addons:RecommendedReview` permission so it can access the Reviewer Tools and review add-ons without the need of additional permissions.

**Comment by EnTeQuAk** [comment]
So, currently you need `ReviewerTools:View` or `Addons:Review` permission as a base for things like `Addons:PostReview`, `Addons:ReviewUnlisted`, `AddonReviewerMOTD:Edit` etc, unless I'm mistaken.

If that's the case, then personally, I kinda like that idea if having finer grained permissions. I do see the point of being a "useless permission on it's own" but imho that's only a documentation issue, I don't think this kind of "inheritance" should exist for these permissions.

**Comment by jvillalobos** [comment]
The `Reviewers: Add-ons` user group only has `Addons:PostReview`, which is sufficient permissions to access the tools and the post-review queue. Same for content reviewers with `Addons:ContentReview`. We refactored groups and permissions (in https://github.com/mozilla/addons-server/issues/6611, I think) so that it'd be easier to manage those groups.

So, while I don't expect there to be reviewers who are exclusively Recommendations reviewers, the issue is still valid to keep consistency across review permissions.
