### ISSUE TITLE
Require email confirmation for first set of API keys

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11635]
From the [Account Submission Restrictions PRD](https://docs.google.com/document/d/1FfFcydrcm_TC4sQHXWQfJg2_11RvvYUANDy0hqMlH7U/edit#).

The first time a developer goes to the [API Keys page on AMO](https://addons.mozilla.org/developers/addon/api/key/), the `Generate new credentials` button shouldn't create them immediately. Instead, the following should happen:

* The page displays a message saying "A confirmation link will be sent to your email address. After confirmation you will find your API keys on this page."
* An email is sent with a temporary confirmation link. It should be possible to introduce a delay in sending this email, to protect against spamming.
* The link should point back to the API Keys page, where the keys should now be shown.

After confirmation, re-generating keys shouldn't require confirmation again. However, it should be possible to reset the confirmation status of any or all developers in order to require confirmation again. By "possible" I just mean it should be visible in the user admin and it should be easy to ask ops to change this flag for a group of users if needed.

**Comment by diox** [comment]
> It should be possible to introduce a delay in sending this email, to protect against spamming.

Is it a globlal delay? If it is, can it require a redeploy to be changed?

**Comment by diox** [comment]
@jvillalobos Ok. Can you give me the email subject and body ? I thought I had seen it somewhere but I must have mixed that up in my mind with the author confirmation stuff.

**Comment by diox** [comment]
@jvillalobos @caitmuenster In https://github.com/mozilla/addons-server/pull/12230#discussion_r319486141 @eviljeff raised a good point: if someone receives the email but hasn't requested it, unless they somehow forgot what they did, it's likely someone has gained access to their account or managed to hack AMO, and it's bad news. Should the sentence about receiving the email without having requested it be more scary? I was thinking of changing it to simply:
> If you didn't request this, please notify amo-admins@mozilla.com.

**Comment by jvillalobos** [comment]
Makes sense!

**Comment by diox** [comment]
Note for QA: if you delete your credentials, but had not gone through the confirmation phase because your account is old enough, then you're required to go through it. Otherwise, if your key had already been generated, you're good (we're not invalidating existing keys).

**Comment by ioanarusiczki** [comment]
@diox 
- I tested this on dev and stage and the e-mail si generated immediately after the API Keys are requested but from what I understand from the [comment](https://github.com/mozilla/addons-server/issues/11635#issuecomment-524930429) above it can be modified later on.
The link points back to the API Keys page where the "Confirm and generate new credentials` button is available and if clicked the API Credentials are displayed. 

![Generation API Keys](https://user-images.githubusercontent.com/33448286/64262359-a7170c80-cf36-11e9-80fe-b5f3faca2f4e.gif)

- Revoke and regenerate credentials will not require e-mail confirmations.

Two things are unclear to me:

> However, it should be possible to reset the confirmation status of any or all developers in order to require confirmation again. By "possible" I just mean it should be visible in the user admin and it should be easy to ask ops to change this flag for a group of users if needed.

Is this part going to be implemented because I did not see on userprofiles from admin such as  /admin/models/users/userprofile/11686839/change/ any flag related to API Keys.

> Note for QA: if you delete your credentials, but had not gone through the confirmation phase because your account is old enough, then you're required to go through it. Otherwise, if your key had already been generated, you're good (we're not invalidating existing keys).

I'm not sure I understood what you meant. The way I tried testing this: I generated API Credentials and then deleted the account (conditions is no addons or themes added so I used a new account).  If I sign back in and go to the API keys page then I must go through the entire confirmation process again.  For an older account with already generated API credentials if I access the page I will see those, no other action is needed.

**Comment by diox** [comment]
>> However, it should be possible to reset the confirmation status of any or all developers in order to require confirmation again. By "possible" I just mean it should be visible in the user admin and it should be easy to ask ops to change this flag for a group of users if needed.
> Is this part going to be implemented because I did not see on userprofiles from admin such as /admin/models/users/userprofile/11686839/change/ any flag related to API Keys.

You're right, I forgot to add it to the admin. Can you file another issue for this ?

>> Note for QA: if you delete your credentials, but had not gone through the confirmation phase because your account is old enough, then you're required to go through it. Otherwise, if your key had already been generated, you're good (we're not invalidating existing keys).
> I'm not sure I understood what you meant. The way I tried testing this: I generated API Credentials and then deleted the account (conditions is no addons or themes added so I used a new account). If I sign back in and go to the API keys page then I must go through the entire confirmation process again. For an older account with already generated API credentials if I access the page I will see those, no other action is needed.

My note is only for older accounts that had already generated API credentials (from before we added the confirmation) and delete those credentials.

**Comment by ioanarusiczki** [comment]
@diox Sorry for misunderstanding. I initially thought I must delete the account instead of revoking the API Credentials. 
Yes, it's the same process for an old account with already generated API credentials: confirmation is required if I revoke and request new credentials.
