### ISSUE TITLE
Delay listed add-on auto-approval

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11653]
Part of [this project](https://docs.google.com/document/d/16PDUnuUGs0iT3iVlYjS2idc59OHIxEwVtZaowcMJiao/edit#).

We want to introduce a delay of 24 hours for auto-approval of _new_ listed add-ons on AMO. This will give content and code reviewers more time to cover recent submissions and reject any obvious ones. This does **not** apply to language packs.

**Comment by wagnerand** [comment]
Blocking on content-review would be easier to implement and more effective. Was that option considered and why did we discard it?

**Comment by jvillalobos** [comment]
I updated the requirements above based on feedback. Specifically, this applies only to new listed add-ons, and the delay will be increased to 24 hours.

**Comment by diox** [comment]
Should we update the text displayed after submission too to mention this delay?

**Comment by jvillalobos** [comment]
I remember someone saying that "shortly" is a relative term :). I think the current wording is fine for now, we don't give any guarantees about auto-approval times.

Another note: please let us know when this is close to landing so reviewers are aware.

**Comment by diox** [comment]
@jvillalobos it should go to prod next week. When it happens, if someone visits the review page they will see `Delayed because it's the first listed version` as (one of) the reasons the add-on wasn't auto-approved.

**Comment by jvillalobos** [comment]
Thanks. @kewisch and @wagnerand might want to notify reviewers about this.

**Comment by diox** [comment]
@jvillalobos There is catch I didn't anticipate: if we delay auto-approval for the first version... then the add-on won't appear in either auto-approved or content approval queues, since those contain add-ons that have been auto-approved... Not sure what's the best way to address this.

**Comment by jvillalobos** [comment]
I think it's okay from a product perspective for the content review queue to show add-ons in a pending review state. I don't know if we've contemplated what happens if there's a content rejection while an add-on is in that state.

Not showing it in the auto-approved queue makes sense. It would probably lead to some mixups. Admins can check the content queue if they want to spot-check things pending review.

**Comment by diox** [comment]
Ok, I'll make the content review queue show add-ons in pending review state after I'm done fixing the queries for them in https://github.com/mozilla/addons-server/issues/11733

**Comment by AlexandraMoga** [comment]
Here are my test results after verifying this on -dev:

- new extensions, dictionaries and search tools submissions are now affected by the 24h auto-approval delay; the review page for add-ons in this state will show a _Delayed because it's the first listed version_ message; while the add-ons are under the delay flag, they won't be listed in the Auto-approved queue.
Here is an example of an add-on submitted on July 1st and approved on July 2nd at roughly the same hour: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/project-delay-approval-no-2
- language packs are not impacted by the delay - they are still being auto-approved as before
- if another version is submitted while the add-on is under the delay approval flag, the 24h clock is not reset - the computation takes into consideration  the time of the first version submission 
Example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/project-delay-approval-no-1
- once the auto-approval script runs on these add-ons, they will be present in the auto-approved queue
