### ISSUE TITLE
Double entry for the Abuse Reports section on the /reviewers/abuse-reports/ page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11775]
**STR**

1. Log in to AMO stage with a reviewer account
2. Open to the Auto-approval queue and select an add-on to review
3. Click on Abuse reports to view all the reports for the selected add-on - see https://reviewers.addons.allizom.org/en-US/reviewers/abuse-reports/botblockerlocale

**Actual result:**
There are two entries for the Abuse reports section

**Expected result:**
Abuse reports section appears only once

**Notes:**
- reproduced on -dev and stage with Fx67, WIn10x64

![double abuse](https://user-images.githubusercontent.com/31961530/60598919-3b89b500-9db6-11e9-9dd7-980e8803ea3e.png)

**Comment by Patil2099** [comment]
Can I work on this @eviljeff ?

**Comment by eviljeff** [comment]
I think you just need to drop the abuse report inclusion from the specific abuse-reports template, but I've not looked through the code.

**Comment by Patil2099** [comment]
I will look through that template and inform you about it. @eviljeff

**Comment by Patil2099** [comment]
@eviljeff  I saw that reviewers/addon_details_box.html had a abuse reports table in it so I removed the table from abuse_reports.html because addon_details_box.html was included at various places but the abuse_reports.html was not so I changed abuse_reports.html. The expected result was achieved by it.

**Comment by Vishal19111999** [comment]
Hey! is this repo good for beginners? I have experience in python and C++.

**Comment by diox** [comment]
Sure. This is probably just a template inclusion problem, @Patil2099 already worked on fixing this in https://github.com/mozilla/addons-server/pull/11961 but we closed the PR because they couldn't get addons-server to work locally. If someone could test that fix locally or even write a unit test in reviewers/tests/test_views.py (maybe just modifying TestReview.test_abuse_reports() is enough) that'd be great.

**Comment by diox** [comment]
Taking this myself, because the right fix is actually slightly more involved than that.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

There's only one entry for abuse reports now:
![2019-09-16_14-15-17](https://user-images.githubusercontent.com/31961530/64953794-75823780-d88c-11e9-8920-b62dc7b9de8c.gif)
