### ISSUE TITLE
Implement admin for Secondary Hero Shelf Promo modules

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11780]
Part of [this PRD](https://docs.google.com/document/d/12aD_v5AOj1Y6VmT4xOuyNcrKfZxqhP8R_AOHroQVLV8/edit#).

The Secondary Hero Shelf in the homepage will have three promotional modules with an icon, some text and a Call to Action:

<img width="623" alt="Screen Shot 2019-07-03 at 4 22 47 PM" src="https://user-images.githubusercontent.com/62568/60628507-ee561500-9dae-11e9-840b-d64f60697694.png">

We need an admin tool for editing the contents of these modules:

* Icon, chosen from an existing pool
* Description, up to 50 characters, localized
* Call to Action, up to 20 characters, localized
* URL

The localization should work in the same way as the copy for Recommended extensions. The pool of icons will probably be [these](https://design.firefox.com/icons/viewer/#), but please confirm with Product when you start working on this :). There will always be exactly 3 modules.

The first version of this module will have the same three "guide page" modules that we currently have on the homepage (Call to Action is "Learn More", icons are TBD).

**Comment by muffinresearch** [comment]
See attachment for SVG icons from Scott: [icons.zip](https://github.com/mozilla/addons-server/files/3411347/icons.zip)

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx68

Adding to the results mentioned in https://github.com/mozilla/addons-server/issues/11779#issuecomment-519093310:
- each secondary hero needs to have three modules attached to it, otherwise the form can't be saved
- each module needs to have a corresponding icon and description, otherwise the form can't be saved 
- all the enabled entries are returned by the `/v4/api/hero/secondary/`

There is an issue with the icons and their radio buttons, for which I filed #12097
