### ISSUE TITLE
Extension risk score should be recomputed regularly

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11790]
I recently noticed an extension with lots of bad ratings and abuse reports, but its risk score was only 3. That's because they only submitted one version and the score was only computed on submission. This makes the risk score unreliable, especially considering all the one-version extensions we have.

A couple of ways this could be fixed:
* Recalculate the risk score for the current version when the metadata factors change. I think that's ratings, abuse reports, and users (I suppose users can be ignored for this).
* Recalculate the risk score for the current version on a regular basis (weekly?).

/cc @wagnerand @kewisch

**Comment by diox** [comment]
Do you need this for versions that have already been confirmed, or just those in the post-review queue ? If that's the latter, we have a command that does this, `process_addons --task=recalculate_post_review_weight`. We could run that regularly if we want - it can be a little costly depending on the number of add-ons, but weekly should be fine.

**Comment by jvillalobos** [comment]
I think this would be useful to run for the ones that have been confirmed too. Increased abuse reporting might make us reconsider review decisions in the future.

**Comment by diox** [comment]
We probably need to make the script a little smarter then, cause it might be doing too much extra work right now for such a volume of data.

**Comment by EnTeQuAk** [comment]
I started working on this but I'll move this to the next milestone as I doubt I'll be able to land this in 2019.07.18 - I'll try nonetheless though.

**Comment by EnTeQuAk** [comment]
So, from what I read in the code so far I started to work on a task that tries to come up with a list of add-on ids that need a recalculation of the risk score by looking at abuse reports and ratings that happened in the last six weeks for abuse reports and a year for negative ratings and simply do a full recalc for those (to re-use the task and code we already have).

Ideally the recalc task will only be launched when the risk score changed significantly enough.

**Comment by EnTeQuAk** [comment]
@jvillalobos in https://github.com/mozilla/addons-server/pull/11950 I implemented this by looking only at abuser reports and ratings for indicators if the score needs to be recalculated or not.

Users are not taken into account, as this would make the PR much more complicated and it could be done in a follow-up.

For that to happen we'd need to know if we actually want to issue recalculation based on user-counts (`average_daily_users`) and what thresholds are important. I can file a new issue if we indeed want to pursue this.

**Comment by jvillalobos** [comment]
I think we can skip recalculating for ADI changes for now.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk are you going to run the re-calculation script on -dev?

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk are you going to run the re-calculation script on -dev?

Yes, I will be running it on -dev. Ideally we should prepare an already confirmed (public) add-on and report for example an abuse against it so that we could test that it actually works.

I can do that, or do you want to to directly confirm it's working?

The same scenario maybe with a rating. The descriptions in https://github.com/mozilla/addons-server/commit/1e0351c37c100f191526ba31730bbfd28db233b8#diff-4be2660a6fb720e5c8c300f646f031d7R231 should describe what scenarios are being considered for a re-calculation of the risk and which aren't.

What would work best for you?

**Comment by AlexandraMoga** [comment]
@EnTeQuAk I've tried to summarize my results in a report which you can inspect [here](https://docs.google.com/spreadsheets/d/1IWSpL5_VR48XRF4sAssT9xD8MygFeOiv12F6bBsFCWc/edit#gid=0)
*Note that I've highlighted with red the weights that don't add up and with green those that look correct. 

The basis of my analysis was this statement:
>"recent" means, we take abuse reports and ratings into account that have been created *after* the latest update to the auto-approval summary object, which usually is the date of when the (auto-)-approval has happened. 

So far I have gathered the following observations:
- bad ratings don't seem to have been taken into account for the risk re-calculation
- weight is being recalculated for other versions as well, not just the current version (see [this](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/homepage) for a clear example)
- each abuse report posted after the last approval date counts as 15 weight points, but the cumulative weight coming from abuse reports doesn't seem to ever exceed 100 points

There are also some questions;
1. Does a 'Confirm Approval' or 'Rejection' count as a "latest update to the auto-approval summary object" or are these review actions not considered for weight recalculation? Judging by the test results, they do not seem to be taken into consideration. 
2. From your statement:
>if we are re-calculating the risk, that updated date will be the current date, so that we don't recalculate the same thing over and over again

Does it mean that add-ons which had their weight recalculated should also have a new `last_updated` date? If that is the case, this doesn't look like it's happening.

**Comment by EnTeQuAk** [comment]
> each abuse report posted after the last approval date counts as 15 weight points, but the cumulative weight coming from abuse reports doesn't seem to ever exceed 100 points

That is perfectly fine and how it has been working since forever.

> Does a 'Confirm Approval' or 'Rejection' count as a "latest update to the auto-approval summary object" or are these review actions not considered for weight recalculation? Judging by the test results, they do not seem to be taken into consideration.

Indeed, approval and rejection actions update the `modified` date ot the approval-summary object so should be taken into account. E.g, the following scenario should be working:

* Developer submits a new version on Monday
* The version get's auto-approved shortly after
* A new abuse report is being reported against that version
* A reviewer rejects t hat version on Tuesday after the report

If the script will run on Saturday, it won't recalculate the weights for that add-on.

> Does it mean that add-ons which had their weight recalculated should also have a new last_updated date? If that is the case, this doesn't look like it's happening. 

No, the date I'm talking about is the actual `modified` date of the `AutoApprovalSummary` where all the approval data is being stored in. That is not exposed anywhere.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk 

> Indeed, approval and rejection actions update the `modified` date of the approval-summary object so should be taken into account. E.g, the following scenario should be working:

The following two examples have been recalculated, but according to what is expected, they shouldn't have been included:

[Example 1](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/perspicacious1)
 - submitted and auto-approved on Dec. 4, 2018, 12:15 p.m
 - has received 5 abuse reports from the auto-approval time until July 30, 2019, 6:36 a.m.
 - Approval is confirmed on July 30, 2019, 6:40 a.m.
 - recalculation task is run on July 31, 2019, around  1:30 p.m.
 - add-on initial weight is 0; recalculated weight is 75

[Example 2](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/source)
 - last version submitted and approved on March 5, 2018, 1:10 p.m.
 - has received 11 abuse reports from the auto-approval time until July 30, 2019, 6:37 a.m.
 - Approval is confirmed on July 30, 2019, 6:39 a.m.
 - recalculation task is run on July 31, 2019, around  1:30 p.m.
 - add-on initial weight is 30; recalculated weight is 190 - out of which 100 points from abuse reports

If the recalculation task listened to the "Confirm approval" date (July 30, 2019, 6:40 a.m, respectively July 30, 2019, 6:39 a.m.) it means that weight should not have increased, since there are no other reports submitted after those dates. 


> bad ratings don't seem to have been taken into account for the risk re-calculation

This was another observation I had. There was no weight coming from bad ratings for any of the add-ons I've analyzed:
- https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/google-video-dev - received **5** bad reviews in the past 3 days
- https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/proxy-settings-test-dev - received **7** bad reviews in the past 3 days

**Comment by EnTeQuAk** [comment]
Short update on that. With #11997 I disabled the weekly crontab so that we have more time to test this and fix issues if they occur.

So, this lands this week but it won't be executed until we decide to do that on our own. Probably not till the next tag.

#11997 Fixes the recalculation to only take the current version into account (once merged).

I'll check the mentioned examples later today.
