### ISSUE TITLE
Use a permission instead of an email check to allow submission of langpacks

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11793]
Firefox release automation was blocked by our new langpack restrictions (https://github.com/mozilla/addons-server/issues/11788) today a few hours after it went live. 

Their email is already in `ADDON_UPLOAD_RATE_LIMITS_BYPASS_EMAILS` to bypass rate limiting, but unfortunately it's a mozilla.org email, not a mozilla.com one, and we can't allow all mozilla.org emails to submit language packs, because of mailing lists, so when we implemented #11788 with a suffix check it didn't include their email, and that's causing the problem.

The proper solution is to use a permission + group instead of an email check, and make their user part of that new group. As a follow-up we could even remove `ADDON_UPLOAD_RATE_LIMITS_BYPASS_EMAILS` and make that check use *another* permission instead, giving it to the same group (gives us flexibility if we ever need to expand use of that bypass feature)

**Comment by tomprince** [comment]
The failure of the release automation is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1563651

**Comment by EnTeQuAk** [comment]
Side-note: Using a group also gives us more freedom to allow trusted developers for 3rd-party langpacks in the future maybe.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I tested on -dev and -stage with a new gmail account then with irusiczki@mozilla.com account. - FF67(Win10)
When the accounts don't have the  `LanguagePack:Submit` permission I receive at submission a red error message ` You cannot submit a language pack`.

The Admins - can submit them if they're not added in the Submit language packs (auto signed) but I believe that is expected because they should have all rights included.
