### ISSUE TITLE
Warnings related to django middleware in local dev

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11819]
Running `make initialize_docker`, we can see the following warnings in the logs:

```
WARNINGS:
?: (debug_toolbar.W003) debug_toolbar.middleware.DebugToolbarMiddleware occurs before django.middleware.gzip.GZipMiddleware in MIDDLEWARE.
	HINT: Move debug_toolbar.middleware.DebugToolbarMiddleware to after django.middleware.gzip.GZipMiddleware in MIDDLEWARE.
```

**Comment by diox** [comment]
Yeah, this will only happen locally, because we do this in `settings.py` (used only for local installs):
```python
MIDDLEWARE = ('debug_toolbar.middleware.DebugToolbarMiddleware',) + MIDDLEWARE
```

To fix this, we should use logic similar to what `debug_toolbar` is doing (including checking for a class inheriting from `GZipMiddleware` and not directly `GZipMiddleware` itself, cause we're using a custom one) to find where the gzip middleware is and insert debug toolbar after it.

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @diox

**Comment by junngo** [comment]
Hello @diox :)

I have thought about this Issue. I thought proper function place where is end of line in "settings_base.py". But I'm not Sure.
Can you guide me about proper function place?

If I understand right, I gonna make function call format in settings.py such as bottom example:
`MIDDLEWARE = insert_debug_toolbar(MIDDLEWARE)`

**Comment by diox** [comment]
This *cannot* go in `src/olympia/lib/settings_base.py`, because that's the settings base (eh) file for all environments, including production. This is why I mentioned `settings.py` above, which is different and only applied to local environment.

The rest of your approach sounds fine, just don't do it at the end,  replace the line in `settings.py` that's already inserting the `debug_toolbar.middleware.DebugToolbarMiddleware` in `MIDDLEWARE`.

**Comment by junngo** [comment]
Thanks for guiding me kindly. 
Can I try to solve it?

**Comment by diox** [comment]
Sure! I assigned it to you, go ahead.
