### ISSUE TITLE
Don't show "Custom heading" in the discovery card

### ISSUE THREAD

**Issue by brassy-** [mozilla/addons-server#11817]
On the discovery pane and on the recommeded section in extensions manager, we're not going to display the heading. 
![recommeded](https://user-images.githubusercontent.com/6309827/60988020-190e1380-a343-11e9-915a-8b3c874b9277.png)

cc @devaneymoz if more details are needed.

**Comment by devaneymoz** [comment]
If we're dropping the Custom Headline I'd like to go into admin and manually edit the Custom Descriptions (i.e. if there's important wording from the former headline that we want to move into the description). When would this change take place so I can try to coordinate timing?

**Comment by mstriemer** [comment]
I just mocked the API response from AMO to entirely remove the `heading_text` property and it looks fine. No console errors, bold text is hidden.

![Screenshot 2019-07-11 14 07 28](https://user-images.githubusercontent.com/211578/61078151-a2762200-a3e5-11e9-8f80-65e2946bde34.png)

**Comment by muffinresearch** [comment]
> If we're dropping the Custom Headline I'd like to go into admin and manually edit the Custom Descriptions (i.e. if there's important wording from the former headline that we want to move into the description). When would this change take place so I can try to coordinate timing?

@devaneymoz For now we don't want to remove any data from the DB. To fix this issue we only need to with-hold `heading_text` from the API responses as that will get the desired output with the most minimal changes.

The other data is still in use by the HTML disco pane.

We can clean out the data when either:

* The new disco pane reaches an ESR
* Or we change the HTML disco pane sooner.

I'd prefer the former since that avoids making changes to a soon to be deprecated property. But if keeping the data formats around just for that are a huge problem editorially we should talk about that separately.

**Comment by devaneymoz** [comment]
@muffinresearch Thanks for the breakdown of options. I'll flag for us to discuss in tomorrow's x-func.

**Comment by muffinresearch** [comment]
> @muffinresearch Thanks for the breakdown of options. I'll flag for us to discuss in tomorrow's x-func.

Sounds good. 

For the fix here, we just need to remove `heading_text` from the discovery API responses, this way we avoid needing a Firefox release to get the desired result. 

To QA this we'll need to make sure:

* All firefox releases with the recommended section work without `heading_text`in the API response.
* The html based disco pane used by older clients is unaffected.

@EnTeQuAk would you have time to take a look at this?

**Comment by muffinresearch** [comment]
Having spoken further with @devaneymoz the issues with just removing `heading_text` is that it will result in some cases where the description doesn't necessarily follow without the heading:

So there's two options for how to deal with this:

**Option 1**

- Update the HTML disco pane to be more similar to the new recommendation cards in Firefox and not use heading data.
- Make the change to withhold heading_text from firefox in the API.
- Update editorial descriptions as needed so anything missing by removing the heading is there in the description.
- Clean-up the API and remove all traces of headings since we're not using them anywhere.

**Option 2**

- Just remove the `heading_text` from the API.
- Update the description, to ensure it makes sense for the new recommendations knowing that the old disco pane is still showing the copy for the original heading.
- Once the old disco pane is shut down we can then remove the headings.

Option 1 make things consistent sooner and also means the admin previews would match up everywhere once the headings are removed. 

Option 2 is less steps and avoids spending time on the AMO-based disco pane which probably can be shut-down in October once ESR 68.2 is out, but other than that there's not a lot in it.

@jvillalobos any preference?

**Comment by jvillalobos** [comment]
I think either option is okay. It sounds like Option 2 is less work and the only problem is wonky copy on old disco panes, for a limited time. I'd favor that.

**Comment by devaneymoz** [comment]
I'm fine with option 2 as well, and with limited time wonky copy. 

My only remaining question is timing. Should I simply adjust copy at my earliest available opportunity? Is there an urgency to remove the heading_text from the API? 

(I estimate it shouldn't take me more than a half-day to adjust copy for 100-ish extensions in admin.)

**Comment by muffinresearch** [comment]
> I'm fine with option 2 as well, and with limited time wonky copy.
> 
> My only remaining question is timing. Should I simply adjust copy at my earliest available opportunity? Is there an urgency to remove the heading_text from the API?
> 
> (I estimate it shouldn't take me more than a half-day to adjust copy for 100-ish extensions in admin.)

I would wait until the heading is gone, since then you'll be working with the desired end result. 

The only other consideration is do we want to wait until new recommendations are closer to being in release? [Which on the basis this is out in 69 should be early September](https://wiki.mozilla.org/Release_Management/Calendar).

**Comment by muffinresearch** [comment]
> > I'm fine with option 2 as well, and with limited time wonky copy.
> > My only remaining question is timing. Should I simply adjust copy at my earliest available opportunity? Is there an urgency to remove the heading_text from the API?
> > (I estimate it shouldn't take me more than a half-day to adjust copy for 100-ish extensions in admin.)
> 
> I would wait until the heading is gone, since then you'll be working with the desired end result.
> 
> @devaneymoz @jvillalobos The only other consideration is do we want to wait until new recommendations are closer to being in release? [Which on the basis this is out in 69 should be early September](https://wiki.mozilla.org/Release_Management/Calendar).

Alternatively if we don't mind we can just make this change now and update the data to make it work.

**Comment by muffinresearch** [comment]
@EnTeQuAk - could you liaise with Scott next week to see about making the change to withhold `heading_text `from the API response? I'm thinking if this can go out in the push for the 8th that should be fine, which will give you until to the 6th August to land it.

**Comment by devaneymoz** [comment]
If we're landing this to go live on 8 Aug, I would wait to adjust copy just a day or two beforehand, since copy changes made in admin reflect pretty quickly on site.

**Comment by EnTeQuAk** [comment]
@devaneymoz this is on-target to land this Thursday.

**Comment by AlexandraMoga** [comment]
I have verified the new discovery layout on stage, with Firefox versions that support Recommendations (Release 68, Nightly 70) and versions that still use the old Discovery pane (FF version < 68, including ESR 60).

With the `heading_text` property excluded from the `/api/v4/discovery/` endpoint, the two layouts are looking like this:

1. Add-on card in Discovery with Recommendations (Firefox >=68)
![image](https://user-images.githubusercontent.com/31961530/62612854-fc98d300-b910-11e9-81fc-77152c8ca0e0.png)


2. Add-on card in old Discovery Pane (Firefox < 68)
![image](https://user-images.githubusercontent.com/31961530/62612841-f60a5b80-b910-11e9-9482-5c140354368c.png)
