### ISSUE TITLE
create API to expose primary shelf config to frontend

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11842]
all the admin model data needs to be exposed in a single API endpoint for frontend to consume

**Comment by AlexandraMoga** [comment]
@eviljeff I tried to figure out what can be tested at this point, but I can't find much.
I've noticed the new [`/hero/`](https://addons-server.readthedocs.io/en/latest/topics/api/hero.html?highlight=hero#hero-shelves) endpoint but apart form verifying that the api calls are working, there isn't any data to validate.
I've also tried to generate data from the new ["Hero"](https://addons-internal.stage.mozaws.net/en-US/admin/models/hero/primaryhero/add/) admin model but this tool doesn't seem to be finished yet. 

If there is anything else that I could verify at this point please let me know.

**Comment by eviljeff** [comment]
It will be easier when #11830 is complete, yes, but it should be possible now to create a `PrimaryHero` instance, link it to a `DiscoveryAddon` and set some details.  Nothing is validated though, and the details for the `DiscoveryItem` are only viewable/editable via the discovery admin at this point.

It won't be used on production for quite a while so there's no urgency to verify.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev 
Both endpoints are returning the add-on details  with the hero customization added in Discovery items. 
`GET /api/v4/hero/`  - brings only one add-on randomly selected from the pool of Enabled primary heroes
`GET /api/v4/hero/primary` - brings the list of all Primary heroes enabled at a given moment

*Note: the `description` field will return the Custom description string added for the discovery item whenever this information is available. Otherwise, `description` will default to the add-on summary.
