### ISSUE TITLE
Allow addons with only unlisted versions to be linked externally on Primary Hero shelf

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11882]
From https://github.com/mozilla/addons-server/issues/11830#issuecomment-513022753
> It should also be possible to feature unlisted  Recommended extensions in the homepage (and we most likely will at  launch). The Call to Action will point to the homepage URL, so having  one set should be another requirement to enable the checkbox in the  admin, for unlisted ones.

Filing separately because it's a follow on from #11842 - but makes the issue more complicated.

**Comment by AlexandraMoga** [comment]
Unlisted add-ons are accepted as Primary heroes in Discovery items by marking the `Is external` checkbox
The unlisted add-on needs to have a homepage set in order to be enabled, otherwise the following error will be thrown:
![image](https://user-images.githubusercontent.com/31961530/62459415-f5928900-b787-11e9-86f0-f7200d6f9f2a.png)

Unlike listed add-ons, pure unlisted add-ons don't have to be recommended in order to be enabled, but looking at https://github.com/mozilla/addons-server/issues/11284#issuecomment-513879980 it seems that this situation is expected (at least at the moment).

@eviljeff regarding the api response for `/api/v4/hero/primary/` for unlisted extensions, I've noticed that the `external` object doesn't have a reference to the add-on `author`. Shouldn't we have that, in case we'd like to expose this field in the frontend?

- api response for unlisted primary hero

```
{
    "primary": {
        "description": "<blockquote>Updates tests</blockquote>",
        "external": {
            "id": 616946,
            "guid": "{2ae22fd0-2e6a-4805-98d5-ab0cf640ee13}",
            "homepage": {
                "en-US": "https://google.com"
            },
            "name": {
                "en-US": "Recommended updates in about:addons"
            },
            "type": "extension"
        } 
```

**Comment by eviljeff** [comment]
> I've noticed that the external object doesn't have a reference to the add-on author. Shouldn't we have that, in case we'd like to expose this field in the frontend?

I didn't see the author listed in the mocks, and as we aren't linking to an add-on that will have a listing page, the user profile page might not exist.  If @bobsilverberg wants it adding to the response I could add it though.

**Comment by jvillalobos** [comment]
I would prefer that we don't disclose authors for unlisted add-ons, since they might not expect to be exposed that way. We can revisit this if the design of the hero area changes.
