### ISSUE TITLE
Stop sending email for abuse reports

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11958]
The introduction of abuse reports in `about:addons` has caused the volume to increase to a level that we can't manage by scanning the emails being sent to the admins list. Nobody is looking at the emails anymore, so let's get rid of them. We have better ways to go through them now.

**Comment by wagnerand** [comment]
QA: When an abuse report is being created in Firefox or on AMO, it should still be recorded on AMO as usual, but no email should be sent out.

**Comment by ioanarusiczki** [comment]
@wagnerand I tested this on -stage with FF68(Win10). Here are my results:
- I sent a report from AMO (from the extension/theme detail page) and checked the fake mail where I did not find e-mails sent to amo-notifications+abuse@mozilla.org. 
The reports are available in  the admin tool  Abuse Report en-US/admin/models/abuse/abusereport/ 
Same if I tested with Postman - through API. 

- When I send a report from about:addons (from the stage environment, I changed the `extensions.getAddons.discovery.api_url` pref to see the stage recommendations). I did not receive e-mail for abuse reporting.
The sent reports from about:addons are not displayed into the admin tool report  en-US/admin/models/abuse/abusereport/.  I don't know if that's the actual expected behavior.

**Comment by wagnerand** [comment]
@ioanarusiczki I am not sure that Firefox pref will also change the abuse report endpoint, so maybe that abuse report sent from Firefox reached prod. Can you tell me what the add-on ID is you reported abuse for?

**Comment by ioanarusiczki** [comment]
@wagnerand 
Stage ID 9609 Name: Ghostery 
https://addons.allizom.org/en-US/firefox/addon/ghostery/
I also tried with https://addons.allizom.org/en-US/firefox/addon/mitzuluc/
ID 620313

**Comment by wagnerand** [comment]
@ioanarusiczki Yes, I can see your abuse report for Ghostery on prod. The abuse report message is "This is a test for admin tools stage - no e-mail should be received".

**Comment by ioanarusiczki** [comment]
@wagnerand Thanks for checking!
I receive the abuse reports in stage after I modified `extensions.abuseReport.url`
