### ISSUE TITLE
Create a task to run `yara`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11983]
We need a new Celery task to run yara. The task will:

- only target web extensions
- ~~unzip file uploads~~ edit: we can directly read the content of (each file of) the xpi
- compile the yara rules
- run yara on all the files ~~of the unzipped upload~~
- create a new `YaraResult` (cf. #11981) object
- ~~delete the unzipped file upload~~

If an exception occurs, we should log it but we should not raise, otherwise it will break the submission flow (and that's not what we want).

In addition to that, we also need a waffle ~~flag~~ switch to enable/disable this task. **– Edit:** this will be implemented in https://github.com/mozilla/addons-server/issues/12006

Important: This task should be part of a Celery chord once we upgrade to Celery 4.2.

**Comment by willdurand** [comment]
> In addition to that, we also need a waffle flag to enable/disable this task.

Do you think I can use the waffle flag in the task directly? (early returning if the flag is `off` for instance)

**Comment by willdurand** [comment]
> In addition to that, we also need a waffle flag to enable/disable this task.

@diox Do you think I can use the waffle flag in the task directly? (early returning if the flag is `off` for instance)

**Comment by diox** [comment]
Use a switch instead of a flag (we don't need the added complexity of the flag). 

Ideally, we wouldn't even add the task to the flow if the switch is off. If it makes your life easier, you could do an early return in the task instead, but that means firing up an extra useless task that's going to sit in the celery queue, so best to avoid it if possible.
