### ISSUE TITLE
Optimize SQL for discovery items

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#12035]
![Screenshot from 2019-08-06 08-49-32](https://user-images.githubusercontent.com/139033/62517490-cb90a380-b827-11e9-92d6-3c33c8bbefee.png)

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Is this qa not needed?

**Comment by EnTeQuAk** [comment]
Not quite, you can make sure the discovery items changelist in the admin works as expected. Ideally it should be a hell lot faster than before. Nothing changed from a logic point of view.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I verified this issue on django admin stage - FF68 (Win10). 

- I did not have problems while editing the discovery items. I can't tell if there's a difference in speed terms because as long as I remember testing I never had a problem with discovery moving slow or slower.
- I've done some functional testing to see how it works. 
One observation:
Editing `Custom Addon Name` and `Custom Heading`  fields won't bring visible changes in the Recommendation Tab. Only `Custom description` works and displays content.  I remember filing something about a while ago (I'm going to check it).
