### ISSUE TITLE
Provide more granular error messages for generic submission failure

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12054]
Our generic submission failure reason is:
_Sorry, we couldn't load your WebExtension._

This also happens to be our second-most failure reason, covering about 20% of all failures. Let's try and be more granular about the actual error to give developers a chance to understand what went wrong and fix it, and avoid reports like https://github.com/mozilla/addons/issues/1083.

**Comment by diox** [comment]
There are 3 main uses of this error message:
- Unsupported file type.
- Bad zip file (invalid or corrupt zip)
- Unhandled exception thrown while linting (IO Error, or Memory error, or timeout)

In the first 2 cases, we actually insert a validation message on top of the generic one, explaining what happened. In the 3rd, because it's a system-level error, we don't disclose additional information, but we do log the actual exception.

Maybe in the first 2 cases we should *replace* the generic error message with the one we currently add, but besides that, I'm not sure what to do.
