### ISSUE TITLE
Allow arbitrary values for `addon_install_method` in the Abuse Reports API

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12060]
The Abuse Reports API currently allows a limited set of values for `addon_install_method`, and doesn't accept reports using other values. On the Firefox side this was solved by defaulting reports to the "Other" method if the value didn't fit the predefined set. Some changes happened in those values since first established that have caused lots of reports to be classified under "Other".

To address this problem, we should do the following:
* Remove the value restriction on the API and allow arbitrary values.
* On the AMO side, map unknown values to "Other", but log those values so they can be looked at and new install methods are added when necessary.
* It might also be a good idea to do the `-` -> `_` mapping that [Firefox currently does](https://searchfox.org/mozilla-central/source/toolkit/mozapps/extensions/AbuseReporter.jsm#152-185).
* Add the new constants that are missing, in preparation for Firefox sending them. @rpl should know what those are.

**Comment by jvillalobos** [comment]
I filed the Firefox work on [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1572173).

**Comment by rpl** [comment]
@diox, as I have been discussing yesterday with @jvillalobos, on the Firefox side we have two separate properties for what the `addon_install_method` represents on the abuse report API side: `installTelemetryInfo.source` and `installTelemetryInfo.method`.

[A brief description of this properties is part of the telemetry event definition in Events.yaml](https://searchfox.org/mozilla-central/rev/9775cca0a10a9b5c5f4e15c8f7b3eff5bf91bbd0/toolkit/components/telemetry/Events.yaml#122-131), which contains a list of possible values (the ones that are currently used), but it is not unlikely that a new one may be added without being also covered by the [AbuseReporter.jsm convertion](https://searchfox.org/mozilla-central/rev/9ae20497229225cb3fa729a787791f424ff8087b/toolkit/mozapps/extensions/AbuseReporter.jsm#149-186), and so it seems reasonable to still include the original values unchanged (so that we can still process them on the server side even when the resulting `addon_install_method` is going to be "Other").

As an example, we recently added source "rtamo", used for the addon installed by ReturnToAMO, and a source "disco" without any `installTelemetryInfo.method`, for the new discovery panel, and currently they would be both submitted to the abuse report API as `addon_install_method: "Other"`.

There could be more than one way to allow the submission of the original `installTelemetryInfo` properties, one option could be the following:

the abuse report submission API could allow a new parameter (e.g. a separate `addon_install_info` or something like that) that Firefox will set to the entire `installTelemetryInfo` object converted into a JSON string (and the value is going to look as something like `{"source": "...", "method": "...}`).

How that sounds to you?

**Comment by diox** [comment]
Some background: Ultimately we've got a lot of abuse reports coming in so I wanted to keep the stored data as small as possible, which is why `addon_install_method` is stored as an integer, every possible value being predetermined in advance.

It's kinda unfortunate that we made one field only in the API though, it really needed 2 separate fields to follow Firefox more closely. I don't love the idea of sending `installTelemetryInfo` as is. Instead, I'm tempted to:
- Add `addon_install_source`
- Follow original plan in the description of this issue to accept unknown values and translate them as `Other` for both `addon_install_method` and `addon_install_source`, logging them and adding missing possible values when some are added to Firefox
- Get Firefox to simply send `installTelemetryInfo.method` and `installTelemetryInfo.source` as `addon_install_method` and `addon_install_source`, respectively. I'd just need the value to be lowercased + `-` and `:` replaced by `_` (makes it easier for me to match values to constants).
- Still accept old `addon_install_method` values for older Firefoxes

How does that sound, @rpl ?

**Comment by rpl** [comment]
> Follow original plan in the description of this issue to accept unknown values and translate them as Other for both addon_install_method and addon_install_source, logging them and adding missing possible values when some are added to Firefox

This means that we still have to make sure of updating the addons-server code everytime we add (or change) the install telemetry info source and method, e.g. by creating an addons-server issue as soon as we are almost ready to land the change in Firefox.

I was wondering: could we also try to detect on the server side when some new unexpected value is being submitted from Firefox? so that we may notice it and fix it asap on the addons-server side in case we missed it when the related change has been landed in Firefox

> How does that sound, @rpl ?

Sure this solution sounds good to me too.

**Comment by diox** [comment]
> This means that we still have to make sure of updating the addons-server code everytime we add (or change) the install telemetry info source and method, e.g. by creating an addons-server issue as soon as we are almost ready to land the change in Firefox.

Ultimately there is no way around this as long as we store that data as integers though. We need a translation to known predetermined values.

> I was wondering: could we also try to detect on the server side when some new unexpected value is being submitted from Firefox? so that we may notice it and fix it asap on the addons-server side in case we missed it when the related change has been landed in Firefox

Yeah, that's why we want to log something somewhere when we translate an unknown value into `Other`. I still hope we can get advance warnings before new values are added to Firefox to avoid this though.

**Comment by rpl** [comment]
> > I was wondering: could we also try to detect on the server side when some new unexpected value is being submitted from Firefox? so that we may notice it and fix it asap on the addons-server side in case we missed it when the related change has been landed in Firefox
> 
> Yeah, that's why we want to log something somewhere when we translate an unknown value into `Other`. I still hope we can get advance warnings before new values are added to Firefox to avoid this though.

Sure, I agree, I think I'm going to add a note to the Events.yaml to point it out that we should open an issue in this repo when we are planning changes to them (but I wanted to also double-check with you if we are going to have a "backup plan" in case "the note goes unnoticed" ;-))

**Comment by jvillalobos** [comment]
We have an [abuse reports dashboard](https://sql.telemetry.mozilla.org/dashboard/add-on-abuse-reports) that I hope we'll monitor on a somewhat regular basis. I'll add charts that we can use to look for spikes in the "Other" values.

**Comment by diox** [comment]
QA: See https://github.com/mozilla/addons-server/issues/12060#issuecomment-519927430 for how the API should behave with those changes. https://bugzilla.mozilla.org/show_bug.cgi?id=1572173 tracks the Firefox side of this.

**Comment by ioanarusiczki** [comment]
@diox I send using the Abuse Report API the values for [addon_install_method ](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#abuse-addon-install-method-parameter) and [addon_install_source](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#abuse-addon-install-source-parameter). 
If "_" is not used for the values which contained "-" and ":" then they'll be interpreted as "Other" except the `app:profile` value which must be fixed - so I will reopen the issue.

**Comment by ioanarusiczki** [comment]
@diox 
I verified this on dev with Postman and `app:profile` is returned as `Other`. 

Before

![appprofile](https://user-images.githubusercontent.com/33448286/64030193-c258d500-cb4e-11e9-9c1d-82795786506d.png)

After

![after the fix](https://user-images.githubusercontent.com/33448286/64030216-cd136a00-cb4e-11e9-8827-23d7a6810b33.png)
