### ISSUE TITLE
Discontinue compatibility overrides

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12063]
We introduced compatibility overrides along with "compatible by default" extensions, many years ago. Since WebExtensions, this feature has become unnecessary, and legacy add-ons are long gone. We can start removing this feature, returning an empty response so clients don't break. [Requests from Firefox will eventually go away](https://bugzilla.mozilla.org/show_bug.cgi?id=1572140), but it'll be a while.

@wagnerand pointed out a few overrides that might still be relevant. [I investigated them](https://docs.google.com/document/d/1-4Znzpalgl6GFpBWTqQeIOO94HRRshHscEXE0XdoCLI/edit) and determined they won't be a problem.

**Comment by eviljeff** [comment]
QA: the two outward facing parts here are:
- The API.  /api/v3/addons/compat-override/ was pinged by Firefox daily to look for overrides but will now return an empty response for every query (the same as the response was when no override existed for a given guid).  The endpoint has been removed entirely from /api/v4+.
- the update service.  Compat overrides would be respected for update checks so we wouldn't have offered the update if there was already an override.

Marking QA:Extra because they're both Firefox related and we don't want to break Firefox.  But really they're both just making sure Firefox doesn't crash or do something unexpected on startup or during the update/compat-override checking.

**Comment by ioanarusiczki** [comment]
@eviljeff Please let me know if my testing plan is ok for the issue :

- The `API` must return an empty response. I have the API documentation [here](https://addons-server.readthedocs.io/en/latest/topics/api/v3_legacy/addons.html?highlight=override#compat-override) and will test it with Postman.
- I'm thinking to install older add-on versions, close and reopen the browser and check the broswer console.  FF should not crash 
- test it with the last version of FF (release is at 68.0.1) to install add-ons I must use the last unbranded release version.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this issue on AMO stage - FF68(release and  release unbranded).
- the API returns an empty response for https://addons.allizom.org/api/v3/addons/compat-override/ or when it has `guid` as parameter. The v4+ returns 404 Not found (because it was removed). 

![api results](https://user-images.githubusercontent.com/33448286/63029874-fd55da00-beb9-11e9-9189-36efe7438791.gif)

- I tested addon and theme version updates with manual `Check for updates` and then after restarting the browser. I did not encounter problems such as unexpected behavior at startup or crashes. I did not see errors for the compat-override API or the versioncheck requests.
