### ISSUE TITLE
Remove search plugins from content review

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#12065]
We've decided to remove OpenSearch search plugins from content review, as we will not be migrating them to WebExtensions. I'm hoping we don't have WebExtension search plugins yet, or they are at least not the same type as OpenSearch plugins?

Noting #11796 for reference where we've also removed themes.

**Comment by wagnerand** [comment]
Note that this is blocked on a decision when we are going to disable existing non-webextension search plugins. If we keep them around until the end of ESR68, then we also need to content-review them, as that's about a year out.

**Comment by kewisch** [comment]
I thought we decided we were going to not keep them around that long and hence can move forward with removing them from content review.

**Comment by jvillalobos** [comment]
That's the current thinking, but we'll confirm that next week.

**Comment by jvillalobos** [comment]
Confirmed, feel free to remote them.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I tested this issue on dev with FF68(Win10).
- the Content Review queue from dev no longer displays search engines. Probably the reason why the number of items in this queue dropped from approximately 5900 (which were available [last week](https://github.com/mozilla/addons-server/issues/12019#issuecomment-518718684) to 2734
- because of problems with the addon submission on dev I will still have to test the submission and then check that the search engines are not available in the queue (tomorrow on stage).

**Comment by ioanarusiczki** [comment]
@eviljeff 
- New submitted search engines are no longer available in the Content Review Queue.

@kewisch 
- With an admin or content reviewer account the content reviewer page can be accessed from the detail pages.

![content review page](https://user-images.githubusercontent.com/33448286/63416065-6df37e00-c407-11e9-8274-e2d0ec8a358a.gif)

Verified on stage with FF68 (Win10).
