### ISSUE TITLE
Add override for account restrictions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12143]
Admins need a way to manually override all account restrictions for a certain user account.

This could be a checkbox on the django admin user profile page, for example.

**Comment by jvillalobos** [comment]
Which restrictions would this apply to, specifically?

**Comment by wagnerand** [comment]
* DeveloperAgreementRestriction
* DisposableEmailDomainRestriction
* EmailUserRestriction
* IPNetworkUserRestriction
* EmailReputationRestriction
* IPReputationRestriction

Did I miss any, @diox?

**Comment by muffinresearch** [comment]
To summarize the concerns raised by @diox and others in the stand-up.

* Bypassing all restrictions forever needs some oversight.
* A good account today might not be a good account tomorrow.
* Should we limit this to being a bypass per restriction for tighter control?
* How can we monitor accounts with this bypass to ensure against takeovers and targetting?

**Comment by jvillalobos** [comment]
These overrides are meant to be a last resort measure when it not possible for a legitimate developer to submit because of the restrictions we have in place. "A good account today might not be a good account tomorrow" is something we already have to deal with for malicious behavior. Spamming wouldn't be much different, and probably less likely, since account takeover usually involves buying off the original developer.

So far we only have a need to bypass the IP restriction, so I suggest we keep it simple and start with that. Changing the account email address is an easier ask for a developer, IMO.

**Comment by diox** [comment]
It's actually easier to allow bypassing of *all* restrictions, so I'm going that route.

**Comment by AlexandraMoga** [comment]
I've verified the submission restriction override on stage and it seems to be working as expected. 
The override is expressed by a checkbox that can be marked on a user admin page:
![image](https://user-images.githubusercontent.com/31961530/63852043-12de0000-c9a0-11e9-9aa6-2204905064f5.png)

@diox I was able to verify by myself only the following restriction overrides:
- DeveloperAgreementRestriction
- DisposableEmailDomainRestriction
- EmailUserRestriction
- IPNetworkUserRestriction

If you think the remaining two restrictions - email and ip reputation -  should be checked as well, I'm going to need your help.

Also, there is some inconsistency between the API and dev hub, which goes like this: 
- create a new user 
- override all restrictions for this user
- try to submit an add-on from dev hub -> it works, i.e the user lands directly on the add-on distribution page because the Developer agreement is also overridden
- try to submit an add-on from the api -> user is blocked by the Developer agreement restriction, since the Dev agreement was never accepted

![image](https://user-images.githubusercontent.com/31961530/63853140-9bf63680-c9a2-11e9-9ded-92140469bbc1.png)

**Comment by diox** [comment]
Regarding checking reputation I think it's fine if you tested with the others.

I had not anticipated the developer agreement inconsistency. It's because that check is done twice, once at the authentication level and once during restrictions checks. I think the former is redundant (and only partial anyway as it doesn't care about the date the developer agreement was read). 

Can you file a follow-up for us to fix it? It's not urgent, I think we can live with it, but it'll be good to clean it up.
