### ISSUE TITLE
Use `No image selected` for default image and icon options in hero admin

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12161]
The hero area admins have 3 different image selection options:
* Image for primary shelf item
* Gradient for primary shelf item
* Icon for secondary shelf item
They default to no image. The radiobuttons in those cases should have a `No image selected` label, instead of ` ---------` or no text.

**Comment by AlexandraMoga** [comment]
The 'no selection' option in the Primary hero module has been updated with the 'No image selected' option:

![image](https://user-images.githubusercontent.com/31961530/63765423-a4cb0780-c8d1-11e9-8ced-be73a16d1174.png)


There is a layout issue in the secondary hero modules caused by this change, for which I filed #12201
