### ISSUE TITLE
Add primary hero shelf featured images

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12184]
The primary hero shelf currently only allows a selection of 2 placeholder images.  We need a wider selection, as per the [PRD](https://docs.google.com/document/d/12aD_v5AOj1Y6VmT4xOuyNcrKfZxqhP8R_AOHroQVLV8/edit#), for launch.

Ideally they can be attached to this issue.

cc @jvillalobos also

**Comment by muffinresearch** [comment]
Speaking to Bob about this he mentioned that @devaneymoz mentioned the first use will more likely not have a hero image so this doesn't need to be super urgent, but more images as and when would be good.

**Comment by eviljeff** [comment]
We should remove the placeholder images before launch at least.  They aren't suitable to be inadvertently selected.

Is there an ETA that someone is willing to agree to for the images being provided?

**Comment by muffinresearch** [comment]
@eviljeff Since there are no images to replace these and no immediate plans to provide them the best way to solve this for now would be to update the images with text on them that says something like "TESTING ONLY" or similar. I was going to suggest removing them but then there would be no way to test it.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/67286646-6ec98e80-f4e2-11e9-83e2-3cb4242db93d.png)
