### ISSUE TITLE
Add a task to run the `wat` scanner

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12223]
We need a task to run the `wat` scanner over HTTP, very similar to `run_customs`.

We will also need a waffle switch to enable/disable this new task.

**Comment by willdurand** [comment]
@ioanarusiczki @vcarciu this is now ready to test. This issue is verified if uploading an extension adds an entry in the `ScannersResult` django admin (for the `wat` scanner). Here are a few scenarios:

1. upload a new extension (xpi) and wait for the validation to complete, this should create a new entry in the Django admin
2. upload a new extension (xpi), wait for the validation, then continue the submission to publish a new add-on. That will add a reference to the add-on in the admin
3. try to submit an unlisted extension
4. uploading an add-on that is not an extension should not trigger the scanners

**Comment by willdurand** [comment]
cc @AlexandraMoga

**Comment by vcarciu** [comment]
I tested using following scenarios:

  1.Tested various xpis(webext, themes, dictionaries , lang packs...) in order to see if after validation an entry is created in Django admin. Also verified that no entry was added if validation is failing or if file validated is not an extension(a search tool xml file) - PASSED

   2. Publish various types of extensions (webext, themes, dictionaries , lang packs...) and verify if reference is added. Also, verified that a reference is added even if some mandatory fields were not added during submission(checked with @willdurand and it is expected) - PASSED

   3.Same verification as in second scenario, but with unlisted addons. The references were added as unlisted. - PASSED

   4. Uploaded addons that are not extensions (ie. Search tools xml files). Verified that no entries were added in the Django admin - PASSED

Marking issue as verified.
