### ISSUE TITLE
Update `run_scanner` to send a `FileUpload` download URL instead of the content

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12236]
Instead of sending the xpi content, we should send the secured download URL implemented in #12232 to the cloud functions. That will fix the GCP limitation on the request body size.

**Comment by willdurand** [comment]
@diox running a few tests with GCP, it takes time to download very big xpis so the execution time is > 60 seconds. It will certainly be less when we'll serve add-ons _via_ addons-server but we might want to adjust `SCANNER_TIMEOUT` accordingly.

Yet, it cannot be greater than the Celery soft limit, right? Can we change the soft limit on one specific task by chance?

Then again, I don't know how long it will take to download xpis from addons-server. It was slow for me but that's because I served the files from my personal laptop, at home, with ngrok.

**Comment by diox** [comment]
> Yet, it cannot be greater than the Celery soft limit, right? Can we change the soft limit on one specific task by chance?

We can, tasks accept a `time_limit` and `soft_time_limit` arguments for this purpose. (We can also catch the soft time limit exception and start doing things when we get it, but in this case we also need to configure the hard limit)

**Comment by willdurand** [comment]
Ah ok, great. Well, that's good to know because that could have been yet another blocker 😅

**Comment by willdurand** [comment]
@ioanarusiczki @vcarciu this is now ready to test. This issue is verified if uploading an extension adds an entry in the `ScannersResult` django admin (for the `wat` scanner currently). Here are a few scenarios:

1. upload a new extension (xpi) and wait for the validation to complete, this should create a new entry in the Django admin
2. upload a new extension (xpi), wait for the validation, then continue the submission to publish a new add-on. That will add a reference to the add-on in the admin
3. try to submit an unlisted extension
4. uploading an add-on that is not an extension should not trigger the scanners

I am going to enable the "wat" scanner for now.

**Comment by willdurand** [comment]
cc @AlexandraMoga

**Comment by vcarciu** [comment]
I tested using following scenarios:

1. Tested various xpis(webext, themes, dictionaries , lang packs...) in order to see if after validation an entry is created in Django admin. Also verified that no entry was added if validation is failing or if file validated is not an extension(a search tool xml file) - PASSED

2. Publish various types of extensions (webext, themes, dictionaries , lang packs...) and verify if reference is added. Also, verified that a reference is added even if some mandatory fields were not added during submission(checked with @willdurand and it is expected) - PASSED

3. Same verification as in second scenario, but with unlisted addons. The references were added as unlisted. - PASSED

4. Uploaded addons that are not extensions (ie. Search tools xml files). Verified that no entries were added in the Django admin - PASSED

Marking issue as verified.
