### ISSUE TITLE
Log the first x chars or return an error for too many chars in addon_install_source and addons_install_method

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#12234]
Followup for https://github.com/mozilla/addons-server/issues/12060
[The Abuse Report API ](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#submitting-an-add-on-abuse-report)

Actual result:
Right now the addon_install_source and addons_install_method are not restricted and even a large number of chars can be sent without returning 400 error.

Expected result:
Only the first x chars to be logged or raise an error. 

Notes:
Verified with Postman on dev.

**Comment by diox** [comment]
To clarify: I asked ioana to file that because even though we store "other" (or the corresponding integer value, technically) for unknown sources/methods, we do log the original value, and it's a bit of a waste to log the full value if it's huge. We know Firefox should never send values over x characters, where x is to be defined. So maybe we should just log the first x chars.

**Comment by diox** [comment]
The fix for this is going to be transparent - the value in the log will be truncated but we won't raise an error.
