### ISSUE TITLE
POST draft_comments API doesn't accept both a 'comment' and a 'canned-response' in the same request

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12270]
### Describe the problem and steps to reproduce it:
1. Send a request with the following body to the [POST draft_comment endpont](https://docs.google.com/spreadsheets/d/11nJqyJvhZwCJxwqPPeccisxGNYzVjsbj9ug0fhtkWfs/edit#gid=1686047495)
```
{
	"canned_response": 43,
	"filename": "manifest.json",
	"lineno": 3,
	"comment": "I'm not allowed"	
}
```

### What happened?
You receive the following response:
`  "You can't submit a comment if 'canned_response' is defined."`

### What did you expect to happen?
The current Reviewer Tools accept both a canned response and an additional comment (see screencast) so maybe the new draft-commets API should accept both values as well.

### Anything else we should know?
I was thinking of a possible use case when a canned_response would cover most of the information a reviewer would like to communicate to the developer, but there are also some additional details to be added to the predefined text.  
Maybe an actual reviewer could confirm if this scenario was or could be encountered. 

@kumar303 I'm curious to see how the code-manager will behave when the mentioned scenario is attempted, more precisely, I'd like to see if the `canned_response` body will be editable like in the current Reviewer Tools.

![2019-09-04_11-14-36](https://user-images.githubusercontent.com/31961530/64237577-491e0100-cf05-11e9-894e-4dc5089ed566.gif)

**Comment by kumar303** [comment]
This is working as expected. The example you cited in the existing reviewer tools is about sending *multiple* comments to a developer about their extension. For example, you might add a canned comment on line 22 of `manifest.json` to say *This violates our policy because...* and then you might add a custom comment on the same line later saying *This permission is not used so you need to remove it*. In the final review, both comments would be combined and submitted to the developer.
