### ISSUE TITLE
Draft comment API should return a reviewer version object

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#12275]
### Describe the problem and steps to reproduce it:

* [`POST`](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#post--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-draft_comments-) a new comment on a version / file / line
* Inspect the response

### What happened?

The response contains a [`comment.version`](https://github.com/mozilla/addons-server/blob/50383b46fee9c48ef6291b0cc6b4866b599c591d/src/olympia/reviewers/serializers.py#L361) object but this is missing some fields, like `version.addon`.

### What did you expect to happen?

I was hoping that `comment.version` would look exactly like the `version` returned by the [browse](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-) endpoint since we already have a lot of code to work with that kind of version object.

### Anything else we should know?

Maybe it's as easy as dropping in this [serializer](https://github.com/mozilla/addons-server/blob/50383b46fee9c48ef6291b0cc6b4866b599c591d/src/olympia/reviewers/serializers.py#L196)?

**Comment by kumar303** [comment]
Thanks! I verified on dev that is working for the forthcoming commenting API.

**Comment by ioanarusiczki** [comment]
@kumar303 I verified with Postman and noticed the following:
The POST (or GET) response returns details now about the content of the XPI file which looks like the response of the Browse API.

<details>
<summary>files - AMO stage, as it looked before </summary>


![files on AMOstage](https://user-images.githubusercontent.com/33448286/64623603-e55a7300-d3f1-11e9-9df1-02cdbeea0b68.png)



</details>

<details>
<summary>file - AMO dev, as it looks now </summary>


![on AMOdev](https://user-images.githubusercontent.com/33448286/64624072-bf819e00-d3f2-11e9-8673-8bf49e86baef.gif)



</details>

Let me know if it's the expected behavior.

**Comment by kumar303** [comment]
Yep, the response should look like [the browse response](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-).

**Comment by ioanarusiczki** [comment]
@kumar303 I forgot to mention:

- I did notice that [docs ](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-)specify for the `entries` as
file.entries[] (array) – The complete file-tree of the extracted XPI.
I see the `entries` but without square brackets.  
it's 
 "entries": {
"file1":{...
},
"file2": {...
},
}
So probably the docs are not updated or entries should look like an array (can't tell).

**Comment by kumar303** [comment]
Good catch! The docs are incorrect here and should be updated. Can you file a separate issue?
