### ISSUE TITLE
Cannot download file uploads using the secure download URLs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12322]
In #12232, we created a new URL to download file uploads:

```
https://addons-dev.allizom.org/files/uploads/edde1fd24ac340dca2d6b1451f9420ec/?access_token=<access_token>
```

We're using the _XSENDFILE_ feature to let Nginx serve the file instead of streaming it _via_ the django app. This works locally but it does not work in -dev because of a redirect loop (similar to #11179).

Here is what I observed so far:

- Because this URL is `/files/uploads/:uuid`, it is automatically rewritten as `reviewers.a.m.o/files/uploads/:uuid` by the main Nginx config.
- The newly added endpoint returns `X-Accel-Redirect` headers with values like this one (in -dev): `/mnt/efs/addons-dev.allizom.org/files/temp/<uuid>.xpi`.
- The `reviewers` subdomain does not have a location configured for those URIs though.

I guess we need to update the `reviewers` Nginx config to add a new location for the URIs returned by the endpoint.

**Comment by bqbn** [comment]
> Because this URL is `/files/uploads/:uuid`, it is automatically rewritten as `reviewers.a.m.o/files/uploads/:uuid` by the main Nginx config.

Just want to mention that this statement is not entirely accurate. For the url `/files/uploads/:uuid`, first, it is the application that redirects it to `/<locale>/files/uploads/:uuid`, and then Nginx redirects it to `reviewers.a.m.o/<locale>/files/uploads/:uuid`.

It is true that currently the `reviewers.a.m.o` domain doesn't handle `X-Accel-Redirect` headers with values such as `/mnt/efs/addons-dev.allizom.org/files/temp/<uuid>.xpi`.

Does the endpoint `/<locale>/files/uploads/...` really belong to `reviewers.a.m.o` domain? If it doesn't, it's worth noting that it is possible to use a more specific rule to match the url so that Nginx doesn't redirect it to that domain.

Previously per [bugzilla 1386984](https://bugzilla.mozilla.org/show_bug.cgi?id=1386984), endpoints with `/<locale>/firefox/files/` prefix are redirected to `reviewers.a.m.o` domain. I'm not sure if that applies for this case or not.

**Comment by diox** [comment]
> FTR: I implemented the new "view" in the files package because it's related to the FileUpload model, which lives in the same files package.
> 
> We could indeed add a more specific rule only for this new URL, but isn't it something you wanted to avoid in the past? Wouldn't it be confusing to redirect all /files/ but /files/uploads/?

I agree this could get a little confusing. If we're worried about that we could add it at the root, under `/uploads` ; or anywhere else you think it makes sense really.

**Comment by willdurand** [comment]
>  If we're worried about that we could add it at the root, under `/uploads` ; or anywhere else you think it makes sense really.

Can we actually do this? That would mean by-passing the `files/urls.py` config and directly registering the view in... `amo/urls.py`?

**Comment by diox** [comment]
We can do whatever we want :) But I was more thinking of having something like `upload_patterns` in `files/urls.py` and include that under `/uploads` in `amo/urls.py`.

**Comment by willdurand** [comment]
> We can do whatever we want :) But I was more thinking of having something like `upload_patterns` in `files/urls.py` and include that under `/uploads` in `amo/urls.py`.

Ok, I wasn't sure we could do that but I see in `src/olympia/urls.py` that we are already doing it for a few patterns, so I proposed a patch on addons-server.

@bqbn I believe the patch I proposed in https://github.com/mozilla/addons-server/pull/12330 makes https://github.com/mozilla-services/cloudops-deployment/pull/3393 obsolete.

**Comment by willdurand** [comment]
So the following new URL:

```
https://addons-dev.allizom.org/uploads/file/edde1fd24ac340dca2d6b1451f9420ec/?access_token=<access token>
```

is redirected to:

```
https://addons-dev.allizom.org/en-US/firefox/uploads/file/edde1fd24ac340dca2d6b1451f9420ec/?access_token=<access token>
```

which is handled by addons-frontend by default (as per https://github.com/mozilla/addons-server/issues/10428).

That means we still need a Nginx change.

**Comment by willdurand** [comment]
@bqbn ^ + the nginx change that I think we need: https://github.com/mozilla-services/cloudops-deployment/pull/3395

**Comment by bqbn** [comment]
> We could indeed add a more specific rule only for this new URL, but isn't it something you wanted to avoid in the past? Wouldn't it be confusing to redirect all `/files/` but `/files/uploads/`?
> 

Yes, I still would like to avoid it as much as possible! However, on the other hand, I also don't want send a url to a domain it doesn't belong to. 

That's why I want to give big kudos to https://github.com/mozilla/addons-server/pull/12330, which solved both concerns above. 👍 

We should make it a pattern for solving this type of issues. LOL.

**Comment by bqbn** [comment]
The changes in https://github.com/mozilla-services/cloudops-deployment/pull/3395 has only been deployed to -dev and -stage as of this comment.

If no objection, we'll deploy them to -prod tomorrow.

**Comment by willdurand** [comment]
@bqbn yep, no problem with deploying these changes to -prod.
