### ISSUE TITLE
document best practices for creating django migrations

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12334]
moved from #12333, part of #3705

@diox said

> It's also worth coming up with some documentation about how to customize migrations to make them backwards-compatible - something we do right now when writing SQL migrations. Maybe something about what strategy to use in which case (delay committing the migration itself when removing a field, add new fields as nullable, etc) ?

**Comment by diox** [comment]
Things to cover:
- How to customize migration that adds a new field (maybe we need to always add fields as nullable, not doing anything special with the migration, then remove the null later, adding a second migration to do that?)
- When to commit a migration that removes a column / table
- What to check for when we add a migration (in particular, was there some migrations that hadn't been generated before, and what would be the consequences of applying those)
- How to deal with big tables, how to test suspected long migrations with ops, etc.

**Comment by diox** [comment]
Something worth noting regarding adding new columns: If you don't add a default, and the field is not nullable, django migrations asks if you want to set a one-off

Regardless of your choice, here is what it does in the migration:
- `ALTER` with a database default matching your choice (causing all existing data to get that default value)
- `ALTER` to remove that database default

It does this because Django handles default values in python and never leaves a database one.

This is a clever trick... that we never want to use! During deployment, we run on the old code for a limited time before promoting the new tag, so if were were to run that second `ALTER`, old code would never provide a default value and any insertions it'd make would fail.

So, instead, we want to do this 99% of the time:
- Add all new field as nullable (create & commit the migration for this) 
- Wait to push to happen
- Make the field non-nullable (create & commit migration for this)

**Comment by diox** [comment]
https://github.com/3YOURMIND/django-migration-linter might be useful

**Comment by ChetanKhanna** [comment]
Hi! :)
Is this issue something that I can take on? If so, where exactly should the docs go?

**Comment by diox** [comment]
This is unlikely to be a good bug for external contributors, no. https://addons-pm.herokuapp.com/contrib/good-first-bugs/?dir=desc&sort=updatedAt has a list of good first bugs across AMO repositories.
