### ISSUE TITLE
Relax setting an image for the primary hero promo

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#12403]
Since images are now optional, we'll need the admin to allow the configuration of a primary hero shelf without one.

See https://github.com/mozilla/addons-frontend/issues/8629 for the frontend component of this.

**Comment by eviljeff** [comment]
@devaneymoz relevant to our discussion from last week where we talked about workarounds when there isn't an image for a hero item.  Once this lands you won't have to set an image.

**Comment by AlexandraMoga** [comment]
The Primary hero module from Discovery admin lets you configure an item without adding a featured image => there is no error generated when saving an item that doesn't have an image selected. 

@eviljeff regarding the `/hero/` api, when there is no image selected, the `featured_image` field is retuning the following value - https://addons-dev-cdn.allizom.org/static/img/hero/featured/ - which is a 404. I believe this field should be `null`, otherwise this will cause some weird rendering on the frontend side.

```
"slug": "worldwide-radio",
"type": "extension",
"url": "https://addons-dev.allizom.org/en-US/firefox/addon/worldwide-radio/"
},
"description": "Do you have a ton of open tabs? Organize them in a tidy sidebar.",
"featured_image": "https://addons-dev-cdn.allizom.org/static/img/hero/featured/",
"gradient": {
    "start": "color-ink-80",
 "end": "color-purple-70"
```

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

`featured_image` returns `null` if no image is set in admin:

```
"featured_image": null,
"gradient": {
    "start": "color-ink-80",
     "end": "color-violet-70"
```
