### ISSUE TITLE
Volunteers should not be able to review recommended extensions

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#12413]
### Describe the problem and steps to reproduce it:
I've received an "Dear reviewer, You're looking great today!" email regarding a new upload awaiting review : https://addons.mozilla.org/reviewers/review/2464 version 7.0

This extension is currently part of the Recommended Extensions program. To my understanding, volunteers shouldn't have access to do such reviews.

### What happened?
In the review page, it seems I have access to all the different options to finish the review. "Approve", "Reject" and "Save" buttons are active. Note that I didn't try to actually save the review, for oblivious reasons.

### What did you expect to happen?
Saving the review should be disabled or should show an error to the volunteer reviewer.

**Comment by diox** [comment]
Actions should not work - you're able to see this page because you've got `ReviewerTools:View` permission, which as the name implies allows you to view the page.

We should hide the buttons when the review page is being accessed through that permission. Something like the following in the view, instead of the current check:

```python
    try:
        bypassed_permission_checks_because_read_only = False
        perform_review_permission_checks(
            request, addon, channel, content_review_only=content_review_only)
    except PermissionDenied:
        # If we're just looking (GET) we can bypass the specific permissions
        # checks if we have ReviewerTools:View.
        if request.method == 'GET' and acl.action_allowed(
                request, amo.permissions.REVIEWER_TOOLS_VIEW):
            bypassed_permission_checks_because_read_only = True
        else:
            raise
```

Then use `bypassed_permission_checks_because_read_only` where needed.

**Comment by diox** [comment]
@spoji this should have been fixed, can you still reproduce ?

**Comment by spoji** [comment]
@diox Do you mean you are now hiding the buttons when the review page is being accessed through that permission?

Because I can still see the following action buttons :
Reject Multiple Versions
Reviewer reply
Request super-review
Comment

on https://reviewers.addons.mozilla.org/en-US/reviewers/review/foxyproxy-standard

**Comment by diox** [comment]
Sigh. That's a bug. You should see reply, request super review & comment, but not any approve/reject actions.

**Comment by AlexandraMoga** [comment]
@spoji would you be able to tell me exactly what reviewer permissions you are using besides `ReviewerTools:View`?
I'm trying to reproduce your issue on stage before verifying the fix on -dev and I need to make sue I'm testing the correct scenario.

**Comment by spoji** [comment]
@AlexandraMoga I don't know which permissions I have on prod. @diox (or another Mozilla employee working on AMO) could dig this up for you.

**Comment by jvillalobos** [comment]
As far as I can tell, he has `Addons:Review` and `Addons:PostReview`

He doesn't have `Addons:RecommendedReview`.

**Comment by AlexandraMoga** [comment]
Since the fix is on stage now, I'm no longer able to reproduce the issue described above when the permissions mentioned are used.
In any case, if the user has `Addons:Review` and `Addons:PostReview` only the options to Reply, Request super review and Comment are available.

![image](https://user-images.githubusercontent.com/31961530/77518207-019d9900-6e86-11ea-90fd-30c1c71d2d54.png)

I'm marking this issue as verified fixed.
