### ISSUE TITLE
Cannot upload big xpis in Stage and -dev

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#12415]
Steps to reproduce:
1.Try to validate a big(around 100MB) xpi to stage or -dev. You can try with https://addons.mozilla.org/en-US/firefox/addon/lolbyte-league-summoner-search/versions/ .

Expected results:
Validation is successful

Actual results:
"Error: Validation was unable to complete successfully due to an unexpected error."

NOTES:
Not reproducible in prod
From @willdurand : "Soft time limit (110s) exceeded for olympia.devhub.tasks.validate_upload" in logs

**Comment by willdurand** [comment]
@diox this is the issue I mentioned to you once (in -dev). It affects stage too, so it might also be a problem in prod. I was thinking that the -dev infra was too small/weak but that might be something else.

**Comment by willdurand** [comment]
I could not find the `p2.5` label so I chose `p2`. Please change it if needed.

**Comment by willdurand** [comment]
In production, we have 2758 (/3,178,568) files larger than 20MB (I used `files.size` to crunch the numbers):

![newplot](https://user-images.githubusercontent.com/217628/65591555-05129f00-df8d-11e9-86cb-07fbde160d30.png)

According to the chart above, production is able to ingest add-ons larger than 100MB, although not all of them are web extensions.

Only 1723 add-ons are web extensions (based on the `is_webextension` field) and here is the distribution:

![newplot(1)](https://user-images.githubusercontent.com/217628/65592382-c7af1100-df8e-11e9-9310-731a9503bf2a.png)

**Comment by willdurand** [comment]
I am reopening this issue because @vcarciu and I found that #12505 was not enough. We often hit the soft limit with big-ish add-ons.

@vcarciu tried to upload a 20MB xpi file containing lots of files and it did not pass the `repack` task. This xpi worked in stage and prod though, so #12505 did help a bit. I believe -dev has less resources than stage/prod.

I tried to upload 50MB xpis and the linter task timed out.

@diox I think we should increase the soft limit a bit. WDYT?

**Comment by vcarciu** [comment]
I used the following addon : 

[ublockvic.zip](https://github.com/mozilla/addons-server/files/3680368/ublockvic.zip)

**Comment by diox** [comment]
We could maybe bump it on dev only, if that's not a problem on stage & prod ? I don't really want to bump it too much in prod - it's already 3 minutes...

**Comment by willdurand** [comment]
> We could maybe bump it on dev only, if that's not a problem on stage & prod ? I don't really want to bump it too much in prod - it's already 3 minutes...

isn't it 110 seconds only? Yeah, I was thinking about bumping it on -dev only too.

**Comment by diox** [comment]
Ah, yeah, `CELERY_TASK_SOFT_LIMIT` is 180 seconds but the validation tasks use `VALIDATOR_TIMEOUT` which is 110 seconds. We could get rid of the latter entirely maybe...

**Comment by diox** [comment]
Scratch that: `VALIDATOR_TIMEOUT` is 360 seconds in prod oO. In that case, we could bump it to 360 seconds everywhere...

**Comment by willdurand** [comment]
Thanks for the explanation. I was confused.

**Comment by vcarciu** [comment]
@willdurand , @diox 

The addon used in the original issue description is still failing at validation(93MB addon).

"Soft time limit (360s) exceeded for olympia.files.tasks.repack_fileupload" in the logs

**Comment by diox** [comment]
Victor mentioned on IRC that it worked a second time, but that's not really a good indicator, it may be because of some caching, or just luck.

The problem seems to be the repack task, so let's focus our attention on that for a bit. It should move the zip as it was uploaded from EFS to local filesystem, unzip it, rezip it (still on local filesystem) and move the resulting file back to EFS, overwriting the original one. Let's see if that's really what's happening and what part of that process is slow.

**Comment by diox** [comment]
@vcarciu note, once fixed, please *also* retry with the xpi from https://bugzilla.mozilla.org/show_bug.cgi?id=1534483#c18 to make sure the repack is still behaving properly.
