### ISSUE TITLE
An entry is created in Scanners even if submission fails with duplicate UUID found

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#12447]
Steps to reproduce:
1.Go to AMO-dev and try to submit an addon with duplicate id(already existent in AMO)
2.Go to Django admin pages and check the Scanners results

Expected results:
No entry is created for a failed validation

Actual results:
An entry is created even if validation was failed with "duplicate uuid found"

NOTES:
This issue was present before, but the scanners made it very obvious

**Comment by willdurand** [comment]
This happens because the "duplicate ID" comes from `parse_addon` and not the linter. The scanners only run when the linter returns no errors, which is the case.

We found out that this problem existed before because `parse_addon` is weirdly called after the linter. @diox will add more info.

**Comment by diox** [comment]
Yeah this will happen for any (?) validation errors added by addons-server outside of the linter.

The submission process is essentially:
- Upload the file via XHR to `/upload`
  - That creates a `FileUpload` and triggers the validation tasks. `parse_addon()` might be called at different stages in this process, but with `minimal=True`, without raising errors.
- Poll the json upload detail endpoint, `/upload/<upload_uuid>/json`
  - That amends the validation results with the error raised by `parse_addon()` 
- If the validation is ok, call the submit upload endpoint
  - That calls `parse_addon()` in `NewUploadForm` and raise any errors

So, we call `parse_addon()` in 2 different places, preventing any `Version` (or `Addon` for new add-on uploads) from being created if there is an error, but it's too late: the `FileUpload` has already been created, and everything that goes with it - linter, scanners etc will have run.

This was done this way because historically, before 2542a9109d57592a8f56c8025096fa9a4d7cc4f7 started to add it, there was no `addon` foreign key on `FileUpload`, so these kind of checks couldn't be done as part of the validation, they had to be done later. 

Nowadays we do set that `addon` foreign key every time, we also set `version` string, so I don't think there is a good reason to delay the checks, except maybe for the standalone validator, but that's easy to ignore. We could completely prevent the whole validation chain from running if we detect such an error, and properly mark the `FileUpload` as invalid (currently, it will be considered valid, even though you can't use it to create a new version/addon).

**Comment by diox** [comment]
Note: in any case the checks need to continue being made in `NewUploadForm`, or whatever is responsible for the `from_upload()` call. This is because a conflicting `Version` or `Addon` might have been created since the `FileUpload` was created, so the check must be done twice.

**Comment by wagnerand** [comment]
@diox should this be reopened?

**Comment by diox** [comment]
If that happens enough to cause issues, yes. Otherwise, I'd be inclined to ignore it for the moment.
