### ISSUE TITLE
Add-on block button in review pages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12457]
Part of this [PRD](https://docs.google.com/document/d/14_Xz_r46yQF4wN7BtrgWfWBdjEqCVdY7d8T_ZjVf1OE/edit). [Mocks](https://docs.google.com/drawings/d/1K6mpb_06oB1MYpQF3gagolWoDCMEHK8Sc_LMvMH6ass/edit).

Add a Block Add-on button, under the Force-disable Add-on button in review pages. This button should only be visible to Admin Reviewers, and should link to the individual block page for the add-on.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

The 'Block add-on' button has been added to the More Actions section from an add-on review page. By clicking on the button, reviewers are redirected to the individual add-on block admin page. The button state will change to 'Update add-on block' if one or more versions of the reviewed add-on has an existing block.

![2019-11-27_11-40-29](https://user-images.githubusercontent.com/31961530/69713186-c58f3d00-110c-11ea-9fa2-3d30397c65d3.gif)


Regarding permissions, note that in order to be able to open the individual add-on block in django admin, it is not enough to have `Reviewers:Admin` permissions. You will also need the `Admin:Tools` permission which is now granted to users from the Admin Advanced and Staff groups.
