### ISSUE TITLE
Disable all OpenSearch add-ons

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12463]
Part of [this PRD](https://docs.google.com/document/d/1FQq47mNCRy1enLsN0giseD2tnS0OaHth3S5mZL9C8jY/edit).

We'll stop accepting submissions and reach out to devs at the beginning of the quarter. Actually disabling them should wait until the end of the quarter, to give devs time to migrate.

Depends on https://github.com/mozilla/addons-frontend/issues/8680.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Can you please add some str for qa on what exactly testing should be focusing on ?
- Disabling the submission has already been done and it's in prod right now: issue https://github.com/mozilla/addons-server/issues/12462
- The frontend issue https://github.com/mozilla/addons-frontend/issues/8680  mentioned by Jorge above has been verified on dev and it did not land on prod yet.

**Comment by EnTeQuAk** [comment]
I am going to run this on -dev in a moment so that you can verify that all opensearch plugins are indeed disabled. So, if you own one in your devhub account you should see the change - is that something you already have?

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I could verify them with my admin account. Let me know when it's ready.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk This was verified on dev with FF72(Win10) :
- As an admin user I uploaded with admin override a couple of  opensearch plugins ( the `xml` formats) and I approved them. 
- after the scrips was executed these plugins are no longer available in my list of submissions 
https://addons-dev.allizom.org/en-US/developers/addons?sort=created - they were deleted. 
- I did not find such a plugin submitted by other user on dev - it looks like the `xml` formats were all deleted.

Please let me know if this is the expected result.

**Comment by EnTeQuAk** [comment]
Imo that is the expected result.

Just cc'ing @jvillalobos to confirm that I understood this correctly. What I implemented is essentially soft-deleting OpenSearch plugins now. The hard-delete can be done at a later point if necessary.

Or should we "just" disable them so that developers still see them? I'm not sure what we communicated.

**Comment by EnTeQuAk** [comment]
> Soft-deleting should be fine.

Phew, then this is ready and all the tests from me and @ioanarusiczki are fine.

It's ready to be run whenever we want to.

For documentation purposes, the task that needs to be run is registered as `disable_opensearch_addons`

`$ ./manage.py process_addons --task=disable_opensearch_addons`

**Comment by AlexandraMoga** [comment]
@EnTeQuAk can we please double check why we still have search tools returned in search results on -dev?

query search:
https://addons-dev.allizom.org/en-US/firefox/search/?q=eccelio

search by add-on type:
https://addons-dev.allizom.org/en-US/firefox/search/?type=search

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Two questions: 

- I checked the submission, which is no longer possible on prod already https://github.com/mozilla/addons-server/issues/12462
 I've noticed that on stage the uploaded search tools from yesterday are still available. Also the Search Tools link returns the list of old .xml formats. 
Does it mean this issue is not going to prod this week together with https://github.com/mozilla/addons-frontend/issues/8680 and https://github.com/mozilla/addons-frontend/issues/8679 ? 

- the Addon details API returns for the deleted search tools the "status": "deleted". The Search API 
https://addons-dev.allizom.org/api/v4/addons/search/?type=search returns 115 search tools, checking a couple of id's these have been deleted from AMO dev, yet the is "status": "public". 
Let me know if I should file an issue.

**Comment by EnTeQuAk** [comment]
To answer both:

* The opensearch disable task wasn't run on -stage yet, only on -dev. I'll do that in a bit later today (once some other testing has been done on -stage)
* I'm looking into the search related bits - they're unexpected but not a blocker for this to go live - if in doubt we could "just" reindex instead. But theoretically a reindex should just happen - I'm still investigating.

**Comment by EnTeQuAk** [comment]
Alrighty, opensearch plugins have been disabled on stage now too.

**Comment by AlexandraMoga** [comment]
> * I'm looking into the search related bits - they're unexpected but not a blocker for this to go live

@EnTeQuAk I disagree a bit with the "not a blocker" part. Thinking that we have about 3.800 search tools on prod right now, I don't think it will be uncommon for users to run into them when searching by a specific query. If they happen to click on any of those results, they'll run into 404s.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk 
I verified on AMO stage with FF72(Win10):
- the problems [observed](https://github.com/mozilla/addons-server/issues/12463#issuecomment-577054989) by @AlexandraMoga on AMO dev regarding the search results are not reproducible on AMO stage.  

- the Addon Detail API https://addons.allizom.org/api/v4/reviewers/addons/addon/554230/ returns a 404 Not Found, same for the Reviewers versions API https://addons.allizom.org/api/v4/reviewers/addon/1003983/versions/20200122/. The Search API https://addons.allizom.org/api/v4/addons/search/?type=search returns 0 results. 

- [admin tools](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/?type__exact=4) indicates that the plugins were deleted.

- the plugins I submitted 2 days ago are no longer available in the add-on list from [Manage my submissions](https://addons.allizom.org/en-US/developers/addons) page in Dev Hub.
