### ISSUE TITLE
Connect blocklist admin to kinto

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12461]
Part of this [PRD](https://docs.google.com/document/d/14_Xz_r46yQF4wN7BtrgWfWBdjEqCVdY7d8T_ZjVf1OE/edit). [Mocks](https://docs.google.com/drawings/d/1K6mpb_06oB1MYpQF3gagolWoDCMEHK8Sc_LMvMH6ass/edit).

Once the admin is functional, its data should be used to feed the Kinto blocklists. We'll have to coordinate with their team on the best process to do this. There's an API @kewisch has used before, so maybe that would be enough.

**Comment by eviljeff** [comment]
blocked on getting details of _how_ to connect to kinto (possibly involving an API)

**Comment by wagnerand** [comment]
Does https://docs.kinto-storage.org/en/stable/tutorials/first-steps.html and https://docs.kinto-storage.org/en/stable/api/1.x/index.html help? Also https://github.com/kewisch/mozblocklist uses the API to automate blocks.

**Comment by eviljeff** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1615337 for access

**Comment by AlexandraMoga** [comment]
@eviljeff could you please add some test instructions to this issue?

**Comment by eviljeff** [comment]
QA:
with waffle `blocklist_legacy_submit` enabled, submit a Block (and signoff is signoff is needed).  The block should be submitted to the staging bucket[1] for addon blocks, and via kinto admin[2] the block should be available to be signed off.  When the block is signed off via kinto admin it should be in the publicly viewable blocklist too.  If the block is then edited on AMO the update should propagate to kinto as well.

(kinto admin based signoff will be disabled at a later stage once signing is implemented on the AMO side)

for addons.allizom.org (stage):
[1] https://settings-writer.stage.mozaws.net/v1/buckets/staging/collections/addons/records (_not_ really practical to access on stage because needs basic auth)
[2] https://settings-writer.stage.mozaws.net/v1/admin
[3] https://kinto.stage.mozaws.net/v1/buckets/blocklists/collections/addons/records

for addons-dev.allizom.org  `kinto.dev.mozaws.net` is used for everything and there isn't strictly a signoff via kinto admin as it's not set up on that server.  The records should be visible straight away on `https://kinto.dev.mozaws.net/v1/buckets/staging_addons_dev_allizom_org/collections/addons/records`

**Comment by eviljeff** [comment]
Importing existing blocks and editing those is going to have to wait until https://github.com/mozilla/addons-server/issues/13598 is implemented (and even then it's a hack)

**Comment by AlexandraMoga** [comment]
I've verified the AMO blocklist - kinto integration on stage and I have the following results:

- add-ons with no sign-off + included in legacy checked
  - a new block is added on AMO -> an entry is created in kinto and Approval is available. The information added on AMO (i.e. version range, reason, URL) is visible in kinto;
  - a block is updated on AMO -> the updates added on AMO are visible on the corresponding block listed in kinto. Approval is again required
  - a block is deleted on AMO -> the entry is deleted from kinto and Approval is required

- add-on with sign-off + included in legacy checked
  - a new block or multiblock is added on AMO -> block request is approved on AMO -> entry is created in kinto
*note that  in case of a multiblock, kinto is creating separate entries for each of the guids blocked
  - a block is updated on AMO -> updates are Approved -> update request is visible in kinto
  - a block is deleted on AMO -> delete request is Approved -> the entry is deleted from kinto and Approval is required
  - for either of the above actions -> block request is Rejected on AMO -> nothing will be sent to kinto

Each of the actions mentioned above will be reflected in the [publicly viewable blocklist](https://kinto.stage.mozaws.net/v1/buckets/blocklists/collections/addons/records)

I haven't checked the api endpoints that required authentication since I do not have credentials for those.

@eviljeff just to double check, we do want to send a request to kinto only when the 'Include in legacy blocklist' checkbox is selected, right?
Also, once the block is approved in kinto, shouldn't this be reflected in Firefox if a user has the affected add-ons installed?

**Comment by eviljeff** [comment]
> just to double check, we do want to send a request to kinto only when the 'Include in legacy blocklist' checkbox is selected, right?

yes, for new blocks and updates to the blocks.  Though if an existing block has "include in legacy" removed it should delete the block from the kinto blocklist.

> Also, once the block is approved in kinto, shouldn't this be reflected in Firefox if a user has the affected add-ons installed?

it should, but I'm not super familiar with testing blocklist integration in Firefox.  afaik as long as the blocklist url is set to the stage blocklist then it will disable the addons once the blocklist is updated.
