### ISSUE TITLE
Primary email changes are not reflected in SFDC

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12472]
Follow up for #12206 

### Describe the problem and steps to reproduce it:
1. Log in to AMO -dev
2. Go to your user profile page and open the FxA account management page in a new tab
3. On the FxA page, add a secondary email address
4. Once you validate your secondary email, set it as your primary email address
5. Refresh the tab where your AMO profile was opened and make sure the email field was updated with the new primary address
6. Verify if the email update has been sent to Salesforce 

### What happened?
There is no record in SFDC of the new primary email 

### What did you expect to happen?
The new email address should be visible in SFDC

### Anything else we should know?
as @pmac noted: 
>I don't believe SFDC is capable of updating email addresses at present for a record as it is the primary key. Have to talk to the SF people about this one.

User Id 10641928 was used for the above test

**Comment by diox** [comment]
Note that this is technically not an addons-server bug. I can see us triggering a sync in the logs, but as noted in the description this is an issue on Salesforce side.

**Comment by blavine** [comment]
I added a story to the IT Customer Operations backlog however, I need a little more info so we can prioritize the work. Can you tell me the following: 

- Business or process impact of not fixing this issue? 
- Do you have a workaround for this issue?

**Comment by diox** [comment]
It prevents us from enabling automatic sync to Salesforce, which we've spent Q3 developing. The only workaround is to continue doing that manually, I'll let @jvillalobos or @caitmuenster can comment on how painful that is and what that impacts.

**Comment by jvillalobos** [comment]
There are other problems caused by changing the primary email address, right? I know @wagnerand has to correct accounts that changed their primary on a somewhat regular basis.

I suppose the impact isn't huge, since the developer would still be contacted to their original primary address (right?). It would only be a problem if the developer changing their primary intend to abandon their old address. It's still an issue, but maybe not a huge one.

**Comment by blavine** [comment]
Thanks for the details. Let me check with my team to see if we know what is causing the issue, what the fix is, and effort to implement.

**Comment by wagnerand** [comment]
Unless I am mistaken and the FxA team has a magical workaround, I believe users who changed their primary email address and are trying to get access to their AMO account using the old email address are stuck, even if they remove the old email address from their AMO account.

**Comment by diox** [comment]
My worry is that is this is not fixed, Salesforce data will irremediably grow out of sync and we won't notice it. This could cause painful issues like a developer not being able to unsubscribe from AMO emails sent through Salesforce, for instance (or, if they cease to be a developer after they have changed their email, this is also likely not to be reflected in Salesforce data)

**Comment by muffinresearch** [comment]
@blavine hi, did you have any updates on a possible fix?

**Comment by blavine** [comment]
Hi @muffinresearch. The COPS team is current working on researching this issue and potential solutions since it is related to an FxA ID issue that was reported. We'll provide an update on progress by end of day next Wednesday. Thank you.

**Comment by diox** [comment]
@AlexandraMoga this should be ready to retest on dev. 

One caveat is that in Salesforce we're now linking FxA accounts and AMO accounts instead of storing the user email in the AMO account data. For this to work, there needs to be an FxA account synced up, and unfortunately the FxA environment we're using is not the one synchronized with Salesforce sandbox, so any AMO account you want to test with might need some manual fixing in Salesforce sandbox before doing the testing - please prepare them in advance and we can coordinate with folks that have access to Salesforce sandbox to prepare the data.

**Comment by diox** [comment]
See also: https://github.com/mozmeao/basket/issues/564

**Comment by AlexandraMoga** [comment]
Test data has been created and is currently pending for verification with the Salesforce team.
