### ISSUE TITLE
Search filters are broken when searching within Complete Themes

### ISSUE THREAD

**Issue by davehunt** [mozilla/addons-server#1247]
Steps to reproduce:
1. Start Firefox with a fresh profile
2. Open https://addons.allizom.org/en-US/firefox/complete-themes/
3. Search for 'nasa'

Expected: Category should be 'Complete Themes'
Actual: Selected Category is 'All Add-ons'

In addition:
- The 'Category' filter cannot be expanded
- When expanded, the 'Works with' filter only shows a single version of Firefox
- After clicking 'Any Firefox' and 'All Systems' in the 'Works with' filter, all add-on types for the search are displayed

Screenshot showing 'expanded' category filter:
<img width="1348" alt="screenshot 2016-01-07 18 25 00" src="https://cloud.githubusercontent.com/assets/122800/12178915/0b044d68-b56c-11e5-9884-4273dcb83e73.png">

**Comment by EnTeQuAk** [comment]
The search isn't context sensitive to the currently selected category but always global. Expanding categories works for me.

![screen shot 2016-07-07 at 10 10 32](https://cloud.githubusercontent.com/assets/139033/16646575/127254d4-442b-11e6-918f-414bd6ff3f01.png)

Closing but please feel free to reopen at any time in case I misinterpreted the issue here.

**Comment by davehunt** [comment]
@EnTeQuAk I think there's still an issue here. When I search for 'nasa' from the Complete Themes page I get one result (on Firefox 48):

![screenshot 2016-07-07 13 17 23](https://cloud.githubusercontent.com/assets/122800/16652967/e702e014-4445-11e6-9c84-7aa0c5e1bfc8.png)

I can now expand the category filter, and clicking 'Complete Themes' shows the same single result:

![screenshot 2016-07-07 13 17 44](https://cloud.githubusercontent.com/assets/122800/16652973/f96e5aee-4445-11e6-803d-88e48787f7e4.png)

Clicking 'All Add-ons' shows 18 results:

![screenshot 2016-07-07 13 17 51](https://cloud.githubusercontent.com/assets/122800/16652977/037ba078-4446-11e6-8ae3-6e5b2cd27524.png)

This suggests that search *is* context sensitive, and that the filter should indicate that we're limiting results to Complete Themes. I'm not sure exactly where the bug is, but there's something strange going on.

**Comment by diox** [comment]
The bug here is subtle. 

Searching from the "themes" page automatically sets the `cat` parameter to "2,0" (encoded as `2%2C0`). This is not a valid category id, it's [a hack that the form uses](https://github.com/mozilla/addons-server/blob/9b2489a249c07bfc739760af0bf1675850eced45/src/olympia/search/forms.py#L118-L129) to set a `type` instead, restraining results to themes only (and no specific category - the `2` part is the id of `ADDON_THEME` type, and the `0` does not match any category id).

Because the `cat` parameter is actually not a true category, the facet filtering in the sidebar ignores it, and pretends that no category is selected. If you expand categories in the sidebar it shows the limited number of categories matching the results. When you select one you clear the hackish `cat` parameter, and that's why it shows what it does.

I think removing this hack, having all pages that want a type search use the `atype` parameter (what clicking on "Complete Themes" does) instead would fix the issue.

**Comment by EnTeQuAk** [comment]
Closing this as it's only relevant for the legacy frontend, I don't see similar problems with the new frontend. In case there are, please re-file there.
