### ISSUE TITLE
Redundant XHR to reviewer tools review page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12476]
### Describe the problem and steps to reproduce it:

It looks like there is a redundant GET XHR to a reviewer tools review page after it has been loaded.

STR:
1. Open devtools network panel
2. Load https://reviewers.addons.mozilla.org/en-US/reviewers/review/lastpass-password-manager for example
3. Inspect requests.

### What happened?

At the end of the request chain, there is a GET XHR to https://reviewers.addons.mozilla.org/en-US/reviewers/review/lastpass-password-manager

### What did you expect to happen?

I don't think that extra XHR is necessary. If it is, we should see if we can refactor the code so we don't need it.

### Anything else we should know?

Assigning to @diox as requested.

**Comment by diox** [comment]
Nice find! Thanks to developer tools "Pause on XHR" we can see that it's coming from this:
https://github.com/mozilla/addons-server/blob/d7ae3e57970e551dbcdd643b8037d511823a90fe/static/js/zamboni/reviewers.js#L185-L199

This is a leftover from Marketplace ([introduced in 2012](https://github.com/mozilla/addons-server/commit/511f76bffb6c549324ca818ddba259776c86e757) when the codebases were still unified), and it has an interesting bug: the check of `if ($node) {` is wrong, it should be `if ($node.length) {`, since `$(something)` always evaluates to a non-falsey object in jQuery. Funnily enough [I fixed that bug in Marketplace 4 years ago](https://github.com/mozilla/zamboni/commit/7b37bab74e7d9dfbd785dc049e858ec78d61c5bf)!

In this case though, we don't need my fix: we just need to get rid of that code entirely, as it's completely useless for AMO.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

Before fix [stage] - extra GET XHR request
![image](https://user-images.githubusercontent.com/31961530/65938940-17795680-e42d-11e9-84c1-b73ba8290c9c.png)


After fix [-dev] - no GET XHR request
![image](https://user-images.githubusercontent.com/31961530/65938971-2c55ea00-e42d-11e9-9081-4b9f2a322ea5.png)
