### ISSUE TITLE
Filter out as many spam accounts / add-ons as possible from Salesforce sync

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12596]
There's a storage cost for the add-on data we store on Salesforce, and we recently had a surge in spamming that has lead to a huge increase in our data. We should filter out as much of this spam as we can from the sync.

Specifically:

- Don't sync add-ons or accounts where the account has been banned.
- Don't sync add-ons that don't have any versions that are approved and signed.
- Anything else we can do?

**Comment by diox** [comment]
The problem is that AMO doesn't know what's the state of the add-on/user in Salesforce when syncing - it sends everything needed, not a diff.

So, if someone creates an account, that gets synced. Later, they are banned, but if we don't sync that you've got stale data in Salesforce. Same problem exists for add-ons if they are rejected after they have been approved once.

Banning equals to soft-deleting though, so it's something that could be handled on the Salesforce side, maybe ? I presume we don't want to keep accounts marked as deleted in Salesforce anyway - when an user is deleted, it's synced with a property indicating it was deleted, so it could be purged from Salesforce at that point, but it's not something we can handle on addons-server side.

**Comment by jvillalobos** [comment]
Yes, we definitely need a way to remove user or add-on data from Salesforce if it's no longer relevant.

**Comment by diox** [comment]
@pmac is that something you can handle in basket, when you receive a call that indicates the account/add-on is deleted/disabled ?

**Comment by pmac** [comment]
we'll need to talk to the salesforce folks. we don't currently have a way to delete contacts via basket. The API may well be able to do it, but it's not something we've done, and my understanding is that Salesforce doesn't make it easy to delete.

@desiree-mofo any thoughts?

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-server/issues/13392

**Comment by diox** [comment]
Actually, leaving open for *existing* accounts.
