### ISSUE TITLE
Cannot login to AMO-dev admin page

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#12645]
Steps to reproduce: 
1.Try to login to https://addons-internal.dev.mozaws.net/en-US/firefox/ or addons-dev.allizom.org/admin using an admin account

Exptected results
User can log in to admin without problems

Actual results:
403 is returned.

NOTES:
Not reproducible on Stage

**Comment by diox** [comment]
I suspect this is just an nginx configuration issue on the admin instance. The 403 is not sent by the addons-server app but rather looks like an nginx one.

One of the changes was to introduce a special "versionless version" of the API for authentication, prefixed with /api/auth/ instead of /api/v3/ or /api/v4/. So maybe the nginx config for the internal instance needs to be changed to allow that.

**Comment by bqbn** [comment]
I've pushed out the nginx change to -dev. Pleaset test it again.

**Comment by vcarciu** [comment]
Issue is not reproducible anymore. Marking bug as verified.
