### ISSUE TITLE
Implement "Flag for human review" flag

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12670]
"Flag for human review" is one of the actions we want to implement in the workflow of the scanners. When triggered, this action should not prevent auto-approval but flag the entire add-on for human review in a separate queue.

Reviewers can unflag, but for now that shouldn't prevent scanners from reflagging the add-on for the same reason after a new upload.

In terms of implementation this is probably going to be a new `BooleanField` in `AddonReviewerFlags` called `needs_human_code_review`. Like `needs_admin_code_review` it doesn't block auto-approval (though may bump the weight assigned to the versions approved). The flag should be set before approving the version, allowing us to see all versions posted since the flag was set including the one that triggered the flag.

We'll also need a separate queue in reviewer tools to see those flagged add-ons. We need to clarify how to display unlisted & listed versions in there, since the flag could be triggered by either and the review pages for are separate for each channel.

**Comment by diox** [comment]
> Reviewers can unflag, but for now that shouldn't prevent scanners from reflagging the add-on for the same reason after a new upload.

For the first stab at this I'm going to follow what we've done for other flags and only let admin reviewers clear the flag.

**Comment by diox** [comment]
> For the first stab at this I'm going to follow what we've done for other flags and only let admin reviewers clear the flag.

Actually... the problem with that approach is that it leaves the add-on in the queue, making it difficult for reviewer to see what they need to care about. I think it's a problem with the implementation design I suggested earlier:

> In terms of implementation this is probably going to be a new `BooleanField` in `AddonReviewerFlags` called `needs_human_code_review`

When doing this, if the flag is set because of an unlisted version, a regular reviewer would end up reviewing the listed version without finding anything wrong with it if the suspicious code is only in the unlisted version.

I wanted to avoid having per-version flags but it seems like a better approach here. We'd display exactly which versions are problematic in the queue, and when an appropriate review would review that specific version the flag could be removed.

**Comment by wagnerand** [comment]
> I wanted to avoid having per-version flags but it seems like a better approach here. We'd display exactly which versions are problematic in the queue, and when an appropriate review would review that specific version the flag could be removed.

Sounds good to me.

**Comment by diox** [comment]
QA: nothing is setting this flag yet, so ping me before testing this and I'll do it on select versions.

**Comment by AlexandraMoga** [comment]
I've verified several scenarios with versions flagged by scanners and I have the following results:

**Working as expected**
- Approving/Confirming approval of a listed add-on removes the flag on all versions
- Approving an unlisted add-on removes the flag on the latest unlisted version only
- Add-ons with mixed (listed and unlisted) versions: approving a listed version doesn't affect the flag for the unlisted version and vice-versa
- the scanner flag is not affected when additional flags are present on the version - i.e. needs admin code review, disable auto-approval, information request etc.
- if the there are more than 10 versions of an add-on and the version flagged by the scanners finds itself on another page, there is  a notification on top of the version history that highlights this fact

@diox for the following cases I need your input.

**I think this is the expected behavior**
- Approving/Rejecting content doesn't remove the scanner flag
- if the developer disables/deletes a version this doesn't remove the scanner flag but the version is no longer present in the Flagged By Scanners queue

**Not working as expected**
- Rejecting a version of a listed add-on doesn't remove the scanner flag from the rejected version - see examples [this](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/creation-date-in-addon-api) and [this](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/project-delay-approval-no-3)

**Comment by diox** [comment]
> **I think this is the expected behavior**
> * Approving/Rejecting content doesn't remove the scanner flag

It is.

> * if the developer disables/deletes a version this doesn't remove the scanner flag but the version is no longer present in the Flagged By Scanners queue

That's the expected behavior, but it's not entirely satisfactory for unlisted. Then again, there is more to do around unlisted in general.

> **Not working as expected**
> * Rejecting a version of a listed add-on doesn't remove the scanner flag from the rejected version - see examples this and this

I'm investigating.

**Comment by diox** [comment]
@AlexandraMoga I just merged a fix for the issue you found, it should land on dev shortly. There is no need to cherry-pick that as the code to set the flag isn't live yet.

**Comment by AlexandraMoga** [comment]
Re-verified on -dev and the rejection part is working now. When using the reject multiple versions method, the scanners flag is removed from the rejected version only - see [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/weather-dev).
This also applies to Content rejections, which is the expected behavior in this case, otherwise we'd end up with a disabled version permanently flagged for human review.
