### ISSUE TITLE
Expose addons users to django admins

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12716]
We should expose the addons-users relationship to django admins so admins can see and edit them.

**Comment by diox** [comment]
QA:
- Addon authors should now appear in addon admin
- Addon authors in devhub, as well as the invitation mechanism, should still work

**Comment by AlexandraMoga** [comment]
Verified on -dev:
- the admin add-on page includes a section where add-on authors are listed
![image](https://user-images.githubusercontent.com/31961530/67857279-05b7cb80-fb1f-11e9-8aa4-9a35dd1084d8.png)
- admins can add new authors, edit the information for existing authors or delete authors altogether
- the DevHub ownership page and the invitation mechanism are still working

@diox I've seen some small differences in behavior between the admin authors list and devhub ownership:
- emails are not sent when a user is added or removed from the admin authors list
- there is no restriction in the admin to have at least one author with an Owner role

I haven't filed followups because the issues are quite small, but if you think it's worth investing the time to work on them, I can create new issues.

**Comment by diox** [comment]
Those differences are expected - using the admin bypasses all that.
