### ISSUE TITLE
Remove "yara" django app

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12750]
We merged both the `scanners` and `yara` apps, so we don't need `yara` anymore. We can remove it in `settings_base` and delete the `src/olympia/yara` directory, unless this is a problem for Django migrations.

This should be done *after* the 2019.10.31 tag.

**Comment by willdurand** [comment]
@diox do you think we need to keep the migration files? If we remove it from the config, then addons-server should not see `yara` anymore, right? Hence, it should be safe to delete all the files?

**Comment by diox** [comment]
If you remove the app, the migrations in there are no longer seen, and therefore no longer applied, which is only really a problem for people that have the yara tables still because they haven't updated & ran the migrations recently.

We had the issue with `akismet` and decided to keep the app & migrations for now.

**Comment by willdurand** [comment]
> We had the issue with `akismet` and decided to keep the app & migrations for now.

Ah, ok. In this case, I am going to close this issue.

**Comment by diox** [comment]
Eventually we'll want to remove both, but we can wait a bit first.
