### ISSUE TITLE
AMO doesn't find files for user-deleted add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12874]
### Describe the problem and steps to reproduce it:

AMO cannot find files for user-deleted add-ons. The files linked from the reviewer tools are just 404.

Assumed STR (not tested):
1. Submit an add-on, possibly need to submit a couple of versions.
2. Delete the add-on.
3. Observe the file status, it should be `STATUS_APPROVED`.
4. Try to download the file from the review tools page.

### What happened?

404 - no file.

### What did you expect to happen?

200 - file download.

### Anything else we should know?

It seems files are not having their status updated when a user deletes their add-on.

**Comment by muffinresearch** [comment]
@wagnerand do you have a proposed priority on this. and is this new?

**Comment by wagnerand** [comment]
I am not sure if this is new. File visibility has come up a few times and we have patched some issues, but maybe we missed a case or two.

I am tagging with P2 to have it above the fold. It's not extremely urgent, but when we run into it, it's a rather significant annoyance and could have impact on our ability/speed on reacting to suspicious or malicious add-ons.

**Comment by diox** [comment]
> Observe the file status, it should be `STATUS_APPROVED`.

Should it ? Shouldn't we set the files status to `STATUS_DISABLED` ?

**Comment by wagnerand** [comment]
> > Observe the file status, it should be `STATUS_APPROVED`.
> 
> Should it ? Shouldn't we set the files status to `STATUS_DISABLED` ?

Sorry, poor choice of words. "should" was describing what I experienced, not what the expected correct thing should be.

**Comment by diox** [comment]
QA: with this fixed, the file status will now be `STATUS_DISABLED` when deleting. The version should be deleted as well. As always with disabling files, we will need to wait for up to one hour for the files to be moved to the right storage (`hide_disabled_files` needs to kick in).

Also, this has implications for permissions needed to review deleted add-ons. We should require the normal `Addons:Review` permission to access the listed review page for an add-on that used to have listed versions before being deleted, and `Addons:ReviewUnlisted` otherwise.

It should still be impossible for a developer to access deleted add-ons with the old devhub URL (by id or by slug).

**Comment by wagnerand** [comment]
> It should still be impossible for a developer to access deleted add-ons with the old devhub URL (by id or by slug).

Does that mean slugs are locked forever?

**Comment by diox** [comment]
> Does that mean slugs are locked forever?

No, deleting clears the slug. Note that I said *impossible*.

**Comment by wagnerand** [comment]
Oh, I read _possible_...

**Comment by AlexandraMoga** [comment]
I've verified this on -dev and I can confirm the following:

- I've looked in django admin File management for an add-on deleted by its developer and the status of files associated with this add-on is "Disabled by Mozilla". Files can be downloaded.
- the status for all add-on versions is "Deleted"
- the add-on slug is deleted
- developers can't access any details of a deleted add-on, either by slug, ID, guid
- reviewers with `Addons:Review` and `Addons:ReviewUnlisted` can access the review page of a deleted add-on if they're querying by the add-on ID

In terms of file downloading, I'm not sure what download method @wagnerand is referring to here:
>Try to download the file from the review tools page.

The method I was thinking of was right clicking on 'All Platforms'  -> 'Save Link As...' in the add-on version history but maybe this isn't the method referred to in the STR.
For the record, my method still doesn't work, i.e. you get to download an `.xpi` but it won't have any contents. 

![image](https://user-images.githubusercontent.com/31961530/69728817-d7350c80-112d-11ea-8b21-c83cc3184c51.png)

**Comment by wagnerand** [comment]
@AlexandraMoga yes, what you described was how I was trying to download it. There is no other way currently to download an xpi from the reviewer tools page.

**Comment by diox** [comment]
@AlexandraMoga can you share the addon you were testing with ?

**Comment by AlexandraMoga** [comment]
@diox the method to download files from Reviewer tools described above it's still not working for me. As said, the saved `.xpi` is seen as damaged or corrupt. 

This is an example of an add-on deleted by the developer - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/616647

**Comment by diox** [comment]
As it turns out, the only way we had to download deleted add-ons until now was through the django admin for files (from /en-US/admin/models/files/file/). I've now also allowed reviewers to download deleted add-ons through the regular download endpoint, the permission depending on the channel. Essentially it means that reviewers should be able to download deleted files just like they were just disabled. Developers (and general public) however should no longer be able to downloaded deleted files.

I've also tweaked permissions required to download source code but it needs a follow-up, I've filed https://github.com/mozilla/addons-server/issues/13006 and there is a pull request up to fix it.

**Comment by AlexandraMoga** [comment]
This is now verified fixed on -dev.
Reviewers with the right permissions (`Addons:Review` for listed and `Addons:ReviewUnlisted` for unlisted versions) can download files using the 'Save link as' option by right clicking on 'All platforms' (screenshot above).
The downloaded `.xpi`contains all the files related to reviewed add-on.

Non-reviewers and the add-on developer can't access the deleted files, even if they have a direct download link.
