### ISSUE TITLE
Group scanner results per add-on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12947]
Scanner results should be grouped per add-on. Note that it should still be possible to triage the individual results.

**Comment by diox** [comment]
Note: it would also be useful for scanner query results (code search).

**Comment by diox** [comment]
I've been [investigating this in a branch](https://github.com/diox/olympia/commit/7f8ef353909cf71810fb8f586806abc54c38a9a6#diff-9641c78db9860fa42e17601aa1218253R93-R98). I could get it to work by having a filter class that does this:
```python
    def queryset(self, request, queryset):
            most_recent_results_per_addon = (
                queryset.values_list('version__addon')
                        .annotate(most_recent_result=Max('id'))
                        .values_list('most_recent_result', flat=True))
            queryset = queryset.filter(pk__in=most_recent_results_per_addon)
        return queryset
```

There are 2 issues with that approach though:
- The filter needs to be at the bottom of the list. It needs to be processed last, because there are actually 2 queries (or a query and a subquery), and the first one at least needs all the filters applied to it.
- We're "losing" the aggregation in the second query, so we don't have information about the other results for each row - we're only displaying the most recent one for each add-on.

Maybe to solve these issues, particularly that second one, *in the context of code search* (regular scanner results are a different beast), instead of having a regular change list, we could make up our own, and start from an `Addon` queryset instead. Ultimately we don't really care about the `SearchQueryResult` objects themselves, except to display matching filenames maybe.

**Comment by willdurand** [comment]
I removed this issue from the Project for now because we discussed this issue again and there is currently no obvious solution to fix it. In addition to that, there seems to be two slightly different use cases: one for the scanner results and the other one for the code search results.

**Comment by AlexandraMoga** [comment]
@diox I see that the grouped results are displayed only for scanner query results, not for regular scanner results. Is this expected?

As for the actual grouping, it looks fine to me. Results are being grouped by add-on/guid and by channel. The grouping is maintained when applying additional filters:

 
![image](https://user-images.githubusercontent.com/31961530/94703057-2009b300-0347-11eb-9bc9-39d2ac6b8a1e.png)

**Comment by diox** [comment]
> @diox I see that the grouped results are displayed only for scanner query results, not for regular scanner results. Is this expected?

Yes, it makes less sense for regular scanner results so we're only doing it for query results for now.
