### ISSUE TITLE
Login session expires too quickly

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#1294]
I have to re-login at least every few days now, while it felt more like weeks in the past. Was this done on purpose, or a regression from the recent migrations?

**Comment by wagnerand** [comment]
That only happens to me if I forget to tick the checkbox `Remember me on this device`.

**Comment by kewisch** [comment]
It happens to me regardless of the checkbox, of course it is expected when unchecked.

**Comment by andymckay** [comment]
The settings have been unchanged since 2010-03-12 I believe. If you click remember me, you get a cookie for 2 weeks. If you don't get a cookie that expires when the session closes. I would ask that you tell us the length of the cookie you've got... but we are moving to Firefox Accounts in a couple of days and that's going to be different. Based on that I'm going to close this... let us know how it works for you in a couple of days.

**Comment by kewisch** [comment]
It has been working for me on FxA and logging in again is much less painful since FxA has longer cookie time. Thanks!
