### ISSUE TITLE
Replace "Reject multiple versions" with "Block multiple versions" for unlisted

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12978]
Follow-up for #12792.

Generally, actions for unlisted versions include:
* Confirm approval (works like listed)
* Reject (works like listed, useful for pending versions that have not been approved/signed yet)
* **Reject multiple versions** (the most relevant for this issue)
* Reviewer reply (works like listed)
* Comment (works like listed)
* (Not sure if request admin approval is still part of the list, it's not super useful, but we can leave it in).

The _Reject multiple versions_ action is not very useful for unlisted versions since rejecting has no real effect.
Yet, we still need a way to drop the "needs human review" flag. Also, the near-equivalent (more severe) action for unlisted would be to block the versions.

**This issue proposes a new action _Block multiple versions_** (replacing _Reject multiple versions_) for unlisted.

On selecting, a selector for versions appears (like for _Reject multiple versions_). 
The action does **not** show a textbox to enter a review message. Clicking _Submit_ would
* Disable the versions (for consistency)
* Drop the "needs human review" flag
* Open the blocklist admin create page, ideally step 2 (where the add-in information is already shown and the admin sets min/max version, url, reason). It would be great if min/max version was already set correctly, taken from the selected versions on the review page.

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and I have the following results:

Working as expected:
- 'Reject multiple versions' has been replaced with 'Block multiple versions' for unlisted add-ons only
- the rejection process for _listed_ versions is still working as before
- reviewers can manually select a range of versions by using the 'Block multiple versions' option
- versions blocked with this method are disabled and the Blocked status will be visible in the version history
- when saving a multiple version block in the unlisted review page, the reviewer is redirected to the admin `/block/add` page to fill in the additional details
- the version range selected in reviewer tools is automatically populated in the `/block/add/` page
- if the version was flagged for human review, this flag is cleared when the 'Block multiple versions' option is used

Needs input from @wagnerand :
- the issue doesn't mention anything about permissions. Since the new rejection process relies on the admin blocklist tool to be opened, reviewers will require `Admin:Tools`and `Reviewers:Admin` permissions. Is this a concern?
- regarding your requests to have the min-max version range automatically populated, there is a scenario in which this doesn't happen. I've filed #13114 to better explain what I mean. Please leave a comment if you think it needs fixing, otherwise you can simply close it.

**Comment by wagnerand** [comment]
> the issue doesn't mention anything about permissions. Since the new rejection process relies on the admin blocklist tool to be opened, reviewers will require Admin:Tool sand Reviewers:Admin permissions. Is this a concern?

Not at the moment. We will revisit permissions in general soon.
