### ISSUE TITLE
elasticsearch `reindex` django command is broken

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13049]
`./manage.py reindex` is supposed to trigger a full re-index of the elasticsearch indexes but it exits too early.
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/6733763/ is an exception thrown "NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')".

**Comment by diox** [comment]
`reindex` works like this:
- Flag the db
- *then*, create a new index
- *then*, reindex all content (that will happen on both the new index and the current one)
- *then*, update aliases so that the alias points to the new index instead of the old one
- *then*, unflag the database
- *then*, delete the old index

The command is supposed to create a celery workflow with all these tasks chained, fire it up, wait with a crude `while` loop for the database to be unflagged, while celery processes all this.

Crucially, that exception we're seeing is coming from `update_aliases`, so it should *not* be happening multiple times... but it does. It also seems to indicate that we've deleted the old index way too early.

The fact that the command returns almost straight away is probably a byproduct of the tasks failing very quickly.

**Comment by diox** [comment]
I'm also seeing this locally. I suspect it's been broken or a while, probably since the last celery upgrade ?

Hard to read, but the workflow looks like this:
`%(olympia.lib.es.management.commands.reindex.update_aliases([flag_database('addons-20191205162444', 'addons', 'addons') | create_new_index('addons', 'addons-20191205162444') | group([olympia.addons.tasks.index_addons([...]), index_addons([...]), index_addons([...]), ...])], [{'remove': {'index': 'addons-20191205161659', 'alias': 'addons'}}, {'add': {'index': 'addons-20191205162444', 'alias': 'addons'}}]) | unflag_database() | delete_indexes(['addons-20191205161659']))`

(I've had to manually trim it since I've got a lot of add-ons locally. Maybe I can get a pretty drawing output to see it more clearly)

**Comment by diox** [comment]
Downgrading to Celery 4.2.x **does not** fix the issue.
Downgrading to Celery 4.1.1 **does** fix the issue.

I suggest the following patch to test locally:
```diff
diff --git a/src/olympia/addons/indexers.py b/src/olympia/addons/indexers.py
 index 612a4d0305..a637ae665e 100644
 --- a/src/olympia/addons/indexers.py
 +++ b/src/olympia/addons/indexers.py
 @@ -496,6 +496,6 @@ def reindex_tasks_group(index_name):
      from olympia.addons.models import Addon
      from olympia.addons.tasks import index_addons
  
 -    ids = Addon.unfiltered.values_list('id', flat=True).order_by('id')
 -    chunk_size = 150
 +    ids = Addon.unfiltered.values_list('id', flat=True).order_by('id')[:3000]
 +    chunk_size = 15
      return create_chunked_tasks_signatures(index_addons, list(ids), chunk_size)
```

You also need a good number of add-ons so that there are enough of them to process. Then fire `manage.py reindex`.

- When the command is broken, it will return without outputting any dots, you'll just have to wait for the initial delay, and the logs should contain the traceback mentioned above multiple times. `update_alias` seems to be running multiple times.  
- When the command is working, it will return a few dots depending how fast the workers manage to process the tasks. Alter the values in the diff above and add more data if it's too fast, but in any case you'll know it's working because the logs will be clean. `update_alias` should be present once.

**Comment by diox** [comment]
The workflow looks like this with Celery 4.1.1:
`olympia.lib.es.management.commands.reindex.flag_database('addons-20191206115322', 'addons', 'addons') | create_new_index('addons', 'addons-20191206115322') | %(update_aliases([olympia.addons.tasks.index_addons([...]), olympia.addons.tasks.index_addons([...]), olympia.addons.tasks.index_addons([...]), olympia.addons.tasks.index_addons([...])], [{'remove': {'index': 'addons-20191206115122', 'alias': 'addons'}}, {'add': {'index': 'addons-20191206115322', 'alias': 'addons'}}]) | unflag_database() | delete_indexes(['addons-20191206115122']))`

Subtle difference, but it makes a lot more sense...

**Comment by diox** [comment]
Another way to view the workflow differences:

With Celery master branch, workflow is "upgraded" to a chord with a group inside:
```python
>>> workflow.tasks                                                                                                                                                                 
[olympia.lib.es.management.commands.reindex.flag_database('addons-20191206130019', 'addons', 'addons') | create_new_index('addons', 'addons-20191206130019') | group([olympia.addons.tasks.index_addons([...]), index_addons([...])])]
>>> workflow.body                                                                                                                                                                  
olympia.lib.es.management.commands.reindex.update_aliases([{'remove': {'index': 'addons-20191206125749', 'alias': 'addons'}}, {'add': {'index': 'addons-20191206130019', 'alias': 'addons'}}]) | unflag_database() | delete_indexes(['addons-20191206125749'])
```

With Celery 4.1.1, workflow is a chain with a chord inside:
```python
>>> workflow.tasks                     
[olympia.lib.es.management.commands.reindex.flag_database('addons-20191206130121', 'addons', 'addons'), olympia.lib.es.management.commands.reindex.create_new_index('addons', 'addons-20191206130121'), %(olympia.lib.es.management.commands.reindex.update_aliases([olympia.addons.tasks.index_addons([...]), olympia.addons.tasks.index_addons([...])], [{'remove': {'index': 'addons-20191206125749', 'alias': 'addons'}}, {'add': {'index': 'addons-20191206130121', 'alias': 'addons'}}]) | unflag_database() | delete_indexes(['addons-20191206125749']))]
```

So Celery > 4.1.1 tries to "optimize" the workflow but ends up breaking the `chord` we want. It's worth noting however that we never explicitly created this `chord`, we relied on the fact that `celery` is supposed to create one when you chain a `group` with a `task`. So maybe there is a way out...

**Comment by diox** [comment]
Now that we only have addons and stats to consider, I think the first step to work around this issue would be to remove the loop inside `reindex`, and have the command only process a single type of index at a time. That will make the chain easier to write, and the code easier to follow, with the only drawback that two commands would need to be run when we need a full reindex with stats - but that only happens in special occasions like a cluster upgrade.

**Comment by ioanarusiczki** [comment]
@diox Please add some STR for qa. Perhaps the weekly release testing search[ test cases](https://testrail.stage.mozaws.net/index.php?/runs/view/23019&group_by=cases:section_id&group_order=asc) could cover for this issue ?

Thanks!

**Comment by diox** [comment]
Yeah, but a reindex will need to be triggered first. I've started one on dev.

**Comment by ioanarusiczki** [comment]
@diox Then I'll start the test cases now on dev. 
Thanks!

**Comment by ioanarusiczki** [comment]
I checked on dev and I don't see issues. 
Verified with FF70(Win10).
