### ISSUE TITLE
fix  TestRankingScenariosWithRecommended intermittents

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13056]
There are up to 5 failures, example fail:
```
__________ TestRankingScenariosWithRecommended.test_scenario_tabbicat __________

src/olympia/search/tests/test_search_ranking.py:853: in test_scenario_tabbicat

    ['Open Image in New Tab', 0.22888695],

src/olympia/search/tests/test_search_ranking.py:77: in _check_scenario

    assert found_score == expected_score, (

E   AssertionError: Expected "Tabby Cat" to be on position 0 with score 3.0745962 but "Tabby Cat" was found instead with score 3.4082708 for query tabbicat

E   assert 3.4082708 == 3.0745962

E     -3.4082708

E     +3.0745962
```

**Comment by diox** [comment]
This is now an extremely common failure on travis. Out of the 15 pull requests opened right now, 8 are failing because of this.

I'm still digging, but here is what I found so far:
- Can't reproduce locally out of 10 tries, running `test_search_ranking.py` tests in isolation or not
- Only seems to be happenning with `TestRankingScenariosWithRecommended` and *not* `TestRankingScenarios`, which is promising.

**Comment by diox** [comment]
So the problem is, we're trying to force ES to refresh twice in a row, but essentially the second call, that happens after we've made the test extension recommended, isn't doing anything. If we add a `time.sleep(1)`, letting ES perform an automatic refresh, then we see the failures - the assertions in the file are all wrong, worked by accident before.
