### ISSUE TITLE
Cannot upload already approved extension: Icons must be square.

### ISSUE THREAD

**Issue by ElectronicManuel** [mozilla/addons-server#13084]
### Describe the problem and steps to reproduce it:
Almost a year ago I deployed a new version of an extension and included the source code since it's using webpack.
The extension was approved and everything was fine. But a few weeks ago I received an email informing me that my extension will be disabled if I don't upload the source code, which was odd considering I already uploaded the source almost a year ago.
I uploaded the source again, just to be sure. But then a few days later my extension got disabled regardless.

I then decided to bump the version and deploy the otherwise same version again.

### What happened?
I received a validation error informing me that the icons must be square. It specifically pointed to [this icon](https://github.com/Softwulf/VideoSyncer/blob/master/src/assets/img/logo.svg).

![image](https://user-images.githubusercontent.com/23333606/70585274-05056100-1bc4-11ea-99b7-c02d61ea8524.png)
![image](https://user-images.githubusercontent.com/23333606/70585304-21a19900-1bc4-11ea-9343-55554fc39500.png)

### What did you expect to happen?
I expected the validation to pass without errors since it did that almost a year ago and I didn't change anything apart from the version. The error also doesn't make sense because the image is exactly square.

**Comment by eviljeff** [comment]
Technically, from looking at the svg source, the width and height _are_ slightly different - `502` vs. `501.9` - but that's perhaps an overly strict rule (i.e. we should round to the nearest int).  @cgrebs for his opinion because it's an addons-linter error.

**Comment by EnTeQuAk** [comment]
That check got implemented quite some time ago but I couldn't find any reference to why the squareness check was implemented. I'm pretty certain it was a requirement but I don't remember if it was something that improves icons shown inside Firefox or otherwise. Maybe @wagnerand or @rpl know.

If neither of that is true we could relax that rule or think about removing it if there isn't any benefit.

**Comment by eviljeff** [comment]
I'd assume it's connected to #5805 that required square icons on the developer hub side.  But I wasn't debating the merit of enforcing square-ness itself, just if we need to be that strict as 501.9 x 502 is going to be resized to a square size without any (noticeable) change in aspect ratio.

**Comment by EnTeQuAk** [comment]
That'll have to be implemented in devhub too, looking at https://github.com/mozilla/addons-server/blob/af81faedd5aab40c8674c76a7dc8e8670b69e5d5/src/olympia/devhub/views.py#L925-L927

I'd be :-1: rounding the sizes because we end up scaling up/down because of that we'll always loose lots of quality. I personally don't think it should be too hard to create exactly square images.

**Comment by eviljeff** [comment]
Fair point @EnTeQuAk .  Okay, @ElectronicManuel you'll have to fix your icon file to have identical width and height numbers.

**Comment by ElectronicManuel** [comment]
I'll contact our designed and ask him to fix that then.
Out of curiosity, how did you find out that the image was 502x501.9?
When I checked the file properties it simply said 502x502
![image](https://user-images.githubusercontent.com/23333606/70641212-8a792780-1c3d-11ea-9bb4-184926f1a058.png)

**Comment by eviljeff** [comment]
svg files are an xml format (so, text) - I read it https://raw.githubusercontent.com/Softwulf/VideoSyncer/master/src/assets/img/logo.svg

**Comment by eviljeff** [comment]
Closing as we've identified the way forward
