### ISSUE TITLE
'Block multiple versions" doesn't update the blocked version range if the add-on has a previous block

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13114]
Follow up for #12978 

### Describe the problem and steps to reproduce it:
1. Upload a new unlisted add-on
2. After the add-on is auto-approved, open its unlisted review page
3. Use the Block multiple versions option to reject and block the available version - `v1`
4. Complete the blocking process on the admin add block page
5. Return to devhub and submit another unlisted version for your add-on
6. Use the Block multiple versions option to reject and block the new version - `v2`
7. Notice the min - max version range populated on the admin `/block/change/` page

### What happened?
The min - max version range is not updated  - the value of the previous block is still populated - `v1`. 
### What did you expect to happen?
The min - max version range should be updated to also include the new blocked version.

### Anything else we should know?
- if the admin reviewer doesn't manually update the version range, the new version will end up disabled but not blocked
- see an add-on example that was reviewed by using the above steps:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/7f446d6625d34815aa9c

**Comment by eviljeff** [comment]
Tbh, I'm not sure if pre-selecting the versions is going to work correctly for existing blocks.

**Comment by wagnerand** [comment]
I can see how this is hard to get right. Instead of pre-selecting all the correct versions, can we add a prominent note on the page that says something like:

`The versions <X>, <Y>, <...> could not be pre-selected because some versions have been blocked already.`, with `<X>`, `<Y>` and `<...>` being the versions coming from the _Block multiple versions_ action. 

The admin can then figure out themselves what the correct range should be, but it's important to list the versions that the admin meant to block in case they forgot or didn't actively make a note to keep in mind.

**Comment by AlexandraMoga** [comment]
There is a warning message displayed now when the above scenario will happen.

[Change block with no pending sign-off]
![image](https://user-images.githubusercontent.com/31961530/82555682-e80c8b00-9b70-11ea-81d0-0ffbbe524899.png)


[Change block with pending sign-off]
![image](https://user-images.githubusercontent.com/31961530/82555708-f22e8980-9b70-11ea-81f3-ae633b1597ac.png)
