### ISSUE TITLE
Delete add-ons with no versions as part of garbage collection cronjob

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13166]
Because of https://github.com/mozilla/addons-server/issues/7135 some `Addon` might be created with no `Version` attached. These incomplete `Addon` instances stay around for no good reason.

#7135 should be fixed but in the meantime, we should delete those extraneous incomplete add-ons from the database, a bit like we delete stale `FileUpload`s. Funny enough, `amo.cron.gc` used to do this 9 years ago, but [it was reverted](https://github.com/jbalogh/zamboni/commit/4e2c688) with this comment added: 
> Incomplete addons cannot be deleted here because when an addon is
> rejected during a review it is marked as incomplete. See [bug 670295](https://bugzilla.mozilla.org/show_bug.cgi?id=670295).

Indeed, we should do more than just checking for `incomplete` status, especially now that pure unlisted add-ons also have this status.

The rules should be something like:
- Add-on with `STATUS_NULL` status
- Created more than 7 days ago
- No versions attached at all, even soft-deleted (this is the important bit)

**Comment by AlexandraMoga** [comment]
Verified on -dev with a few add-on IDs which had their creation date altered to make them older than 7 days. 
All the add-on used had an Incomplete status, caused by various contexts:
1.  add-on had only purely unlisted versions
2.  an incomplete submission started from dev-hub
3.  add-on with all versions deleted by the developer or by an admin 
4.  an API submission which triggered an error

For the first three cases, even though the add-ons appear to have no versions attached (when looking in dev-hub for example, the version were only soft-deleted, so their records can still be found in admin or rev tools => add-ons are not deleted by the cron

In the API example, the add-on was created but there was never any version attached to it => the add-on was deleted by the cron.

**Comment by wagnerand** [comment]
Hm, shouldn't (2) also have the add-on deleted?

**Comment by diox** [comment]
No: In that case, a version has been created.

**Comment by wagnerand** [comment]
Does that version have a file as well?

**Comment by AlexandraMoga** [comment]
@wagnerand yes, the version has a file. This is the [example](https://addons-internal.dev.mozaws.net/en-US/admin/models/files/file/410619/change/?_changelist_filters=q%3D%257Be5d77035-7ee2-4fe5-896d-3148fcb52c40%257D) I've used

**Comment by diox** [comment]
To clarify: this is for a version that has passed validation. In devhub, contrary to an API submission, a failed validation for the initial submission would not result in an addon creation at all. You can't get a versionless add-on through devhub (unless you delete the version afterwards, and even then the version would only be soft-deleted).

**Comment by wagnerand** [comment]
Yes, I get that. I was just wondering whether there is a case where we somehow end up with an add-on, a version but no file.

**Comment by diox** [comment]
That shouldn't be possible, at least not with extensions. If you find add-ons that end up like this, please file an issue.
