### ISSUE TITLE
Run django system checks in a test

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13193]
we need a test that does (the equivalent of) `manage.py check` and fails if there's a failing check.

**Comment by junngo** [comment]
Hi eviljeff :)
Does It add test case using `call_command`function for testing `manage.py check`?

**Comment by eviljeff** [comment]
Personally, I'd be happier if the underlying `django.core.checks.run_checks` method was called and the results processed, than relying on running the command and an error code.  I don't know if @mozilla/addons-engineering have other opinions.

**Comment by diox** [comment]
Django normal test runner executes those tests automatically - somehow, pytest doesn't despite having django integration enabled. So maybe it's worth trying to make a minimal test project to reproduce the issue and file a bug over at https://github.com/pytest-dev/pytest-django/issues

In the meantime though... I don't think manually calling `django.core.checks.run_checks` is that much better than calling `manage.py check`. But instead of doing it via `call_command`, I'd add the `manage.py check` call, with a test on the return value, in the `codestyle` job (which should really be called `linting` or something).

**Comment by diox** [comment]
Valuable enough that we should keep this opened for a little while longer.
