### ISSUE TITLE
Include list of matched files in customs result

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13220]
It would be nice if the customs scan result page would also include the list of matched files, next to the list of matched rules, ideally linking to the file in the file viewer.

Note that for now, we might want to point it to the old file-viewer since most unlisted files have not been extracted yet and thus code-manager doesn't see them.

**Comment by willdurand** [comment]
> It would be nice if the customs scan result page would also include the list of matched files, next to the list of matched rules, ideally linking to the file in the file viewer.

Implementation idea: let's only consider `customs` (so other scanners would not have what is explained thereafter). We have the JSON with all the information we need so we could add a new row in the page (above the raw JSON one). This row should list all the files (with links to the file viewer) for each matched rule.

**Comment by willdurand** [comment]
> Implementation idea: let's only consider `customs` (so other scanners would not have what is explained thereafter). We have the JSON with all the information we need so we could add a new row in the page (above the raw JSON one). This row should list all the files (with links to the file viewer) for each matched rule.

Looks like we can do this for all scanners, actually.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev and stage. The 'Matched rules' section from a scanner details page is now including a direct link to the file(can be multiple files) that generated it. The link opens in the old file viewer. This will also work for disabled and deleted files, if the user has the correct permissions. 

Note that since `wat` doesn't have any rules yet, this section will be empty, but, assuming that we're going to have rules for `wat` as well, it makes no sense to hide it temporarily. 

![image](https://user-images.githubusercontent.com/31961530/72432994-0f0d1780-37a1-11ea-9868-2cf607e69a78.png)
