### ISSUE TITLE
Add a new permission for the scanners admin

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13239]
Let's introduce new permissions for accessing the scanners admin so that both admins and privileged users with this new permission can view the scanners rules/results. We'll have permissions to view the scanner results, view the scanner rules and edit the scanner rules.

Admins should still be able to access the scanners admin and triage the scanner results.

**Comment by AlexandraMoga** [comment]
I've verified the new scanner admin permissions on -dev and I have the following results:

Prior condition: these permissions need to be combined with the `Admin:Tools` permission in order to be able to access the `/admin/models/`

1. User with `Admin:ScannersResultsView` - can view all the entries listed in Scanner results, can view a scanner result detail page; doesn't have access to Actions fields (i.e. reporting as false or true positive); doesn't have access to Scanner rules at all (i.e. trying to open a linked scanner rule will throw a 404)
1. User with `Admin:ScannersRulesView` - can view all the entries listed in Scanner rules, can view a Rule detail page; cannot add, change or delete scanner rules; doesn't have access to Scanner results at all (i.e. trying to open a linked scanner result will throw a 404)
3. User with `Admin:ScannersRulesEdit` - can view all the entries listed in Scanner rules, can view a Rule detail page, can add, change or delete scanner rules; doesn't have access to Scanner results at all

  * The above permissions can be combined to allow broader access to scanners, as needed.

4. Full Admins' access to Scanners results and rules works as before
5. Users with `Admin:Advanced` permission don't have access to Scanners anymore

@willdurand I'd like to clarify something with regards to scanner Actions (Report False positive or True Positive): the new `Admin:ScannersResultsView` permission doesn't give access to this option. However, if I'm combining this permission with `Admin:Advanced`, the Actions fields become available.
Was this intended?

**Comment by willdurand** [comment]
> @willdurand I'd like to clarify something with regards to scanner Actions (Report False positive or True Positive): the new `Admin:ScannersResultsView` permission doesn't give access to this option. However, if I'm combining this permission with `Admin:Advanced`, the Actions fields become available.
> Was this intended?

Yes. I realize that we could have a `Admin:ScannersResultsEdit` instead, though (but we do not actually edit the results).

**Comment by AlexandraMoga** [comment]
@willdurand I think that, in order to make Scanners permissions more independent from other permissions, such as `Admin:Advanced`, having a separate `Admin:ScannersResultsEdit`for managing scanner results would be a good idea. We can replace `Edit` with `Manage` or `Triage` just to make it more clear that scanner results are not actually editable. 
I can file a follow up for this.

**Comment by willdurand** [comment]
> I can file a follow up for this.

Yes, please file an issue to create `Admin:ScannersResultsEdit`.
