### ISSUE TITLE
replace the Block dual sign-off waffle with a condition around addon ADU

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13285]
from https://github.com/mozilla/addons-server/issues/13089#issuecomment-572233744

> One more thing we discussed with the Security people: there could be a threshold for requiring dual sign-off. If all add-ons involved in a block have user counts under that threshold, the block change would be allowed without sign-off. We need to figure out what the right number is, but we talked about 100K being a good starting point.
>
> Since we don't have stats for unlisted extensions at the moment, any ID without stats should required dual sign-off. Once we have complete data this threshold should become more practical.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev based on the following scenarios:
1. Block two listed add-ons, both with ADU >100k => Signoff state is Pending
2. Block two listed add-ons, both with ADU <100k => Signoff state is Published to Blocks
3. Block two listed add-ons, one with ADU >100k and the other <100k => Signoff state is Pending
4. Block one listed add-on with ADU <100k and one unlisted add-on => Signoff state is Pending
5. Block a set of unlisted add-ons => Signoff state is Pending

Note: I've relied only on multiblock submissions because only these are currently supporting dual sign-off

**Comment by eviljeff** [comment]
Note, there's no checking of listed vs. unlisted versions, it's just about `average_daily_users` and unlisted only add-ons end up with 0 average_daily_users, typically (whereas add-ons with listed versions usually have at least 1)

**Comment by AlexandraMoga** [comment]
> Note, there's no checking of listed vs. unlisted versions, it's just about `average_daily_users` and unlisted only add-ons end up with 0 average_daily_users, typically (whereas add-ons with listed versions usually have at least 1)

My goal here was to verify if "any ID without stats should required dual sign-off" was working as expected. If I understood the requirement correctly, if a multiblock submission contains 1 or more add-ons without stats, it should require dual sign off. Hence my use of an unlisted add-on (without stats) and a listed add-on with ADU<100k (which normally would not require dual sign off).
