### ISSUE TITLE
Scanner query rule erroneus redirect

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13552]
### Describe the problem and steps to reproduce it:

Go to a scanner query rule page, and click on the link to a result.

### What happened?

All results for all rules are shown:

`/en-US/admin/models/scanners/scannerqueryresult/?matched_rules__id__exact=9&has_version=all&state=all&scanner=3` redirects to `/en-US/admin/models/scanners/scannerqueryresult/?e=1`

### What did you expect to happen?

Only the results for the relevant rule is shown.

### Anything else we should know?

The redirect does not happen for `/en-US/admin/models/scanners/scannerqueryresult/?matched_rules__id__exact=9`

**Comment by diox** [comment]
Yeah we need to find a better solution that hardcoding which parameters to send, especially now that the scanner results and scanner query results don't have the same filters.

**Comment by ioanarusiczki** [comment]
@diox 
- I went from the general page /en-US/admin/models/scanners/scannerqueryresult/ and clicked on some rules from the `Matched rules` column. The scanner query rules page has a `Matched Results` field which shows the number of the results. If I click it it will redirect to en-US/admin/models/scanners/scannerqueryresult/?matched_rules__id__exact=21 where I see the list of results for a specific rule and not the general list. 

The issue is no longer reproducible on admin tools dev with FF73(Win10).
