### ISSUE TITLE
Reviewer cannot access review tools page for add-on without public or pending versions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13566]
### Describe the problem and steps to reproduce it:

An add-ons reviewer (with permissions `Addons:PostReview`) cannot access review pages for add-ons where all files are disabled.

### What happened?

"You're not allowed to view this page"

### What did you expect to happen?

They should be allowed to view the page and also do write operations like sending a reviewer reply or commenting.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
For most of reviewer tools, there are 2 separate permission checks:
- One in the view itself - typically done by `perform_review_permission_checks`
- One in the review helper, that restricts which actions are available (for the actual review page only)

I believe `Addons:PostReview` already covers the latter correctly - it's just that the former is needlessly paranoid, and restricts such reviewers so that they are only able to see add-ons which are public and whose current version has been auto-approved.

I'm pretty sure we can relax `perform_review_permission_checks`, and probably rename it to indicate that it's more about accessing the page itself than performing the real checks needed for write operations. Need to be careful though, as that function is also currently used in a couple other places.

**Comment by diox** [comment]
@wagnerand I've got a branch with a refactor of the reviewers permission checks. It would allow any kind of reviewer access to any listed review page, while still restricting the available actions as necessary, allowing them to reply or comment in almost any review (*). There is one question regarding public & private whiteboards though: viewing & editing those is allowed for anyone that can access a review page, so any kind of reviewer with my branch. Should it still be the case ? Even for say, recommended add-ons ?

(*) unlisted review page would still be unavailable to listed reviewers.

**Comment by wagnerand** [comment]
@diox Can we change it so that users that only have the `ReviewerTools:View` can only read the page, but not send any request that would cause change of data, incl. reviewer replies, comments, whiteboard changes? It should be a true read-only.

**Comment by diox** [comment]
That's already the case and not changing - `ReviewerTools:View` will never allow write operations. I'm talking about other permissions, like someone with `Add-ons:PostReview` accessing a recommended add-ons page.

**Comment by wagnerand** [comment]
Ah, thanks for clarifying. I would prefer if only reviewers with the respective permission to review the add-on in question can update the whiteboards, for example only reviewers that have `Addons:RecommendedReview` can update them for recommended extensions?

**Comment by diox** [comment]
Ok. Per the description of the issue though, you want them to be able to post replies, though, right ? Just not update the whiteboards ?

**Comment by wagnerand** [comment]
Yes, but only if they would have had access too if there was an add-on with public or pending versions.

Generally speaking should the file status not be a special case. The same permissions should apply depending on the other factors (recommended, unlisted etc), regardless of the file statuses.

For example, a user with `ReviewerTools:View` should be able to access any listed add-on review page, without being able to make any modifications (regardless of what the file statuses are).
A user with `Addons:PostReview` should be able to review all auto-approved listed add-ons, incl. reviewer reply, comment and whiteboard updates, again, regardless of the file statuses. They should be able to access other listed add-on pages like for recommended or auto-approval disabled add-ons, but not allowed to make changes to those.
Similar for users with `Addons:RecommendedReview`. They should be allowed to review, reply, comment, change whiteboards etc on all recommended add-ons but not any others, where they would have read-only access.

Does that sound feasible?

**Comment by diox** [comment]
It makes sense, but the definition of what an auto-approved listed add-on is is tricky: Currently, it's an add-on with a current version set, and that current version needs to have been auto-approved. When all listed version files of an add-on get disabled, they lose that current version, and that's causing the issue here.

Consider the following scenarios: what should happen for each, for an user with only `Addons:PostReview`? :

- Add-on that was auto-approved, but is no longer public because all its files have been disabled (original issue).
- Add-on that was auto-approved, is currently public, but then had another version submitted that hasn't been approved (manually or auto) for some reason (scanner blocking it, flag set by somebody after the initial auto-approve, etc).
- Add-on that was auto-approved in the past, is currently public, but had another version submitted which was manually approved and is now its current version. (So current version was not auto-approved for some reason - either a reviewer that can do that manually approved it before auto-approve or they had their auto-approved disabled)

**Comment by wagnerand** [comment]
> Consider the following scenarios: what should happen for each, for an user with only `Addons:PostReview`? :
> 
>     * Add-on that was auto-approved, but is no longer public because all its files have been disabled (original issue).

The user should be able to access the page, send a reviewer reply, leave a comment and update the whiteboards.

> 
>     * Add-on that was auto-approved, is currently public, but then had another version submitted that hasn't been approved (manually or auto) for some reason (scanner blocking it, flag set by somebody after the initial auto-approve, etc).

Ideally, this would depend on the reason why the latest version was not auto-approved. For example, when an admin manually disables auto-approval, the review should be done by admins only. I don't see that many special cases like this one though, so maybe we can have general "write access" for that user, with a few exceptions.
Could you compile a list of all scenarios where a version/file would not get auto-approved?

> 
>     * Add-on that was auto-approved in the past, is currently public, but had another version submitted which was manually approved and is now its current version. (So current version was not auto-approved for some reason - either a reviewer that can do that manually approved it before auto-approve or they had their auto-approved disabled)

Same as above. It depends on the reason why auto-approval did not happen. Afaik, we already display that information on the review page ("Not auto-approved because..."), so it could be fairly straight forward to collect those scenarios and then we can make decisions for them.

**Comment by diox** [comment]
Let's back up a little bit. We already have a property to restrict a review page to admins, that's `needs_admin_code_review`. When it's set, only admins are able to approve/reject something. It's already working, and will still work with my changes. I think we should continue to rely on this as it's an explicit signal that's easy to keep track of. If necessary (please tell me) we can automatically set it in various situations as well.

In all the scenarios I highlighted, if that flag is set the (confirm) approval and rejection actions would be limited to admins. I'm interested in what should happen when it's *not* set.

**Comment by diox** [comment]
We met with Andreas to discuss this. The approach we're taking:
- Try to merge `Addons:Review` and `Addons:PostReview`, or at least give both to reviewers. We don't need the distinction that badly anymore now that we don't have legacy extensions anymore. This doesn't have to happen now, though.
- Keep current restrictions in place to access review actions (approve/reject). So, depend on `needs_admin_code_review` to limit things to admin, otherwise on current version being public for `Addons:PostReview`, and then the old checks on whether the add-on latest version is unreviewed for `Addons:Review`. If the permissions are merged obviously it gets simpler, but we'll see if we can do that easily.
- Commenting should always be available
- Replying to the developer or using the whiteboard should follow checks for approval.

**Comment by diox** [comment]
QA: Check the original description, but also try all sort of scenarios around permissions in reviewer tools to make sure it still works. The key takeaway from these changes is that read-access to review page (and privacy policy/eula) should be available at all times for any kind of reviewer now, but actions on that page should be limited depending on the add-on you're looking at and the permissions you have. The only exception is unlisted review page/pure unlisted add-ons, which continue to require an unlisted reviewer even just to access the review page, as it might contain private information.

What action should be available is mostly straightforward:
- Content review of any kind require `Addons:ContentReview`, except if the admin content review flag   is set
- Recommendable extensions require `Addons:RecommendedReview` except if the admin content review flag or admin code review flag is set.
- Unlisted require `Addons:ReviewUnlisted` except if the admin code review flag is set
- Static themes require `Addons:ThemeReview` except if the admin theme review flag is set
- Listed extensions with their current public version auto-approved require `Addons:PostReview` except if the admin content review flag or admin code review flag is set.
- Rest require `Addons:Review` except if the admin content review flag or admin code review flag is set.
- Things reserved for admins require `Reviews:Admin`

Commenting, Requesting super review and Replying actions requirements are more lax: you need to be an appropriate reviewer for the add-on type but that's it. So, for an extension, you should have either `Addons:Review`, `Addons:PostReview`, `Addons:RecommendedReview` or even `Addons:ContentReview`, regardless of add-on state. For themes, you need `Addons:ThemeReview`.

Users with `ReviewerTools:View` should be able to access reviewer tools pages but not perform any actions.

We'll probably give `Addons:Review` to reviewers that already have `Addons:PostReview`, so the distinction might not be useful in the future, but it stays for now.

**Comment by AlexandraMoga** [comment]
I've verified the new set-up for Reviewer permissions by following the guidelines provided and also taking into account the original issue reported.
I've tested both individual permissions and combinations of several permissions.
Overall, I didn't find inconsistencies and the outcome was within the guidelines.
A full report of the scenarios tested is [here](https://docs.google.com/spreadsheets/d/1cA0qS4--wSetpEB_XbRN5rWpT7fiZm3iukcIKhI2l1Y/edit#gid=921659092)

@diox or @wagnerand there is one thing I'd like to clarify:
Are reviewers on prod always having the `ReviewerTools:View` permission? If not, they will see an error page in the following scenario:
- a user from one review group, i.e. `Addons:PostReview` opens a Content review page and posts a Comment or a Reviewer reply => the comment is Saved and the review is processed but the user will see an unauthorized error page in the next step, where the content review queue should be opened.

The error will not happen if the user has `ReviewerTools:View` which makes general queues viewing available.

**Comment by diox** [comment]
@wagnerand to confirm, but we removed `ReviewerTools:View` from content-reviewers, and presumably regular reviewers as well. Ultimately I think we can live with that edge case (regular reviewers shouldn't care about content review anyway), the action will have taken place, it's just the redirect that is leading to an unauthorized page ?

**Comment by AlexandraMoga** [comment]
> it's just the redirect that is leading to an unauthorized page ?

Yes, I've only seen the error there. It will (obviously) happen for any review queue for which the user doesn't have permission.

**Comment by diox** [comment]
Ok. You can file a follow-up in case we decide to fix it, but I don't think it's very important.

**Comment by wagnerand** [comment]
Hm, do I understand correctly that a user with `Addons:PostReview` can access a content-review page and submit a content-review, but not access the content-review queue?

**Comment by AlexandraMoga** [comment]
> Hm, do I understand correctly that a user with `Addons:PostReview` can access a content-review page and submit a content-review, but not access the content-review queue?

You cannot Approve or Reject a content review, but you can Comment, Reply or Request super review. However, as you stated, you won't have access to the content review queue.

**Comment by wagnerand** [comment]
Ah, ok. I agree it would be nice to fix, but not very important. Worst case, we can add all users with `Addons:PostReview` to the content-reviewers group.
