### ISSUE TITLE
Sorting for "See more Recommended extensions"

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#13574]
### Describe the problem and steps to reproduce it:
From the AMO homepage click "See more Recommended extensions" text link within its shelf.

### What happened?
You're taken to a "search results" type page, with pagination that currently runs to four pages. 

### What did you expect to happen?
Since the Search results page tells me there are (currently) "97 extensions found" I expect the four pages to list them in some type of consistent order in case I want to peruse the entire list of Recommended extensions. However when you click from page to page you find an inconsistent ordering and often see extensions you already saw on previous pages. User is never certain if they've seen the entire list.

**Comment by bobsilverberg** [comment]
Just wondering, are we going to implement this for *any* search with `random` as its sort sequence, or just for ones that are for recommended add-ons?

**Comment by devaneymoz** [comment]
> Just wondering, are we going to implement this for _any_ search with `random` as its sort sequence, or just for ones that are for recommended add-ons?

That's a @jvillalobos call. I was just focused on having a place we can direct people to see a comprehensive list of Recommended extensions. Should probably exist for Recommended themes as well.

**Comment by diox** [comment]
`random` should only be available as a sort parameter when searching for recommended add-ons (and no query).

**Comment by bobsilverberg** [comment]
> `random` should only be available as a sort parameter when searching for recommended add-ons (and no query).

That's not currently the case. I can request search results using `random` as a sort sequence and *not* request recommended add-ons only. I'm not sure this is a big issue, and I think it's fine to use this new approach for any search that is sorted by `random`, but I wanted to raise the question, which is why I did it at https://github.com/mozilla/addons-server/issues/13574#issuecomment-590991334.

**Comment by diox** [comment]
Can you file a new issue for this on `addons-server`, with the exact API request you're making ? I correctly get this error message when I try:
`["The \"sort\" parameter \"random\" can only be specified when the \"featured\" or \"recommended\" parameter is also present, and the \"q\" parameter absent."]`

**Comment by bobsilverberg** [comment]
> Can you file a new issue for this on `addons-server`, with the exact API request you're making ? I correctly get this error message when I try:
> `["The \"sort\" parameter \"random\" can only be specified when the \"featured\" or \"recommended\" parameter is also present, and the \"q\" parameter absent."]`

Ah, you're right, my mistake. I tried changing the URL in addons-frontend, and forgot that we added code to make sure we do not send an API request like that to addons-server, so while I thought it was issuing the API request, it in fact was not, and was removing the `random` sort param.

**Comment by ioanarusiczki** [comment]
@diox I checked on AMO dev the following:
- a GET response for the search API with the query parameters below will return the extensions/themes in the same order. 
https://addons-dev.allizom.org/api/v5/addons/search/?recommended=true&sort=random&type=statictheme&page=1
https://addons-dev.allizom.org/api/v5/addons/search/?recommended=true&sort=random&type=statictheme&page=2
https://addons-dev.allizom.org/api/v5/addons/search/?recommended=true&sort=random&type=extension&page=1
https://addons-dev.allizom.org/api/v5/addons/search/?recommended=true&sort=random&type=statictheme&page=2
- on AMO frontend I see the addons in the same order since yesterday. Opening a new tab or refreshing the page will keep the same order. An addon from the first page will not be available again in the second. 

I'm waiting the time to expire and will re-check once again. But so far this looks fixed to me on dev with FF73(Win10).
