### ISSUE TITLE
Add information about whether a file is minified to the reviewers API

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#13589]
### Describe the problem and steps to reproduce it:
When retrieving information about a file via the [Browse](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#browse) and [Compare](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#compare) APIs, the consumer should be able to tell whether the file requested is minified, based on the determination from the linter.

### What happened?
Information about whether the file is minified is not included in the response.

### What did you expect to happen?
Information about whether the file is minified should be included in the response.

### Anything else we should know?
This is a request for additional data in the API response. 
This blocks https://github.com/mozilla/addons-code-manager/issues/1462.

**Comment by willdurand** [comment]
@diox @EnTeQuAk do you know why a new attribute is needed in the API response instead of code-manager looking into the linter results on its own?

**Comment by diox** [comment]
That's a good point. I thought this wasn't available but it already is, so maybe we don't need that ? Or maybe the validation endpoint is called too late in code-manager ?

**Comment by EnTeQuAk** [comment]
I thought that the decision whether or not a file should be minified or not will be happening in parallel to loading other parts of the site - including linter results.

So having it directly in the response sounded like the way to go.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I was looking for `uses_unknown_minified_code` in Browse and Compare views for these files which look minified to me:
https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689955...1689956/?allowSlowPages=true&path=src%2Fcontribute%2Fcontribute.bundle.js
https://code.addons-dev.allizom.org/en-US/compare/618913/versions/1690391...1690392/?path=psl.min.js
If I make a request from Postman like:
https://addons-dev.allizom.org/api/v5/reviewers/addon/618525/versions/1689955/compare_to/1689956/
https://addons-dev.allizom.org/api/v5/reviewers/addon/618525/versions/1689955/compare_to/1689956/
I even tried to add a parameter such as ?path=src/contribute/contribute.bundle.js also works with ?selected_file=psl.min.js (the minified file) the API responses will return this:

![minified files](https://user-images.githubusercontent.com/33448286/76953908-25a62b00-6918-11ea-9aea-9d66063710e1.png)

I am probably not making something right in my API requests ?

**Comment by EnTeQuAk** [comment]
So, I looked into this. The changes implemented here aren't being used by the code-manager right now so there won't be any visible changes.

If I hit https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689955...1689956/?allowSlowPages=true&path=src%2Fcontribute%2Fcontribute.bundle.js and look into the network panel, I do see the `uses_unknown_minified_code` property to be `true`.

![Screenshot from 2020-03-19 13-23-41](https://user-images.githubusercontent.com/139033/77067192-ded23700-69e4-11ea-9bd1-02218263214a.png)

For the manifest.json I assume that's fine and kinda expected since the file is fairly small the heuristics might not entirely match in this case.

The same seems to be working for the `psl.min.js` example

![Screenshot from 2020-03-19 13-25-21](https://user-images.githubusercontent.com/139033/77067368-2658c300-69e5-11ea-9cc7-a7f7d6c9f87c.png)

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I can't make it visible from Postman but I see it too in the Network if I look at the response when I hit on the file.

![response in the network panel](https://user-images.githubusercontent.com/33448286/77068491-63c24e00-69ef-11ea-8f38-e1030fdf9163.png)

verified on dev with FF74(Win10).
