### ISSUE TITLE
Allow users with ReviewerTools:View to view validation results for listed add-ons

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13652]
`ReviewerTools:View` permission should allow you to see validation results for listed add-ons. This would be useful to allow users with that permission to access the code manager (code manager specific APIs already support that permission, they have `AllowReviewer` in their `permission_classes` which supports that permission for read-only requests)

**Comment by ioanarusiczki** [comment]
@diox 
I created in admin tools dev a new group "Reviewers:Read Only" and added the `ReviewerTools:View` permission:
- The user in this group has access to view all rev tools queues the same way an admin does except that this user has no rights to modify anything. POST methods return a 403 Forbidden (for example when from the addon review page, to approve, reject or  add a comment is not possible).

![the rev tools](https://user-images.githubusercontent.com/33448286/76312656-2e757c00-62dc-11ea-8d4b-a4ae41b0e130.png)

 
- The access in read only is granted for queues such as Other Pending Review, Flagged by Scanners, Auto Approved Add-ons, Content Review and so on except for  All Unlisted Add-ons and Expired Information Request where access is forbidden. 

- I could access the validation reports (An example: https://addons-dev.allizom.org/en-US/developers/addon/clamellar-gazee-flartrose/file/254328/validation)

- I could access the code manager Browse and Compare pages in read only - adding comments is forbidden. 
- in case all the above is the expected behavior the only problem I found is that the Rev tools link cannot be accessed from the frontend - it is not included in user's drop down menu. The link is available only from dev hub. Let me know if I should file the issue.
