### ISSUE TITLE
Handle add-ons with no name in auto approval

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13678]
Somehow, an add-on with no name was successfully submitted and this [broke auto-approval](https://github.com/mozilla/addons-server/issues/13675). 

Ideally this should be prevented completely (we thought it was...) but we should be able to avoid the issue when approving (refusing to approve the nameless add-on, or catching the failure, or avoiding it completely) and therefore prevent the breakage we experienced.

**Comment by AlexandraMoga** [comment]
It looks like the signing API doesn't throw an error when the `"name"` key is missing from the manifest or contains just an empty string. 
However, in this case your add-on will be created without a version, so auto-approval wouldn't be triggered.
I'm still not sure how the issue seen in prod was possible.

**Comment by AlexandraMoga** [comment]
@diox since we couldn't identify exactly how the add-ons found on prod had no name, I'm not sure if my test method is correct.
Here is what I've done:
- I've submitted an unlisted add-on with no `"name"` defined in the manifest
- I've used the admin Override failed validation to allow the add-on to pass submission
- the add-on was created without a name but it had a valid version
- I've waited a few minutes and the add-on was auto-approved

This is the add-on: https://addons-dev.allizom.org/en-US/developers/addon/468f4d91071043da92d3/versions

**Comment by diox** [comment]
That should be ok, yeah. I've verified in dev and it has no name indeed. This is a good add-on to keep around for testing various stuff with :)
