### ISSUE TITLE
Slow query in addons_collections

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1367]
```
# Time: 160112 22:56:14
# User@Host: addonsrw[addonsrw] @  [172.31.8.184]  Id: 2021520
# Query_time: 5.165989  Lock_time: 0.000088 Rows_sent: 2  Rows_examined: 2018199
use addons_mozilla_org;
SET timestamp=1452639374;
SELECT DISTINCT (
            select 1 from addons_collections as ac
                where ac.addon_id = 201 and ac.collection_id = collections.id
                limit 1) AS `has_addon`, `collections`.`id`, `translations`.`localized_string` FROM `collections` LEFT OUTER JOIN `collections_users` ON ( `collections`.`id` = `collections_users`.`collection_id` ) LEFT OUTER JOIN `translations` ON ( `collections`.`name` = `translations`.`id` ) WHERE (("en-us"="en-us") AND (`collections`.`author_id` = 10701592  OR `collections_users`.`user_id` = 10701592 )) ORDER BY `translations`.`localized_string` ASC;
```

This is occuring on master, so isn't good, 2018199 rows examined for 2 rows sent. Tracker: #1244

**Comment by diox** [comment]
The culprit is this method of `CollectionManager` in [`bandwagon/models.py`](https://github.com/mozilla/addons-server/blob/9b81d4f63204194d10293e23427ace1f7e07389f/src/olympia/bandwagon/models.py#L82):
```python
    def publishable_by(self, user):
        """Collections that are publishable by a user."""
        owned_by = models.Q(author=user.id)
        publishable_by = models.Q(users=user.id)
        collections = self.filter(owned_by | publishable_by)
        return collections.distinct().order_by('name__localized_string')
```

It's called in the `ajax_list` view, which adds a `.with_has_addon(addon_id)` call (annoyingly there is a  `publishable_by()` method on the `Collection` model that is completely different and not relevant here)

Need to investigate more why we'd need to do all this... it's probably going away with the new frontend though.

**Comment by diox** [comment]
So, it's used when adding something to a collection: we call the `ajax_list` view to display a list of collections the user owns/can edit. 

The part that kills perf is the condition on *publishable by* and *owned by* at the same time - the `has_addon` subselect, and even the order by name and distinct are not the biggest issue. 

We could conceivably fix that with raw SQL, by using `UNION` instead of `OR`, that may help. But AFAIK new frontend will remove the ability to have multiple contributors to a single collection, so even if the view somehow stays, we won't have this problem any more.

**Comment by eviljeff** [comment]
@diox multiple contributors is staying but this isn't applicable via the API... right?

**Comment by diox** [comment]
mmm... so far we've avoided this in the API / new frontend, but if multiple contributors are staying this could come back. The only reason we're not experiencing this is in the API is that the API does not let you list all collections that you can modify, only the ones you've created.

**Comment by eviljeff** [comment]
Okay, we can argue against that feature being reintroduced then :)
Closing this then.
