### ISSUE TITLE
Investigate not generating new blocklist when we don't need to

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13694]
In https://github.com/mozilla/addons-server/issues/13616 we are now generating bloom filters for the blocklist every 6 hours and pushing that to kinto. Because there is a different salt every time, the blocklist blob is going to be different every time, even if there are no new blocks, and clients will download that new version (we don't support diffs) every time they download new remote settings (which should happen every 24 hours).

We estimated that the blob could grow up to ~ 500KB if the blocklist starts to contain millions of items. So, that's 500KB that would be downloaded by every active client every 24 hours even if we don't make changes to the blocklist.

Is that an issue ? If so, we need to avoid generating a new blocklist if there are no changes to existing blocks and no new blocks.

**Comment by eviljeff** [comment]
If Firefox sticks with rule that any xpi signed after the signing-date from the last bloomfilter is okay then it should be fine to only produce new bloomfilters when the blocklist content has changed.  (Potentially we could switch to generating the filters on demand too for quicker reaction time to any blocks, but that could cause a strain if lots of separate submissions are approved in a short time)

**Comment by AlexandraMoga** [comment]
@eviljeff I guess that in order to test this I need to make sure there are no changes made to the AMO blocklist after the `last_modified` time returned in https://kinto.dev.mozaws.net/v1/buckets/staging_addons_dev_allizom_org/collections/addons-mlbf/records

**Comment by eviljeff** [comment]
yes.  If there aren't any changed/new Blocks then there shouldn't be a new record created.

**Comment by AlexandraMoga** [comment]
There are no changes to the AMO blocklist since March 25th. 
https://kinto.dev.mozaws.net/v1/buckets/staging_addons_dev_allizom_org/collections/addons-mlbf/records is not returning any records today. 
I still don't understand why the endpoint asks for authentication instead of simply returning a 404 if there are no records generated.

**Comment by eviljeff** [comment]
> I still don't understand why the endpoint asks for authentication instead of simply returning a 404 if there are no records generated.

The bucket and collection aren't generated until there's a need to on the dev test server so if there's no new bloomfilter and after the clearance time there's no bucket or collection either.  The asking for auth if the bucket doesn't exist seems to be a kinto thing (presumably because there could be private buckets they don't want to expose)
