### ISSUE TITLE
Deprecation warning FixedOffset in reviewers.serializers

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#13690]
```
src/olympia/reviewers/serializers.py:143

  /home/travis/build/mozilla/addons-server/src/olympia/reviewers/serializers.py:143: RemovedInDjango31Warning: FixedOffset is deprecated in favor of datetime.timezone

    commit_tzinfo = FixedOffset(commit.commit_time_offset)
```

**Comment by apsychogirl** [comment]
Hi, I want to work on this. Can you please explain what fixes do I need to make here?

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @EnTeQuAk

**Comment by eviljeff** [comment]
You just need to change that line of code to use `datetime.timezone` instead

**Comment by ManishAradwad** [comment]
Hello, I'd like to work on this issue.

**Comment by diox** [comment]
A few extra hints for someone wanting to fix this issue:
- `timezone` must be imported from `datetime` since we already do `from datetime import datetime` at the top of the file. Also, `FixedOffset` must be removed as well.
- `timezone()` takes a `timedelta`, not an `int`
- `commit_time_offset` represents a number of minutes
