### ISSUE TITLE
Allow admins to invalidate a user session

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13705]
Admins need a way to invalidate a user session to force a re-login into AMO.

We would probably want to add a button or action to the django admin user profile page that would clear `auth_id` for that user.

**Comment by ioanarusiczki** [comment]
@wagnerand I tested on admin tools dev - FF74(Win10). 

On the user's profile page from admin tools:
- The "Reset session(s)" button is available at the bottom of the page. All buttons from the section changed the appearance (look better than before). 
- from dev hub after the session reset, the user is redirected to the fxA page and log in is possible. 
- from the frontend pages the login of the user is not possible (log out button is not responding). When private pages such as collections or user profiles are clicked a warning message is displayed. I filed https://github.com/mozilla/addons-frontend/issues/9260
- as an admin I could ban the user then I could use the "Reset session(s)" button again. The admin is notified that the user had their session(s) reset but it has no effect since the user was previously banned ( I will get the "Incorrect authentication credentials." red message on the frontend and dev hub indicates "You do not have permission to perform this action.") Let me know if that's ok.

**Comment by wagnerand** [comment]
@ioanarusiczki Thanks for testing!

As far as I understand, the _Ban_ and _Reset session_  button should work independently.
* Banning a user prevents them from future logins, but if the user is already logged in, they can still use their current session.
* Resetting the session for a user invalidates the current session, which means they would be treated as a logged out user and would have to re-login.

**Comment by ioanarusiczki** [comment]
@wagnerand Thanks for the info!

- I checked again so I can confirm that the ban right now behaves like the Reset session - on the frontend or devhub. If using the session is wanted then I think that a separate issue should be filed. 

- maybe the `Reset session` could be inactive if the ban was applied on the user ?

**Comment by wagnerand** [comment]
@diox I did not expect the behavior Ioana described. It sounds like we don't even need to use the _Reset session_ button if we ban a user? Can you confirm that from looking at the code?

**Comment by diox** [comment]
Banning a user already resets their existing sessions, yes - it would be a pretty weak ban if it didn't affect users already logged in :) But the action to reset the sessions remains useful if you don't want to ban the user (since banning has other implications).

**Comment by wagnerand** [comment]
Ah, right. I suppose we're all good here then!
