### ISSUE TITLE
A theme is marked as recommended in the Search API results but it is not recommended anymore

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13713]
### Describe the problem and steps to reproduce it:

1. Go to: https://addons.mozilla.org/en-US/firefox/search/?recommended=true&sort=random&type=statictheme
2. Look for "Cheshire Cat -Night" (could be on the 2nd page)
3. Observe that is has a "recommended" badge
4. Go to its detail page

### What happened?

The add-on is not recommended so it does not have a "recommended" badge.

### What did you expect to happen?

The add-on is either not recommended and it should not be listed in the search results OR it is recommended and there should be a badge on its detail page.

### Anything else we should know?

It could be a sync error between Elastic and the AMO DB.

**Comment by diox** [comment]
I believe this is due to a long-standing issue (*) with changes in a collection that don't trigger a reindex of the add-ons that were part of it before (themes use a special collection to figure out whether or not they are recommended, and not the "normal" mechanism in place for extensions). This is not a new issue, though we should definitely fix it.

(*) May have been reported already.

**Comment by diox** [comment]
Previously reported issue : https://github.com/mozilla/addons-server/issues/8673

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/pull/12956 likely caused this : We removed the code for featured collections, and in doing that removed the code that indexed the add-ons when a featured collection changes in one way or another, but we still need to do this for this special featured themes collection.

**Comment by diox** [comment]
In the meantime I've asked ops to reindex the affected themes.
