### ISSUE TITLE
'Invalid parameter: state` for a login triggered by a Block action from Rev Tools

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13752]
Prerequisites: User is logged out in django admin

### Describe the problem and steps to reproduce it:
1. Log in with an admin user on AMO
2. Open a listed add-on review page 
3. Scroll down to More actions and click on 'Block add-on'
4. Enter valid admin credentials on the FxA login page
5. Click Sign in

### What happened?
The following error is received:
![image](https://user-images.githubusercontent.com/31961530/76881268-94847500-6881-11ea-929d-e0cbc4afb912.png)

You can also see this error in the console with a 400 status code:
```
POST https://stable.dev.lcip.org/auth/v1/oauth/authorization
```

### What did you expect to happen?
Log in is successful 

### Anything else we should know?
- it will also happen for unlisted add-ons when the Block multiple version option is used
- I did not reproduce the error when I tried to log into django admin from other links from Reviewer Tools or Dev Hub

**Comment by eviljeff** [comment]
This is because we're using the `state` parameter to confirm what type of blocklist Submission object we want to make (add/change vs deletion) but it's conflicting with fxa which already uses a `stage` parameter.  

I think we can just drop the `state` param from review pages (they don't try to delete submissions and the default is add/change), or otherwise we'll need to switch to a different param and handle that throughout BlockSubmissionAdmin.

**Comment by eviljeff** [comment]
This is something to do with how `state` is handled by FxA.  `state` contains an encoded copy of the url a client was trying to navigate to and it seems there's a max length - the ?guids on the end of the url exceeds that length

**Comment by eviljeff** [comment]
I'm not really sure if there's a good fix here on the AMO side.  We don't know if the user is auth'd in the admin internal instance from the reviewers domain, but if they're not, and the url is too long, it'll fail.  It could happen anywhere on the site we have a page behind auth - it's just obvious here because the guids param tends to make it longer than a straight path.

**Comment by eviljeff** [comment]
In addition to the encoded `next_path` making the `state` param exceed the maximum length, the current functionality in django admin is to strip off the path beyond /models/ after you complete auth which means the user wouldn't end up on the blocklistsubmission creation page anyway.

**Comment by AlexandraMoga** [comment]
@eviljeff the issue is fixed for for the case in which the block action is triggered by clicking on the Block add-on button, i.e the scenario described in the STR.

However, the issue will still reproduce for unlisted addons when the Block multiple versions option is used (there was a note in the STR that mentioned this as an additional trigger). I can file a follow up issue for this second case.

**Comment by eviljeff** [comment]
> However, the issue will still reproduce for unlisted addons when the Block multiple versions option is used (there was a note in the STR that mentioned this as an additional trigger). I can file a follow up issue for this second case.

Please do.   I did try to handle that case too but I think the POST is getting eaten
