### ISSUE TITLE
Hide "wat" and "mad" options in the list of scanners to create a new rule

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13851]
Given that we do not have rules for the "wat" and "mad" scanners, let's hide them in the list of scanners displayed in the form of a scanner result:

<img width="486" alt="Screen Shot 2020-03-30 at 11 41 53" src="https://user-images.githubusercontent.com/217628/77898529-9257e880-727b-11ea-85af-e11f6b7a9815.png">

**For QA:** we should not see "wat" and "mad" in the list displayed above when this issue is fixed.

Note: I suppose we can use this: https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_for_choice_field but I am not sure.

**Comment by avgupt** [comment]
@willdurand  can you please help me with how I could navigate to this page?

**Comment by willdurand** [comment]
> @willdurand can you please help me with how I could navigate to this page?

You should go to the django admin: http://olympia.test/en-US/admin/models/, then `Scanners rules` and click the `+ Add` button.

**Comment by AlexandraMoga** [comment]
The select field for scanner rule creation will include only `yara` and `customs` now:

![image](https://user-images.githubusercontent.com/31961530/80087488-cf09bd80-8563-11ea-91fb-710181b5d05a.png)

@willdurand This patch introduces a small regression for scanner query rule creations.  In https://github.com/mozilla/addons-server/pull/13430, scanner query rules were restricted to show only `yara`, but now they also have `customs` in the select list, same as regular scanner rules. 

I can file a follow so that can be fixed (again).

**Comment by willdurand** [comment]
> @willdurand This patch introduces a small regression for scanner query rule creations. In #13430, scanner query rules were restricted to show only `yara`, but now they also have `customs` in the select list, same as regular scanner rules.
> 
> I can file a follow so that can be fixed (again).

Yes, you can file an issue. I am not sure why this is different now, though.
