### ISSUE TITLE
code-manager does not finish loading for admins for some add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13889]
https://code.addons.mozilla.org/en-US/browse/2633678/versions/4995785/ is stuck showing `Loading linter information...`. In the web console, I see CORS request failures:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons.mozilla.org/en-US/developers/addon/cookie-api-test-extension3/file/3540155/validation.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons.mozilla.org/en-US/developers/addon/cookie-api-test-extension3/file/3540155/validation.json. (Reason: CORS request did not succeed).
```

Loading that file validation page manually redirects me to https://addons.mozilla.org/en-US/developers/addon/cookie-api-test-extension3/submit/details

@diox has figured out the cause for this, I'll leave it up to him to add more details, as needed.

**Comment by diox** [comment]
Haven't checked yet if that's a regression from https://github.com/mozilla/addons-server/issues/13652 or if that's always been there lurking. It happens only to add-ons that are incomplete, with missing metadata but a non-deleted, non-disabled listed version present - because that endpoint is a devhub one, the `dev_required` decorator helpfully tries to redirect you to finish the submission process... Funny enough *not* having admin permissions but having `ReviewersTools:View` bypasses the problem.

It looks like at first glance we could fix it by swapping the order of those 2 `if` in `dev_required()`:
```python
        if acl.check_addon_ownership(request, addon, dev=True,
                                     ignore_disabled=True):
            # Redirect to the submit flow if they're not done.
            if (not submitting and
                    addon.should_redirect_to_submit_flow()):
                return redirect('devhub.submit.details', addon.slug)
            return fun()
        # allow reviewers for read operations.
        if allow_reviewers_for_read and (
            acl.is_reviewer(request, addon) or acl.action_allowed(
                request, permissions.REVIEWER_TOOLS_VIEW)):
            return fun()
```

Allowing reviewers first sounds like a good idea...

**Comment by eviljeff** [comment]
> Haven't checked yet if that's a regression from #13652 or if that's always been there lurking

It's a very good candidate for the regression - before ` if allow_reviewers:\n    if acl.is_reviewer(request, addon):` was first but now then `acl.check_addon_ownership` check happens before it.

**Comment by diox** [comment]
Yeah, makes sense. I remember changing the ordering on purpose, but then again I went back and forth with different solutions for this issue so this might not have mattered for what I was trying to fix in the end, so we should try to change the ordering back and see what breaks...

**Comment by ioanarusiczki** [comment]
@wagnerand 
I submitted incomplete listed add-ons - I did not end the submission flow. 
From admin en-US/admin/models/addons/addon/ I went to the Reviewer Tools (listed) link and from there I tried to open the codemanager.
With an admin account the file will not be visible. - it is loading infinite

![reproducible with admin account](https://user-images.githubusercontent.com/33448286/78346833-48873f00-75a8-11ea-8c62-3d5f827fd3a9.png)

I still can't figure out how to make these type of incomplete addons visible in the flagged by scanners queue from rev tools - seems like if I don't complete the submission the addons won't show up here.
I still must test around.

**Comment by wagnerand** [comment]
@ioanarusiczki it's possible they don't show up in the queue. However, they show up on the scanner admin page (`/admin/models/scanners/scannerresult/`), and that's how I cam across it.

**Comment by wagnerand** [comment]
> It happens only to add-ons that are incomplete, with missing metadata but a non-deleted, non-disabled listed version present...

Sounds like a fairly limited case, should probably be a P2 then.

**Comment by ioanarusiczki** [comment]
@wagnerand Yes, from scanner results the listed review page can be accessed probably anywhere in admin tools where the listed/unlisted links are now available. Looks like the old file viewer does not have this problem.

I might be wrong but personally I can't see the use of the listed review pages for this type of incomplete add-ons. As an admin I can send a question to the developer but the developer can't see it because in dev hub he can only resume or delete this add-on.

**Comment by diox** [comment]
> I might be wrong but personally I can't see the use of the listed review pages for this type of incomplete add-ons. As an admin I can send a question to the developer but the developer can't see it because in dev hub he can only resume or delete this add-on.

The developer might have grabbed a signed listed version somehow, so we definitely need code manager and the review page to work.

**Comment by ioanarusiczki** [comment]
@diox This issue is no longer reproducible. - FF75(Win10)
I verified this on dev with an admin account. From /admin/models/scanners/scannerresult/ or en-US/admin/models/addons/addon/ I could open the review pages and then the codemanager file viewer for listed incomplete add-ons.
