### ISSUE TITLE
Add-on can't be submitted because of platform selection

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#1390]
STR:
1) Download XPI from https://app.box.com/s/0d8w6q736mimkleknem8enkglan5ckev
2) Upload it at https://addons-dev.allizom.org/developers/addon/submit/1 (choose All Platforms or anything else in the platform selection checkboxes).

Observed:

After uploading, the platform selection checkboxes are all disabled and unchecked, blocking the submission from continuing.

Not this add-on doesn't have a maxVersion set. If this is the cause of the error, then we should just show a validation error instead. I'll ask the developer to give that a try.

**Comment by muffinresearch** [comment]
Trying this locally adding a maxVersion does appear to fix the checkboxes being disabled.

**Comment by andymckay** [comment]
I think @magopian has tried to fix this but the original STR from @jvillalobos still happens. Could you have a look please @diox?

**Comment by diox** [comment]
@magopian did some work to have a default max version for WebExtensions, this is something else, since this is a plain old .xpi. 

The validator notices the lack of max version and outputs a warning, not an error (and it's not a recent regression, I tested with an older validator too to be sure). This would work and allow you to submit the extension, except addons-server code also does some checks to see compatible applications and fails to find any because of the lack of max version.

I don't know all the edge cases. Is there a reason the validator is not considering this an error ? @jvillalobos do you know ?

**Comment by jvillalobos** [comment]
I believe the error was triggered in the metadata retrieval stage rather than the validation stage. It used to work, so I don't know what happened that makes it fail now. And by "work" I mean that it followed the MDN doc, and only accepts these [version strings](https://addons.mozilla.org/firefox/pages/appversions/).

**Comment by diox** [comment]
I'll make sure they are mandatory again then, thanks.

**Comment by diox** [comment]
(This will go to production with the next amo-validator bump)
