### ISSUE TITLE
'Invalid parameter: state` for a login triggered by a Block multiple versions action in unlisted review pages

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13931]
Follow up for #13752 
Prerequisites: User is logged out in django admin

### Describe the problem and steps to reproduce it:
1. Log in with an admin user on AMO
2. Open an _unlisted_ add-on review page
3. Use the 'Block multiple versions' action to block one or more add-on versions
4. Enter valid admin credentials on the FxA login page
6. Click Sign in

### What happened?
An `Invalid parameter: state` error is received and you can't login

### What did you expect to happen?
Log in is successful 

![image](https://user-images.githubusercontent.com/31961530/78767226-fcb30c00-7992-11ea-9043-26dac14c90ec.png)

**Comment by eviljeff** [comment]
After investigation, turns out the problem is the same as #13752 - i.e. the next_path when encoded as state (along with other state information) exceeds the maximum length.

A url looks like `/en-US/admin/models/blocklist/block/add_addon/<addon-id>/?min_version=1.0&max_version=1.0` - if the combination of the addon-id and version strings is too long, it fails.  I could do something similar to the addon id, i.e. pass on the version pks and expand to version strings, but it's less clear cut as the version pks are also pretty large on prod. 

@AlexandraMoga what addon & versions did this fail on?

**Comment by AlexandraMoga** [comment]
@eviljeff this is an add-on example that will reproduce the issue:
review page; https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/480740e3e7a24dcd8813
It could be any of the two versions available, although the version strings are pretty normal, i.e. they are not too long.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
I am able to log in successfully when using the Block multiple version method for unlisted add-ons.
