### ISSUE TITLE
Allow including or excluding files in code search

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13966]
It would be helpful to admins if there was a way to include and exclude files or file patterns during the definition of a code search. This could speed up performance and reduce load.

**Comment by diox** [comment]
A special `filename` variable is automatically going to contain the filename. So, for instance, to write a rule that would only apply to JSON files containing `foo`:
```
rule json_foo {
    strings: $foo = "foo"
    condition: filename matches /\.json$/ and $foo
}
```

Or only `manifest.json` files that contain `foo`:
```
rule manifest_foo {
    strings: $foo = "foo"
    condition: filename == "manifest.json" and $foo
}
```

Or all files that contain `foo` *except* for `.json` files:
```
rule not_json_foo {
    strings: $foo = "foo"
    condition: not filename matches /\.json$/ and $foo
}
```

etc.

**Comment by willdurand** [comment]
> This could speed up performance and reduce load.

That won't work with the approach we took but on the other hand, this is not so much a problem I think.

**Comment by diox** [comment]
The following special variables will be available:
- `is_json_file ` (`true` for filenames ending with `.json`)
- `is_manifest_file` (`true` for `manifest.json` file at the root)
- `is_locale_file` (`true` for `messages.json` files in `_locales/` folder at the root)

**Comment by AlexandraMoga** [comment]
@diox should these variables be specified in the definition when creating a new yara rule or are they included by default?

**Comment by diox** [comment]
They are always automatically present for you to use in the rule conditions if you wish.

**Comment by AlexandraMoga** [comment]
I've created an add-on that would match a specific rule, making sure that the rule match was placed in the files targeted by the special variables:
- one match in `manifest.json`
- one match in `_locales/messages.json`
- one match in a random `.json` file

Then I've run the following code searches:

(Inclusions)
1. _match_rule_ (includes the special variables by default) => the search runs normally on all the add-on files

(Exclusions)

2. _match_rule_ and `not is_json_file` => the add-on was not found during code search because `.json` files were not scanned 
3. _match_rule_ and `not is_manifest_file` => the add-on is found but the `manifest.json` is not scanned
4. _match_rule_ and `not is_locale_file` => the add-on is found but the `_locales/messages.json` is not scanned

Look like this is the expected outcome based on what was required.
