### ISSUE TITLE
Send email to developer if add-on submission is pending review after a few hours

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#13974]
If an add-on submission hasn't been signed and is pending review after a few hours, the developer should be sent an email to let them know that the file is still pending review and it could take up to a couple of days to get a resolution.

The text of the email [can be found here](https://docs.google.com/document/d/1msQ-vvDi7GDK04bTp8P5MJgiXoejTrSZ_EOay7HCUA0/edit?ts=5e8d0852#heading=h.tvvrctr03w7t). I suggest sending the email after a 3 hour wait, since I think that should cover for any normal server-side signing delays. Happy to change it if others think there's a better range.

/cc @caitmuenster

**Comment by diox** [comment]
- If they submit several versions, should we notify for each ?
- If they submit a new version before we send notification for the previous one, should we still send the notification ? (For listed, the previous version would automatically be disabled, but not for unlisted)

Underlying question here is: should we keep track of the notifications we sent with a per version flag, or a per add-on flag ? And when should we reset that flag ?

**Comment by jvillalobos** [comment]
Per add-on. If a new version is uploaded the delay should be reset.

**Comment by diox** [comment]
Note for QA: the delay is 3 hours, but we only check that we should send emails every hour, and it can take a few minutes to process everything, so the delay before a developer is notified is between 3 and 4 hours approximately.

**Comment by ioanarusiczki** [comment]
@diox I could use a review for the scenarios below which are already applied. I am waiting the e-mails for now:

**the first listed add-on version**

As far as I know the first listed version is pending 24hours for auto-approval. 
- the first version of an add-on should send the standard notification.
- I submitted the first listed version and then I disabled the auto-approval. This should delay the 24h approval and then send the new notification. 

**new listed add-ons version**
- a new version for an add-on and then I disabled auto-approval.
-  a new version which is now pending in the recommended queue.
- a new version which has the auto-approval delayed indefinitely.

**unlisted add-ons**
- I submitted the first version of an unlisted add-on which is flagged by scanners indefinitely.
- I submitted a new unlisted version which has the auto-approval delayed indefinitely.

**Comment by diox** [comment]
The new notification should be sent in all these cases after 3 to 4 hours.

**Comment by ioanarusiczki** [comment]
@diox Results:
- for the listed add-ons I've received an e-mail and it took ~3-4 hours.

Exceptions were:

[This example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/human-review-delay3). The version is submitted on June 2, 2020, 12:35 p.m. and the [e-mail ](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/93902/change/
) is received at June 2, 2020, 1:05 p.m. It was pretty fast, after 30 min. 

[This example](https://addons-dev.allizom.org/en-US/developers/addon/history-autodeleter/versions/1691462) submitted June 2, 2020, noon and I've noticed the e-mail has been generated twice. [First e-mail](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/93908/change/) then the second [e-mail](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/93909/change/)

- I do not find e-mails generated for the unlisted add-ons.

The add-ons are: 
[Unlisted new Version 2](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/human-review-delay3)
[Unlisted  first Version 5.0.7](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/ec2f200f65954b5683d6)
[Unlisted new Version 5.0.7](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/8ece2234f10e44c4b782) 
[Unlisted  first version ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/ec2f200f65954b5683d6)5.0.7 (from a different account)
[Unlisted new version 5.0.7](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/154b2ca27eff421e93d7) (from a different account)

 - the e-mail includes some  useful links after "Thank you for your attention. " which are not mentioned by the [doc](https://docs.google.com/document/d/1msQ-vvDi7GDK04bTp8P5MJgiXoejTrSZ_EOay7HCUA0/edit?ts=5e8d0852#).
 I hope the content is alright. 

![links](https://user-images.githubusercontent.com/33448286/83629651-2b202280-a5a3-11ea-8a9f-3854f5756ee9.png)

**Comment by diox** [comment]
> [This example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/human-review-delay3). The version is submitted on June 2, 2020, 12:35 p.m. and the [e-mail ](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/93902/change/) is received at June 2, 2020, 1:05 p.m. It was pretty fast, after 30 min.

This is a weird, interesting edge case. The version was created recently yes, but its nomination date was far in the past, because it inherited it from the previous version attached, that was blocked & disabled some time ago. I need to add something to handle this.

> [This example](https://addons-dev.allizom.org/en-US/developers/addon/history-autodeleter/versions/1691462) submitted June 2, 2020, noon and I've noticed the e-mail has been generated twice. [First e-mail](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/93908/change/) then the second [e-mail](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/93909/change/)

That is normal: there are 2 authors attached to this add-on, and each one received a separate email.

>     * I do not find e-mails generated for the unlisted add-ons.
> 
> The add-ons are:
> [Unlisted new Version 2](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/human-review-delay3)

Wrong copy/paste ? This is the one you mentioned above, it doesn't have unlisted versions.

> [Unlisted first Version 5.0.7](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/ec2f200f65954b5683d6)
> [Unlisted new Version 5.0.7](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/8ece2234f10e44c4b782)
> [Unlisted first version ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/ec2f200f65954b5683d6)5.0.7 (from a different account)
> [Unlisted new version 5.0.7](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/154b2ca27eff421e93d7) (from a different account)

Mmmf. So unlisted versions don't have nomination date... I also need to handle that.

**Comment by ioanarusiczki** [comment]
@diox 

> Wrong copy/paste ? This is the one you mentioned above, it doesn't have unlisted versions.

yes, I wanted to redirect to https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/0008d7c270d44b61842c

**Comment by diox** [comment]
@jvillalobos in the following scenarios:
- Author uploads a version, it gets held up, they submit another one before the delay, say 2 hours after. When should we send the email ?
   - If we wait 3 more hours, they might wait another 2 hours, notice the same problem, upload another one, etc and we'll never end up sending them the email.
   - If we don't wait, we might end up sending the email within minutes after they submitted the second version. This might even mean we'd send the email right when the new version is being approved.
- Author uploads a version, it gets held rejected. After some time, they submit another one. When should we send the email ? The main problem here is that we don't really distinguish between this scenario and the previous one, because in both cases the initial version stats is `Disabled by Mozilla`, and the `nomination` date isn't reset in either case.

**Comment by jvillalobos** [comment]
> Author uploads a version, it gets held up, they submit another one before the delay, say 2 hours after. When should we send the email ?

I prefer to have the second version reset the delay. So, it will be possible for the dev to keep uploading new versions without getting any notice, hopefully a rare case. And I expect that we'll eventually have limits that will stop a dev from doing this excessively.

> Author uploads a version, it gets held rejected.

Not sure if this is a typo or I'm not understanding the scenario well. Do you mean in cases where a submission is auto-rejected? Do we have cases like that?

**Comment by diox** [comment]
Sorry, I meant to write gets held *then* rejected. If you're fine with a new version uploading resetting the delay, I don't think this scenario would be different from the other one.

**Comment by jvillalobos** [comment]
Okay, sounds good.

**Comment by ioanarusiczki** [comment]
@diox I'll change the milestone and then I'm going to test scenarios.

**Comment by ioanarusiczki** [comment]
@diox 


[This](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/154b2ca27eff421e93d7) was submitted at June 10, 2020, 11:03 a.m. and e-mail was sent 2 min. after it [Date: Wed, 10 Jun 2020 11:05:09 -0000](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/94115/change/) and the e-mail refers to version 5.0.7 (that's from the last week). The new one from yesterday is 5.0.8

[The other one](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/human-review-delay3) look alright. [e-mail](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/94128/change/)

**Comment by diox** [comment]
Alright, so this is what happened:
- We had already set the flag indicating an email was sent for https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/154b2ca27eff421e93d7
- A new version was submitted, which reset the flag
- The cron fired as scheduled at the 5th minute of the hour (happens every hour), a couple minutes after the version had been submitted
- It looked at *every* version auto-approvable, not just the latest one, to figure out whether or not we should email the developer
- The flag indicating an email was sent had been reset so it sent the email, and then set the flag

The problem here is that we should *only* have looked at the last version, realized it was too recent, and waited 3 more hours, and only then send the email, and only about that newest version.

**Comment by ioanarusiczki** [comment]
@diox All e-mails have been sent. I verified this on AMO dev with FF76(Win10).
