### ISSUE TITLE
Missing UI to change add-on visibility when the add-on no longer has listed versions

### ISSUE THREAD

**Issue by jorrete** [mozilla/addons-server#13973]
### Describe the problem and steps to reproduce it:
Addon with only one build set to invisible. Deleted the build and uploaded new one.

### What happened?
After delete last (invisible) build and uploading new one, I can't change the visibility status of new builds. Alson while uploading the new build the page warned me that the addon was invisible but there was no previous build (because a deleted it) and didn't ask me the new status.

### What did you expect to happen?
When uploading the new build should be asked the visibility status. When uploaded should be able to change visbility staus through the interface.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
As far as I can see, the problem with the listing is that the global status was `Awaiting Review` instead of `Incomplete`. When I looked at it, it only had two unlisted versions (both `Approved`), so it is expected that Visibility wouldn't be an option.

**Comment by jvillalobos** [comment]
I fixed the status and replied separately, so maybe there's a bug on why the add-on ended this way, but it might also not be worth investigating.

**Comment by jvillalobos** [comment]
Okay, so it looks like another problem was that the extension was also `Invisible`, and that blocked uploading any kind of version (listed or unlisted). I don't know how an extension could end up like this, but that does sound like a more problematic bug.

**Comment by diox** [comment]
That add-on used to have listed versions, but they were deleted. Presumably before they were deleted the add-on was made `Invisible`, then the versions were deleted, leaving only the unlisted ones... 

Note that it is possible to upload new *unlisted* versions while in `Invisible` state, since https://github.com/mozilla/addons-server/issues/4025 was fixed.

**Comment by diox** [comment]
So:
What governs the fact that you can see (and change) the `Listing visibility` is whether or not you have a listed version (disabled count, deleted do not). We default to the add-on being visible. In addition, while the add-on is invisible, per #4025 you can't upload any new listed versions.

Therefore, if you start with an add-on that has a listed version, make it invisible, then delete the version, you end up stuck. 

A simple solution would be to flip back the add-on state to visible when the last listed version is deleted (it still won't have a listing, since it does not have public listed versions). It might be surprising if the developer ends up uploading a new listed version, but OTOH if you're uploading a new listed version... you probably expect it to show up anyway ?

**Comment by diox** [comment]
Alternative solutions:
- Show the `Listing visibility` at all times, with a different copy to make it clear it will only affect listed versions if one is ever published.
- Show the `Listing visibility` if the add-on had deleted listed versions as well (so they wouldn't get stuck in that scenario)

**Comment by jvillalobos** [comment]
> Note that it is possible to upload new unlisted versions while in Invisible state, since #4025 was fixed.

FWIW, I didn't see _any_ upload options in the DevHub when I looked at this add-on. Maybe it's only allowed via the API?

> A simple solution would be to flip back the add-on state to visible when the last listed version is deleted

That sounds good to me.

**Comment by diox** [comment]
> FWIW, I didn't see any upload options in the DevHub when I looked at this add-on. Maybe it's only allowed via the API?

I think that's because you were looking at the add-on as an admin, not as an actual developer of the add-on. The reporter shared some screenshots on Matrix and they had the upload button (they were just limited to self-hosting).

**Comment by diox** [comment]
Because it could be a bit surprising to automatically change the visibility, I'm considering going with this approach instead:
> Show the `Listing visibility` if the add-on had deleted listed versions as well so they wouldn't get stuck in that scenario.

**Comment by AlexandraMoga** [comment]
The Listing visibility is now visible to developers who deleted all their listed versions while the add-on was set to Invisible:

![image](https://user-images.githubusercontent.com/31961530/122047404-c8ce4480-cde8-11eb-9bfd-91df17d5aa40.png)


As it was pointed in the comments above, the section will disappear when the visibility status is changed, but this is pretty minor. The section comes back once the listed version is submitted.

This issue is verified fixed on -dev.
