### ISSUE TITLE
Prevent signing of new versions if a guid is blocked and the version range is open-ended

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#14029]
If a new add-on version is uploaded for a guid that is already blocked (e.g. an AMO block already exists) and the version range blocked matches the new version, it would makes sense for that new version to not be allowed to be signed.

If we continue to allow signing we'll need to continually issue new blocks when generating new block dbs / stashes. 

/cc @jvillalobos and @wagnerand for input in-case there are any other considerations to take into account before doing this.

**Comment by eviljeff** [comment]
> We could even prevent the submission from going through in the first place.

The previous thinking on this is you'd want a (non-malware) developer to be able to submit a compliant version so the block range could be reduced.  If they can't even upload then that's not possible and admins have to get involved (more work for admins)

**Comment by wagnerand** [comment]
In the past, we have edited the block range before a new version was submitted (we also usually have to manually change the add-on status to re-allow submissions), or (in exceptional cases) the developer submitted a file to us for review via email.

**Comment by jvillalobos** [comment]
Most current blocks are open-ended because there's generally a suspicion of malicious behavior. The add-on is force-disabled and then blocked, and it's a manual process for the dev to contact us and maybe get their listing enabled again so they can submit a new version.

What I'm getting from this proposal is that, instead, only the block would be needed, and instead of disabling and later enabling what the admin would do is edit the block range. I don't know if that makes much difference in the process, but I suppose it's a bit safer because it better integrates blocking and submission changes.

**Comment by eviljeff** [comment]
If we entirely prevent upload (like we do with `amo.STATUS_DISABLED`) then we should think through how this fits with changing the add-on status to `amo.STATUS_DISABLED` - we don't want to inadvertently end up in a situation where we have some add-ons disabled and blocked, and some just disabled, and some just blocked, for no underlying reason beyond a future admin user forgot/misunderstood how it fitted together.

If we go with comment#0 then developers are free to upload a new version that doesn't end up being signed but that seems fine to me in the case of malware developers (extra frustration), and what we'd want in the case of non-malware developers so we can review their submission and change the block range.  `amo.STATUS_DISABLED` would remain for addons where we specifically want to stop further uploads.

**Comment by jvillalobos** [comment]
What does "not allowed to be signed" mean? That it will end up pending review or that it will just be silently disabled/deleted/something else?

**Comment by muffinresearch** [comment]
> What does "not allowed to be signed" mean? That it will end up pending review or that it will just be silently disabled/deleted/something else?

@jvillalobos I think this is part of what we're trying to decide. To help we probably need to step back and thing about some base requirements. 

* Is it useful to keep the upload for a new version covered by an open-ended block? 
   * If we do want to require a record - blocking at the point of upload is not viable.
* When we do open ended blocks how common is it for that to be changed later?
   * This is to make sure we're not optimizing for a marginal use-case.
* What should the experience be like for add-on developers? 
    * This would help us to know how much feedback there should be. Would this provide clear feedback or be silently discarded and what are the pros and cons with each?
* If the add-ons are entered into the system how will this state should be reflected?
   * What will this look like to reviewers and how we control changes to this state.

@wagnerand could you help with answering the questions related to current use-cases? 

I think overall making the block data the single source of truth will make this all easier to reason about.

**Comment by wagnerand** [comment]
The initial comment in this issue was referring to submissions whose versions match an existing block range. For those, I think we should prevent signing, or even prevent successful submission/validation.

All of this is probably one edge-case where we block an add-on but don't set its status to `STATUS_DISABLED`, which we don't do at the moment.

(I could potentially see a change in the workflow for an edge-case of this edge-case. When admins decide to re-allow submission for an add-on, the developer would resubmit, but we would not sign it automatically, until we made sure the resubmission is ok and we have changed the block so the new submission would no longer be covered. That said, there might be further implications I am not aware of at the top of my head, so maybe that is something we could do down the line.)


>     * Is it useful to keep the upload for a new version covered by an open-ended block?
>       
>       * If we do want to require a record - blocking at the point of upload is not viable.

I don't think we need to keep the upload. 


>     * When we do open ended blocks how common is it for that to be changed later?
>       
>       * This is to make sure we're not optimizing for a marginal use-case.

It is uncommon, but it happens.

>     * What should the experience be like for add-on developers?
>       
>       * This would help us to know how much feedback there should be. Would this provide clear feedback or be silently discarded and what are the pros and cons with each?

If we prevent the upload from going through, I think it would be fair to tell the developer that submission failed and why, possibly linking to the block page.
If we prevent signing but let the upload through, it's a little bit more tricky to find the right timing and channel to tell developers.


> 
>     * If the add-ons are entered into the system how will this state should be reflected?
>       
>       * What will this look like to reviewers and how we control changes to this state.

The submission should probably be automatically disabled to prevent a reviewer from accidentally approving it. If approval is necessary, an admin can manually set it to _Awaiting Review_.
That said, if we automatically disable it, there is little gain over just disallowing the submission in the first place.

I'd like to hear @jvillalobos's opinion on developer experience as well.

**Comment by jvillalobos** [comment]
Agree that this is all an edge-case, since for the most part malicious add-ons are totally disabled and new uploads aren't possible in that state. For the other cases, it sounds like the better proposal is to not allow them to be submitted. So, we take the upload, check the version, and if it's within the blocked range we show an error message. Those developers will need to resolve the issue via amo-admins rather than AMO.

**Comment by eviljeff** [comment]
So in summary, (and after speaking to @muffinresearch) we're going to prevent uploads that match blocks at the upload step, after the xpi has been parsed to get the version.  That will fit the aim of comment#0 and not affect too many other parts of devhub/signing api.  

setting `STATUS_DISABLED` will remain an options for admins when they want to entirely lock down the addon listing so it can't be changed/deleted by the developer after we block them. (Deleting the addon on AMO won't allow them to avoid the block, it's matched by guid).  If we want to automate setting that status we can do it in a follow-up issue.

@jvillalobos can you provide copy for the error message?

**Comment by jvillalobos** [comment]
> The version you're uploading matches a [blocklist entry] for this add-on. You can contact [AMO Admins] for additional information.

First link points to blocklist page and second link points to the amo-admins email.

**Comment by AlexandraMoga** [comment]
I've verified this on -dev for the following scenarios:
- submitting a new version for a blocked add-on with an open-ended version range => new version can't be submitted (error message is received);
- submitting a new version while the add-on is blocked for a fixed min -max version range => new version can be submitted if its version sting is not included in the blocked range; otherwise, the error message is received;
- deleting an add-on then submitting a new add-on with the same guid while that guid still has an open-ended block => new version can't be submitted (error message is received);
- deleting an add-on then submitting a new add-on with the same guid while that guid is blocked for a fixed version range => new add-on can be submitted if its version string is not included in the blocked version range*; otherwise, the error message is received

*note that the block from our list will take the information of the new submitted add-on (not the previously deleted add-on that had the same guid). In consequence, the existing version range can become invalid if the new add-on doesn't have a matching version string (like this [example](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26197/change/)). 

Error message:
![image](https://user-images.githubusercontent.com/31961530/82445722-02316500-9aae-11ea-9c5a-e8eb3e519116.png)

**Comment by eviljeff** [comment]
> note that the block from our list will take the information of the new submitted add-on (not the previously deleted add-on that had the same guid). In consequence, the existing version range can become invalid if the new add-on doesn't have a matching version string (like this example).

An interesting edge case.  Not strictly related to this issue because it'd happen to a Block anytime a developer deleted their add-on - we always only consider the versions attached to the current Add-on listing for the guid.  Can you log an issue for follow-up?

**Comment by wagnerand** [comment]
I believe a better follow-up would be to prevent resubmission of a blocked add-ons after it has been deleted. We can do that by adding it to `DeniedGuid`.

**Comment by AlexandraMoga** [comment]
I'll file a follow up with the steps that can trigger this case, sure.

**Comment by eviljeff** [comment]
> I believe a better follow-up would be to prevent resubmission of a blocked add-ons after it has been deleted. We can do that by adding it to `DeniedGuid`.

That's pretty much the same as the status to `STATUS_DISABLED`, which admins can already do.
