### ISSUE TITLE
Add sha256, mimetype and size to File information returned by reviewers APIs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14026]
This supports #14020 

When a client requests data for a specific file, the API should return the `sha256`, `mimetype` and `size` of the requested file. This information is currently only provided in `entries`, but we want the API to be able to return data for a file without the `entries`, hence the need for this data for the requested file.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on dev (I must say I did not finish investigating this entirely) 
For the Browse API my example is https://addons-dev.allizom.org/api/v5/reviewers/addon/618937/versions/1690425/?file=src/capture/index.html
The Compare API is https://addons-dev.allizom.org/api/v5/reviewers/addon/618525/versions/1689955/compare_to/1689956/?file=src/contribute/contribute.bundle.js

They both have now below selected_file the `sha256` and `mimetype` information. The compare view displays it for the base file (the older version).  I don't see `size` though

Browse
![browse API](https://user-images.githubusercontent.com/33448286/80224182-0787c500-8652-11ea-9296-2d32c00ea291.png)

Compare
![compare API](https://user-images.githubusercontent.com/33448286/80224196-0c4c7900-8652-11ea-8e56-535ec7af0455.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this issue on dev with Postman and I also checked in the Console the Responses for the Browse and Compare APIs and I think I can mark the issue verified because:

- I found `size` being available in "file" which was already there if I compared it with the responses on AMO stage but now the difference is that the correct size of the selected file is shown. 
- `sha256` and `mimetype` are available in the responses under "selected_file" which I mentioned already in the comment above (these were available before only in "entries").
