### ISSUE TITLE
Separate Add and Change in Blocklist Submissions actions

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14037]
### Describe the problem and steps to reproduce it:
1. Open the Blocklist submissions model - https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/
2. Notice the entries with an Add/Change action

### What happened?
You can't distinguish between new blocks and changed blocks by simply looking at the list entries. 

### What did you expect to happen?
There should be separate actions for Add (new blocks) and Change (edited blocks)

### Anything else we should know?
If we intend to add some filters based on Action, it would be helpful to keep Add and Change separate 

![image](https://user-images.githubusercontent.com/31961530/79963677-5be44680-8492-11ea-8599-3dcfd1f33507.png)

**Comment by eviljeff** [comment]
This isn't possible because there aren't separate types of submission - the input of multiple guids can contain a mix of change (when the guid already exists in a Block) and add (when it doesn't).

I discussed a while back in https://github.com/mozilla/addons-server/issues/13089#issuecomment-567417573 and Product accepted the argument.
