### ISSUE TITLE
The content review display of links doesn't always match the product page

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#14054]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?

View the descriptions on these two pages:

https://addons.mozilla.org/en-US/firefox/addon/passwall/
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/passwall

The listing has:
[not linked]the[not linked] [linked]awesome passwall community[linked] [not linked]and[not linked]

The content review has:
[not linked]the[not linked] [linked]awesome passwall community[linked] [strange]and learn how to setup your unique password manager.[strange]

The "strange" part shows up as a lighter blue than the link color, changed to the linked color on mouse hover, but isn't linked.

On both pages the final part is inside an "a" tag with no href attribute.

### What did you expect to happen?

The two displays should be the same.

**Comment by wagnerand** [comment]
The invalid HTML causing this is:

```
Check out the <a href="https://github.com/pass-wall">awesome passwall community<a/> and learn how to setup your unique password manager.
````

**Comment by virgilt** [comment]
@wagnerand May I work on this?

**Comment by wagnerand** [comment]
@virgilt Sure, but please keep in mind that this is not an issue we mentor. If you know what the problem is and how to solve it, we welcome you to submit a pull request. If you are looking for issues where we provide guidance, check out the ones that are labeled "good first bug".

**Comment by virgilt** [comment]
@wagnerand I would like to take a swing at it.

**Comment by wagnerand** [comment]
@virgilt Absolutely, go for it!

**Comment by virgilt** [comment]
@wagnerand I'm having problems with docker getting the server to run so I think it's best to pass this issue off to someone else. I don't want to hold it up.

**Comment by caitmuenster** [comment]
This issue is open to contributors, but it might take some trial and error to figure out what the correct fix is.

**Comment by junngo** [comment]
Hello :)
I can't access review admin page on product environment. so, I reproduced this issue on local for understand clearly.

- Review admin (on local)
![1593416400417](https://user-images.githubusercontent.com/29684524/85987154-3c384400-ba28-11ea-8c13-65d6edf8ed1d.jpg)

- Product page (on local)
![1593416403017](https://user-images.githubusercontent.com/29684524/85987166-3fcbcb00-ba28-11ea-80f3-d95db41806dc.jpg)

It works hover function on admin page but not work on product page.
Does this issue allow the product page to use the hover function?

**Comment by bjherbison** [comment]
The admin page doesn't look like what I see. Here is the screenshot I should have attached originally. The light blue on the end of the sentence becomes the same color as the "awesome passwall community" when I hover, but no URL shows up at the bottom of the page (but does when I hover over "awesome passwall community").
![Screenshot_2020-06-29 Passwall – Add-ons for Firefox](https://user-images.githubusercontent.com/4101902/86003424-c01a0e00-b9df-11ea-9661-321cfa15d6d9.png)

**Comment by junngo** [comment]
Thank you so much for the detailed explanation. Thanks @bjherbison :)

The description part is the part that the user writes.
I'm looking at wagnerand's contents, it is thought that the user wrote the wrong tag.
> The invalid HTML causing this is:
> 
> ```
> Check out the <a href="https://github.com/pass-wall">awesome passwall community<a/> and learn how to setup your unique password manager.
> ```

If It write the wrong tag like the one above, it will be shown on the screen as follows.
![Screenshot from 2020-06-30 00-00-37](https://user-images.githubusercontent.com/29684524/86022056-d0c09780-ba64-11ea-9690-b6d2a04ac9d8.png)
Then the appearance of the screen changes according to the `<a>` tag.

So I compared Review admin and Product page. This result occurs because the processing of `<a>` tag is different.
Product page is treated with transparent about `a` tag. But Admin page has various css as below.

- Review admin 
![Screenshot from 2020-06-30 00-08-24](https://user-images.githubusercontent.com/29684524/86023074-29dcfb00-ba66-11ea-94ab-c25e27134473.png)

- Product page
![Screenshot from 2020-06-30 00-08-48](https://user-images.githubusercontent.com/29684524/86023086-2cd7eb80-ba66-11ea-92a5-1ae832387e25.png)

The easiest way to solve this issue is to modify the description about wrong tag directly.
Or, It should modify the css for the admin page, but I am worried that the current tag is being used in all areas.

**Comment by wagnerand** [comment]
The actual issue is that `<a/>` has been used instead of `</a>`. So, the invalid tag breaks that link.

**Comment by Sparsh-Bansal** [comment]
I am unable to find the code files of these two different pages. Can anyone please provide me with the links.
