### ISSUE TITLE
Use the (new) blocklist to label scanner results as "bad"

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14086]
The current approach to label "bad" scanner results is to rely on the `state` property. This is sub-optimal as we miss many blocked add-ons for other reasons (the primary use cases of the `state` property are: (1) triaging the scanner results and (2) assessing the soundness of the scanner rules)

**Comment by AlexandraMoga** [comment]
@willdurand  I've verified this on -dev and I have the following results:

- an add-on is fully blocked (for all versions) => the scanner results for all its versions will be labelled  as `bad`
- an add-on is partially blocked (only for selected versions) => the scanner results pertaining to those versions will be labelled as `bad`
- an existing block is edited by increasing the blocked version ranges => the scanner results for the newly included versions will be labelled as `bad`
- a scanner result is marked as true positive then the add-on is blocked as well => there is only one `bad` scanner result for each scanner (i.e. there are no double entries for the same labelled result)

Potential issues:
- a scanner result label remains `bad` when a previously blocked version becomes unblocked
- a new version for a fully blocked add-on is marked as blocked automatically when submitted; however, the scanner result for this version doesn't show up in the api, i.e it is not labelled as `bad` (example: https://addons-dev.allizom.org/en-US/reviewers/review-unlisted/743bb61d623b425a8143). I guess this might be happening because there is no actual add/edit action on that last version?
- once a scanner result was labelled `good`, it won't change to `bad` if the add-on gets blocked afterwards

**Comment by willdurand** [comment]
> a scanner result label remains `bad` when a previously blocked version becomes unblocked; the same happens when the block is deleted entirely ;

yep, that's a known issue and I don't think we can fix  that. We shouldn't delete blocks very often, though.



> a new version for a fully blocked add-on is marked as blocked automatically when submitted; however, the scanner result for this version doesn't show up in the api, i.e it is not labelled as `bad` (example: https://addons-dev.allizom.org/en-US/reviewers/review-unlisted/743bb61d623b425a8143). I guess this might be happening because there is no actual add/edit action on that last version?

Interesting, yeah I guess you're right. @eviljeff what could we do here?



> once a scanner result was labelled `good`, it won't change to `bad` if the add-on gets blocked afterwards

ha, really? I guess it should.

**Comment by eviljeff** [comment]
> > a new version for a fully blocked add-on is marked as blocked automatically when submitted; however, the scanner result for this version doesn't show up in the api, i.e it is not labelled as `bad` (example: https://addons-dev.allizom.org/en-US/reviewers/review-unlisted/743bb61d623b425a8143). I guess this might be happening because there is no actual add/edit action on that last version?
> 
> Interesting, yeah I guess you're right. @eviljeff what could we do here?

Not much currently, but #14029 will stop those versions from being uploaded.

**Comment by AlexandraMoga** [comment]
Since the first two observations were clarified, I filed #14268  for the last point to be investigated further.
