### ISSUE TITLE
Create a new (experimental) queue for MAD in the reviewer tools

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14085]
Once we fix #14084, we'll have a list of versions that reviewers should examine to improve MAD. We should have a new queue for those versions.

**Comment by willdurand** [comment]
@wagnerand what would be a good name for that queue? Should it be part of the "Flagged By Scanners" section?

**Comment by willdurand** [comment]
> @wagnerand what would be a good name for that queue? Should it be part of the "Flagged By Scanners" section?

we'll go with "flagged for human review" and we'll rename the section to "security scanners".

**Comment by AlexandraMoga** [comment]
@willdurand I had a look at the new MAD queue in reviewer tools and so far I've noticed the following:
- scanner results with a score of exactly `0%` or `100%` will appear in the queue
- scanners with different scores can appear or not in the queue; for example, a [result](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/10187/change/?_changelist_filters=has_matched_rules%3Dall%26scanner__exact%3D4%26state%3Dall) with a score of `1%` was not in the queue, but [another](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/10195/change/?_changelist_filters=has_matched_rules%3Dall%26scanner__exact%3D4%26state%3Dall) one with a score of `65%` was present in the queue (note that I ran these tests while the other scanner flags were disabled/triggered no action)
- in #14084 you also mention "a model disagreement" as a possible condition for scanner results to be present in the queue. What does this mean exactly?

There are a few issues with unlisted add-ons (one of them being that they link to the listed instead of the unlisted review page) but for these I will file a follow up.

I've also seen some empty queue entries (see screenshot). I'm guessing these are some scanner results without a version, but I don't think we should see them in the queue in any case.

![image](https://user-images.githubusercontent.com/31961530/81819005-6c3e8d00-9537-11ea-9f67-4c76390a6af9.png)

**Comment by willdurand** [comment]
>     * in #14084 you also mention "a model disagreement" as a possible condition for scanner results to be present in the queue. What does this mean exactly?

You can forget about that, it's an implementation detail, sorry.

**Comment by willdurand** [comment]
> I've also seen some empty queue entries (see screenshot). I'm guessing these are some scanner results without a version, but I don't think we should see them in the queue in any case.

Ah, that's interesting. I don't see how this is possible, though..

**Comment by willdurand** [comment]
> I've also seen some empty queue entries (see screenshot). I'm guessing these are some scanner results without a version, but I don't think we should see them in the queue in any case.
> 
> ![image](https://user-images.githubusercontent.com/31961530/81819005-6c3e8d00-9537-11ea-9f67-4c76390a6af9.png)

This is caused by a different issue (missing `distinct()` I believe), could you please file an issue?

**Comment by AlexandraMoga** [comment]
@willdurand what about the relation between the score and the presence of the add-on version in the mad queue? I still don't know how exactly to interpret this:

> * scanners with different scores can appear or not in the queue; for example, a [result](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/10187/change/?_changelist_filters=has_matched_rules%3Dall%26scanner__exact%3D4%26state%3Dall) with a score of `1%` was not in the queue, but [another](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/10195/change/?_changelist_filters=has_matched_rules%3Dall%26scanner__exact%3D4%26state%3Dall) one with a score of `65%` was present in the queue (note that I ran these tests while the other scanner flags were disabled/triggered no action)

One thing I forgot to mention:  an add-on can end up both in the Flagged by scanners and in the mad review queue, if certain scanner flags are enabled. Normally, if the reviewer picks the add-on from either of the queues, once the review is concluded, the entries will be removed from both queues. There is though an issue with approvals, for which I filed #14284 as a follow up.

**Comment by willdurand** [comment]
> @willdurand what about the relation between the score and the presence of the add-on version in the mad queue? I still don't know how exactly to interpret this:
> 
> > * scanners with different scores can appear or not in the queue; for example, a [result](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/10187/change/?_changelist_filters=has_matched_rules%3Dall%26scanner__exact%3D4%26state%3Dall) with a score of `1%` was not in the queue, but [another](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/10195/change/?_changelist_filters=has_matched_rules%3Dall%26scanner__exact%3D4%26state%3Dall) one with a score of `65%` was present in the queue (note that I ran these tests while the other scanner flags were disabled/triggered no action)

@AlexandraMoga yeah, that makes sense. The add-on with 65% is there because of model disagreement actually so that's good. It's 0%, 100% and model disagreement.

**Comment by AlexandraMoga** [comment]
In that case, I'll mark this as verified fixed and will file follow ups if I notice anything else.

**Comment by ioanarusiczki** [comment]
@diox 

 I did not see non-extensions displayed in these queues.

I submitted themes, lang packs, dicts with rules which were scanned by all scanners -> as shown by the [admin](https://addons-internal.stage.mozaws.net/en-US/admin/models/scanners/scannerresult/?has_matched_rules=all). Then checked the rev tools queues -> they are not displayed here

Also I 've submitted extensions. -> which showed up in scanners and/or  mad queue.

Verified on AMO stage.
