### ISSUE TITLE
Automate the import of v2 blocks into AMO

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#14094]
Running v2 from AMO's data had two potential issues: 

- Perf impact from multiple records being created rather than a single block of guids in a larger regex.
- Issues with dual-sign off being required in two places.

To workaround this and minimize the risks to the V2 blocklist during the overlap with v3, we are going to keep the existing process of setting up blocks in v2.

This means we will need to import v2 blocks into AMO at an interval rather than as a one-off.

The risks around this are if the import fails then the v3 blocklist won't get updated correctly. So if any part of this process fails errors should result in an alert so we know.

To minimize the chances of problems we will look to avoid unpredictable custom regexes and changes to the format that's currently used.

## Edits/Deletions

We'll need to consider edits and deletions in so much as how we will handle them. 

For imports I think it would make things simpler to not require the import to spot changes to historical data, and for admins handle that manually on a case by case basis in changes to AMO as they happen. This is based on these kind of changes having been fairly infrequent in the past.

It's important that if something is blocked and then that block is edited/removed later in v2 records (and assuming a manual update to AMO), that the the import won't reverse that manual change (thanks to Philipp for raising this point).

**Comment by eviljeff** [comment]
For edits the main decision to make is whether we will allow AMO-side edits to blocks that have been imported from v2.  Don't allow; or allow:
* If we don't want to allow edits then we can always rely on the contents of the v2 collection to be accurate and update every block that's been changed.  But it won't be possible to make any changes to a v2 block on AMO - the object will be read only in django admin with an explanation to update it via kinto admin.
* The alternative is to allow edits on AMO, with a warning that once you edit the block on AMO it will be "disconnected" from the v2 block so any deletes or update won't propagate to v3.  This _seems_ like a perfect option but the fact it's not connected any more won't be visible on kinto admin so whoever is making an edit via kinto admin will have to be careful to check AMO admin too if they want the change to propagate to v3.

Deletes would work in the same way -
* if no edits of v2 blocks from AMO admin then we can just delete the block on AMO on next sync and disallow v2 blocks from being deleted - if you want the block just in v3 you'd have to recreate it via AMO admin (quickly!).  You wouldn't be able to have a block in v2 only.
* otherwise, once you've edited the block on AMO it won't be linked to the v2 block so deleting it from kinto admin will retain it in v3.   (There's a few more edge cases here - if we want to be able to delete a block from v3 only then AMO needs to keep track of the deletion; Ideally there will be some way of just "disconnecting" the block from v2 in AMO admin _without_ editing some of the metadata if you wanted to only delete it from v2 via kinto admin afterwards)

The former options would be easier to implement and clearer for admins (a block would never become v3 only), but they tie us to having the exact same data for a given guid and limit us to v3 always being a superset of v2.

**Comment by eviljeff** [comment]
Not an immediate concern, but we should also consider what we will want to do in September (| the current ESR support period) when the v2 blocklist is formally deprecated and frozen.  We'd turn off the automatic syncing but would we remove all the v2 linkage?  (If we didn't allow edits we'd have to).

Also to consider is the current support in the codebase for updating kinto v2 collections - if all the new blocks are going to continue to be regex based it won't be much use anyway so I guess we can delete it?  (The waffle switch can be disabled in the short term at least)

**Comment by jvillalobos** [comment]
I'm in favor of keeping V2 blocks read-only on the AMO side, so there's a clear source of truth for all blocks (V2 is kinto, V3-only is AMO). When V2 is frozen, we should remove any linkage and edit restrictions. The AMO blocklist would effectively be forked out of Kinto and there would be no further changes on the Kinto side.

**Comment by wagnerand** [comment]
I agree with Jorge.

**Comment by eviljeff** [comment]
Splitting the AMO admin side of the work (making the v2 blocks read-only) to #14141

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/issues/14143 to handle the "alert" mentioned in comment#0

**Comment by eviljeff** [comment]
As the code stands a v2 block will always override an existing block if the guid matches so v2 is the source a truth for blocking for given guid.  

Edge case though: 
* you add a block for `foo@baa` to v3 via AMO; 
* you then add a block for `foo@baa` (either literally `foo@baa`, or a regex that matches it, or an edit to an existing block's regex to match it) to v2 via kinto admin
* import_blocklist would update `foo@baa` to the v2 details
* you then delete the v2 block for `foo@baa` in kinto admin (or edit the regex so it no longer matches)
* import_blocklist would delete the block for `foo@baa` because it's been removed from v2.

The alternative is to _not_ update `foo@baa` during the import_blocklist if it's not originally from v2.  That would mean v3 would have different blocklist information for a guid than v2 though.

**Comment by jvillalobos** [comment]
> import_blocklist would delete the block for foo@baa because it's been removed from v2

Seems unlikely we would remove something from v2 unless it was deemed safe after inspection, so I think this is okay.

**Comment by AlexandraMoga** [comment]
@eviljeff I'm going to test this on stage with kinto admin and I'd like your approval on these high level scenarios I'm intending to test:
- add a new block in kinto admin and make sure an entry will be created in AMO after the cron runs
- edit an existing block on kinto (which also has an equivalent in AMO) and make sure the changes are propagated in AMO
- delete an existing block on kinto (which also has an equivalent in AMO) and make sure that the record is also deleted from AMO

I'm not going to insist on tests that involve editing v2 blocks from AMO since I understand they will be soon set as read only.

Also, how often does the cron run?

**Comment by eviljeff** [comment]
@AlexandraMoga :+1: on the scenarios.  (Stage is ideal - if you were to test this on dev the procedure is a little more involved).  

Note, as the blocks are supposed to be from the approved legacy blocklist, they will need to be signed off in kinto admin so they propagate through from /buckets/staging/collections/addons/records to /buckets/blocklists/collections/addons/records

The cron runs every 6 hours, an hour before the v3 bloomfilter cron, so 05:35am UTC, and +6 hours thereafter.

**Comment by AlexandraMoga** [comment]
@eviljeff I've used kinto yesterday to add/change blocks, based on the discussed scenarios, but I could not see the effects on AMO when I've checked the list this morning. I did the following:

1. new blocks added and approved (signed) in kinto => blocks not present in AMO: 
`addon@darkreaderlonglines2.org`
`dai-EoE@daries.dict.dev.com`
`{a1be413d-8f66-4e0e-a341-9e848842de66}`
`{61337a92-4a88-4730-b84d-05fdf90c26ba}`
2. blocks edited and approved in kinto => changes did not propagate in AMO:
`{232f11df-20ca-49d4-94eb-e3e63d7ae773}`
`kittens@pioneer.mozilla.com`
3. block deleted in kinto (approved) => block is not deleted in AMO:
`{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3d}`

I've verified that all the additions/changes made above were reflected in https://kinto.stage.mozaws.net/v1/buckets/blocklists/collections/addons/records

A note regarding the blocks used for the edit and delete tests: those blocks were created in AMO for  some previous testing and marked also as legacy. They were approved in kinto before I've used them for the tests performed yesterday. I'm not sure if the import should be influenced by this.

**Comment by eviljeff** [comment]
argh! I forget to mention the cron is behind a waffle (and it's off by default)
`blocklist_auto_import` waffle switch has to be `on`|`active=True`
and to avoid confusing edit loops, the waffle switch
`blocklist_legacy_submit` should be `off`|`active=False`

**Comment by AlexandraMoga** [comment]
@eviljeff I have some results to report, finally.

Straight forwards results:
- new blocks added in kinto were imported in AMO
- blocks edited in kinto (applies to changes in any of the editable fields) were updated in AMO

Issues:
- blocks deleted from kinto are not deleted in AMO, although the blocks are no longer present in `/buckets/blocklists/collections/addons/records`

Observations:
- blocks that have not been edited or touched at all in kinto are being re-imported in AMO, so their Last Update date will become the date at which the import happened. The block history includes a log for the import date but with no apparent changes to the block itself ([see example](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/block/148/change/)). Nonetheless, these imports will not be re-created with the new mlbf since there are no actual changes. 
- there is also a significant number of old blocks that were present in kinto, but not in AMO which are now imported; these blocks were also added to stash blocks

I will continue to test this and will try to cover more use cases.

**Comment by eviljeff** [comment]
> blocks deleted from kinto are not deleted in AMO, although the blocks are no longer present in /buckets/blocklists/collections/addons/records

That's unexpected - do you have any examples?

> blocks that have not been edited or touched at all in kinto are being re-imported in AMO, so their Last Update date will become the date at which the import happened. The block history includes a log for the import date but with no apparent changes to the block itself (see example). Nonetheless, these imports will not be re-created with the new mlbf since there are no actual changes.

That should only happen once - we only just added the code that tracked the changes so all prior records were seen as "new"

>    there is also a significant number of old blocks that were present in kinto, but not in AMO which are now imported; these blocks were also added to stash blocks

correctly, I assume?

**Comment by AlexandraMoga** [comment]
> > blocks deleted from kinto are not deleted in AMO, although the blocks are no longer present in /buckets/blocklists/collections/addons/records
> 
> That's unexpected - do you have any examples?

These two guids are still in the AMO admin blocklist (stage):
{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3d}
{badee3c1-a494-4e17-87e3-f5f41a2fed98}

**Comment by AlexandraMoga** [comment]
@eviljeff I've tested the delete part again and this time the blocks were also deleted in AMO.

I'm still not sure why it didn't work in the first test for  these guids:  
{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3d}
{badee3c1-a494-4e17-87e3-f5f41a2fed98}

**Comment by eviljeff** [comment]
I didn't have change to look into the timing - the deletion logic will only have worked if we'd previously imported them.  Otherwise its the same reason as why blocks were reimported even though they'd not changed - the code to detect the changes/deletes had only just landed.
