### ISSUE TITLE
Prevent imported v2 blocks from being edited via AMO admin

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14141]
#14094 will automate the import of the blocks from the v2 blocklist collection on remote-settings, but we also need to stop those blocks from being edited via AMO (or the changes could be overwritten during the next import)

**Comment by eviljeff** [comment]
QA:
with the `blocklist_legacy_submit` waffle off, try to edit a block that was either imported from blocklist v2, or a block that was previously created as `include_in_legacy` when `blocklist_legacy_submit` was on (probably harder to verify because the key information isn't exposed - if a Block was created when the waffle switch was _off_ it would still look the same in django admin). 

Then turn `blocklist_legacy_submit` on and check those same blocks are now editable. (This functionality isn't needed right now, but we're trying to keep it working in the event we need it later in the year when the legacy collection is deprecated)

note: I'll be attempting to resolve the inconsistent situation around the `include_in_legacy` property in https://github.com/mozilla/addons-server/issues/14222

**Comment by AlexandraMoga** [comment]
I've verified this on stage and have the following results:

with `blocklist_legacy_submit` OFF:
- blocks that originated in kinto and have been imported in AMO can't be edited or deleted (by using either the Delete button from the block detail page or the Multiblock delete option)
- blocks that were added in AMO and had the include in legacy checkbox selected while the switch was on (I was able to find one after all) can't be edited or deleted

with `blocklist_legacy_submit` ON:
- for both cases mentioned above, editing and deleting is possible

This seems to be the expected behavior, so I'm marking the issue as verified fixed on stage.
