### ISSUE TITLE
Enable git-extraction CRON task in -prod

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14185]
We want to enable the git extraction CRON task -prod (and therefore -stage too). The name of the waffle switch is: `enable-git-extraction-cron`.

**Comment by ioanarusiczki** [comment]
@willdurand 
I should be testing on stage what I've been doing on dev - some versions on the same add-on and multiple add-on uploads perhaps.
Is it alright for the admin queue to be incomplete for now?

**Comment by ioanarusiczki** [comment]
@willdurand I tested on AMO stage with FF76(Win10):

**The file extractions**

- the queue is empty meaning all extractions were made successfully. I can confirm that because I checked the code manager for each version/addon.

  Old versions which have not been extracted before (from 2015-2018) still cannot be viewed but the     new versions uploaded by me yesterday and today are displayed.
  2 examples:
https://reviewers.addons.allizom.org/en-US/reviewers/review/tabliss
https://reviewers.addons.allizom.org/en-US/reviewers/review/ublock-origin

- the extraction is not affected if I delete the entry from the admin queue.

**What I've noticed about the admin queue:**

- static themes are also extracted - entries show up in the admin queue.
- the green flag for a successful extraction is random. Most of the time if I refresh the page after a couple of minutes when I've noticed the files are loading in codemanager if I refresh the admin queue the entries will simply disappear. Until then "In progress" stays with a grey question mark (the initial status).
- I think entries should show at least the version (number) that is being extracted when clicking the detail of the "ID". 
- when deleting an entry the user lands on the general amo admin page /en-US/admin/models/ instead of the git queue. I will file a followup. 

- it occurred randomly and so far I cannot figure out how to reproduce ( I noticed this behavior 3 times): I think 2 queue entries were generated for the same version. The final result however is that extraction was successful.

  I'll give an example:
  Version 3.2.3 on https://reviewers.addons.allizom.org/en-US/reviewers/review/release-dictionary3
  Version 4.0 on https://reviewers.addons.allizom.org/en-US/reviewers/review/%E6%9D%B1%E4%BA%AC%E3%81%A8%E5%BA%83%E5%B3%B6%E3%81%AE%E5%8E%9F%E7%88%86%E8%A8%98%E5%BF%B5%E7%A2%91testingkanji


  Admin queue: 

![entries doubled](https://user-images.githubusercontent.com/33448286/81277691-6fc8a480-905d-11ea-9391-c9a7bef85b1f.png)

**Comment by willdurand** [comment]
>     * static themes are also extracted - entries show up in the admin queue.

I did not change that so I think that was the case before.

>     * the green flag for a successful extraction is random. Most of the time if I refresh the page after a couple of minutes when I've noticed the files are loading in codemanager if I refresh the admin queue the entries will simply disappear. Until then "In progress" stays with a grey question mark (the initial status).

It's not random but we should not see it frequently unless (1) extraction takes a lot of time and we're lucky to look at this page at the same time or (2) there was an error and the add-on is stuck. Otherwise, extraction happens too fast and at the end of the git extraction, we delete these records.

> I think entries should show at least the version (number) that is being extracted when clicking the detail of the "ID".

It's tricky because now we extract an add-on and not a specific version. Extracting a single version that has just been submitted is therefore a special case.

> when deleting an entry the user lands on the general amo admin page /en-US/admin/models/ instead of the git queue. I will file a followup.

Ah yes, no one should really delete such entries but we can definitely have an issue filed for that. I guess we should return to the list view.

> it occurred randomly and so far I cannot figure out how to reproduce ( I noticed this behavior 3 times): I think 2 queue entries were generated for the same version. The final result however is that extraction was successful.

Same version? That's possible, indeed. We git-extract before and after signing a version so it is possible, but the CRON task does not really care and it will only extract a version once. I think we could still file an issue to stop the git-extraction after signing. I don't think that will be required anymore.

**Comment by ioanarusiczki** [comment]
> I think we could still file an issue to stop the git-extraction after signing. I don't think that will be required anymore.

I could file that too but wouldn't that affect the information on files about `sha256` ? (because this is available in codemanager too right now.)

**Comment by ioanarusiczki** [comment]
@willdurand Maybe static themes could be removed form entries ? They are auto-removed after extraction yet there is no codemanager for themes.

I can mark the issue verified on stage with FF76(Win10).

**Comment by willdurand** [comment]
> I could file that too but wouldn't that affect the information on files about `sha256` ? (because this is available in codemanager too right now.)

That's a good question. We'll discuss this in the new issue :p (I don't think we need to git-extract the files twice anyway)

**Comment by willdurand** [comment]
> @willdurand Maybe static themes could be removed form entries ? They are auto-removed after extraction yet there is no codemanager for themes.

@diox so I guess we git-extract static themes in -prod?

**Comment by diox** [comment]
Well currently we extract *everything*, I think.
