### ISSUE TITLE
Allow bulk delete in git entry admin

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14244]
We might have to delete more than one entry at a time and it is cumbersome to go and delete each entry individually. Let's add a bulk delete action to the admin list.

**Comment by ioanarusiczki** [comment]
@willdurand  Because dev is having deploys and it causes errors too often I cannot rely on the results so I tested this on AMO stage. The bulk deletion can be done, technically it works.

There might be a problem for the extraction which could be caused by deleting entries as soon as the upload of a version is done. I filed it here: https://github.com/mozilla/addons-server/issues/14265
