### ISSUE TITLE
Addtion of pre-commit hooks

### ISSUE THREAD

**Issue by shubhank-saxena** [mozilla/addons-server#14249]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
Integrate pre-commit hooks having standard python lint tools like flake8, isort, black, pep8auto.

### What did you expect to happen?
This will help us to keep a standard code style and compliance with best python practices.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://pre-commit.com/

**Comment by RachitG001** [comment]
@eviljeff Can i pick this up?

**Comment by eviljeff** [comment]
> @eviljeff Can i pick this up?

sure.  We currently use prettifier for JS code but using Black is still in progress (#8617) so it'd be running `make format` (to autoformat JS) then `make lint` (to check, but not autoformat, python code with flake8)

**Comment by dbxnr** [comment]
@RachitG001 are you still working on this? If not, I'd like to take it on

**Comment by eviljeff** [comment]
@dbxnr I think you can go ahead

**Comment by eviljeff** [comment]
@dbxnr has created a patch (#16664) that will add config for pre-commit.  

We're not really sure about how helpful it actually will be though for the people who should benefit - the target users of this would be occasional or novice, non-Mozilla contributors, (if you're a regular contributor you would likely have already created your own .git precommit hook, or otherwise have your workflow optimized however you prefer it).  

But, having to install the pre-commit package creates its own setup and dependencies (which on Windows can be non-trivial) in addition to the pretty simple requirements we currently have for addons-server (we currently only require git and Docker to be installed).  And if we make it clear that using pre-commit is optional, then it's likely that most of the first time users - who would benefit most from auto-formatting and linting before the CI runs on github - would skip installing it anyway.

**Comment by eviljeff** [comment]
Fwiw, on addons-frontend we use a tool call `husky`, which runs on nodejs instead.  Using _that_ would mean only one tool would be needed across the AMO stack, but carries it's own setup burden if just for addons-server (you'd have to setup nodejs - something required for addons-frontend development - but not required right now for addons-server development)

**Comment by eviljeff** [comment]
After further discussion internally, we think it will be difficult to have a proscribed solution that wouldn't also force the user to install additional dependencies (e.g. python or nodejs runtime) at the OS level, which presents it's own barriers to new contributions. Having further install documentation  would be good though - which could describe how one could setup pre-commit (or similar).
