### ISSUE TITLE
Do not redirect to unlisted queue after submitting an unlisted add-on review

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14267]
Loading the unlisted add-on review queue is very slow and optimizing it isn't a priority (and it shouldn't be for now). However, we redirect to that queue every time a review is submitted for an unlisted add-on, which unlisted reviewers and admins have to do sometimes.

Let's reload the unlisted add-on review page after the review has been submitted instead.

**Comment by ioanarusiczki** [comment]
@wagnerand I verified this issue in the Unlisted Review Queue from rev tools on AMO dev with FF76(Win10):
- once an action is done such as Confirm Multiple Versions,  Reviewer reply, Request super-review or Comment is made the user will not return to the general queue, the review-unlisted page will be displayed.
- `Block Multiple Versions` (which has the disabling role) has a different path meaning after I click the `save` the version will be rejected but then an admin blocklist page is displayed. With `Reviewers: Unlisted` permission I am redirected to a 403 page (because this type of user doesn't have admin rights to blocklist) but if I return and check the page the version/versions are rejected.

2 things I've noticed and I'd like to ask about:
- after an action such as rejecting or confirming is taken the add-ons are still available/displayed in the list of add-ons (in the Unlisted Review queue). To give an example, there is no other version to confirm or reject for:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/1b943951d70a4af9a747

yet, the id 619746 is still available in the [list](https://reviewers.addons-dev.allizom.org/en-US/reviewers/unlisted_queue/all) 

- a reviewer from the `Reviewers: Unlisted` group can only block (disable) or confirm versions. `Reviewer reply`, `Request super-review` or `Comment` buttons are not available on the unlisted review page.

**Comment by wagnerand** [comment]
Thank you for testing!

> 2 things I've noticed and I'd like to ask if they're expected:
> 
>     * after an action such as rejecting or confirming is taken the add-ons are still available/displayed in the list of add-ons (in the Unlisted Review queue). To give an example, there is no other version to confirm or reject for:
>       [reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/1b943951d70a4af9a747](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/1b943951d70a4af9a747)
>       yet, the id 619746 is still available in the [list](https://reviewers.addons-dev.allizom.org/en-US/reviewers/unlisted_queue/all)

I don't think we filter the unlisted queue much. Technically, I guess it's not 100% accurate, but there is more to the story here. I don't think it's worth fixing this, the unlisted queue view is of very limited use anyway.

>     * a reviewer from the `Reviewers: Unlisted` group can only block (disable) or confirm versions. `Reviewer reply`, `Request super-review` or `Comment` buttons are not available on the unlisted review page.

That sounds like an issue. Could you file a follow-up for that please? Unlisted reviewers should be able to take those actions as well.

**Comment by ioanarusiczki** [comment]
@wagnerand Thank you for the clarification.
I also filed a followup https://github.com/mozilla/addons-server/issues/14315
This issue is verified on AMO dev with FF76(Win10).
