### ISSUE TITLE
Expose blocked status in code-search

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14316]
For code-search, it's very useful to show the blocked state for each matched version, as well as a filter to exclude them from being shown in the list.

This can greatly reduce the manual triage.

I believe @diox has an idea how to implement that without too much performance impact.

**Comment by diox** [comment]
The idea would be to check blocked status in the task, when a version is a match - and only then. This would have a perf hit on the global search time, but hopefully not that much since we'd be limiting that to versions that match the query.

Then we'd store the info in a boolean on the `ScannerQueryResult` (noting that it was the blocked state *at the time we ran the search*) and add a simple exclusion filter on it.

**Comment by AlexandraMoga** [comment]
[Code search results](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerqueryresult/?matched_rules__id__exact=44) now include a 'Was blocked' column that will show the block status of each version identified by the executed rule. 
There has also been a filter added which can be used to exclude/include results based on the block status.
Add-ons that are fully blocked (version range `0 - *`) will not be returned in code search results, unless the 'Run on disabled addons' option was selected.

![image](https://user-images.githubusercontent.com/31961530/96728140-7a34eb80-13bc-11eb-8c0f-a4215498b182.png)
