### ISSUE TITLE
Allow more actions for unlisted reviewers

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14315]
As a followup for https://github.com/mozilla/addons-server/issues/14267#issuecomment-630162575

1. A reviewer from the `Reviewers: Unlisted` group can only block (disable) or confirm versions. `Reviewer reply`, `Request super-review` or `Comment` buttons are not available on the unlisted review page. 

Expected result:
They should be able to take all actions.

Notes:
This issue is reproducible on AMO dev with FF76(Win10).

**Comment by diox** [comment]
These actions use `is_reviewer()`, which in turn uses `check_addons_reviewer()`, which doesn't check for `ADDONS_REVIEW_UNLISTED`. In the real world, unlisted reviewers would have one of the other permissions this function checks.

**Comment by diox** [comment]
Currently we don't have reviewers that only belong to `Reviewers: Unlisted` group in production so this isn't affecting anyone, so this is low priority.

Changing `is_reviewer()` behavior has a lot of implications, maybe the best solution would be to add a `or` with a different check for unlisted reviewer in the code that defines which actions are available, rather than adding `ADDONS_REVIEW_UNLISTED` to the permissions `check_addons_reviewer()` checks.
