### ISSUE TITLE
L10n: Need clarity on Review tool titles and where they are used

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#14322]
### Describe the problem and steps to reproduce it:
https://pontoon.mozilla.org/it/amo/all-resources/?status=fuzzy%2Cmissing&search=%E2%80%93&string=210028. Here are a few examples
* `Reviewer Tools – Add-ons for Firefox`
* `Reviewer Moderation Log – Add-ons for Firefox`
*  `– Reviewer Tools – Add-ons for Firefox`

### What happened?
Lack clarity on the purpose of the hyphenation. Don't know where they appear and if the translation is correct in the context.

### What did you expect to happen?
1). Are these "title" attributes for the web page?
2). Need to know how  "reviewer" is used.`Reviewer` (singular) means that we are displaying the page of a particular reviewer, as opposed to a generic page for reviewers?
3). Need staging URL to test the reviewer portion of the product.

**Comment by jvillalobos** [comment]
They are page titles, yes, I think introduced in https://github.com/mozilla/addons-server/issues/13510. 

The hyphen is only a separator. The first part of the title specifies what the particular page is for ("Reviewer Moderation Log"), and the second part is the name of the site ("Add-ons for Firefox"). That's how titles are handled in the user-facing front-end, for example in [this page](https://addons.mozilla.org/en-US/firefox/extensions/)("Extensions – Add-ons for Firefox").

In those titles, "Reviewer" is referring to the group of reviewers rather than an individual reviewer. So, for instance, "Reviewer Moderation Log" shows a log of the moderation activity of all reviewers.

**Comment by peiying2** [comment]
> They are page titles, yes, I think introduced in #13510.
> 
> The hyphen is only a separator. The first part of the title specifies what the particular page is for ("Reviewer Moderation Log"), and the second part is the name of the site ("Add-ons for Firefox"). That's how titles are handled in the user-facing front-end, for example in [this page](https://addons.mozilla.org/en-US/firefox/extensions/)("Extensions – Add-ons for Firefox").

Thank you so much for the response. Is this one correct then, `– Reviewer Tools – Add-ons for Firefox`? A hyphen in front of the tool?

**Comment by peiying2** [comment]
@jvillalobos I guess for the reviewer feature to be tested, one has to register to be a reviewer or vetted as such, right? I just attempted to sign in as using my work email address, it doesn't allow me to see it.

**Comment by peiying2** [comment]
Comment from Mat on Slack: `reviewer tools in general need special permissions. we can give those permissions temporarily on our dev instance on a case-by-case basis, but ideally we'd prefer to keep it limited`. 

Thanks!

**Comment by jvillalobos** [comment]
> Thank you so much for the response. Is this one correct then, – Reviewer Tools – Add-ons for Firefox? A hyphen in front of the tool?

I suppose that's used to prepend another page title before it, but I'm not sure about it.
