### ISSUE TITLE
Use SameSite=Lax on frontend auth token cookie

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14376]
While our `sessionid` cookie has SameSite=Lax, currently our `frontend_auth_token` cookie (that is not used directly by the API, but to pass the token to the frontend) doesn't. Let's unify that.

**Comment by diox** [comment]
QA: make sure logging in and out still works (and that you're correctly logged in and out of frontend, devhub & code-manager at the same time).

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev with the following scenarios:
- log in/log out in frontend => user log in/log out state is correctly propagated in devhub, rev tools and code-manager
- log in/log out in devhub=> user log in/log out state is correctly propagated in frontend, rev tools and code-manager
- log in/log out in rev tools=> user log in/log out state is correctly propagated in devhub, frontend and code-manager
- log in/log out in code-manager=> user log in/log out state is correctly propagated in devhub, rev tools and frontend
