### ISSUE TITLE
Use BigQuery in `update_addon_average_daily_users()`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14428]
Update `update_addon_average_daily_users` task to pull the data from BigQuery.

**Comment by willdurand** [comment]
We'll add a waffle switch to enable this feature.

**Comment by willdurand** [comment]
@eviljeff this has landed but it is behind a waffle switch. I'll make some tests in -dev to see how it goes. Note that we won't be able to use the BigQuery stats for `average_daily_users` until we know what to do for https://github.com/mozilla/addons-server/issues/14533

**Comment by eviljeff** [comment]
great, I'll land the fix for #13123 behind the same waffle switch.

**Comment by ioanarusiczki** [comment]
@willdurand Can qa help with testing here?

**Comment by willdurand** [comment]
> @willdurand Can qa help with testing here?

Yes, we'll have to work together because it requires manual steps. I'm off today and tomorrow so can we verify this issue next week or the week after? Thanks

**Comment by ioanarusiczki** [comment]
@willdurand Ok, enjoy!

**Comment by ioanarusiczki** [comment]
@willdurand I see `use-bigquery-for-addon-adu` active on admin dev. 

I verified ADU for https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/beta/usage/?last=30 and  the information in the frontend is displayed.

I'm going to take a look tomorrow to other addons see if Daily Users by Date starts being populated for beta.

**Comment by ioanarusiczki** [comment]
@willdurand I'm not sure what exactly is available so far:

1. I've noticed in the [overview](https://addons-dev.allizom.org/en-US/firefox/addon/view-page-archive-cache/statistics/beta/?last=30) section that Average Daily Users shows a number. Once I click on it it redirects to statistics/beta/usage/?last=30 where for the sample tests such as 

https://addons-dev.allizom.org/en-US/firefox/addon/statistics-sample/statistics/beta/?last=30 and
https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/beta/?last=30 
data is available per day. 

On the other hand there are many other add-ons which show an ADU in the overview but if I go to 
statistics/beta/usage/?last=30 there is no data per day.

https://addons-dev.allizom.org/en-US/firefox/addon/search_by_image/statistics/beta/usage/?last=30
https://addons-dev.allizom.org/en-US/firefox/addon/view-page-archive-cache/statistics/beta/usage/?last=30

2. Looking over some data for this GUID  
`{7e7eda8f-2e5d-4f43-86a9-07c6139e7a08}`. For 6/18/2020 ADU was 96 in the [API](https://addons-dev.allizom.org/api/v4/addons/addon/{7e7eda8f-2e5d-4f43-86a9-07c6139e7a08}/) on dev but the [graph](https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/beta/usage/?last=30) shows 98. If I checked it on prod the [ADU](https://addons.mozilla.org/api/v4/addons/addon/{7e7eda8f-2e5d-4f43-86a9-07c6139e7a08}/) for this GUID is 149. Is it because telemetry is something else and it is not information provided in APIs ?

**Comment by willdurand** [comment]
>     1. I've noticed in the [overview](https://addons-dev.allizom.org/en-US/firefox/addon/view-page-archive-cache/statistics/beta/?last=30) section that Average Daily Users shows a number. Once I click on it it redirects to statistics/beta/usage/?last=30 where for the sample tests such as
> 
> 
> [addons-dev.allizom.org/en-US/firefox/addon/statistics-sample/statistics/beta/?last=30](https://addons-dev.allizom.org/en-US/firefox/addon/statistics-sample/statistics/beta/?last=30) and
> [addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/beta/?last=30](https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/beta/?last=30)
> data is available per day.
> 
> On the other hand there are many other add-ons which show an ADU in the overview but if I go to
> statistics/beta/usage/?last=30 there is no data per day.
> 
> [addons-dev.allizom.org/en-US/firefox/addon/search_by_image/statistics/beta/usage/?last=30](https://addons-dev.allizom.org/en-US/firefox/addon/search_by_image/statistics/beta/usage/?last=30)
> [addons-dev.allizom.org/en-US/firefox/addon/view-page-archive-cache/statistics/beta/usage/?last=30](https://addons-dev.allizom.org/en-US/firefox/addon/view-page-archive-cache/statistics/beta/usage/?last=30)

we only have a few add-ons with "beta" stats data in -dev and -stage so that could be an explanation. The ADU values should be visible in the detail page of each add-on (addons-frontend).



> 1. Looking over some data for this GUID
>        `{7e7eda8f-2e5d-4f43-86a9-07c6139e7a08}`. For 6/18/2020 ADU was 96 in the [API](https://addons-dev.allizom.org/api/v4/addons/addon/%7B7e7eda8f-2e5d-4f43-86a9-07c6139e7a08%7D/) on dev but the [graph](https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/beta/usage/?last=30) shows 98. If I checked it on prod the [ADU](https://addons.mozilla.org/api/v4/addons/addon/%7B7e7eda8f-2e5d-4f43-86a9-07c6139e7a08%7D/) for this GUID is 149. Is it because telemetry is something else and it is not information provided in APIs ?

-prod data is different and that's expected.

For -dev/-stage, we use the sum of the last 13 days so that might explain why it is 96 and not 98?

**Comment by ioanarusiczki** [comment]
@willdurand  
Ok. I thought ADU data will be available for all add-ons once the waffle is active.
An average for the last 13 days explains it.
