### ISSUE TITLE
Implement delayed review rejections

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14454]
To give developers sufficient time to fix their add-ons before their versions are taken down and 
Minimize the time add-on listings are unavailable due to review issues, we want to implement delayed review rejection option as per [PRD](https://docs.google.com/document/d/1rh8rfMviJwEQekz-qoDT487q2mc5KsJiDWY7rDQtmBs/edit#).

Once [the other issues in the project](https://github.com/orgs/mozilla/projects/130) are done: 

- [ ] In the reviewer tools, rejections default to applying after a grace period of ~~7~~ 14 days (the same time interval used previously for info requests).
  - [ ] Like with info requests, the email sent to developers must explain this.
  - [ ] Rejections of multiple versions apply the grace period for all selected versions.
  - [ ] Auto-approval is disabled for the add-on until it gets a manual approval or an admin changes the auto-approval flag.
- [ ] Reviewers also have the option to reject immediately, for cases where it’s considered users are at real risk or there have been repeated rejections with no progress.

**Comment by diox** [comment]
@jvillalobos Previously we had a cronjob that would notify developers about soon to expire info requests, now that pending rejection deadline replaces that, are we keeping that cron, but using it with the new delayed rejections ?

**Comment by jvillalobos** [comment]
Yes, please.

**Comment by diox** [comment]
Note: to support https://github.com/mozilla/addons-server/issues/14814, the comments from the reviewer needs to be attached to the activity log associated with a delayed review rejection. It probably needs to be a separate activity log, too, to be able to distinguish between an immediate and a delayed rejection.

**Comment by AlexandraMoga** [comment]
Since this new feature covered quite a lot of functionality in Reviewer Tools, I've created a list of [test scenarios](https://docs.google.com/spreadsheets/d/13UUZ5AnmzkOs38Wb-jmJpQhzBRYgcYVWlxWy6AFgiyI/edit?usp=sharing) that I found relevant - based on the [PRD](https://docs.google.com/document/d/1rh8rfMviJwEQekz-qoDT487q2mc5KsJiDWY7rDQtmBs/edit#) and the various comments added in the other issues from [this project](https://github.com/orgs/mozilla/projects/130).

The Reject multiple versions action (for listed) includes now two options: 
-  reject versions with a delay (default is 14 days and the period can't be updated by regular reviewers) 
- reject immediately (the option selected by default).

The Information request option is gone, but if there were any add-ons with a pending information request at the time the new delayed rejections feature was enabled, those can still be resolved either by the developer when a new version is submitted, or by an admin reviewer by clearing the Pending Information Request flag. 


Visuals
![image](https://user-images.githubusercontent.com/31961530/88298458-daf35000-cd09-11ea-8519-a125236d31d2.png)
