### ISSUE TITLE
setup cron job(s) to delete account/addon data after a set period

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14494]
see #13896 for the main issue.

This is the implement the steps mentioned in the deletion policy:
> When an AMO account is deleted, all of its associated data is deleted with it. The only exception is when the account is the sole owner of an add-on, in which case:
>
> - All add-on files and their associated metadata will be retained for a total of 7 years, after which they will be permanently deleted.
> - The developer’s email address and IP addresses used to submit their add-ons will be retained for a total of 7 years, after which they will be permanently deleted.

(and other comments relating to the non-immediate deletion of data)

Data retention policy doc: https://docs.google.com/document/d/1E4rFeLhsafcOnesetDbpaXLiCkGjkCsgnZnzbso9Fls/edit#heading=h.91acyaz58wl1

**Comment by eviljeff** [comment]
@jvillalobos the current implementation retains email, fxa_id, and last_login_ip on the UserProfile (along with any addons they own), for **all** users.  last_login_ip is then cleared after 6 months for all users.  

- Do we want to differentiate users with addons, and users without addons?  Or is clearing for all users after 7 years sufficient/desirable?
- does `last_login_ip` still need to be cleared after 6 months, or is that on a 7 year timescale too?
- At the 7 year mark, should we clear email and fxa_id too? 
- what about `notes` (admin notes when deleting accounts)?

**Comment by diox** [comment]
> does `last_login_ip` still need to be cleared after 6 months, or is that on a 7 year timescale too?

FWIW that 6 month period was something we came up with Legal & Trust & Privacy teams. They mentioned in the email thread that we could re-assess if needed, but they should be involved in that discussion if we do.

**Comment by jvillalobos** [comment]
> Do we want to differentiate users with addons, and users without addons?

Yes, the 7 year data retention only applies to users with add-ons. For all other users we should delete the data within 48 hours.

> does last_login_ip still need to be cleared after 6 months, or is that on a 7 year timescale too?

For add-on developers, the same 7 year timescale.

> At the 7 year mark, should we clear email and fxa_id too?

Yes.

> what about notes (admin notes when deleting accounts)?

That should be okay to keep indefinitely, but I don't think it'll be of much use if all other data is cleared. So, whatever's easiest.

> FWIW that 6 month period was something we came up with Legal & Trust & Privacy teams.

The new policy was cleared with those teams, so we should be okay.

**Comment by eviljeff** [comment]
To clear within 48 hours the daily cron job clears accounts deleted at least 24 hours ago if they a) don't have any addons and b) aren't banned; otherwise they are cleared, and any add-ons hard-deleted, after 7 years.

fwiw @jvillalobos I've included banned users in the 7 year timescale.   It's probably unlikely we'd be banning users who _don't_ submit addons, but clearing any user we just banned within 48 hours seemed wrong.

**Comment by eviljeff** [comment]
QA:
testing that the email, fxa_id, and last_login_id are cleared for cleared within 48 hours for users who don't own any add-ons (and aren't banned) is just a matter of deleting them; waiting 48* hours; then going into django admin and looking up those UserProfile ids to see the data is cleared.  Similarly users who _do_ own add-ons, and banned users, shouldn't have their information cleared after 48* hours (and the add-ons should stay, and remain soft-deleted).

Testing the 7 year deletion is going to be more tricky - after deleting some accounts let me know and I'll have to set the modified dates on those accounts to more than 7 years ago.

* the job runs at 6am UTC and clears accounts deleted over 24 hours ago so, for example, if you deleted the account at 2pm Wednesday, then they should be cleared by 7am Friday.  I.e. they'll be cleared sometime between 24 and 48 hours after deletion.

**Comment by AlexandraMoga** [comment]
@eviljeff I've prepared some accounts to test this - they were deleted around 4pm on Wednesday, so they should be picked up when the cron runs on Friday morning. 
These are the accounts that should be >7 years old: 10642062, 10642061, 10642060

**Comment by eviljeff** [comment]
> These are the accounts that should be >7 years old: 10642062, 10642061, 10642060

I changed the modified dates to 2013

**Comment by AlexandraMoga** [comment]
Here are the test results:
- regular users who deleted their accounts over 24h ago: the email, fxa_id and last_login_ip  fields are cleared - [10642055](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10642055/change/)
- regular users that were banned over 24h ago: the email, fxa_id and last_login_ip fields are _not_ cleared - [10642057](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10642057/change/)
- developers who deleted their accounts over 24h ago: the email, fxa_id and last_login_ip fields are _not_ cleared; their (soft-deleted) addons can be viewed by admins - [10642058](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10642058/change/)
- developers who deleted their accounts over 7 years ago: the email, fxa_id and last_login_ip  fields are cleared; their add-ons are hard deleted - [10642060](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10642060/change/)

@eviljeff there is a [Restriction history](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userrestrictionhistory/?user=10642060) section in admin which records restrictions associated with a specific user. For example, we are recording when a developer accepted the Developer agreement and log that in the restriction history (the example I've given is for one of the developer accounts deleted over 7 years ago).  That log includes the user's last_login_ip. This section is not covered by the Data retention policy, but since we are clearing the  last_login_ip after 7 years of inactivity, shouldn't we make sure we clear it from all locations?

**Comment by eviljeff** [comment]
> @eviljeff there is a Restriction history section in admin 

can you file a follow-up?  I'm assuming @jvillalobos intended for that to be cleared as well after 7 years (I didn't know the model existed).
