### ISSUE TITLE
Create admin page to add entries to git extraction queue

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14537]
We need an admin page so we can add add-ons to the git extraction queue, so they work in code-manager.

**Comment by AlexandraMoga** [comment]
@wagnerand I was able to identify the new 'Git extract' button added at the bottom of the admin addon page. 
In order to test this, I've selected a few add-on versions that couldn't be opened in code-manager [1] (they were throwing a 500 error) and versions that were available in code-manager but the META-INF was missing [2] (the original extraction happened before they were signed)

Examples:
[1] - [example 1](https://reviewers.addons.allizom.org/en-US/reviewers/review/opoodcon-sealo-ramana), [example 2](https://reviewers.addons.allizom.org/en-US/reviewers/review/wed22-feb)
[2] - [example 1](https://code.addons.allizom.org/en-US/browse/1004968/versions/2478148/), [example 2](https://code.addons.allizom.org/en-US/browse/1004875/versions/2478134/)

For both set of examples, the 'Git extract' button triggers a new extraction => I can see the add-on being extracted in the [git extraction queue](https://addons-internal.stage.mozaws.net/en-US/admin/models/git/gitextractionentry/). However, the addons in set 1 are still triggering a 500 in code-manager and set 2 will not contain the META-INF file.

Unless my test method is wrong, this doesn't seem to be working as expected.

**Comment by wagnerand** [comment]
@AlexandraMoga Apologies, I missed adding STR for this.

500 would actually be a different error, and it would be interesting to learn where those come from. Usually, code-manager would show a red message bar with a 404 because the version has not been extracted (yet), or when something went wrong during extraction.

Are the entries that were put into the git extraction queue eventually disappearing from that queue?

**Comment by wagnerand** [comment]
As for the examples in [2], I believe that is working as expected. The extraction cron skips versions that are already successfully extracted.

The button just adds the add-on into the git-extraction queue. Everything else is handled by the git-extraction queue and that has not changed in months.

Note that there is also a different action on the add-ons list admin page. You can select one or more add-ons and then use the action from the dropdown above the table.

<img width="521" alt="Screenshot 2020-10-21 at 17 39 50" src="https://user-images.githubusercontent.com/873258/96743569-6f7e5480-13c4-11eb-90f1-2fc5f2ad3092.png">

All selected add-ons should be added to the git-extraction queue.

**Comment by AlexandraMoga** [comment]
> Are the entries that were put into the git extraction queue eventually disappearing from that queue?

@wagnerand yes, the add-ons do disappear from the git extraction queue after a few minutes. 
I'll try to see what happens in case of add-ons that trigger a 404.

**Comment by AlexandraMoga** [comment]
@wagnerand I've verified again, this time with an add-on that hasn't been successfully git extracted (404 returned in code-manager). After re-running the Git extraction from addon admin page, the add-on was successfully extracted and is now available in code-manager - https://code.addons.allizom.org/en-US/browse/1004983/versions/2478173/

The group extraction  from add-ons list admin page is also working. 

This issue is verified fixed on -dev.
