### ISSUE TITLE
Use download stats for updating `addon.average_daily_users` for dictionaries and langpacks

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14609]
We won't have usage stats for langpacks and dictionaries _via_ Telemetry yet so let's update `addon.average_daily_users` with the download stats instead.

**Comment by willdurand** [comment]
@diox we have a waffle switch to either use the BigQuery data or the old way of updating the `average_daily_users` values: https://github.com/mozilla/addons-server/blob/b22a64eab4f1336d4c6aa493fe364fe5041a3558/src/olympia/addons/cron.py#L40-L43

I am thinking about adding logic similar to what we have in `update_addon_download_totals()` (filtering on the addon-on `type` too) and update the `d` array right after. WDYT?

**Comment by willdurand** [comment]
@eviljeff @diox now that I landed the patch for this issue and that I fixed it (twice), it works well but I realize that it might not be needed at all :|

While the `Addon.total_downloads` property isn't exposed by the API, we still compute it in a CRON task (frequently). The value for this property is almost the same as the one we now use for `addon.average_daily_users` (for add-ons that don't have stats in BigQuery). I am wondering if this is actually needed?

Instead, we could expose the `total_downloads` property and use it in addons-frontend. That would mean add-ons without stats in BigQuery would not get their `average_daily_users` updated anymore. Is that a problem? Where do we use this value in addons-server?

**Comment by eviljeff** [comment]
iirc, not exposing total downloads was a deliberate decision.  Why aren't we using weekly downloads?

**Comment by jvillalobos** [comment]
I believe we used total downloads for search engines before, but I could be wrong. If it's easier to use weekly downloads, that's fine too.

**Comment by ioanarusiczki** [comment]
@willdurand I verified on AMO dev the following lang packs and dictionaries:
acholi-ug-language-pack
afrikaans-language-pack
chinese-simplified-zh-cn-la
afrikaans-spell-checker
albanian-dictionary

- in all cases I could see in the overview a number of downloads (which should be the total number of downloads) and ADU which are equal. The reason is [explained](https://github.com/mozilla/addons-server/issues/14609#issuecomment-644916552)

![information](https://user-images.githubusercontent.com/33448286/85008771-14162e80-b166-11ea-929d-0b0c38f5fe2d.png)

- the number I see in [Overview](https://addons-dev.allizom.org/en-US/firefox/addon/chinese-simplified-zh-cn-la/statistics/?last=30) is also shown by the frontend.
