### ISSUE TITLE
don't make waffle checks in monitor_fxa_sqs

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14702]
we run `monitor_fxa_sqs` as a long-running command to monitor the sqs queue for FxA, looking for email changes and deletions.  The deletion monitoring is currently behind a waffle switch.  

Unfortunately django can lose it's database connection during long running commands, meaning the `waffle.switch_is_active` check errors and raises an exception. 

Long term we won't need the switch, but short term we do, so we should move the check to the task where a new database connection is opened each time.

**Comment by AlexandraMoga** [comment]
@eviljeff is QA required for this?

**Comment by eviljeff** [comment]
QA: 
- with the waffle `fxa-account-delete` enabled, delete a FxA account that's logged into AMO and has created content (addon, collection, ratings) and see that the AMO account is deleted too.  The addon should be deleted, the collection and profile inaccessible, and any ratings also removed.
- with the waffle `fxa-account-delete` disabled, repeat, and see that the account on AMO isn't deleted (the content should all still be there)

**Comment by AlexandraMoga** [comment]
Test results for stage (the switch is not working on -dev, most likely because of the FxA dev server configuration):

- `fxa-account-delete` enabled - user deletes account from FxA while being logged into AMO:
  - content created by the user is deleted, including profile details, reviews, collections, add-ons
  - the user is logged out of AMO(*)

- `fxa-account-delete` disabled - user deletes account from FxA while being logged into AMO:
  - there is no impact on the user created content, i.e nothing gets deleted
  - the user is still logged in on AMO

@eviljeff  *in the first scenario, if the user is logged into AMO when the account deletion happens on the FxA side, AMO will throw a 401 when a page is refreshed. The error will persist for as long as the browser session is open. I can file a follow up to track this further.

**Comment by eviljeff** [comment]
> if the user is logged into AMO when the account deletion happens on the FxA side, AMO will throw a 401 when a page is refreshed. The error will persist for as long as the browser session is open. I can file a follow up to track this further.

throwing an error on page refresh doesn't sound good.  Can you log a follow-up (separately for addon-server and addons-frontend if it's happening on devhub _and_ frontend pages please)

**Comment by AlexandraMoga** [comment]
I've filed an issue only for the frontend because the error does not reproduce on devhub. 
I'm also marking this issue as verified fixed on stage.
