### ISSUE TITLE
hard delete addons from *all* users deleted over 7 years old

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14809]
#14494 adds a cron job that deletes the addons of user accounts that were deleted over 7 years ago, but only for user accounts that are being cleared of fxa_id, email, or last_login_ip.  This is fine for new accounts, but we've only started retaining fxa_id and email a few weeks ago, and last_login_ip was previously cleared for all users after 6 months.  We should hard delete the add-ons from _all_ user accounts deleted over 7 years ago.

**Comment by AlexandraMoga** [comment]
@eviljeff I was able to verify this with the users modified in https://github.com/mozilla/addons-server/issues/14494#issuecomment-652907584 but those users did not cover the cases where the user data (email, fxa_id, last_login_ip) was already deleted.

I've found some users with add-ons in various states that would be suitable for testing. Could you set the deletion date for them to over 7 years ago? 

10641799, 10641822, 1064167, 10641831, 10642043

**Comment by eviljeff** [comment]
`1064167` doesn't exist

**Comment by eviljeff** [comment]
> 10641799, 10641822, ~1064167~, 10641831, 10642043

done

**Comment by AlexandraMoga** [comment]
Oops, I missed a `1` at the end. The Id should have been `10641671`. But I think the ones you've already modified should be enough to test this.

**Comment by AlexandraMoga** [comment]
@eviljeff looks like add-ons are hard deleted only if they were soft-deleted in advance. Since add-ons didn't use to be deleted when an account was deleted, we might have the following situations:

1. User [10641799](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10641799/change/) - had a listed Approved [add-on](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/496331/change/?_changelist_filters=authors%3D10641799) after the account was deleted => the add-on is still available
2. User [10641822](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10641822/change/) - had a listed Disabled [add-on](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/498514/change/?_changelist_filters=authors%3D10641822) after the account was deleted => the add-on is still available

The first scenario should not be very common I believe, but there could be cases where the second scenario applies - for example, when users are banned, their add-ons become disabled.

**Comment by eviljeff** [comment]
> The first scenario should not be very common I believe, 

yeah I purposely didn't want to delete approved add-ons that were still associated with a deleted user because something has gone wrong in the process so it's a risk.

> but there could be cases where the second scenario applies - for example, when users are banned, their add-ons become disabled.

Ah, I didn't take disabled addons (from banning) into account.  Can you log a follow-up?
