### ISSUE TITLE
Remove obsolete views/code about expired info requests

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14899]
With delayed review rejections the notion of "Information request" (which is essentially a reviewer reply with a deadline associated to it) will no longer exist. There will be some code to remove:
- The cron that notifies developers about soon to expire info requests (https://github.com/mozilla/addons-server/issues/14814 will implement the same thing for delayed rejections) and the `notified_about_expiring_info_request` field in `AddonReviewerFlags`
- The expired info requests reviewer queue (https://github.com/mozilla/addons-server/issues/14576 will implement a queue for add-ons with versions pending rejection)
- The code to create an info request (will probably be removed in https://github.com/mozilla/addons-server/issues/14454 already)
- The `pending_info_request` field in `AddonReviewerFlags`.

**Comment by diox** [comment]
Reviewer tools & devhub should continue to work as normal, this change should be completely transparent to users.

**Comment by AlexandraMoga** [comment]
I've verified that actions related to former Information requests are no longer present and did a bit of regression around the still available Reviewer replies:

- reviewer replies can still be performed
- developers are receiving emails when a reviewer reply is posted or they can use the version review history on the Manage versions page to communicate with the reviewer 
- the Expired information request queue has been removed from the reviewers dashboard
- the Pending information request button will no longer appear in the Admin actions section
- the Pending information request icon is not displayed next to add-ons that have an unresolved information request 

This issue is verified fixed on -dev.
