### ISSUE TITLE
Roll back trademark restriction for add-on names

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#14945]
We are running into some issues with the restriction we enabled in https://github.com/mozilla/addons-server/issues/14656 and https://github.com/mozilla/addons-linter/issues/2158, so we need to roll them back.

**Comment by willdurand** [comment]
@jvillalobos do we plan on re-enabling this check later? or can we remove everything in a more permanent manner?

**Comment by jvillalobos** [comment]
You can remove it in a more permanent manner. We _might_ implement something like it in the future, but if we do it will be more nuanced, allowing certain things for themes and others for extensions. It's not in the plans, though.

**Comment by jvillalobos** [comment]
@willdurand do we need a separate issue for the linter?

**Comment by willdurand** [comment]
> @willdurand do we need a separate issue for the linter?

Probably but I was going to file one before submitting a patch.

**Comment by ioanarusiczki** [comment]
@willdurand I verified on AMO dev with FF78(Win10) with a regular account (using a gmail e-mail address in my case) and it allowed `for Mozilla` and `for Firefox` in the `Name` field for add-ons or themes.

The only case I still receive the red warning is when I use both trademarks such as `Bubbles for Mozilla Firefox`.  The issue is reproducible at addon submission too. 

No problems encountered when using a mozilla account.

**Comment by willdurand** [comment]
cc @wagnerand and @jvillalobos

**Comment by jvillalobos** [comment]
That should be okay. I believe that's what we did before.

**Comment by willdurand** [comment]
> That should be okay. I believe that's what we did before.

Theoretically, yes.
