### ISSUE TITLE
Make our test results easier to read and more useful

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#1497]
I find our test failures in travis unreadable the way they are set up right now, especially compared to the usual way unittest displays errors. This issue is an attempt to make a list of my problems and hopefully come up with a better py.test configuration.

* Errors and failures not displayed inline : need to wait for the full test to be over to see what went wrong for each failure
![no-inline](https://cloud.githubusercontent.com/assets/187006/12515046/94645c36-c126-11e5-99d4-ffb0b2f1917d.png)
* Header in each traceback difficult to read : 5 lines are shown for each error with a lot of information that is repeated or that we don't need. In addition, it's difficult from this header to find the line you need to launch to repeat this particular test locally - the filename or the full module path of the test isn't present.
![cant-easily-launch-this-failed-test](https://cloud.githubusercontent.com/assets/187006/12515131/17d1ccc0-c127-11e5-81d4-dd94bf118965.png)
* Super long and confusing tracebacks with a lot of information : I don't even know where to start looking.
![super-long-traceback](https://cloud.githubusercontent.com/assets/187006/12515305/fd795900-c127-11e5-887a-a0e65dac23f7.png)
![super-long-traceback2](https://cloud.githubusercontent.com/assets/187006/12515306/fd7d965a-c127-11e5-8561-6a05efe9bd88.png)

**Comment by magopian** [comment]
Regarding your first bullet point, the fix is simple I think: we can use `pytest-instafail` (see #1545).

For the two following ones, I'm a bit surprised: there's a lot of information, but it all seems very useful to me: usually you have the following pieces of information:

1/ the header which has the test case name and test name, some information about the params passed to the test function, the code of the failing test, and the "pointer" to the failing line with the failure reason if it failed there
2/ the proper traceback
3/ possibly some "drill down" in the code to pin-point the exact place where the error occured, with the exact line and exact exception
4/ when there's captured output (logs, prints...), you also see them

This output is sometimes "messed up" a bit by our use of `mock` (as we see in the last screenshot). It outputs the (often) useless mock code.

I understand all this can be a bit bewildering, but once you're used to it, it often gives you all the information you need, without having to go back to run the test, drop a "pdb" in there to inspect or drill-down...

I've also added the `--show-locals` parameter so we have the value of the local variables everywhere, even more convenient!

If you're a vim user, make sure to check https://github.com/alfredodeza/pytest.vim

**Comment by diox** [comment]
The header is useless to me because I don't know how to make use of that information to repeat that particular test locally. With nose/unittest I can directly copy/paste the header as an argument to the test runner.

Also, if you look at the smallest of my screenshots: The 3rd line is the only one with useful information: the first line is entirely repeated in the 3rd one, 2nd one is useless (python version ?! path to python binary ?!), and the 4th one contains the test method name, which is also repeated from the 3rd line.

**Comment by magopian** [comment]
So this was auto-closed when merging #1545, but it's definitely not "fixed", in the way that the amount of useless information hasn't been reduced. I'm not too sure what we should do about that, we _could_ implement a custom test reporter I guess, just not sure we want to :)

**Comment by diox** [comment]
Re-opening :)

The problem with instafail is that now, failures are *only* displayed inline, so you have to dig for them once the build is over. Is that something we can tweak ? unittest used to display it twice (once inline, once at the bottom), which helps.

**Comment by diox** [comment]
@EnTeQuAk fixed this while tweaking travis.
