### ISSUE TITLE
Enable stats for all add-on types we currently support

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14982]
Once https://bugzilla.mozilla.org/show_bug.cgi?id=1653499 is fixed, we'll have data for all add-ons in BigQuery, which would allow us to enable the stats feature for all add-ons and not just web-extensions and themes.

**Comment by willdurand** [comment]
For QA: I am still working on getting langpack data in -dev/-stage. For now, we'll have to update the GUID of an existing langpack (and/or dict) with [one of those](https://github.com/mozilla/bigquery-etl/blob/c8d08ace85cba1b2fad445daa6a67ec74bc3a57f/sql/amo_dev/amo_stats_dau_v2/query.sql#L14-L24)

**Comment by ioanarusiczki** [comment]
@willdurand test results:
- I used an id from the [samples above](https://github.com/mozilla/bigquery-etl/blob/c8d08ace85cba1b2fad445daa6a67ec74bc3a57f/sql/amo_dev/amo_stats_dau_v2/query.sql#L14-L24) on dev for a [lang pack](https://addons-dev.allizom.org/en-US/firefox/addon/lang-pack-with-statistics/) and a [dictionary ](https://addons-dev.allizom.org/en-US/firefox/addon/release-dictionary-with-stats/). In this case I can see data including the average ADU which is now displayed on the frontend too instead of the "Downloads".

- with guids from prod for lang packs I checked these:
https://addons-dev.allizom.org/en-US/firefox/addon/asturianu-language-pack/statistics/?last=30
https://addons-dev.allizom.org/en-US/firefox/addon/czech-cz-language-pack/statistics/?last=30

They show data except that the ADU (the blue link) is 0, which is also shown as "no users" on the frontend. I don't know why.

- with guids from prod for dictionaries I did not find data though. I looked for stats into the following:
https://addons-dev.allizom.org/en-US/firefox/addon/afrikaans-spell-checker/
https://addons-dev.allizom.org/en-US/firefox/addon/bulgarian-dictionary/

**Comment by willdurand** [comment]
> with guids from prod for dictionaries I did not find data though. I looked for stats into the following:

Oh right, we don't have data for dictionaries.

**Comment by ioanarusiczki** [comment]
@willdurand Yes. Are the lang packs with guids from prod alright with that ADU 0?

**Comment by willdurand** [comment]
> @willdurand Yes. Are the lang packs with guids from prod alright with that ADU 0?

mm, not sure. Let's see when the last cron task ran.

**Comment by willdurand** [comment]
@ioanarusiczki I ran the cron task manually. It should be better now

**Comment by ioanarusiczki** [comment]
@willdurand Yes, looks good now. It's been updated.
