### ISSUE TITLE
Add-on validation on dev sometimes never completes

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1500]
Sometimes when you submit an add-on to dev, it never completes validation. It just shows a progress bar. This is because the celery / rabbitmq cluster has issues. Jason has a workaround for fixing the issue when it arises but this bug is to put a permanent solution in place. This only concerns the dev environment.

**Comment by kumar303** [comment]
jason on IRC says: "I need to change around the rabbitmq architecture and move it into federated mode"

Also: https://bugzilla.mozilla.org/show_bug.cgi?id=1241937

**Comment by jasonthomas** [comment]
Last week I set up -dev and stage rabbitmq clusters to use 'autoheal' partition tolerance to see if that would help with cluster partitions. Looks good so far but I am not convinced that it will help this actual issue.

https://github.com/mozilla/addons-server/pull/1702 should help -dev and stage since we receive much less traffic from web instances to rabbitmq causing connections to be idle for too long.

It just landed on stage so I will keep my ear to the ground to make sure if it is actually fixed.
