### ISSUE TITLE
Use BigQuery for download stats (behind a Flag)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15030]
Once we have a way to pull data, let's display it. We'll use a waffle flag to determine whether to show new data (from BigQuery) or legacy data (download count). This issue is about using BigQuery for the existing download stats only.

**Comment by willdurand** [comment]
I think in -dev/-stage, we'd likely have no data when flag is disabled and some data from BQ when flag is active.

**Comment by ioanarusiczki** [comment]
@willdurand On dev:
- the admin has access to data as before without being added as a user for `bigquery-download-stats`.
- I added then removed a regular user that has an uploaded [dictionary](https://addons-dev.allizom.org/en-US/developers/addon/release-dictionary-with-stats/edit) with BigQuery data but I don't see changes, the same data is available in both cases. 
Perhaps I'm doing something wrong but I think the waffle is enabled so I did not change anything else except for the user.
- a single user can be added or removed from `bigquery-download-stats`. Can't tell what's expected.

**Comment by willdurand** [comment]
> a single user can be added or removed from `bigquery-download-stats`. Can't tell what's expected.

mm, no you can have more than one I think. I just added myself.


> the admin has access to data as before without being added as a user for `bigquery-download-stats`.

Yeah, the pages remain the same. Only the data is different and that's depending on the waffle flag.

Here is an add-on with download data: https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/statistics/downloads/?last=30. Last few days should be 0 because we didn't automate the import of new data in the BigQuery table.

> I added then removed a regular user that has an uploaded dictionary with BigQuery data but I don't see changes, the same data is available in both cases.

Really? Did you try to hard refresh?

**Comment by ioanarusiczki** [comment]
@willdurand 
 Something is not working on my default profile but I tested on a new profile and I did not have problems, no need to hard refresh. 
No problems with adding more users either, for other admin models each user has a new field where it can be added but in this case multiple users can be added using the same field, separated by `,`  (so I got confused)

1. With flag disabled and an admin account - I see the data displayed for all the add-ons shown in the [search results](https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&sort=users). Indeed, the downloads are `0` since 21th of July. 
2. With flag enabled and the admin added into the `users` group the data from 1. + the new download categories from https://github.com/mozilla/addons-server/issues/15012 are displayed.
3. With the regular account, it's the same as described above for an admin, except that this type of user can only access personal stats.

I think it should be the expected result. In case something is not right, let me know.
