### ISSUE TITLE
Don't send account deletion notification for users without a display_name or other content

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#15035]
We're getting lots of replies to the email introduced in https://github.com/mozilla/addons-server/issues/14512, where we notify users if their account was deleted. Most of them are very new users and are deleting the account right after it was created. They just seem confused about the email.

To mitigate this, I think we should skip sending this email when the user isn't losing anything by deleting the account. So it would be for accounts that meet all of these conditions:

- no `display_name` set
- no add-ons
- no reviews/ratings
- no collections

All other profile metadata can be ignored.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on stage.

Email is not sent:
- there is no user profile content at all (account created and deleted immediately)
- there is some user profile content (i.e. Location, Occupation etc) but _no_ display name

Email is sent:
- user has set a display_name
- user has collections
- user has posted reviews/ratings
- user has add-ons

The same rules apply when accounts are deleted directly from FxA.
