### ISSUE TITLE
Rename `deliver_hotness` cron task to `update_addon_hotness`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15046]
This would make add-on cron tasks a bit more consistent.

**Comment by bhushan-borole** [comment]
Hello @willdurand.
I would like to work on this issue.
It would be helpful, if you give me a little more insight on this issue.

**Comment by willdurand** [comment]
@bhushan-borole sorry, @piotrzarycki already submitted a PR.

**Comment by bhushan-borole** [comment]
Oh okay, thank you.

**Comment by ioanarusiczki** [comment]
@willdurand Let me know when you can run the task.

**Comment by willdurand** [comment]
> @willdurand Let me know when you can run the task.

task has been run manually

**Comment by ioanarusiczki** [comment]
@willdurand For https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&sort=hotness I checked that the list of add-ons has the same order on the first page. 

I've noticed that refreshing the page changes the order in the add-on list, but that is also reproducible on stage and for sort=users parameter too. Probably because of the lack of data on the testing servers.

I'm going to mark it verified on dev - FF78(Win10).
