### ISSUE TITLE
Use `weekly_downloads` instead of `total_downloads` when waffle flag is enabled

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15055]
When the `bigquery-download-stats` _flag_ is active, users should see the number of weekly downloads in the stats overview.

For admins and reviewers, weekly downloads is now the default and only download count in the django admin and reviewer tools. This isn't controlled by the waffle flag because we do not want to use `total_downloads` anymore and we are going to deprecate this field.

**Comment by ioanarusiczki** [comment]
@willdurand 

On dev:
- the rev tool pages have "Weekly Downloads" instead of "Downloads" 
- total downloads is no longer displayed in admin tools - `models/addons/addon/619864/change/`
- stats overview shows downloads such as here https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/statistics/?last=365

If there's anything else I should check here, let me know.

**Comment by willdurand** [comment]
we're good I think
