### ISSUE TITLE
Add 'Build #' prefix to Fenix versions

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15070]
Usage stats for Fenix have build IDs instead of more user friendly **app versions**. It's not clear whether we can rely on a more meaningful version string so let's make it clear that those `202023343` strings are build IDs while we figure out how to retrieve more user-friendly version strings.

We're not going to add this prefix in the exported data.

For QA: I don't think you'll be able to verify this issue because of the lack of Fenix data in -dev/-stage. Firefox Desktop data shouldn't be affected.

**Comment by ioanarusiczki** [comment]
@willdurand 
- I actually found an add-on on dev:
https://addons-dev.allizom.org/en-US/firefox/addon/firefox-color/statistics/usage/applications/?last=90
It's "Android Build #2015752521" displayed instead of  "Android 2015752521"

- other data such as usage by date doesn't seem to be affected.  I took a look at dev versus stage. 

Verified on AMO dev - FF78(Win10).

**Comment by willdurand** [comment]
>     * I actually found an add-on on dev:
>       [addons-dev.allizom.org/en-US/firefox/addon/firefox-color/statistics/usage/applications/?last=90](https://addons-dev.allizom.org/en-US/firefox/addon/firefox-color/statistics/usage/applications/?last=90)
>       It's "Android Build #2015752521" displayed instead of  "Android 2015752521"

That's unexpected but good for QA :p

**Comment by ioanarusiczki** [comment]
@willdurand Yes, a nice surprise there :)
