### ISSUE TITLE
FAILED src/olympia/lib/es/tests/test_commands.py::TestIndexCommand::test_reindexation_with_wipe

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15103]
See: https://travis-ci.org/github/mozilla/addons-server/jobs/712851866

**Comment by diox** [comment]
See discussion in https://github.com/mozilla/addons-server/issues/14467#issuecomment-644109610

**Comment by diox** [comment]
(Didn't mean to close, let's keep both separate, but the discussion in the other issue is relevant)

**Comment by diox** [comment]
As mentioned in https://github.com/mozilla/addons-server/issues/14467#issuecomment-644109610 this one is a bit different from the other intermittent failure: we're simply trying to refresh the index (which should have been created at the beginning of the test) and it isn't found. This is especially weird since it happens after we've created an add-on, so not only should the index exist at this point, but it should contain something.

**Comment by diox** [comment]
Even weirder: in the few cases I've looked at, we actually fail on the `self._test_reindexation(wipe=True)` call, complaining about the index not being there, but that's *after* we've already ran a first `refresh()` and `check_results()`. So the index was definitely there a second ago...
