### ISSUE TITLE
Use a different queue for `extract_optional_permissions` tasks and maybe lower the rate limit

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15117]
Any task that touches EFS is expensive and we're going to run this `extract_optional_permissions` task on [almost 2M files](https://sql.telemetry.mozilla.org/queries/73458/source) so let's make sure that it's not going to block other tasks and/or slow/take down AMO.

**Comment by bobsilverberg** [comment]
Which queue should we use? I take it the rate limit is set on the `@task()` decorator? What should the rate limit be sent to?

**Comment by diox** [comment]
Not sure if this could be done in time for next week, but in an ideal world we'd have a completely separate queue with its own workers for one-off tasks. Those workers would be spawn manually by ops before running the command triggering the tasks, and shut down after it's done. We'd just have to adjust the routing on our side.

**Comment by willdurand** [comment]
> I take it the rate limit is set on the `@task()` decorator?

Yes, something like this:

```
@task(rate_limit='10/m')
```

> What should the rate limit be sent to?
> Which queue should we use?

Good questions.

> we'd have a completely separate queue with its own workers for one-off tasks. Those workers would be spawn manually by ops before running the command triggering the tasks, and shut down after it's done. We'd just have to adjust the routing on our side.

cc @bqbn

**Comment by bqbn** [comment]
Why the workers need to be spawned manually? From ops' perspective, we prefer not having to do that manually. Instead, we're OK running a worker that just listens to the said queue, and processing tasks as needed.

https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/olympia/manifests/celery.pp#L32-L66 is how we set up the celery workers. In order for this queue to not consume too many CPU cycles, we'd assign just 1 or 2 workers to it.

(Let us know what the queue name is so that we can update the puppet manifest file accordingly.)

**Comment by diox** [comment]
> Why the workers need to be spawned manually? From ops' perspective, we prefer not having to do that manually. Instead, we're OK running a worker that just listens to the said queue, and processing tasks as needed.

Just whatever is best for you from a cost perspective. If you're ok with spawning some workers that would sit mostly idle, that's fine for us (not sure how much CPU that consumes)

**Comment by bobsilverberg** [comment]
For the queue name, I suggest `adhoc`.

**Comment by willdurand** [comment]
So I guess if we can have a worker for the next push, we could introduce a new `adhoc` queue and use it for the `extract_optional_permissions` task. We should probably still rate limit the task because of EFS, but we can probably be more generous.

**Comment by bqbn** [comment]
Also, it is important to remember that the `adhoc` tasks should avoid adding tasks to other queues or it defeats the purpose of having this special queue. ;)

(I seem to remember some cron tasks would add tasks to the priority queue for instance.)

**Comment by diox** [comment]
Yeah, one thing we need to be careful about for instance is indexing, that happens after any modification of an add-on. Specifically in this case though, it'd be fine to trigger new tasks on a different queue, since it's unlikely to happen *that much*: that is, if we spawn 20000 tasks to update optional permissions, in the end it's going to result in like 100 tasks to update the index or something, so it's fine.

**Comment by bobsilverberg** [comment]
It looks like we now have an `adhoc` queue, so I suppose the changes needed now are:
1. Specify that this task use the `adhoc` queue.
2. Add some rate limiting to the task.

Question: what rate limiting should we put in place?

**Comment by bobsilverberg** [comment]
@bqbn Mat suggested we might not need much (or any) rate limiting for this task as it will be using this new adhoc worker. Do you agree? What sort of limiting, if any, do you think we need?

**Comment by AlexandraMoga** [comment]
@bobsilverberg let me know if you need any QA for this.
Thanks.

**Comment by bobsilverberg** [comment]
Oops, sorry @AlexandraMoga, qa: not needed.
