### ISSUE TITLE
restrict developers from deleting current versions when approved for promotion

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15121]
We currently prevent a developer from deleting the current version of a recommended add-on if by deleting it the addon becomes not recommended (i.e. the previous version isn't approved for recommendation).  I'm assuming we need to generalise this to other promoted add-ons..

@jvillalobos which other classes of promoted add-on, if any, should have the same restriction applied?

**Comment by jvillalobos** [comment]
It should apply to the ones that require a review to be badged: Line, and both Verified tiers.

**Comment by AlexandraMoga** [comment]
The disable/delete current version restriction applies to promoted add-ons belonging to the Recommended, Verified - Tier 1, Verified - Tier 2 or Line promoted groups, as follows:
- current version can't be disabled/deleted if the next available listed version doesn't belong to the same promotion group or is no longer promoted
- current version can be disabled/deleted if the next available listed version also belongs to the same promotion group

If the add-on promotion group changes between versions, for example from Verified - Tier 2 to Verified - Tier 1, the restriction also applies. More exactly, if the current version is Verified - Tier 1 and the next available version is Verified - Tier 2, developers won't be able to disable/delete the current version (@eviljeff I believe this expected).

The restriction does not apply to add-ons from the Strategic or Spotlight groups.

In addition to the restriction added, the message displayed to users needs to be updated as well. Currently, this is the message displayed for all the promoted groups:
`The latest approved version of this Recommended extension cannot be deleted or disabled because the previous version was not approved for recommendation. Please contact AMO Admins if you need help with this. `   

I'll file a follow up issue to cover this aspect.

**Comment by eviljeff** [comment]
@AlexandraMoga I will (aim to) address all the devhub messaging in #15196
