### ISSUE TITLE
Remove previous featured hero images

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#15176]
Supports  #14471

After #14473 lands to have the uploaded primary hero images associated with the enabled add-ons, remove the hero images that were previously utilized.

**Comment by ioanarusiczki** [comment]
@xlisachan I don't see anything changed since https://github.com/mozilla/addons-server/issues/14473 landed: 
- as an admin I could add images with `admin/models/discovery/primaryheroimageupload/` and attach them to a primary hero addon which can be found in the promoted addon model. 
- there's only one Image section displayed in the promotedaddon model.

**Comment by eviljeff** [comment]
@ioanarusiczki that's expected - the changes are clean-up in the codebase
