### ISSUE TITLE
Add DevHub and API support for URL to source code repository

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#15174]
We want to add a new URL field to add-ons where the developer can set the source code repository for it. 

The URL doesn't need to be shown in the initial submission flow, but can be edited in the DevHub, in the "Additional Details" section, below the Homepage URL. This field doesn't need to be localized. It should have the same validation as other URL fields.

We also need to expose this URL through the API so it can be shown on add-on listing pages.

**Comment by jvillalobos** [comment]
Yes, feel free to take it. Note that we use `contrib: welcome` for issues that are harder than `contrib: good first bug`, so it's more advisable to start with the latter (we don't have any [good first bugs open right now in this repo](https://github.com/mozilla/addons-server/labels/contrib%3A%20good%20first%20bug), though).

@eviljeff might be able to help if you have questions.

**Comment by 532910** [comment]
I believe bots should not close issues.

**Comment by eviljeff** [comment]
Bots are only following instructions from their non-bot controllers.  If you are willing and able (i.e. experienced in django) to take on this issue then please go ahead. Otherwise, it _is_ stale -regardless of the label and open/close state- and isn't going to be worked on unless something changes.
