### ISSUE TITLE
Store hash of add-on GUIDs in the database

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15189]
For the download stats, we'll be using hashed add-on GUIDs as identifiers. While we could compute this value on the fly in BQ queries, we need the hashes in the CRON job that updates the `weekly_downloads` values. Therefore, let's add the hash of each add-on GUID, likely in the `AddonGUID` model.

**Comment by willdurand** [comment]
For QA, the issue is related to the "AddonGUID"/"ReusedGUID" feature. Things should work as before when creating a new add-on or updating the GUID if that is possible.

**Comment by ioanarusiczki** [comment]
@willdurand 
- Updating a GUID is no longer possible because of https://github.com/mozilla/addons-server/issues/14700
- The only way is to submit an addon with a guid that uses BQ data. 
- Right now all guids from the [list ](https://github.com/mozilla/bigquery-etl/blob/3cefa96e15cebbded340633bed240db36bb8cff5/sql/amo_dev/amo_stats_dau_v2/query.sql) have been used on AMO dev and AMO Stage.

**Comment by willdurand** [comment]
@ioanarusiczki I think you can delete an add-on and re-submit a new one with the same GUID

**Comment by ioanarusiczki** [comment]
@willdurand And to be the owner of the addon too (which I keep forgetting) 
It worked for me. I deleted `@testpilot-containers` and submitted again an addon and it also loaded stats data. 

https://addons-dev.allizom.org/en-US/firefox/addon/statistics-reloaded/statistics/?last=30

Verified on dev with FF80(win10).
