### ISSUE TITLE
Include deleted add-ons when calculating `average_daily_users`

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15220]
We want to include deleted add-ons when calculating `average_daily_users` so we have usage statistics for deleted add-ons that might still be used or distributed outside of AMO.

**Comment by AlexandraMoga** [comment]
@wagnerand I wonder if the following approach would verify that this is working on -dev:

- identify an add-on with stats on -dev (we have just a few) and make a note of the current `average_daily_users`
- delete the add-on
- check the next day if the `average_daily_users` for this add-on has changed (for deleted add-ons, I should still be able to verify the new value in reviewer tools or in the add-on detail API)

I'm a bit skeptical about this approach because we do not collect usage data on -dev, so I'm not sure how reliable the results will be.

**Comment by wagnerand** [comment]
@AlexandraMoga I think the average is calculated over several days, so it might take a bit until you'd see it on AMO.
I am also not sure if those STRs work. If the number doesn't change, you wouldn't know whether it's because the actual numbers of users didn't change, the entry wasn't updated or something went wrong.

@eviljeff also let me know that -dev uses a different statistics dataset, so we can't just take a GUID from prod and test it on -dev.

**Comment by AlexandraMoga** [comment]
If that is the case, I guess we won't be able to verify this before it goes to production. I can still try my STR by deleting an add-on with stats from -dev and then monitoring the  `average_daily_users` over several days just to see if I can get any relevant results.
