### ISSUE TITLE
New account cannot be deleted after changing its password from Firefox Accounts page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1523]
Steps to reproduce:
1. Create a new account
2. Register to AMO-dev using that account  https://addons-dev.allizom.org/en-US/firefox/users/register
3. Go to "Account Settings" and click "Manage Firefox Account... " link
4. Change the password
5. Go back to "Account Settings" and click the "Delete Account" red link

Expected results:
User is prompted to confirm account deletion by entering account password (the new password) and checking the "I understand this step cannot be undone" option. The account is deleted.

Actual results:
The message "Wrong password entered!" is displayed. The account cannot be deleted.

Notes/Issues:
Verified on FF43(Win 7). Issue is reproducing on AMO-dev.
Screencast for this issue: http://screencast.com/t/hwfsgS4UVN

**Comment by mstriemer** [comment]
I don't think steps 3 and 4 are required for this. I think any migrated account will see this happen.

What we should do instead of prompting for password is get them to enter their username (less ideal) or force FxA authentication and then they can only delete their account if they've authenticated within the last 5 minutes or something.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screencast: http://screencast.com/t/PgPF6T7eeQ
