### ISSUE TITLE
"Enable Listed Auto-Approval Before Next Manual Approval" message is confusing

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#15249]
### Describe the problem and steps to reproduce it:
The way I understand it, "Disable Listed Auto-Approval Before Next Manual Approval" will mark the add-on so that auto-approval is disabled, but it will automatically re-enable itself on the next submission. When clicked, it turns into "Enable Listed Auto-Approval Before Next Manual Approval", which is a bit confusing to me.

I'm not sure I've fully understood the feature, but based on my understanding now, let me know if the following would work to help clarify. Also happy to be enlightened. /cc @wagnerand @iulianacse 

### What happened?

* When auto-approval is enabled, these buttons are shown:
  *  "Disable Listed Auto-Approval": Permanently disable auto approval until re-enabled manually
  *  "Disable Listed Auto-Approval Before Next Manual Approval": Disable auto-approval until the next manual approval
* Clicking either will put them each into a separate Disabled/Enabled state.
* The "Enable Listed Auto-Approval Before Next Manual Approval" message is a bit confusing.

### What did you expect to happen?

* When auto-approval is enabled, show buttons "Disable Listed Auto-Approval" and "Disable Listed Auto-Approval _Until_ Next Manual Approval"
* When auto-approval is disabled in whatever form, just show "Enable Listed Auto-Approval"
* When auto-approval is disabled until next approval, additionally show a text that says "Auto-Approval will be enabled on the next manual approval". This could be closer to the review actions if it helps.

**Comment by diox** [comment]
> The way I understand it, "Disable Listed Auto-Approval Before Next Manual Approval" will mark the add-on so that auto-approval is disabled, but it will automatically re-enable itself on the next submission

The disable is called `Disable Listed Auto-Approval Until Next Manual Approval`, not `Before` :) As the name implies, it disables auto-approval until there has been a manual approval on the add-on. This is meant to be set automatically when there is a delayed rejection, per delayed rejection PRD. When the auto-approval until next manual approval is already set, then opposite becomes "Enable listed auto-approval before next manual approval", since what you're doing if you click it is enabling regular auto-approval before any manual approval happens.
