### ISSUE TITLE
Add `promoted` filter to addons api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15272]
the addons api can filter by recommended status - we need to expand that to allow addon searches to be filtered by any promoted class.

**Comment by eviljeff** [comment]
@bobsilverberg while doing the PR for this I realised we don't have a good answer about `NotPromoted` in the api.  We have an `api_name` for it defined, but, afaik, we don't store it in the index, or return it (it's None` instead).   

 _Do_ we want want to be able to filter by `not_promoted`?  It could be `?promoted=not_promoted` - though we never supported `?recommended=False`, I note.  It's not impossible to add support for it but it'd need a bit of special handling because of the `None`-ness in the index.

**Comment by eviljeff** [comment]
@bobsilverberg second thing I wondered about was multiple promotions (i.e. comma separated).  I left it out because it would have made the implementation more complicated (with many more tests!) but could be added in a follow-up issue if you think `?promoted=recommended,line` to return addons in either category will be a thing.

**Comment by ioanarusiczki** [comment]
@eviljeff I tried various combinations of search/autocomplete parameters. 

Scenarios:
- requests with `?promoted=category`, `?promoted=category&app=add-on application`, `?promoted=category&app=add-on application&type=add-on type` -> status 200
- requests with a category that does not exist -> 400 bad request
- combination of `?promoted=recommended&recommended=true` returns the same results as if I use each of them individually. 

One question:
- a request such as `?promoted=line&recommended=true` has a 200 status, with 0 add-ons found. Should this be a 400?

**Comment by eviljeff** [comment]
>     * a request such as `?promoted=line&recommended=true` has a 200 status, with 0 add-ons found. Should this be a 400?

`recommended=true` is deprecated and will likely be removed once frontend has switched to `promoted` so I'm not too concerned with mixing the old and new filters together.

**Comment by bobsilverberg** [comment]
@eviljeff I think your questions above are both for product, and I believe that one of them is answered in the PRD, but I will restate the issues here, and you can correct me if I am wrong:

Q: Will we need to be able to search through all add-ons for those that are specifically not promoted?
There is a discussion of this [in the PRD](https://docs.google.com/document/d/1dm6d8pBvUVP4sTAQcg5WvXu10NGZJtbOzPU9eyb0AH4/edit?disco=AAAAJ0VojPM) where it talks about changing the "Recommended" checkbox to a dropdown that has values for "Recommended", "Verified", "Line" and "Reviewed" (the latter of which is a combination of the other three). It does not mention an option for "All not promoted", and I'm not sure there's a decent use case for that, so it sounds like we can leave it out.

Based on what's in the PRD, and discussed above, I believe this answers your question about whether we need to be able to search by more than one specific catergory, for example `?promoted=recommended,verified`. In order to be able to search for "Reviewed", as discussed above, we would need to be able to specify `?promoted=recommended,verified,line`, because there are other promoted categories in addition to those three, so I think an argument that was just `?promoted=true` wouldn't return the same thing as what is defined above as "Reviewed".

We could probably implement a `?promoted=reviewed` argument, which the server would understand to be the same as `?promoted=recommended,verified,line`, but I'm not sure if that's a good idea.

@jvillalobos Can you please take a look and let us know the answer to the question posed above, as well as whether the interpretation of the PRD above is accurate and up to date?

**Comment by jvillalobos** [comment]
That's correct, we don't need a filter for "not promoted".

We just need the ones explained in the PRD: "Recommended", "Verified", "Line" and "Reviewed", with the added note that for users "Verified" includes both what we call "Verified" and "Sponsored".
