### ISSUE TITLE
Signature files will not be visible in code-manager if the git-extraction is completed before the add-on is signed

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15327]
### Describe the problem and steps to reproduce it:
1. Submit a new add-on
2. Wait for ~5 minutes to make sure that the git-extraction has completed extracting the version
3. With a reviewer account, Approve the new add-on manually
4. Open the code-manager to inspect the files available for this add-on version - see [example](https://code.addons-dev.allizom.org/en-US/browse/620118/versions/1691940/)

### What happened?
The signature files (META_INF / mozilla-recommendation) are not present in code-manager

### What did you expect to happen?
The signature files should be present 

### Anything else we should know?
This issue is very similar to #11102, which was fixed by making the git-extraction run twice in such cases. Probably, when the git-extraction method has been redesigned, this aspect was not part of the implementation. 
Since #11102, the review and signing process has changed significantly, as we now have much more cases of add-ons with delayed (auto)approvals.

**Comment by willdurand** [comment]
I suppose this is _not_ unexpected these days (given that we can delay signing). @diox should we wontfix this issue?

**Comment by diox** [comment]
I am not sure I understand why this is happening. There can be a small delay, but eventually, we should extract after signing, and so the signature files should eventually be shown in code-manager, right ?

**Comment by willdurand** [comment]
> I am not sure I understand why this is happening. There can be a small delay, but eventually, we should extract after signing, and so the signature files should eventually be shown in code-manager, right ?

My thought was that once `git_hash` is set on a version, we don't re-extract?

**Comment by diox** [comment]
Ah, right, forgot about that. I don't mind wontfixing, but maybe @wagnerand does ?

**Comment by wagnerand** [comment]
Ideally, the code-manager (and thus the git-repo) should reflect the current (live) state of the file. For example, if the file is signed, the code-manager should show the `META-INF` folder and its contents. This is even more important now that we have additional badging information inside the XPI.

I am aware we have talked about it before and it was mentioned it's not easy to do. On the other hand, unless that has changed in the meanwhile, we are still extracting - or at least trying to extract - several times (before and after signing?). It sounds plausible to me that this is probably not working correctly if we are skipping extraction when a `git_hash` is already set for a version. I don't know what a proper solution would look like on the technical side, but the behavior described above would be preferable to me.

If that's not feasible, then we might want to clean up that code anyway and remove the second attempt to sign, which will never happen, assuming the above is accurate.

I think it would be helpful to document the current behavior and discuss what our options are and which one of them would be feasible.

**Comment by wagnerand** [comment]
A greenfield approach (unclear if feasible) could be:

Do not extract the file until the point where we make a decision on whether the file is auto-approved or not.
1) When we auto-approve it, send the signal to extract the file after signing has completed.
2) If we don't auto-approve, send a signal to extract the file right away.
3) When we manually approve, send a signal to extract the file after signing has completed.

In each case (first and third really, the second one is does not apply for the following), we probably would have to extract even if the file has been extracted already. Especially for unlisted, this could involve rewriting the git-history due to potential subsequent versions already existing.

In fewer words:

1) Extract a file after signing has completed, even if the file had already been extracted.
2) If a file does not match the auto-approval criteria, extract it, if it hasn't been extracted already.
