### ISSUE TITLE
Don't warn about compatibility issues for non-strict add-ons in devhub

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1548]
If an add-on does not adhere to [strict compatibility](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#strictCompatibility) (which it does not by default) then we should not show this scary warning when their maxVersion is out of date.
![amo-compat](https://cloud.githubusercontent.com/assets/55398/12680571/346a332e-c670-11e5-90a7-562be835b119.png)

It is quite common to see this error because jpm's min/max versions are no longer being maintained (see https://github.com/mozilla-jetpack/jpm/issues/474#issuecomment-176489206).

**Comment by kumar303** [comment]
Thunderbird may care about binaries still (Firefox does not) so we could also check the `binary` flag to show/hide the warning.

**Comment by asamuzaK** [comment]
[amo-validator/app_versions.json at master · mozilla/amo-validator](https://github.com/mozilla/amo-validator/blob/master/validator/app_versions.json)

There is no `*` for Firefox's version list.
I think adding `*` in Line 5 (start of the list) or at the end may fix.
What do you think?

After that, maybe you should fix this too (remove them).
[amo-validator/constants.py at master · mozilla/amo-validator](https://github.com/mozilla/amo-validator/blob/master/validator/constants.py)
from Line 46 to 48

> # Add the '*' fake max version. Used specifically for WebExtensions, see
> # https://github.com/mozilla/amo-validator/issues/390.
> APPROVED_APPLICATIONS['1']['versions'].append('*')

PS
Maybe this issue should move to mozilla/amo-validator ?

**Comment by andymckay** [comment]
@magopian this is fixed I think with your recent changes?

**Comment by asamuzaK** [comment]
At least, not for jetpack add-ons
![withexeditor_add-ons_for_firefox_-_2016-02-11_09 51 26](https://cloud.githubusercontent.com/assets/6790339/12966914/482b5a7a-d0a5-11e5-93cc-ae453a4fbb8c.png)
s

**Comment by asamuzaK** [comment]
My settings in package.json:
`  "engines": {
    "firefox": ">=38.0 <=*"
  },`

In install.rdf (which JPM created):
`          <em:targetApplication>
            <Description>
              <em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id>
              <em:minVersion>38.0</em:minVersion>
              <em:maxVersion>*</em:maxVersion>
</Description>
</em:targetApplication>`

**Comment by andymckay** [comment]
@magopian * was just for WebExtensions add-ons?

**Comment by diox** [comment]
Correct: https://github.com/mozilla/amo-validator/pull/391 was just for Web Extensions. I'm not sure of the implications of enabling that for everything else.

**Comment by jvillalobos** [comment]
Enabling * for all add-ons should be okay, since Firefox ignores the maxVersion for the most part. Some add-on types shouldn't set * as maxVersion, but that can be deal with by admins if it happens.

**Comment by andymckay** [comment]
If I set the maxVersion as * for an add-on, does the compatibility bump still happen? Concerned that a developer could set that and then lose out on that functionality and we assume that their add-on will always be compatible when it won't be.

**Comment by jvillalobos** [comment]
The bump wouldn't happen for them. Then again, many devs set a pretty high maxVersion without testing, or don't bump up the version after a false positive compat bump failure and stay behind... There are many cases where developers end up missing those notifications.

As long as we don't advertise the * maxVersion, I think only a minority of developers will end up using it. And if an add-on breaks due to compat changes, they'll find out, either from their users or us.

**Comment by andymckay** [comment]
I would rather document the * maxVersion (after all, this is all public) and be clear that doing so you don't get the compat checks going forward.

**Comment by jvillalobos** [comment]
wfm

**Comment by jc3213** [comment]
As signature will be required after 46 (or even from it is said to be 42), many developers would switch to either the developers' edition(aurora) or the nightly edition to continue their development(like me, I'm using nightly). It is because the beta and stable release won't accept unsigned add-ons for them to test if it works or not. So, I think it is ok to add wildcard * to the maxVersion.

**Comment by ValentinaPC** [comment]
1. In what concerns new submissions - I cannot verified this because submission is blocked if the install. rdf does not contain the `strictCompatiblily` preference.
2. If I make an update to an already submitted add-on, I am not able to see if the red banner is displayed because the updated add-on is not listed in Manage My Submissions page (even if I added myself as an owner of the add-on)

@diox : Is there any other way to check this?

**Comment by diox** [comment]
2. is weird. If you are a developer of an add-on you'll see it in Manage My Submissions page... that's always been the case ?

Try to figure out why this is not working for you and you'll be able to bypass restrictions by just adding you as a developer on an add-on that already has strict compatibility enabled.

**Comment by ValentinaPC** [comment]
It turns out that the add-on I've updated at 2. is listed in Manage My Submission, but being created looong time ago, is not listed in the first page....because the list was sorted by creation.

The red banner is no longer displayed in Dev Hub for incompatible add-ons if they don't have `strictcompatibility` preference set.
![red-compat](https://user-images.githubusercontent.com/15685960/28827542-94d194e2-76d6-11e7-9e77-704994abc1ba.png)
