### ISSUE TITLE
Stop displaying counts in reviewer tools queues tab bar

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15502]
Originally https://github.com/mozilla/addons-server/issues/15392

Don't show counts for the queues in the tab bar (keep them on the dashboard and keep the current one in the pagination).

Bonus: tweak layout, the tab bar was never meant to display that many queues originally...

**Comment by kewisch** [comment]
Would it be an option to show the counts only on specific queues that we intend to be small? Softvision relies mostly on the counts for the Recommended Extensions and Other Pending Reviews queues. @caitmuenster and I rely on the count for the Rating Reviews.

**Comment by diox** [comment]
The counts continue to be displayed on the current queue you're viewing as well as the dashboard. Isn't that enough for you ?

**Comment by AlexandraMoga** [comment]
The navigation tabs are no longer displaying the queue counts:
![image](https://user-images.githubusercontent.com/31961530/93602919-fd34e180-f9cb-11ea-89be-cd4afd6f45d7.png)

The page width has been increased and there were no layout issues introduced (in fact, some of the existing layout issues, like the crowded navigation tabs and the Performance page graph, have been fixed by this). Queue counts are still being displayed on the dashboard:
![image](https://user-images.githubusercontent.com/31961530/93603091-340af780-f9cc-11ea-89b7-1103ed542283.png)


@diox you mentioned that "counts continue to be displayed on the current queue you're viewing", but as far as I can tell, these counts are displayed only when pagination is also present (see screenshot). For queues that have less than 200 entries (which is the current page limit) there is no indication of the total number of pending items.

[queue counts when pagination is present]
![image](https://user-images.githubusercontent.com/31961530/93603132-3d945f80-f9cc-11ea-9ecb-f2796c9a197e.png)

**Comment by diox** [comment]
> @diox you mentioned that "counts continue to be displayed on the current queue you're viewing", but as far as I can tell, these counts are displayed only when pagination is also present (see screenshot). For queues that have less than 200 entries (which is the current page limit) there is no indication of the total number of pending items.

I think that's fine, but if needed we could force the number to be shown also when no pagination is present.
