### ISSUE TITLE
MAD score is shown as -100%

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15500]
In the reviewer tools, the MAD score is shown as -100% for some add-ons. @willdurand tells me we are converting a result of -1 into a percentage. We should probably not do that. Maybe, we can also display something more sensible instead of -1.

Thanks to @spoji for reporting it via Matrix.

**Comment by AlexandraMoga** [comment]
I've submitted a few different add-ons but I could not get a score of -100% (or `n/a` for that matter) in rev tools.
However, I was bale to find an add-on on stage that had a -100% score before the patch landed and now the score for that add-on has been updated to `n/a`:

[before patch]
![image](https://user-images.githubusercontent.com/31961530/93983250-fa9b0900-fd8a-11ea-9143-975da0d83046.png)

[after patch]
![image](https://user-images.githubusercontent.com/31961530/93983271-038bda80-fd8b-11ea-9d3b-1f2105c1cb13.png)

This issue is verified fixed on stage.
