### ISSUE TITLE
For some add-ons the calendar shows inactive dates when trying to select a custom date

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15516]
From https://github.com/mozilla/addons-server/issues/15213#issuecomment-693306177

STR:
1. Go to one of the following add-ons:
https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/statistics/?last=7
https://addons-dev.allizom.org/en-US/firefox/addon/firefox-color/statistics/?last=30
https://addons-dev.allizom.org/en-US/firefox/addon/private-relay/statistics/?last=90
https://addons-dev.allizom.org/en-US/firefox/addon/statistics-reloaded/statistics/?last=365
2. Open `Custom` and go back to a different month, observe the calendar.

Expected result:
Dates can be selected.

Actual result:
At some point, dates become inactive. 

Notes:
As a workaround - click on `From` and a calendar opens which can be used for selecting a number.
Not for all add-ons is reproducible. I did not find it reproducible for the lang packs below
https://addons-dev.allizom.org/en-US/firefox/addon/asturianu-language-pack/statistics/?last=7
https://addons-dev.allizom.org/en-US/firefox/addon/czech-cz-language-pack/statistics/?last=30

![selectable2](https://user-images.githubusercontent.com/33448286/93453176-03e72a00-f8e2-11ea-8c4a-c232f97a1177.gif)

**Comment by willdurand** [comment]
Interesting. Is it possible that we don't have data before this `from` date?

**Comment by ioanarusiczki** [comment]
@willdurand For this particular case https://addons-dev.allizom.org/en-US/firefox/addon/firefox-color/statistics/?last=30 daily user data was available in 2019 when I see these dates.
Same for https://addons-dev.allizom.org/en-US/firefox/addon/private-relay/statistics/?last=90 -> daily user data was available before July when I see these dates.
But in other cases such as https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/statistics/?last=7, there's no data for 2018 when dates cannot be selected.

**Comment by willdurand** [comment]
Alright, I see what's going on. I don't think you can reproduce this problem on prod because the datepicker "min date" is set to the add-on creation date. On -dev and -stage, we created add-ons for testing purposes but we rely on stats data coming from production where add-ons have been created in the past. That's why we see data but the datepicker does not allow us to select a date that is _before_ the add-on creation date.

The fact that we can still use the input instead of the fancy widget is a bug with the datepicker lib and we cannot do anything.

There is nothing to fix here.

**Comment by ioanarusiczki** [comment]
@willdurand Alright, I have a workaround in these cases anyway so I am going to remove the milestone too.
