### ISSUE TITLE
Unique icons in the reviewer review queue for different promoted groups

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15520]
The fix for #15124 was just a single "P" icon, but with unique css classes (and title attributes in markup).  If we have distinct icons it's just a matter of updating the sprite graphic (and the line offsets in the css file).

**Comment by mixedpuppy** [comment]
by request, addon manager icons:

https://searchfox.org/mozilla-central/source/toolkit/themes/shared/extensions/line.svg
https://searchfox.org/mozilla-central/source/toolkit/themes/shared/extensions/recommended.svg
https://searchfox.org/mozilla-central/source/toolkit/themes/shared/icons/check.svg (verified)

**Comment by eviljeff** [comment]
There are 6 promoted groups currently:
* recommended - doesn't strictly need an icon because it has it's own queue but could.
* sponsored
* verified
* line
* spotlight
* strategic

Som using https://searchfox.org/mozilla-central/source/toolkit/themes/shared/extensions/recommended.svg for recommended is possible; and I guess a check mark is okay for verified if you think it unambiguously means "verified"?

Using the Firefox logo (i.e. something like line.svg) for Line is an option, but I'd be a concerned it could be interpreted as application compatibility rather than promoted group.  Regardless, we need icons for the other groups.

**Comment by wagnerand** [comment]
I'd suggest the following:

* recommended: https://searchfox.org/mozilla-central/source/toolkit/themes/shared/extensions/recommended.svg
* sponsored and verified: https://searchfox.org/mozilla-central/source/toolkit/themes/shared/icons/check.svg
* line: https://searchfox.org/mozilla-central/source/toolkit/themes/shared/extensions/line.svg
* spotlight and strategic: None, or keep the "P" for now.

/cc @kewisch

**Comment by eviljeff** [comment]
QA: flags should be shown in all queues now also (https://github.com/mozilla/addons-server/issues/15124#issuecomment-696198553)

**Comment by AlexandraMoga** [comment]
The new Promoted icons are available as follows:


![image](https://user-images.githubusercontent.com/31961530/94014496-4910cd80-fdb4-11ea-8c48-408a0b8e1814.png)

![image](https://user-images.githubusercontent.com/31961530/94014873-cdfbe700-fdb4-11ea-8fae-49278b47fd50.png)


The icons are now displayed in all queues, not just the Recommended or Other Pending review queues:

[Auto-approved/ Content review queue]

![image](https://user-images.githubusercontent.com/31961530/94014787-aefd5500-fdb4-11ea-8722-7486cf834b5f.png)

 This issue is verified fixed on -dev.
