### ISSUE TITLE
Requesting a super-review for AMO admins sometimes send messages to dev.

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#15620]
### Describe the problem and steps to reproduce it:
On version 2.2.12 of [malwarebytes](https://reviewers.addons.mozilla.org/en-US/reviewers/review-listed/malwarebytes), my "Admin add-on-review requested" comment ended up inside the dev's mailbox. I assume so as the dev replied two days later requesting clarification about my message.

### What happened?
"Admin add-on-review requested" comments seem sometimes to end up inside the dev mailbox.

### What did you expect to happen?
"Admin add-on-review requested" comments should not be sent to the developer.

### Anything else we should know?
Note that I tried to reproduce this issue with Jorge on [drumpfinator-fx](https://reviewers.addons.mozilla.org/en-US/reviewers/review/drumpfinator-fx) version 1.0. He didn't receive any email.

**Comment by jvillalobos** [comment]
I didn't get the email, but it looks like admin review comments are now showing up in the DevHub:

<img width="726" alt="Screen Shot 2020-10-01 at 1 45 36 PM" src="https://user-images.githubusercontent.com/62568/94855878-682ee100-03ec-11eb-9b97-96658aa60014.png">

**Comment by spoji** [comment]
Thanks for this follow up. I think that, by design, it shouldn't show there. Those messages should be accessible to admins only.

**Comment by AlexandraMoga** [comment]
I've tried to replicate this on stage but I can't see an actual email being sent to the developer when I look in Fakemail. I do see the message in Devhub though.

**Comment by diox** [comment]
When https://github.com/mozilla/addons-server/issues/3642 was implemented we verified that a generic message was shown in devhub for this action. Not sure how this regressed since yet.

**Comment by diox** [comment]
This is a regression from 1340cf9c6829c3c7611067b5a541b39ac7ca26cb (April 2018) when we split super review requests for code/content/theme. The new actions introduced for the split don't have the generic message and therefore show the full comments instead.

**Comment by AlexandraMoga** [comment]
I've submitted super review requests for extensions (listed/unlisted) and themes and the the Dev Hub add-on review history will display a generic message instead of the actual message written by the reviewer.
This applies both for code and content super-review requests.

[code review]
![image](https://user-images.githubusercontent.com/31961530/95189772-f7663b00-07d6-11eb-80dd-5863329a423b.png)
[content-review]
![image](https://user-images.githubusercontent.com/31961530/95189797-05b45700-07d7-11eb-9045-b318f57ecbb9.png)

Reviewer Comments are still accessible only to reviewers while Reviewer replies will be visible to developers.

@diox I understand that Admin reviewers should receive an email when a super-review request is submitted. I have an user who is an Admin reviewer on -dev but I didn't see any related notifications in Fake mail. I can address this issue in a follow up.

**Comment by diox** [comment]
> @diox I understand that Admin reviewers should receive an email when a super-review request is submitted. I have an user who is an Admin reviewer on -dev but I didn't see any related notifications in Fake mail. I can address this issue in a follow up.

Yeah, please open another issue for this - I'm not sure whether it's actually still required but we can discuss that in the new issue.

**Comment by wagnerand** [comment]
If I remember correctly, we removed the email notification on purpose.
