### ISSUE TITLE
Measure installation of add-ons returned by Adzerk

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#15718]
For add-ons in the sponsored shelf, we need to measure impressions, clicks, and installations. There are some additional steps that need to be taken in the Adzerk setup for installations to be measured. Front-end issue: https://github.com/mozilla/addons-frontend/issues/9762

**Comment by ioanarusiczki** [comment]
@eviljeff The sponsored shelf API https://addons-dev.allizom.org/api/v4/shelves/sponsored/ has a new property below "click_data" for each add-on displayed: "event_data" which includes "click" (and I think it has the same value as "click_data") and "conversion". 

If I sent a POST request with https://addons-dev.allizom.org/api/v4/shelves/sponsored/click/, using the "conversion" value instead of the "click_data" value, I get a 202 Accepted status.

Two questions:

- Is the "click_data" still needed if the "click" has the same content? 

- Is the 1 hour expiry interval still applicable for the POST request for https://addons-dev.allizom.org/api/v4/shelves/sponsored/click/ ? Because today I did not get a 404 with the warning from https://github.com/mozilla/addons-server/issues/15619

**Comment by eviljeff** [comment]
> Two questions:
> 
>     * Is the "click_data" still needed if the "click" has the same content?

It's not, but I didn't want to break frontend code in the meantime.  I'll remove it in a follow-up.

>     * Is the 1 hour expiry interval still applicable for the POST request for https://addons-dev.allizom.org/api/v4/shelves/sponsored/click/ ? Because today I did not get a 404 with the warning from #15619

It's been increased to 24 hours, like the conversion (install) event.

**Comment by ioanarusiczki** [comment]
@eviljeff I tested the interval and it's "Bad click_data: Signature age 88524.8540687561 > 86400 seconds"
