### ISSUE TITLE
Images attached to the primary hero addons have various dimensions

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15729]
Followup for https://github.com/mozilla/addons-server/issues/14473#issuecomment-708407015

1. The frontend shows different dimensions for the images attached to the primary hero addons. 

![resized](https://user-images.githubusercontent.com/33448286/95997880-ee134900-0e3c-11eb-8ced-054528961a48.gif)

Looking at prod - it used to be 480x320

**Comment by eviljeff** [comment]
yes, whatever image that's uploaded via the admin is served.  The uploader needs to be careful they've uploaded something with the correct aspect ratio.

**Comment by ioanarusiczki** [comment]
@eviljeff Well then this is not an issue, hm, they looked quite alright before. 
I'm closing this.

**Comment by eviljeff** [comment]
There isn't a good way of resolving this problem programmatically*.

*broadly, the options whenever an image of the wrong aspect ratio is submitted are either to
* crop the image (problem: impossible to know what the "correct" crop is)
* return the wrong aspect ratio (current problem)
* error at the submission (problem: errors on minor numeric differences)

They looked alright before because I carefully cropped and resized the assets manually 😄

**Comment by ioanarusiczki** [comment]
@eviljeff yes, it worked for me too 😄 , I resized it manually then uploaded it, and attached it to an addon. I got the 480x320 px on the frontend:

![works for me](https://user-images.githubusercontent.com/33448286/96000963-29fbdd80-0e40-11eb-9c76-6da4afd26292.png)
