### ISSUE TITLE
Implement payment flow using Stripe Checkout

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15726]
The PRD has more info about the exact flow: https://docs.google.com/document/d/1cohRp8JRlv7h41I0MxFUK1oBk70th71Fa7g4sGruzpM/edit#

In short, we have a landing page with a big button to go to Stripe. Once payment has been made, we return to a similar page. In case of an error, it should be possible to go to Stripe again (and there will be an error message displayed).

When the payment is successful, there are changes to make to the add-on but this will be tackled in a different issue. This issue is about implementing the views to have a working payment integration.

**Comment by bobsilverberg** [comment]
So this will be part of DevHub, or elsewhere in addons-server code?

**Comment by willdurand** [comment]
> So this will be part of DevHub, or elsewhere in addons-server code?

DevHub

**Comment by harsh07051** [comment]
i will like to take it up

**Comment by diox** [comment]
This issue is already assigned (and was never opened to external contributors in the first place, look for https://addons-pm.herokuapp.com/contrib/good-first-bugs/ to begin contributing to AMO).

**Comment by ioanarusiczki** [comment]
@willdurand 

I could make a subscription following the above flow for verified/sponsored add-ons:

1. The regular user can access the onboarding URL:

![Set up payment](https://user-images.githubusercontent.com/33448286/97010948-be57f580-154e-11eb-9740-f8e72eb6ad5e.png)

2. The user makes the payment using Stripe service:

![Stripe page](https://user-images.githubusercontent.com/33448286/97011033-da5b9700-154e-11eb-9171-f4b0a63185d8.png)

3. The flow is complete, the user is asked to submit another version

![after payment step](https://user-images.githubusercontent.com/33448286/97011077-e9dae000-154e-11eb-84a9-a7d01064220c.png)

In case of an error (as canceling payment, I clicked the back button next to Mozilla(test Will):

![The error message](https://user-images.githubusercontent.com/33448286/97011361-3de5c480-154f-11eb-9aee-2e09d9eff28e.png)

From the admin perspective:

- technically there is no need for the developer to submit a new version. A first version of an add-on which is awaiting review can be approved - the page can be accessed from "Other pending review:" queue.  
The current flow requires 2 submissions (otherwise the onboarding URL would not be generated in the admin) so the first version is automatically disabled and the next version after payment is approved. 
[Sponsored](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/upload-an-addon)
[Verified](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/a-verified-addon)

From the developer's perspective: preferable one version instead of 2.

I've also noticed that the onboarding URL is also visible for the admin. Other regular users cannot access it. 

Once the subscription is done:

![payment done](https://user-images.githubusercontent.com/33448286/97012441-85b91b80-1550-11eb-8b83-0d1dd94799b8.png)

**Comment by ioanarusiczki** [comment]
@willdurand I think the above flow looks good. 

2 questions:
- what happens when the developer wishes to cancel subscription after a payment ?
- if the addons changes the group from sponsored to verified what should happen? Right now if I follow the onboarding URL generated I see the "You're done" step - where a new version is required. But the fee for the 2 groups are not the same.

**Comment by willdurand** [comment]
> what happens when the developer wishes to cancel subscription after a payment ?

We don't know yet. We filed https://github.com/mozilla/addons-server/issues/15805 and we'll talk to Product.

> if the addons changes the group from sponsored to verified what should happen? Right now if I follow the onboarding URL generated I see the "You're done" step - where a new version is required. But the fee for the 2 groups are not the same.

Yes, that's also captured in https://github.com/mozilla/addons-server/issues/15783
