### ISSUE TITLE
Recommended addons show up in the list of addons without a badge when going from Firefox to All applications

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15740]
STR:
1. A recommended addon in the promoted model has "Firefox" application
2. Change it to All Applications 
3. Observe the list of recommended addons on android

Expected result:
The addon should be available on Android only after a new version is submitted and approved.

Actual result:
The addons is displayed in the list of [search results](https://addons.allizom.org/en-US/android/search/?promoted=recommended&sort=random&type=extension) without the recommended badge

Notes:
This is also reproducible when going from "Android" to "All Applications" on AMO stage - FF81(win10). 
Not reproducible when it is changed from desktop to android as mentioned in this[ PRD](https://docs.google.com/document/d/1QTt1G05tjQqfi4ZuAx8Jy4lAshQKdFQpTC3_zqMQHQA/edit#heading=h.xgwsthhsp8lm) when only after the approval of a new version the addon is displayed with it's badge.

**Comment by eviljeff** [comment]
thanks for catching this - it's because we're using slightly different properties in the ES index to filter on vs. what we return in the JSON.

(technical breakdown - we're indexing and then filtering on `.promoted.application_id` which is the application id of the `addon.promotedaddon`, rather than the current approved applications, which is stored as `approved_for_apps`.  I suspect the fix is to not store both things - either store an `application_id` which is actually the approved apps and don't store `approved_for_apps` seperately; or don't store `application_id` and filter on `approved_for_apps` instead)

**Comment by ioanarusiczki** [comment]
@eviljeff I tested this on AMO dev with FF82(Win10) - this is no longer reproducible.
