### ISSUE TITLE
Drop developer reply emails from banned users 

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15743]
### Describe the problem and steps to reproduce it:

1. As a developer, submit a new add-on.
2. As a reviewer, reject the add-on.
3. As an admin, ban the user.
4. As the developer, reply to the rejection email sent in step 2.

### What happened?

The email is accepted by AMO and its contents are added to the reviewer tools.

### What did you expect to happen?

The email should be dropped.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
@wagnerand here are my test results:

- Testing that a banned user cannot reply to reviewer messages by email:
  - I've located the rejection email in Fake mail and copied the "Reply-to" address
  - I've sent an email to the "Reply-to" address copied before
  - I've checked Fake mail again to see if an automatic reply has been returned to the sender - [Fake mail id](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/95486/change/)  
![image](https://user-images.githubusercontent.com/31961530/97889272-d5f46280-1d34-11eb-84dd-1f58036c1edb.png)
  - I've checked the add-on review page to make sure that the email reply attempt from the banned user is not displayed
- Testing that a banned user cannot reply to reviewer messages from DevHub:
  - with the banned user still being logged in on the add-on manage versions page, I've tried to post a Reply in the Review history; the Reply button has no effect and a 401 Unauthorized error is received in the console (that is because the user session is terminated when the ban action takes place)
- Testing that developer replies are still received if the user is not banned:
  - I've located the rejection email in Fake mail and I've copied the "Reply-to" assigned address
  - I've sent an email to the "Reply-to" address copied before
  - I've checked Fake mail again to make sure that the developer reply has been received
  - I've checked the add-on review page to make sure that the email reply is visible on the add-on review page

Regarding the automatic reply sent to banned users, I believe that `Please visit https://addons-dev.allizom.org to leave a reply instead.` should not be present in the email body. It is a small issue though.
