### ISSUE TITLE
Handle already promoted add-ons after payment

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15786]
Let's adjust the content for add-ons part of the pilot program.

**For QA:** if an add-on is already promoted as "sponsored" (or verified) and the current version has been approved, the payment flow should say something like "You're done".

**Comment by willdurand** [comment]
I think we can start with a different message like `You're done!`.

**Comment by ioanarusiczki** [comment]
@willdurand For all the verified/sponsored add-ons I verified for https://github.com/mozilla/addons-server/issues/15726, that went through the payment step when I try to access the URL again I receive "You're done" and the Manage add-on button that redirect to edit addon page.

![you're done](https://user-images.githubusercontent.com/33448286/97148127-44548600-1773-11eb-8cb3-40f57e05bfbf.png)

Those that are sponsored - already on the sponsored shelf (approved before introducing the payment flow) can be onboarded - the flow starts with "Continue to Stripe Checkout". 

I believe that's the expected behavior. 

Verified on dev - FF82(Win10).
