### ISSUE TITLE
make Version.version (and other version fields) a type of VersionString

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15798]
We recently refactored version string comparison to fix some edge cases but it would be good if Version.version was naturally able to be compared as a version string everywhere.  This will lead to more straightforward code where version is compared to, and will remove any edge case where we accidentally forget to convert it first

**Comment by ioanarusiczki** [comment]
@eviljeff If qa can verify this, please add some str. 
Thanks!

**Comment by eviljeff** [comment]
QA: this shouldn't change any functional behaviour but it does touch a few places in the model back-end.  Most will be difficult to directly verify - the most exposed is the blocklist and blocklist admin.  

So please check a BlockSubmission can be created with different min and max versions - with more than one guid so it's a free-text input - including when min_version is 0 or blank.  And also check that addon versions are correctly blocked in the blocklist output (stash json is fine), especially version edge cases e.g. min_version `3.9.*` blocks `3.9.0` and `3.10` but not `3.8.99`, etc.

**Comment by AlexandraMoga** [comment]
@eviljeff I've blocked several add-ons with various version strings. Please have a look at these results, especially the last three which don't seem to be exactly as expected. 

- [Example 1](https://reviewers.addons.allizom.org/en-US/reviewers/review/version-strings1)
  - the add-on was fully blocked in admin (version range `0 - *`) - [block submission](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/154/change/?_changelist_filters=signoff_state%3D4)
  - _actual block results as viewed on amo_: all add-on versions were blocked (as expected)
  - _stash results_: all expected blocked versions are in stash
- [Example 2](https://addons.allizom.org/en-US/reviewers/review/1004941)
  - free block range input in admin - `0 - *` (the default) - [block submission](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/159/change/?_changelist_filters=signoff_state%3D4)
  -  _actual block results as viewed on amo_: all add-on versions were blocked (as expected)
- [Example 3](https://reviewers.addons.allizom.org/en-US/reviewers/review/version-strings2)
  - free block range input in admin - `3.9.* to *` - [block submission](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/155/change/?_changelist_filters=signoff_state%3D4)
  - _actual block results as viewed on amo_: versions blocked: `3.10, 3.90, 4.0`
  - _expected block results_: all versions except for `3.8.99`
  - _stash results_: same versions as seen on amo
- [Example 4](https://reviewers.addons.allizom.org/en-US/reviewers/review/version-strings3)
  - free block range input - `4.1.* to *` -  [block submission](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/158/change/?_changelist_filters=signoff_state%3D4)
  -  _actual block results as viewed on amo_: versions blocked: `4.10, 4.2.0`
  - _expected block results_: `4.10, 4.2.0, 4.1.999`
  - _stash results_: same versions as seen on amo
- [Example 5](https://addons.allizom.org/en-US/reviewers/review/1004936)
  - free block range input - `* to *` (could not leave the Min version field blank because input is mandatory) -  [block submission](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/160/change/?_changelist_filters=signoff_state%3D4)
  -  _actual block results as viewed on amo_: none of the versions have been blocked
  - _expected block results_: all add-on versions should have been blocked?
  - _stash results_: n/a

**Comment by eviljeff** [comment]
mmm, interesting.  It's due to `*` being interpreted as "infinitely large number" - which works great when `*` is included in a `max_version`; and perhaps unexpectedly so when it's part of a `min_version`.  For `min_version` we typically want `0`.    Not sure if we should cover it though.

**Comment by eviljeff** [comment]
Thinking more on this, I don't think there's a consistent way to implement `*` that would work for a `min_version` (while still working correctly for `max_version`).  

We want to be able to do `VersionString('3.9.0') <= VersionString('3.9.*')` is true to test if a version string is within the range for `max_version`.  But to test the range for `min_version` it would have to be `VersionString('3.9.0') >= VersionString('3.9.*')`.  For both to be true it would mean `<=`, `<`, `>=`, `>` would be true but not `==`, which is logically... unexpected.

Maybe we can just prevent `*` in a minimum version block entry with a validator for the forn instead.

**Comment by eviljeff** [comment]
filed https://github.com/mozilla/addons-server/issues/15877 to prevent `*` in a min_version
