### ISSUE TITLE
UI issues for "Is Approved" and "Primary Hero Shelf" 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15819]
Followup for https://github.com/mozilla/addons-server/issues/15737#issuecomment-714343186

1. When an addon is deleted "Is Approved" shows a correct state but the Primary Hero column shows it as still being displayed on the shelf. 

![deleted](https://user-images.githubusercontent.com/33448286/96991856-c2294f00-1531-11eb-80de-6ee79dbad49c.png)

2. Meanwhile disabled addons don't show anything to have a clue that it's been disabled

![The disabled](https://user-images.githubusercontent.com/33448286/96991962-e4bb6800-1531-11eb-98ae-ba5fb7309400.png)

This is reproducible  in the promoted admin model - FF82(Win10).

**Comment by eviljeff** [comment]
@jvillalobos / @devaneymoz I guess you'd want both deleted and (user) disabled add-ons to show as not being enabled shelf in the admin?  
The former is pretty clear (a deleted add-on is never going to suddenly become undeleted and a primary hero again) but the latter, when it's user disabled, is an edge case because the user could re-enable the add-on again at any point.

**Comment by jvillalobos** [comment]
I think the current behavior (keeping it approved) would be more consistent with the very likely future where we use Adzerk to decide what shows up in the primary hero area. If a developer disables their add-on during that time, we wouldn't automatically remove it from Adzerk. Rather, it would just be filtered out when the API tells the front-end what to show.

**Comment by jvillalobos** [comment]
It sounds like we don't need to do anything additional here.

**Comment by ioanarusiczki** [comment]
@jvillalobos Thanks
