### ISSUE TITLE
Don't approve versions for promoted when a subscription is in progress

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15868]
When an add-on has been added to the Verified/Sponsored promoted group but there is a subscription pending we shouldn't auto approve any new versions created in the meantime (or currently pending approval at the time the add-on was added to the group)

We also shouldn't allow addons to be manually approved for verified/sponsored while the subscription is pending.

**Comment by eviljeff** [comment]
Note: there may be some difficulties here in the transition period from the trial to BAU because in the trial period addon are verified but haven't got a subscription.

**Comment by ioanarusiczki** [comment]
@eviljeff  I think this works as expected because:

- addon versions submitted and awaiting review for a verified/sponsored addon cannot be manually approved because the "Approve" button is not available for reviewers until the payment is completed. 
- after the payment, new submitted versions are not auto-approved, they require manual review -> they're listed in the Other pending review queue from rev tools. 

I verified this with an admin and an addon reviewer account on AMO dev with FF82(Win10).
