### ISSUE TITLE
Do not cascade deletion of a license to deletion of all versions using that license

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15876]
### Describe the problem and steps to reproduce it:

STR:

1. Create a new license (via django admin)
2. Upload a version and select the license you just created.
3. Delete the license from the django admin

### What happened?

The uploaded version is also deleted.

### What did you expect to happen?

The uploaded version should be kept with the license attribute being set to null.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@wagnerand 
On AMO dev:
I could create, attach and then delete a License. Once the License from django is deleted the versions are still displayed in dev hub but without any License on the[ version page](https://addons-dev.allizom.org/en-US/developers/addon/select-the-general-license/versions/1692248). 

On AMO stage:
I could not delete the License once I created it. I receive this message: "Deleting the license 'General License' would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:
scanner result"

This probably will be fixed by this issue once it lands (I can't tell only after I re-test it for stage later this week). 

Common on both servers:
it is very important when creating the License in django to use a number for "Builtin:" field that has never been used before. Else it could generate some errors (including a 500 server error when I try to attach the license to a version). Let me know if you want an issue to be filed for this.

**Comment by wagnerand** [comment]
Thank you, @ioanarusiczki!
 
> Common on both servers:
> it is very important when creating the License in django to use a number for "Builtin:" field that has never been used before. Else it could generate some errors (including a 500 server error when I try to attach the license to a version). Let me know if you want an issue to be filed for this.

That sounds strange. Could you file an issue with more details?

**Comment by ioanarusiczki** [comment]
@wagnerand Done: https://github.com/mozilla/addons-server/issues/15904

I'll also take a look on stage tomorrow to make sure I can mark this verified.

**Comment by diox** [comment]
In case anyone wondered, I went through all `on_delete=` foreign keys and one to one relations in our models, and couldn't find similar issues for other models.
