### ISSUE TITLE
Link from reviewer page to scanner result page for scanner result admins

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15903]
On the reviewer tools page, if a version was flagged by a scanner, we see a _Flagged by scanners_ label.

If the reviewer has the permission `Admin:ScannersResultsView` and `is_staff` is `true`, let's linkify that label and point to the scanners result page for that version.

**Comment by wagnerand** [comment]
@diox I added checking for `is_staff` in initial comment.

**Comment by ioanarusiczki** [comment]
@diox 
I've noticed that the rev tool pages now link to djago admin to a scanner result page.
Example 1: [listed addon](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/swaryx-coyotte-groutter)
Example 2: [unlisted addon](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/e656113f2e4e4939912b)

I verified on AMO dev - FF84(Win10) with an admin account. 
I'll re-check with an account with Admin:ScannersResultsView later when -dev will allow register/login since right now it's not working, and there are some issues on the fxA side too.

**Comment by ioanarusiczki** [comment]
@diox I added a user, (with mozilla e-mail address) to this [group ](https://addons-internal.dev.mozaws.net/en-US/admin/models/access/group/50115/change/) which has Admin:ScannersResultsView but I cannot view the pages I mentioned above.

**Comment by ioanarusiczki** [comment]
@diox 
Sorry, the title is pretty clear, this is working as expected. - verified on dev with FF84(Win10).
