### ISSUE TITLE
Dev hub error when the Builtin field uses a number that already exists

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15904]
Followup for https://github.com/mozilla/addons-server/issues/15876#issuecomment-720472478

STR:
1. I created a new [License ](https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/license/4095/change/)on AMO dev 
2. I've given the Builtin the value `20`
3. Changed the Builtin to "9" (or any other value that belongs to other Licenses)
4. Attach an addon version to this License

Results:
A server error 

![server error](https://user-images.githubusercontent.com/33448286/97997430-9d668e80-1df1-11eb-8ba6-76e2c2e55ee3.gif)

This was reproducible on both testing servers - FF82(Win10).

**Comment by wagnerand** [comment]
It looks like only values 11-8 are valid for _Builtin_.

**Comment by diox** [comment]
The `builtin` value, when non-zero, must match one of the values from https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/licenses.py - this is a confusing mechanism, but the bug is really that you shouldn't be able to create/delete a `License` in the admin with a `builtin` value. You shouldn't be able to change the `builtin` value if there is one already set either.

**Comment by eviljeff** [comment]
> The `builtin` value, when non-zero, must match one of the values from https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/licenses.py 

it doesn't need to - that's just for the CC licenses (used for themes), the non-theme built in licenses (GPL, MPL, etc) aren't defined in constants.  From [sentry](https://sentry.prod.mozaws.net/operations/olympia-dev/issues/9926268/?query=is%3Aunresolved%20license) looks like the issue is just that we expect `builtin` to be unique, if non-zero, but don't enforce it at the database level or elsewhere.

I still think it's a p5 though - adding/changing built in licenses is a pretty rare task and admins should take care 😛
