### ISSUE TITLE
Developer can't download source code from developer hub version page

### ISSUE THREAD

**Issue by ralli007** [mozilla/addons-server#15926]
When I attempt to download the source by clicking on "Version 4.6.1" above, then beside "Source Code" clicking on "View Current" I get a 404 page. This is the page it sends us to: https://addons.mozilla.org/firefox/downloads/source/4951372 . The add-on is https://reviewers.addons.mozilla.org/en-US/reviewers/review-listed/wonder-switcher

**Comment by eviljeff** [comment]
@wagnerand can you confirm and provide any details which might point to what's special about this addon (or version or file)?

**Comment by diox** [comment]
Source code download has always been just an admin (and developer) thing.

**Comment by wagnerand** [comment]
Reviewers received an inquiry from a developer asking how to download the source code they uploaded again. They wrote:

_(when I attempt to download the source by clicking on "Version 4.6.1" above, then beside "Source Code" clicking on "View Current" i get a 404 page. But uploading our source is part of our process so I think we've been uploading those files. )_

Presumably, this is about the the _View Current_ on the developer hub version page. The version in question has been rejected by us.

I took a brief look at the code and it seems the disabled file (caused by the rejected version) makes the source code unavailable to the developer: https://github.com/mozilla/addons-server/blob/master/src/olympia/versions/views.py#L169
