### ISSUE TITLE
Setting up local developer environment from scratch fails with mysql 8

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15929]
When setting up a local dev enviromnent, setup fails during `python3 manage.py migrate --noinput`:

`MySQLdb._exceptions.OperationalError: (1156, 'Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory')`

This is due to the changed default auth method in mysql 8: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password

A workaround is to manually connect to the db and `ALTER` the user root as follows:

```
$ docker-compose exec mysqld mysql
mysql> alter user 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';
mysql> alter user 'root'@'%' IDENTIFIED WITH mysql_native_password BY '';
```

**Comment by diox** [comment]
This **only** affects new environments - when starting from an existing `mysqld` container, it's upgraded but keeps the old authentication plugin method, and everything works. New installs (or when the `mysqld` container, or its volume, was deleted) are broken.

This is caused by the upgrade to MySQL 8.0 in https://github.com/mozilla/addons-server/issues/15898 ; the new default auth plugin is `caching_sha2_password` but unfortunately in our image we're using MariaDB client libs/executable which [straight up do not support this](https://mariadb.com/kb/en/authentication-plugin-sha-256/).

**Comment by diox** [comment]
We can fix this by switching to the official `MySQL` client libs in our image, or by overriding the plugin used by the `mysqld` image default config. 

I also need to double-check behavior for dev/stage/prod and whether redash could somehow be affected, just to be sure.

**Comment by bobsilverberg** [comment]
It looks like this is affecting the frontend integration tests on CircleCI as well: https://app.circleci.com/pipelines/github/mozilla/addons-frontend/2874/workflows/fc9e7728-e785-416c-ba5d-47ccb5207c76/jobs/23684
