### ISSUE TITLE
Works with Firefox undefined - undefined

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1599]
The add-on https://addons.mozilla.org/en-US/firefox/addon/mute-all-inactive-tabs/ says "Works with Firefox undefined - undefined" in my Firefox 47.  

https://www.dropbox.com/s/7mry3q8dvco4i2o/Screenshot%202016-02-02%2016.31.55.png?dl=0

Not sure if its WebExtensions related.

**Comment by andymckay** [comment]
From evilpies in IRC: I think this might be the reason. Somehow compatibility is blank https://usercontent.irccloud-cdn.com/file/mFmAkEqG/Screenshot%20from%202016-02-03%2001%3A34%3A12.png

**Comment by magopian** [comment]
So there's something weird here, was the add-on/version admin validated or something? Several things strike me as odd:
1/ indeed, no "compatibility": this shouldn't be possible, unless maybe they used the devtools to un-disable the platforms selection during the submission process, and "force" the submission?
2/ I can see the upload and the manual edition in the devhub of the "max version" (for the compatibility part) for the version 0.1 (see screenshot below), but there's no trace of the 0.1.1 version in the feed (is it a caching issue?)

<img width="712" alt="screen shot 2016-02-03 at 09 34 56" src="https://cloud.githubusercontent.com/assets/167767/12776935/f28194a0-ca59-11e5-8326-401a163d665b.png">

The WebExtension as it is, with its manifest.json only specifying the `strict_min_version` can't be properly submitted on AMO until #1580 lands (maybe next week?), because at the moment not specifying a `strict_max_version` results in it being automatically set as `42.*` (which is smaller than `46.0`). Also, in the current manifest the `strict_min_version` is set to `46.0.0` which doesn't exist (it should be `46.0` I believe).

**Comment by jvillalobos** [comment]
An admin override wasn't used for this one.

**Comment by madalincm** [comment]
This is reproducing for "classic"  add-ons (not webextensions). Scroll down to the DOM Inspector addons in here: https://addons.mozilla.org/en-US/firefox/collections/whimboo/devel-tools/

Screencast: http://screencast.com/t/SXmJyzQyTI

**Comment by andymckay** [comment]
That's an add-on that only works on Thunderbird, yet being accessed at a Firefox URL and being asked for the version that it works for on Firefox, which are undefined. I actually think its a different bug. This is a collections bug.

**Comment by vasilicamihasca** [comment]
This is not a collection bug, because there is another place where this issue can be reproduced. 
Verified on AMO-dev using Firefox 48.0a1 (2016-04-11).
See screenshot:
![61f0916b7aa6c0564542526aed114cac7ea03ea5c1197c1139 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/18114210/14456697/efb5429a-00ae-11e6-9b0f-f3b793a8914b.png)
