### ISSUE TITLE
Owners and reviewers can't download add-on files from a region where the add-on is restricted

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16006]
Follow up for #15942 

### Describe the problem and steps to reproduce it:
1. Select an add-on and request its details: see https://addons-dev.allizom.org/api/v4/addons/addon/620244/ (this add-on is restricted in FR)
2. Locate the `files[].url` value where a direct link for the file download is located - make a copy of this link
3. Have the add-on restricted in a specific country
4. Authenticate as the add-on owner or as a reviewer and try to download the `.xpi` from the direct download link copied earlier

### What happened?
You receive a 451 error mentioning that the file is "Unavailable for legal reasons."

### What did you expect to happen?
As per https://github.com/mozilla/addons-server/issues/15942#issuecomment-726739024, add-on owners and reviewers should be able to download the add-on file even from regions where the add-on is restricted

### Anything else we should know?
Download links served by pages like Dev Hub - Manage versions and the add-on review page will not work because of this restriction

**Comment by diox** [comment]
Ah, yes, at the moment it works if the file isn't supposed to be public in the first place (disabled/deleted/unlisted cases). A refactor of the checks are needed to handle this case. 

It's tricky though, because to handle that properly, we'd need to always avoid the CDN redirect for those users (it doesn't do it now, but eventually the CDN *will* have region blocks), so we'd need to serve it ourselves. At the same time, most of the time we'd prefer letting the CDN serve to not put unnecessary stress on our servers. In addition, if somehow a developer copies the url they are redirected to to share it, it won't work if it's not the CDN one.
