### ISSUE TITLE
Ignore georestrictions in api for certain authenticated users

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16014]
follow-up for #15942 
> As a follow-up, we'll likely need something to be added to be able to bypass this if logged in as an admin, while adding something to the response to indicate to the frontend that we bypassed the restriction, but this doesn't have to be implemented right away.

**Comment by eviljeff** [comment]
@jvillalobos the easiest implementation would be to exclude (from the restriction) any user that would normally have "special" rights to the add-on detail when logged in - admins, reviewers, and the add-on's authors.  Does that fit the requirements, or should it _just_ be admins?  

(note: some addons/addon sub api endpoints need to be accessible by the add-on's authors regardless, e.g. #16005)

**Comment by jvillalobos** [comment]
I think it should only be admins. Add-on ownership could be abused by the owner in order to give people access to the add-on. Maybe unlikely, but I'd rather not leave that door open.

**Comment by bobsilverberg** [comment]
@jvillalobos you say "while adding something to the response to indicate to the frontend that we bypassed the restriction". How do we expect this to manifest in the frontend? I guess a separate frontend issue should be opened for that?

**Comment by jvillalobos** [comment]
@diox said that, not me 😄 

I suppose it would manifest as a message like the one we show when an admin looks at a listing page that is otherwise invisible.

<img width="798" alt="Screen Shot 2020-11-16 at 2 48 29 PM" src="https://user-images.githubusercontent.com/62568/99306457-db64a900-281a-11eb-8c41-4bce27cd5f2a.png">

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos. @eviljeff It looks like, for that message, we display it if `addon.status !== STATUS_PUBLIC || addon.is_disabled`, but I'm guessing neither of those would be true in this case. Do we need a new property in the `addon` response for `hiddenForRegion`, or something like that?

How important is it to show something like that on the add-on detail page when an admin is viewing an add-on that would otherwise be hidden for their region?

**Comment by eviljeff** [comment]
If it's _just_ admins, I'm not convinced it's justified to add the extra messaging because it'd be the intersection of a very small number of users being in a specific country, and a very small number of add-ons (which, like @bobsilverberg says, is unlikely to actually happen).

**Comment by jvillalobos** [comment]
For now I think it's fine to not show any specific messaging. We can revisit if geo-restrictions become more commonplace.

**Comment by AlexandraMoga** [comment]
I've reverified add-on georestrictions for users with special permissions. Full admins and users with `Addons:Edit` permission can now access the add-on detail and version detail API from restricted regions (i.e. the 451 is bypassed)

Reviewers that don't have the `Addons:Edit` permission will still receive the 451, as well as add-on Owners or Developers. 

I'm marking this issue as verified fixed on -dev.
