### ISSUE TITLE
Change returned data for localized fields in API version >= 5

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#16069]
As of API v5 (which is experimental at the time of writing), localized fields return different data than previous API versions. This change is described in https://addons-server.readthedocs.io/en/latest/topics/api/overview.html#api-overview-translations.

That being said, the new design isn't particularly easy to use from a client perspective. The problem is that when the requested locale isn't available, we return a different locale. Given that v5 returns data keyed by the locale itself, a client won't be able to retrieve the requested locale in this object:

```
// ?lang=fr and `fr` is available
{ "field": { "fr": "value" } }

// ?lang=fr and `fr` isn't available
{ "field": { "en-US": "value" } }
```

We'd need to return "something" when the requested locale isn't available so that clients can handle that case. Here is what the API v5+ should return instead:

```
// ?lang=fr and `fr` isn't available, but we still have it in the returned object!
{ "field": { "en-US": "value", "fr": null, "fallback": "en-US" } }
```

By returning more information, clients can detect that the request locale isn't available and can use the `fallback` property to know which locale they can use instead.

---

**For QA:** this comment describes the final design: https://github.com/mozilla/addons-server/issues/16069#issuecomment-737805239

**Comment by eviljeff** [comment]
Does `default` work rather than `fallback`?  i.e.
`{ "field": { "en-US": "value", "fr": null, "default": "en-US" } }`

**Comment by willdurand** [comment]
ah yeah, `default` would work for me too

**Comment by bobsilverberg** [comment]
I'm not sure if we can come up with a better design, but I wanted to point out that
```json
{ "field": { "en-US": "value", "fr": null, "default": "en-US" } }
```

doesn't seem ideal because we are expecting an object with a set of key:value pairs which are `lang`:`value`, and we are trying to shoehorn this knowledge about a default lang into that. Just looking at the structure, it looks like `default` is a `lang` with a value of `en-US`.  I wonder if we need something more like:
```json
{ "field": { "langs": { "en-US": "value", "fr": null }, "default": "en-US" } }
```

**Comment by eviljeff** [comment]
> 
> 
> I'm not sure if we can come up with a better design, but I wanted to point out that
> 
> ```json
> { "field": { "en-US": "value", "fr": null, "default": "en-US" } }
> ```
> 
> doesn't seem ideal because we are expecting an object with a set of key:value pairs which are `lang`:`value`, and we are trying to shoehorn this knowledge about a default lang into that. Just looking at the structure, it looks like `default` is a `lang` with a value of `en-US`. I wonder if we need something more like:
> 
> ```json
> { "field": { "langs": { "en-US": "value", "fr": null }, "default": "en-US" } }
> ```

what would the multi-language (i.e. no `?lang=xx`) response be?  The same but without the `"fr": null`?

**Comment by bobsilverberg** [comment]
> 
> what would the multi-language (i.e. no `?lang=xx`) response be? The same but without the `"fr": null`?

I suppose so. I wonder if we even need `"fr": null` in the `?lang=xx` response?  The client is going to try to find `fr` in the response, and when it finds it's `null`, then it will look for the value for the `default` lang, so having `"fr": null` doesn't really give us any more information than just leaving `fr` out of the object.

**Comment by diox** [comment]
I kinda like the `{ "field": { "en-US": "value", "fr": null, "default": "en-US" } }` format because it's less verbose and compatible with what we already have for all languages (no `lang` parameter). Breaking compatibility for both at once seems a bit rough... If it's just a matter of ensuring the fallback info isn't conflicting with anything, maybe we could use `_fallback` instead ?

Worth noting as well that technically, for add-ons, the information is already in `default_locale` in the response (that might not be true for all response types currently - for some we don't even have a dynamic fallback and always use `en-US`)

**Comment by eviljeff** [comment]
fwiw, the `default` value should be the same as the `default_locale` value in the parent object, but this would be more explicit.

**Comment by willdurand** [comment]
I think we need `"fr": null` because requesting `lang=fr` should return a result with `fr`, even if the value is `null`.

**Comment by eviljeff** [comment]
`{ "field": { "en-US": "value", "fr": null, "_default": "en-US" } }` wfm

**Comment by willdurand** [comment]
> `{ "field": { "en-US": "value", "fr": null, "_default": "en-US" } }` wfm

+1

**Comment by AlexandraMoga** [comment]
I've compared the responses of the detail, version detail and search api in `v4` and `v5`, with add-ons containing translated fields and I did not find any functional issues. 

Below are some examples to illustrate the changes:

1. example with translated fields returned in `v4` vs `v5` - requested locale available:

`/addons/addon/620337/?lang=de`

_v4_
```
"release_notes": "Version notes in DE"
```
_v5_
```
"release_notes": { "de": "Version notes in DE" }
```
2. example with requested locale missing for a particular field:

`/addons/addon/620337/?lang=fr`

_v4_
```
"release_notes": "Version notes in en-US"
```
_v5_
```
"release_notes": {
            "en-US": "Version notes in en-US",
            "fr": null,
            "_default": "en-US"
        }
```
When the `lang` parameter is not specified, we return all the available translations. 

@eviljeff could you please clarify if the following is expected:

- for an add-on with a `default_locale` different than `en-US`,  which also has translated fields for `en-US`, if a non-existent locale is requested, we default to showing the `en-US` translations - https://addons-dev.allizom.org/api/v5/addons/addon/620338/?lang=foo
If a translation in `en-US` is not available, then we return the `default_locale` values - https://addons-dev.allizom.org/api/v5/addons/addon/620343/?lang=foo

**Comment by eviljeff** [comment]
> @eviljeff could you please clarify if the following is expected:
> 
>     * for an add-on with a `default_locale` different than `en-US`,  which also has translated fields for `en-US`, if a non-existent locale is requested, we default to showing the `en-US` translations - https://addons-dev.allizom.org

I wasn't seeing what you described, but when I looked carefully I saw for _some_ of the fields I was getting my browser's locale (`en-GB`).  What is happening is `foo` locale doesn't exist in AMO's list of valid locales, so when AMO is setting the current requests locale it's falling back to your browser's `HTTP_ACCEPT_LANGUAGE` header (`en-GB` in my case, `en-US` I would guess for you based on your comments).  I.e. what you see for https://addons-dev.allizom.org/api/v5/addons/addon/620338/?lang=foo is actually https://addons-dev.allizom.org/api/v5/addons/addon/620338/?lang=<your browser's HTTP_ACCEPT_LANGUAGE>.  I was seeing a mix of `default`s because not all of the fields have a `en-GB` translation.

If you try with a valid, but unused (by the addon) locale, e.g. `ar`, you get the response as expected: https://addons-dev.allizom.org/api/v5/addons/addon/620338/?lang=ar

**Comment by AlexandraMoga** [comment]
> What is happening is `foo` locale doesn't exist in AMO's list of valid locales, so when AMO is setting the current requests locale it's falling back to your browser's `HTTP_ACCEPT_LANGUAGE` header (`en-GB` in my case, `en-US` I would guess for you based on your comments).

Just to point out that I did not use the Browser to test the API. I've been using Postman and `curl` in parallel and, in case of an unsupported AMO locale - `foo`- the response always defaults to `en-US` for https://addons-dev.allizom.org/api/v5/addons/addon/620338/?lang=foo. 



> If you try with a valid, but unused (by the addon) locale, e.g. `ar`, you get the response as expected: https://addons-dev.allizom.org/api/v5/addons/addon/620338/?lang=ar

Yes, this is correct. If the `lang` parameter is set to any of the locales supported by AMO but not directly supported by the add-on in question, the API will return the values of the addon's `default_locale`  - for  https://addons-dev.allizom.org/api/v5/addons/addon/620338/?lang=ar would be `de`.
