### ISSUE TITLE
migrate the addons that use icons from the preselected list

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16114]
follow up for #10090 - the icon selection has been removed, but to completely remove the feature we need to give each add-on that chose one of the icons a copy of it.

A quick redash query shows 471 approved and enabled add-ons (and another 2446 in various other states that are potentially usuable by the developer, i.e. not deleted/disabled, if we want to fully support them)

**Comment by ioanarusiczki** [comment]
@eviljeff I don't know if I understood this correctly but I've checked addons to see if custom addons are still displayed on detail pages or search results and I found a couple. 
Examples:
https://addons-dev.allizom.org/en-US/firefox/addon/webmail-ad-regression2/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured
https://addons-dev.allizom.org/en-US/firefox/addon/copy-me-that/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
https://addons-dev.allizom.org/en-US/firefox/search/?category=appearance&sort=recommended%2Cusers&type=extension

After replacing the old pre-selected custom icons with an image the preselected one is no longer displayed into dev hub (cannot be re-used) but this behavior is also present on AMO stage.

**Comment by eviljeff** [comment]
@ioanarusiczki I hadn't actually run the migration task yet.  I've just done it now and the addons you've mentioned still have the same icon so it appears to have worked, (it's not the same file - the icon is now a custom upload, served from `/user-media/`)

**Comment by ioanarusiczki** [comment]
@eviljeff Ok, then it should be fine on AMO dev.
An example, location : https://addons-dev-cdn.allizom.org/user-media/addon_icons/618/618623-64.png?modified=2f3e8d67

Perhaps on -stage you did not run the migration task yet because it shows me a different location: 
https://addons-stage-cdn.allizom.org/static/img/addon-icons/security-64.png

this is the addon: https://addons.allizom.org/en-US/firefox/addon/clear-cache-uncomp/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by eviljeff** [comment]
@ioanarusiczki I've just run the migration task on stage too

**Comment by ioanarusiczki** [comment]
@eviljeff Stage looks good now.
It's https://addons-stage-cdn.allizom.org/user-media/addon_icons/617/617937-64.png?modified=d6b1b5ec

Verified on AMO dev and stage - FF84(Win10).
