### ISSUE TITLE
User can still access the account using an older email account

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1612]
## steps to reproduce:
1. Using Fxa, sign into your amo-dev account
2.  Navigate to https://addons-dev.allizom.org/en-US/firefox/users/edit
3. Change the email address and click save
4. Confirm the change in email address
5. Sign out
6. Sign in using the older account

## expected behavior:
After email confirmation, the user shouldn't be able to sign in using the older account

## actual behavior:
The user is able to sign in using the older email

## screencast: 
http://screencast.com/t/p7ReOTLO

**Comment by mstriemer** [comment]
This is because the `fxa_id` still matches even though the email address changed. Since we redirect new users to FxA you get redirected there even after the +94 account doesn't exist, then when you return from FxA the `fxa_id` matches and the email address is updated to match FxA.

I can think of two solutions.

1. Prevent the user from changing their email address and force them to change it through FxA (not currently supported I believe). This would work with https://github.com/mozilla/olympia/issues/1609 if FxA starts to support changing emails.
2. Allow the user to change their email address and don't automatically copy over the value from FxA after the initial migration/creation.

I'm leaning towards 1 since it seems easier but people might want to change their email address which leaves us with option 2 or getting FxA to support changing email addresses.

They might also want to have amo go to `me+amo@example.com` so they can filter easily or something and that wouldn't make sense with forcing the AMO email to match the FxA email.

So we should probably do 2 but for now I think 1 will suffice.

**Comment by krupa** [comment]
The option to update emails is removed for FxA users. See https://www.dropbox.com/s/8c4jlvi0rlyx5gt/Screenshot%202016-02-11%2010.53.10.png?dl=0
