### ISSUE TITLE
Banning a user isn't reflected in Salesforce

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16188]
When we delete a user normally (they delete their account on AMO or via FxA) we trigger a sync with Basket which updates the data in Salesforce.

It doesn't happen when a user is banned, because it happens in bulk bypassing post save signals. So we need to manually add the sync trigger.

**Comment by AlexandraMoga** [comment]
Banned users are now marked as deleted in Salesforce. Here is an example:

[User](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10642153/change/) banned in AMO admin:
![image](https://user-images.githubusercontent.com/31961530/103007687-88c68d00-453c-11eb-8716-13b88e065d15.png)

-----
User marked as Deleted in Salesforce:
![image](https://user-images.githubusercontent.com/31961530/103007720-924ff500-453c-11eb-8cb0-1e66bb133781.png)

This issue is verified fixed on AMO -dev.
