### ISSUE TITLE
Extension approved, NOT published for over a week?

### ISSUE THREAD

**Issue by PELock** [mozilla/addons-server#16259]
### Describe the problem and steps to reproduce it:

1. I have published a new version of my extension https://addons.mozilla.org/en-US/firefox/addon/social-media-bot-auto-clicker/ (v1.3.0)
2. It's been approved
3. I have updated the descriptions manually at the developer panel

### What happened?

1. The submitted version is marked as v1.3.0
2. It's listed here https://addons.mozilla.org/en-US/firefox/addon/social-media-bot-auto-clicker/versions/ but it's listed as an older version than v1.2.9 (with the older date)?
3. In dev panel I can see:
 
Listed Version: 1.2.9 ?
Next Listed Version: 1.3.0 ? (with the tooltip that it isn't live on the website yet)

In recent activity in dev console I see:

Social Media Bot - Instagram, Twitter, SoundCloud properties edited. (descriptions updated)
1 week, 2 days ago by PELock

Social Media Bot - Instagram, Twitter, SoundCloud Version 1.3.0 approved.
1 week, 2 days ago by Mozilla Firefox

### What did you expect to happen?

If the extension was approved I would expect it to be available as the current version on the main site

### Anything else we should know?

Screenshots from dev panel console:

https://addons.mozilla.org/en-US/firefox/addon/social-media-bot-auto-clicker/

**Comment by wagnerand** [comment]
All statuses look correct to me, @diox mentioned this is a known but unidentified rare bug. I don't recall it at the moment, so I am not sure when we've seen it last time or if there is a related bug.

I believe mat suggested to take a look at logs to see if we can spot anything.

**Comment by diox** [comment]
From the activity log, I have a good idea of what happened:
- The version was approved at 2020-12-27 01:00 exactly
- The developer mades changes in devhub at exactly the same time (and also one minute, two minutes and four minutes before - it was basically approved just as they were updating reviewer notes and uploading source code)

So my guess is that one of the forms (or all of them...) in devhub that modifies the add-on saves all fields (django's default behavior) and it overrode `_current_version` with the value from before the approval.

**Comment by PELock** [comment]
I did upgrade the descriptions like I always do (with version changes detail description), right after it was approved, maybe its some concurrency bug?

**Comment by diox** [comment]
Yes. Between the database transactions, replication, and the fact that devhub forms potentially override data that has since been modified, it's possible to end up in this situation if everything happens in the same super short period of time.

I am looking into fixing this, but this is not trivial...

In the meantime, the simplest workaround for you would e to resubmit a new minor version with no extra changes besides the version number, and upload sources of that as normal. Once approved, the latest version should be ok.

**Comment by diox** [comment]
QA: this is tricky to test, since it depends on a race condition, but at least you can ensure there are no obvious regressions by just using the site normally, submitting / editing / approving add-ons & versions.

**Comment by ioanarusiczki** [comment]
@diox I verified this on AMO dev - could not reproduce the issue with FF84(Win10). 

Tricky bug indeed :
I tried really hard to get it on AMO stage and I finally have, after I edited the description field, I was on the rev tools page and the dev hub page and clicked "Save" and "Save Changes" very quickly one after another. 
I tried to save the approval and edit the notes from the version page - with this scenario I could never reproduce it on stage.

I'll give @AlexandraMoga's sample from stage because mine is no longer a proof (I continued testing on the same addon and versions reappeared in their correct order).  

https://addons.allizom.org/en-US/developers/addon/3%E2%84%A8-%E5%A4%96%E3%81%AF%E3%82%82%E3%81%86-%E6%9A%97%E3%81%84/versions

**Comment by PELock** [comment]
I have pushed the v1.3.1, will let you know how it went :)

**Comment by PELock** [comment]
It went just fine this time https://addons.mozilla.org/pl/firefox/addon/social-media-bot-auto-clicker/
