### ISSUE TITLE
correctly handle outgoing'ing translated fields in api/v5

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16268]
looks like if we specify a lang, e.g. `/api/v5/addons/addon/tasty-sushi/?lang=en-GB` then the response ends up as:
```json
"homepage": {
    "url": {
      "en-US": "https://goog.gl",
      "en-GB": null,
      "_default": "en-US"
    },
    "outgoing": {
      "en-US": "https://outgoing.prod.mozaws.net/v1/19edd172a6b04a284719f9ba8bded9e04f10bc5fa13a91c019997c0c72d996/https%3A//goog.gl",
      "en-GB": null,
      "_default": "/"
    }
  },
```
Because we try to outgoingify the `_default` key too.  We shouldn't try to pass `_default` through outgoing because it's not a url.

**Comment by AlexandraMoga** [comment]
I've verified the issue on -dev with the `v5` and `v4` APIs. With `v4`, the behavior is the same as before, i.e. if the `wrap_outgoing_links` is passed, an outgoing url is returned (where applicable), otherwise, the original url is returned.

In `v5`, we have the following structure - the `"_default"` value is now the `default_locale` value instead of `"/"`:


Request: https://addons-dev.allizom.org/api/v5/addons/addon/donottrackplus/?lang=zh-CN

```
"support_url": {
        "url": {
            "en-US": "https://www.abine.com/support",
            "zh-CN": null,
            "_default": "en-US"
        },
        "outgoing": {
            "en-US": "https://outgoing.stage.mozaws.net/v1/13748512fcaf55e6a42a3b0cf3b2db707fd987fbe1b83f881c58e75f3bd78460/https%3A//www.abine.com/support",
            "zh-CN": null,
            "_default": "en-US"
        }
    }
```

@eviljeff  for the `contributions_url` field, the object construction is different from other translated fields with an outgoing property: there are no `"zh-CN": null` and `"_default"` values for the `"url"` and the `"outgoing"` fields. Is there a reason behind this?

```
"contributions_url": {
        "url": "https://patreon.com?utm_content=product-page-contribute&utm_medium=referral&utm_source=addons.mozilla.org",
        "outgoing": "https://outgoing.stage.mozaws.net/v1/5835ca725738732044b51accb114a74143545bd414641e44fa2cd02a23589470/https%3A//patreon.com%3Futm_content=product-page-contribute&utm_medium=referral&utm_source=addons.mozilla.org"
    }
```

**Comment by eviljeff** [comment]
> @eviljeff for the `contributions_url` field, the object construction is different from other translated fields with an outgoing property: there are no `"zh-CN": null` and `"_default"` values for the `"url"` and the `"outgoing"` fields. Is there a reason behind this?

`contributions_url` isn't localizable so there's only one value.
