### ISSUE TITLE
update DRF setting DEFAULT_VERSION

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16318]
We recently changed policy to have v5 of the AMO be the standard api version.  The django REST framework setting `DEFAULT_VERSION` is set to `v4` currently, which mainly affects tests.  That should be updated too so we're testing by default on the version we use in addons-frontend.

**Comment by AlexandraMoga** [comment]
@eviljeff is QA required for this issue?

**Comment by eviljeff** [comment]
other than tests, it touched the shelves (#14871) admin (the form validation in the admin) so better check that's still working okay.

**Comment by AlexandraMoga** [comment]
@eviljeff while trying to verify #16312 I found out that I can no longer add or edit a shelf through the admin [/shelfmodule/](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/add/) because of the following form error generated by the Criteria field:

![image](https://user-images.githubusercontent.com/31961530/104930479-def8e580-59ad-11eb-88ab-e0f1f3f2c0bf.png)

The API request used in the field should return data - https://addons-dev.allizom.org/api/v5/addons/search/?sort=users&type=extension

I've tried other combinations as well and I'm getting the same error. 

I've received a valid error message when I've tried to use Endpoint `search-themes` with a `type=extension` Criteria parameter:
![image](https://user-images.githubusercontent.com/31961530/104931657-6004ac80-59af-11eb-9067-9cba67e27f08.png)

The message is also correct for the inverse combination: Endpoint `search` with Criteria parameter `type=statictheme`

I'm raising the issue here but I'm not sure if the regression is caused by this patch or for the one meant for #16312

**Comment by AlexandraMoga** [comment]
I've reverified the shelves module and now I'm able to add new shelves and edit existing ones. I've tried various Endpoint and Criteria combinations, with valid and invalid data and the form responded with the appropriate errors.
