### ISSUE TITLE
Cache all API non-authenticated responses for 3 minutes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16311]
We'd like for consumers of the api to be able to (optionally) return cached results for some of the api endpoints for a short period on the server side for performance.  The collections and addons/search endpoints are the most accessed (because they're shown on the AMO landing page).

**Comment by diox** [comment]
Note that https://github.com/mozilla/addons-frontend/issues/9996 will change what the homepage uses.

This strategy could still be useful for some endpoints though. We could also consider caching the responses in memcached for a short time (not for authenticated requests, and not for responses too large)

**Comment by diox** [comment]
The [response size problems we've experienced recently](https://github.com/mozilla/addons-server/issues/16102#issuecomment-739895163) need to be addressed for this. I've been trying to find a generic solution to this. Swapping the `Response` for an `HttpResponse` is a bit tricky to do in a generic way, so the more APIs we cache the more annoying it'll be to maintain. 

Paths I've explored so far:
- Fixing this in DRF. I filed https://github.com/encode/django-rest-framework/issues/7704 and I'm waiting for feedback
- Swapping `Response` class with our own, that would remove `data` when the object is pickled. Unfortunately DRF doesn't let you do customize the `Response` class used, so we'd have to explicit implement `list()`, `get()` etc, or monkeypatch the existing class.
- Customizing the renderer to avoid this. Doesn't work, renderers in DRF don't receive the response object, only the data.
- Having a custom [`post_render_callback`](https://docs.djangoproject.com/en/2.2/ref/template-response/#post-render-callbacks) on every cached API response to remove the `data` before it gets pickled. Doesn't work because you can't ensure the order, so the callback may be called after the cache one (we could find ways to make it work but it'd be incredibly fragile, order isn't guaranteed)

**Comment by diox** [comment]
Radical shift: we're considering caching all API endpoints instead, with the following limits:
- GET requests only
- 20x and 30x responses only
- Un-authenticated requests only (no `Authorization` header)
- Query string escape hatch like `cache=0` or `disable_caching=1`, something like that
- v5 API only for now

Similar to what we already do for service.a.m.o. we'd be doing this at the nginx level, bypassing addons-server completely. I'll open a new bugzilla bug for ops, but keep this opened for now just in case.

**Comment by diox** [comment]
From discussions with ops, we want to try having caching handled by nginx but caching duration set by addons-server, by returning `Cache-Control` headers. So we'll need to implement that logic, probably through a middleware.

**Comment by diox** [comment]
QA: with this change, all non authenticated API requests are going to be cached by default. The basics are described in  https://github.com/mozilla/addons-server/issues/16311#issuecomment-769256204 and should be enough to test it, but there are some subtle technicalities to keep in mind:
- There is a both a client-side cache and a server-side one. Each has a 3 minute duration. It's in theory possible for something to be cached for ~ 6 minutes as a result, depending on when expiration kicks in on both sides.
- Client side caching is handled by the browser (response will have the `Cache-Control` header with a `max-age` in seconds) but sometimes the server side caching will not immediately kick in - that's normal, due to how it's set up. The `X-Cache-Status` header indicates if the response was coming from the cache on the server side (`HIT`) or not (`MISS`)

**Comment by AlexandraMoga** [comment]
@diox I've tried to cover most of our API endpoints and used the browser, Postman and curl in parallel to compare the results. 
I was able to see the cache working most of the time and the 3 minutes cache duration was more or less accurate.

Looking at the Response headers for a request, I could see the following: first API request for a particular endpoint => `X-Cache-Status` is a `MISS`; for following requests `X-Cache-Status` is a `HIT`; after ~3 minutes `X-Cache-Status` will be `EXPIRED`. The `EXPIRED` status is returned several times before a new `HIT` happens.


I have also encountered some issues:
- I've seen cached responses returned for authenticated requests. Below is an example with the `/search/` api, but it happens with other endpoints as well: 
  - authenticated user sends a search request -> make a note of the number of add-ons returned -> set one of the returned add-ons as invisible -> repeat the search request and notice that the number of add-ons returned hasn't changed

- response values fluctuate - for example in the `/detail/`, `/ratings/` or `/collections/` api - both for authenticated and unauthenticated users. This won't happen 100% of the time, but below is an example of how I was able to reproduce with an add-on detail page:
  - open an add-on detail page and check the summary -> leave the page open for several minutes (more than 3) -> refresh the page -> change the add-on summary in devhub -> refresh the add-on detail page and check the summary again -> keep refreshing and observe how the summary fluctuates between the previous and the current value
  - I've also seen this behavior by directly calling the api (Postman, curl) and the `X-Cache-Status` was `HIT` for both summary values retuned
  - here is how it looks in the browser:
 ![6r5Mqdzrbp](https://user-images.githubusercontent.com/31961530/108531876-e2023100-72df-11eb-9852-433d9dfd0cf1.gif)

**Comment by diox** [comment]
I've seen those issues as well and raised that with ops (we're not going to activate caching on stage & prod yet, only the headers to ask browsers to keep caching, not the server-side cache).

**Comment by diox** [comment]
ops fixed the issue with authenticated requests getting cached responses, please retest.

Regarding the response values fluctuating, it doesn't seem out of the ordinary if it eventually settles down after a few minutes.

**Comment by AlexandraMoga** [comment]
> ops fixed the issue with authenticated requests getting cached responses, please retest.

Authenticated users are no longer receiving cached responses - they can see updates as soon as they've occurred. The `Cache-Control` header is not present in the response and the `X-Cache-Status` is `BYPASS`



> Regarding the response values fluctuating, it doesn't seem out of the ordinary if it eventually settles down after a few minutes.

The fluctuations usually occur within the ~3 minutes cache time; once the cache expires, only the current values will be returned

Some things that I forgot to mention earlier:
- as expected, 40x responses are not cached - for example, if an unauthenticated user looks at a detail page for an invisible add-on, the API returns a 401; if the add-on is made visible again, the user will immediately receive a 200 response => the 401 response wasn't cached
- only GET requests are cached from what I've seen in my tests - there' no `Cache-Control` response header present in a POST/PUT request

@diox I'm not sure what you mean by this and how it should be tested:
>Query string escape hatch disable_caching=1

**Comment by diox** [comment]
> The fluctuations usually occur within the ~3 minutes cache time; once the cache expires, only the current values will be returned

Ok. So I'm not too worried - cache is refreshed in the background, and we serve potentially stale cached responses in the meantime to keep the responses fast.

> @diox I'm not sure what you mean by this and how it should be tested:
>>  Query string escape hatch `disable_caching=1`

If the query parameter `disable_caching=1` is present, the request should not be served from cache.

**Comment by AlexandraMoga** [comment]
Ah, right. I didn't think to use `disable_caching=1` as a query parameter. So, in this case, the `Cache-Control` header is not present in the response and the `X-Cache-Status` is `BYPASS` - same as for authenticated requests.

**Comment by diox** [comment]
Sound good then. Small inconsistencies during the 3 minutes cache time when changes occur are fine.

**Comment by diox** [comment]
@AlexandraMoga one last thing: can you check that the geo-restrictions still work correctly on dev ? Some of the config changes needed could have affected that.

**Comment by AlexandraMoga** [comment]
The region restriction API is still working. If the detail API is requested by an unauthenticated or a non-admin user from a region where the add-on is restricted we return a 451 (there is no `Cache-Control` for this response).
If I have a cached response for an add-on detail which becomes restricted while my cache is still valid, I will receive the 451 status only after the cache expires (again, in ~3 mins time). This seems to be the correct behavior.

**Comment by bqbn** [comment]
I updated the Nginx config to include the country code in the cache key, and deployed it to -dev.

However, I haven't tested and see how it works because I don't know a URL that can return 451 for me.

**Comment by AlexandraMoga** [comment]
I've repeated the tests and the results are as follow:

1. Requests come from the same country: 
 - detail API accessed from a country where the add-on is NOT restricted => 200 response, cache HIT
 - add-on becomes restricted in the country where the request originated
 - request is resent from the same country =>200 response, cache HIT until the cache expires (~3 mins), afterwards response status changes to 451. I believe this is expected, considering that the country code has not changed between requests, so the cache should act as normal
 
2. Requests come from different countries:
- detail API accessed from a country where the add-on is NOT restricted => 200 response, cache HIT
- detail API is immediately  accessed from a country where the add-on IS restricted => 451 response status, no cache. The behavior seems to be correct now.

I've used an add-on restricted in DE and FR for testing: https://addons-dev.allizom.org/api/v5/addons/addon/620403/

**Comment by diox** [comment]
That sounds good. Everything seems OK for me too as well now.

**Comment by bqbn** [comment]
We've deployed the Nginx changes to -stage environment. Please test it and let us know how it works.

**Comment by AlexandraMoga** [comment]
I've tested stage and the cache seems to work there as well. The same observations and results mentioned for -dev are valid for stage too.
