### ISSUE TITLE
Investigate `isort` and how we could use it

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#16458]
We added then removed `isort` and it would be nice to understand why we couldn't fully leverage `isort` in the past (apparently related to issues with the test files). Now that we have black, let's see if we could use `isort` in an automated way (i.e. it shouldn't be manual and it should be verified in CI).

**Comment by diox** [comment]
Original problem with `isort` was that the module, which was used by pytest-isort, changed `defaultsystemencoding`. Back when we were in python 2, this was incredibly bad, it would lead to all kinds of breakage. Generally not the sort of things you expect in a module. As such, we couldn't enable pytest-isort because as soon as you'd import `isort` the tests wouldn't be reliable anymore. The command could still be used manually though.

Lots of time has passed since then, some people complained at the time, and everybody is using Python 3 nowadays anyway, so the module is probably safe now. And even if it's not, we could still use the command and avoid the module.
