### ISSUE TITLE
Return grouped ratings with addon detail response

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16459]
The addon detail page calls https://addons.mozilla.org/api/v5/addons/addon/{slug}/ but then has to call https://addons.mozilla.org/api/v5/ratings/rating/?addon={addonId}&show_grouped_ratings=true just for the group rating counts. Given this is a relatively small amount of data we could (optionally) return it with the add-on detail response.

something like:
https://addons.mozilla.org/api/v5/addons/addon/{slug}/?show_grouped_ratings=true

**Comment by AlexandraMoga** [comment]
The add-on detail API returns now a `grouped_counts` property when the `show_grouped_ratings = true` parameter is passed. 


https://addons-dev.allizom.org/api/v5/addons/addon/3006/?show_grouped_ratings=true
```
"ratings": {
        "average": 4.3619,
        "bayesian_average": 4.361576634593846,
        "count": 4110,
        "text_count": 4104,
        "grouped_counts": {
            "1": 307,
            "2": 119,
            "3": 202,
            "4": 573,
            "5": 2896
        }
```

Without the parameter, the detail API returns the normal rating object, without the `grouped_counts` property.

This issue is verified fixed on -dev.
