### ISSUE TITLE
Return latest rating by logged in user with addon detail?

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16457]
The addon detail page calls https://addons.mozilla.org/api/v5/addons/addon/{slug}/ and then https://addons.mozilla.org/api/v5/ratings/rating/?user={userId}&addon={addonId} for the current user's rating if logged in.

We should investigate if it's practical to return this extra data with the addon detail API.

TBC: what rating detail is needed from https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#detail

**Comment by bobsilverberg** [comment]
Unfortunately this is kind of complicated on the frontend side. We really need most of the data for the review (and not just the score) for a couple of reasons:

1. If the user has submitted a review then we display it in the area where they can see their current rating. We display the body text, the byLine (which includes the date it was posted), and even a reply if one exists, so we need quite a few fields and pieces of data.
2. The way we store reviews in the frontend is also complicated, but, unless we change it dramatically (which I don't think we want to do), a review that is retrieved as part of an add-on detail response should be stored the same way. We definitely do not want to store two instances of an add-on review, especially as this is something that a user can edit at any time. Therefore, we really need to have *all* of the fields that we need for a review to be returned to us, so we can store them.

I do think that the number of fields that we're currently getting back from the API may be more than we need, so we can probably pare that down a bit, but I don't think we can zero in on just exactly what the detail page needs because that would mess with the way we store reviews.

@willdurand Can you please take a look at what I've said above and let me know if you agree, or if you think there's a different approach we can take?

**Comment by eviljeff** [comment]
refocusing this issue on the latest rating for the current user and filed https://github.com/mozilla/addons-server/issues/16459 for the straightforward grouped ratings.

**Comment by eviljeff** [comment]
I'll hold my conclusion until @willdurand has replied but I'd lean towards wontfix'ing this - it only affects logged in users (so not SEO related) and the vast majority of logged in users won't have left a rating for all the addon detail pages they visit so they wouldn't see a difference.  IMO we can make it as an XHR call after the page loads.

**Comment by bobsilverberg** [comment]
I agree with this assessment. The only piece that’s less than correct is the fact that a logged in user will still generate the API call for each detail page, even if they haven’t recorded a rating.

**Comment by eviljeff** [comment]
> The only piece that’s less than correct is the fact that a logged in user will still generate the API call for each detail page, even if they haven’t recorded a rating.

True, I meant more they wouldn't particularly notice if the component was unpopulated with data on page load if we filled it with a data from an XHR call after (I rearranged what I what I wrote afterwards so it was referring to the following sentence)

**Comment by eviljeff** [comment]
I'm taking a lack of reply as agreement 😬 and closing
