### ISSUE TITLE
settings.LANGUAGES should always have been a list of tuples, not a dict (django3.2 fix)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16479]
`settings.LANGUAGES` is a list* of tuples https://docs.djangoproject.com/en/2.2/ref/settings/#languages and we've been setting it to dict [forever](https://github.com/mozilla/addons-server/commit/723ab7a6ec39ad41b2f7d1c02178cdc4018c65da)  https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L185:L186 😐️

In django3.2 there's a system check that errors because the  `(x, y) in LANGUAGES` doesn't work for dicts like it would for list/tuple.

*it was a tuple of tuples back in django1.8 and before, which is fine as lists and tuples are pretty compatible; dict, not so much.

**Comment by AlexandraMoga** [comment]
@eviljeff does this require QA?

**Comment by eviljeff** [comment]
it should be a transparent change, and would have been fairly obvious if things broke (the language codes in urls on addons-server wouldn't be working).  For specific areas to check - places where we display the names of languages, like in devhub when you can add/change localizations for the add-on metadata.

**Comment by AlexandraMoga** [comment]
I've checked that language codes are working correctly in devhub and reviewer tools pages. For devhub, I've also checked that the locales available in the "Localize for" and "Default locale" lists are correctly displayed. 
Another tested area is the Language picker available in the footer.

This issue is verified fixed on -dev.
