### ISSUE TITLE
Return translated fields for the Primary and Secondary hero shelves

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#16515]
The data returned from the [`hero`](https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html#get--api-v5-hero-) endpoint does contain translated data, but it is returned in simple strings, as opposed to most other translated fields which are returned as objects. This should be updated in the API, which will also require a change on the frontend.

**Comment by ioanarusiczki** [comment]
@eviljeff Following https://github.com/mozilla/addons-server/issues/8712#issuecomment-769912249, the test results on -dev are below and I bolded the results that raise question marks: 

1. Results for Primary hero "description" field:
I used for testing sample addon "id":7560,  with "fr" set as default language. 

1.1 The primary "description" field with a custom description set in the admin:
- v4,v5, lang specified and translation is available - returns the value of the custom description added in the description admin field for that locale.
- v4,v5, lang specified but translation is not available - returns the value of the custom description added in the description admin field for en-US.
- v4,v5 lang not specified or invalid, unsupported - returns the description admin field for en-US. I don't know if that's correct because `fr` is set as default in dev hub. **Perhaps it should be "fr" ?** 
-v4 lang is not specified - accept language header is "it"  - returns "it" because the addon has translated strings for these languages
- v5 lang is not specified - accept language header is "it"  - returns the description in "en-US" and "it".  **I don't know if that's alright as it is, or should it be only "it" ?** 

1.2 The primary "description" field without a custom description set in the admin when there are translated strings provided by the summary of the add-on (the same addon 7560, with "fr" set as default language):
- v4,v5, lang specified and translation is available - returns the value of the language specified. 
- v4,v5, lang specified but translation is not available - returns the default locale set by the developer - which is "fr" in this case.
- v4 lang not specified - returns the summary in en-US.
- v5 lang not specified - returns all translated summaries (description in all languages). 
- v4/v5 lang not supported - returns the summary in the default language which is "fr".
- v4/v5 lang is not supported - and I use an `accept-language` header other than the default (fr), a lang in which the summary translations are available (de,it, en-US) - returns the default "fr" **Perhaps the accept-language should be returned here, "de", "it" or "en-US"?** 

2. Results for Secondary Hero "description" field: 
"description", "headline" and "cta.text" fields from the secondary hero->
- v4,v5 with a specified lang in which translation exists (de) - returns one language (de)
- v4,v5 with a specified lang that does not have a translation - returns en-US
- v4,v5 with not specified, not supported or invalid lang - returns en-US
- for lang not specified using an accept header lang other than en-US (de) and "de" translations are available: 
   v4 returns strings in "de"
   v5 returns strings for  "de" and "en-US"  **Should v5 return only the accepted header "de" without "en-US" ?** 
- for unsupported lang using an `accept-header` lang other than en-US(de) and "de" translations are available -
   v4,v5 return translations in en-US **Should it be "de" instead of en-US?**

**Comment by eviljeff** [comment]
> @eviljeff Following [#8712 (comment)](https://github.com/mozilla/addons-server/issues/8712#issuecomment-769912249), the test results on -dev are below and I bolded the results that raise question marks:
> 
> 1.1 The primary "description" field with a custom description set in the admin:
> 
> * v4,v5 lang not specified or invalid, unsupported - returns the description admin field for en-US. I don't know if that's correct because `fr` is set as default in dev hub. **Perhaps it should be "fr" ?**

In a meeting @bobsilverberg expressed concern that the default locale of the add-on should be taken into account (like it is in the discovery api) so I didn't add that fallback for the hero shelves.  It's an easy change to make if it's wanted though.

> * v5 lang is not specified - accept language header is "it"  - returns the description in "en-US" and "it".  **I don't know if that's alright as it is, or should it be only "it" ?**

if a lang isn't specified for any API endpoint the caller should expect multiple languages to be returned.

> 1.2 The primary "description" field without a custom description set in the admin when there are translated strings provided by the summary of the add-on (the same addon 7560, with "fr" set as default language):
>
> * v4/v5 lang is not supported - and I use an `accept-language` header other than the default (fr), a lang in which the summary translations are available (de,it, en-US) - returns the default "fr" **Perhaps the accept-language should be returned here, "de", "it" or "en-US"?**

If `?lang-xx` is specified in any api call that becomes the language used for the request/response (accept-language is only used when `?lang=` _isn't_ specified).  If the language set for the request/request is unavailable for the addon then the addon's default locale is returned.
 
> 2. Results for Secondary Hero "description" field:
> * for lang not specified using an accept header lang other than en-US (de) and "de" translations are available:
>       v4 returns strings in "de"
>       v5 returns strings for  "de" and "en-US"  **Should v5 return only the accepted header "de" without "en-US" ?**

same as above, if a lang isn't specified for any API endpoint the caller should expect multiple languages to be returned.

> * for unsupported lang using an `accept-header` lang other than en-US(de) and "de" translations are available -
>       v4,v5 return translations in en-US **Should it be "de" instead of en-US?**

same as above, If `?lang-xx` is specified in any api call that becomes the language used for the request/response ('en-US' is  the default_locale otherwise)

**Comment by ioanarusiczki** [comment]
@eviljeff Thanks for the review.

 Last question: Testing again, only using the accept-header lang -> 
- when a custom description is used for the primary hero addon, accepted language header is set "de", the response is returned in two languages "en-US and "de" for all fields (in primary and secondary). 
- without a custom description used for the primary hero addon and accepted language header is "de" or any other, the response returns for the primary 9 languages (because the summary was translated for 9, that's visible in the admin) and for the secondary is only"de" and "en-US" again. 
Is the 2 expected only? Because I don't see the number of translated languages for secondary or custom description in admin but there's more than two.

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff Thanks for the review.
> 
> Last question: Testing again, only using the accept-header lang ->
> 
>     * when a custom description is used for the primary hero addon, accepted language header is set "de", the response is returned in two languages "en-US and "de" for all fields (in primary and secondary).
> 
>     * without a custom description used for the primary hero addon and accepted language header is "de" or any other, the response returns for the primary 9 languages (because the summary was translated for 9, that's visible in the admin) and for the secondary is only"de" and "en-US" again.
>       Is the 2 expected only? Because I don't see the number of translated languages for secondary or custom description in admin but there's more than two.

yes.  From api docs "Note: when lang is not specified, not all locales will be returned, unlike other translated fields"
