### ISSUE TITLE
Update the Shelf admin to call out the fact that footer_pathname should be left empty unless needing to be overridden

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#16513]
I guess we added it before figuring out the implementation on the frontend, but it doesn't seem like we need `footer_pathname` at all, and there is also a risk that someone will put invalid data into it, which will result in a bug in the frontend.

We can calculate `footer_pathname` in the frontend using `endpoint` and `criteria`. This will work for both `search` and `collections`, and I'm not sure of other use cases for which we wouldn't be able to calculate it.

@eviljeff @jvillalobos @devaneymoz Can any of you think of a use case for creating a shelf where we'd need to manually specify the pathname for the footer? If not, we should remove it from the model.

cc @xlisachan

**Comment by jvillalobos** [comment]
What is `footer_pathname`? If it's the "See more" link, I think we wanted to leave open the possibility to link to blog posts or other material, instead of a search or collection link.

**Comment by bobsilverberg** [comment]
> What is `footer_pathname`? If it's the "See more" link, I think we wanted to leave open the possibility to link to blog posts or other material, instead of a search or collection link.

Yes, it is the destination of the "See more" link. If we were going to link to a blog post or something else, what would be used to populate the shelf with add-ons? Is a use case to use a collection to populate the shelf, but link not to the collection page but rather somewhere else (e.g., a blog post)?

**Comment by jvillalobos** [comment]
An example use case is that we would release a blog post with "Back to School" extensions and then create a collection with those recommendations to accompany it. In that case we would have a shelf populated by the collection and link to the blog post with more details rather than just the collection.

**Comment by bobsilverberg** [comment]
> An example use case is that we would release a blog post with "Back to School" extensions and then create a collection with those recommendations to accompany it. In that case we would have a shelf populated by the collection and link to the blog post with more details rather than just the collection.

Thanks @jvillalobos, that makes sense! In this case we need to keep `footer_pathname`, but I think we should add something to the admin page to indicate that it should be left blank unless the default behaviour needs to be overridden. This will limit the likelihood that an invalid path will be added which will cause an issue on the site.

**Comment by eviljeff** [comment]
I think originally it was intended to be the frontend url to see the rest of the addons in the collection/search (v.s. the api url to get the data) in cases where we wanted extra/different parameters in the api url for the criteria.  (I'm not sure how it'd handle external links - not a problem for the blog, at least, soon)

**Comment by ioanarusiczki** [comment]
@eviljeff 
- the message has been updated to "Can be set to override the default generated footer url/path to see more of the add-ons shown on the shelf. Leave blank otherwise" 
- adding blog pages into the field such as `blog/too-many-open-tabs-extensions-to-the-rescue/`will open the blog pages into a new tab (this has been modified into https://github.com/mozilla/addons-frontend/issues/10721). External links - using a full URL work the same way.
