### ISSUE TITLE
Return translated fields for the Homepage Shelves

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#16514]
We are storing a `title` and `footer_text` for shelves defined in the admin, which are returned via the [`shelves`](https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html#get--api-v5-shelves-) endpoint. When this data is displayed on the front-end, it should be possible to display it in the user's current language. I believe two things are needed:

1. Extract the data for `title` and `footer_text` in order to make it localizable in a similar way that is being done for discovery items.
2. Return `title` and `footer_text` in the API response as translated fields, as opposed to simple strings.

**Comment by eviljeff** [comment]
> Because the `footer_text` needs to be translatable, it also should change from an optional field to a mandatory field in the db and in the admin.

I thought we'd fall-back to generic "See more <title>"?

**Comment by eviljeff** [comment]
i.e. both `footer_text` and `footer_pathname` were optional overrides if the default "See more <title>" and the link to the full search/collection wasn't wanted.

**Comment by bobsilverberg** [comment]
We cannot have a default "See more <title>" because l10n. We cannot concatenate "See more" with the title from the db.

**Comment by eviljeff** [comment]
> 
> 
> We cannot have a default "See more <title>" because l10n. We cannot concatenate "See more" with the title from the db.

Why? We have mixed content all over the site when the addon's content isn't localised.  e.g. the main card at the top is "<addon.name> by: <addon.authors>" where <addon.name> might be localised in the current locale but often isn't and the author display names never are.

**Comment by bobsilverberg** [comment]
> > We cannot have a default "See more <title>" because l10n. We cannot concatenate "See more" with the title from the db.
> 
> Why? We have mixed content all over the site when the addon's content isn't localised. e.g. the main card at the top is "<addon.name> by: <addon.authors>" where <addon.name> might be localised in the current locale but often isn't and the author display names never are.

If there are places where we have that, then it's technically incorrect. We try to avoid that whenever possible, because in a different language it might be incorrect to say "See more", followed by the shelf title. I think for something as prominent as a footer of a shelf on the home page, we'd want it to be as correct as possible.

What do you think @jvillalobos?

**Comment by jvillalobos** [comment]
Are you saying that it isn't possible for localizers to change the position of the title placeholder in "See more <title>"? The title always needs to come last?

**Comment by bobsilverberg** [comment]
I've somehow lost my mind. Forgive me, and ignore me. We can totally make it work with i18n, and we do it all the time. I don't know what I was thinking.

**Comment by ioanarusiczki** [comment]
@eviljeff  
I enabled [3 shelves](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/) from the admin which are present right now on AMO dev homepage. 

The v5, shelves API for `title` and `footer_text`:
- without ?lang specified the strings are returned into "en-US"
- with ?lang specified as parameter, lang=it or lang=de I get the en-US  string( it's _default), with "it" or "de": null. ( the frontend right now has translations in "it" or "de" from what I see, also primary "description" or secondary "headline" are translated in "it" or "de" in this API).  Is this correct?
- with accept-lang other than en-US, I tested with "it" and "de", the strings are returned into "en-US". 
- unsupported or invalid ?lang returns "en-US", "eu":null, "_default":en-US.

**Comment by ioanarusiczki** [comment]
@eviljeff I forgot to add that a request for  https://addons-dev.allizom.org/api/v5/shelves/editorial/ returns the list of all shelves added into the [admin module](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/) providing information about their "title" and "footer_text".

**Comment by eviljeff** [comment]
> ( the frontend right now has translations in "it" or "de" from what I see, also primary "description" or secondary "headline" are translated in "it" or "de" in this API). 

I couldn't find any indication the strings were already translated - what do you see?  

If you use a string that you know was used for a different thing and translated for _that_ (e.g. a primary hero shelf or discovery item) then if should work - gettext translations are matched by the string in English, rather than any sort of object id.

**Comment by ioanarusiczki** [comment]
@eviljeff 
So what I though it that if I use "See more recommended extensions" for title and footer text then I will see it translated as "Mehr empfohlene Erweiterungen ansehen" in "de" because https://addons-dev.allizom.org/de/firefox/ shows this being translated.

I used "They add features to Firefox to make browsing faster, safer, or just plain fun." as the "title" and "footer_text" and I get it translated into "it" or "de" so the results are:
- without ?lang specified the string in "en-US" is returned, which is fine, the docs mention that not all locales will be returned. 
- with ?lang=de, the translation in "de" only is returned. 
- with ?lang=fa, unsupported, or invalid it's "en-US" as _default. 
- with accept-language "de", it's both "en-US" and "de" returned and I think it's ok since I had the same results for the hero fields the previous week. 



I think the API responds as it should in all cases. 
Verified on AMO dev.

**Comment by eviljeff** [comment]
> So what I though it that if I use "See more recommended extensions" for title and footer text then I will see it translated as "Mehr empfohlene Erweiterungen ansehen" in "de" because https://addons-dev.allizom.org/de/firefox/ shows this being translated.

Ah, that's translated in _addons-frontend_ I think.  It's only the strings from addons-server localization that would be already available in the api response.
