### ISSUE TITLE
The homepage shelves list can't be saved because of an incorrectly detected position overlap error

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16559]
### Describe the problem and steps to reproduce it:
1. Open the [/homepageshelves/](https://addons-internal.stage.mozaws.net/en-US/admin/models/discovery/homepageshelves/) admin and create two sets of shelves to alternate between - i.e. two shelves for each position, one shelf Enabled and another one Disabled (as seen in the stage example linked)
2.  Disable the shelf displayed in a certain position and Enable the other shelf available for the same position
3. Save the form

### What happened?
The form can't be saved because of two field validation errors that detect an overlap between the two shelves.

### What did you expect to happen?
There shouldn't be an overlap detected, since there aren't two shelves with the same position Enabled at the same time

### Anything else we should know?
To avoid the errors, you need to delete one of the shelves

![xqqJQqbfrz](https://user-images.githubusercontent.com/31961530/108055630-e9fc6f80-7058-11eb-912b-5a10c4d8894a.gif)

**Comment by bobsilverberg** [comment]
This seems like a bug in the validation. WDYT @eviljeff?

**Comment by eviljeff** [comment]
> This seems like a bug in the validation. WDYT @eviljeff?

It's a bug, though not -that I can see- a new one.  It's likely an edge case with the constraint (`models.UniqueConstraint(fields=('enabled', 'position'), name='position_id')`).  

I assume changing the position too would workaround it.

**Comment by AlexandraMoga** [comment]
@eviljeff changing the position doesn't serve as a direct workaround:


In the below example, I've tried to Disable the first shelf in position 4 and incremented the position for the next shelf from 4 to 5 before trying to Enable it. The error is still displayed for the previous shelf:

![image](https://user-images.githubusercontent.com/31961530/108074385-ceea2980-7071-11eb-80ec-050b535aa837.png)

**Comment by eviljeff** [comment]
yeah, that's unfortunately just how models and saved and database constraints are enforced  - each shelf is saved sequentially, so at the point "Extensions Shelf" is saved "stage_shelf_one" is still `position=4`, `disabled=False`, which breaks the uniqueness constraint.  

(If we used postgres for our database we could use features like conditional and delayed constraints but mysql doesn't support them)

If this is a big enough of a problem we could rewrite to remove the database constraint and check in python code instead (not 100% guaranteed to not end up with inconsistent data because exceptions, etc, but probably not worth worrying about given the tool usage and the impact of two shelves having the same position - i.e. nothing)

**Comment by jvillalobos** [comment]
@devaneymoz has run into this issue every time he's tried to rearrange the shelves, so I think this is worth fixing.

**Comment by eviljeff** [comment]
#17572 drops the constraint. There isn't a straightforward way to reimplement this due to how it's implemented in django admin so it just drops it entirely. If it's a particularly desirable feature we can put the extra work in though - shout up if so.  (The only downside with no constraint is not preventing you from having two shelves with the same position, which would produce an indeterminate order in the API response.)

**Comment by ioanarusiczki** [comment]
@eviljeff Verified on -dev with FF90(Win10). 

![verified](https://user-images.githubusercontent.com/33448286/127295493-ca57e896-7f40-4203-88cf-d06cf438c4bb.gif)
