### ISSUE TITLE
The user is not logged in inside Discovery Pane after he logs in addons.allizom.org using FxA

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#1657]
Steps to reproduce:
1. Open addons.alliom.org and sign in using FxA.
2. Open about:addons

Expected results:
The user is logged in in Discovery pane.

Actual results:
The user is not logged in in Discovery pane.

Notes/Issues:
I've changed the discovery pane to point to the stage server in about:config
extensions.webservice.discoverURL - https://addons-services.allizom.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%
Verified in FF44(Win7) in addons-stage.
Issue is not reproducing in production.
Screencast for this issue: http://screencast.com/t/XJNco8Cvr

**Comment by mstriemer** [comment]
I'm not convinced that this worked prior to FxA on stage since it appears to use the regular cookie that we set but the domains are not correct for that to work on stage.

On AMO we set a cookie with `Domain=.addons.allizom.org` this means it will match `addons.allizom.org` or any of its sub-domains. In production the services URL is `services.addons.allizom.org` so it will get the cookie but on stage it is `services-addons.allizom.org` which is not a sub-domain of `addons.allizom.org` so it does not get the cookie.

**Comment by madalincm** [comment]
We turned off FxA in stage and tried the scenario one more time. The user is still not logged in, so this is not a FxA issue in my opinion. 
Last week the log in inside discovery pane worked in stage.

**Comment by muffinresearch** [comment]
So if you use just `addons.allizom.org` and not `services-addons.allizom.org` this should work. For the reasons mentioned above re: cookie origins we should look to get the services hosts set up more like prod. I'll look to re-open the ops ticket on this.

**Comment by muffinresearch** [comment]
I've re-opened this: https://bugzilla.mozilla.org/show_bug.cgi?id=1245459

**Comment by andymckay** [comment]
The discovery pane is being re-done. With no login. So that's that problem solved.
