### ISSUE TITLE
Search suggestion order varies when searching with the same term

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16610]
### Describe the problem and steps to reproduce it:
1. Load AMO stage
2. Enter a search query - i.e. Flagfox
3. Make a note of the search suggestions returned
4. Search for the same term again
5. Compare the new search suggestions with those in step 3

### What happened?
The search suggestion ordering is different:
![image](https://user-images.githubusercontent.com/31961530/108832688-8b913d00-75d4-11eb-8e17-9f11d5a4239f.png)

### What did you expect to happen?
Search suggestions should be returned in the same order

### Anything else we should know?
- it can take several attempts to notice this inconsistency
- this behavior was observed after the the hard-deletion of legacy files
- I haven't been able to reproduce on prod yet, so this might be caused by the lack of actual data on stage
- I've also observed that the autocomplete results and search results are not displayed in the same order sometimes:
![image](https://user-images.githubusercontent.com/31961530/108831858-5e905a80-75d3-11eb-81c2-11e28117c4db.png)

**Comment by diox** [comment]
I suspect there is something wrong with the [`rescore query`](https://github.com/mozilla/addons-server/blob/13dcd75c970e60b5e237130fdf868fae13f1f526/src/olympia/search/filters.py#L824-L836) that we apply to the top 10 results of a search. That should be investigated, maybe it needs to consider *everything* the initial query did (including weight bumps?), and not just secondary rules. It's been a while since I've looked at this, I forgot how it works behind the scenes.

That being said, the stage data is atrocious for testing this. All the clones, all add-ons having 0 users, this is messing with the relevancy of the results badly.

> I've also observed that the autocomplete results and search results are not displayed in the same order sometimes

This has the same root cause - it's not an inconsistency between the 2 endpoints, but rather an inconsistency at the Elasticsearch level.
