### ISSUE TITLE
Fix sentry-sdk integration in 0.20.0+ 

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16623]
See https://github.com/mozilla/addons-server/pull/16582 for failing tests.

I presume getsentry/sentry-python#992 is causing the test fails as it changes how middleware is patched - it's used for (normal) sync as well as async middleware, despite the description.

**Comment by eviljeff** [comment]
Actually, might be earlier than 0.20.1 as https://github.com/mozilla/addons-server/pull/16536 failed too and that was 0.19.5 to 0.20.0.

**Comment by eviljeff** [comment]
After investigation, it's not the middleware patching changes after all, it's the new `patch_templates` feature ("Django integration now creates transaction spans for template rendering") - monkey patching to noop `sentry_sdk.integrations.django.patch_templates` makes the tests pass again. 

Somehow `patch_templates` means our replacement for django.shortcuts.reverse isn't used (and possibly other patches we do to the django internals).  We _could_ apply the patch to bypass this new feature.  Further investigation needed otherwise.

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some str for qa.
Thanks!

**Comment by eviljeff** [comment]
This was a change that could, potentially, impact anywhere on the site that returns a url within AMO (the /xx-YY/ locale part of the url needs to still be there) both in the api responses and on django served pages.  Not sure of any particular steps to take, but it shouldn't be a noticeable change.

**Comment by eviljeff** [comment]
The only place where there is a slight (probably unnoticeable) change is in the login redirect you would see on /admin/ pages, but it should functionally work the same as before.

**Comment by AlexandraMoga** [comment]
I've verified this issue on stage and looked at the following areas in particular:
- AMO URLs returned in various API endpoints
- switching locales and navigating through and between developer, reviewer and  admin pages
- logging in and out from django served pages 

@eviljeff I have two observations to add:
1. the locale is not preserved when navigating through different admin modules; for example, you start on https://addons-internal.stage.mozaws.net/fr/admin/models/ then select the Addons model => you land on https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/ (/en-US/ being my browser language) . Could be that this has always been the case with the admin pages, but since locales are not really a focus on there, we never looked at them.
2. logging out from django admin triggers a server error - known issue #13200

**Comment by wagnerand** [comment]
> @eviljeff I have two observations to add:
> 
>     1. the locale is not preserved when navigating through different admin modules; for example, you start on [addons-internal.stage.mozaws.net/fr/admin/models](https://addons-internal.stage.mozaws.net/fr/admin/models/) then select the Addons model => you land on [addons-internal.stage.mozaws.net/en-US/admin/models/addons](https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/) (/en-US/ being my browser language) . Could be that this has always been the case with the admin pages, but since locales are not really a focus on there, we never looked at them.
> 
>     2. logging out from django admin triggers a server error - known issue #13200

I can confirm both issues are happening on prod as well.

**Comment by eviljeff** [comment]
@AlexandraMoga unfortunately there was a merge problem so this didn't actually get deployed to dev or stage so you weren't testing after the patch was applied.  I've fixed that now, but any QA will need to be re-completed unfortunately.

**Comment by AlexandraMoga** [comment]
Ok, I'll have another look.

**Comment by AlexandraMoga** [comment]
I've retested and haven't noticed any new issues.
