### ISSUE TITLE
Tracking of Force Disable action

### ISSUE THREAD

**Issue by lafonth** [mozilla/addons-server#16637]
Hello,
initially, Force Disable action was accessible to a really small group of person. 
Today admin reviewers are able to use this action for add-ons that need to be blocked _and_ do not have any approved versions.

In this matter, it would be useful to track this action in the log_activity. 

Thank you,
Hubert

**Comment by diox** [comment]
Could you give more details about what you're asking here ? We already use `CHANGE_STATUS` activity log for this, with the user responsible for the change.

**Comment by wagnerand** [comment]
Ah, that's great. Can we expose that on the reviewer tools page (but not on the developer hub, recent changes)

**Comment by diox** [comment]
We can, but there is a catch: it's used for *every* status change of the add-on, including automatic ones. It's also already displayed in the developer hub, I think.

**Comment by wagnerand** [comment]
Maybe we need to take a step back here and expand on the problem we'd like to solve:

As Hubert mentioned, with a bigger group being able to force-disable add-ons, it would be useful for all admins to see who did that, in order to have a record and to follow up with the admin in case there are questions. We might already record this in some way, but it's not visible. Unless I am mistaken, I can't even find out via django admin at the moment.

**Comment by diox** [comment]
Yeah it looks like at the moment, this is only shown in devhub, in the "Recent changes" page for the add-on. This is accessible to developers, and users with the `Addons:Edit` permission. As mentioned it will display *all* status changes, automatic or manual.

It could be shown in reviewer tools, but this would also include automatic changes, similar to devhub.

It could also be displayed in the add-on admin - currently we don't display activity logs there, but we could (it's technically displayed in the separate `Activity` app in the django admin, but it's just the raw list of all activities, with no filtering and no optimizations of queries so it's not very useful. I don't know if the page even loads on prod)

**Comment by wagnerand** [comment]
> Yeah it looks like at the moment, this is only shown in devhub, in the "Recent changes" page for the add-on. This is accessible to developers, and users with the Addons:Edit permission. As mentioned it will display all status changes, automatic or manual.

I see. We probably shouldn't disclose the name of reviewer that force-disabled an add-on.

> It could also be displayed in the add-on admin - currently we don't display activity logs there, but we could (it's technically displayed in the separate Activity app in the django admin, but it's just the raw list of all activities, with no filtering and no optimizations of queries so it's not very useful. I don't know if the page even loads on prod)

Yes, I checked that page. It takes a bit to load, but it works. As you said, it doesn't have denormalized fields, search or filters, and given the volume, in-page search doesn't work well with pagination.

As an alternative, could we introduce a new activity specifically for force-disabling by a human?

**Comment by diox** [comment]
So, if we want to hide the reviewer from developers, then I don't think we have a choice and we need another specific activity log recorded for force disabling. We would then mark that as a reviewer action, and ensure it's displayed in reviewer tools review log and review pages.

Playing with the django admin is a separate topic IMHO - there are lots of things we could do with the data in the admin, like showing all activity log for a given add-on, optionally filtering by type, user, etc.

**Comment by diox** [comment]
Summary of the changes:
- Force disable/enable action now have their own separate activity log action id. This is recorded with the reviewer responsible for the change, but hidden from developers.
- Change of status activity log, which is triggered from automated status changes, is now recorded with the "Mozilla" user at all times. Developers can still see that one.
- Those logs are now shown in review page with the authorship changes log. Reviewer specific actions (at the moment, only Force Disable/Enable) are shown in bold there.
- The Force Disable/Enable actions are also visible in the general review log in reviewer tools.

**Comment by AlexandraMoga** [comment]
@diox I've verified the Force disable/enable action plus various other reviewer actions and checked the events recorded in the Add-on review log and DevHub Recent activity log. These are my results:

  - Force disable/enable reviewer action is displayed in the Add-on important changes history section as seen in the attached screenshot;
  - the Add-on review log will show an event for Force disable/enable actions;
  - DevHub Recent activity log will show manual Approvals, Rejections (immediate and delayed), Reviewer replies and Admin code/content review requests attached to the reviewer name that performed the action;
  - Status changes triggered by auto-approval, block actions or auto-rejection (when delay rejection expires) will be seen as coming from Mozilla in DevHub Recent activity log;
  - actions made by the developer will be marked with the developer display name in DevHub Recent activity log.

Observations:
  - there is no mention of the reviewer who Forced disabled/enabled an add-on in the Add-on important changes history section; Reviewers need to filter results in the Add-on review log to find the entry for that add-on in order to see who made the change;
  - when an add-on is Forced disabled, there is no entry in DevHub recent activity to reflect the add-on status change into Disabled by Mozilla; there is however an entry for Force enable when the add-on status changes to Incomplete.

![image](https://user-images.githubusercontent.com/31961530/111179853-21593000-85b5-11eb-8d3f-8515e0780fbd.png)

**Comment by diox** [comment]
Re-opening to add the reviewer responsible directly to the changes history list

**Comment by diox** [comment]
Actually, since I won't have the time to fix this before the tag, @AlexandraMoga can you open a follow-up to make the reviewer responsible for the action explicitly present in the review page ? I know the original issue was all about this, but technically this is just an UI bit, we can consider that the current issue was just about the backend work.
