### ISSUE TITLE
Host mysql data volume externally for docker development

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1665]
It's annoying to rebuild the DB everytime you have to rebuild docker, rather than simply applying migrations. We can fix this by using a [data volume](https://docs.docker.com/engine/userguide/containers/dockervolumes/) for mysql.

**Comment by EnTeQuAk** [comment]
adding on that, I think I disagree here a bit. You don't necessarily have to rebuild docker all the time, we have a `make update_docker` shortcut that can help so that pulling the latest images should not be necessary most of the time.

I also think that using an external data-volume might clutter the users disk and a simple docker-clean script won't clean that up anymore leaving lots of trash.

I'm going to close this for now, if someone disagrees or thinks this is more important than I think please feel free to re-open anytime.

**Comment by kumar303** [comment]
I meant using a separate data volume container for mysql (still managed by docker), which is a more standard docker configuration. See https://docs.docker.com/engine/admin/volumes/volumes/

 Switching to this pattern would make cleanup easier when you run out of space (which happens a lot) -- you could delete all containers except your db data volume, pull in fresh containers, and run the update script instead of starting a new db from scratch. The current workaround is to destroy your database and start from scratch which isn't too bad but annoying.

We did this on payments and it was convenient. I don't remember exactly how we configured it though. https://github.com/mozilla/payments-env/blob/master/docker-compose.yml#L44
