### ISSUE TITLE
Add more allowed values for `addon_install_source`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#16671]
While reading our production logs to debug a different issue, I saw warnings about unsupported `addon_install_source` values. It's not a big issue because we use "others" for all unknown sources but it would be better to allow those values:

- not_installed
- winreg_app_user

**Comment by willdurand** [comment]
@rpl are there any other sources we'd like to allow?

**Comment by rpl** [comment]
> @rpl are there any other sources we'd like to allow?

@willdurand Let me double-check, I'm pretty sure there is at least another `winreg_...` one that may be worth adding along with the two we did notice yesterday.

**Comment by rpl** [comment]
@willdurand as I assumed there is one more `winreg_...` location:
- [`winreg_app_global`](https://searchfox.org/mozilla-central/rev/002023eb262be9db3479142355e1675645d52d52/toolkit/mozapps/extensions/internal/XPIProvider.jsm#2356), it is a "sideload through windows registry" location like `winreg_app_user` but for all users instead of a single one

If we want to also explicitly include all other locations that exists on the Firefox side but not yet in the API endpoint ([1]):

- [app_system_profile](https://searchfox.org/mozilla-central/search?q=symbol:%23KEY_APP_SYSTEM_PROFILE&redirect=false)
- [app_system_addons](https://searchfox.org/mozilla-central/search?q=symbol:%23KEY_APP_SYSTEM_ADDONS&redirect=false)
- [app_system_defaults](https://searchfox.org/mozilla-central/search?q=symbol:%23KEY_APP_SYSTEM_DEFAULTS&redirect=false)
- [app_builtin](https://searchfox.org/mozilla-central/search?q=symbol:%23KEY_APP_BUILTINS&redirect=false)
- [app_system_user](https://searchfox.org/mozilla-central/search?q=KEY_APP_SYSTEM_USER+&path=)
- [app_global](https://searchfox.org/mozilla-central/search?q=symbol:%23KEY_APP_GLOBAL&redirect=false)
- [app_system_share](https://searchfox.org/mozilla-central/search?q=symbol:%23KEY_APP_SYSTEM_SHARE&redirect=false)
- [app_system_local](https://searchfox.org/mozilla-central/search?q=symbol:%23KEY_APP_SYSTEM_LOCAL&redirect=false)

(The full list of location is defined here on the Firefox side, in case we want to reference it in the docs or an inline comment nearby the definitions of the values allowed on the api endpoint side: https://searchfox.org/mozilla-central/rev/002023eb262be9db3479142355e1675645d52d52/toolkit/mozapps/extensions/internal/XPIProvider.jsm#2271-2360)

-----
[1]: not all of the location should currently be allowed to accept sideloads (and so it is likely that we may never receive any reports for some of these values, as long as no malicious apps is manually tempering our addon db), but on some system and/or builds we actually allow some of them to accept sideload, e.g. 
- on linux we allow the distribution to sideload an extension packaged with the distro package system and allow them to sideload the extension from a location that is actually locked in other builds/platforms

**Comment by AbhisekOmkar** [comment]
https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

Check this out..

**Comment by diox** [comment]
I'm happy to add all other possible locations to prepare for the future, it doesn't cost us much to do so, but in order to add new values I need a human-readable version for each. For most, if not all of the current sources it was pretty straightforward, but I'm not sure about all those new ones. Can you help, @rpl ?

* `winreg_app_user`: Windows Registry (User) ?
* `winreg_app_global`: Windows Registry (Global) ?
* `app_system_profile`: ?
* `app_system_addons`: ?
* `app_system_defaults`: ?
* `app_builtin`: ?
* `app_system_user`: ?
* `app_global`: ?
* `app_system_share`: ?
* `app_system_local`: ?

**Comment by rpl** [comment]
>  Can you help, @rpl ?

Sure thing, I just double-checked them, follows a short description of each one:

  - `winreg_app_user`: Windows Registry (User) ? yes :+1:
  - `winreg_app_global`: Windows Registry (Global) ? yes :+1:
  - `app_system_profile`: system addons location, located in the `system-extensions` subdir in the user profile (never actually saw it used, @mixedpuppy may know more about this one)
  - `app_system_addons`: system addons location, located in the `feature` subdir in the user profile (I'm pretty sure this should be where we install the system addons updates and installations coming through Balrog product updates)
  - `app_system_defaults`: system addons location bundled with the app, located in the `browser/feature` subdir of the application directory
  - `app_builtin`: builtin addons (addons builtin into the application omni.ja), e.g. builtin themes and default search engines  
  - `app_system_user`: user accessible app-level sideload location shared across profiles (e.g. on Linux this is `$HOME/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}`, where the last part is the application uuid) 
  - `app_global`: addons located in the `browser/extensions` subdir of the application directory
  - `app_system_share`: Same as `app_system_user` but at system level (e.g. this is `/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}` on Linux) 
  - `app_system_local`: similar to `app_system_share` but on a different path (e.g. this is `/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}` on Linux) 

To be honest I haven't directly saw some of these to be ever or often used (in particular `app_system_profile`, or what is the reason for having both `app_system_share` and `app_system_local`) and so it would be good to ask @mixedpuppy to take a look to this list and correct me if I'm wrong on some of them or add anything that I may have missed.

**Comment by diox** [comment]
Trying to come up with concise text for each... I've got:
- `winreg_app_user`: Windows Registry (User)
- `winreg_app_global`: Windows Registry (Global)
- `app_system_profile`: System Add-on (Profile)
- `app_system_addons`: System Add-on (Update)
- `app_system_defaults`: System Add-on (Bundled)
- `app_builtin`: System Add-on (Builtin)
- `app_system_user`: System Add-on (User)
- `app_global`: Application Add-on
- `app_system_share`: System Add-on (OS Share)
- `app_system_local`: System Add-on (OS Local)

The goal is for each name to be unique and descriptive enough that admins & reviewers can differentiate between them when they are found in the wild (which should hopefully be rare)

**Comment by diox** [comment]
@rpl we have a note in our docs that says all `addon_install_source` values should match what's documented in https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/Events.yaml#166. None of those new values are are in there though (not even `not_installed` and `winreg_app_user` which we've seen in the wild). Is that doc out of date ?

**Comment by rpl** [comment]
@diox yes, it is, we usually update Events.yaml when we add or update the telemetry events, and based on the `hg annotate` info the last time we changed that description has been changed to rtamo (Bug 1549770) and geckoview-app (Bug 1614760).

It is easy enough to recall to add them when we are adding a new source explicitly passed in a new call to the AddonManager  APIs (like rtamo and geckoview-app), whereas these ones are the kind of source values that are autogenerated by the XPI location names and I should have actually added them in the initial version of this description as part of the initial bug that introduced this Event.   

Let me file an bugzilla issue to update it with the ones that we listed in this issue comments (I'll file the issue and then I'll edit this comment and link that issue here).

**Comment by mixedpuppy** [comment]
> Trying to come up with concise text for each... I've got:
> 
>     * `winreg_app_user`: Windows Registry (User)
> 
>     * `winreg_app_global`: Windows Registry (Global)
> 
>     * `app_system_profile`: System Add-on (Profile)
> 
>     * `app_system_addons`: System Add-on (Update)
> 
>     * `app_system_defaults`: System Add-on (Bundled)
> 
>     * `app_builtin`: System Add-on (Builtin)
> 
>     * `app_system_user`: System Add-on (User)
> 
>     * `app_global`: Application Add-on
> 
>     * `app_system_share`: System Add-on (OS Share)
> 
>     * `app_system_local`: System Add-on (OS Local)

The naming here is confusing due to the overuse of "system".   

app_system_user/share/local are addons installed in a OS-system location.  user is addons installed on a single machine for a single user, but multiple firefox profiles.  share is a network share, available (potentially) to all users/profiles on a network.  local is installed for a single machine, for all users/profiles on that machine.  I'd prefer to find a different name for these since "System Add-on" has a specific meaning internally to mozilla.  While I don't like it, maybe we call them "Enterprise Add-ons".  

app_system_profile/addons/defaults are what we tend to call "System Add-ons", and are typically addons we distribute.  

app_builtin can just be called Builtin Add-on.

**Comment by diox** [comment]
@mixedpuppy I proposed `Operating System Add-on` above instead of `Enterprise Add-on`, but alternatively... `System-wide Add-on` ?

**Comment by diox** [comment]
(Re-closing since technically this went into the tag, but I've got a follow-up PR to change the human readable text)

**Comment by AlexandraMoga** [comment]
I've verified that the newly added `addon_install_sources` and the pre-existing ones listed in [this table](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#abuse-addon-install-source-parameter) are accepted by the Add-on Abuse report API.  A readable version of the abuse reports I've submitted can be found [here](https://reviewers.addons.allizom.org/en-US/reviewers/abuse-reports/devhub-listed-ext-04-29).

Also, install sources that are not listed in [this table](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#abuse-addon-install-source-parameter) will be translated as "Other" in the API response.

This issue is verified fixed on stage.
