### ISSUE TITLE
Filter out auto-approvals in "Add-on important changes history" section

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16808]
### Describe the problem and steps to reproduce it:

The "Add-on important changes history" on the reviewer tools page contains an entry for each auto-approval, which can cause lots of entries for add-ons with many versions. Let's hide them.

### What happened?

Many auto-approval entries shown like: "... status changed to Approved."

### What did you expect to happen?

Auto-approvals should probably be hidden.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
For the record, this is a problem because we log additional useless status changes every time there is an approval, even when the status hasn't actually changed... it would be good to get rid of the extra logs... but the easiest solution right now is just to hide them.

**Comment by AlexandraMoga** [comment]
Status changes are no longer displayed in the Add-on important changes history section. I'm seeing only authorship changes and Force disable/enable actions:

![image](https://user-images.githubusercontent.com/31961530/112493578-f3c96f00-8d8a-11eb-941c-9f2df4ba1b1a.png)

The Recent changes history in Devhub is still displaying all the status changes related to an add-on.

This issue is verified fixed on stage.
