### ISSUE TITLE
report a bug link at bottom of extension edit page goes to 404 error

### ISSUE THREAD

**Issue by st333v** [mozilla/addons-server#16884]
### Describe the problem and steps to reproduce it:

when i visit the following page
https://addons.mozilla.org/en-US/developers/addon/revert-site/edit
there is a "Report a bug" link at the bottom of the page
when i click it, it goes to a 404 error page

### What happened?
clicking the "Report a bug" link goes to a 404 error at  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Contact 

### What did you expect to happen?
it should take me to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us

**Comment by st333v** [comment]
i just found out this bug is already covered by https://github.com/mozilla/addons-server/issues/16753 #16753 and it seems the link should got to github new issue instead of the contact page...

**Comment by diox** [comment]
Ah, yeah. The problem is, we don't have a good generic contact page elsewhere... Maybe https://addons.mozilla.org/en-US/about ? Paging @caitmuenster for an opinion

**Comment by jvillalobos** [comment]
This is the same as https://github.com/mozilla/addons-frontend/issues/9923, but for DevHub. Maybe we should update the DevHub footer with what we currently have on front-end.

**Comment by caitmuenster** [comment]
We've been asked to remove the "Contact Us" page instead of MDN, so unfortunately we'll have to revisit the DevHub and photon-footer links. 

Right now, https://wiki.mozilla.org/Add-ons#Reporting_problems is probably the most stable place for contact & bug reporting issues. It has same "reporting bugs" content as the MDN page. I'd recommend linking there for now. 

@diox, I also like your idea to put something on https://addons.mozilla.org/en-US/about. Under the "Get Involved" section, we could add: 

**Report an issue**
If you find a problem with the site, we'd love to fix it. Please file an [issue](https://github.com/mozilla/addons/issues/new) and include as much detail as possible. 

To report a security vulnerability for an extension, even if it is not hosted on this site, please file an issue on [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=addons.mozilla.org&component=Add-on%20Security&maketemplate=Add-on%20Security%20Bug&bit-23=1&rep_platform=All&op_sys=All) or email amo-admins@mozilla.com. All security vulnerability reports are [confidential](https://www.mozilla.org/about/governance/policies/security-group/bugs/).

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @willdurand

**Comment by bhushan-borole** [comment]
Hello @caitmuenster @diox 
I would like to take up this issue.

**Comment by caitmuenster** [comment]
Go for it, @bhushan-borole! It sounds like you are on the right track. Go ahead and tag [@]willdurand when you have a patch up. :)

**Comment by bhushan-borole** [comment]
Hey @willdurand 
I should replace https://github.com/mozilla/addons-server/blob/b17d4ce7e1f2ee036f8bd0fda94381b6c0fb9976/src/olympia/templates/photon-footer.html#L17 with https://addons.mozilla.org/en-US/about right?

**Comment by bhushan-borole** [comment]
@willdurand  @caitmuenster Tagging you for a reminder.

**Comment by willdurand** [comment]
> We've been asked to remove the "Contact Us" page instead of MDN, so unfortunately we'll have to revisit the DevHub and photon-footer links.
> 
> @diox, I like your idea to put something on [addons.mozilla.org/en-US/about](https://addons.mozilla.org/en-US/about). Under the "Get Involved" section, we could add:
> 
> **Report an issue**
> If you find a problem with the site, we'd love to fix it. Please file an [issue](https://github.com/mozilla/addons/issues/new) and include as much detail as possible.
> 
> To report a security vulnerability for an extension, even if it is not hosted on this site, please file an issue on [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=addons.mozilla.org&component=Add-on%20Security&maketemplate=Add-on%20Security%20Bug&bit-23=1&rep_platform=All&op_sys=All) or email [amo-admins@mozilla.com](mailto:amo-admins@mozilla.com). All security vulnerability reports are [confidential](https://www.mozilla.org/about/governance/policies/security-group/bugs/).

@caitmuenster could you please file an issue in addons-frontend for any "about" page changes: https://github.com/mozilla/addons-frontend/issues/new, thanks!

**Comment by ioanarusiczki** [comment]
@willdurand If I understood correctly, "Report a bug" should redirect to https://addons.mozilla.org/about 

On AMO dev I still get the 404

![report a bug404](https://user-images.githubusercontent.com/33448286/128867864-a5bdf0ce-0c19-4a2d-abc5-f5ce0356d403.gif)

**Comment by willdurand** [comment]
mmm right, the wrong footer was updated :(

**Comment by ioanarusiczki** [comment]
@willdurand 
Ok, right now on Manage my submissions or edit addon pages - Report a bug redirect to https://addons.mozilla.org/en-US/about 

There's also the Report a bug from the footer of the dev hub page https://addons.mozilla.org/en-US/developers/ which will redirect to https://addons.mozilla.org/en-US/about. Before this change this link redirected to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us

I hope that's fine too.

**Comment by willdurand** [comment]
Yep
