### ISSUE TITLE
Update theme previews to support new Firefox design

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#16887]
There are some changes coming to Firefox that will impact themes. We need to update the theme tool in DevHub and the theme previews we show on the site to follow these changes.

So far, it appears these changes are:
* The tab is no longer attached to the toolbar.
* The tab shape is a rounded rectangle.
* The "tab line" at the top of the tab is no longer there. For themes that declare that property, `tab_line will` define the border color for the tab. The appearance of this border is still being worked on in [bug 1702329](https://bugzilla.mozilla.org/show_bug.cgi?id=1702329).

The new design is expected to go out with Firefox 89 on May 18, but that could change. It'd be great if we can coordinate this update with the release, or slightly earlier.

/cc @caitmuenster

**Comment by eviljeff** [comment]
MR1 is now June 1st, so I assume the target date has moved on by 2 weeks also.  

In terms of milestones and merging patches, we have to consider a) when this will be available for _new_ themes, and b) when the migration tasks finish and update all the _existing_ themes (with 400k+ themes the task to update existing themes won't finish quickly).  

The optimal date would be aiming for the 2021.05.27 milestone (i.e. the Thursday before) for deploying the code -for (a)- and then starting the migration task -for (b)- on the following Monday 31st May*.  There's a risk some existing themes wouldn't be updated with the new design if the tasks have failures or take expectedly long.  

If we particularly want to be sure all existing themes match Proton design before MR1 we'd have to deploy this the week before, with the downside of a longer period when new uploads would have a different design to existing themes.

*(Monday May 31st is a public holiday in the UK so I may not be around to supervise)

**Comment by jvillalobos** [comment]
> If we particularly want to be sure all existing themes match Proton design before MR1

They don't need to be all updated by the release date. That'd just be nice to have.

**Comment by eviljeff** [comment]
I separated the tab; made it rounded; and added the border.  The icons aren't filled now, and the weight of the hamburger menu is less.  
<img src="https://raw.githubusercontent.com/eviljeff/olympia/346ed8b6faec5abee231b60e135b63d9e9a54f7f/photon-1.svg">
The changes to the tab made it looked unbalanced (to me), so the second image is after making the tab strip taller and the toolbar shorter. 
<img src="https://raw.githubusercontent.com/eviljeff/olympia/346ed8b6faec5abee231b60e135b63d9e9a54f7f/photon-2.svg">
 (and an original for comparison)
<img src="https://raw.githubusercontent.com/eviljeff/olympia/346ed8b6faec5abee231b60e135b63d9e9a54f7f/original.svg">

**Comment by JulianWels** [comment]
Hello 👋 !
Based on the guidelines from proton and your suggestions I made a new preview svg. Here are some examples

<img width="712" alt="preview" src="https://user-images.githubusercontent.com/16828024/118814890-ed4e0400-b8b0-11eb-8732-01fc9373ba6f.png">

I had to zip it because GitHub didn't want me to upload an svg. If there is an issue with this or you need it in different sizes, just reach out :)
[theme-preview.svg.zip](https://github.com/mozilla/addons-server/files/6508808/theme-preview.svg.zip)

**Comment by ioanarusiczki** [comment]
@eviljeff I tested this on AMO dev - FF88(win10): 

- theme previews on dev hub and frontend show the new design as displayed [above](https://github.com/mozilla/addons-server/issues/16887#issuecomment-844076882).
- themes installed look good.
- I filed an issue https://github.com/mozilla/addons-server/issues/17212 because I've noticed an inconsistency with the theme wizard.
