### ISSUE TITLE
Cannot download previously signed unlisted extension using the API

### ISSUE THREAD

**Issue by Jamstah** [mozilla/addons-server#17068]
### Describe the problem and steps to reproduce it:
I used to be able to sign an unlisted extension with the API, then fetch it indefinitely by using the instructions from https://addons-server.readthedocs.io/en/latest/topics/api/signing.html#checking-the-status-of-your-upload:

```
curl https://addons.mozilla.org/api/v5/addons/<id>/versions/<version>/
```

It now seems that after some time passes, that API no longer returns information about that version.

### What happened?

```
# Version already exists from a long time ago (see conflict)
[jammy@ibm007470 thinkip_userscript (master)]$ curl https://addons.mozilla.org/api/v5/addons/ihkgcafbhaecolnlbmiigkfjicmonfhf@ibm.com/versions/0.3.22/ --fail -g -XPUT -F upload=@build/firefox/thinkip_plus.zip -H 'Authorization: JWT '$token
curl: (22) The requested URL returned error: 409 Conflict
# Cannot use the API to get version info and a file download link
[jammy@ibm007470 thinkip_userscript (master)]$ curl https://addons.mozilla.org/api/v5/addons/ihkgcafbhaecolnlbmiigkfjicmonfhf@ibm.com/versions/0.3.22/ --fail -g -H 'Authorization: JWT '$token
curl: (22) The requested URL returned error: 404 Not Found
```

### What did you expect to happen?

That I can use the API to get information about the signed extension (no 404)

### Anything else we should know?

In the webui I can see and download the version

![image](https://user-images.githubusercontent.com/298807/116985740-ce524e00-acc4-11eb-9ef6-230c5af78184.png)

**Comment by diox** [comment]
Sorry this fell through the cracks and we didn't reply sooner. 

This is because the API you're using is meant for signing and checking the state of an upload, which is a temporary object, and not the version, which is permanent (once the upload has passed validation).

We do have some APIs that work on versions. Head over https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#versions-list for the documentation about them.
