### ISSUE TITLE
Can't login from a page containing unicode in a slug

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1709]
STR:
* https://addons.mozilla.org/en-US/firefox/addon/%D0%BA%D0%BE%D1%88%D0%B0%D1%87%D1%8C%D0%B8-%D0%B3%D0%BB%D0%B0%D0%B7%D0%B0/
* click on log-in
* enter email, click "continue"

Actual result:
Nothing happens, get the following error: InvalidCharacterError: String contains an invalid character impala-min.js:5:0

**Comment by yash14123** [comment]
How to go about this?

**Comment by yash14123** [comment]
Where are you getting the error? I see no changes but no errors either.

**Comment by andymckay** [comment]
You will see the error in the Web Console: https://developer.mozilla.org/en/docs/Tools/Web_Console

**Comment by muffinresearch** [comment]
Using charles to run un-minified code, this is the line with the problem: https://github.com/mozilla/addons-server/blob/79d48953655a187199cedeafbfd2cb74aa663313/static/js/common/fxa-login.js#L41

**Comment by muffinresearch** [comment]
This patch [1] allows the JS to work but there's an additional bug server-side in handling utf-8 on the return. The cause is that unicode_literals are imported in the module containing is_safe_url and mixing bytes and unicode causes an exception.

@mstriemer may have a better idea on how to fix. Maybe the conversion in the patch is not needed if a percent encoded url str can be used throughout the process?

[1] https://gist.github.com/muffinresearch/14a07ab7e6471af4fb78

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7 x64)
Postfix video: 
![k](https://cloud.githubusercontent.com/assets/15685960/17206130/fd69a10e-54b6-11e6-89f8-5cf3c877a67c.gif)
