### ISSUE TITLE
filter userprofile extension and theme counts in sitemap by addon compat

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17142]
follow-up for #16960 - addons listed are filtered by app compatibility per page but the sitemap is using an overall count which is incorrect.

**Comment by AlexandraMoga** [comment]
I've created a few users that helped me test this more easily:

1. User 10642189 - has one theme submitted
2. User 10642190 - has one extension compatible only with Firefox for Desktop
3. User 10642191 - has one extension compatible only with Firefox for Android
4. User 10642192 - has one extension compatible both with Firefox for Desktop and Firefox for Android

Presence in sitemap:
- `/firefox/` - users 1, 2, 4
- `/android/` - users 3 and 4

This issue is verified fixed on -dev.
