### ISSUE TITLE
only include firefox compatible addons under /firefox/ in sitemap? (& for android)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17143]
follow-on from #16910

the sitemap currently includes both /firefox/addon/<slug> and /android/addon/<slug> for every add-on, regardless of compatibility.  Both urls work, and render a slightly different page - you get a warning banner if the add-on is not compatible with desktop Firefox on /firefox/, and similarly with /android/.

We _don't_ mark an incompatible page as an alternative of the compatible one; or tag it with `<meta name="robots" content="noindex, follow" />` to de-index it; or link to the other page.  It's assumed you landed on the page intentionally as you visited the link from AMO where the app would have been auto-detected. 

But, should we exclude from the sitemap /firefox/ versions of add-ons that aren't compatible with desktop Firefox?  And should we exclude /android/ versions of add-ons that aren't compatible with Firefox on Android?

back in 2018 @rraue cautioned against excluding android urls in https://github.com/mozilla/addons-frontend/issues/6644#issuecomment-430215919 but maybe this isn't still valid (or isn't relevant to the sitemap)

**Comment by eviljeff** [comment]
current proposal is:
- for addons that are only compatible with desktop Firefox, only include the `/en-US/firefox/addon/<slug>/` urls
  - don't include `/en-US/android/addon/<slug>/`
- for addons that are only compatible with Android Firefox - and are recommended - only include `/en-US/android/addon/<slug>/`
  - don't include `/en-US/firefox/addon/<slug>/`
  - don't include the addon for either `/firefox/` or `/android/` if the add-on is Android only but is _not_ recommended, because only recommended add-ons are installable on release Android Firefox.
- for addons that are compatible with desktop Firefox, and Android Firefox, and are recommended for Android, include both `/en-US/firefox/addon/<slug>/` and `/en-US/android/addon/<slug>/`

does this seem reasonable @rraue ?

(I'm only mentioning `/en-US/` urls for brevity; this would equally apply to urls under other locales too)

**Comment by rraue** [comment]
This seems exactly right. We want only urls that are useful for a user indexed and getting traffic to. And our sitemap is basically the reference for that. So I think you got it right here.

**Comment by AlexandraMoga** [comment]
I've created the following set of add-ons in order to verify this issue:

1. [Add-on compatible only with Firefox for Desktop](https://addons-dev.allizom.org/en-US/firefox/addon/only-with-firefox-for-desktop/)
2. [Add-on compatible only with Firefox for Android](https://addons-dev.allizom.org/en-US/firefox/addon/only-with-firefox-for-android/)
3. [Add-on compatible only with Firefox for Android _not_ Recommended](https://addons-dev.allizom.org/en-US/firefox/addon/only-with-firefox-for-a-no-r/)
4. [Add-on compatible both with Firefox for Desktop and Firefox for Android](https://addons-dev.allizom.org/en-US/firefox/addon/both-desktop-android/)
5. [Add-on with two versions, first (older) compatible with Firefox for Desktop and second (current) with Firefox for Android](https://addons-dev.allizom.org/en-US/firefox/addon/first-version-d-second-a/)

Appearance in sitemap sections (in addons, versions, reviews):
- `/firefox/` - 1, 4
- `/android/` - 2, 4, 5

@eviljeff I have a question about add-on 5: the current version for this add-on is compatible only with Android, hence the presence in the `/android/` sections in the sitemap. However, the first version was compatible with Firefox for Desktop, so theoretically, the add-on versions page would include an entry relevant for `/firefox/`. Should we care about these scenarios?

**Comment by eviljeff** [comment]
> @eviljeff I have a question about add-on 5: the current version for this add-on is compatible only with Android, hence the presence in the `/android/` sections in the sitemap. However, the first version was compatible with Firefox for Desktop, so theoretically, the add-on versions page would include an entry relevant for `/firefox/`. Should we care about these scenarios?

It's an edge case really - amo wouldn't highlight there were previous compatible versions on the detail page so they would have to go into versions to find it anyway - and we only show the last 25 versions so older than that it wouldn't be there even then.  I don't think it's worth the extra complexity to deal with that case.  All the pages will still work, it just means it wouldn't be surfaced to search engines unless there was a link elsewhere to it.
