### ISSUE TITLE
Readme.rst not showing image even though there is an image-box

### ISSUE THREAD

**Issue by yash14123** [mozilla/addons-server#1718]
Not very sure about it though. Waiting for review.

**Comment by andymckay** [comment]
There's a pull request somewhere for us to review?

**Comment by muffinresearch** [comment]
I think this is pointing to the requires.io image not working:

<img alt="mozilla_addons-server__addons_mozilla_org__reloaded_" src="https://cloud.githubusercontent.com/assets/1514/13176604/6f1e8500-d70b-11e5-9979-36e6244507e0.png">

@yash14123 In future if you can include more information + screenshots on the bug report where approprioate it helps us know where to look.

**Comment by tofumatt** [comment]
This isn't a good first bug, as it seems we need to enable the "new" repo (`addons-server` instead of `olympia`) in requires.io's web interface. Unfortunately, only admins of the org can enable it:
<img width="717" alt="screenshot 2016-02-23 09 58 03" src="https://cloud.githubusercontent.com/assets/90871/13239273/e8c7d4be-da13-11e5-8753-13912c8544a7.png">

So @andymckay or another admin might need to do that to get the image working. Simply changing the slug to addons-server doesn't seem to do it. (https://requires.io/github/mozilla/addons-server/requirements.svg?branch=master)

**Comment by andymckay** [comment]
Oh that's right, thanks @tofumatt. I just activated for the new repo and updated the readme.
