### ISSUE TITLE
"Signed" but not really

### ISSUE THREAD

**Issue by wbt** [mozilla/addons-server#1726]
**User story:**
As you know, forced software upgrades to Firefox (43.0.1 or 44.0.2) automatically disables add-ons that some users view as core functionality, without any warning in the upgrade process and without any interface option to go back.  The only notice looks something like this **Screenshot 1:**
![One or more add-ons disabled](https://cloud.githubusercontent.com/assets/563406/13197512/d2379c46-d7bd-11e5-88b9-3f53310de482.PNG)

Clicking Learn More, I'm brought to a screen where I learn that TabGroupsManager (among others) is disabled, **Screenshot 2:**  
![TabGroups Manager disabled](https://cloud.githubusercontent.com/assets/563406/13197518/06d2f04a-d7be-11e5-9a04-31ed57f50b1b.PNG)

Clicking Find Replacements, I'm brought to addons.mozilla.org.  I type "TabGroups Manager" into the search box and am immediately taken to [this page](https://addons.mozilla.org/en-US/firefox/addon/tabgroups-manager/?src=ss), which says the add-on is signed, **Screenshot 3:**
![Search for TabGroups Manager says signed and OK to add](https://cloud.githubusercontent.com/assets/563406/13197533/549c9984-d7be-11e5-85f8-73e05b15f00f.PNG)

Clicking Add To Firefox gets me to **Screenshot 4:**
![allow request to install](https://cloud.githubusercontent.com/assets/563406/13197540/89f0ac24-d7be-11e5-83d7-5f6a1cb3e13e.PNG)

And clicking Allow gets me to **Screenshot 5:**
![would like to install](https://cloud.githubusercontent.com/assets/563406/13197548/9a1648ac-d7be-11e5-8dd9-a7ef30decbbd.PNG)

Clicking Install indicates that the extension will be installed after restarting Firefox, as shown in **Screenshot 6:**
![Will be installed on restart](https://cloud.githubusercontent.com/assets/563406/13197551/c3f77cb8-d7be-11e5-9054-67ba8b0ba61a.PNG)

And indeed, it is installed on restart, as shown in **Screenshot 7:**
![TabGroups Manager is there](https://cloud.githubusercontent.com/assets/563406/13197556/db63111e-d7be-11e5-8feb-ff818bda9ba0.PNG)

It also appears to be just fine, in the non-disabled Extensions list, **Screenshot 8:**
![Appears fine in extensions](https://cloud.githubusercontent.com/assets/563406/13197562/286f34f6-d7bf-11e5-9fdc-16e03050b228.PNG)

But then, next time Firefox starts up, it's back to **Screenshot 1,** and a loop.  Every other time I start Firefox, I need to reinstall the add-on and restart.  The add-on page says it's *signed* and on every other startup it works as signed, but apparently it isn't really. Or is it?  It seems impossible to tell.

It seems like forced add-on signing is intended to be a security system that has gaping holes in recognizing as signed things that really aren’t or vice versa, and disrespects user choice while removing core functionality.  The new policy disproportionately affects third-party security and privacy add-ons, giving the impression Mozilla doesn't like those ideas and doesn't want users to be empowered to take control over security and privacy nor does it respect informed consent about significant changes, which I think is opposite the intended message.  

This is unexpected and undesired behavior.  These are the kinds of frustrating experiences that lead people to turn off updates, downgrade using old installers from sketchy sites, and do other things that run counter to the original goals of the change.  At the very least, the system for indicating and recognizing what is signed or not should work.

**Comment by wagnerand** [comment]
Most likely, the add-on is changing its own folder or files within the directory it is installed in. Of course, changing folders or files inside the add-on directory breaks the signature. As Firefox can no longer verify their integrity, the add-on gets disabled.
For this specific add-on, I recommend using https://addons.mozilla.org/en-US/firefox/addon/tabgroups-manager-revived/

In general, you need to contact the add-on developer and ask them to submit a new version of their add-on that does not change any folder or file inside the add-on directory.

**Comment by amuntner** [comment]
wbt,

The purpose of the signature validation mechanism is to ensure that the add-on files have not changed. When the signed files change, the signature is no longer valid and the browser disables the add-on as a security feature. The intent of the design is to fail secure because there's no way to know if the add-on modified it by design itself or if a malicious add-on or malware modified it. 
There is nothing stopping an add-on developer from getting an add-on signed that violates this rule.
Wagnerand is right, this is not an addons-server bug. 
Other options are:
1. Use Developer or Nightly which allow disabling addon signing 
2. Fork and fix the add-on and submit it yourself
3. Open a bug report issue with the developer and ask them to fix it.

**Comment by wbt** [comment]
Based on what you described, the addons-server could be modified to test the add-on in a secure environment and see if it does something which would cause it to be branded "unsafe" by the browser, and then either don't tell users that one's signed and OK, OR change the malicious code detection code to cut out the false positive.

**Comment by amuntner** [comment]
Unsafe, based on what loaded content from what website? What other add-ons are installed, what other programs installed on the computer, and which browser version with which configuration settings?

We do some tests[1] by they can never be more than cursory for bad behavior, there are way too many ways for bad behavior to be done and too many possible variants that would beat a scanner to make it a task even worth pursuing. 

The addon you're discussing was last updated in 2011 and last year is when the signing requirement came into effect.[2] Existing addons were signed (otherwise we'd have a lot of complaints) and most did not have a problem. Even if we developed the system you described and started using it tomorrow, apps with this bug wouldn't be removed because they'd still work with nightly or developer edition. 

It sounds like your best bet is to use nightly or dev edition and turn off signing, which is not recommend for security reasons, or using the alternative newer version.[3]

1. https://github.com/mozilla/amo-validator
2. https://blog.mozilla.org/addons/2015/02/10/extension-signing-safer-experience/
3. https://addons.mozilla.org/en-US/firefox/addon/tabgroups-manager-revived/

**Comment by wbt** [comment]
What about at least testing the add-on with the latest vanilla release?  Even a fix that doesn't cover every possibility can still be an improvement over the status quo.  

This GitHub issue encourages readers to use the "revived" version, but the the AMO interface encourages people to use the original which is labeled "signed" and has the green Add to Firefox button, while "revived" has a cautionary black-and-yellow scheme as a warning indicating it might not be safe, and doesn't indicate it's signed.  That kind of UI design encourages behavior that seems opposite the goal.

**Comment by amuntner** [comment]
"That kind of UI design encourages behavior that seems opposite the goal. "

You're welcome to file a separate issue for specifically that, there's no way for it to happen in this one
