### ISSUE TITLE
Broken redirect on reviewer tools page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17268]
### Describe the problem and steps to reproduce it:

STR:
1. Open the reviewer tools page for a non-deleted add-on via the GUID. You get redirected to the slug-based url.
2. Delete the add-on
3. Repeat (1).

### What happened?

The redirect still happens and leads you to a 404 page because the slug is no longer available.

### What did you expect to happen?

To see the review page, the redirect should probably not happen, at least not to the unavailable slug.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
I suspect this is because the redirect is coming from the `addon_view` decorator, which does a 301 redirect through `HttpResponsePermanentRedirect`. In reviewer tools, we probably never want a permanent redirect, so `addon_view` should be modified to make it possible to do a 302 instead and `reviewer_addon_view_factory` should make use of that.

**Comment by diox** [comment]
This should no longer happen since you made the AMO ID the canonical identifier in reviewer tools instead of the slug in https://github.com/mozilla/addons-server/issues/17644
