### ISSUE TITLE
Include blog's sitemap in main sitemap

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17341]
In https://github.com/mozilla/addons-blog/issues/204, we added a sitemap for the blog, available at `a.m.o/blog/sitemap.xml`. We should include it in the main AMO sitemap.

**Comment by AlexandraMoga** [comment]
The main sitemap.xml (I was looking at the debug version because it has the latest updates - https://addons-dev.allizom.org/sitemap.xml?debug) includes an entry for the blog sitemap at https://addons-dev.allizom.org/blog/sitemap.xml

@willdurand I've noticed that even if I'm opening the AMO -dev blog sitemap, the URLs within are pointing to prod. Also, the template used seems to be a bit different from the other sitemaps (which are rendered as simple URL sequences). Is this expected?

**Comment by willdurand** [comment]
> @willdurand I've noticed that even if I'm opening the AMO -dev blog sitemap, the URLs within are pointing to prod. Also, the template used seems to be a bit different from the other sitemaps (which are rendered as simple URL sequences). Is this expected?

Yeah, that's expected.
