### ISSUE TITLE
JSON syntax errors in the manifest will trigger an "unexpected error" during validation 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#17369]
### Describe the problem and steps to reproduce it:
1. Edit an add-on manifest to purposely introduce a syntax error (like an extra `,` , `}` or a missing `"` etc)
2. Submit the add-on on AMO

### What happened?
The following validation error is triggered: Error: Validation was unable to complete successfully due to an unexpected error.

### What did you expect to happen?
Validation results point to the JSON syntax error

### Anything else we should know?
- issue reproduced in all AMO environments 
- most likely a regression from the manifest normalization feature

**Comment by willdurand** [comment]
I think we'd need to add support for the `InvalidManifest` in the `@validation_task` decorator but this might because by other errors than just a malformed JSON. An alternative could be to... not normalize invalid manifest files?

@diox WDYT?

**Comment by diox** [comment]
I lean towards not normalizing invalid manifest files, because that was kind of the idea behind how `validate_file_path()` deals with invalid manifests already: the logic being that if it can't parse the manifest, it lets the linter deal with it, and the linter will return an error. The idea was to not duplicate the logic the linter already has there. It's not amazing, but it should be ok.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev.

Syntax error identification:
![image](https://user-images.githubusercontent.com/31961530/122932703-a0a98d00-d376-11eb-8501-547a1604795b.png)
![image](https://user-images.githubusercontent.com/31961530/122932731-a7d09b00-d376-11eb-9779-03109535e388.png)
