### ISSUE TITLE
Separate legacy API code from the rest

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#1737]
Tracker: #1680 

For the new API, I think we should move API bits to the relevant apps. We already started doing this, the signing API code is in the signing apps, the accounts stuff is in accounts, the statistics stuff is in stats, etc.

However, we'll still need a central place to host general utilities, base classes etc, and at the same time we need to put the legacy API somewhere.

I propose the following folder architecture (The URLs remain the same - only the code is moved around):
- All legacy API code is moved to a `legacy_api` app
- `api` app is the place where all base classes and utils for the new API will live
- `api.urls` stays the central place for all API urlpatterns, including the legacy one (`legacy_api.urls` will be included from `api.urls`)

**Comment by EnTeQuAk** [comment]
So, with the django 1.7 branch we get a new `olympia.core` app and maybe that's a good place to store central api related stuff (jwt, auth, base-classes, helpers, etc).

All other parts can also move to their specific apps (`devhub.api`, `search.api`, `signing.api`) although we need to make clear that `api` in our context always means "the api that is available via HTTP" since quite a lot projects use `module.api` for general "code related api's and helpers".

But I'm also very okay with a `olympia.api` app compared to moving stuff to `core.

**Comment by diox** [comment]
Now that I've played a bit more with the new API I'm convinced that we need `<app>.api` like you suggested, for the new API. I'll do that, as well moving the legacy stuff to a `legacy` app as mentioned in the description of this issue.
