### ISSUE TITLE
replace existing tags with new, editorial defined, tags

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17474]
https://docs.google.com/document/d/1QJ5PSHJJn5ruvhITlTMongePpZggsrTYKdmmBO0Wbk4/edit# for full details on background, but tl;dr: we want to replace the existing tags that a developer can define with a fixed list of tags AMO's staff define.  

* existing tags will be reset (deleted)
* devhub edit form needs changing to allow a selection from the tags available (multi-select list?  checkboxes like categories?) rather than a free text box

(and more, but this is the main change in addons-server and probably needs to be done first and in one go)

**Comment by ioanarusiczki** [comment]
adblocker - correct
image searchsearch - 2 separate tags 
dynamic theme is instead of search 
@eviljeff 
on AMO stage: 

- Tags from the above [doc](https://docs.google.com/document/d/1QJ5PSHJJn5ruvhITlTMongePpZggsrTYKdmmBO0Wbk4/edit#) are displayed into Additional Details section of the edit page.
- I think it works as expected: I could check/uncheck boxes, the limit is 10 tags. For 10 plus there's a warning message.
 
![too many](https://user-images.githubusercontent.com/33448286/126485343-4b268c1f-680d-478f-899a-181cb5051f39.png)

- the tooltip contains the same text as before except for the number of tags, "maximum of 20" is updated to "maximum of 10"

![tooltip](https://user-images.githubusercontent.com/33448286/126485544-b3984ac6-fa7d-45f6-b61e-ea0865b5f44b.png)

- the new list of tags is available for all addon types: extensions, themes, lang packs and dicts.

- I've noticed some issues about the tags so I filed https://github.com/mozilla/addons-server/issues/17538
