### ISSUE TITLE
implement "rotating" tag shelf

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17482]
We want to have a shelf for tags on the homepage, but we want to "rotate" (randomly select) which tag shelf is shown. 

There is currently the ability to create arbitrary shelves that would show content from any valid API response that returns add-ons,  and in some ways rotating is similar to the primary hero shelf, which shows a randomly selected promoted add-on, but we don't want to have to create 44 shelves, each one defining a different `&tag=xxx` value.

**Comment by ioanarusiczki** [comment]
@eviljeff 
What's the API endpoint I could use in Postman?

**Comment by eviljeff** [comment]
> What's the API endpoint I could use in Postman?

If a Shelf (& module) is enabled, with endpoint "random tag", then the results will be returned via /api/v5/shelves/ with the other enabled shelves.  On each API call the `tag=xxx` in the underlying search url will be different.   There isn't currently (#17497) any threshold or filtering for addons appearing in the shelf, or any default ordering - though extra criteria can be specified in the `criteria` field similarly to a search shelf.

**Comment by ioanarusiczki** [comment]
@eviljeff 

on AMO dev: 

- I added and enabled 3 shelves with endpoint `random-tag`. I used for criteria the "see more" links from search results - the ones available into the extensions tab on AMO dev (recommended, top rated and more trending). These only include recommended add-ons (46) and I added tags to multiple addons so I could see get some results returned.
- I see that the API https://addons-dev.allizom.org/api/v5/shelves/ is returning results, making several API calls it looks like results are returned randomly.
- the frontend also started returning results , every time I refresh the page I get different add-ons but most of the times I get less than 4(but I left 4 as default for each shelf in django), sometimes a shelf is empty and I think there should be enough tags in order to rotate 4 each time  - is that good for now? 

![results](https://user-images.githubusercontent.com/33448286/126781404-9e448e08-561f-49be-835a-a767e0471917.png)

**Comment by eviljeff** [comment]
>     * the frontend also started returning results , every time I refresh the page I get different add-ons but most of the times I get less than 4(but I left 4 as default for each shelf in django), sometimes a shelf is empty and I think there should be enough tags in order to rotate 4 each time  - is that good for now?

Do you mean that the shelf _should_ contain more than 4 addons (because there are more than 4 addons tagged with that tag, and that fit whatever other criteria you entered, if you entered extra criteria) but doesn't?  

Did you find an easy way to identify which tag was actually used in the shelf if there wasn't a "see more..." link?

**Comment by ioanarusiczki** [comment]
@eviljeff 

I only assume that the reason I sometimes get less than 4 is because there might not be enough addons tagged for a specific tag because it's not quite easy for me to identify which is the tag used by a shelf. 

I did not add extra criteria - this is the [content](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/71/change/) of a shelf. 

I tried testing it on AMO stage -  but I cannot save a random-tag shelf because I get an error -> No add-ons found. Check parameters - e.g., "type".  Criteria is ?promoted=recommended&sort=random&type=extension and there's one addon I tagged https://addons.allizom.org/en-US/developers/addon/recommended/edit This worked on -dev Friday.

**Comment by eviljeff** [comment]
> I tried testing it on AMO stage - but I cannot save a random-tag shelf because I get an error -> No add-ons found. Check parameters - e.g., "type". Criteria is ?promoted=recommended&sort=random&type=extension and there's one addon I tagged https://addons.allizom.org/en-US/developers/addon/recommended/edit This worked on -dev Friday.

The form does a query with a single tag for sanity - the first Tag in django admin - which I suspect might be `dynamic theme` on stage because (that tag was removed on addons-dev on Thursday so will still exist on stage).

**Comment by ioanarusiczki** [comment]
@eviljeff I enabled on -stage a shelf using random-tag endpoint. I used the search API to check the number returned, for example:
`?promoted=recommended&sort=random&type=extension&tag=privacy` - 4 addons found 

frontend: 

![should be ok](https://user-images.githubusercontent.com/33448286/127291678-be3be782-abb3-4551-b508-65feef06c96c.png)

See more https://addons.allizom.org/en-US/firefox/search/?promoted=recommended&sort=random&type=extension&tag=privacy returns 4 extensions. 

Should be fine. I'm marking this issue verified - FF90(Win10).
