### ISSUE TITLE
limit the results for a (tag) shelf to minimum thresholds

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17497]
For tag shelves (that will be randomly displayed on the homepage) we want to limit the add-ons shown to ones that meet certain thresholds.

> Sorting by users sounds good, but we should also set some minimum thresholds. I  think something like 500 users or more, and 3.5-star rating or more.

Implementation details are if this is hardcoded just for tag shelves, or available for other shelf endpoints too, or added as an API feature (e.g. something like a param of `?threshold=rating>3.5`)

**Comment by ioanarusiczki** [comment]
I verified on -dev some search results for 2 enabled shelves with random-tag endpoint enabled. I've noticed that:

The following search results display addons which have not been rated yet (these are some examples):
https://addons-dev.allizom.org/en-US/firefox/search/?promoted=recommended&sort=random&type=extension&tag=password%20manager
https://addons-dev.allizom.org/en-US/firefox/search/?promoted=recommended&sort=random&type=extension&tag=anti%20tracker
https://addons-dev.allizom.org/en-US/firefox/search/?promoted=recommended&sort=random&type=extension&tag=shopping
https://addons-dev.allizom.org/en-US/firefox/search/?promoted=recommended&sort=random&type=extension&tag=user%20scripts
https://addons-dev.allizom.org/en-US/firefox/search/?sort=users&tag=content%20blocker

I've also found 2 cases when all addons have ratings >3 (average ratings) :
https://addons-dev.allizom.org/en-US/firefox/search/?sort=users&tag=antivirus
https://addons-dev.allizom.org/en-US/firefox/search/?promoted=recommended&sort=random&type=extension&tag=antivirus

I don't know if users threshold (500 or more) can be verified on AMO dev, all addons displayed in search results above have 0 users. Some data has been imported a while ago, because if I check the search results https://addons-dev.allizom.org/en-US/firefox/search/?sort=users, there's only 7 addons with ADU.

**Comment by eviljeff** [comment]
sorry, I forgot to update the issue with the details of how this was implemented.  

QA: So, right now there are no default thresholds for any of the shelves (they will function exactly the same as before).  But the criteria (the parameters) for the tag* shelf can be added to, to define whatever limits are wanted for that shelf.

`?ratings__gt=3&users__gt=1000` for a shelf would limit the results to addons that have an average rating above 3 and an average daily users about 1000.  (It's not limited to `__gt`, e.g. `__lt` instead would be less than,  https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-threshold-param)

*I added this for the tag shelf but it's usable for search shelves too, and directly on the underlying `api/v5/addons/search` endpoint.

**Comment by ioanarusiczki** [comment]
@eviljeff 

- I've noticed the API search endpoint working, for example:

https://addons-dev.allizom.org/api/v5/addons/search/?type=extension&ratings__gte=1&users__gt=500 
result: 4 addons (one has a 1 star rating and the others are above 3.5)

https://addons-dev.allizom.org/api/v5/addons/search/?type=extension&ratings__gt=3.5&users__gt=500
result: 3 addons 

I also get 3 addons into the response for https://addons-dev.allizom.org/api/v5/addons/search/?type=extension&ratings__gt=3.5&users__gt=500&tag=anti malware, because I've tagged the addons with anti-malware

- When I try to add into a random-tag shelf `?ratings__gt=3.5&users__gt=500` as Criteria I run into this error:  `No add-ons found. Check parameters - e.g., "type"` . The Addon type is `Extension`.

**Comment by ioanarusiczki** [comment]
@eviljeff  

Yeah, that was a problem but now I added the first 10 tags on addons with ratings and ADU, they're not too many but I could get 4 to make a shelf. I added and enabled now 2 random tag shelves with django.

For now, frontend returns more results than the API search endpoint, examples are below:

https://addons-dev.allizom.org/en-US/firefox/search/?ratings__gte=3&users__gt=500&tag=content%20blocker - 13 results
https://addons-dev.allizom.org/api/v5/addons/search//?ratings__gte=3&users__gt=500&tag=content blocker - 5 results

https://addons-dev.allizom.org/en-US/firefox/search/?ratings__gt=3.5&users__gt=500&tag=chat - 12 results
https://addons-dev.allizom.org/api/v5/addons/search//?ratings__gt=3.5&users__gt=500&tag=chat - 4 results

https://addons-dev.allizom.org/en-US/firefox/search/?ratings__gte=3&users__gt=500&tag=container - 9 results
https://addons-dev.allizom.org/api/v5/addons/search//?ratings__gte=3&users__gt=500&tag=container - 5 results

https://addons-dev.allizom.org/en-US/firefox/search/?ratings__gt=3.5&users__gt=500&tag=antivirus - 13 results
https://addons-dev.allizom.org/api/v5/addons/search/?ratings__gt=3.5&users__gt=500&tag=antivirus - 4 results

**Comment by eviljeff** [comment]
@ioanarusiczki mmm, yes, looks, like the new query params aren't passed on to the api by frontend (it was too good to be true to expect it to just work!).  I'll log a follow-up issue for addons-frontend.

**Comment by ioanarusiczki** [comment]
@eviljeff Ok, then I'm marking this verified.
