### ISSUE TITLE
Submitting an abuse report for an AMO-deleted add-on sets AbuseReport.addon_id to NULL

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17507]
### Describe the problem and steps to reproduce it:

Abuse reports we received after an add-on has been deleted from AMO are not correctly linked to the add-on. The `addon_id` is `NULL`.

### What happened?

Since the `addon_id` is `NULL` those abuse reports don't show up on the reviewer tools page for example.

### What did you expect to happen?

Abuse reports should be linked to the add-on they were submitted for.

### Anything else we should know?

If we keep using the `addon_id` as the mapping, we need to backfill the data for already existing abuse reports.
If we use a different mapping, then pages using or showing abuse reports should be updated to use that new mapping.

**Comment by diox** [comment]
Note: the `addon_id` is correctly kept for existing abuse reports if an add-on is soft-deleted. This is about making the link possible even though the add-on is deleted.

We'll probably want to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1721143 at the same time.

**Comment by eviljeff** [comment]
Relying on a foreign key to an `Addon` instance is risky because an add-on can be deleted and reuploaded with the same guid, resulting in a different instance in the database.  Blocklist code works around this by querying with the guid through the `AddonGUID` model (`addons_reusedguid` db table) and helper properties on the models to always return the current addon instance.  It makes any raw sql queries more complex though.

**Comment by diox** [comment]
Instead of setting `addon_id` we should go the opposite direction and just store `guid` as we do now, completely ignoring `addon_id` when a `guid` is passed to the abuse report API. Then, in reviewer and admin tools, always consider all add-ons that originally had the same `guid` - even if the add-on has been deleted and a new one was resubmitted with the same guid (in that case, the abuse report should be shown for both add-ons).

Bonus : make guid reuse more visible in reviewer tools.

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO -dev and I have the following results:

- an add-on abuse report posted after an add-on has been deleted from AMO (abuse reports can be submitted from add-ons manager if the add-on was installed before being deleted) is now being recorded in the Abuse reports section on the add-on review page; an entry for the abuse report is created in admin tools as well, but this was already the case before
- if one or more add-ons are re-using the guid of the deleted add-on, then the abuse reports will also be linked to all add-ons that share the same guid - [example from rev tools](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/re-re-reused-guid-abuse)
- abuse reports submitted for public add-ons are still recorded as before

@diox I have some observations:
- there is a ui regression in Abuse report detail admin for which I filed #17629 
- the Abuse Reports table in reviewer tools is no longer displaying the add-on name in the first column. Reviewers might need this information, so I filed #17630  
- I've noticed that the Reporter name still comes back as _anonymous_ even when the report was submitted from AMO by a logged in user; if I'm posting a report from the API with an authenticated user, the Reporter name (`display_name`) is visible. This is happening on stage as well, so it's not a new issue. Shouldn't we send the user details when the report originates in AMO?
