### ISSUE TITLE
Use different cache policy in the CDN for /api/

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17529]
In order to increase the cache hit ratio, CDN should apply a different cache policy for the API. This should be achievable by setting a different cache behavior for the `/api/*` path pattern, creating new policies attached to that specific behavior.

The key difference with the main policy is that we'll be able to ignore `DNT`, `User-Agent`, all cookies (*).

(*) To be double-checked: we do need cookies for authentication (login & logout), but those are not `GET` / `HEAD` requests and shouldn't be cached...

**Comment by diox** [comment]
> (*) To be double-checked: we do need cookies for authentication (login & logout), but those are not GET / HEAD requests and shouldn't be cached...

Actually... we had to add an explicit cache-control to those to avoid them being cached: https://github.com/mozilla/addons-server/issues/17546
I think that this change, coupled with an Origin Request Policy that does send every cookie (like we have for everything right now), should be enough regarding authentication.

**Comment by diox** [comment]
Want to get the CDN deployed to stage before doing this, cause then we'll have a stable config and we'll be free to run more unstable experiments on dev.

**Comment by bqbn** [comment]
I filed https://github.com/mozilla-services/cloudops-deployment/pull/4309/commits/9c5c87e3d5908bb86a9a5c8a62a3fce62397f3ed for this.

@diox Please have a look at the two newly added policies, `AmoApiCachePolicy` and `AmoApiOriginRequestPolicy`, and make comments on what needs to be tweaked. They're currently the same as the previous main policies.

**Comment by diox** [comment]
Thanks, I added a couple comments. Can you deploy the changes on dev when you're done ? I'll test them tomorrow.

**Comment by bqbn** [comment]
> Can you deploy the changes on dev when you're done ? I'll test them tomorrow.

Done and pushed to -dev.

**Comment by diox** [comment]
It seems to be working well. Caching for the API on dev no longer depends on cookie/user-agent header/dnt header, while regular pages still do.

Example with the homepage and user-agent:
```
curl -s https://addons-dev.allizom.org/en-US/firefox/\?me\=1 -H 'User-Agent: foo' -I | fgrep -i cache
cache-control: max-age=0
cache-control: s-maxage=180
x-cache: Miss from cloudfront

curl -s https://addons-dev.allizom.org/en-US/firefox/\?me\=1 -H 'User-Agent: foo' -I | fgrep -i cache
cache-control: max-age=0
cache-control: s-maxage=180
x-cache: Hit from cloudfront

curl -s https://addons-dev.allizom.org/en-US/firefox/\?me\=1 -H 'User-Agent: foo' -I | fgrep -i cache
cache-control: max-age=0
cache-control: s-maxage=180
x-cache: Hit from cloudfront

curl -s https://addons-dev.allizom.org/en-US/firefox/\?me\=1 -H 'User-Agent: bar' -I | fgrep -i cache
cache-control: max-age=0
cache-control: s-maxage=180
x-cache: Miss from cloudfront
```

With the API (notice you don't get a miss when you change the User Agent):
```
curl -s https://addons-dev.allizom.org/api/v5/addons/search/\?me\=1 -H 'User-Agent: foo' -I | fgrep -i cache
cache-control: max-age=180
x-cache: Miss from cloudfront

curl -s https://addons-dev.allizom.org/api/v5/addons/search/\?me\=1 -H 'User-Agent: foo' -I | fgrep -i cache
cache-control: max-age=180
x-cache: Hit from cloudfront

curl -s https://addons-dev.allizom.org/api/v5/addons/search/\?me\=1 -H 'User-Agent: bar' -I | fgrep -i cache
cache-control: max-age=180
x-cache: Hit from cloudfront
```

**Comment by AlexandraMoga** [comment]
@diox before I start retesting the cache functionality, do you have some instructions that I should follow?

**Comment by diox** [comment]
Nothing in particular no

**Comment by AlexandraMoga** [comment]
I've tested the API and frontend caching in parallel to see if the functionality remained unchanged - i.e. requests being cached for ~3 minutes for unauthenticated users and bypassed for authenticated users. These functionality principles are still applicable for the endpoints and pages I've tested with.

I've also covered add-on regional restrictions and the functionality remains unchanged here as well (*). 

@diox I have some observations:
- for the API caching, when I'm re-sending an authenticated request, the `x-cache` status returned is `RefreshHit from cloudfront`.  I didn't fully understand how this differs from `Hit from cloudfront`. Is this some equivalent for the `BYPASS` that used to be retuned previously for authenticated requests? 
- (*) georestrictions frontend caching, logged out: I'm opening an add-on detail page, from search results for example, make sure that the page is cached, then restrict the add-on in my region; I wait for a while, then refresh the detail page expecting to see the add-on restricted, since the cache should have expired, but the detail page is still available. I have the same outcome if I repeat the process several times.

**Comment by diox** [comment]
- A `RefreshHit` means that the CDN has that object in its cache but went to the origin to refresh it because it was potentially stale, and the origin returned the same thing the CDN had cached. This is probably happening because although you're sending an authenticated request, the response for the API you're calling doesn't differ for authenticated requests.
- Georestrictions can take a little while to update (especially if you refresh right before the 180 seconds mark) but we've confirmed on Matrix that it eventually does.
