### ISSUE TITLE
Add rate limiting for user review edits

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17535]
We should add some rate limiting for editing existing user reviews.

I'd suggest 5 edits per minute. Should that be also counted against the review, i.e. 5 edits  (of the same review) per minute?

**Comment by diox** [comment]
I don't think we need to care about which review the edit is from - 5 edits per minute total should be more than enough.

**Comment by bobsilverberg** [comment]
Why exactly do we need this? Is it to reduce traffic from a possible automated attack? If not, why do we actually care if someone updates their review of an add-on hundreds of times?

**Comment by diox** [comment]
Purely to reduce potential load on the database.

**Comment by bobsilverberg** [comment]
Is this a common problem? Do we have any data on how often it happens? Do we have other endpoints that could potentially be abused like this that are also not protected? I'm not convinced that the benefit of adding the code will outweigh the cost.

**Comment by diox** [comment]
This is not a problem yet as far as we know. Most endpoints already have rate limiting through DRF throttling mechanism, and we should definitely add some to those which do not before we run into some issues and not after.

There isn't much code to add, and in fact already do have a rate limit of 1 user review created per minute, it just specifically ignores edits at the moment because at the time we didn't have a good idea of what that limit should be.

**Comment by ioanarusiczki** [comment]
@diox 
I tested this on AMO stage - FF90(Win10):

Frontend :
- 5 consecutive PATCH operations -> Request was throttled. message is displayed at number 5
- 1 POST + 4 PATCH operations -> Request was throttled. message is displayed at PATCH nr.4
- 4 PATCH+1DELETE  -> Request was throttled. message is displayed at DELETE
- editing rating stars without text at the fifth attempt -> Request was throttled. message is displayed
- editing 5 different ratings (for 5 different addons) , at the fifth attempt -> Request was throttled. message is displayed

API:
- 5  consecutive PATCH operations -> I received a 429 "Too Many Requests" at number 5 

Should be as expected.
