### ISSUE TITLE
API calls from code-manager are failing because of CORS errors

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17537]
## STR

1. Go to: https://code.addons-dev.allizom.org/
2. Login or try to browse an add-on version

## Got

> NetworkError when attempting to fetch resource.

And too many CORS errors in the devtools console, e.g.:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons-dev.allizom.org/api/v5/accounts/profile/?lang=en-US. (Reason: CORS preflight response did not succeed).
```

## Expected

Not that. 

---

See also: https://github.com/mozilla/addons-server/issues/17521

**Comment by diox** [comment]
I've added `Access-Control-Request-Headers` and `Access-Control-Request-Method` to the headers forwarded to origin requests, that fixed the problem for me.

**Comment by ioanarusiczki** [comment]
@diox The only place I see CORS errors - 403 on -dev is when I log out and then try to login. On fxA page - I see some errors in the network

![on fxA page](https://user-images.githubusercontent.com/33448286/126978176-d4965c37-02a9-4f7c-a385-d181b2a99d40.png)

**Comment by diox** [comment]
Those are unrelated.

**Comment by ioanarusiczki** [comment]
@diox Then let me know if I should file this on fxA side.

**Comment by diox** [comment]
Probably doesn't hurt to file on FxA's side.

**Comment by ioanarusiczki** [comment]
@diox
I cannot reproduce the above issue then. If I navigate to all version page I only get a console message "No addon manager, cannot set add-on status". Also code manager files on -dev are loading without errors. 

I was pretty sure that the above errors are related to this since login was mentioned.  I filed it here https://mozilla-hub.atlassian.net/browse/FXA-3796 because the errors appear when the fxA stage page is loaded and before I click the Sign In 
![CORS in COnsole](https://user-images.githubusercontent.com/33448286/126985994-fda153ce-4889-46e8-861a-cc41a29d4818.png)

**Comment by ioanarusiczki** [comment]
@diox fyi - I've noticed the issue being reproducible on all AMO servers - updated it in fxA
