### ISSUE TITLE
drop ShelfManagement model

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17573]
We currently have a `ShelfManagement` model, that contains enabled state and shelf position, and `Shelf`, that contains all of the details about the Shelf.  The difference between the two would enable Editorial to build up a collection of `Shelf` modules that would only be added to a `ShelfManagement` when needed.  

But that's not how it's ended up being used so the two models just add extra complexity when creating a new shelf (you have to create the `Shelf` fix; then the `ShelfManagement` object) and in code, with little benefit operationally - any unused shelves can just be left as `enabled=False`.  The code and tests are also larger with two models.

**Comment by eviljeff** [comment]
marking QA extra because it's pretty important this tool is working for Editorial to use.  

Practically, there shouldn't be any difference in functionality, apart from the enabled and position that were previously in the `ShelfManagement` instances are now directly set in the `Shelf` instance.

**Comment by ioanarusiczki** [comment]
@eviljeff 

On -dev:
- perhaps because of https://github.com/mozilla/addons-server/issues/16559 being fixed, I can now enable using the same position (3) as it's right now in django - multiple shelves. They're all displayed on the frontend keeping the same position if I reload the homepage. 
 
![position](https://user-images.githubusercontent.com/33448286/127309044-2b7d4b18-8b3d-4733-ae29-1021a30ad273.png)

- I could delete from the shelf module enabled or disabled shelves (I don't remember if deleting an enabled shelf was possible or it is expected) 
- I ran into some server errors while trying to delete shelves - filed https://github.com/mozilla/addons-server/issues/17581
- I could do the basic operations without errors, which means, creating and adding into a specific order shelves using `admin/models/discovery/homepageshelves/` so except what I've mentioned above , it looks good 👍

**Comment by eviljeff** [comment]
>     * perhaps because of [The homepage shelves list can't be saved because of an incorrectly detected position overlap error #16559](https://github.com/mozilla/addons-server/issues/16559) being fixed, I can now enable using the same position (3) as it's right now in django - multiple shelves. They're all displayed on the frontend keeping the same position if I reload the homepage.

yep.  There aren't any constraints on position or enabled state so it's possible to have two enabled shelves in the same position.  

>     * I could delete from the shelf module enabled or disabled shelves (I don't remember if deleting an enabled shelf was possible or it is expected)

There wasn't any prohibition before for deleting a `ShelfManagement` instance when it was enabled.
