### ISSUE TITLE
Check support for Firefox versions over 100

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#17574]
As Firefox versions > 100 are not too far off it would be good to check if there are any issues from using Firefox versions that are >= 100 and ensure we have tests covering those areas. Feel free to add details to this bug of what those areas are, or create new bugs as needed.

Hopefully this will be a non-issue but it wouldn't hurt to be sure.

**Comment by diox** [comment]
This should have been covered when we did https://github.com/mozilla/addons-server/issues/6016

**Comment by eviljeff** [comment]
for app version comparison we should be good up to Firefox 65535

**Comment by Rob--W** [comment]
The update comparison logic has a hardcoded threshold of 99: https://github.com/mozilla/addons-server/blob/d9467f6030b3a3e4642950e415ed118fc823b74a/src/olympia/versions/compare.py#L131

@diox  Could you check the impact? I looked at this code because I was looking for a potential cause of the inability to receive langpack updates (https://bugzilla.mozilla.org/show_bug.cgi?id=1732506)

**Comment by diox** [comment]
As mentioned in the docstring of this function, this only applies to the minor parts of the version. So we can't have a firefox version xx.100, but we can have a version 100.yy (technically up to 65535.y.z.w as @eviljeff pointed out above)

**Comment by ioanarusiczki** [comment]
@diox Let me know how to test around this. 
Thanks!

**Comment by ioanarusiczki** [comment]
@diox 
1. I did not have problems submitting addons with min version 100.0, 100.0.2, 100.* or lang packs with min 100.0, max 100.* 
2. I could not install the submitted addons:
- I tried with the pref you mentioned above + I added a custom device with this user agent string Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0 
- I tried with another pref general.useragent.override with the string ` Mozilla/5.0 (Windows NT 10.0; rv:100.0) Gecko/20100101 Firefox/100.0` 
- And I even let both prefs set but the same result:

![cannot install](https://user-images.githubusercontent.com/33448286/157059241-1ffdec99-da6f-4069-a196-da4b0f1e002e.png)

**Comment by diox** [comment]
Uh right, didn't think this through. The actual Firefox version will need to match to complete the install. But if AMO let you through, we can consider it's ok (Ideally we'd test with a custom Firefox build that has the right version, or wait for 100.0 to hit Nightly)

**Comment by ioanarusiczki** [comment]
@diox 
- I could file a followup for the installs from AMO and update versions from about:addons (reading the previous issue I tried testing that part too but it won't work either), and make some testing when Nightly hits 100.0)
- I don't know what the search API should return for
 https://addons-dev.allizom.org/api/v5/addons/search/?app=firefox&appversion=100.0
I get 66285 addons in response, I thought I should see less, only those compatible for 100.0 or when going to 100.0.2 only those with min version specified for 100.0.2 
I can make requests using as appversion any numerical number as string, for example: 
https://addons-dev.allizom.org/api/v5/addons/search/?app=firefox&appversion=1000000000000000000

**Comment by diox** [comment]
> * I don't know what the search API should return for
https://addons-dev.allizom.org/api/v5/addons/search/?app=firefox&appversion=100.0
I get 66285 addons in response, I thought I should see less, only those compatible for 100.0 or when going to 100.0.2 only those with min version specified for 100.0.2

You're seeing all add-ons compatible with 100.0. So all add-ons with a min version *lower or equal* than 100.0, and, *if they have strict compatibility set*, with a max version higher or equal than 100.0.

**Comment by ioanarusiczki** [comment]
@diox 
Then the search API should be fine. 
Looking at the release date for Nightly 100.0 it's today, I should be able to test installs soon, so there's no point in making a separate issue.

**Comment by ioanarusiczki** [comment]
@diox 
I made some checks on FF Nightly 100.0a1 and here are my results:
2. Addon installs with strict min version  100.0a1 are installed
- strict min version < 100.0 -> are installed
- strict min version is 100.0 -> I get a message that the addon is not compatible with 100.0a1 but I think that's expected
- strict min version > 100.0 such as 100.0.2 or 100.2.0 -> "You need an updated version of Firefox for this extension", should be expected

3. Lang pack installs: 
- I could install a lang pack with min 100.0a1 and max 100.*
- I could not install a lang pack with min 100.0 and max 100.* because I get the incompatibility message (as above , it's because Nightly is on 100.0a1)
- I could not install a lang pack with min 100.0a1 and max 100.0a1 or min 100.0a1 with max 100.0a2. I get "This add-on is not compatible with your version of Firefox." and button is not active.
Similar, I tested with FF 97.0.1 , a lang pack with min 97.0.1 max 97.0.1. Another one with min 97.0.1 and max 97.0.2 -> cannot install such lang packs, I get "You need an updated version of Firefox for this extension".  
I see that on prod lang packs have the min "97.0" and max "97.*" so I don't know if using a different max instead of "xx.*" must work. 

4. The update service: 
- manual updates work as expected
- I don't get automatic updates yet with Nightly 97.0a1. I could see that they work on 97.0.1. Can't conclude yet. I'll try again.

**Comment by ioanarusiczki** [comment]
@diox 
I had the feeling I did not test the update service right ( I found what I was not doing right)
I checked for manual and automatic updates on -dev, -stage and -prod with FF97.0.1 and FF 100.0a1 and it work as expected.
