### ISSUE TITLE
The addon detail card is no longer displayed in admin Abuse reports

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#17629]
Follow up for #17507

### Describe the problem and steps to reproduce it:
1. Go to the Abuse Reports model in admin tools
2. Select an abuse report for a public add-on from the list - see https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/25580/change/
3.  Notice the layout and contents displayed in the first section of the page

### What happened?
The section is called "Unknown Add-on" and is missing some details

### What did you expect to happen?
The section should contain and add-on info card, similar to what we have on the add-on review page, and list all the Abuse reports submitted for the same add-on. This is an example of an older abuse report and how the page should look like: https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/25556/change/

[current layout]
![image](https://user-images.githubusercontent.com/31961530/128016202-f28b47e2-8a82-4a18-ae4f-6623b4f6b5a0.png)

[before]
![image](https://user-images.githubusercontent.com/31961530/128016219-746585a6-ad32-4f19-a8ab-7807b7f787c2.png)

**Comment by diox** [comment]
Yes, this was done on purpose, sort of. The problem is that we can't know for sure this is the right add-on to link to. In production, the abuse reports are submitted through Firefox (unless using another browser, of course) even for AMO, and we receive the `guid`. But it could be a report against any of the deleted add-ons sharing that `guid`, we don't know! So I stopped linking to the add-on (we were picking the latest available) and that in turn hid the card from the admin.

Ideally we'd show something aggregating all data from all possible add-ons that have/had that guid, or maybe just link to the review page.

**Comment by wagnerand** [comment]
If there are multiple add-on instances and we can't or don't want to show an add-on card for each, we could show just links to each instance. If there is only one add-on instance, showing the card would be great, but if needed, a simple link would probably do as well.

**Comment by diox** [comment]
We'll now show the card from the matching add-on by guid.

**Comment by AlexandraMoga** [comment]
I've verified this issue on stage and the addon details card is now displayed on the abuse report page. 

[guid belongs to only one addon => addon card is displayed](https://addons-internal.stage.mozaws.net/en-US/admin/models/abuse/abusereport/45657/change/)
![image](https://user-images.githubusercontent.com/31961530/181214000-6591405c-a011-493c-bb87-cdccd1c3dd13.png)




> We'll now show the card from the matching add-on by guid.

@diox I couldn't verify this properly since we can't create  add-ons with a reused guid anymore but we do have some deleted addons with reused guids on the site. That being said, I don't quite understand how we decide which addon card to display on the [abuse report page](https://addons-internal.stage.mozaws.net/en-US/admin/models/abuse/abusereport/45667/change/). This is the [review page]() for this add-on, where the other addon sharing the guid is visible.

**Comment by diox** [comment]
Yeah, with reused guids we have no way to tell which add-on the report, so we have to either show all of them or pick one. Since we've disabled guid reuse entirely at the beginning of the year (and I've landed a clean-up patch removing the waffle switch for this alongside that patch in https://github.com/mozilla/addons-server/issues/19501) I've decided to ignore this here, because I didn't want to show multiple add-on cards in this admin.
