### ISSUE TITLE
Allow the current tag to be referenced in shelf copy

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17689]
For a homepage shelf with an endpoint type `random-tag` we might want to craft a title or footer_text referencing the random tag returned, but this isn't possible.  We should add support for specifying a `{tag}` token or similar in strings.

**Comment by AlexandraMoga** [comment]
The `{tag}` placeholder can be added in Homepage shelves - in shelf title and footer text -  with endpoint `random-tag`.  Frontend tag shelves will display the actual tag for the matching results:

![image](https://user-images.githubusercontent.com/31961530/129572587-b241fc1f-5ca7-4ca0-9536-3b8558486a3b.png)


When used in other endpoints, the `{tag}` placeholder has no effect - i.e. it's interpreted as plain text.

This issue is verified fixed on -dev.
