### ISSUE TITLE
Add 'utm' parameters to the Source code submission links

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#17723]
Follow up for #16753 

### Describe the problem and steps to reproduce it:
The links for Source code upload displayed in the add-on submission flow should be:
https://extensionworkshop.com/documentation/publish/source-code-submission/?utm_source=addons.mozilla.org&utm_medium=devhub&utm_content=submission-flow

Currently, the links are pointing to https://extensionworkshop.com/documentation/publish/source-code-submission/, without `utm`s

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @eviljeff

**Comment by leni1** [comment]
Hello all. I would like to work on this if that's okay.

**Comment by caitmuenster** [comment]
Hey @leni1, welcome! 🙌 Go for it. We'll assign you to the issue once you submit a PR (draft PRs are fine!).

**Comment by AlexandraMoga** [comment]
@eviljeff there are some issues with this patch. As far as I've noticed, the submission flow features the source code submission link in two locations:

1. https://addons-dev.allizom.org/en-US/developers/addon/{addon}/submit/source-listed
![image](https://user-images.githubusercontent.com/31961530/134134858-40e20c26-5aba-43de-a6cb-98f7efe5c294.png)
In this location, the "Source Code Submission" link points to https://extensionworkshop-dev.allizom.org/documentation/publish/source-code-submission?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=submission, but this was already done in #17831.
Secondly, the current `utm`'s - `utm_source=addons.mozilla.org&utm_medium=referral&utm_content=submission` do not match what was initially proposed - `utm_source=addons.mozilla.org&utm_medium=devhub&utm_content=submission-flow`. Maybe @caitmuenster can comment on that.
Lastly, even if the `utm`'s are present in our link, once you click on the link to open the Extension workshop page, the `utm`'s are not preserved - i.e. the destination link will be https://extensionworkshop-dev.allizom.org/documentation/publish/source-code-submission/

2. https://addons-dev.allizom.org/en-US/developers/addon/{addon}/submit/details
![image](https://user-images.githubusercontent.com/31961530/134137628-f9adc142-600b-4353-ac88-ff0306331996.png)
This is the second location where the link is featured and, according to the [PR changes](https://github.com/mozilla/addons-server/pull/17924/files), this seems to be the place where the updates were made. However, I can't see any `utm`'s in this link in DevHub.

**Comment by eviljeff** [comment]
So, what's happened here is both Leni and I have taken the url specified literally; searched for it; and found there is only one place that is currently written as `https://extensionworkshop.com/documentation/publish/source-code-submission/`, and that's in `describe_minimal.html`. Used for new add-ons with an unlisted version (and subsequent listed versions when all the metadata was defined during the first listed version submission)

But almost the same url is also defined for:
- describe.html - that's your 2. - where it's written as `https://extensionworkshop.com/documentation/publish/source-code-submission` - note the lack of trailing slash.  (Used for new add-on submissions with a listed version)
- source.html - that's your 1. - where it's written as `'href="%s/documentation/publish/source-code-submission?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=submission" target="_blank" rel="noopener noreferrer"'|format(settings.EXTENSION_WORKSHOP_URL)`.  This already has the utm params, but have been added without the slash, so they get lost.  Also `utm_content=submission` rather than `utm_content=submission-flow` as you noted.
- source_form_field - where it's written as `{{ settings.EXTENSION_WORKSHOP_URL }}/documentation/publish/source-code-submission/?utm_source=addons.mozilla.org&utm_medium=devhub&utm_content=submission-flow"`.  This one is correct because it has the utm params _and_ the trailing slash 🎉 

@leni1 would you be able to create another pull request that fixes the two other urls that @AlexandraMoga highlighted?  (describe.html and source.html)

**Comment by leni1** [comment]
@eviljeff sure. Happy to do this.

**Comment by AlexandraMoga** [comment]
I've reverified the source code submission links to Extensionworkshop and now we have:

1. for https://addons.allizom.org/en-US/developers/addon/{addon}/submit/source-listed:
![image](https://user-images.githubusercontent.com/31961530/135409643-b7bbdf86-e38f-4503-9879-cc8b5931a688.png)
https://extensionworkshop.allizom.org/documentation/publish/source-code-submission/?utm_source=addons.mozilla.org&utm_medium=devhub&utm_content=submission-flow => the `utm`'s are preserved once the transition to EW is made

2. https://addons.allizom.org/en-US/developers/addon/{addon}/submit/details
![image](https://user-images.githubusercontent.com/31961530/135410898-a4d7764e-d886-4d17-95da-4b004177e2c3.png)
https://extensionworkshop.com/documentation/publish/source-code-submission/?utm_source=addons.mozilla.org&utm_medium=devhub&utm_content=submission-flow => the `utm`'s are preserved once the transition to EW is made

This issue is verified fixed on stage.
