### ISSUE TITLE
Add Tags admin to discovery edit permission

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17784]
Scott needs to be able to add/remove tags as part of the homepage editorial process.

**Comment by ioanarusiczki** [comment]
@eviljeff 

- With a mozilla e-mail address, an account with Admin:Tools,Discovery:Edit permissions can access the Tags module and enable/disable tags. 
- only with Discovery:Edit the account cannot access the admin tools so in order to test this I added the user to Discovery Recommendations Editors group on -dev.
