### ISSUE TITLE
fix failing `test_temporary_worktree` test

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17828]
Since https://github.com/mozilla/addons-server/commit/fdfc355fa18237752285c99d6628b369138a72fd CI has been failing with a single test - `test_temporary_worktree`.  

First thoughts were that the pytest bump from 6.2.4 to 6.2.5 was to blame but when that reverting that didn't fix it, further investigation pointed to a python upgrade from 3.8.11 to 3.8.12 (we don't specify the minor python version in our `Dockerfile` and circleci config - just 3.8 - and the latest version in the prebuilt images gets used).

https://github.com/eviljeff/olympia/commit/4927df46a86c1c06c1ae82ed90bf9441fd34eac5 confirmed that specifying 3.8.11 fixed the test fail. Upgrading to the latest 3.9 python didn't fix it either - there was a 3.9.6 release around the same time that contained all the same fixes as 3.8.12 had.

**Comment by diox** [comment]
That test confuses me - it's trying to do `git worktree list` but at this point I don't think there is any guarantee a worktree has been set up at all ? And if there is one, it might be from another test ? I tried to address this in https://github.com/mozilla/addons-server/pull/17829 but it still failed, despite passing locally.

For the moment we should probably skip it.

**Comment by diox** [comment]
CircleCI's `cimg/python:3.8.12` image is built from `cimg/base:2021.07`.  `cimg/python:3.8.11` image was built differently, from `cimg/base:2021.04`. This is visible in this commit: https://github.com/CircleCI-Public/cimg-python/commit/9c3e961350aa1bbafd27bd10a5827c4dac6f6bc6

It matters, because although it's the same version of Ubuntu underneath, it's not the same version of `git`: https://github.com/CircleCI-Public/cimg-base/commit/cf548c39e1559123a0719efa777d5e9aa1b71b1c

```
% docker run -it cimg/python:3.8.11 git --version
git version 2.25.1

% docker run -it cimg/python:3.8.12 git --version
git version 2.33.0
```

So I suspect our problem is that the output of `git` has changed - no longer including the `.git` in the result. As we're using CircleCI image instead of the regular base python image, we get this difference in behavior in CI.
