### ISSUE TITLE
Allow excluding more than one rule on scannerresult admin page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17898]
The _scannerresult_ admin page currently allows to exclude one scanner rule from the view. Due to changed needs, admins need to be able to exclude more than one rule now.

**Comment by ioanarusiczki** [comment]
@diox 

On /scannerresult page from admin dev I see the last filter being modified:

- selection of multiple consecutive rules is possible using "Shift" key. Same for all rules.
-  to select 2 or 3 random rules,  I added manually query params such as `?exclude_rule=40&exclude_rule=20`.  

Let me know if that's the expected behavior.

**Comment by wagnerand** [comment]
@ioanarusiczki fwiw, you can select non-consecutive rules by using the CTRL key (CMD on Mac).

**Comment by ioanarusiczki** [comment]
@wagnerand Yes, worked for me 👍
