### ISSUE TITLE
Logged out on every new Firefox session

### ISSUE THREAD

**Issue by Quicksaver** [mozilla/addons-server#1789]
Before FxA, I could exit and restart Firefox without being logged out of AMO. It would maybe log me out once a month or every couple of months, which was acceptable. Now it logs me out every time I exit Firefox.

**Comment by Quicksaver** [comment]
To elaborate, this happens regardless of if I choose to remember session data between Firefox restarts or not. According to a conversation on IRC, it's apparently saving the login in a session cookie, then it definitely should be kept in that case.

And even though the "remember me" checkbox is gone, I'd like to keep the previous behavior of keeping me logged in across Firefox sessions (persistent cookies?).

**Comment by andymckay** [comment]
@ryanfeeley since we are planning on removing the migration and bouncing straight to FxA and back, there wouldn't be anyway to record the users preference if they wanted a session cookie or a longer term cookie. In the past this used to be done through the "remember me" checkbox.

Any advice on how to ask for that preference?

**Comment by ryanfeeley** [comment]
I'm not sure how this is managed. @rfk?

**Comment by rfk** [comment]
This...seems complicated.  Ideally we'd find prior art here - how do other OAuth-consuming sites deal with this when logging in with google, github, etc?

I doubt we can successfully ask for this preference within the FxA login UI.  Perhaps it can be done on a post-login landing page or doorhanger or similar in AMO?

**Comment by andymckay** [comment]
It feels like we should assume a session cookie by default, a post login landing page seems awkward (although maybe our awesome UX could make it less so), the FxA flow is so smooth right now.

**Comment by ryanfeeley** [comment]
It is likely that users feel that the previous behaviour was fine: stay logged in as long as possible. How long can we do @rfk?

**Comment by rfk** [comment]
@andymckay IIUC this is all managed by an AMO-specific cookie, and is not tied back to FxA in any way, correct?

> It feels like we should assume a session cookie by default

Sorry, it's not obvious to me whether this corresponds to the "remember me" option being checked or unchecked.  IIUC @ryanfeeley's proposal is that we should just act as though it were always checked, and remember the login until they explicitly log out.

> How long can we do @rfk?

Since the session cookie is managed by AMO, there's no restriction on it from the FxA side, AMO can make it last for as long or as little as they like.

Is the user-expectation here that they will remain logged in to AMO as long as they remain logged in to FxA?  Perhaps more importantly: will users expect logging out of FxA to also log them out of AMO?

I have a few suggestions for how we could make that happen (there's a silently-reconfirm-an-existing-login flow we could use) but they're non-trivial, so let's agree about what we want before we get too far into how to do it.

**Comment by andymckay** [comment]
Correct, the cookie is managed by AMO, but when we remove the migration flow, there will be almost no AMO UI involvement in the login flow. Which means there isn't really any way to ask about the length of the cookie.

I don't know if users expect logging out of FxA to log them out of AMO. Does that imply something along the lines of, if the user is logged into FxA, we can log them in automatically?

**Comment by tofumatt** [comment]
In terms of the UX of "remember me", I think it's best to assume a long cookie/login session by default, then simply offer the "log out" button (which we already do) to destroy the session. This way users who _do_ want only a session login can explicitly confirm they've signed out (rather than trust us to handle it), but otherwise users stayed signed in. TravisCI, Twitter/Facebook Oauth apps, etc. all tend to use longer cookies and **not session cookies** by default in my experience.

It's also a much nicer UX than having to sign in every time. Having metrics on how many users previously used "remember me" or how many use the "log out" button would help; not sure if we have 'em 🤔

**Comment by rfk** [comment]
> Does that imply something along the lines of, if the user is logged into FxA,
> we can log them in automatically?

Google's OpenID Connect auth has a flow like this that I've been trying to find a good summary of, but have so far failed.  It offers a way to silently refresh a login session by bouncing the user back through the OAuth flow without showing any UI.  If the user is still logged in to Google on that browser, the OAuth flow completes silently and you can extend your local session cookie; if not then it gives an error and you throw the session away.

This sort of thing *might* let you get the best of both worlds if we added it in FxA.  You could have a relatively short-lived AMO session cookie, but the ability to silently refresh it with a new login session as long as the user remains logged in to FxA.

> TravisCI, Twitter/Facebook Oauth apps, etc. all tend to use longer cookies and not session cookies by default in my experience

I broadly agree that we should go with the flow and follow prior art from other big oauth integrations here, as it seems most likely to be what users expect.
