### ISSUE TITLE
Finally actually drop `files` from `VersionSerializer` (for api/v5)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17955]
Follow-up for #17945 

in #17839 we replaced `files` with `file` but didn't actually drop `file` because frontend was relying on it.  Now mozilla/addons-frontend#10900 is merged that's no longer the case and we can clean it up.

To be safe we don't want to make the change until after mozilla/addons-frontend#10900 is deployed, i.e. we should merge the pr after the 2021.09.30 tag.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I verified with Postman:
-  the detail, versions, version detail , search APIs - "files":[] has been dropped from v5, kept on v4/v3. 
- v5 displays the "file":{} wihout "is_restart_required": and "is_webextension": being removed (because of https://github.com/mozilla/addons-server/issues/17390 and https://github.com/mozilla/addons-server/issues/17946 ).  I also see "platform" being removed - is that ok?

**Comment by eviljeff** [comment]
@ioanarusiczki looks okay.  https://github.com/mozilla/addons-server/issues/16466 dropped platform earlier in the year

**Comment by ioanarusiczki** [comment]
@eviljeff Ah, thanks ! I did not remember this.
