### ISSUE TITLE
User lands on desktop view instead of /android/ after creating a new account

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17995]
STR:
1. Create a new account on an android device 
2. Observe the landing page 

Expected result:
https://addons.allizom.org/en-US/android/users/edit is displayed

Actual result:
User lands on https://addons.allizom.org/en-US/firefox/users/edit/ - the desktop view

![prod bug](https://user-images.githubusercontent.com/33448286/135267131-25290f41-ce77-4208-a59a-730048e331f6.png)

Notes:
- editing something on the page and then updating it with "Create My Profile" lands back on android view.
- not editing the profile and navigating to the homepage using the logo or to any other page - the desktop view will persist. 
- the issue is reproducible on all AMO servers.

**Comment by diox** [comment]
The flow looks like this:
Page the user is on (somewhere on /android/) -> FxA -> API callback -> User edit page (with an optional `next_path`)

The API callback is generic, it doesn't contain an `app` parameter, so when it's processed, the prefixer in the thread doesn't have an `app` set (normally set by middleware), so it falls back to its [`get_app()`](https://github.com/mozilla/addons-server/blob/9dccf58e1a977b5540980ca2e909996958638e22/src/olympia/amo/urlresolvers.py#L60-L76) implementation, which looks at the `User-Agent`, but since the CDN is configured to not forward that header for /api/ it then falls back to just `settings.DEFAULT_APP`, which is `firefox`. So when we reverse `users.edit`, we add the `firefox` prefix, and that's what users are redirected to.

if we called our `reverse()` with `add_prefix=False` then the edit URL would be app-less (also locale-less), and then the user would be redirected to the app-less version, user-agent based detection would be triggered, they would get redirected to the mobile version if they are on mobile.

Alternatively... we could try to be a little smarter, and look at the `next_path` if present, extracting the prefix from it (even if we aren't directly redirecting to it, because we want them to go to the profile edit page first). The advantage of doing that is that users would stay on the app+locale combination they were on, which might differ from what we'd detect from the headers.

**Comment by ioanarusiczki** [comment]
@diox I tested this on AMO dev with Android - after the first login I landed on https://addons.allizom.org/en-US/android/users/edit

![looks fixed](https://user-images.githubusercontent.com/33448286/135851897-fa7e62ee-c4c2-4ee4-ada8-d7f6b8706a0d.png)
