### ISSUE TITLE
Exclude `addon-submission-api` gate in stage config as well

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#18008]
We couldn't deploy this week's tag to prod because of an issue on the config, related to `DRF_API_GATES`. This fix was trivial, see: https://github.com/mozilla/addons-server/pull/18007.

We should have similar configs for stage/prod to avoid surprises like this one so let's try to have similar stage/prod configs as much as we can. We can start by disabling the `addon-submission-api` gate on stage too, given that it isn't very useful right now.

**Comment by eviljeff** [comment]
> We should have similar configs for stage/prod to avoid surprises like this one so let's try to have similar stage/prod configs as much as we can. 

It's a noble idea, but difficult to achieve much more than we have now - we have to define a lot of very similar values between stage and prod so it's not obvious if there are genuine functional differences.  

Also, because every setting value is evaluated immediately we end up having to redefine any setting that references an earlier one (e.g. once you define `DOMAIN` you have to redefine any setting that includes `DOMAIN`, like `SITEURL = 'https://' + DOMAIN`).  A while back I wrote a prototype of a `BaseSettings` class that had lazily evaluated values where a `StageSettings` could subclass a `ProdSettings` (that in turn inherited from `BaseSettings`).  But because we don't have any test code coverage for settings files it was difficult to develop into a final feature and I gave up.  I still like the idea though.

**Comment by willdurand** [comment]
Could we try to update both config files (instead of just one) when we plan on editing `prod.py`?

**Comment by eviljeff** [comment]
the gate is available on all envs now.
