### ISSUE TITLE
Fix the required fields for new addon/version submission for listed/unlisted versions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18035]
follow-up for #7811

Currently categories are required to create an add-on but aren't really needed unless the add-on has listed versions.
For the first listed version we want to require all the necessary metadata (name, summary, categories, version license) being defined if not available in the manifest, but not really for unlisted versions. This will necessitate some refactoring - probably moving some validation from AddonSerializer to VersionSerializer.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- "name" is a mandatory key in manifest.json, I could not submit a listed/unlisted addon without it -> I run into a 400, "addon is not valid" error.
- "summary" is not mandatory in the manifest, but if it is missing then it is required at API submission for a listed version. Unlisted versions can be submitted without "summary" -> I added it into the JSON {"categories": {"firefox": ["other"]}, "version": {"upload": "97fd7461b7cc4ca6b2a7fcdd5e44edf6", "license": 18}, "summary":{"en-US":"this is an API testing"}} and got a 201.
- unlisted addons can be submitted without category or licence. Listed addons require both. 

- now that unlisted first versions don't need category or licence I submitted an addon and then I tried to submit a new listed version but I run into a 400 with this message:
{
    "non_field_errors": [
        "Addon metadata is required to be set to create a listed version: ['categories']."
    ]
}
The JSON is : `{"upload": "1bcc031f7aea4f698492d27066d67927", "license": 18, "categories": {"firefox": ["other"]}}`

Possible that the JSON should look different, I can't tell or if it's a new issue because of the changes.

**Comment by eviljeff** [comment]
>     * now that unlisted first versions don't need category or licence I submitted an addon and then I tried to submit a new listed version but I run into a 400 with this message:
>       {
>       "non_field_errors": [
>       "Addon metadata is required to be set to create a listed version: ['categories']."
>       ]
>       }
>       The JSON is : `{"upload": "1bcc031f7aea4f698492d27066d67927", "license": 18, "categories": {"firefox": ["other"]}}`

You can't set add-on metadata with the version api endpoint - if the categories (or name or summary) aren't defined they need to be set beforehand with the add-on api. (Generally, with rest framework, you can only CREATE/PATCH properties on an endpoint that you GET, and you don't get all add-on details with the version api endpoint.  I had to expand the syntax slightly for add-on CREATE or we'd end up with empty add-ons without versions)

**Comment by eviljeff** [comment]
I'm assuming the rest of the points were as you expected?

**Comment by ioanarusiczki** [comment]
@eviljeff 

First I made a PATCH request {"categories": {"firefox": ["other"]}} and then I could create the new listed version with {"upload": "1bcc031f7aea4f698492d27066d67927", "license": 18}.  That's the workaround for the unlisted v1 with listed v2. Or when v1 is created the categories can be set with license. 

It's a bit confusing, I thought that categories should be accepted at new version submissions same way as license.  

The rest of points were expected.
