### ISSUE TITLE
Fix Version queries that don't scale when webext permissions are loaded

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18047]
When writing the patch for #17946 I found the querysets in AddonVersionViewSet, AddonVersionViewSet, and reviewers.views.review end up with webext_permission queries for each Version instance returned.  Adding a `prefetch_related` didn't help (there were more queries instead).  I suspect the fix will have to made with, or inside, the version transformers.

**Comment by diox** [comment]
QA: this should be a transparent change, it's worth checking that permissions still show up in the add-on detail / versions list APIs, as well as in the review page. You can also check that the language tools API / page still works correctly.

**Comment by ioanarusiczki** [comment]
@diox 
- permissions looks good, checked the APIs and the frontend detail pages. (I think you meant that instead of the review page)
- language-tools API also responds and displays lang packs and dicts as expected , also works as expected with Query Parameters (I used the [docs](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#language-tools))
- I've still one scenario left but I'll get back with final results tomorrow.

**Comment by ioanarusiczki** [comment]
@diox I don't know why I was thinking of the frontend reviews pages. 

I checked the review pages - > permissions are displayed for each version

I also checked with extensions.getAddons.langpacks.url changed for -dev -> that languages are displayed for FF into settings

![languages](https://user-images.githubusercontent.com/33448286/175015051-ca915cba-4bea-419b-b33a-2a37985de379.png)
