### ISSUE TITLE
Unexpected submission scanner results exclusion behavior 

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#18040]
### Describe the problem and steps to reproduce it:

1. Imagine you have a result that matches both a rule A a rule B.
2. In the scanner result admin, exclude both rules A and B.

### What happened?

The result is shown.

### What did you expect to happen?

The result is not shown.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
From Matrix discussion about it:
- This is because of the workaround we have to support showing results that match an excluded rule but also something else (if a result matches A, B and C, and you exclude A and B, you still want to see that result). This worked well when there was only a single excluded rule, but now it has this limitation if a result only matches the excluded rules.
- A better design would be to allow admins to choose multiple rules to filter on, and remove the exclusion filter. However this would make bookmarking a filtered URL problematic, because the included rules in a bookmarked URL would be out of date every time a new rule is added
- Instead of building a query that excludes the target rules, we should look into implementing the logic in the same as a multi-rules filter behind the scenes. Fetch all rules excluding the target rules, and _then_ filter on that list.
