### ISSUE TITLE
Record install origins declared in manifest for a given Version

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18134]
When a `Version` is created from a `FileUpload`, if the manifest had install origins declared (https://github.com/mozilla/addons-linter/issues/3972) we'll want to record them.

The model should look like this:
- `version`, a Foreign Key to the `Version`
- `origin`, the full origin string
- `base_domain`, the etld+1 base domain (in accordance to public suffix list) extracted from the origin for convenience (probably using `get_sld()` from https://pypi.org/project/publicsuffix2/ - making sure domains are in unicode first)

If there are more than one install origin for a given version, multiple instances of that model will be recorded to the database. To find all origins declared for a given version, we would group by `version` when fetching the rows from the database.

**Comment by diox** [comment]
Note: do all of this behind a waffle switch that we won't enable in stage/production until the linter work is ready.

**Comment by AlexandraMoga** [comment]
@diox I understand that we can't verify this issue until https://github.com/mozilla/addons-linter/issues/3972 is fixed, no?

Also, in the meantime, if you could add more details on how/where this verified once the linter issue lands?

**Comment by diox** [comment]
I didn't bother with an admin yet, so it's kinda tricky to verify for the moment. But once I do (https://github.com/mozilla/addons-server/issues/18242), you should be able to verify without waiting on https://github.com/mozilla/addons-linter/issues/3972.

- Uploading an add-on or a new version with `record-install-origins` waffle switch on and off should still work
- Uploading an add-on or a new version with `record-install-origins` waffle switch on and off should still work when the add-on has the `install_origins` set in manifest as described in https://github.com/mozilla/addons-linter/issues/3972
- When the switch is on, and `install_origins` is present in manifest, uploading an add-on or new version should create a new `InstallOrigin` instance record for each origin in the `install_origins` list in the manifest. For each, you should be able to see the `version`, `origin` and `base_domain` as described above.

https://github.com/mozilla/addons-linter/issues/3972 will add the validation of the values to prevent erroring on weird data - it's possible to test before it lands, though you could then encounter 500 errors or something that prevents the upload with intentionally bad data in `install_origins`.

**Comment by AlexandraMoga** [comment]
I've verified the new `install_origins` property on -dev with the `record-install-origins` switch on and off and I have the following results:

- switch off:
  - new addons and versions _without_ `install_origins` specified can be successfully submitted 
  - new addons and versions _with_ `install_origins` specified can be successfully submitted => no record of `install_origins` in the admin model

- switch on:
  - new addons and versions _without_ `install_origins` specified can be successfully submitted
  - new addons and versions _with_ `install_origins` specified can be successfully submitted => a record for each of the `install_origins` specified in the manifest will be created in https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/installorigin/


Observation:
- `install_origins` values not an array => 500 error at submission (when clicking continue after validation). I expect this (and other invalid values) will be caught by the linter once we have validation for this field. 
- addon with `install_origins` cannot be installed (addon appears to be corrupt error is displayed on the frontend). I get this is happening because Firefox is not supporting the property yet - https://bugzilla.mozilla.org/show_bug.cgi?id=1736902?

**Comment by diox** [comment]
Yes, https://github.com/mozilla/addons-linter/issues/3972 would force it to be an array, and we're still discussing how to tackle the Firefox side of things.
