### ISSUE TITLE
allow default_locale to be set/updated via the addon api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18235]
split from #18036

We'd like to be able to set during create, and update later, the default locale for the addon's translated strings.  This will probably need a lot of validation because it's easy to end up with an add-on with (apparently) entirely missing metadata because those strings aren't present in the newly selected default locale.

**Comment by AlexandraMoga** [comment]
I'm moving this to the following milestone since we won't push next week.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I tested various scenarios so I won't detail everything:

- with multiple locales declared in the _locales folder with information about name and summary , at addon create when the JSON also includes information about "name" or "summary" -> it will override the information from the archive -> which is expected

- a value for the default locale is required for ""description", "developer_comments", "homepage", "name",  "summary", "support_email" when these are added with a default_locale .  -> expected

- when making a PATCH in order to change the default_locale, the name and summary are the mandatory fields. I've noticed that dev hub also requires the "description" (which is an old thing, I am pretty sure but I think it should work the same way as the API)

**Comment by eviljeff** [comment]
> * when making a PATCH in order to change the default_locale, the name and summary are the mandatory fields. I've noticed that dev hub also requires the "description" (which is an old thing, I am pretty sure but I think it should work the same way as the API)

I forget the requirements for devhub - and it's changed a few times over the years.  Strictly required metadata to be approved for a listed version is name + summary + license + categories so I used that.

**Comment by ioanarusiczki** [comment]
@eviljeff 

Yes, it's been a bit difficult to understand what is going on but after making a comparison on the API versus dev hub I found some issues:
https://github.com/mozilla/addons-server/issues/19333
https://github.com/mozilla/addons-server/issues/19334 
https://github.com/mozilla/addons-server/issues/19335
