### ISSUE TITLE
UI issue in disco pane when closing the intro video at a certain moment

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#1824]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:44.0) Gecko/20100101 Firefox/44.0

Steps to reproduce:
1.Go to Tools-Addons in your browser
2.Select the Learn More button from "What are addons?" section
3.Immediately after second 48 , click close video

Expected results:
Video is closed and no UI issues are displayed 

Actual results:
UI issue in Featured Addons section

Please see screencast for this bug : http://screencast.com/t/XugsHkAbBVd

**Comment by andymckay** [comment]
This will occur at many places in the video because the video is changing the state of the page and not resetting it on close video. 

This is all being redesigned in the new discovery pane project for Firefox 48, so at this point I think we should close it and make a note if we do this in the future to try and clean up after ourselves.
