### ISSUE TITLE
Ensure a submission with a reserved GUID is already signed

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#18252]
When an add-on version is submitted to AMO with an ID that matches the set of [reserved IDs](https://github.com/mozilla/addons-server/blob/9a2767cb5f7532b576d2179011cbe2bf7b3dbdff/src/olympia/constants/base.py#L374), the submission can only pass if the file is already signed with the privileged certificate. This enforces that only Shipit can sign files for privileged add-ons.

**Comment by eviljeff** [comment]
Is this only for new submissions?  (if not, what about existing addons that may be using those guids and are not privileged add-ons)

**Comment by wagnerand** [comment]
I suppose it will be easier to do this for any submissions. The expectation is that existing add-ons using a reserved GUID will need to go through shipit, until phase 2 of the project (permission-based service ownership) is completed.

If it's easy to limit to new add-ons, we could also look into that and check for any unintended implications.

**Comment by eviljeff** [comment]
> If it's easy to limit to new add-ons, we could also look into that and check for any unintended implications.

it's just as easy to apply to all submissions, but what about existing add-ons using those guids?  iirc when we added the feature originally there were already some non-mozilla add-ons using those guids, and we've expanded the number of domains since then a few times.

**Comment by wagnerand** [comment]
I see. Yes, we should limit it to new add-ons then. As far as I understand, with the existing checks in place, at least we can be sure that there list of non-mozilla add-ons using reserved guids is not growing.

**Comment by diox** [comment]
Would that error message work ?
> Add-ons using an ID ending with this suffix need to be signed with privileged certificate before being submitted

For reference, the error message shown if you don't have the relevant permission (which we would keep, it would be an extra check and a separate error):
> You cannot submit an add-on using an ID ending with this suffix

**Comment by wagnerand** [comment]
> Would that error message work ?

Yes, sounds good, thank you!

**Comment by ioanarusiczki** [comment]
@diox 

- an addon using the list of reserved IDs mentioned above will not pass validation because of an error (plus Continue button is inactive) but while going on the full validation report this error is not present. 

![full validation report](https://user-images.githubusercontent.com/33448286/151809394-f1de16a6-0603-4f81-8c84-eaecdd6cc50d.gif)

- I think I found a signed mozilla sample and I added a reserved guid in the manifest -> it passes validation with one warning "Package already signed". I'll attach a sample. 

[mozillaorg_signed-1.0-fx.zip](https://github.com/mozilla/addons-server/files/7971403/mozillaorg_signed-1.0-fx.zip)
