### ISSUE TITLE
Use `developer.url` to set the homepage URL when present

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#18251]
We parse the manifest to retrieve the `homepage` value in: https://github.com/mozilla/addons-server/blob/92e53f4e0142324e35ac00c306e1581889587a99/src/olympia/files/utils.py#L398

This is based on `homepage_url` but it is possible to use `developer.url`, which overrides the value of `homepage_url` according to [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/developer):

> The object, and both of its properties, are optional. The "name" and "url" properties, if present, will override the author and homepage_url keys, respectively

We should update the `parse()` function to read `developer.url` when it is available.

We don't use the `author` value AFAIK, which is why this issue is about the homepage URL only.

Note: this issue is blocked by https://github.com/mozilla/addons-linter/issues/4008 (meaning we need to update the linter first).

**Comment by ioanarusiczki** [comment]
@willdurand 
I see this being fixed on linter 4.1.0 ->not yet on AMO dev which still shows the typo right now. 

![typo is fixed on 4 1 0](https://user-images.githubusercontent.com/33448286/140940335-c15ea5ce-94c8-43da-b317-8b71e00e085c.png)

**Comment by ioanarusiczki** [comment]
@willdurand labeled by mistake :P It was meant for https://github.com/mozilla/addons-linter/issues/4024

**Comment by ioanarusiczki** [comment]
@willdurand I've noticed that 'homepage_url' is present in dev hub if I use the key at the submission of version1. If I did not use it in v1 and then I add it in the manifest for the next version, it is not displayed.

**Comment by ioanarusiczki** [comment]
@willdurand 
When submitting a new addon on AMO dev "Homepage" from edit product page displays:
- the URL from "homepage_url" when it's available in manifest 
- the URL from "developer" when it's available in manifest
- the URL from "developer" when both keys are used in the manifest because "url" overrides "homepage_url"

As I mentioned, it is only applicable for v1 of an add-on. Newer versions don't override information for Homepage when "homepage_url" or "developer" are used in the manifest but "Homepage" field is editable from dev hub anytime.
