### ISSUE TITLE
Deny submissions that declare a privileged permission

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#18254]
⚠️ This is pending on https://bugzilla.mozilla.org/show_bug.cgi?id=1739114.

During submission, when a privileged permission is declared, submission should fail with an error message saying:

_This submission declares a privileged permission which requires it to be already signed with the privileged certificate._

**Comment by mixedpuppy** [comment]
The privileged permissions are:

Signing should verify at least one of the following permissions are in the permissions key of the manifest.

[
  "activityLog",
  "geckoViewAddons",
  "mozillaAddons",
  "nativeMessagingFromContent",
  "networkStatus",
  "normandyAddonStudy",
  "privilegedAddon",
  "telemetry",
  "urlbar",
]

**Comment by willdurand** [comment]
We'll implement new checks in https://github.com/mozilla/addons-linter (that should be transparent for AMO).

In https://github.com/mozilla/addons-linter/issues/4306, we'll add logic to detect privileged features and emit errors by default. If the XPI is already signed, the linter will NOT emit errors, though, because AMO accepts already signed privileged extensions. Here, the assumption is that the signature will be very likely the regular signature (and not the privileged one) because only the shipit pipeline should be able to sign XPIs with the privileged signature.

This shipit pipeline will also run the linter at submission (see: https://github.com/mozilla-extensions/xpi-manifest/issues/136) but it will pass a new CLI flag to the linter: https://github.com/mozilla/addons-linter/issues/4324. This flag will changes the linter's behavior to reject non-privileged extensions. The linter will except the `"mozillaAddons"` permission to be specified in the list of permissions in the `manifest.json` file.

**Comment by ioanarusiczki** [comment]
@willdurand 

- I verified on AMO dev, I submitted from dev hub the addons tested for https://github.com/mozilla/addons-linter/issues/4306#issuecomment-1134711505

Permissions used : activityLog, mozillaAddons, networkStatus, normandyAddonStudy, telemetry, urlbar

Example of such an error:

![error on AMO dev](https://user-images.githubusercontent.com/33448286/170274996-244711eb-bdb3-493f-92ea-7db779b50ee8.png)

- I also checked a mozilla signed addon -> it will pass validation 

![signed mozilla addon](https://user-images.githubusercontent.com/33448286/170275792-9e562df8-9f2b-4e70-b5b4-b38ed55f8222.png)

- and using "update_url" it will fail validation -> that's passing with linter CLI when  --privileged flag is used

![not allowed](https://user-images.githubusercontent.com/33448286/170276593-74eceb10-77d6-4cef-9fa0-f1101b6f614b.png)
