### ISSUE TITLE
Cannot install a complete theme after updating its compatibility

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#1829]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:44.0) Gecko/20100101 Firefox/44.0

Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/firefox/complete-themes/
2.Select a theme which is not compatible with FF44 and update its compatibility from Manage status and versions (https://addons.allizom.org/en-US/developers/addon/nasa-night-launch/versions)
3.Try to install the theme

Expected results:
Theme is installed without any issues

Actual results:
A message saying that the theme is not compatible with FF 44 is still displayed and the theme is not installed

Please see screencast for this bug : http://screencast.com/t/RetNSe3kTa

**Comment by vcarciu** [comment]
Same issue discovered for language packs

**Comment by EnTeQuAk** [comment]
Changing the compatibility on AMO does **not** change any compatibility values in the `install.rdf` file. The first will be used to show the green button but the actual value in the `install.rdf` is being used by Firefox to determine compatibility which is failing here since it hasn't been updated.

This is a wont-fix I think since it's working as expected imho. Feel free to reopen if I'm missing something though.
