### ISSUE TITLE
Wrong versions displayed in versions history page after one add-on file is disabled

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1831]
Steps to reproduce:
1. Sign in to AMO-stage Dev Hub with an admin account https://addons.allizom.org/en-US/developers/
2. Submit an add-on (i.e. test-stage-versions) and approve it
3. Disable add-on version
4. Add another file for that version and approve it (observe add-on status and check the View Listing page)
5. Add another version for that add-on and approve it
6. Check out View Listing->Version history page

Expected results:
Only the last version is displayed in version history public page.

Actual results:
After step 4, if "View Listing" link is clicked a 404 page is displayed (because the add-on status is INCOMPLETE: has a version with a file disabled and a file approved). 
After step 6, both versions are listed and available for installation in public pages.

Notes/Issues:
Verified on AMO-stage FF44(Win 7). 
The second file is not listed in any queue. Can be approved from add-on review page.
Screencast after step 4: http://screencast.com/t/YVjSfqO26
Screencast after step 6: http://screencast.com/t/axaKgXJZUk

**Comment by ValentinaPC** [comment]
This issue is also reproducing following other steps:
1. Submit Add-on - Approve it
2. Add a new file for that Add-on (don't approve the file)
3. Click "View Listing" - > 404 error
4. Add a second version -> Approve it
5. Click "View Listing" - Version history -> both versions displayed.

**Comment by shell15** [comment]
for an approved add-on we do show unreviewed versions in the history page.  something we need to consider when we do the style re-write for versioning (and a clear write-up of expected behavior).  in first situation logged in as admin.  in second situation it is user facing and logically should not see version 2 (but it's working).  

we're pretty certain it's expected behavior -but tagging @jvillalobos to confirm

**Comment by jvillalobos** [comment]
Yes, showing unreviewed versions is expected behavior, though I'd like to change that in the future (it doesn't make much sense now with faster review times and signing requirements).

As for the initial bug report, I'd like to know how the file was approved in step 4. Was it approved using the reviewer tools? Did it appear in the review queue?

**Comment by muffinresearch** [comment]
> Yes, showing unreviewed versions is expected behavior, though I'd like to change that in the future (it doesn't make much sense now with faster review times and signing requirements).

On the basis of this I don't think there's anything to do here.
