### ISSUE TITLE
Add logging and statsd timers around each important step of source code submission

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18337]
We want to add logging and statsd timing around the various steps in the source code submission views, to narrow down issues we've seen in #18105 when submitting large files.

Note that there are 2 different paths to upload source code: one is at submission, after you've uploaded your add-on or version, and the other is in the version edit view. We could maybe focus on just the submission one (/{locale}/developers/addon/{slug}/versions/submit/{version_id}/source, /{locale}/developers/addon/mante-armorne-sherrew/submit/source-listed and /{locale}/developers/addon/{slug}/submit/source-unlisted) which should be slightly less complex (see also https://github.com/mozilla/addons-server/issues/18336).

**Comment by bobsilverberg** [comment]
I've been looking into this, and I'm not sure where we can add this logging and timers. As I am reading the code, it looks like when someone submits a source code upload (for a version, in this case) it goes directly to the `submit_version_source` view. The code for that view seems to happen *after* we have received the form post, so it seems like that is too late to do any logging or timing. It seems like all of the processing is happening at the time of form submission, and, as I understand it, that is happening outside of the Django app. We do process the version upload differently, where we have JS controlling the upload, which happens when a user selects the file, as opposed to at form post time. Do we need to switch source code uploading to do something similar, or is there something else we can do to wrap the actual form post into something where we can log before and after?

**Comment by bobsilverberg** [comment]
@diox I have added the logging and timing to the submission flow in #18362. It looks like the other flow is in the [`version_edit`](https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/views.py#L1087) view. I know that https://github.com/mozilla/addons-server/issues/18336 was opened to address the fact that we have two different code paths for source upload, but I am wondering if I should just go ahead and add the logging to the `version_edit` path as well, for now, instead of waiting for #18336 to be addressed?

**Comment by AlexandraMoga** [comment]
@bobsilverberg I've verified source code submission from the source code submission form during add-on/version uploads and from the Manage versions page in devhub, with several archives of various sizes. I had no issues with the upload process.
Is there something more specific that should be tested to verify that the logging is captured correctly?

**Comment by bobsilverberg** [comment]
> @bobsilverberg I've verified source code submission from the source code submission form during add-on/version uploads and from the Manage versions page in devhub, with several archives of various sizes. I had no issues with the upload process. Is there something more specific that should be tested to verify that the logging is captured correctly?

Thanks @AlexandraMoga. I checked the logs and statsd pings and I can see them from dev, so you don't need to test that. It all seems to be working as expected.
