### ISSUE TITLE
No review types drop-down list when adding a new file for a disabled add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1833]
Steps to reproduce:
1. Sign in to AMO-stage https://addons.allizom.org/en-US/firefox/
2. Submit an add-on
3. Disable its version
4. Click the "Add another file" blue button/link

Expected results:
In the popup window there is a drop-down list to select what type of review you ask for your add-on (under the "Which review type would you like to nominate for?" question)

Actual results:
There is no drop-down.

Notes/Issues:
Verified on FF44(Win 7). Reproducing in AMO-stage, dev and production.
Screenshot for this issue: 
![2016-03-03_1529](https://cloud.githubusercontent.com/assets/15685960/13496125/33022670-e157-11e5-92b7-ddea9c21b98a.png)

**Comment by EnTeQuAk** [comment]
I wonder why no one complains about this and why this still works. Maybe @wagnerand knows if this a regression somehow or did we remove that dropdown and forgot to remove the label too? I feel like this has some importance but given that this bug was reported ages ago I don't know if that's actually the case. Mind commenting on that @wagnerand? Or @eviljeff could know something about that too

**Comment by jvillalobos** [comment]
It's very edge-casey, and I would suggest this is a wontfix. Only on certain circumstances you should be able to add files to a version, and this shouldn't be one of them.

**Comment by EnTeQuAk** [comment]
Thanks for the quick comment!
