### ISSUE TITLE
Prevent developers from editing site permission add-ons in devhub

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18444]
Site Permission add-ons from #18135 are automatically generated and should be visible in devhub, but the only thing you should be able to do is add/change/remove authors.

They shouldn't be allowed to be uploaded by developers either, unless they have a specific permission.

**Comment by diox** [comment]
Spent some time untangling the various checks, it's a bit tricky.

What we essentially need to care about here are `dev_required` decorator and `check_addon_ownership` function. There are a couple things to be mindful of however:
- We want to allow modification of authors, so `dev_required` needs a specific argument for this.
- `check_addon_ownership` has a `ignore_disabled` to let developers see disabled add-ons for read-only requests, and a `dev` argument to allow only owners or regular developers for specific write actions. That function is used both inside `dev_required` and throughout devhub to show or hide the edit buttons.

We have the following to take care of (ignoring reviewers/admins) for regular extensions:

| User  | Disabled add-on | Verb | Page | Allow Access    |
|-------|-----------------|------|------|---------------- |
| Non-author | Any | Any | Any | NO           |
| Developer or Owner | Any | GET  | Any | YES (*) |
| Developer Only | Any | POST | Delete / Authors | NO     |
| Owner | No | POST | Delete / Authors | YES     |
| Developer or Owner | No | POST | Other than Delete / Authors | YES     |
| Developer or Owner | Yes | POST | Any | NO     |

(*) There is a `owner_for_get` argument but it's not used, we could remove it.

For Site Permissions, we need:

| User  | Disabled add-on | Verb | Page | Allow Access    |
|-------|-----------------|------|------|---------------- |
| Non-author | Any | Any | Any | NO           |
| Developer or Owner | Any | GET  | Any | YES |
| Developer Only | Any | POST | Delete / Authors | NO     |
| Owner | No | POST | Delete / Authors | YES     |
| Developer or Owner | No | POST | Other than Delete / Authors | NO ⚠️     |
| Developer or Owner | Yes | POST | Any | NO     |

Because of the difference in behavior regarding non authors/delete pages, we can't just repurpose and rename `ignore_disabled` argument.

We could simplify the checks by only allowing to have owners and not developers for site permissions, but that would shift the problem somewhere else...

**Comment by diox** [comment]
QA: 
- As tested in https://github.com/mozilla/addons-server/issues/18329 regular developers shouldn't be able to submit new site permission add-ons unless they have `Addons:SubmitSitePermission`
- Once someone is a developer of a site permission, they should be able to see it in devhub, but not edit it or upload new version (*even* if they have `Addons:SubmitSitePermission`). They should only be able to edit ownership (invite people, change roles, remove authors) and delete the add-on.
- Please also test behavior of regular and site permission add-ons when they are disabled: if listed, developers should be able to see it in devhub, but not edit/delete. If they are a pure unlisted add-on (no listed versions) they should get a 404 when trying to see it in devhub.

Exception to those points: users with `Addons:Edit` should still be allowed to see and/or edit add-ons in all situations.

**Comment by AlexandraMoga** [comment]
@diox These are my (long) results after testing add-on submissions and editing for site-permissions and regular add-ons on -dev:

- **site-permission addons** (currently the results apply only to unlisted addons, since listed can't be submitted due to issue #18596;
  - new add-on submissions permitted only to users with `Addons:SubmitSitePermission` permission
  - new version uploads are not allowed
  - the Edit buttons in the DevHub Edit product page are hidden => changes are not possible (I've also tried to edit the add-on by URL and HTML manipulation and it was not possible, i.e. I received a 403 error message when I tried to submit my changes)
  - editable fields, other than authors, are hidden in the Manage Authors and License page => they can't be changed; adding and deleting add-on authors is possible:
    - a new Owner will be able to change the same fields as the original Owner (i.e. add/remove authors, delete the add-on)
    - a new Developer has only View rights for the add-on, i.e. no changes are permitted
  - the Manage Status and Versions page hides the Visibility, Upload new version, Disable/Delete version sections => no edits are possible; the Delete Add-on button is present and functional
  - if the add-on is disabled (by Force disabling it in RevTools), regular developers will receive a 404 (applies only to purely unlisted add-ons) if they are trying to access it in DevHub 
  - Disabled addons: users with `Addons:Edit` permissions are allowed to edit add-on fields in DevHub directly, except for uploading new versions(*)

- **regular add-ons:**
  - any active user can submit a new add-on
  - new version uploads are possible
  - every editable fields in DevHub Edit product, Manage authors and Manage Versions pages can be updated
  - new added Owners will have the same editing rights as the original Owners
  - new added Developers will have the right change any fields, except for those in the Manage Ownership page and Deleting the add-on
  - Listed, Force Disabled add-ons: regular Developers can view them in DevHub but are not allowed to Edit fields or submit new versions, not even Delete their add-on(**) 
  - Unlisted, Force Disabled: regular developers will receive a 404 if they are trying to access them in DevHub 
  - Listed or Unlisted, Force Disabled: users with `Addons:Edit` permissions are allowed to edit add-on fields in DevHub directly, except for uploading new versions



Outtakes:
- (*) for a site-permission add-on with a single version, if the version is disabled (by rejecting it from RevTools or by blocking it), `Addon:Edit` users will see the option to upload a new version in Devhub, but when they click on the option, a 403 is triggered; this issue should only have a small impact, so I'm not sure if it warrants a follow-up
- (**) for listed, Force Disabled add-ons, shouldn't developers be allowed to Delete them from DevHub?

**Comment by diox** [comment]
- (*) That's fine
- (**) If it's force disabled then we want to keep the add-on in that state and prevent deletion by developer
