### ISSUE TITLE
Submitting an invalid xpi fails when record-install-origins waffle switch is on

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18612]
STR:
- Enable `record-install-origins` waffle switch
- Submit an add-on with no `manifest.json` at the root (or maybe an invalid zip file)

Expected Results:
- You get an error explaining the issue like `No manifest.json was found at the root of the extension.`

Actual Results:
- You get a generic error like `Sorry, we can't parse your webextension` (which technically is not far from the truth anyway, eh...)

Traceback:
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/16985046/

This is because we try to annotate the results searching for install origins, but the `parsed_data` we're passing is an empty dict, since, well, we couldn't even parse the xpi correctly.

We should probably only do this bit for valid add-ons anyway. And/Or write this code more defensively, handling the potential absence of the key (which I kinda wanted to avoid to ensure we would not ever be accidentally in a position to bypass the origin deny list)

**Comment by AlexandraMoga** [comment]
Hm, this might be related to https://github.com/mozilla/addons-server/issues/18483;  Back than I was receiving these 'Unexpected' errors only on -dev, but it would make sense if the `record-install-origins` waffle was enabled only on -dev at at that time.

**Comment by diox** [comment]
Ooops, yes. Didn't notice that issue.

**Comment by AlexandraMoga** [comment]
I've submitted add-ons with the following invalid data, which used to trigger the 'Unexpected error' when the `record-install-origins` waffle was on:
- manifest.json not at the root
- broken archive
- invalid json syntax (as described in #18483)

Validation results are now relevant to the invalid data summited, i.e there are no more "Unexpected errors" triggered.

This issue is verified fixed on -dev.
