### ISSUE TITLE
Remove reviewer_name

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18683]
This is a spin-off from #17318 and is about removing all references to `reviewer_name`.

**Comment by ioanarusiczki** [comment]
@bobsilverberg What does it involve? Should I look again on what's been tested on previous issues - including e-mails sent ?

**Comment by bobsilverberg** [comment]
Based in the changes that landed in the patch, I'd suggest checking the `reviewnotes` endpoint, which can be done in Reviewer Tools via the versions page (Review History), as well as User admin.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I've noticed the endpoint returns a 200 status in the network from the versions page while Review History is displayed. 

Making a request such as https://addons-dev.allizom.org/api/v5/addons/addon/620296/versions/1693577/reviewnotes/ it will return a list of actions, including approved, rejected, admin super request and so on. 
A specific action is also returned https://addons-dev.allizom.org/api/v5/addons/addon/620296/versions/1693577/reviewnotes/4010965/ 

I don't know at what point the endpoint is called in the user admin, could not see it in the Network though.

**Comment by wagnerand** [comment]
@ioanarusiczki What permissions did the user have you tested with? Developer profiles should not see actions like "super/admin review requested".

**Comment by ioanarusiczki** [comment]
@wagnerand I used my admin account while testing that. 

With a developer account (I double-checked and it has no permissions in the admin):
-  I cannot access someone else's review notes on a version. 
- for an addon submitted on this account I can see "admin-add-on-review-requested" as action together with "reviewer-reply", "developer-reply" and "approved". 

I tested with: 
https://addons-dev.allizom.org/api/v5/addons/addon/620308/versions/1692314/reviewnotes/ 
https://addons-dev.allizom.org/api/v5/addons/addon/621224/versions/1693600/reviewnotes/

**Comment by wagnerand** [comment]
Thanks! Hm, maybe that is the expected behavior after all. I'd need to dig into the code see if we expose the admin review request action on purpose.

**Comment by ioanarusiczki** [comment]
@wagnerand  Also , looking at this action I see it's returning a standard comment instead of what I wrote while making the admin review request (on the listed review page)

It's: 
"comments": "The addon has been flagged for Admin Review.  It's still in our review queue, but it will need to be checked by one of our admin reviewers. The review might take longer than usual." 
and the name is anonymous "name": "Add-ons Review Team"

So probably it's fine.

**Comment by bobsilverberg** [comment]
> @bobsilverberg I've noticed the endpoint returns a 200 status in the network from the versions page while Review History is displayed.
> 
> Making a request such as [addons-dev.allizom.org/api/v5/addons/addon/620296/versions/1693577/reviewnotes](https://addons-dev.allizom.org/api/v5/addons/addon/620296/versions/1693577/reviewnotes/) it will return a list of actions, including approved, rejected, admin super request and so on. A specific action is also returned [addons-dev.allizom.org/api/v5/addons/addon/620296/versions/1693577/reviewnotes/4010965](https://addons-dev.allizom.org/api/v5/addons/addon/620296/versions/1693577/reviewnotes/4010965/)
> 
> I don't know at what point the endpoint is called in the user admin, could not see it in the Network though.

The `reviewnotes` endpoint isn't used by user admin, it's just that user admin was also touched by this patch which is why I thought it should be checked for regressions.

**Comment by bobsilverberg** [comment]
Regarding the conversation about actions above, the recent patches didn't change anything about which actions are returned via the endpoint, they only changed whether the name of a reviewer was revealed or not. I think the discussion about the "super/admin review requested" action was a red herring and not related to this patch.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Except for the Add User Profile+ button which does not work -> I am not 100% , to add a user profile from the admin. does not work for a while (maybe @wagnerand can tell if it's of use on prod). Anyway,  it's a 500 server error there but I think it's another red herring.

I've been testing around , especially the admin actions:
- adding a user to Group Users
- ban, reset API Key, Reset Session, Delete picture, Delete
- interaction between the admin user and the frontend works, if I'm updating a field in one place the other will update the information as well. 
- bypass upload restrictions for a lang pack user seems to be working because I got no restrictions uploading 3+ addons/min

I hope I covered this. Verified on AMO stage - FF96(Win10).
