### ISSUE TITLE
Remove ui.lightbox.js

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18740]
Originally spotted in #18142 but not technically dependent on jquery-ui despite the name.

The lightbox code these days is only used in reviewer tools for non-themes (themes have a different solution). Since we are not using a carousel, are already using a list of thumbnails, its only purpose is really to view screenshots one at a time in a modal popup. Let's simplify this into a link that opens in a new tab instead.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev:

[Images in extension review page - image opens in new tab]
![firefox_DmZu68hVe5](https://user-images.githubusercontent.com/31961530/152758268-2db48b74-6060-45d7-95f3-53895bc82273.gif)


[theme review page - as before]
![image_2022-02-07_110947](https://user-images.githubusercontent.com/31961530/152758292-b70ab9aa-6681-4654-894b-71f6e4289238.png)
