### ISSUE TITLE
access_tokens aren't being re-validated after 12 hours

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18754]
#18149 adds refresh tokens, which are supposed to be used to retrieve new access tokens after the existing access tokens expire (after 12 hours), but this isn't happening.  There is a setting that is disabled on stage and prod but it's not working on dev either.

**Comment by eviljeff** [comment]
Note: FxA team has confirmed that the tokens **aren't** invalidated by just logging out of FxA.  You've got to sign out of AMO in connected services specifically.

**Comment by ioanarusiczki** [comment]
@eviljeff I could use some STR for qa (I guess it's something similar to what's been done for https://github.com/mozilla/addons-server/issues/18149 )

**Comment by eviljeff** [comment]
yeah, it's the things that didn't work in https://github.com/mozilla/addons-server/issues/18149#issuecomment-1028822233.  So this is the feature that didn't work:

* after 12 hours the fxa login should be validated (silently, server-side, by sending refresh tokens) - if the user has ~logged out of FxA~ _signed out of AMO in the connected services list in FxA_ in the meantime it should fail and redirect the user back to FxA to login again. 

Frontend's behaviour is different - if the refresh failed an error is returned from the API; the user is logged out; and there is an error telling them to re-authenticate - implemented with https://github.com/mozilla/addons-frontend/issues/11102

Note: this validation is only enabled on addons-dev currently (https://github.com/mozilla/addons-server/issues/18828)

**Comment by ioanarusiczki** [comment]
@eviljeff I'll prepare my profiles with a few accounts on -dev now that https://github.com/mozilla/addons-server/issues/18836 has been merged.

**Comment by ioanarusiczki** [comment]
@eviljeff 

There could be a problem. 
There's a bug about Connected Services, the Sign out button does not work https://mozilla-hub.atlassian.net/browse/FXA-2847 I can confirm that because I tried on a few profiles but nothing happens after the button click. 
The refresh button is not working either https://mozilla-hub.atlassian.net/browse/FXA-3454

![sign out bug](https://user-images.githubusercontent.com/33448286/154249948-e6ec3284-adb6-4cd3-a09f-8f3ecf5ad3d9.png)

**Comment by ioanarusiczki** [comment]
@eviljeff 
An update:
there are accounts where Sign out from Connected Services is not working, in my case I have a few: rusiczki.ioana@gmail.com with 2fa disabled, irusiczki+1@mozilla.com and irusiczki@mozilla.com both with 2fa enabled.

I could Sign out with: contnoutestdev@mailinator.com new account, bancosioanaiulia@gmail.com, irusiczki+2@mozilla.com - all without 2fa enabled

I checked with Bianca from fxA , she's qa on that side, she could sign out using an account with 2fa enabled. In my case, irusiczki@mozilla.com and irusiczki+1@mozilla.com have 2fa enabled but sign out won't work.  So I don't think it's related with 2fa.

**Comment by eviljeff** [comment]
@ioanarusiczki in the past I've experience a bug where multiple sessions for FxA are represented by a single item - i.e. it shows you one connected service; you sign out; hit refresh; and it's still there - expect it's just showing the next session from AMO.  (Eventually I was able to sign out of all of them, by repeatedly signing out and refreshing).

Anyway, this is an FxA bug.

**Comment by ioanarusiczki** [comment]
@eviljeff 
All accounts were logged out of sessions with the expected behavior -> redirecting to fxA from server side when I tried clicking a button, the login expired page displayed on frontend.

It's interesting on codemanager that I was not redirected to login and I think I should be when I try to browse through files or add a comment on a code line. Only when I tried to download a file I was redirected: 

![unexpected code manager](https://user-images.githubusercontent.com/33448286/154430652-1806940b-7ed1-4384-9d9f-33511c226f60.gif)

**Comment by eviljeff** [comment]
> It's interesting on codemanager that I was not redirected to login and I think I should be when I try to browse through files or add a comment on a code line. Only when I tried to download a file I was redirected:
> 
> ![unexpected code manager](https://user-images.githubusercontent.com/33448286/154430652-1806940b-7ed1-4384-9d9f-33511c226f60.gif)

codemanager is still using the older API auth, that doesn't know about access token validity and refreshing them.

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-code-manager/issues/2156 for code manager auth changes

**Comment by ioanarusiczki** [comment]
@eviljeff I'll mark this verified on AMO dev. 
https://github.com/mozilla/addons-server/issues/18828 is for -stage and -prod deploys.
