### ISSUE TITLE
Remove devhub/base_impala.html

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18760]
DevHub has layers upon layers of CSS, templates that override older templates... With subtle differences everywhere. Let's try to harmonize everything by getting rid of `devhub/base_impala.html`.

It's only used by the API keys page and the DevHub dashboard. The biggest issue is that the dashboard has a couple design elements specific to impala style: the sidebar on the right instead of the left, and the pagination/sort links/items. So we'll need to make some minor adjustments.

**Comment by diox** [comment]
This will make https://github.com/mozilla/addons-server/issues/18143 easier

**Comment by diox** [comment]
Following this change, you can browse around devhub and see that it still works and looks the same.

There should be two pages with small differences:
- In the API keys generation page, some buttons will be aligned differently
- In the full list of add-on submissions, there should be:
  - A slightly darker shade of gray for most of the text on the page itself
  - A slightly larger font size for the submit buttons in the sidebar
  - A different pagination style

**Comment by vcarciu** [comment]
Verified as fixed:

Darker shade of grey for text in add-ons submissions:
Dev:
![DarkerDev](https://user-images.githubusercontent.com/1583842/152984381-4bd3201e-fff4-4813-94b8-a3f4ffed6c4f.png)
Stage:
![DarkerStage](https://user-images.githubusercontent.com/1583842/152984485-7f05a9f9-4aab-4260-aed8-512cccdbc7c1.png)

Slightly larger font size for the submit buttons:
Dev:
![LargerSubmitDev](https://user-images.githubusercontent.com/1583842/152985544-dda0612c-8e9e-476b-bc16-9b73785cb3f7.png)
Stage:
![LargerTextStage](https://user-images.githubusercontent.com/1583842/152985577-e1a1c861-50b8-4633-b078-7f280cbc71cf.png)

@diox : also, the button size is now bigger in -dev in order to fit the larger text size , but I guess that this is expected

Different pagination style:
Dev:
![image_2022_02_08T11_56_59_899Z](https://user-images.githubusercontent.com/1583842/152985964-b7de0bf0-9411-42e2-9811-efa45e7d65c5.png)
Stage:
![image_2022_02_08T11_53_28_712Z](https://user-images.githubusercontent.com/1583842/152985990-284fafaf-56eb-482c-a0c9-edaa0b52f66d.png)

API keys page:
Buttons aligned differently in multiple pages(Generate, Manage), but everything working as expected

@diox : I will mark this as verified, but please let me know if any of screenshots provided is showing something which is not expected.
