### ISSUE TITLE
Make paginating throughout all of AMO possible

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1878]
To help support bug 1140538, it would be nice if searching for an empty string would be possible. Then a client could just paginate through all the responses to download all the public add-ons.

**Comment by diox** [comment]
In #1817 I added a bunch of fields to the new search detail API, which should cover the needs of this issue. I already had support for searching for an empty string since #1772, with pagination.

At the moment this is restricted to listed add-ons with preliminary reviewed or public status, but I think this is not a problem since the custom SQL in [bug 1140538](https://bugzilla.mozilla.org/show_bug.cgi?id=1140538) worked the same way.

What's missing is a `sort` parameter - right now it sorts by name, which is not super useful.

**Comment by diox** [comment]
Now that sorting is done, we need to wait until tomorrow's tag to reindex stage, and wait for the push to be over on Thursday to reindex prod, and we'll be done with this issue.

**Comment by diox** [comment]
Reindex done on stage.

**Comment by diox** [comment]
We'll reindex prod on Monday.

**Comment by diox** [comment]
Reindex done on prod. The [search API](http://addons-server.readthedocs.org/en/latest/topics/api/addons.html#search) can now be used to paginate through all public add-ons and returns useful information for people wanting to build a feed of AMO contents.
