### ISSUE TITLE
Update api docs to clarify how `source` can be combined with other version/addon properties

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18797]
Follow-up for #9913 - some of the limitations of combing the fields need to documented when uploading a file as `source` and other values.  Only simple values can be sent in a multipart form, so for version, upload and license (because it's a slug). And sending the source during an Add-on create doesn't work.

**Comment by eviljeff** [comment]
(left this in the 2022.02.10 milestone because RTD deploys immediately)

**Comment by AlexandraMoga** [comment]
The new docs reflect the expected behavior now. 

There is one tiny issue with the "Add-ons Create" link in this section:
![image](https://user-images.githubusercontent.com/31961530/153235186-6148cbe5-3163-4768-a87a-ae1236a5ec52.png)

It's pointing to [addons-edit](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-edit) instead of [addons-create](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#create).

**Comment by eviljeff** [comment]
> It's pointing to [addons-edit](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-edit) instead of [addons-create](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#create).

fixed!
