### ISSUE TITLE
Explicitly add add-on ID in manifest for generated site permission add-ons

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18819]
Let's add an ID in the manifest for site permission add-ons we generate (ensuring it matches what we record in the database and the signature later, like normal). It will make an eventual upgrade path easier in the future.

**Comment by AlexandraMoga** [comment]
I've used the [site-permission generation](https://addons-dev.allizom.org/en-US/developers/site_permission_generator/) form in devhub to create add-ons. I've verified the generated add-on archive, both before and after the the signature is applied, and in both situations, the add-on ID (`guid`) is present in the manifest:

```
{
  "manifest_version": 2,
  "version": "1.0",
  "name": "Site permissions for addon-id-retry.com",
  "install_origins": [
    "https://addon-id-retry.com"
  ],
  "site_permissions": [
    "midi-sysex"
  ],
  "browser_specific_settings": {
    "gecko": {
      "id": "{ecbcddeb-87d5-4e75-a458-152977dca12f}",
      "strict_min_version": "97.0"
    }
  }
}
```

This issue is verified fixed on -dev.
