### ISSUE TITLE
Remove usage of addons.cdn.mozilla.net

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18998]
Remove any code dealing with addons.cdn.mozilla.net in addons-server. Links to download `.xpi` files should use the endpoint on the main domain from https://github.com/mozilla/addons-server/issues/18844 instead (including in the update service).

When this is deployed, we'll need an ops ticket to check usage of `addons.cdn.mozilla.net` and eventually decommission it, along with removing the ability to serve `.xpi` files directly from nginx (those downloads should go through addons-server and be served through `X-Accel-Redirect` and `internal` nginx directive instead). Then, we'll be able to do https://github.com/mozilla/addons-server/issues/18869

**Comment by diox** [comment]
QA: as mentioned in the description, nothing should use `addons.cdn.mozilla.net` (`addons-dev-cdn.allizom.org` on dev, `addons-stage-cdn.allizom.org` on stage), including download URLs from the update service - it should use the main domain instead.

**Comment by diox** [comment]
Hit or Miss depends on whether the response was already in the cache and, for installs from AMO, whether or not you were logged in. You should try to repeat the install a few times to see if you get a hit - you should after 2-3 times if you're not logged in.

**Comment by ioanarusiczki** [comment]
@diox 
I verified on -stage too, installs and updates work and requests are made to `addons.allizom.org`

I repeatedly installed on -dev and -stage addons in log out view:
- I never saw a "Hit" when installing the last version from the detail pages or see all versions page
- I did notice "Hit" into requests when I installed an older version from the See all versions page on both -dev and -stage

There's actually 2 requests, I see"Hit" for the one with Initiator 'document` and "Miss" for the XPIInstall as Initiator

![Miss andHit](https://user-images.githubusercontent.com/33448286/160822336-e6b35c5a-9941-4902-ac3d-dbaca1ac528d.png)

And it's "Hit" for both request in the case below: 

![hit with hit](https://user-images.githubusercontent.com/33448286/160823039-6907a9ce-842f-40d3-b1f6-66ca44f73e75.png)

- It's always a "Miss" when the addon is updated in about:addons

![updates](https://user-images.githubusercontent.com/33448286/160823790-bb9f07c4-a01b-4b55-88fe-3cba658b5ca7.png)

**Comment by diox** [comment]
@ioanarusiczki can you retest with `disable cache` checkbox in the top bar of the network tab checked ? That disables the caching in your browser, which makes testing more accurate because otherwise, in repeated tests like this you're often hitting your own browser cache and not even making the request.

Also if that's not the case already (can't see from your screenshots) make sure you were not logged in (`sessionid` cookie should not be sent)

**Comment by ioanarusiczki** [comment]
@diox Yes, sure, I'll repeat the tests tomorrow.

**Comment by ioanarusiczki** [comment]
@diox 

Results with disabled cache - log out view, new profile, no login before:

- https://addons.allizom.org/en-US/firefox/addon/pinitbutton1/versions/ ->  at first I has miss from the detail page, then after going to see all version I have hit on both versions then hit from the detail page for the last version
- https://addons.allizom.org/en-US/firefox/addon/flag-of-mexico/versions/-> hit from the first install on the detail page, hit when going to all versions page on both versions
- https://addons.allizom.org/en-US/firefox/addon/customs-dictionary/versions/ -> miss from the detail page, miss from the see all versions. Tried 10 times and still “Miss”
- https://addons.allizom.org/en-US/firefox/addon/basque-language-pack-ff98/versions/ -> miss from the detail page but then I went to see all versions and installed the older version I saw a hit from the first try, still a miss every time for the last version (on detail & see all versions)
- [https://addons.allizom.org/en-US/firefox/addon/onenote-clipper/versions/](https://addons.allizom.org/en-US/firefox/addon/onenote-clipper/versions/?utm_content=hotness&utm_medium=referral&utm_source=addons.mozilla.org)-> Last version is a miss every time, the oldest version has a hit and a miss because the console generates 2 requests.

the one with "document" is a hit and below it's the second request generated:
![3 8 0](https://user-images.githubusercontent.com/33448286/161027643-6c9c65bd-108e-40ff-8b07-0579f733b343.png)



- [https://addons.allizom.org/en-US/firefox/addon/animated-holiday-cheer/versions/](https://addons.allizom.org/en-US/firefox/addon/animated-holiday-cheer/versions/?utm_content=rating&utm_medium=referral&utm_source=addons.mozilla.org)-> miss for the last version, hit on both requests for the oldest version (as above it's been 2 requests generated)

Addon updates:

I hit a request with unusual headers  which only occurs at the first addon update for all addons below except for the lang pack

![first addon update](https://user-images.githubusercontent.com/33448286/161028089-965e6010-1fef-42ea-ac14-ff13310552b2.png)

https://addons.allizom.org/en-US/firefox/addon/pinitbutton1/versions/ hit when updating it
https://addons.allizom.org/en-US/firefox/addon/flag-of-mexico/versions/ hit 
https://addons.allizom.org/en-US/firefox/addon/onenote-clipper/versions/ miss
https://addons.allizom.org/en-US/firefox/addon/animated-holiday-cheer/versions/ miss
https://addons.allizom.org/en-US/firefox/addon/basque-language-pack-ff98/versions/ miss


With the tests above I cannot conclude it's behaving as expected if a hit is expected after repeated installs of the same add-on.

**Comment by diox** [comment]
That looks ok to me - ideally you'd only have hits, but there is no guarantee you're hitting the same CDN server everytime (we can check for that though, comparing `x-amz-cf-pop` identifier in the responses), and even if you were, no guarantee the CDN would keep the response in its cache, it may have to deal with more popular items at the same time.

**Comment by ioanarusiczki** [comment]
@diox Ok, in that case I'm marking this verified on -dev and -stage - FF98(Win10).

**Comment by ioanarusiczki** [comment]
@diox I'll keep in mind for future checks the 'x-amz-cf-pop' identifier. Thanks for the info!
