### ISSUE TITLE
Add submission API data to grafana

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19014]
We should make sure that we have data from the new submission API on grafana. Some stuff might already be there and we might want to start with replicating what we have for the old signing API.

Generally, among other things, the following might be useful:
* Counts of XPI submissions
* Counts of source code submissions
* Timings for XPI submission
* Timings for source code submission

Do we collect other timing, for example for metadata changes? Do we need that?

**Comment by eviljeff** [comment]
https://earthangel-b40313e5.influxcloud.net/d/PisVfMBnz/amo-add-on-submissions?orgId=1&var-env=prod&from=now-14d&to=now is tracking new addon and new version submissions for the new api, devhub, and the old signing api.

https://earthangel-b40313e5.influxcloud.net/d/SkaM51tnz/amo-submit-source-measurements?orgId=1&refresh=1m&from=now-14d&to=now&var-env=prod is for the source code submission (they're a little different because I created one of the dashboards, and Bob the other)

**Comment by eviljeff** [comment]
I'm assuming the dashboards I linked to cover the issue, if not please comment/reopen with what's still needed.
