### ISSUE TITLE
Name and Summary can be `null` in the add-on submission API

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#19055]
### Describe the problem and steps to reproduce it:
1. Upload a new listed add-on through the upload API
2. Set the `name` and `summary` to `null` in the request JSON body - i.e. `"name"/"summary": {"en-US": null}`
3. Submit the add-on

### What happened?
The submission is successful. The add-on created will not have a name and summary. 

### What did you expect to happen?
A 400 error with the following message:  "This field may not be blank."

### Anything else we should know?
If `name` or `"summary"` is set as an empty string, we get a 400 error, as expected.

**Comment by AlexandraMoga** [comment]
I've updated the issue to also include the `name` property, which shows the same behavior.

**Comment by ioanarusiczki** [comment]
@eviljeff I'm also checking on https://github.com/mozilla/addons-server/issues/8816 and I tried this scenario with POST - create listed addon and PATCH on name and summary. 
- when sending "summary":{"en-US":null},"name":{"en-US":null} at addon creation I still get a 201 Created, the submission can be resumed from dev hub since there's no name or summary for the default locale. 
- PATCH with "summary":{"en-US":null},"name":{"en-US":null} throws an error message         "A value in the default locale of \"en-US\" is required."

**Comment by eviljeff** [comment]
> @eviljeff I'm also checking on #8816 and I tried this scenario with POST - create listed addon and PATCH on name and summary.
> 
>     * when sending "summary":{"en-US":null},"name":{"en-US":null} at addon creation I still get a 201 Created, the submission can be resumed from dev hub since there's no name or summary for the default locale.

what is the upload xpi you're submitting - maybe there's something about the manifest structure that's breaking some check.

**Comment by ioanarusiczki** [comment]
[kanji.zip](https://github.com/mozilla/addons-server/files/8610228/kanji.zip)

@eviljeff it's just a dummy extension I'm using.

**Comment by eviljeff** [comment]
So, effectively what's happening is the validation code is ignoring the `null` value but seeing the `name` as being present because there's a value in the manifest; whereas `name` dict (with the `null` value(s)) is then overriding the `name` from the manifest later.  I.e. there's a disconnect between what the validation step is doing and what the actual add-on creation step does.

**Comment by ioanarusiczki** [comment]
@eviljeff 
when I'm  sending "summary":{"en-US":null},"name":{"en-US":null} at addon creation I get a 400 Bad Request,with the error messages:
{
    "name": [
        "This field is required for add-ons with listed versions."
    ],
    "summary": [
        "This field is required for add-ons with listed versions."
    ]
}
