### ISSUE TITLE
Prevent deleting and replacing files within versons

### ISSUE THREAD

**Issue by vanowm** [mozilla/addons-server#1905]
If a addon version was deleted it doesn't allow reupload the same version again. - this doesn't make sense because at the same time we can delete and reupload the same .xpi file again and again within the same version, which changes/breaks download location after each upload. This is one of the causes why people experience errors when trying update their addons - their browser is trying download deleted file.

**Comment by eviljeff** [comment]
You already can't delete reviewed files and I've recently addressed part of this in #2713 (you can't add new versions once reviewed).  Locking down the deleting and replacing files functionality entirely is blocked on the submission re-design because the current flow makes managing multiple files in versions difficult.
