### ISSUE TITLE
“My Themes” button overlaps “My Add-ons” button when the page is translated to Urdu.

### ISSUE THREAD

**Issue by SilviaSabou** [mozilla/addons-server#19082]
Preconditions: User is logged in https://addons-dev.allizom.org/en-US/developers/ .

Steps to reproduce:

1. From the page header click on “My Add-ons”.
2. From the page footer change the language to Urdu. 
3. Scroll back to the top of the page.

Expected results: “My Themes” and “My Add-ons” buttons should be next to each other.

Actual results: “My Themes” button overlaps “My Add-ons” button and crops it.

Notes: Reproducible in all AMO servers. - FF96(MacOS 12.2.1)

Please see a screenshot for this issue:
<img width="402" alt="Screenshot 2022-04-04 at 15 47 03" src="https://user-images.githubusercontent.com/86671716/161716526-8ed30fea-64da-4469-9a51-08f612963de3.png">

Urdu language:

<img width="122" alt="Screenshot 2022-04-04 at 13 10 24" src="https://user-images.githubusercontent.com/86671716/161716628-f52da6ec-7080-4407-a076-00b5593ea75f.png">

**Comment by eviljeff** [comment]
I'd guess it's because Urdu is a right-to-left language and we're trying to treat it correctly in the style but in this case it's not actually a localised string - it's just the `en-US` default - so it's slightly messing up the layout.

After investigation we've noticed we don't actually have any localisations in Urdu anyway and will remove it as an option.  Closing this issue in favour of https://github.com/mozilla/addons-server/issues/19092 as this issue will go away once it's not an available locale.
