### ISSUE TITLE
`custom_license.url` links to a non-existent page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#19122]
### Describe the problem and steps to reproduce it:
1. GET the details of an add-on with a custom license - see https://addons-dev.allizom.org/api/v5/addons/addon/621471/
2. Open the link present in the `custom_license.url` field

### What happened?
The `url` links to a 404 page - see https://addons-dev.allizom.org/en-US/firefox/addon/custom_license_url/license/10.222

### What did you expect to happen?
The `url` has the version number appended, which is what causes this issue. The `url` should link instead to https://addons-dev.allizom.org/en-US/firefox/addon/custom_license_url/license/

### Anything else we should know?
Reproduces with add-ons created through DevHub and with the API

**Comment by eviljeff** [comment]
mmm, this is very old addons-server behaviour though - we've supported the version in the license url since it was added [12 years ago](https://github.com/mozilla/addons-server/commit/c2a35031529491ac92306062c3026f34cfd34aa5) because licenses are per-version.  

I don't know if it was a conscious decision not to support the same url when frontend reimplemented the license view or not - maybe @bobsilverberg knows?

**Comment by bobsilverberg** [comment]
> mmm, this is very old addons-server behaviour though - we've supported the version in the license url since it was added [12 years ago](https://github.com/mozilla/addons-server/commit/c2a35031529491ac92306062c3026f34cfd34aa5) because licenses are per-version.
> 
> I don't know if it was a conscious decision not to support the same url when frontend reimplemented the license view or not - maybe @bobsilverberg knows?

I don't see anything in the [original issue](https://github.com/mozilla/addons-frontend/issues/3697) about having the license number in the URL, nor do I recall any conversation about it. I note that the page mentioned in the issue is https://addons.mozilla.org/en-US/firefox/addon/onetab/, and the link to the custom license from that page *does not* contain the version number. So I'm wondering, under what circumstances does the `license_url` contain the version number and when does it not contain it? If this was a problem with most add-ons with custom licenses I imagine it would have been reported long ago.

**Comment by bobsilverberg** [comment]
Ah, so we don't actually use the URL at all. I guess I should have looked at the code (and my own comments in the PR). So is the issue here that the URL returned by the API not actually a valid one?

**Comment by eviljeff** [comment]
IMO the bug is that frontend doesn't support the urls with the version number like legacy frontend used to, so is only able to show the license for the current version.  But I don't see that being implemented any time soon, realistically.  So in that case (or at least in the meantime) the URL returned by the API is invalid.

**Comment by bobsilverberg** [comment]
We could easily render the license for the current version for any URLs that contain a version number, rather than returning a 404, but maybe we don't want to do that as it would be inaccurate?

**Comment by eviljeff** [comment]
> We could easily render the license for the current version for any URLs that contain a version number, rather than returning a 404, but maybe we don't want to do that as it would be inaccurate?

agreed

**Comment by AlexandraMoga** [comment]
The custom license URL no longer includes the version number at the end:

```
       "license": {
            "id": 4250,
            "is_custom": true,
            "name": {
                "en-US": "custom-license-url"
            },
            "slug": null,
            "url": "https://addons-dev.allizom.org/en-US/firefox/addon/privacy-badger78/license/"
        }
```

This issue is verified fixed on -dev.
