### ISSUE TITLE
Reload version in `auto_approve` before determining whether or not it should be auto-approved

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19136]
`auto_approve` fetches versions that are auto-approvable but then can take a long time to go through them all, so instead, it should fetch version ids and instantiate each version from the database at the last minute, just before determining whether or not it should be auto-approved.

**Comment by diox** [comment]
QA: ensure auto-approve still works correctly.

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and these are my results:

- auto-approval for new listed add-on submission => delayed as it is the first listed version
- auto-approval for new listed version submission => approved ~ 5 minutes
- auto-approval for new unlisted add-on/new version submission => approved ~ 5 minutes
- auto-approval hold when auto-approval is disabled from reviewer tools - listed => new listed versions are not auto-approved
- auto-approval hold when auto-approval is disabled from reviewer tools - unlisted => new unlisted versions are not auto-approved
- auto-approval hold when manual approval is required for a new version when add-on has a previous rejection/delayed rejection => new version are not auto-approved
- auto-approval hold when a scanner rule prevents auto-approval => addons are not auto-approved
- auto-approval hold when add-on requires manual approval (recommended extensions, themes) => addons are not auto-approved
- auto-approval for new language pack submission => approved ~ 5 minutes

Since auto-approval seems to be working as before, I'm marking this issue as verified fixed.
