### ISSUE TITLE
Allow addon authors to be added via addon api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19164]
split from https://github.com/mozilla/addons-server/issues/18231 (which was itself spun off from https://github.com/mozilla/addons-server/issues/18036)

You should be able to add new add-on owners/developers via the addon api

Complexity here is 
- not actually creating AddonUser, but creating AddonUserPendingConfirmation.
- we need to expose any AddonUserPendingConfirmation somewhere.  It would _seem_ like the ideal place is the same `/authors/` sub-endpoint but the models themselves are different and not (easily) exposed with a single queryset (there is django magic but probably complete overkill)
- how do users confirm the pending confirmation?

**Comment by ioanarusiczki** [comment]
@eviljeff 
I'll be done with all my testing tomorrow , so far I filed  an issue https://github.com/mozilla/addons-server/issues/19213

**Comment by ioanarusiczki** [comment]
@eviljeff 
- I could not reproduce the issue above with PATCH and DELETE pending-authors. 
- [confirm](https://addons-server.readthedocs.io/en/latest/topics/api/authors.html#pending-author-confirm) and [decline](https://addons-server.readthedocs.io/en/latest/topics/api/authors.html#pending-author-decline) APIs are missing a "/" at the end -> I added it into the request because they won't respond without it
- I could see in the browser the invitation if I access an URL such ashttps://addons-dev.allizom.org/en-US/developers/addon/pepega-catch-3/invitation/ after [creating](https://addons-server.readthedocs.io/en/latest/topics/api/authors.html#pending-author-create) one but I did not see any in the fake e-mails. Let me know if that's alright.

**Comment by eviljeff** [comment]
> @eviljeff
>     * [confirm](https://addons-server.readthedocs.io/en/latest/topics/api/authors.html#pending-author-confirm) and [decline](https://addons-server.readthedocs.io/en/latest/topics/api/authors.html#pending-author-decline) APIs are missing a "/" at the end -> I added it into the request because they won't respond without it

I'll fix with #19213
 
>     * I could see in the browser the invitation if I access an URL such ashttps://addons-dev.allizom.org/en-US/developers/addon/pepega-catch-3/invitation/ after [creating](https://addons-server.readthedocs.io/en/latest/topics/api/authors.html#pending-author-create) one but I did not see any in the fake e-mails. Let me know if that's alright.

ugh, I thought the email code was in the model, so I missed out replicating it.  Can you file an issue?
