### ISSUE TITLE
Rendered license name does not match the actual addon's license

### ISSUE THREAD

**Issue by gregorypappas** [mozilla/addons-server#19165]
### Describe the problem and steps to reproduce it:
The rendered "License" is not the actual license. It says MPL but the hyperlink is GPL

### What happened?
I went to https://addons.mozilla.org/addon/ublock-origin/
The "License" section under "More Information" says MPL

### What did you expect to happen?
I expected the "License" section under "More Information" to say GPL 3.0

**Comment by AlexandraMoga** [comment]
After a quick browsing, I've noticed that this happens with Search by Image as well - https://addons.mozilla.org/en-US/firefox/addon/search_by_image/

One interesting tidbit: if you go to All versions page for either of these two add-ons and then navigate back to their detail pages, the license name will be correct, until you refresh the page.

**Comment by diox** [comment]
From discussion on Matrix:
- The `License` model uses `builtin` to determine `slug` and `name` for builtin licenses. `builtin` is an integer.
- However `builtin` is indexed as `{'boolean', 'index': False}`, we do `'builtin': bool(version_obj.license.builtin)` when indexing.
- So the data in ES is `'builtin': True` (rest of the data, `id`, `name_translations`, `url` are correct)
- In the serializer, we instantiate a `License` with that ES data, that `True` gets converted into an integer, and we land on the license with `builtin = 1`, which is `LICENSE_MPL2`.

**Comment by diox** [comment]
I tried running the reindex on dev but that failed, somehow the indexing tasks were not running on the new index but on the old one.. This is weird.

Could be related to https://github.com/mozilla/addons-server/issues/19134, need to investigate more.

**Comment by diox** [comment]
Looking at the [traceback](https://sentry.io/organizations/mozilla/issues/3227087720/?project=6224627&query=is%3Aunresolved) we were using the right index, and inspecting the corresponding mapping manually, everything seems to be normal, we can see `'builtin': {'index': False, 'type': 'short'}` as expected...

**Comment by diox** [comment]
Aaaaah `reindex` tries to index on both the old and the new alias. On the _old_ alias, `builtin` is still a boolean, and we pass an integer, so that fails.

Not sure how to workaround this without doing a ugly hack checking the mapping type at indexing time temporarily. I'm not sure why `reindex` bothers with the old index ?

**Comment by AlexandraMoga** [comment]
I've verified the licenses for extensions and themes on -dev and I haven't found mismatches between the rendered license name and the actual license linked. I've checked that add-ons with versions that have different licenses are returning the correct license for the current version available on the detail page. 

Since this issue reproduced only with a few add-ons, I'm not sure how complete my check is. I'll have to double check that the specific add-ons from prod have been fixed once this lands on production.
