### ISSUE TITLE
Consider replacing `nobot` with `django-recaptcha`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19195]
We moved to `nobot` in 64830bfcc1b1656f2ce6ce950e0db2dff8cbcb57 but nowadays `django-recaptcha` is better maintained. It may not behave in the same way, particularly when testing, so we need to investigate.

This would address the following deprecation warning:
`RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().`

**Comment by diox** [comment]
QA: you should still see a captcha when the developer agreement is shown (try in private browsing mode to have more chances of seeing it)

**Comment by ioanarusiczki** [comment]
@diox I did find some scenarios when with an extra pic which would not match what's required would pass the verification. They're subtle errors, because it would not pass when selecting all the images or too many pictures that won't match the requirement.

Such as:

![capcia](https://user-images.githubusercontent.com/33448286/172628679-568670a2-7c95-413b-b225-6a830b1e4ca6.gif)

![capcia2](https://user-images.githubusercontent.com/33448286/172628710-977e904c-0bbd-452e-9af3-b22d0ea5cbad.gif)

![capcia3](https://user-images.githubusercontent.com/33448286/172628731-465de587-72d7-475a-be50-898372cbd8e1.gif)

![capcia4](https://user-images.githubusercontent.com/33448286/172628777-0403a491-f356-473e-b657-0e62d510ce19.gif)

**Comment by diox** [comment]
That's expected - recaptcha is not 100% strict in these cases. The part that you should verify is that a failure (you don't get the "I'm not a robot" green check) or an attempt to bypass (you do not click on the checkbox, you click but dismiss the captcha with developer tools) don't let you submit the form.

**Comment by ioanarusiczki** [comment]
@diox 

>  The part that you should verify is that a failure (you don't get the "I'm not a robot" green check)

this I'm sure it happened every time. It's fine. 

> an attempt to bypass 

I'll check this, sure.

**Comment by ioanarusiczki** [comment]
@diox Ok, I could not bypass it when I do not click it. 

> you click but dismiss the captcha with developer tools

How do I dismiss it with dev tools?

**Comment by ioanarusiczki** [comment]
@diox Nevermind, I deleted the entire element and clicked Accept -> it reloads and throws an error message " This field is required"

It will pass only when I click it and then click Accept too.  -> works as expected
