### ISSUE TITLE
Some addons trigger downloads instead of installs on Android

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19232]
I tested today on a debug build android installs - > I noticed that some addons trigger downloads instead of installs
The ids are: 

id 620020
id 11377
id 620558
id 620019

I checked and found them into the fenix collection on stage. 

![download triggered](https://user-images.githubusercontent.com/33448286/168041962-2c588eed-277c-4510-aa4e-5e1025db1231.png)

I did not reproduce this on prod.

**Comment by diox** [comment]
@ioanarusiczki Can you give the URLs of the detail pages you were on in each case ? Also, do you have examples of add-ons on stage that still download correctly with your build ?

**Comment by ioanarusiczki** [comment]
https://addons.allizom.org/en-US/android/addon/enhancer-for-youtube/
https://addons.allizom.org/en-US/android/addon/invisiblehand/
https://addons.allizom.org/en-US/android/addon/remote-scriptx2/
https://addons.allizom.org/en-US/android/addon/search_by_image/

Now I've noticed another strange behavior, I went to another one https://addons.allizom.org/en-US/android/addon/decentraleyes/ and it triggered an install  then just went back on the detail page and the download xpi (as the screenshot show above) just appeared on the screen. 
Also I can reproduce it with https://addons.allizom.org/en-US/android/addon/youtube-high-definition/
then after I refreshed the page the normal install was triggered. 
I just see this happening randomly on all addons and refreshing the detail page is changing the behavior from download to install.

**Comment by ioanarusiczki** [comment]
@diox 
I'll describe what happened with this one https://addons.allizom.org/en-US/firefox/addon/invisiblehand/
-> installed it without issues went back on the detail page with the back button
-> tapped the logo and went back on the list of addons then opened again https://addons.allizom.org/en-US/firefox/addon/invisiblehand/
-> tapped the install button, the download is triggered instead

**Comment by diox** [comment]
@ioanarusiczki I've edited my comment with more questions, but you were probably already writing your reply by then and missed my edit.

**Comment by ioanarusiczki** [comment]
@diox [Admin fenix collection](https://addons-internal.stage.mozaws.net/en-US/admin/models/bandwagon/collection/5745306/change/?_changelist_filters=author%3D11686491)

**Comment by diox** [comment]
Ok so I think I have part of the answer. Doing the following (similar STRs as above really) triggers it:
- Open homepage
- Tap on Youtube High Definition
- Tap install button, it installs correctly
- Go back (to the homepage)
- Tap on Youtube High Definition again
- Tap install button again, it downloads

This is because the download URL the second time around somehow becomes https://addons.allizom.org/android/downloads/file/1096908/ instead of https://addons.allizom.org/android/downloads/file/1096908/youtube_high_definition-80.0.0-an+fx.xpi. Both are valid, but [Fenix only recognizes the one with the filename that ends with `.xpi`](https://github.com/mozilla-mobile/fenix/blob/a1243a8e9f23b930c8c9512548a3c7900ed1a088/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt#L195).

**Comment by diox** [comment]
This is another variation of https://github.com/mozilla/addons-server/issues/19165, sort of. The search API doesn't return the URLs with the filename in them on stage.
