### ISSUE TITLE
Secondary shelf module CTA URLs are being wrongly transformed and lead to broken pages

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19258]
**STR:**
- In the admin, set up a secondary shelf with a secondary hero module that has a Cta Url pointing to an URL on AMO with an app (i.e. firefox) and locale (i.e. en-US) in it.
- Once cache clears on the frontend (*), click on the link for that module on the homepage

**Expected results:**
- The page linked originally loads

**Actual results:**
- You end up loading a page with the app and locale re-added, which errors out. See examples below.

**Examples of broken CTA urls:**
- https://addons-dev.allizom.org/en-US/firefox/addon/spellcheck-enabler/ if you're visiting the homepage in `fr`, you'll end up loading https://addons-dev.allizom.org/fr/firefox/en-US/firefox/addon/spellcheck-enabler/ instead (+ some query string for utm parameters). It would work in `en-US`, though.
- https://addons-dev.allizom.org/firefox/addon/spellcheck-enabler/ would be transformed to 
https://addons-dev.allizom.org/en-US/firefox/firefox/addon/spellcheck-enabler/ (+ some query string for utm parameters).

The CTA url in the API is correct: the problem lies on the frontend. We should fix it, but note that we should probably prevent linking to an URL in a specific locale in the admin, because if we obey that, users would end up on a page translated in a different language than the one they were on initially.

---

(*) include a query string in the CTA url when you're changing it : you'll now cache has cleared and you're looking at fresh data when you see that query string in the CTA url on the homepage. This applies to both broken and working scenarios.

**Comment by diox** [comment]
Yet another example taken from -dev right now:
- Visit AMO homepage in `en-US`
- Look at the link from the secondary Hero on the left - this one:
![Screenshot 2022-08-18 at 17-17-20 Add-ons for Firefox (en-US)](https://user-images.githubusercontent.com/187006/185432031-a2e1aad1-94ee-49c7-b749-3ed6c998c553.png)
- It correctly links to `https://addons-dev.allizom.org/en-US/firefox/collections/4757633/privacy-matters/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-secondary-hero` which works.
- Now repeat with AMO homepage in another language such as `fr`
- Look at the link again
- It incorrectly links to `https://addons-dev.allizom.org/fr/firefox/en-US/firefox/collections/4757633/privacy-matters?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-secondary-hero` - note the `/fr/firefox` followed by `/en-US/firefox` in that link.

**Comment by ioanarusiczki** [comment]
@diox I'm not getting the expected result. 

I went to the secondary hero shelf in [admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/secondaryheroshelf/15/change/). All URLs have /fr/ instead of /en-US/ -> I saved the new CTA URLs
Also I repeated this for a homepage shelf -> replaced /en-US/ with /fr/ (using the Footer pathname field) -> now if I click on See more popular extensions I get a 404.

**Comment by diox** [comment]
Ah, I think I see what's happening. 

So first, an easier way to test that my fix is working is to re-edit the shelf/modules after saving them: the URL should no longer have the app/locale prefix if it had any, or both.

I suspect the problem here is that it's fixing URLs that start with `/` or `https://addons-internal.dev.mozaws.net/` but not `https://addons-dev.allizom.org/`. So it's partially working, but I need to patch it to fix URLs beginning with the regular public domain as well.

**Comment by ioanarusiczki** [comment]
@diox 

For the "Cta url" I tried with: 

https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus-0425/
https://addons-dev.allizom.org/it/firefox/addon/koutter2359/
https://addons-dev.allizom.org/en-US/firefox/collections/4757633/privacy-matters/ or other locale "it", "de"
https://addons-dev.allizom.org/de/firefox/extensions/category/tabs/
https://addons-internal.dev.mozaws.net/it/firefox/extensions/category/tabs/

-> after I save these, the Cta url will display only `/addon/adblock-plus-0425/` or `/collections/4757633/privacy-matters/` and the frontend links are opened -> with `en-US` locale in all cases.  

An example -> I used https://addons-dev.allizom.org/it/firefox/addon/koutter2359/ in the Cta url field and saved, I open the frontend in en-US, the url is : https://addons-dev.allizom.org/en-US/firefox/addon/koutter2359/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-secondary-hero

Then if I visit the frontend with 'it' or 'fr' the urls are opened with that locale without errors.

For "Footer pathname:" from [Homepageshelves](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/78/change/) module if I use a URL with "it" instead of "en-US" it still throws a 404. Let me know if I should open a separate issue.

**Comment by diox** [comment]
Ah, good find on the homepage shelves. It's the same root cause but because it's less common to use a full URL when customizing the "footer pathname" we haven't encountered that bug in prod with the homepage shelves.

Let's open a new issue, the fix is likely going to be similar but it's a completely different module.
