### ISSUE TITLE
Investigate compatibility information for dictionaries

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19323]
Something I spotted while working on https://github.com/mozilla/addons-server/issues/19245 : the update service expects all add-ons to have minimum compatibility information stored in the database, even in the `ignore` compatibility mode (which should only be used for dictionaries).

Dictionaries in production currently do have compatibility information set, so they currently work, but not [when created with the new API](https://github.com/mozilla/addons-server/blob/9feeb673910b700680a643f34b1a4807e4650585/src/olympia/versions/models.py#L560-L562) and [not in tests](https://github.com/mozilla/addons-server/blob/9feeb673910b700680a643f34b1a4807e4650585/src/olympia/amo/tests/__init__.py#L931-L940).

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-server/issues/19166

**Comment by eviljeff** [comment]
after investigation this isn't so bad - the api _does_ create default compatibility information for dictionaries, they just can't be changed from the defaults.  

So changes needed:
 - Stop returning fake data in version serializer
 - rename `NO_COMPAT`, etc, to make it clear it's only changes we block, and we do actually store compatibility in the db (and have since webext dictionaries were supported, at least)
 - fix any stray dictionaries that have missing or incorrect min/max versions
 - change version_factory to always create compatibility

**Comment by eviljeff** [comment]
> At dictionary create:
> 
>     * I can send a request with a JSON that includes {"compatibility": {"firefox": {"min": "100.0", "max": "102.* "}, "android": {"min": "61.0", "max": "92.*"}}} -> the response returns the information set for firefox (android is ignored)

Is that compatibility actually being set?  Or it's just being returned in the response and still ignored?

**Comment by ioanarusiczki** [comment]
@eviljeff 

The API responses return the min and max if they're set but I think that only the min.  is set and max is ignored, I'll give 2 examples:

https://addons-dev.allizom.org/en-US/firefox/addon/azerbaijani-spellchecker1/ I sent the JSON with min:97 and max 98.* -> I could install the dict on FF 100.0.1
https://addons-dev.allizom.org/en-US/firefox/addon/azerbaijani-spellchecker2/ I sent  the JSON with min:102 and max 102.* -> I see  "You need an updated version of Firefox for this extension" yellow banner above the install button on FF 100.0.1 

That's the same for any other webextension - because they don't have strict compatibility that can be set as for langpacks.

**Comment by ioanarusiczki** [comment]
@eviljeff Looks like only at create the min can be set other than 61.*  and with new versions/patch requests it's set to 61.*

**Comment by eviljeff** [comment]
> @eviljeff Looks like only at create the min can be set other than 61.* and with new versions/patch requests it's set to 61.*
> 
> In case this should be changed let me know.

I think this is covered in #19166
