### ISSUE TITLE
Localized fields which are not mandatory are required when the default_locale is edited

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19335]
I've submitted an addon - > the default-locale is en-US. It also has for en-US information besides name and summary for description, support_email and support_url. 
When making a PATCH request such as  {"default_locale":"it", "name":{"it":"123"}, "summary":{"it":"123"}}

Actual result:
The error message is that   "A value in the default locale of \"it\" is required." for description , support_email and support_url

Expected result:
I should get no error message because only name and summary are mandatory fields.

**Comment by eviljeff** [comment]
If there are existing localized values in the other translation fields they'll be required if you change the default locale too - it'd lead to unexpected and inconsistent output otherwise 

(e.g. existing default locale is `fr` and add-on has a `support_url` in `fr` - you'd get a `support_url` in results for all requested locales; if you change the default locale to `it` without providing an `it` translation for `support_url` it'd be `null` for every locale requested, other than `fr`).
