### ISSUE TITLE
Remove `allow-deleted-guid-reuse` and ability for developers to reclaim guid from deleted add-on

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19501]
We introduced `allow-deleted-guid-reuse` (it's `False` in production) in https://github.com/mozilla/addons-server/issues/18253 but now we're not going back. Remove associated code, preventing developers to re-use guids of add-ons they owned and deleted no matter what.

The waffle switch itself will be removed later.

**Comment by diox** [comment]
Note: the waffle switch should still be there, but it shouldn't do anything. We'll remove it separately later.

**Comment by ioanarusiczki** [comment]
@diox I tried on AMO stage uploading an addon with a deleted guid:
- by the same user ->     Duplicate add-on ID found.
- by another user ->  Duplicate add-on ID found.

I get the results about with `allow-deleted-guid-reuse` disabled and enabled. 

That's the expected result because before, when the switch was enabled, it allowed re-submission by the owner.
