### ISSUE TITLE
Allow reviewer notes upload in new submissions API

### ISSUE THREAD

**Issue by jmif** [mozilla/addons-server#19554]
Hi there,

Would be great to be able to add reviewer notes to the submissions via the new submission API.  Looking at the docs [here](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-edit) I don't see them.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I verified this on -dev:
- I sent "approval_notes" at addon create using the PUT and POST requests, inside "version"
such as "version": {"upload": "e7eadf346f73451a8215b81f8504159a", "approval_notes":"test, with a PUT request, unlisted version","license":"all-rights-reserved"} -> the JSON response does not return  "approval_notes" but I see what I sent in dev hub and on the  [rev tool page](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/622085).

- with a PATCH request I could edit  "approval_notes" for a specific version. 
- with POST/PUT at version create I could send "approval_notes" when submitting a new version. 
- for an approved listed version the version detail API will display "approval notes" for authorized developers . I will check again for reviewers tomorrow morning since I can't conclude if it's working as expected yet (I suspect I'm doing something wrong on my side with Postman).

**Comment by eviljeff** [comment]
Ah, yeah, we don't use the version serializer that includes `approval_notes` for Addon responses, only Version responses - so it won't be there. That's inconsistent so we should change that.

**Comment by ioanarusiczki** [comment]
@eviljeff Ok, I'm going to file a followup. 

I repeated tests to see that reviewers can see the approval_notes in the JSON responses with the addon versions API. 
- when the user is part of Reviewers :Addons group -> I can access the details of the versions but I did not see approval_notes being available. This is the[ addon](https://addons-dev.allizom.org/api/v5/addons/addon/622084/versions/1694724/) it has 2 non-public versions and one approved and public. -> I'm thinking of filing an issue.

- I also added the user into Reviewers:Unlisted. In this case, the approval_notes are available for unlisted versions.
