### ISSUE TITLE
Allow admin reviewers to unreject a version

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19683]
In the Reviewer Tools, users with permission `Reviews:Admin` should be able to change the status of a version from `STATUS_DISABLED` to `STATUS_AWAITING_REVIEW`.
Doing so might have an impact on the add-on status, the system should determine the right status automatically.

As a security precaution, the ability to unreject should only be available if the add-on status is not `STATUS_DISABLED`. Admin reviewers should first manually "force enable" an add-on which changes the add-on status to `STATUS_NULL`, to express the explicit intent to enable a previously manually disabled add-on.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I'll try to make a short summary because I tried lots of scenarios on AMO dev and stage. 

 - I mainly tested with an admin account but did check that it works for reviewer:admins too. The button is not available for regular reviewers. 

- if the addon is forced-disabled the button is no longer present, so it needs to be forced-enabled
- cannot unreject after rejection scheduled -> the addon needs an immediate rejection
- in most situations after unrejection , the state of the version will be "Has auto-approval disabled/delayed flag set "-> if the "Enable Listed Auto Approval before next manual approval button" is clicked then the versions will be automatically approved after. 
Examples : 
https://reviewers.addons.allizom.org/en-US/reviewers/review/1007488
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/622689


- I tried with blocked versions too, there's a flag that indicated it's been added to blocklist. For an unlisted addon I will get a 500 server error if I try to approve the version (it is not reproducible for a listed addon because the approval button is not present here)
unlisted blocked version: https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1007495#review-actions
listed blocked version: https://reviewers.addons.allizom.org/en-US/reviewers/review/1007497

- I've noticed that unrejected versions were automatically auto-approved after I forced-enabled and unrejected 2 auto-approved versions (I can't remember in which order I tried these actions)
this is the example: https://reviewers.addons.allizom.org/en-US/reviewers/review/1007503

- sometimes there's a delay for "Not Auto Approved Because:" but the reason will be displayed after refreshing the pages

I hope this is working as expected, I did not have str -> that's why I gave some examples

**Comment by eviljeff** [comment]
> cannot unreject after rejection scheduled -> the addon needs an immediate rejection

I figured there was some way for a reviewer/admin to stop a scheduled rejection? Is that not the case?

> in most situations after unrejection , the state of the version will be "Has auto-approval disabled/delayed flag set "-> if the "Enable Listed Auto Approval before next manual approval button" is clicked then the versions will be automatically approved after.
Examples :
https://reviewers.addons.allizom.org/en-US/reviewers/review/1007488
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/622689

I'm not clear on what the STR are here - can you elaborate?  (And is this working as you expected?)

> I tried with blocked versions too, there's a flag that indicated it's been added to blocklist. For an unlisted addon I will get a 500 server error if I try to approve the version (it is not reproducible for a listed addon because the approval button is not present here)
unlisted blocked version: https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1007495#review-actions
listed blocked version: https://reviewers.addons.allizom.org/en-US/reviewers/review/1007497

Blocking is an edge case I'd not tried to code for - the rejection is a side-effect of the Block and the action shouldn't remove the Block on the add-on.  Maybe we should just not allow this for Blocked versions?  Although it'd also complicate the code and require extra queries so... yeah, dunno.  @wagnerand do you have strong opinions?

> I've noticed that unrejected versions were automatically auto-approved after I forced-enabled and unrejected 2 auto-approved versions (I can't remember in which order I tried these actions)
this is the example: https://reviewers.addons.allizom.org/en-US/reviewers/review/1007503

The unreject action doesn't change anything to do with the auto-approval status of the addon/version so it kind of makes sense the auto-approve cron would pick it up and auto-approve the version after it was un-rejected.  Whether it should though...?  Again, thoughts @wagnerand ?

**Comment by wagnerand** [comment]
> I figured there was some way for a reviewer/admin to stop a scheduled rejection? Is that not the case?

There is a button at the end of the page to cancel a scheduled rejection.

> Blocking is an edge case I'd not tried to code for - the rejection is a side-effect of the Block and the action shouldn't remove the Block on the add-on. Maybe we should just not allow this for Blocked versions? Although it'd also complicate the code and require extra queries so... yeah, dunno. @wagnerand do you have strong opinions?

Good catch! We should not allow unrejection of a blocked version. Let's remove blocked versions from the selection list.

> The unreject action doesn't change anything to do with the auto-approval status of the addon/version so it kind of makes sense the auto-approve cron would pick it up and auto-approve the version after it was un-rejected. Whether it should though...? Again, thoughts @wagnerand ?

That's a good question. I don't have a strong opinion at this point. I lean towards leaving as is and re-evaluate at a later time, after gathering some experience and feedback from reviewers in production.

**Comment by ioanarusiczki** [comment]
@eviljeff Yes, I forgot to add that I did cancel the rejections, I knew about that. 

@wagnerand  Could you take a look on the cases below because I cannot tell if that's what reviewers expect: 

The first one https://reviewers.addons.allizom.org/en-US/reviewers/review/1007488 -> version 2.1 was automatically approved, then rejected, unrejected and now it's with Has auto-approval disabled/delayed flag set

And the second example was 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/622689  -> last version was rejected then unrejected and now has Has auto-approval disabled/delayed flag set

**Comment by wagnerand** [comment]
> The first one [reviewers.addons.allizom.org/en-US/reviewers/review/1007488](https://reviewers.addons.allizom.org/en-US/reviewers/review/1007488) -> version 2.1 was automatically approved, then rejected, unrejected and now it's with Has auto-approval disabled/delayed flag set

From reading your comment, that seems expected. The initial rejection caused auto-approval to be disabled.

> And the second example was
[reviewers.addons-dev.allizom.org/en-US/reviewers/review/622689](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/622689) -> last version was rejected then unrejected and now has Has auto-approval disabled/delayed flag set

Same here. From what I can see it works as I would expect it.

In general, let's not fiddle with automated auto-approval conditions changes too much as a start. It's hard for reviewers to follow and understand why something happened or didn't happen. We can make consider changes when reviewers identify an issue or source of confusion in their workflow.

**Comment by ioanarusiczki** [comment]
@wagnerand Ok, thanks for the info!

**Comment by ioanarusiczki** [comment]
@eviljeff I filed https://github.com/mozilla/addons-server/issues/19789
