### ISSUE TITLE
Handle submission of a version string corresponding to a previously deleted version in signing API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19696]
STR:
- Submit an add-on (listed or unlisted, doesn't matter, but don't submit more than one version)
- Delete the only version on AMO
- Using the signing API, try to submit the same version number to the same add-on

Expected:
- A 409 response indicating the version was already uploaded before but was deleted

Actual:
- A 500 error : https://sentry.io/organizations/mozilla/issues/3171609056/?project=6310819
```
AttributeError: 'NoneType' object has no attribute 'version'
  File "rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "olympia/signing/views.py", line 68, in inner
    return fn(view, request, addon=addon, **kwargs)
  File "olympia/signing/views.py", line 103, in put
    file_upload, created = self.handle_upload(
  File "olympia/amo/decorators.py", line 125, in wrapper
    return f(*args, **kw)
  File "olympia/signing/views.py", line 153, in handle_upload
    % latest_version.version
```

The error happens because we do a first (correct) check using `Version.unfiltered`, but then try to display what the latest version number is using `addon.find_latest_version(None, exclude=())` which can't by design find deleted versions.

Note: Devhub and new submission API already handle that case.

**Comment by AlexandraMoga** [comment]
I've uploaded an add-on and then deleted its only version. Using the old signing API -  `PUT /api/v5/addons/(string:guid)/versions/(string:version)/` - I've tried to reupload the same version (same version string).

Addon used for testing: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/622362

Response: `409 Conflict: {"error": "Version 10.240 was uploaded before and deleted."}`

Uploads of non-conflicting versions are successfully processed. 

This issue is verified fixed on -dev.
