### ISSUE TITLE
Migrate user photos to new directory structure and delete orphaned files from EFS

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19709]
Follow-up to https://github.com/mozilla/addons-server/issues/19690 : we likely have some orphaned photos on the filesystem we can delete.

**Comment by diox** [comment]
Probably can be done with a one-shot synchronous script doing something like:
```python
for dirname in os.listdir('userpics'):
    for subdirname in os.listdir(dirname):
        for filename in os.listdir(subdirname):
            pk = int(os.path.splitext(filename)[0])
            if UserProfile.objects.filter(pk=pk, deleted=False).exists():
                continue
            os.remove(filename)
```

**Comment by diox** [comment]
While looking into that, I realized that this is using a weird directory structure completely different from the rest, so I'll probably change this issue into migrating that to the new structure we used for add-on files, and clean up orphaned pictures at the same time.

**Comment by diox** [comment]
This needs a command to be ran on the dev/stage/prod envs, I'll edit this command once I've run it on dev & stage so that it can be verified there. 

Once the migration is done, QA should check that previously & newly uploaded user pictures still work, even if you copy the URL of the image and add something to the query string (to bypass CDN/browser caching)

**Comment by diox** [comment]
Migration is done on dev, it took ~25 minutes.

**Comment by AlexandraMoga** [comment]
I've looked at older users with profile photos attached and I am now seeing their photos:

[before]
![image](https://user-images.githubusercontent.com/31961530/193274926-12eb7d80-898e-4c1b-a579-8b45e0cf9979.png)

[after]
![image](https://user-images.githubusercontent.com/31961530/193274862-37bcbc8f-a854-4df0-978f-5600b5d93c93.png)


We've also created new accounts with profile photos before the migration and their photos remained attached after the migration.

Adding, editing and deleting profile pictures still works.

We'll be checking stage too once the migration is done there as well.

**Comment by ioanarusiczki** [comment]
@diox 

On AMO stage: 

Old profile pictures (not being displayed before) -> are available now
Examples:
https://addons.allizom.org/user-media/userpics/39/9839/6199839/6199839.png
https://addons.allizom.org/user-media/userpics/43/3443/3443/3443.png
https://addons.allizom.org/user-media/userpics/56/3456/3456/3456.png

I also checked with one of my testing accounts, I've opened the picture URL and tried to modify the parameter. It happened that there was another image uploaded before so this would load instead of the actual : 

![picture url](https://user-images.githubusercontent.com/33448286/194030760-72362728-6b95-420e-97c6-b7077c78b307.gif)
 
I tried again after I changed again the profile picture and I reproduced this by removing entirely `?modified=1664962488`
