### ISSUE TITLE
Store a canned response for each review action reason

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#19835]
This contributes to #19818

When a reviewer chooses a review action reason, a particular canned response will be added to the comments input for the review. We should therefore update the `ReviewActionReason` model to also store a canned response text, so that it will be available for use in the UI.

**Comment by bobsilverberg** [comment]
@wagnerand Does this make sense to you based on the requirements of the feature?

**Comment by wagnerand** [comment]
@bobsilverberg yes, sounds good.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I added with the admin model new [reasons ](https://addons-internal.dev.mozaws.net/en-US/admin/models/reviewers/reviewactionreason/20/change/) which have a Canned Response field.  I could not save the reason without a canned response because I get an error "    This field is required." 

On the review page this canned response it's not visible yet. 

From reading the description of the issue, this should be the expected for now.
