### ISSUE TITLE
New `Notable` promoted add-on group

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19976]
We need a new promoted add-on group _Notable_ that behaves similar to Spotlight.

Add-ons having `average_daily_users` above a certain threshold (set in a config) are automatically added to this group. They stay in the group should usage fall below the threshold.

If the latest version of an add-on in that group has been auto-approved and not reviewed by a human, it should appear in a queue for review.

**Comment by diox** [comment]
> If the latest version of an add-on in that group has been auto-approved and not reviewed by a human, it should appear in a queue for review.

This is trickier than it looks - There are 2 issues:
- We have a mechanism to approve addition to a promoted group (`immediate_approval=False`), but that only shows up in the admin, and is a bit clunky to use for random add-ons, it was designed for promotions like recommended where we are communicating with the developer and can ask them to delay publishing a new version for instance. Still, maybe we can re-use that or do something similar.
- We don't really have a reviewer queue well suited for that at the moment - all of them are quite specific and don't really fit that use-case.

**Comment by diox** [comment]
Conceptually, the `needs_human_review` flag makes the most sense for this - flagging the current version of those add-ons for human review is exactly what we want.

Unfortunately it's a little confusing because the MAD queue is called "Flagged for human review" and uses `needs_human_review_by_mad` flag, while the scanners queue is called "Flagged by scanners" and uses `needs_human_review` flag. Ideally we'd rename the scanners queue, keeping it generic, use the `needs_human_review` flag for this issue (dropping those add-ons in that queue), and find a new name for the MAD queue...

**Comment by wagnerand** [comment]
That works for me. @diox if we are pursuing this approach, can you give me a heads up a few days before we are dropping the add-ons in the existing _Flagged by scanners_ queue? I'd like to make sure those still get reviewed.

**Comment by wagnerand** [comment]
> ... (dropping those add-ons in that queue) ...

I clarified with Mat that this means existing add-ons would not be dropped, but _Notable_ would be added to( dropped into) that queue, as well.

**Comment by eviljeff** [comment]
Okay, that means `immediate_approval=False` would work here - it would only be exposed as `Notable` in the API after approval.  We just need to trigger the additional review somehow.  

(I don't think we'll need to make any changes to how `needs_human_review` works because being a promoted group that is `pre_review=True` is another trigger for requiring review for each version before signing, but tbc)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I started testing today on AMO dev and I added manually some Notable add-ons in the [admin ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?group_id__exact=7) What I've noticed:
- for a [new submitted add-on ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/623817) the review page will show the flag "Is in a promoted add-on group that requires pre-review", and "This is a Notable add-on" orange warning is visible. I found the add-on into Flagged By Scanners queue and approved it, then I submitted a new version, this time the new version is not available in this queue.

- for an [already auto-approved add-on ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/623586)once I added into the Notable group I found the version displayed [Flagged By Scanners](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/scanners) queue. After I submitted a new version, same as before, I did not see it available in the queue. 

- I tried with [static themes](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/623593) too. I checked the review page -> the warning This is a Notable add-on.  is available but I do not see a Confirm Approval action here, also they're not available in the scanners queue. Maybe they're not in scope for this group, I don't know. 

Andreas mentioned 

> Add-ons having average_daily_users above a certain threshold (set in a config) are automatically added to this group. They stay in the group should usage fall below the threshold.

 Can this be tested on AMO dev right now? What I did is adding them manually. There are a [few add-ons](https://addons-dev.allizom.org/en-US/firefox/search/?sort=users) with ADU.

**Comment by eviljeff** [comment]
Oh, the `Notable` group is only added as part of the daily cron job that updates the ADUs.  I believe it's scheduled to start 13:30 UTC (not sure how long it runs for - probably not too long on addons-dev)

**Comment by eviljeff** [comment]
> [Firefox Color](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/617049) also appeared in human review queue and I confirmed approval, then submitted a new version -> the version is waiting for a review now but the addon is not available in the queue. -> I don't know if that's ok or should I wait until the next cron job runs?

The cron job only collects add-ons that have passed the ADU limit but aren't already in the group - and then the re-review will be in flagged for human review (because it's an already approved version).  Once an add-on is in the Notable group it's a pre-review add-on so it would appear in the Other Pending Review queue (I think - wherever a pre-review add-on would end up)

> when adding[ Facebook Container](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/409/change/?_changelist_filters=group_id__exact%3D7) and [Firefox Color ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/408/change/?_changelist_filters=group_id__exact%3D7)to Primary Hero I could do it only with "Is external" checkmark
> I don't know why that is required , yesterday I added the samples without checking "Is external"

I don't really know - it's not something I've changed - the Notable group _is_ enabled for the Hero shelf, but it's all generic code so I didn't change anything specifically. (note: setting `is external` is not a "fix" - it's a special case for promoting add-ons that wouldn't have a detail page on AMO.)  If it persists or is reproducible can you log an issue?

**Comment by ioanarusiczki** [comment]
@eviljeff 

Ah, thanks! I found Firefox Color in [Other Pending Review ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/extension)queue 

![Pending review](https://user-images.githubusercontent.com/33448286/205648179-3e11b6b1-c875-4a46-b86d-c070c923cb27.png)

I'm going to check the admin part again on -stage, when I'll take a look at the "Not promoted" and "extensions only" scenarios.

**Comment by eviljeff** [comment]
> @eviljeff
> 
> I forgot to mention, about the frontend layout:
> 
> I don't know if it's alright with "Sponsored" and the URL "What is this" going to https://support.mozilla.org/en-US/kb/add-on-badges -> where recommended and By Firefox labels are explained

Can you log an issue?  It's not particularly high priority as Scott would have to choose to enable the primary hero shelf for a `Notable` add-on first, but we should fix it for the day that happens.

**Comment by ioanarusiczki** [comment]
@eviljeff 

On AMO stage:

- I added as "Not promoted" addons with ADU>7 -> they are now in the [Notable group](https://addons-internal.stage.mozaws.net/en-US/admin/models/discovery/promotedaddon/?group_id__exact=7)
- I added as "Not promoted" a [lang pack](https://addons-internal.stage.mozaws.net/en-US/admin/models/discovery/promotedaddon/118/change/?_changelist_filters=group_id__exact%3D0), and there is [another one ](https://addons.allizom.org/en-US/firefox/addon/esperanto-language-pack/) with ADU -> they are not part of the Notable group
- I get an error when I try adding them into the Primary Hero Shelf, even if I check "Is external". I filed https://github.com/mozilla/addons-server/issues/20068
