### ISSUE TITLE
The update service is not working as expected for unlisted addons with mixed MV2 and MV3 versions

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20016]
### Describe the problem and steps to reproduce it:
As an addon developer, submit a new MV2 unlisted addon. Once the add-on is approved, distribute your add-on to be installed by your users.
As one of the addon users, install the addon in Firefox < 109. As another user, install the addon in Firefox => 109.
As the addon developer, upload a new unlisted MV2 version for your addon. Then, upload another MV3 unlisted version with a `strict_min_version` set to 109 (109.0a1 for the current Nightly).
Make sure you have an `updates.json` file which points to the new versions so that your users can receive the updates. 
As the addon users, check for updates to receive the new versions for the installed addon. The user on Firefox < 109 should receive an update to the new MV2 version and the user on Firefox >= 109 (Firefox Nightly) should receive an update to the new MV3 version.

I've already tested this scenario and have the test data available here: https://alexandramoga.github.io/ so you can follow these STR:

1. Open https://alexandramoga.github.io/
2. Download the [MV2_and_MV3_updates_v1.zip](https://alexandramoga.github.io/MV2_and_MV3_updates_v1.zip) addon
3. Install the addon in Firefox < 109 (using the about:addons Install from File method)
4. Once the addon is installed successfully, check for updates - it helps to have the Browser toolbox open to see the requests made

### What happened?
The update service is finding the latest MV3 version -  [MV2_and_MV3_updates_v3=MV3.zip](https://alexandramoga.github.io/MV2_and_MV3_updates_v3=MV3.zip) as an update option, which results in the update failing since the MV3 version is not compatible with this version of Firefox. 

### What did you expect to happen?
The update service should find the new MV2 version - [MV2_and_MV3_updates_v2=MV2.zip](https://alexandramoga.github.io/MV2_and_MV3_updates_v2=MV2.zip) as an update option and install it. 

### Anything else we should know?
- This is my updates manifest used for the above scenario - https://alexandramoga.github.io/updates.json and the addon in question is `mv2-and-mv3-updates@external_updates.io`
- In Nightly, the addon is updated successfully to the MV3 version.
- I've repeated the scenario with a listed addon and could not reproduce the issue, i.e. Firefox < 109 receives updates to the MV2 version and Nightly the MV3 version
- It seems to me that Firefox is looking for the latest version available when checking for updates; I've tested this by uploading a new MV2 version for the test addon and checking for updates again in Firefox < 109 and in this case the addon was successfully updated to the newest MV2 version.

**Comment by diox** [comment]
That is not an AMO bug, since the update service used is your own, and not AMO's. Whether it should be considered a Firefox bug or not is debatable, it depends on how we think it should behave, I don't think it's clearly defined.

The way it works for _listed_ add-ons is that AMO applies some filtering to find the best compatible version, and avoids returning incompatible versions. So, a user on < 109 would never see the MV3 version in the updates returned by AMO's update service, unless they forced it.

It looks like Firefox just tries to pick the latest version you're returning, and so it fails in that case for < 109. A way to address that in your update service would be to make it dynamic and filter on `User-Agent`, or just use an `update_url` that only returns MV2 for MV2 add-ons, and only returns MV3 add-ons for MV3, only merging them when you no longer want to distribute MV2 add-ons.

**Comment by diox** [comment]
Closing as per previous comment, this is not an AMO bug
