### ISSUE TITLE
Group add-on review log by reviewer "actions"

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20045]
The add-on review log currently shows one entry per version reviewed, even if multiple versions were reviewed in one review. We should group those entries together so that the log shows one entry per reviewer "action" (i.e. the submission of a review, regardless of how many versions are affected).

The log currently also shows the version affected, we can drop the version info since we are going to aggregate version-actions as per the above.

**Comment by diox** [comment]
We could look into having a single activity log for actions that affect multiple versions... Back in the day, I chose to make multiple because we had no idea where we were going with this, but maybe we could reconsider... (To be clear, I'm not sure it's the a good idea - we'd need to investigate the consequences of doing that, but in theory the model supports recording any number of `versions` as arguments...)

**Comment by eviljeff** [comment]
> in theory the model supports recording any number of `versions` as arguments.

`ActivityLog.to_string` only supports a single instance of a certain Class per log.  If we only wanted to represent a single version in the string - and we were careful to pass that version first in the args - then it'd still work though.

**Comment by eviljeff** [comment]
But, imo, a single activity log entry for multiple versions is an implementation detail - we could reimplement the current review log that shows per version with a single activity log record if we wanted, and the page would look the same - but the issue is about the UX representation, and I'm unclear about the extent of the changes requested.

**Comment by eviljeff** [comment]
> If we're only recording a single activity log for reviewers actions that affect multiple versions, doesn't this solve the problem described in the issue ? We'd no longer need to group anything, no UX to change.

Where would these activity logs appear then?  The existing review log is per version so if it's not linked to a version it won't show up anywhere.  We could show it linked to the most recent version that the action affected, but that's counter to "we can drop the version info since we are going to aggregate version-actions", which indicates it _won't_ be shown linked to any version.

**Comment by diox** [comment]
It would still be linked to the versions.

**Comment by diox** [comment]
@wagnerand To be clear, this is about the Add-on Review Log page (`/en-US/reviewers/reviewlog`) right ? Not the log that appear on the review page of an add-on (`/en-US/reviewers/review/<id>`)

As @eviljeff asked at the top, a mockup of what it should look like would help.

**Comment by eviljeff** [comment]
> @wagnerand To be clear, this is about the Add-on Review Log page (`/en-US/reviewers/reviewlog`) right ? Not the log that appear on the review page of an add-on (`/en-US/reviewers/review/<id>`)
> 
> As @eviljeff asked at the top, a mockup of what it should look like would help.

Fwiw, I read the issue as refering to log on the review page of an add-on

**Comment by wagnerand** [comment]
This is about the Add-on Review Log (`/reviewlog`).

It's not easy to create a mockup because I can't use prod data and stage data doesn't have many good examples, but here is an excerpt:

Before:
<img width="1426" alt="Screenshot 2023-02-15 at 14 18 38" src="https://user-images.githubusercontent.com/873258/219039008-ec6f55a1-ed6d-4926-b59b-5cd7f8b0c869.png">

After:
<img width="1423" alt="Screenshot 2023-02-15 at 14 19 20" src="https://user-images.githubusercontent.com/873258/219039032-5da734f3-05e4-4ec5-8a55-01dceabfffe0.png">

The two actions should be combined into one, omitting the version, since they were part of a single reviewer action. In this case the reviewer rejected two versions at once using `Reject Multiple Versions action`. If they had done that in two separate actions, they should be shown in the log as two separate entries.

**Comment by diox** [comment]
I still think the way forward here is to introduce new actions that deal specifically with multiple versions at once, replacing the individual actions we are currently recording when we reject/approve/block/confirm approval of multiple versions.

The `ActivityLog` model isn't built for this though, specifically the string formatting really expects a maximum of one argument of each type IIRC. But with the suggestion to simplify the text shown and only link to the add-on, maybe this is fine and we can just ignore that.

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/issues/20039 was logged to record reviewer reviews, fwiw (to build the review reports, before I grouped by identical timestamp instead)

**Comment by diox** [comment]
@wagnerand would my suggestion from https://github.com/mozilla/addons-server/issues/20045#issuecomment-1431416975 break any manual queries you're currently maintaining in redash or elsewhere ?

**Comment by wagnerand** [comment]
> @wagnerand would my suggestion from [#20045 (comment)](https://github.com/mozilla/addons-server/issues/20045#issuecomment-1431416975) break any manual queries you're currently maintaining in redash or elsewhere ?

I'm not sure and it's hard to search for that in redash. Would we migrate (or rather duplicate) existing data to use the new actions? If not, how could we combine both old and new actions (with the respective applicable versions)? How would the log show entries (and work for search) when we have both old and new actions?

**Comment by diox** [comment]
My rough plan was:
- Introduce new actions - like `REJECT_MULTIPLE_VERSIONS`, `APPROVE_MULTIPLE_VERSIONS`
- Use them instead of recording multiple `ActivityLog` with `REJECT_VERSION`, `APPROVE_VERSION` etc for actions that affect multiple versions. 
- Leave actions that only deal with a single version alone
- Leave existing data alone

In the log, you'd see either multiple entries for old actions made before that, or a single entry for the new one if the review was performed after. If you search for an add-on you could potentially see both if a mix of new and old actions were performed against that add-on.

**Comment by wagnerand** [comment]
@kplotnik would that be sufficient?

**Comment by diox** [comment]
If new actions are not desired, the alternative would be to "manually" group actions by creation date+user - considering actions from the same user with the same creation date as part of the same group. That would work for 99% of the cases, but only really solve the problem superficially in the review log instead of fixing the underlying data to only record a single action every time. Still, that's an option if we don't want to be too agressive.

**Comment by eviljeff** [comment]
At the cost of extra complexity (and more tables, models, etc), maybe we need both a a generic `REJECT_REVIEW` (etc) that's used for (name subject to bikeshedding) and then an intermediate model to fk the `REJECT_REVIEW` to many `REJECT_VERSION` instances.

Or an even more generic `REVIEWER_REVIEW` activity that is then fk'd (via the intermediate model) to many `REJECT_VERSION`, `APPROVE_VERSION`, etc.

**Comment by kplotnik** [comment]
> @kplotnik would that be sufficient?

@diox @wagnerand I'd say so

**Comment by diox** [comment]
> Or an even more generic `REVIEWER_REVIEW` activity that is then fk'd (via the intermediate model) to many `REJECT_VERSION`, `APPROVE_VERSION`, etc.

We already have the notion of which actions are reviewer actions, so I don't think recording yet another generic action is the way to go. I'd rather make it so that we don't record multiple actions in those cases, but all of this is more of a discussion for https://github.com/mozilla/addons-server/issues/20039 .

I'll investigate fixing just the UI for now in this issue and see if that's enough, and we can look at the underlying data model in #20039 .

**Comment by diox** [comment]
> I'll investigate fixing just the UI for now in this issue and see if that's enough, and we can look at the underlying data model in https://github.com/mozilla/addons-server/issues/20039 .

I did that but I'm not convinced we can do this in a satisfying way. We're either running into pagination issues (if just ordering and hiding the extra instead of grouping in the query) or not distinguishing single version reject from multiple rejects (if grouping in the query) or causing super inefficient queries (if grouping in the query and then making a subquery to find how many actions were done for each date).

**Comment by diox** [comment]
So I think the best solution is https://github.com/mozilla/addons-server/issues/20045#issuecomment-1438704199 (*). Going to spend some time on that next.

(*) without migrating existing data for now, unless that becomes a problem.

**Comment by diox** [comment]
Starting from this patch, all reviewer actions that affect multiple versions should record a single `ActivityLog` that has multiple `Version` arguments (and multiple `VersionLog` attached). This should be transparent to reviewers in the review page, but should effectively ensure only one activity log is shown per reviewer action in the review log page.

Old activities are still separate.

**Comment by ioanarusiczki** [comment]
@diox 

- actions on multiple versions will show up in a single row 
- when the same action is taken consecutively on single versions they'll be registered on separate rows

On AMO dev:

![multiple versions approved](https://user-images.githubusercontent.com/33448286/223673821-c496dece-70ea-44ea-9c6f-b867f0b907aa.png)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-140
