### ISSUE TITLE
The addon review page throws a 403 error when the character limit is exceeded for the Whiteboard field

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20070]
### Describe the problem and steps to reproduce it:
1. Open an addon review page - https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1004976
2. Add some text in the "Whiteboard" field that exceeds the character limit for this textarea
3. Update the whiteboards

### What happened?
The page throws a 403 error and the Whiteboard is not saved

### What did you expect to happen?
The Whiteboard should display an error message mentioning the character limit excess

### Anything else we should know?
The same issue applies to the Private Whiteboard which is used only by reviewers.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/20079 makes it a lot less problematic - reviewers will be prevented to go over the character limit by their browsers. An error message would still be nicer if somehow that attribute is bypassed client-side.

**Comment by diox** [comment]
The problem:
https://github.com/mozilla/addons-server/blob/40e8d32443ef89e487f384098335bf421c097db1/src/olympia/reviewers/views.py#L1037-L1044

When the form is invalid, we just 403. We don't have a great way to surface errors back to the user, because this view isn't the review view where the user is coming from. We could do an XHR, or handle it in the `review` view, or whatever, but that doesn't seem worth it now that we have the `maxlength` attribute set.

**Comment by eviljeff** [comment]
closing this if the maxlength attribute works around it.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-178
