### ISSUE TITLE
Can't upload new version of the dictionary

### ISSUE THREAD

**Issue by arysin** [mozilla/addons-server#20183]
### Describe the problem and steps to reproduce it:
I’ve tried to upload new version of my dictionary addon and I get an error:

### What happened?
The locale of an existing dictionary/language pack cannot be changed

### What did you expect to happen?
New version of the addon is uploaded

### Anything else we should know?
I haven’t changed anything in the addon metadata for years and I can’t figure out why it would not allow me to upload new version.
I've tried to change the default locale on the page to en-us but that didn't help.
The addon is [https://addons.mozilla.org/en-US/developers/addon/ukrainian-dictionary 2](https://addons.mozilla.org/en-US/developers/addon/ukrainian-dictionary)

**Comment by diox** [comment]
Hi,

Could you attach the file you were uploading to this issue?

**Comment by arysin** [comment]
[ukrainian_dictionary-6.0.1-mozilla.zip](https://github.com/mozilla/addons-server/files/10406796/ukrainian_dictionary-6.0.1-mozilla.zip)
I've changed the extension as github didn't allow to attach xpi

**Comment by diox** [comment]
The internal target locale recorded in the database for that dictionary is `uk`, but your dictionary is for `uk-UA`. To ensure consistency we started checking that those values match in  https://github.com/mozilla/addons-server/issues/19380 - which went to production just a couple days after your last successful upload, which is why you haven't encountered that behavior before.

An admin should fix the `target_locale` of your dictionary to be `uk-UA` in the database to unblock you (you could update your dictionary to match but that's probably a bad idea - the locale appears correct, it's really AMO database that is wrong here).

cc @wagnerand who might be able to fix that.

**Comment by arysin** [comment]
Thank you! 
I think it'll also be helpful if the UI shows both values (I'd definitely spend less time trying to figure out what I did wrong if I saw "uk" and "uk-UA")

**Comment by wagnerand** [comment]
I updated the target locale for `uk-ua@dictionaries.addons.mozilla.org`.

**Comment by arysin** [comment]
Thank you, I was able to submit the update

**Comment by mtrevisan** [comment]
Hi all.
I have the vary same problem with my dictionary.
My locale is vec-IT and my xpi is located [here](https://github.com/mtrevisan/VenetanSpellChecker/blob/dev/dict-vec-xpi/dict-vec.xpi.zip)
Thank you

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-208
