### ISSUE TITLE
Fix flag icon line break in review queue

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20213]
### Describe the problem and steps to reproduce it:

The `needs admin review` flag icon in the queues are unnecessarily breaking the line.

STR:
1. Submit a listed add-on and attach sources.
2. Make sure it's not auto-approved, so it appears in the `Other Pending Review` queue.
3. Observe the flag icons in the `Other Pending Review` queue

### What happened?

<img width="159" alt="Screenshot 2023-01-20 at 14 29 12" src="https://user-images.githubusercontent.com/873258/213706132-2ec9b295-687b-438f-968a-4b77f91e23e5.png">

### What did you expect to happen?

<img width="208" alt="Screenshot 2023-01-20 at 14 29 38" src="https://user-images.githubusercontent.com/873258/213706215-cec89a31-c9fb-449d-9021-6f5c067cffea.png">

### Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on stage:

![image](https://user-images.githubusercontent.com/31961530/214602854-4f8c7f78-9094-49a2-98b2-ad154939e355.png)
![image](https://user-images.githubusercontent.com/31961530/214602880-58857949-52f0-4026-bfa3-0589433871b2.png)
![image](https://user-images.githubusercontent.com/31961530/214603133-f3173932-a74d-40bf-9109-ee012b3c91d6.png)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-213
