### ISSUE TITLE
Show maliciousness score in Manual Review queue

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20220]
The new merged manual review queue from https://github.com/mozilla/addons-server/issues/19984 should display a column with the maliciousness score of the version being shown.

**Comment by ioanarusiczki** [comment]
@diox 
On AMO dev:
- the first addons from the list have a "-" as score, but if I look in the admin, they're incomplete/invisible so they'll be removed from this queue. 
- in the other cases, the score is n/a or a percentage. In some cases the review page would display 100% and the queue 99% -> that's an old thing and it's been filed already https://github.com/mozilla/addons-server/issues/16830

It looks alright, but I'm going to check on -stage too tomorrow.

**Comment by ioanarusiczki** [comment]
@diox 

On AMO stage:
- most of the addons with "-" at score instead of n/a are incomplete 
- there are a few that have been approved, and have versions in awaiting review -> also display "-" instead of n/a:
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/619493
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/619491
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/619452
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1004916 
but they're quite old and look like the auto-approval script has not run on those versions.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-215
