### ISSUE TITLE
Backfill last 6 months of RatingLog on stage and prod

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20231]
It seems we missed running the command that backfills the last 6 months or `RatingLog`s on stage and prod. Let's do that now.

**Comment by diox** [comment]
Command is `backfill_ratinglog`. It calls `get_or_create` so it shouldn't create duplicates. It will create the missing `RatingLog` for every rating-related activities we have, and since we don't keep the old ones past 6 months (https://github.com/mozilla/addons-server/issues/20228 will increase that) there shouldn't be anything special to do but run the command.

**Comment by diox** [comment]
There is now 5162 `RatingLog` on stage out of 55128 `ActivityLog`. That's because a lot of those `ActivityLog` no longer point to existing `Rating` instances (most are from times where we hard-deleted ratings).

```
>>> RatingLog.objects.count()
5162
>>> activities = ActivityLog.objects.filter(action__in=(amo.LOG.APPROVE_RATING.id, 
amo.LOG.DELETE_RATING.id, amo.LOG.EDIT_RATING.id, amo.LOG.ADD_RATING.id))
>>> activities.count()
55128
>>> len([activity for activity in activities if any(isinstance(obj, Rating) for obj in activity.arguments)])
5162
```

There are also more `Rating` objects than that (31175) but that's because we don't keep all `ActivityLog` forever for ratings.

So I'm considering this issue verified on stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-220
