### ISSUE TITLE
Django admin add-ons changelist page times out

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20248]
On prod, the django admins addons changelist page loads for a minute, then times out with a 504 error.

**Comment by diox** [comment]
In https://github.com/mozilla/addons-server/issues/20091 I added IP address search for ratings & addon admins. When we're not performing a search however, we're still fetching the IPs.

So we could:
- Look if that's the case and find ways to optimize the query further
- Stop doing the IP part of the query if we're not doing an IP search (the IP isn't displayed by default in the addon changelist page)

**Comment by wagnerand** [comment]
_Users_ and _Ratings_ pages are also affected. The _Users_ page does not load at all, the _Ratings_ page needs almost half a minute to load.

**Comment by diox** [comment]
Good news: it's also relatively slow on stage, so we can test there - though it depends on the admin.

It's caused by the extra `JOIN` made to find and return the IP addresses, and also the fact that these are made twice - once for the `count(*)` used in the pagination, once for the results themselves.

At the moment, on stage:
- The original query takes ~ 9 seconds (!) just for the `COUNT(*)`
- Removing the `GROUP_CONCAT` but leaving the `JOIN` gains ~ 1-2 second
- Removing the listed/unlisted counts (which forces a query on yet another table) gains ~ 3-4 seconds
- Removing the `JOIN`s on activity log gains another ~ 3-4 seconds 

A few ideas:
- Start by making it so that the pagination count doesn't use annotations/joins. Since the pagination count costs half the time it takes really.
- Don't do the annotations/joins when we're not showing the IP
- Look into finding ways to optimize the query - it's tough because it fetches data from a bunch of different tables...
  - Removing the `_ip_address` `CharField` on `IPLog` probably wouldn't help here, but it wouldn't hurt either...

**Comment by diox** [comment]
QA: let's check performance of user admin list, addon admin list, ratings admin list, then  repeat with an IP search. On dev and stage.

**Comment by ioanarusiczki** [comment]
@diox 

On AMO dev -> none of the admin modules had problems loading or going on a particular entry /change/ 

On Users -> the IP search with multiple ID takes a while until it return results. Also here I cannot add to the search query using the green "+" a new IP. This is working for ratings and addons.

I verified users and ratings for issues in the last couple of milestones -> I don't remember having timeouts

In case I should try actions on multiple entries please let me know, I'd be careful with what I ban/reset for users.

**Comment by diox** [comment]
> On Users -> the IP search with multiple ID takes a while until it return results. Also here I cannot add to the search query using the green "+" a new IP. This is working for ratings and addons.

Could you link the exact URL you were on with the query you made ?

**Comment by ioanarusiczki** [comment]
@diox Sure, an example [here](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/?q=188.24.88.85%2C79.119.133.80%2C79.119.157.255%2C86.122.38.93%2C78.96.81.4%2C78.97.216.42%2C+91.232.94.148%2C188.27.131.96%2C84.117.102.49%2C188.27.128.8%2C79.119.174.15%2C49.36.54.132%2C+5.2.199.196%2C50.65.179.42%2C82.119.30.121%2C213.209.97.204)

**Comment by diox** [comment]
Ok, it's possible the +/- feature was temporarily broken for you because of the random issues on dev, that could have prevented the necessary JavaScript from loading.

**Comment by ioanarusiczki** [comment]
@diox 

I tried on AMO stage with [this search](https://addons-internal.stage.mozaws.net/en-US/admin/models/users/userprofile/?q=35.226.182.48%2C+78.96.80.116%2C+79.119.133.80%2C+62.231.93.2%2C+34.68.142.105%2C+188.24.88.85%2C+73.143.28.214%2C+91.209.45.248%2C+79.119.186.119%2C+54.86.50.139%2C+104.154.109.14%2C+104.154.113.238%2C+104.154.114.121%2C+104.154.158.13%2C+104.154.216.252%2C+104.154.236.164%2C+104.154.240.184%2C+109.166.137.206) on users -> went slower but I did not get timeouts

Same query is moving a lot faster for ratings or addons. Users has a lot of entries compared to the other 2.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-230
