### ISSUE TITLE
Show auto approval delay unlisted flag in reviewer tools

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20251]
Followup from #20250.

- Add-ons with temporary (not infinite) auto-approval delay (unlisted or listed) should only be shown in the Manual Review queue if the user has `Addons:TriageDelayed` permission
- Such add-ons should be shown in the queue with a distinct background and have a specific flag
- Bonus: if a version shown in the queue for an add-on is marked as needing human review or auto-approval explicitly and permanently disabled for a channel, show a specific flag
- It should be possible for users with `Reviews:Admin` to clear the unlisted auto-approval delay like it is for listed

**Edited** by @diox for clarity.

**Comment by diox** [comment]
> For such flagged submissions, we set a due date, which should be the same value as the config in https://github.com/mozilla/addons-server/issues/20250.

If the config ever changes, this is going to be annoying: we'd either have inconsistent due dates, or we'd need to find all existing versions with the flag, figure out the difference between the old config value, and add/substract that to the original due date to fix it...

**Comment by ioanarusiczki** [comment]
@diox 

I tested on AMO dev: 

- an [unlisted](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/624943)/[listed](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/624945) addon delayed temporarily because of a scanner rule -> are displayed in the Manual Queue with Needs Human Review and Unlisted/Listed Auto-Approval Delayed Temporarily flags and a due date set to 23 hours (equal to it's delay for auto-approval). I cleared the delays then the versions got auto-approved but they stay in the queue because of the Human Review flag. Only after confirming approval the addons are no longer in the Manual Queue. 

- an unlisted addon delayed temporarily because of INITIAL_DELAY_FOR_UNLISTED set -> it is displayed in the queue. I cleared the unlisted auto-approval extra-delay from it's review page -> the addon is automatically removed from the queue and gets auto-approved immediately after.

- I've noticed that an Admin reviewer with Addons:TriageDelayed can view and clear the flag (I added my user to Reviewers:Admins, Reviewers:Addons and Reviewers:Unlisted in order to test the scenarios above). Also this can be done as admin `*.*`
Without Addons:TriageDelayed the delayed temporarily addons are not visible for the reviewer.

- the delayed temporarily addons have a yellow background in the manual review queue. If the temporary delay is cleared and still have the human review flag set the background becomes white.

- each flag has an associated symbol which is present in the Flags column : needs human review, delayed temporarily and disabled listed/unlisted auto-approval. 

I am not sure if the due date in the first scenario is as expected. Except for that it should be alright.

**Comment by ioanarusiczki** [comment]
@diox And is the due date set to 23 hours alright? For the rest of the cases it's 4 days. Initially it is 4 days (now that I checked again) https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/624947 After the auto-approval script runs it also gets the needs human review flag and then the due date changes.

**Comment by diox** [comment]
That's intended, we specifically use the date the temporary delay expires at as the due date when it's set by a scanner action.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-233
