### ISSUE TITLE
Deleted add-ons and versions should show up in the Manual Review queue

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20256]
Per title.

Change `objects` to `unfiltered` in:
https://github.com/mozilla/addons-server/blob/d821a0bb86094ee2f2fed7ac5e5c125d0caa8978/src/olympia/reviewers/utils.py#L161
https://github.com/mozilla/addons-server/blob/d821a0bb86094ee2f2fed7ac5e5c125d0caa8978/src/olympia/addons/models.py#L292

**Comment by eviljeff** [comment]
Does this just apply to add-ons that are flagged for needs_human_review?  (blocked by https://github.com/mozilla/addons-server/pull/20252)

Because otherwise in `should_have_due_date`:
- for deleted add-ons in we specifically filter on the add-on status for listed versions that otherwise need manual approval - and only consider `amo.VALID_ADDON_STATUSES` - i.e. nominated and approved.  
- for deleted versions needing manual approval (both listed and unlisted) we filter on file status being `amo.STATUS_AWAITING_REVIEW` - whereas deleting a version sets it's files to `amo.STATUS_DISABLED`.

**Comment by diox** [comment]
Had not realized but yes, that makes sense, only add-ons explicitly flagged as needing human review.

**Comment by AlexandraMoga** [comment]
I've verified this issue on stage and these are my results:

- [listed deleted addon](https://reviewers.addons.allizom.org/en-US/reviewers/review/1007496) -  the add-on is still present in the Manual review queue after the addon is deleted, if it was already in the queue prior to its deletion;
- [unlisted deleted addon](https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1007867) - the add-on is still present in the Manual review queue after the addon is deleted, if it was already in the queue prior to its deletion;
- [listed addon with deleted version](https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1008189#review-actions) - the add-on is still present in the Manual review queue after a version flagged for human review is deleted; 
  - if I submit a new version which gets [Approved](https://reviewers.addons.allizom.org/en-US/reviewers/review/1008165)/[Confirmed Approved](https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1008189#review-actions), the add-on will continue to be present in the queue due to the previously deleted version
- [unlisted addon with deleted version](https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1008195) - the add-on is still present in the Manual review queue after a version flagged for human review is deleted

@wagnerand as far as I can tell, there is no way to remove deleted addons/versions  from the Manual queue with the available reviewer actions. The only option I found to remove them was by using the Admin Version manage by deleting the `due_date` field there.

**Comment by wagnerand** [comment]
@eviljeff how would a reviewer be able to remove such an entry from the queue?

**Comment by eviljeff** [comment]
> @eviljeff how would a reviewer be able to remove such an entry from the queue?

At the moment it may not be possible - the reviewer tools weren't built with the idea that actions could be taken on deleted add-ons.  

@AlexandraMoga can you log a follow-up to enable some of the actions to work on deleted add-ons. @wagnerand which actions would be appropriate?

**Comment by AlexandraMoga** [comment]
> @AlexandraMoga can you log a follow-up to enable some of the actions to work on deleted add-ons

filed https://github.com/mozilla/addons-server/issues/20326

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-234
