### ISSUE TITLE
Don't open new tab when reporting a scanner result as false positive

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20260]
### Describe the problem and steps to reproduce it:

1. Have a submission being flagged by a scanner.
2. On a scanner result page in django admin, click "False positive" for a result.

### What happened?

The same page opens in a new tab.

### What did you expect to happen?

No new tab should be opened (and the report should still be applied correctly).

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
Reporting a False positive for a scanner result will now open the github report page in the same tab.

**Comment by wagnerand** [comment]
@AlexandraMoga Hm, there shouldn't be a github page opened at all, at least in the scenarios that I am used. Could clarify the STR for that?

**Comment by AlexandraMoga** [comment]
@wagnerand the STR are:

1. Open a scanner result detail with matched rules, for example [this one](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/46971/change/?_changelist_filters=state%3Dall)
2. Click on False positive 

Actual results:
This [github page](https://github.com/mozilla-services/addons-customs-scanner/issues/new?title=False+positive+report+for+ScannerResult+50534&body=%23%23%23+Report%0A%0AThe+%5Bscanner+result+50534%5D%28https%3A%2F%2Faddons-internal.dev.mozaws.net%2Fen-US%2Fadmin%2Fmodels%2Fscanners%2Fscannerresult%2F50534%2Fchange%2F%29+reports+matches+of+the+following+_customs_+rules%3A%0A%0A%0A-+%60CLONE_DETECTION%60%0A%0A%0AHowever%2C+it+is+not+correct+for+the+following+reasons%3A%0A%0A%3C%21--+Please+explain+why+you+are+reporting+a+false+positive+here.+--%3E%0A%0A%23%23%23+Metadata%0A%0A%7C+Name++++++++%7C+Value+++++++++++++++++++++++++++%7C%0A%7C-------------%7C---------------------------------%7C%0A%7C+Add-on+GUID+%7C+%7B916e5737-7f95-42e0-b98b-7707a5414d01%7D+%28%5Bproduct+page%5D%28https%3A%2F%2Faddons-dev.allizom.org%29%29+%7C%0A%7C+Version+ID++%7C+1698054+%7C%0A%7C+Channel+++++%7C+Unlisted+%7C%0A%7C+Scanner+++++%7C+customs+%7C%0A%0A%0A&labels=false+positive+report%2Crule%3A+CLONE_DETECTION) opens in the same Tab.


I have the same results if I click on False positive in the Scanner results list.

I've checked stage when your changes were available only on -dev and I was landing on the same github page but in a new tab at that time. 

Also, the github page is a 404 for me because I do not have access to that repo.

**Comment by wagnerand** [comment]
Ah, I believe this is for scanner results for customs only. That's fine. Results for yara rules shouldn't redirect to github.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-236
