### ISSUE TITLE
Increase the default due date to 4 days

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20277]
We'd like to increase the default due date for reviews to 4 days, existing entries do not need to be updated.

**Comment by ioanarusiczki** [comment]
@wagnerand 

I verified this on AMO dev, I have 2 examples:

- a [recommended add-on](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/624643) with due date set to 5 days, 23 hours from now
- an[ addon with unlisted versions](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/624746), due date was 5 days, 23 hours from now

For both the due date looks good, my question is about the unlisted addon -> I submitted v 7.0 first then 8.0 and I've noticed that the addon is displayed in the [Manual Queue](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/extension?page=2) but then these versions are auto-approved automatically. The addon has been flagged by scanners too because of detected rules.  Is it alright for these versions to be auto-approved in this case?

**Comment by diox** [comment]
If the action attached to the scanner rule was just to flag the add-on, yes. In that case, the relevant version should keep its due date even after auto-approval, and the add-on should stay in the queue until a reviewer looks at it.

**Comment by ioanarusiczki** [comment]
@diox It's auto-approval delayed indefinitely , it's [listed version](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/624746) is automatically delayed for auto-approval.

**Comment by diox** [comment]
I suspect you've found an issue with the rules/actions engine - it's hard to tell with so many rules matching. Maybe something with conflicting actions attached to rules (the versions for that add-on match multiple rules, with different actions setting different delays which could conflict) or maybe something else. Please file a separate issue about this.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-242
