### ISSUE TITLE
Delay rejection sent with another reviewer's name

### ISSUE THREAD

**Issue by iulianacse** [mozilla/addons-server#20371]
The add-on in case: {d2962de1-cbb0-4c3d-8f37-5f288c83bcfe}

A previous reviewer sent a delay rejection for that add-on. As the first delay rejection was expiring tomorrow and I wanted to give the developer more time to reply, so I sent another delay rejection, but it got sent with the previous reviewer's account. 

I know the developer does not see the reviewer's name, but it will mess with our statistics.

**Comment by diox** [comment]
Nice find.

The `reject_multiple_versions` action explicitly sets the `user` of the `ActivityLog` to the user that the pending rejection was made for:
https://github.com/mozilla/addons-server/blob/918288b6c946ba5e82bf656a6921b13f8d1bd3b4/src/olympia/reviewers/utils.py#L1189

This allows us to correctly assign the actual rejection to the user that did the delayed rejection - since it will re-use the same action. Then `pending_rejection_by` property it uses is set *after* the log has been recorded. The only reason why this works for the first delayed rejection is that `pending_rejection_by` would then be `None` (it hasn't been set yet), which would make the `ActivityLog` code use the current `user` from the thread...

We should probably flip this around, recording the `ActivityLog` after the `if self.human_review` instead of before in:
https://github.com/mozilla/addons-server/blob/918288b6c946ba5e82bf656a6921b13f8d1bd3b4/src/olympia/reviewers/utils.py#L1184-L1209

**Comment by ioanarusiczki** [comment]
@eviljeff 

I delayed for rejection 2 addons:

On dev https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/624977 I rejected with a delay a version twice using 2 different reviewer accounts 
Same for this one https://reviewers.addons.allizom.org/en-US/reviewers/review-content/1008426#review-actions on stage

I checked for both the activity log - admin and I saw 2 different names. The review pages also display 2 different reviewers.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-266
