### ISSUE TITLE
Don't set needs_human_review when adding an add-on to Notable group if it has already been reviewed by a human

### ISSUE THREAD

**Issue by iulianacse** [mozilla/addons-server#20405]
Add-on: Flight_Tab_Pro___Custom_Web_Search_yVOErTvhoC@flighttabpro.com

This add-on has been lastly reviewed on 14 Dec 2021 and it appeared now in the manual queue, as it has a due date.
The add-on is listed and having the last version reviewed it shouldn't need a review now.

**Comment by diox** [comment]
We shouldn't set `needs_human_review`=`True` on an addon that becomes part of a promoted group with `flag_for_human_review` if the `current_version` already has an `human_review_date` set.

**Comment by diox** [comment]
BTW, this is something to think about for every future place where we set `needs_human_review`: if it has already been reviewed by a human, do we really need to set that flag, causing it to be reviewed a second time ? Sometimes the answer can be yes, but here it's clearly counter-productive.

**Comment by ioanarusiczki** [comment]
@diox 

How can I make a new notable add-on on AMO dev ? There's a [small list](https://addons-dev.allizom.org/en-US/firefox/search/?sort=users) which has already been used for testing.  

I remember it required some prod guids to make an addon have ADU in stats , I am not sure it's enough.

**Comment by ioanarusiczki** [comment]
@diox 

I moved 2 addons into Not Promoted group (from Notable) 
[This one ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/617049) -> while being not promoted I approved version 2.1.7. After the cron job ran I checked the manual review queue and I did not find it here. 

[The other one ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/502955) was already approved, I confirmed approval. After it got back into the Notable group after 13:30 UTC -> it's not displayed in the manual review queue

I don't know why [in admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?group_id__exact=7) the Firefox Color has a a red "X" at Is Approved -> because it's been approved.

**Comment by diox** [comment]
> I don't know why [in admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?group_id__exact=7) the Firefox Color has a a red "X" at Is Approved -> because it's been approved.

That's not the same kind of approval. It's an approval for the promotion, which isn't meant for notable.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-273
