### ISSUE TITLE
Add listed addons with non-public version to Notable group once they cross user threshold

### ISSUE THREAD

**Issue by wesinator** [mozilla/addons-server#20422]
### Describe the problem and steps to reproduce it:
related to #20405 

Listed addons with non-public versions should still be added to the Notable group once the user threshold is reached. 

### What happened?
We had a case with `869387`, where an addon version got approved and crossed the threshold for notable before the addon version was listed. 
The next version they uploaded 8 days later had a due date set from the previous version, making the due date the same day as the newest version upload date. 

### What did you expect to happen?
Due date for the new version should have been the typical week due date. 

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
The due date thing is because of the fact that `needs_human_review` was set on the version that had just been approved - that's essentially https://github.com/mozilla/addons-server/issues/20405

But the fact remains, we should add add-ons to the notable group whether they are public or not. This is similar to https://github.com/mozilla/addons-server/issues/20351, but that issue is blocked on deciding what to do about unlisted versions. Here we care mostly about ensuring the add-on is added to the notable group so that future listed versions are never auto-approved.

So STR could be something like:
- Delete the only listed version of an add-on.
- Make the add-on cross the user threshold for notable somehow

Expected results:
- The add-on should be put in the notable group next time the cron runs

**Comment by ioanarusiczki** [comment]
@diox 

On -dev this [notable add-on ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/495646) was moved into Not promoted. Then I deleted the listed versions and waited for the cron job 

Results:
- it's back into the [Notable group ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?group_id__exact=7)
- it's present in the Manual review queue , flagged for human review with a due date 4 weeks 1 day ago. I hope that's alright.

**Comment by diox** [comment]
mmm that due date is in the past, which would suggest it had already been set (and the version was already needing human review) before you altered it to make it not notable, so I'm not sure it's a good test.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-278
