### ISSUE TITLE
Can't upload new version of the dictionary (again)

### ISSUE THREAD

**Issue by mtrevisan** [mozilla/addons-server#20571]
Hi all.
I have the very same problem with my dictionary as stated in [issue #20183](https://github.com/mozilla/addons-server/issues/20183).
My locale is vec-IT and my xpi is located [here](https://github.com/mtrevisan/VenetanSpellChecker/blob/dev/dict-vec-xpi/dict-vec.xpi.zip) (vec is a valid ISO 639-3 code)
Thank you

**Comment by diox** [comment]
Hi,

It's a similar problem than #20183 indeed - your add-on `target_locale` is `vec` in AMO, but that xpi targets `vec-IT`.

@wagnerand should be able to fix that.

**Comment by mtrevisan** [comment]
I wanted to make a reflection: the Venetan language is spoken not only in Italy, but also in other parts of the world (Mexico, Brazil, Slovenia, etc). Apart from that, the plugin I wrote is a dictionary of a language, not a treatise on geography. It therefore seems strange to me that a country code enters the definition of the xpi targets. So, if it were for me, I'd drop the "-IT" part altogether and leave "vec". But this is only my thought.

**Comment by diox** [comment]
The country code part is not mandatory, it's there to specify that the dictionary (or language pack) is targeting a specific regional variant of the language. This is extremely common, precisely because although the same language can be used in different regions, there can be subtle localized differences. A common example is British English spelling vs American English spelling (colour vs color), or Canadian French vs France French.

Ultimately though, it's your choice. You could change the target from your dictionary to `vec` yourself, since this is specified in the `xpi`. Or let us modify the AMO listing to make it target `vec-IT`, matching the contents of the `xpi`.

**Comment by mtrevisan** [comment]
I'd rather change the target in my dictionary.

**Comment by wagnerand** [comment]
@mtrevisan can you provide the ID of your add-on?

**Comment by mtrevisan** [comment]
Sure, I changed the target from my dictionary to vec

**Comment by mtrevisan** [comment]
Sorry, maybe you meant ***@***.***

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-323
