### ISSUE TITLE
All new unlisted addons are currently getting set to "needs human review" even after auto-approval

### ISSUE THREAD

**Issue by wesinator** [mozilla/addons-server#20573]
### Describe the problem and steps to reproduce it:
All new unlisted addons that get auto-approved, after human triage and clearing the auto-approval delay, are ending up in the manual review queue 

Noticed this starting the week of April 3rd. 

our internal discussion suspects the root cause is that all new addons are getting set to "needs human review"

### What happened?
New unlisted addons that are auto-approved after human unlisted triage are getting added to the manual review queue.

### What did you expect to happen?
New unlisted addons that have been processed in triage (cleared auto-approval delay) and auto-approve should not be added to the manual review queue.

**Comment by diox** [comment]
Essentially we were erroneously setting `needs_human_review` on every new upload if _any_ version belonging to _any_ add-on had `needs_human_review` set in the same channel. Since that will almost always be true, all new uploads were getting `needs_human_review`. Yikes.

**Comment by AlexandraMoga** [comment]
I think this issue is what @ioanarusiczki was trying to say in https://github.com/mozilla/addons-server/issues/20545#issuecomment-1497509038:

> I've noticed that flagged for human review is now present for all addons/versions I submitted even when I used dummy extensions.

I've made several new addons/new version submissions on stage today and I'm no longer seeing addons that should not have a "needs human review" flag in the Manual review flag.  

That being said, I think that testing on https://github.com/mozilla/addons-server/issues/20545 should be redone to make sure that "needs human review" inheritance works as expected. 

I'm marking this issue as verified fixed on stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-324
