### ISSUE TITLE
Unlisted add-on delayed auto-approval timer starts when the add-on is created

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#20586]
### Describe the problem and steps to reproduce it:
When an unlisted add-on is created the auto-approval delay timer starts. If the first version is submitted later, the add-on's versions can get auto-approved before the delay that the reviewer expects, giving the reviewer less time to get to an add-on.

### Reproduction
* Unlisted add-on is created at time `x`
* First unlisted version is submitted at time `y` which is after `x`
* Add-ons versions are auto-approved at time `x + extra_delay`

### What did you expect to happen?
* Add-on's versions should be auto-approved at time `y + extra_delay`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-328)

**Comment by eviljeff** [comment]
Note this should only be a thing when the older signing (now only v3 and v4) is used - with the submission api (and devhub) the addon is only created when the first version is.  @diox was there some reasoning behind using the add-on creation date rather than version creation date?

**Comment by diox** [comment]
It's because we needed a fixed date regardless of how many unlisted versions have been created. We potentially reset the delay at every submission - with the current code, it will always be the same delay, so there isn't any risk of accidentally increasing it that way.

At the point where the code is running the version has been created, so we're guaranteed to have at least one unlisted version, so we could just pick the oldest unlisted for that add-on instead.

**Comment by eviljeff** [comment]
we don't use this particular timer currently so closing this issue for now

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-328
