### ISSUE TITLE
Auto-approvals are not working on AMO -dev

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20666]
### Describe the problem and steps to reproduce it:
1. Upload a new unlisted addon or a new listed addon version - the scope is to upload an addon that would normally be auto-approved without any delays
2. Wait for the add-on to be auto-approved

### What happened?
The auto-approval doesn't run in the expected amount of time (~5 mins intervals). Addon remains in Awaiting Review status. 

### What did you expect to happen?
Addons should be auto-approved

### Anything else we should know?
- I was able to approve an addon manually from Reviewer tools, so autograph seems to be responding this time 
- examples: [listed new version](https://addons-dev.allizom.org/en-US/developers/addon/search-new-addon/versions), [unlisted addon](https://addons-dev.allizom.org/en-US/developers/addon/130458f159db41e9b3a4/versions)

@diox could this regression be caused by https://mozilla-hub.atlassian.net/browse/SVCSE-1212?

**Comment by diox** [comment]
Possibly related yes.

Other failures that are definitely caused by this change:
- https://mozilla.sentry.io/issues/4168764107/?project=6224627&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
- https://mozilla.sentry.io/issues/4168764060/?project=6224627&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1
- https://mozilla.sentry.io/issues/4168431784/?project=6224627&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=4

Maybe the celery worker instances (servers processing tasks) and admin instances (server processing recurring jobs like auto-approval) were not restarted after this config change ? Or maybe the path is still hardcoded somewhere else in the settings.

**Comment by diox** [comment]
@AlexandraMoga logs do say there was a signing error. Is manual approval broken too (using a different add-on) ?

**Comment by AlexandraMoga** [comment]
@diox manual approvals from RevTools are working.

**Comment by diox** [comment]
@AlexandraMoga could you try again with new versions ?

**Comment by AlexandraMoga** [comment]
@diox new submissions will be auto-approved but the ones uploaded yesterday are still stuck in Awaiting Review.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-344
