### ISSUE TITLE
Record why a version was flagged for human review

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20687]
We have various bits of code that can flag a version for review, setting `needs_human_review` boolean to `True`. We should add 2 things when that happens:
- A model recording why that happened, so we could then later make stats on that data
- An `ActivityLog` that could then be displayed in the review page with a human-readable comment explaining why that happened.

The information would be kept even after a reviewer reviews the version, for historical purposes.

Possible reasons (more to come):
- Unknown (not-automated)
- Scanner action
- Add-on entered a promoted group that flags already approved versions (At the moment, only Notable does that)
- Inherited from a previous version
- Sources were provided on a version pending rejection
- Developer reply

**Comment by diox** [comment]
Note: a very basic admin (for staff users with `*:*` permission) is available under the `reviewers` app to help debug/verify that this is recorded properly.

**Comment by ioanarusiczki** [comment]
@diox 

1. Version delayed indefinitely or temporary by scanners get "Hit scanner rule" reason 
- While there's no decisive reviewer action and they're awaiting review, clearing needs human review from the reviewer page or from admin will not have an effect -> they're still displayed in the manual review queue 
- Approval/Rejection un-check "is active" checkbox and after review they're no longer displayed in the manual review queue 
-  a reviewer can manually set needs human review (from the version's review page) and "Manually set as needing human review by a reviewer" reason is displayed in admin. If previously the version was approved it will show up again in the Manual Review Queue. When awaiting review versions were rejected, needs human review set manually from rev tools page or admin will not have any effect -> awaiting review and then rejected versions are not displayed back into the queue. 

2. I've also tested and noticed the "Previous version in channel had needs human review set", "Sources provided while pending rejection" and "Developer replied" reasons which showed up when expected. 

3. There's a "Unknown" reason that I've noticed in admin to a couple of versions having the creation date May 17, 2023. I don't know what caused this. 
 
4.  Now the "Set needs human review" button is always active on pages meaning that "Manually set as needing human review by a reviewer" can be repeated over and over again -> [an example ](https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/version/1699212/change/)


5. I'll have to check the Notable tomorrow , I thought I prepared the samples but I forgot, so now I made 2 versions from Notable ->not promoted and submitted new versions, these will get auto-approved since they're out of the group until the cron-job runs.

**Comment by diox** [comment]
> While there's no decisive reviewer action and they're awaiting review, clearing needs human review from the reviewer page or from admin will not have an effect -> they're still displayed in the manual review queue

Do you have a link for an add-on where that happened to you on dev ?

> When awaiting review versions were rejected, needs human review set manually from rev tools page or admin will not have any effect -> awaiting review and then rejected versions are not displayed back into the queue.

Yeah, only signed versions are considered for needs human review, that's not a new thing (that's https://github.com/mozilla/addons-server/issues/20479)

> There's a "Unknown" reason that I've noticed in admin to a couple of versions having the creation date May 17, 2023. I don't know what caused this.

That's for all past needs human review versions from before we started recording reasons. It's good that it's there, means the migration worked.

> Now the "Set needs human review" button is always active on pages meaning that "Manually set as needing human review by a reviewer" can be repeated over and over again

Yeah. I figured this wasn't a big deal, and in the future could be useful to allow a version to be flagged by different reviewers for instance.

**Comment by ioanarusiczki** [comment]
@diox Except pct. 4 where I really wasn't sure, the other cases I described should be fine. I needed to double check because I was like 98% sure. 

Thanks for answering, I'll mark this verified on AMO dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-354
