### ISSUE TITLE
create view/endpoint to return per-version ADU for reviewer tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20700]
part of https://mozilla-hub.atlassian.net/browse/AMO-70

We want a json endpoint that will return ADU per version for a given addon id.  This is to be consumed by the reviewers tools review page to asynchronously show on the page.  Data should be queried directly from bigquery statistics.

**Comment by ioanarusiczki** [comment]
@eviljeff I should make requests to this endpoint but I don't know it's format. Can you share some info?

**Comment by eviljeff** [comment]
@ioanarusiczki it's `/reviewers/usage_per_version/<addon-id>` where `<addon-id>` is the numeric id. json will be returned - an object with the keys as the version strings and the values as the average adu for that version over the past 2 weeks (actually a range from today to -13 days for consistency with the overall ADU calculation - but depending on the time of day it might be slightly different if today's numbers are in bigquery at that point). The top 100 versions are returned but I don't think any of the add-ons we have on -dev will have that many version with active users.

For sense-checking the numbers you could compare to the stats dashboard for the add-on, where it has a day by day per version breakdown.  `/addon/<addon-id>/statistics/usage/versions/`.  (You likely don't need to calculate averages for every single version though)

Note: not all add-ons have stats on dev.  https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/amo_dev/amo_stats_dau_v2/query.sql#L15-L25 has the ones that do (I used for testing `@contain-facebook`)

**Comment by ioanarusiczki** [comment]
@eviljeff 
From the browser I tried 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/usage_per_version/617049
https://reviewers.addons-dev.allizom.org/en-US/reviewers/usage_per_version/495646 

and they return data , an example
`{"2.1.7": 113135, "2.1.5": 115, "2.1.6": 63, "1.0.1": 17, "2.1.2": 12, "2.1.0": 8, "Unknown": 5, "2.0.0": 4, "1.0.0": 1}`

but values don't match with the [statistics per versions](https://addons-dev.allizom.org/en-US/firefox/addon/firefox-color/statistics/usage/versions/?last=30) , right now at least because the last date is Mon, May 22, 2023 and the endpoint might be up to date.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-356
