### ISSUE TITLE
Show the highest ADU versions in a block in the review page

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20702]
part of https://mozilla-hub.atlassian.net/browse/AMO-70

> Display the block that shows the top 10 most used versions
> -    The individual versions in the list have links to the review section that contains the version

**Comment by ioanarusiczki** [comment]
On -dev or -stage most of the versions don't have a link since those version don't even exist but I managed to check the links too with FirefoxColor@mozilla.com 

On a laptop scren or when resizing the new section might overlap the footer so if that's an issue, let me know

![laptop](https://github.com/mozilla/addons-server/assets/33448286/8a6ce2ad-3944-4121-a09e-8e8d0a538057)
![resized](https://github.com/mozilla/addons-server/assets/33448286/98ea8f27-d21b-4d3c-8153-c658debaf1b6)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-358
