### ISSUE TITLE
Denied Rating Words should support domains

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20710]
### Describe the problem and steps to reproduce it:

Adding a denied rating word like `example.com` should match strings like `Get my great app at app.example.com!`

### What happened?

According to @eviljeff, patterns containing a `.` currently don't match at all.

### What did you expect to happen?

See above.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
This conflicts with the original implementation from #20499 and it's follow-up #20547. So at the very least we need to answer the following questions:

If the pattern is `foo`:
- Should you match `foobar` ?
- Should you match `foo.bar` ?
- Should you match `foo bar` ?
- Should you match `foo-bar` ? (same question for a bunch of other separators)

If the pattern is foo.bar`:
- Should you match `bazfoo.bar` ?
- Should you match `foo.bar.baz` ?
- Should you match `foo.barbaz` ?
- Should you match `foo.bar.` ?

(And probably a lot more)

**Comment by kplotnik** [comment]
@wagnerand to review the questions and come back with the answers by 13.06.23

**Comment by wagnerand** [comment]
After talking to @kplotnik, @abhn can you look into this?

**Comment by abhn** [comment]
@eviljeff As per our discussion yesterday, let's do this

- **If the denied rating word doesn't contain a period (`.`)**: 

Tokenize the ratings string and match. 
Essentially, `"google.com is a searchengine"` becomes` ["google", "com", "is", "a", "searchengine"]`. My understanding is that this is how it works right now, if I'm reading this right https://github.com/mozilla/addons-server/blob/3e504b1c4c80fb191dcf73291991f9bd22abc609/src/olympia/ratings/models.py#L398

- **If the denied rating word contains a period (`.`)**: 

Treat the query as a strict match and try to match it on the untokenized rating string (or just add `.` to the match regex `r'[^\w.]+|_+'` so that "google.com" is one token and not `["google", "com"]`

Any feedback on this is welcome! 😸

**Comment by abhn** [comment]
Following up on my previous comment and to answer @diox's questions

```
If the pattern is foo:

    Should you match foobar ? // no (no token foo in this)
    Should you match foo.bar ? // yes (since foo.bar are "foo" and "bar")
    Should you match foo bar ? // yes 
    Should you match foo-bar ? // yes (again, foo-bar are "foo" and "bar")

If the pattern is foo.bar:

    Should you match bazfoo.bar ? // yes
    Should you match foo.bar.baz ? // yes
    Should you match foo.barbaz ? // yes
    Should you match foo.bar. ? // yes
```

**Comment by wagnerand** [comment]
If we don't want to match `foobar` for `foo`, what is the rationale behind matching `barfoo.bar` for `foo.bar`? This could create some false positives, are we ok with that?

**Comment by abhn** [comment]
My proposal is to treat search strings with `.` differently than search strings without `.` because of sentence boundaries ("sentence that ends with foo.next sentence" matches "foo" since `.` gets omitted when tokenizing, which is intended). 

But when the search string itself has `.`, like `foo.bar`, we want the `.` to stay after tokenization, so "sentence that contains link foo.bar sentence ends here" will match "foo.bar". This way, we can have a `obscuredomain123.xyz` search query. 

If we look at the spammy domains of the recent past, they seemed particular enough to not get caught in the "legitimate sentence ends.new sentence" case. But do you see other cases where this could fail?

**Comment by eviljeff** [comment]
QA: I also added model validation that should be used when you use django admin to add words - it should stop any being added that won't work (anything non-alphanumeric; except for when there is a `.`, then anything is allowed)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I tested with the cases mentioned [above ](https://github.com/mozilla/addons-server/issues/20710#issuecomment-1592633736) on AMO stage - I confirm it's working as expected. 

The module `/admin/models/ratings/deniedratingword/` won't accept non-alphanumeric except for `.`

Frontend message when flag for moderation is not checked: 

![frontend](https://github.com/mozilla/addons-server/assets/33448286/7db251d8-64ae-4132-910e-3ad43ef74fe1)

With the flag checked , reviews would enter the [Ratings Awaiting Moderation](https://reviewers.addons.allizom.org/en-US/reviewers/queue/reviews?page=2) queue with a delay (which is a known issue)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-360
