### ISSUE TITLE
Don't show links to code manager to developers in validation results (but still show them to reviewers)

### ISSUE THREAD

**Issue by ultronstudio** [mozilla/addons-server#20725]
I wanted to look at the code for the manifest.json of my HopHub extension, but this is what I got.
![image](https://github.com/mozilla/addons-code-manager/assets/71195567/88463078-5d12-4daa-b2bd-7c7b7a794b46)

**Comment by diox** [comment]
This should be fixed in production when this lands in a couple weeks (see milestone).

QA:
- As a developer, in validation results at upload time, when displaying the filename corresponding to where an error is coming from (like `manifest.json` or specific js files) inside the xpi, there should **not** be a link to the code manager
- As a developer, when viewing validation results of an already posted version (linked from the version edit page), when displaying the filename corresponding to where an error is coming from (like `manifest.json` or specific js files) inside the xpi, there should **not** be a link to the code manager
- As a reviewer, when viewing validation results of an already posted version (linked from the review page), when displaying the filename corresponding to where an error is coming from (like `manifest.json` or specific js files) inside the xpi, there **should** be a link to the code manager

**Comment by ioanarusiczki** [comment]
@diox 

I verified this on AMO stage:

- as a developer the files from the validation page cannot be accessed while uploading or from version's page.
- I could click the files that triggered warnings as an admin from the reviewer's pages or dev hub.
- as an addon reviewer or admin reviewer the files can be clicked and redirect to code-manager , from review pages in Validation results.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-364
