### ISSUE TITLE
Investigate if we need code change to use the SaaS elasticsearch

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#20730]
### Describe the problem and steps to reproduce it:
We'll be using the SaaS Elasticsearch on GCP.

Please investigate if any code change is needed in order to use the SaaS Elasticsearch. By looking at https://elasticsearch-py.readthedocs.io/en/v7.17.10/, I suspect the `get_es()` may need to be changed because we don't do any authentication currently.

### What happened?
Moving to GCP, the way we connect to an Elasticsearch cluster may need some changes.

### What did you expect to happen?
Be able to talk to the SaaS Elasticsearch while at same time continue to be able to talk to the self-hosted ES cluster on AWS.

### Anything else we should know?
n/a

**Comment by diox** [comment]
Actually, I don't think we need to do anything, because `Elasticsearch` class should allow passing an URL with or without auth already.

Which means we should be able to use the following `ES_HOSTS` environnement values today:
- `host` e.g. `localhost`
- `host:port` e.g. `localhost:9200`
- `scheme://host:port` e.g. `https://localhost:9200`
- `scheme://user:password@host:port` e.g. `https://foo:bar@localhost:9200`

Note: despite the plural in the env var name, only use a single url.

**Comment by bqbn** [comment]
Using `https://user:password@hostname` worked. I think we can close this issue.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-366
