### ISSUE TITLE
Firefox for Android as category should not be visible for static themes in dev hub 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20780]
Followup for https://github.com/mozilla/addons-server/issues/20757#issuecomment-1569974139

There's still information left for Categories in dev hub this is displayed:

![categories](https://github.com/mozilla/addons-server/assets/33448286/61355ed8-eb12-4519-98f7-619f525d8b47)

**Comment by eviljeff** [comment]
Is this for a new theme submission?  (I'm not sure why we are adding Android compatibility for themes if it's new; I thought we removed Android compat for existing themes?)

**Comment by ioanarusiczki** [comment]
@eviljeff Yes, I've submitted https://addons.allizom.org/en-US/developers/addon/android-in-dev-hub/edit and Firefox for Android is always displayed at Categories.

**Comment by willdurand** [comment]
Might be good to bump up the priority on this issue?

**Comment by eviljeff** [comment]
Note: this really only affects how the categories are rendered on devhub before editing.  If [Edit] is chosen and the form loaded to change the categories there is only a single group of radio buttons that don't mention Android.  The categories don't affect app compatibility (that is defined per version rather than per add-on), and we don't expose static themes on the frontend homepage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-385
