### ISSUE TITLE
Reviewer Tools "review" page sometimes show an add-on version instead of ADU

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#20814]
See:

![Screenshot 2023-06-09 at 09 31 02](https://github.com/mozilla/addons-server/assets/217628/06795395-4909-4cc0-8b61-380a29da6096)

It might be related to these lines: https://github.com/mozilla/addons-server/commit/ed835856095dce54253b444ab03ddeeac8f3e59c#diff-2d4f865b1c316ca0dbe02f7ca5c94a1b600009312b96b632d0f9427963bfddbaR518-R519

**Comment by eviljeff** [comment]
I think it's just that the array is a list of 2 pairs and it should be showing the second of the pair (the ADU number) rather than rending the version string too.

(This will only be reproducible on add-ons with > 100 versions in active use)

**Comment by AlexandraMoga** [comment]
> On -stage I can see this issue on 3 lang packs
> https://reviewers.addons.allizom.org/en-US/reviewers/review/417164
> https://reviewers.addons.allizom.org/en-US/reviewers/review/417166
> https://reviewers.addons.allizom.org/en-US/reviewers/review/619853

@eviljeff  I've looked at these three langpacks from stage and we are displaying the ADU now instead of the version number, but we still show a `<=` sign next to the number; this wasn't the case for the example found on dev (https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/417160) so I'm not sure what's happening here. 

![image](https://github.com/mozilla/addons-server/assets/31961530/8e4dd593-095e-47c3-b90e-dc38c3d81c94)

**Comment by eviljeff** [comment]
its `<=` because the ADU is equal to, or less than, 76 users - we don't know the exact ADU because we max out at 100 versions.

**Comment by AlexandraMoga** [comment]
> its `<=` because the ADU is equal to, or less than, 76 users - we don't know the exact ADU because we max out at 100 versions.

oh, ok. I though the ADU number was exact.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-393
