### ISSUE TITLE
Add BlockVersion to track versions that are blocked

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20838]
part of #20829 - adding the `BlockVersion` model that is created/deleted when Blocks are added/changed/deleted.

QA:
- there's a command to migrate existing blocks (we'll run on dev & stage)
- there are changes to the reviewer tools block creation integration - the `block multiple versions` command should function as before.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I don't remember for a delayed auto sign-off if it's expected: I cannot edit the blocklistsubmission by changing min or max version, I can only edit the reason.  [An example](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/247/change/?_changelist_filters=signoff_state%3Ddelayed) but the review pages have a "View Blocklist Submission" instead of "Update add-on block" so it could be expected.

**Comment by eviljeff** [comment]
> @eviljeff
> 
> I don't remember for a delayed auto sign-off if it's expected: I cannot edit the blocklistsubmission by changing min or max version, I can only edit the reason. [An example](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/247/change/?_changelist_filters=signoff_state%3Ddelayed) but the review pages have a "View Blocklist Submission" instead of "Update add-on block" so it could be expected.

that's expected (and not changed)- once a submission has been created (and that includes a change via Edit Block) only url and reason can be edited before it's approved or the delay has ended.

**Comment by ioanarusiczki** [comment]
@eviljeff 

Looking around I think it's all good. 
I verified this on AMO stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-399
