### ISSUE TITLE
[GCP migration] Code-manager files are not loading on -dev 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20886]
Could be from the GCP migration 

I am unable to open files on -dev with code-manager. At first I tried from the scannerqueryresult admin. Won't work from the reviewer pages either. 

Some examples:
https://code.addons-dev.allizom.org/en-US/browse/625454/versions/1699224/?path=assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt
https://code.addons-dev.allizom.org/en-US/browse/8542/versions/1536609/?path=sitecats.js
https://code.addons-dev.allizom.org/en-US/browse/625685/versions/1699530/

**Comment by bqbn** [comment]
The issue should have been fixed with https://github.com/mozilla-sre-deploy/deploy-amo/commit/f2534d5bdbf267cd72c666e6e24dc53724049d6b. Essentially we had to supply the asset build step with all the required env variables for that environment, i.e. https://github.com/mozilla-sre-deploy/deploy-amo/commit/f2534d5bdbf267cd72c666e6e24dc53724049d6b#diff-718f20568908f36b3ed[…]870a153af9a7a4ac8R85-R90

Please check and let us know if there are issues.

**Comment by ioanarusiczki** [comment]
@bqbn  I could access code-manager files on AMO -dev, looks good to me.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-414
