### ISSUE TITLE
Show multiple authors in unlisted add-ons list

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#2089]
The Authors column currently shows only one author. If there's more than one, it shows "..." and a popup with the remaining names. To avoid breaking the layout, I suggest we show at least the first 3 and have a toggle if the reviewer wants to see the rest.

It also looks like this column is buggy for some cases. See Addon-signed .1 by ValStage and ADB helper 0.8.2.1. They both have duplicate authors in the popup.

**Comment by eviljeff** [comment]
The duplicated authors was an unintended consequence of `JOIN`ing files to versions - the duplicates were all in add-ons that had multiple platform support.  That should be addressed via the fix for #2088 so the remaining issue is to show more authors.

**Comment by eviljeff** [comment]
Do we want *all* authors to be shown or just listed ones?  The actual review page now only shows listed ones, fwiw.  

Is implementing a toggle (rather than re-using the title attribute to show on hover) really justified for the edge case of having more than 3 authors and needing direct access to their user profiles from the queue page rather than going via /review, etc.

**Comment by jvillalobos** [comment]
> Do we want all authors to be shown or just listed ones? The actual review page now only shows listed ones, fwiw. 
I think it would be useful to show all of them both on the list page and on the review page, including the non-listed ones.
> Is implementing a toggle (rather than re-using the title attribute to show on hover) really justified for the edge case 
Yeah, you're right. If they show up in the review page it should be okay to only have the title attribute for the list page.
