### ISSUE TITLE
"Disable add-on" should be available only when blocking the entire add-on (all versions)

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20898]
Followup for https://github.com/mozilla/addons-server/issues/20748#issuecomment-1609805196

There's a "Disable add-on" option, the initial state is active (blue checkmark). When a partial block is done and disable add-on is checked the versions which have not been blocked are displayed as being approved on rev tools pages and in dev hub. The developer can no longer submit new versions and Force-enable state is available on the reviewer's pages which is expected when all versions are disabled.

An example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/625710

Frontend throws a 404 at https://addons-dev.allizom.org/en-US/firefox/addon/sample-3-blocking1/ (with 2 versions still approved)
There's a blocked add-on URL -> https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B0eff4a4f-1ace-4f07-91c1-ec7e7ad3e662%7D/

Note:
Previously on AMO Stage - when the range 0 - * was applied the add-on would be force-disabled too. On partial blocks (one version or a range other than 0 - *) force-disable did not apply.

**Comment by eviljeff** [comment]
It's not clear how to achieve the ask, that disable add-on should only be available when blocking all the versions, because if you create a blocksubmission via the admin tool directly we don't know what versions will be selected when you first load the form.
(The reviewer tools redirect is a special case, and will likely eventually be replaced with an action directly in the reviewer tools)

The instinctive fix is to not have a checkbox and model field at all, and determine it from the versions blocked at the time the submission is processed.  But how can we differentiate between "we want all _current_ versions blocked, but the developer can submit more" and "we want all current and _future_ versions blocked"?  (i.e. not add-on not disabled; and add-on disabled). This will be a common scenario when we default to blocking signed versions when rejecting.

So, I think realistically there will need to be some sort of checkbox/selection to control behaviour - _what_ the behaviours are, and what the default is, is the question.

@wagnerand @kplotnik for thoughts.

**Comment by wagnerand** [comment]
I understand that, by default, all versions are selected.

If so, how about: When all versions are/get selected, the "disable add-on" checkbox gets checked. When a version gets unselected, the "disable add-on" checkbox gets unchecked.

**Comment by eviljeff** [comment]
idea: change the checkbox (and the meaning of the underlying field) to be "disable add-on if all versions blocked"?  i.e. we'd block the add-on _if_ at the time the submission is processed there are no unblocked versions. If there were still unblocked versions (either because there was a choice not to block a particular version, or because the other version(s) were in separate delayed blocksubmissions) the add-on wouldn't be blocked.

**Comment by wagnerand** [comment]
That should work as well, as long as the admin page makes it clear what that checkbox does.

**Comment by eviljeff** [comment]
I've got a working patch for this with `disable_addon` now being a field with 3 choices:
- don't disable add-on
- always disable add-on (which will also explictly disable any other non-disabled versions for completeness)
- disable add-on if all signed versions blocked

The first two are pretty straightforward and what is there now.  For the third choice, there are some scenarios, so given an add-on with the following setups:
### Scenario A
version1: status=disabled (not signed - either rejected by us, or superseded before signing)
version2: status=approved (signed)
And the submission has only selected version2 to be blocked; the add-on **would be disabled**.
### Scenario B
version1: status=disabled (signed - rejected by us after signing)
version2: status=approved (and signed)
And the submission has only selected version2 to be blocked; the add-on **would not be disabled**.
### Scenario C
version1: status=disabled (not signed - either rejected by us, or superseded before signing)
version2: status=approved (signed)
version2: status=awaiting approval (not signed - perhaps uploaded after the submission was created because it was delayed or needed sign-off)
And the submission has only selected version2 to be blocked; the add-on **would be disabled**.  

@wagnerand do these make sense to you?  I slightly changed it to be _signed_ versions, rather than versions but perhaps that's unexpected/inconsistent?

**Comment by eviljeff** [comment]
> @eviljeff My concern here would be that for the third choice, an admin would not know what action is actually taken, since they cannot see which versions have been signed. Especially in scenario C (or a variant of scenario A where version1 is signed and to be blocked and version2 is not signed), the decision on disabling the add-on might be unexpected or even undesired.

So what is the desired behaviour?   Some changes to the scenarios when things are or aren't blocked? (please detail)  Or changes to the list of versions so, for example, the signing status is shown, or unsigned versions _can't_ be blocked (no checkbox)?  

Or just the choices we have now and your earlier comment:
> When all versions are/get selected, the "disable add-on" checkbox gets checked. When a version gets unselected, the "disable add-on" checkbox gets unchecked.

If so, should "disable add-on" be _always_ checked on page load?  What about if there are versions that are in other active submissions (e.g. delayed or requiring sign off)?  Is the javascript one-way? (i.e. selecting all the versions again won't re check the disable add-on checkbox)

**Comment by wagnerand** [comment]
After further conversation on Matrix, we concluded not to pursue this at this time and re-evaluate later.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-418
