### ISSUE TITLE
Allow the changed versions in a blocklistsubmission to be edited before publishing

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20902]
Currently you can only edit metadata (reason/url) for a blocklistsubmission, meaning if you want to change the versions the entire submission has to be rejected and recreated.  Being able to remove versions (guids?) from the submission would be easier for the staff user.

**Comment by AlexandraMoga** [comment]
@eviljeff I've verified this issue on -dev  by creating a blocksubmission which requires sign off. While the block is still pending for signoff, I am able to deselect versions that were initially selected as part of the block submission, but we don't have the option to add other versions to the block. The versions that were not selected at submission time will not be editable - i.e. they will be displayed with a green dot instead of a checkbox. 

[Example](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/690/change/)
![image](https://github.com/mozilla/addons-server/assets/31961530/c996a981-356f-438a-8145-6c637aee40ae)


Was this implementation intended only for versions removal?

**Comment by eviljeff** [comment]
> Was this implementation intended only for versions removal?

Yes.  Handling adding versions too was a little more difficult - it can be worked around by just creating a new submission if you want to block more versions.  (If admins do want this they can file an issue and we can see how it ranks among other feature requests)

**Comment by AlexandraMoga** [comment]
@eviljeff From https://github.com/mozilla/addons-server/issues/20922#issuecomment-1642173990

[after fix - Published blocks lists only the versions that were selected for blocking - [example](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/687/change/?_changelist_filters=signoff_state%3D4)]
![image](https://github.com/mozilla/addons-server/assets/31961530/708415f8-83ec-476f-8eb6-5bd270083db0)


[before fix - Published blocks also lists versions that haven't been selected for blocking (with a green dot)]
![image](https://github.com/mozilla/addons-server/assets/31961530/b8fb7d3b-5aef-4fd6-8cb6-737b7273bad9)

Was this change on purpose?

**Comment by eviljeff** [comment]
Ah, published submissions.  Yes, it was on purpose - the submission doesn't record the status of the other versions that _weren't_ changed - or if the versions have been blocked or unblocked by another action sine the submission was published - so it was potentially misleading to show them.  If the admin wants to see the current blocked status of the versions the Block itself (via the Edit Block link) is the place to see them

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-421
