### ISSUE TITLE
Empty reasons were removed from review page

### ISSUE THREAD

**Issue by iulianacse** [mozilla/addons-server#21030]
When sending a reject/delay rejection/reviewer reply it is mandatory to select a reason for it. Last week there were multiple empty reasons (Cloned add-on, Other, Other: security issue) that we that have been removed, but we as reviewers use and need them.

**Comment by eviljeff** [comment]
It was a deliberate change. Now blocklist reasons are using the same model there would I figured be cases where there would be reasons that aren't valid for blocklisting; and other that aren't valid for rejection. And as I assumed a blank canned response didn't make sense because we'd always want to justify our rejection somehow, the querysets in the reviewer and blocklist tools exclude reasons that are empty.

**Comment by eviljeff** [comment]
Easy fix is to just add some kind of text to all the reasons that should show up in the reviewer tools.  If that's not desirable then how the functionality _should_ work.  e.g. display all reasons always (could show and allow block specific reasons to be selected); add something to the model? etc

**Comment by eviljeff** [comment]
@wagnerand to make a call.

**Comment by wagnerand** [comment]
We are planning to add a canned response to each reason.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-464
