### ISSUE TITLE
A rejected version shouldn't be delay-rejected

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21047]
### Describe the problem and steps to reproduce it:

A version that has already been rejected by a reviewer (and is still rejected) should not be listed in the options for the action "Reject multiple versions".

STR:
1. Reject a version
2. Refresh the page, select "Reject multiple versions"

### What happened?

The rejected version was in the select list and thus can be rejected again.

### What did you expect to happen?

The rejected version is not in the select list.

### Anything else we should know?

@ioanarusiczki could you test and confirm this behavior, please?

**Comment by ioanarusiczki** [comment]
@wagnerand 

With an admin account: 

I could not reproduce it with versions from the Manual Review queue on -dev, because once I reject a version , Reject multiple versions is no longer present in actions.

I submitted 2 versions, rejected one of them -> went to Reject multiple versions -> I only find the one which should be displayed, the version already rejected is not present 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/626286#review-actions

On AMO stage another example: 
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/617465#review-actions

Refreshed page: the same , the reject multiple is no longer displayed.

**Comment by ioanarusiczki** [comment]
@wagnerand 

Was the version in the Manual Review queue for some reason and waiting for approval, or it's been approved before being rejected? Is it in a promoted group, recommended or notable? 

Is the reviewer an admin reviewer with permissions set such as the [AMO stage group](https://addons-internal.stage.mozaws.net/en-US/admin/models/access/group/50094/change/)?

**Comment by wagnerand** [comment]
> Was the version in the Manual Review queue for some reason and waiting for approval

It shouldn't have been waiting for approval, otherwise I think there should be an "Unreject" action logged between these two rejections.

> or it's been approved before being rejected?

It's been auto-approved, then approval confirmed, then I flagged it for review again (using "Set Needs Human Review), then it was instant-rejected and afterwards delay-rejected.

> Is it in a promoted group, recommended or notable?

It's notable now, and I believe it was at the time of rejection, but I'm not sure the promotional state matters here.

> Is the reviewer an admin reviewer with permissions set such as the [AMO stage group](https://addons-internal.stage.mozaws.net/en-US/admin/models/access/group/50094/change/)?

It's an admin reviewer with similar permissions, yes.

**Comment by wagnerand** [comment]
@ioanarusiczki Thank you. If we can't reproduce tomorrow, let's close this issue. Reviewers are aware of this issue and can comment/reopen if they have more information.

**Comment by ioanarusiczki** [comment]
@wagnerand 

I can't seem to reproduce it with Notable either 
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1004834#review-actions
Version 9.0 -> was auto-approved (wasn't notable yet), confirmed approval then the cron job ran and today it's notable again. 
I did not see it in the Manual Review Queue , I'm not sure why, probably because it's been confirmed for approval so I set the need human review flag and then rejected it. -> Reject Multiple Versions no longer displayed version 9.0 for rejection

**Comment by wagnerand** [comment]
@ioanarusiczki Thank you, I appreciate your efforts. Let's close this for now.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-467
