### ISSUE TITLE
Show all submissions instead of Pending sign-offs

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21064]
From https://addons-internal.stage.mozaws.net/en-US/admin/models/ click Blocklist submissions:
https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/ displays only Pending Sign-off state

Expected result:
It should show All

Note:
This is also reproducible after a new block is saved or updated (both actions are initiated from the review pages)

**Comment by wagnerand** [comment]
Displaying only pending sign-offs is the default. You can switch to all by selecting "All" in the right-hand side filter bar. The reason for that is because the pending ones are the ones that need action, where the full list is very long and we (almost) never start any action on a specific block from the full list.

**Comment by ioanarusiczki** [comment]
@wagnerand ok I understand, if that's expected I'll close the issue.

But while testing I was looking for the last blocked versions to check metadata or other things inside the block created,  and they're most of the time Published.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-471
