### ISSUE TITLE
Carousel does not rotate but jump back to start

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2120]
![amo-carousel-not-rotating](https://cloud.githubusercontent.com/assets/8145891/14186247/69ef6c24-f74b-11e5-8b5d-b9392d6cbb9c.gif)
It should not animate back to start after moving from the last to the duplicate of the last at the end of the row, but just jump instantly after the slide animation.

**Comment by muffinresearch** [comment]
We've not changed the carousel functionality afaik so this is unrelated to refresh changes. 

The carousel is quite flakey in general, sometimes it rewinds and sometimes is looks to be continuous. In addition click events should not be happening when it's animating because if you click the nav before animation is completed chaos ensues.

**Comment by designakt** [comment]
Hmm... Is there still something we could do to fix that without too much effort?

**Comment by andymckay-limited-access** [comment]
Hopefully we can just remove the carousel.
