### ISSUE TITLE
Version requirements after accidental uploads

### ISSUE THREAD

**Issue by madprops** [mozilla/addons-server#21259]
I accidentally uploaded a zip to another addon.  That addon has version for example 100. The intended addon has version 1.1. I removed that version through the page, but when I attempted to upload a new version (1.2) it says the version number must be greater than the previous (100).

I would expect since the version 100 upload doesn't exist anymore that the min version number should be lowered as expected.

As a workaround I uploaded it with version 101, which I will have to keep using I guess.

Wonder if that's the best way.

**Comment by diox** [comment]
Hi,

Sorry about this. It is the intended behavior, even if it's awkward in your case.

Version numbers have to be greater than the previous ones to ensure updates work properly. Even if you deleted it, that version still existed for a short while, could have been distributed, so in order to guarantee users would still update normally if they somehow got it, we don't allow version re-use and force you to upload a version with a greater version number.

Your workaround is correct.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-511
