### ISSUE TITLE
Bump add-ons for Android minimum compatibility to 120.0a1

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21293]
Just before Firefox for Android 119.0 is released (*), we need to bump Android minimum compatibility from `119.0a1` to `120.0a1` and migrate compatibility of existing add-ons, to avoid Android 119.0 users seeing those add-ons, as they should not be available on release yet (only Beta/Nightly).

(*) This will require a special push on October 23rd.

**Comment by ioanarusiczki** [comment]
@diox 

I tried the following:
- submissions on dev hub 
- submissions with the new api
- submissions with the signing api 
- some regression testing around scenarios from the [compatibility testing document](https://docs.google.com/document/d/1Fv_V-yBavijTLvztnYvrTrPo5LM9CsfAuKACnv6BeRA/edit).

Instead of 119.0a1 it's now 120.0a1, the error would be: 

`  "Invalid version range. For Firefox for Android, you may only pick a range that starts with version 120.0a1 or higher, or ends with lower than version 79.0a1."`

When the manifest has a strict_min lower than 120.0a1 AMO would silently set it to 120.0a1.

Forgot to check a few uploads for recommended/line, but I'm doing that tomorrow. 

Let me know if I should prepare anything for the migration.

**Comment by ioanarusiczki** [comment]
@diox 

I've noticed a change for recommeded versions and filed https://github.com/mozilla/addons-server/issues/21318

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-520
