### ISSUE TITLE
Rejecting unlisted auto-approved versions

### ISSUE THREAD

**Issue by iulianacse** [mozilla/addons-server#21308]
As a reviewer I should be able to send a delay rejection / rejection to an unlisted auto-approved version. 

Even though it doesn't change anything for the developer we will have the correct status recorded for each version.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-524)

**Comment by diox** [comment]
Discussed this yesterday, it's a little pointless because the actual action that matters is really blocking (https://github.com/mozilla/addons-server/issues/20498), not rejecting - as noted above, a rejection changes nothing for the developer but we will still have to notify them and give them the possibility of appeal, which if successful won't have any impact either.

So from an engineering perspective it's fine, this is really a product / developer experience impact. If @wagnerand you think that's fine then let's do it.

**Comment by wagnerand** [comment]
You are right it doesn't change much for the developer, it has a few upsides for operations. Leaving the reject-appeal scenario aside (which we need to discuss), do you see any downsides overall?

**Comment by diox** [comment]
As I said above I think this is mostly a problem in terms of developer experience, because it's just going to be confusing for them (especially if they receive another notification later about a block) and appealing that decision will make no sense. If that's fine then I don't have objections.

**Comment by wagnerand** [comment]
> ...it's just going to be confusing for them (especially if they receive another notification later about a block) and appealing that decision will make no sense...

That's fair but I don't believe it's unique to unlisted. The same thing could happen for listed as well, right? What is our strategy there?

**Comment by diox** [comment]
For listed at least rejection has an impact - it prevents the versions from being visible on AMO, can reverting that decision can be meaningful. I agree that if there is a block afterwards we're in the same position.

**Comment by wagnerand** [comment]
We discussed this internally with other teams including Legal and it was deemed ok. Handling appeals for progressive action needs to be dealt with (after the DSA launch) regardless, since it can also happen to listed versions.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-524
