### ISSUE TITLE
Due dates are not set properly

### ISSUE THREAD

**Issue by iulianacse** [mozilla/addons-server#21326]
We as reviewers noticed that some add-ons do not receive a proper due date. Multiple add-ons that were flagged for "Over growth threshold for usage tier"  received a wrong due date.

https://reviewers.addons.mozilla.org/en-US/reviewers/review-unlisted/872446 - Flagged for threshold on 12th of October, received deadline of 23rd of October, should've been 17th of October
same for: https://reviewers.addons.mozilla.org/en-US/reviewers/review/982502 
https://reviewers.addons.mozilla.org/en-US/reviewers/review/851547 - Flagged for threshold on 13th of October, received deadline of 23rd of October, should've been 18th of October
same for: https://reviewers.addons.mozilla.org/en-US/reviewers/review/2720226

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-531)

**Comment by diox** [comment]
This is on purpose.

Flags for human reviews are staggered to avoid putting too much pressure on the queue: We have a maximum number of add-ons allowed to be flagged for a given reason per day, so if we flag more at the same time their due date gets pushed further out.

Those 2 days (12th and 13th) happened to have more flags than the target, that's why the deadlines was set later on some of these.

/cc @wagnerand

**Comment by iulianacse** [comment]
What is the said limit for flagged for human review?

**Comment by diox** [comment]
The default if not set is 8 per day, but I don't know if it is set to a different value, I don't have access to prod, it requires admin access (For admins: the config name is `extra-review-target-per-day` and should be an integer).

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-531
