### ISSUE TITLE
Handle decisions from Cinder about extensions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21352]
In the webhook for Cinder (https://github.com/mozilla/addons-server/issues/21194) we need to handle decisions about extensions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-540)

**Comment by eviljeff** [comment]
bumping the milestone because 2023.11.23 is when #21408 will land, which adds the ability to have fully reversible add-on disables (unless I've missed some case); but #21376 adds support for executing the existing slightly flawed `addon_disable` so kinda works in 2023.11.09.

**Comment by eviljeff** [comment]
QA: there are some hidden changes with this issue that have impacts outside of cinder/dsa/abuse reporting.  Things that need testing:
- How developer disabling of versions is implemented has changed, so we need to test that developers can still enable and disable versions in devhub (and the api), and they can't enable a version they've not disable (i.e. a developer can't enable a rejected version, or a version that was disabled because it was made obsolete by a newer upload)
- Force disable action in reviewer tools should now be reversible. If you force enable after force disable the previously approved versions should change back to approved; any versions that were disabled (either because rejected or because developer disabled) should remain disabled.

It's likely easier to test the cinder handling with #21376 instead

**Comment by ioanarusiczki** [comment]
@eviljeff 

I verified on AMO Dev:

- disable/enable versions from dev hub

- disable/enable versions with api

- enable/disable for already disabled versions (by Mozilla - when rejected, blocked, force-disabled) cannot be done , the api would throw an error , from dev hub the disable can be used but it won't change the state of an already disabled version (from Disabled by Mozilla to Disabled by developer), and there's the delete action that would have an effect:

![disabled](https://github.com/mozilla/addons-server/assets/33448286/857933ab-4d30-466a-83ea-0a89b494c148)

- force-disable is making an "approved" or "awaiting review" state turn into "unreviewed" but once re-enabled the versions regain "approved" or "awaiting review" states
- when force-disabling an add-on, on the it's review page,  the action is registered in add-on history on the last version submitted (in case there are multiple versions). Force-enable is only mentioned in add-on important changes history

I think it looks good but I added these notes, maybe someone catches something that should be modified.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-540
