### ISSUE TITLE
Replace CinderReport with CinderJob

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21491]
Cinder consolidates multiple unresolved reports for the same entity under a single job, which will have a single decision_id.  Our current models have a `CinderReport` per `AbuseReport`, so we potentially have to update multiple `CinderReport`s for a single webhook request from Cinder, with the same information (and then try to perform the same action on a single entity).  This is inefficient and prone to complications if each CinderReport is handled seperately, when there is only a single decision (and enforcement action) taking place.

Instead, we should have a CinderJob model (many AbuseReport to a single CinderJob).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-584)

**Comment by eviljeff** [comment]
QA: This issue changes a core model of our Cinder integration, to reflect that cinder combines multiple abuse reports into a single "job", which is resolved with a decision. So, broadly:
- check that you can file multiple reports for the same content
- check that resolving that job (that contains the multiple reports) in cinder takes the action (e.g. disable the addon)
- check that the appeal form works with the new url (that now contains both the abuse report id and the decision id)
  - https://github.com/mozilla/addons-server/issues/21500 adds an email notification for the owner/target of a report with the appeal url in it
  - https://github.com/mozilla/addons-server/issues/21486 adds email notifications for all the reporters with unique appeal urls for each reporter in them.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I only tested multiple reports part for an add-on and noticed that these are gathered in Cinder when the same content is reported multiple times anonymously or by the same reporter (when user is authenticated) There's a reasoning section in Cinder without details yet 

![reasoning](https://github.com/mozilla/addons-server/assets/33448286/16479e0e-d30a-466e-8f21-14abec0ef8e2)

Let me know if I should file an issue. I think this should show what's the report's reason (what the reporter filed from AMO)

**Comment by eviljeff** [comment]
@ioanarusiczki `reasoning` should be there - it's the "details" text box.  If you wrote some text in the abuse reports there's a bug, so can you file an issue please.

**Comment by ioanarusiczki** [comment]
@eviljeff 

Re-tested this:

- I made consecutive reports on the same content, from 3 different browsers being authenticated or anonymous (it doesn't matter) and the reports are gathered in Reports tab under 1 job in Addon Content Infringement 

![from 3 different profile same pc](https://github.com/mozilla/addons-server/assets/33448286/8adfb767-5e38-4f1e-b28e-671d3765c386)

- the multiple reporting doesn't work on Addon Infringement queue when I made multiple reports for "violates add-on policies" " with Inside add-on" or "Both locations", only one shows up in the queue, if I wait for a while and report then I'll get individual jobs.  I don't really know how it should behave. 

- taking a decision would remove the reported content (except for "Ignore") and send e-mail for authenticated users or with name and email address. 
- reasoning is for details which are displayed in Cinder 
- I could access appeals - they're only available for the reported user, I even sent some and I've noticed them being available in the Content Infringement queue
- I'll comment on https://github.com/mozilla/addons-server/issues/21486 because I've noticed the reporter e-mails too

**Comment by eviljeff** [comment]
> the multiple reporting doesn't work on Addon Infringement queue when I made multiple reports for "violates add-on policies" " with Inside add-on" or "Both locations", only one shows up in the queue, if I wait for a while and report then I'll get individual jobs. I don't really know how it should behave.

Reports in different queues aren't de-duplicated.  But I'm not sure what "waiting for a while" is about... unless the report is processed in cinder in the meantime the timing shouldn't make any difference.  If you can reproduce can you file an issue with STR.

rest seems as expected.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-584
