### ISSUE TITLE
Unable to properly report (and therefore ban) a user that has lots of add-ons through Cinder

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21523]
Followup for 
https://github.com/mozilla/addons-server/issues/21513#issue-2014107172

Expected result: 

I sent from Cinder decisions using each policy available and it should ban a user (except for "Ignore") 

Actual result: 
User 10640485 is not banned. The user profile is still public.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-595)

**Comment by diox** [comment]
https://mozilla.sentry.io/issues/4680442274/?project=6224627 (3 of the 4 events are for that one - the 3 different reporting attempts made)

Cinder returned a 502 error when we reported the user, but the report actually still went through despite this. Because of the 502 AMO doesn't have the Cinder job id so we can't process any decisions made, since as far as AMO is concerned, Cinder never successfully recorded the report in the first place.

**Comment by diox** [comment]
It looks like we hit a timeout in Cinder or/and the Load Balancer in front of Cinder when reporting. We have increased the timeout on the LB side, but that might not be enough - Cinder folks are looking into this.

**Comment by ioanarusiczki** [comment]
@diox 

This is verified on -dev. 

User is banned , takes a little while until the user profile page throws a 404 but it should be fine. 
I filed https://github.com/mozilla/addons-server/issues/21659

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-595
