### ISSUE TITLE
Add EmailBlock instances based on downloaded CSV

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons-server#21536]
Logic for processing a CSV containing suppressed emails into EmailBlock instances.

<img width="965" alt="image" src="https://github.com/mozilla/addons-server/assets/19595165/3c3c1e0a-b3bf-444d-8bad-5c74925c807c">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-601)

```[tasklist]
### Tasks
- [x] Add code for parsing the CSV and upset EmailBlock instances
- [x] Add EmailBlock model to codebase
```

**Comment by KevinMind** [comment]
@diox we discussed how best to add an escape hatch to this flow (when socketlabs API is unavailable and we need to sync the suppression list manually) We discussed different approaches to address this so I think it's worth outlining here the options. For context, my investigation to socketlabs API has revealed some instability in uptime and a lot of strange error that could result in failures to download the file.

The way I see it there are 2 options:

1. add ability to provide a CSV file (like the one socketlabs provides) to our admin interface and run the flow as it is.
2. extract the part of the flow which is processing a single email to a task, and make this callable from admin.

2. is more of a deviation from the current plan, but could be better in terms of fault tolerance. We have a task per email and we could move the logic for processing the CSV either to the task downloading the file or to a separate middle step (for ultimate fault tolerance) I don't have a super strong opinion but I would lean towards option 1 as you can always upload a CSV with one email and you get the same behaviour. maybe more clunky from an operations perspective but it keeps the code simpler as everything operates on the same concept of a csv.

Thoughts? cc: @wagnerand

We could also agree to not cover this edge case for now. Happy to do that but the instability I faced so far was significant so I think it's very realistic we run into this issue soon after shipping.

**Comment by wagnerand** [comment]
I understand we are pulling the entire list in a CSV, is that correct? How often do we plan to do that? What was the fail ratio you saw in your local tests? Could that be some kind of rate limiting?

We could implement (1) but I am not sure if we are going to do that too often. It certainly does not scale as a recurring manual task from an effort and sustainability perspective. Are the API outages intermittent? If so, we could just retry the automatic task. If there are longer outages, do we expect we can still download the CSV from the website manually during the outage? Otherwise, is there a way to notify AMO or admins when either the API or manual download is working again?

I don't think there is much value in doing (2). I don't see us adding individual emails to the internal `EmailBlock`s. If anything, we'd rather do some bulk-adding, which sounds similar to (1).

(3) seems like an implementation detail to me, I am not sure I can give helpful feedback on the best approach there.

**Comment by ioanarusiczki** [comment]
@KevinMind In case you need qa to test for this issue please add some str.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-601
