### ISSUE TITLE
Implement what's missing for abuse report appeal process (for Cinder decisions)

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21575]
Base scenarios to test:
- [x] Content **not** taken down, reporter appeals, we confirm the decision. The content stays up, the reporter can no longer appeal.
- [x] Content **not** taken down, reporter appeals, we change the decision and disable. The content goes down, the author can appeal (the only time an appeal decision can be appealed)
  - [ ] From there, in that second appeal we can change the decision to approve or confirm the decision off the back of the reporter appeal and leave the content disabled. Neither the reporter nor the author can appeal that final decision.
- [x] Content taken down, author appeals, we change the decision and bring the content back up
- [x] Content taken down, author appeals, we confirm the decision
- [x] All scenarios above but with multiple reporters involved: all get the chance to appeal individually until an appeal decision takes place, but in Cinder that would be collapsed into a single job. When the decision is made they can no longer appeal.

In addition, we need to ensure emails to reporters and content authors are sent properly for those cases. https://github.com/mozilla/addons-server/issues/21558 notably should be investigated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-617)

**Comment by eviljeff** [comment]
Also, afaik, we still include the blurb and link about being able to appeal the decision on emails on the back of their own appeal (i.e. you can't re-appeal, but we say you can).

**Comment by ioanarusiczki** [comment]
@diox 

I think the scenarios above are working, I'll try to highlight a few parts:

At scenario 1,  e-mail is sent: the reporter is notified can no longer appeal

![finalemailscenario1](https://github.com/mozilla/addons-server/assets/33448286/a4b82edc-d97c-4729-9739-fd62182a4f66)

Scenario2 

content is reinstated 

![scenario2reinstate](https://github.com/mozilla/addons-server/assets/33448286/7312854c-c731-4442-b4d8-017dada95f27)

decision is confirmed 

![scenario2confirmsdecision](https://github.com/mozilla/addons-server/assets/33448286/a933cf97-2d18-4224-a3d2-e3848706d1cc)

These were emails that I did not see yet after appeals but now they're sent. 

I did not use "Revert decision" as I tried for https://github.com/mozilla/addons-server/issues/21558 For example, if  I wanted to disable content after an appeal made by the reporter when previously the decision/action was "Ignore", I clicked the Change policy and chose another action and submit. As a result content is taken down from AMO. 

No issues with scenario 3 or scenario 4. 

For multiple reports - they're gathered under one job and same happens when multiple reporters send appeals. 
All emails are sent individually to reporters., I did not see issues here. 

Maybe all users should be displayed somewhere , in this case I've only one id and 3 reports from 3 authenticated users

![multipleappeals](https://github.com/mozilla/addons-server/assets/33448286/84f7aedb-5551-4a05-8fdf-e37f7f99c4e2)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-617
