### ISSUE TITLE
Increase cache duration for services.a.m.o. API requests

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21628]
Currently, all `GET` non-authenticated API requests default to being cached by the CDN for 180 seconds (with some specific endpoints having a custom higher value). The value was chosen arbitrarily to keep data fresh while still providing enough caching to reduce infrastructure costs.

We'd like to increase that cache duration for API requests on `services.addons.mozilla.org` domain (and `services.addons-dev.allizom.org`, `services.addons-dev.allizom.org`), which serves requests for Firefox. That domain receives a lot of traffic but the freshness of the data for those requests doesn't seem as important.

The main impact would be that information that Firefox pulls from the API to show in about:addons (notably number of ratings, average score) would be slightly less up to date.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-634)

**Comment by diox** [comment]
Also, looking at our logs, some ideas about what Firefox could be doing to help:
- Possibly cache that data on the client-side more/longer
- When using the search API with a `guid`, sort the guids before sending them
- Avoid looking up langpacks, search engines, default theme when searching (anything that add-on manager doesn't need to show information coming from AMO)

**Comment by Rob--W** [comment]
What is the proposed cache duration?

**Comment by diox** [comment]
That is up for discussion :) We could iterate, but I'd like to get a sense of what your team is acceptable regardless.

**Comment by rpl** [comment]
Let's start by enumerating which are the endpoints we use and what data they provide, that may make it easier to evaluate what cases we have and if any of that would have different needs that we should account for to determine if what number would be acceptable, in the first pass I looked to the following query on searchfox: https://searchfox.org/mozilla-central/search?q=services.addons&path=

on that list I see the following:
- [pref("extensions.getAddons.get.url", ...)](https://searchfox.org/mozilla-central/source/browser/app/profile/firefox.js#41), used by AddonRepository to gather additional data from AMO about the extensions (we should be using it for a few additional details we show in the details view of the addon in about:addons, and checking for overrides to compatibility ranges if I'm not mistaken)
- [pref("extensions.getAddons.langpacks.url", ...)](https://searchfox.org/mozilla-central/source/browser/app/profile/firefox.js#44), I need to double-check this one but if I recall correctly this provides list of additonal downloadable langpacks used by about:preferences
- [pref("extensions.getAddons.discovery.api_url", ...)](https://searchfox.org/mozilla-central/source/browser/app/profile/firefox.js#45), this should be only be used for the discovery panel from what I recall, and so refresh it less often should not be that big of a deal (@Rob--W worked on that and may recall if there is any other use of it that I may not be recalling right now)
- [pref("extensions.getAddons.browserMappings.url", ...)](https://searchfox.org/mozilla-central/source/browser/app/profile/firefox.js#46), used by the extensions import mapping (e.g. to determine which amo addon id would match a chrome extension id), reducing refresh of this also seems reasonable, depending of how much we increase it we just want to write down that where we can find it back, so that we wouldn't be surprised if the mapping isn't refreshed right away and we may be wondering why
- the one used by CFRPageAction may be just retrieving addon details for an addon being suggested contextually, refreshing it less often shouldn't be that big of a deal, and honestly I'm not sure if that is currently enabled or if we disabled the experiment for now
- the two abuse reports one are going to be unused in more recent versions where the AMO hosted form is used

@Rob--W @willdurand feel free to augment this list with other I may have missed, or difference considerations I may have missed to mention, and other relevant details you may likely have on this topic

**Comment by diox** [comment]
I'm most interested in `extensions.getAddons.get.url` which hits our search endpoint. From what I can see in the logs, around half of the requests we see given an hour are requests we already saw during that same hour and could therefore mean that a one hour cache duration would halve the number of requests we handle (*)

(*) of course cache can expire on its own etc, so it's not exactly true, but it's a good enough estimation.

**Comment by Rob--W** [comment]
The uses of `extensions.getAddons.get.url` are:

- https://searchfox.org/mozilla-central/search?q=symbol:AddonRepository%23getAddonsByIDs&redirect=false
  - `installDictionariesForLanguage` https://searchfox.org/mozilla-central/rev/4d6a5b97428760d15bfcad13f8fc81439370a7ec/browser/components/preferences/dialogs/browserLanguages.js#675
    - This is triggered thrrough `about:preferences`, part of installing the relevant dictionary when a langpack is installed, for the feature from https://bugzilla.mozilla.org/show_bug.cgi?id=1469696 . I think that freshness is not very critical here.
  - `getMappedAddons` https://searchfox.org/mozilla-central/rev/4d6a5b97428760d15bfcad13f8fc81439370a7ec/toolkit/mozapps/extensions/internal/AddonRepository.sys.mjs#584
    - Triggered after looking up browser-mappings, part of browser import.
    - The worst that can happen is installing a slightly out-of-date add-on version and/or some out-of-date metadata (id, name, version, icons) - https://searchfox.org/mozilla-central/rev/4d6a5b97428760d15bfcad13f8fc81439370a7ec/toolkit/mozapps/extensions/AddonManager.sys.mjs#5395,5398,5417,5420
      - The add-on autoupdate check (once a day) should find updates if an older update is installed, so outdated info is probably not a big deal here.
  - `_getFullData` https://searchfox.org/mozilla-central/rev/4d6a5b97428760d15bfcad13f8fc81439370a7ec/toolkit/mozapps/extensions/internal/AddonRepository.sys.mjs#601
    - `cacheAddons` https://searchfox.org/mozilla-central/rev/4d6a5b97428760d15bfcad13f8fc81439370a7ec/toolkit/mozapps/extensions/internal/AddonRepository.sys.mjs#631
      - `AddonInstall`'s `loadManifest` https://searchfox.org/mozilla-central/rev/4d6a5b97428760d15bfcad13f8fc81439370a7ec/toolkit/mozapps/extensions/internal/XPIInstall.jsm#1655
        - It immediate next use is to get a fall back for the name if the extension manifest did not provide any. I don't consider this a useful scenario, as extensions should ideally not have an empty name.
        - [Other uses](https://searchfox.org/mozilla-central/search?q=symbol:%23_repositoryAddon&redirect=false) include looking up the replacement icon, full description, release notes, xpi location, review counts, etc.
    - `backgroundUpdateCheck` https://searchfox.org/mozilla-central/source/toolkit/mozapps/extensions/internal/AddonRepository.sys.mjs#690
      - Notable comment in caller of `backgroundUpdateCheck`: https://searchfox.org/mozilla-central/rev/4d6a5b97428760d15bfcad13f8fc81439370a7ec/toolkit/mozapps/extensions/AddonManager.sys.mjs#1301-1303

            // Repopulate repository cache first, to ensure compatibility overrides
            // are up to date before checking for addon updates.
            await lazy.AddonRepository.backgroundUpdateCheck();

**Comment by diox** [comment]
Consensus from discussion on Matrix is that we should be ok to increase the caching duration for `services.a.m.o.` to one hour. All the metadata Firefox fetches from AMO is optional / freshness is not critical.

**Comment by diox** [comment]
I keep discovering weird issues with `services.a.m.o.` ... My code landed but it looks like `SERVICES_DOMAIN` is wrongly configured. That setting and `SERVICES_URL` were apparently never used elsewhere anymore, so we never noticed.

**Comment by diox** [comment]
It's finally working on dev. 

An easy way to test the difference is to make `GET` API requests against `services.addons-dev.allizom.org` and `addons-dev.allizom.org` and compare the `cache-control` header in the responses: it should be `cache-control: max-age=3600` (caching in the CDN/Client for one hour) for `services`, and `cache-control: max-age=180` (caching in the CDN/Client for 3 minutes) otherwise.

**Comment by diox** [comment]
That's expected since those endpoints have custom cache durations already - we're only changing the default for endpoints that don't have a custom one set.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-634
