### ISSUE TITLE
Information about collection's items should be present in Cinder reports 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21638]
Followup for https://github.com/mozilla/addons-server/issues/21234#issuecomment-1845546170

Collection also need add-on metadata (the items list) as mentioned in the[ documentation](https://docs.google.com/document/d/1k1iyC1TMdyaTsOGlJLJpDyXr4l03O9bGemOSHrbKbnE/edit)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-637)

**Comment by eviljeff** [comment]
I think this was a deliberate choice by @diox ? (to avoid sending a lot of metadata for very large collections)

**Comment by diox** [comment]
Yes, and also because I feared this would be misleading, since the add-ons are not made by the collection author, they aren't responsible for them. If someone sees problematic content on a collection page that is coming from an add-on, they should report the add-on itself IMHO, not the collection.

Closing until we get pushback on this.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-637
