### ISSUE TITLE
Remove FxA -> Mxa banner in server

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21682]
The migration completed last year; it's time to remove the notifications about the rebranding.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-646)

**Comment by GregSherman** [comment]
commenting for assignment

**Comment by alexandruschek** [comment]
Hello,

I was able to verify this through fakemail in the admin section, since i couldn't get the delete e-mail in my inbox.
It's okay to have Firefox add-ons team or it should be: Mozilla add-ons team?
<img width="1392" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/1ac129a5-1092-4d53-83a1-9da6359abebf">
There is a reference to a banner too but I only know there's been a banner added on frontend - edit profie page - so if there is anything else I should be checking , let me know.

Thank you!

**Comment by eviljeff** [comment]
@alexandruschek my mistake, it's just the email on addons-server (frontend has the banner, like you said).  

I've never noticed the `Firefox Add-ons Team` sign off at the end of the email - it wasn't something we changed last year - but I think it should be Mozilla add-ons team like you suggested - can you file a quick follow-up for someone to update the signature (everywhere else we've always signed off with "Mozilla Add-ons team")

**Comment by alexandruschek** [comment]
Hello @eviljeff ,

I've submitted a follow-up regarding the sign off at the end of the mail.

We'll mark this issue as fix verified.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-646
