### ISSUE TITLE
Add management command to sync policies from cinder to AMO

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21747]
We need to get the policies from https://docs.cinder.co/reference/kosa_api_api_policies and fill the `CinderPolicy` model with all the policies returned.

a policy object is like
```json
{
    "id": 4,
    "name": "Harassment",
    ...
    "uuid": "f73ad527-54ed-430c-86ff-80e15e2a352b",
    "description": "We do not allow posts that appear to be shared for the purpose of diminishing, degrading or shaming others, causing them fear, or otherwise tormenting them.\n\n",
    "nested_policies": []
  },
```
`nested_policies` can contain other policies (and so on) - we want those too.  `CinderPolicy` doesn't support nesting currently, so needs a `parent` fk.

Ideally it would be implemented as a django management command that can be run on demand by SRE (and potentially linked up to a cron in the future)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-669)

**Comment by wagnerand** [comment]
Note that a `CinderPolicy` is linked (1:1) to a `ReviewActionReason`, which holds the `canned_response` for that reason and policy. So before sync, the existing _CinderPolicies_ must not be cleared and during sync, for items that already exist on AMO, the internal id of a `CinderPolicy` must not change, so that the existing link is not broken.

**Comment by KevinMind** [comment]
@Andreas Wagner can you clarify what does “cleared” mean and what does “internal id” mean? Is internal id the uuid as in the ticket description? And by cleared you mean:

given a policy with uuid ‘234’ already exists in our database

when we sync policies and encounter this policy based on the uuid 234

then we should have only 1 instance and the uuid for that instance should be unchanged. Also the relation between the policy and the review action reason should be unbroken

Can you clarify that is what you mean? And if not, could you help me understand?

**Comment by eviljeff** [comment]
(channelling my inner @wagnerand )
> @andreas Wagner can you clarify what does “cleared” mean 

deleted

> and what does “internal id” mean? Is internal id the uuid as in the ticket description? 
yes

> And by cleared you mean:
> given a policy with uuid ‘234’ already exists in our database
> when we sync policies and encounter this policy based on the uuid 234
> then we should have only 1 instance and the uuid for that instance should be unchanged. Also the relation between the policy and the review action reason should be unbroken

yes.  (uuid should be `unique=True` if it's not already).

**Comment by wagnerand** [comment]
> given a policy with uuid ‘234’ already exists in our database
> when we sync policies and encounter this policy based on the uuid 234
> hen we should have only 1 instance and the uuid for that instance should be unchanged.

I am not sure about that. What if someone changes the name or description of an existing policy?

**Comment by KevinMind** [comment]
Isn't that consistent with the acceptance criteria I gave? Id don't understand the confusion. In the case you described @wagnerand 

Before: we get a policy for the first time that looks like this.

{
uuid: '234',
name: 'Foo',
description: 'Foo is bad. Do not foo.'
}

We create a record with id "1" containing this data.

After: on the next sync we get the same object with the same uuid but the name/description have changed.

{
uuid: '234',
name: 'Bar',
description: 'Bar is bad. Do not bar.'
}

What should happen here? cinder is giving us a record with the same UUID as one we have already seen, so given my current understanding we should find our existing record based on the given uuid 234, which returns record 1 and we will update the name and description with whatever we get from cinder.

Name and description can change uuid cannot. That is how I am understanding this. Otherwise I still don't understand what you mean by "the internal of a CinderPolicy must not change".

**Comment by wagnerand** [comment]
@KevinMind please see my updated comment above.

**Comment by eviljeff** [comment]
@KevinMind QA won't be able to run this themselves, but if you can run it in an addons-dev k8s pod it can be verified by QA by:
- looking in https://stage.cinder.nonprod.webservices.mozgcp.net/policies
- comparing to the policies listed in django admin, as CinderPolicy instances

**Comment by KevinMind** [comment]
👍 Should I do that as part of this task? I guess I will have to wait for whoever will QA this. I'll remove the label then so we can test it.

**Comment by KevinMind** [comment]
Let's see if removing the label is picked up by the sync 🎲

**Comment by eviljeff** [comment]
> 👍 Should I do that as part of this task? I guess I will have to wait for whoever will QA this. I'll remove the label then so we can test it.

You (or someone else on engineering, or SRE) will need to run the command.  It's usually better to have QA verify that the changes actually worked as expected in django admin though, if possible.

**Comment by ioanarusiczki** [comment]
@KevinMind 

I've noticed in dev admin a [ciderpolicy model](https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/cinderpolicy/) currently there's no content. But it's possible that you didn't run the command yet so let me know when to check this.

**Comment by KevinMind** [comment]
@ioanarusiczki I will run the command tomorrow morning and ping you when it is done.

**Comment by KevinMind** [comment]
@ioanarusiczki I've run the command on dev.

**Comment by ioanarusiczki** [comment]
@KevinMind 

Yes, I see them in [cinderpolicy](https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/cinderpolicy/) 

It's the policies + their nested policies (as it's displayed in [Cinder](https://stage.cinder.nonprod.webservices.mozgcp.net/policies?policyFilters=%7B%7D)). UUID , Name and Text fields could be edited in admin. 

 "Parent policy for tests" has also been imported together with 6 nested policies that begin with "Testing-" but it should be expected.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-669
