### ISSUE TITLE
mobile AMO is not style refreshed

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2178]
currently still reflects the old AMO style:
![screen shot 2016-04-04 at 18 25 12](https://cloud.githubusercontent.com/assets/8145891/14255039/992e1388-fa92-11e5-8967-ace5810379a0.png)

**Comment by designakt** [comment]
@andymckay do we have numbers on mobile to judge if it is worth restyling?

**Comment by andymckay** [comment]
That's quite a lot of work. As in a lot, because all the templates are completely different and the CSS is different. I knew this wasn't going to happen in this release and ok'd that but probably didn't tell you.

Unless its a big concern to you I suggest we shelve this.

It's imperative to us that all future work is responsive to avoid this in the future. But at the moment this is a pile of technical debt we shouldn't worry about I think.

**Comment by tofumatt** [comment]
I agree, I don't think this is worth the effort when we have a plan to redo a lot of AMO in the not-so-immediate-but-somewhat-near future (eg I'm guessing within a year).

I don't think doing a mobile version is worth it; we should just focus on making sure the new version is responsive and works for all platforms, whatever that entails.

**Comment by designakt** [comment]
I agree with you! I do not think it is worth the effort as I think we do not have a lot of mobile visitors.
But I was hoping for some numbers to prove that feeling we have of it not being worth the effort.
Do we have numbers on how many % of visitors visit via mobile. And how many & of installs come from mobile? (I sort of expect visits to be low and installs to be even lower... am I right?)

**Comment by andymckay-limited-access** [comment]
Do you have access to google analytics?

**Comment by designakt** [comment]
I do not.

**Comment by muffinresearch** [comment]
So I'm going to close this on the basis we're not planning to fix this as part of the refresh scope.
