### ISSUE TITLE
Cinder moderator escalation reasoning text should be accessible to reviewers

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#21899]
### Describe the problem and steps to reproduce it:
If a cinder moderator escalates a case to AMO, the reasoning text should be displayed to the reviewer for them to be able to make a decision on the case.

### What happened?
Currently we're showing generic text "Escalated for an abuse report, via cinder" for cinder escalation cases without any context for the reviewers into what could the reason for the escalation be.

### What did you expect to happen?
The escalation accompanies the reasoning provided by cinder moderator so that a reviewer has the necessary context to handle the case

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-725)

**Comment by diox** [comment]
In terms of implementation, this will require a little refactoring, because:
- `NeedsHumanReview` automatic activity log is created with `details={'comments': self.get_reason_display()}` and no way to override that
  - We could find a way to pass that, or disable the automatic activity log, creating our own
- `CinderActionEscalateAddon.process_action()` doesn't receive the reasoning (though I guess we have it in the webhook initially)

**Comment by eviljeff** [comment]
Would the moderator escalation reasoning be in `payload->notes`?  If so, we store that as `CinderJob.decision_notes` in `process_decision`, so could expose it from there.  (Though we should arguably log in it in the activity log too because `decision_notes` could get overwritten with a subsequent decision on the same job)

**Comment by diox** [comment]
Ah yeah forgot about that, it should be sent for any action so that so that sounds like a good place to start. Agreed ideally that should be somehow attached to the activity log.

**Comment by ioanarusiczki** [comment]
@eviljeff 

There's a text field ("Notes" I think) where a moderator can write the reason for escalation. 

A report escalated 

![Reasoning sent](https://github.com/mozilla/addons-server/assets/33448286/a589006e-4ad2-480f-b285-265c9035635c)

An appeal escalated 

![appeal reasoning](https://github.com/mozilla/addons-server/assets/33448286/461cde60-f4d6-43b8-8008-6c96f8de0f1b)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-725
