### ISSUE TITLE
Consider re-signing add-ons in nonprod envs (-dev/stage)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#22021]
Once https://github.com/mozilla/addons-server/issues/22016 is fixed, we should consider re-signing the add-ons in nonprod envs (-dev and stage) since (1) Autograph will sign newly submitted versions with the new certificate, and (2) Firefox will also be updated with this new certificate ([Bug 1885349](https://bugzilla.mozilla.org/show_bug.cgi?id=1885349)).

This is not necessarily a high-priority issue but OTOH we might want to get the add-ons re-signed to avoid debugging install problems in 6+ months (when we'll have forgotten about this staging certificate update...).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-764)

**Comment by diox** [comment]
cc @vcarciu @ioanarusiczki

**Comment by alexandruschek** [comment]
Hello @diox ,

These are preferences that are used for dev and stage in auto:
extensions.install.requireBuiltInCerts : False
xpinstall.signatures.required : False
xpinstall.signatures.dev-root: True
extensions.webapi.testing: True
ui.popup.disable_autohide: True
devtools.console.stdout.content: True
extensions.getAddons.discovery.api_url: https://services.addons.allizom.org/api/v4/discovery/?lang=%LOCALE%&edition=%DISTRIBUTION%
extensions.getAddons.get.url: https://services.addons.allizom.org/api/v4/addons/search/?guid=%IDS%&lang=%LOCALE%
extensions.update.url: 
- STAGE:  https://versioncheck.allizom.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=%APP_LOCALE%&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%
- DEV: https://versioncheck-dev.allizom.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=%APP_LOCALE%&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%

I'm having trouble on both stage and dev, with installing addons/themes from about:addons page(probably because of the current problem):
![image](https://github.com/mozilla/addons-server/assets/139126091/b38251b0-16d4-48e4-9e13-080a45c25177)

Examples of addons/ themes used for dev in installs:
Theme: full-moon-kitty
Addons: aarafow-molla-mantinch

for STAGE:
Theme: japanese-tattoo
Addons: stealthy, ghostery

**Comment by diox** [comment]
Ok. Do you use _any_ existing ones or _specific_ existing ones ? And do you just install the latest version or do you try installing older versions as well ? If it's only a handful and you just care about the latest version, we could upload new versions.

**Comment by willdurand** [comment]
> xpinstall.signatures.required : False

This should usually be set to `true`. When set to `false`, signing is by-passed, which doesn't sound to great when verifying bugs about signing...

**Comment by ioanarusiczki** [comment]
We can make new submissions and replace the existing data for AMO installs. 

I try to figure out something in addon manager though. I'm still on it.

**Comment by willdurand** [comment]
Please make sure to have enough add-ons signed with the new cert in -dev (and soon stage), e.g. for all kind of add-on types, different badges, etc. because all these add-ons (and versions) will be useful when we'll have to verify the root succession plan.

**Comment by diox** [comment]
Closing as we've agreed **not** to automatically resign existing dev/stage add-ons with the `cas_cur` cert. These will break, so QA will need to replace add-ons they test with "manually".

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-764
