### ISSUE TITLE
Report non-abuse-report related reviewer tools decisions to cinder

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#22077]
Final part of https://mozilla-hub.atlassian.net/browse/AMO-116

Following on from https://github.com/mozilla/addons-server/issues/22049 and https://github.com/mozilla/addons-server/issues/21990 now we want to be able to report every reviewer decision to cinder; send DSA compliant emails; and offer an appeal on negative decisions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-782)

**Comment by eviljeff** [comment]
QA: this patch (and the previous supporting issues) enables two significant changes:
- DSA compliant emails are sent for reviewer tool actions, even when cinderjobs are not being resolved.
  - All existing reviewer emails have been replaced.  The dsa style emails are knowingly different, and some things are no longer included (e.g. tested by fields), but if something important is missing please call it out and file follow-ups.
  - emails should state the review was carried out on our own initiative in the text
- Decisions which take down add-on content (i.e. rejecting versions and disabling add-ons) are notified to Cinder.
  - approvals which aren't connected to a cinder job (i.e. abuse report related, or an appeal) don't get notified (we auto approve _a lot_ of versions and that's not useful data to send to cinder)
  - decisions can't be associated with a queue in cinder, so are only shown via the entity investigation view
- The third bonus change is rejection/disable decisions that weren't on the back of abuse reports can now be appealed via the same process as takedowns that originated from reporters.

The QA priority is item 1 - emails - because the reviewer tools must continue to work for non-abuse report related reviews.  (But obviously the other changes should work too)

**Comment by ioanarusiczki** [comment]
I started checking email , only covered approvals for now. 
https://docs.google.com/document/d/1Hhr6kW02JtV1Dn1wkIwCyAieQYenv0COE1_I0LfxFX4/edit?usp=sharing

**Comment by ioanarusiczki** [comment]
Question:
what's " entity investigation view", should I see it by now in Cinder?

I verified Emails for: 

**Approvals**  

For unlisted versions I've noticed https://github.com/mozilla/addons/issues/1739 , "it is now available at " should point to dev hub. 
If that could be updated for all e-mails sent , should be ok. 

![approvals for unlisted](https://github.com/mozilla/addons-server/assets/33448286/e53c0b65-818f-4286-914a-991a44ae9b33)


**Rejections**

Seem to have the format of a reported extension with an appeal number available, did not try to appeal yet to see what happens. 

![rejected on dev](https://github.com/mozilla/addons-server/assets/33448286/b9b17280-c3df-4d37-8507-feecd5628467)

**Force disable**
 Emails are almost identical to the rejected format , excluding  "Affected versions". 

![forcedisable](https://github.com/mozilla/addons-server/assets/33448286/8de2ec3e-56d2-4f9f-af5e-6f9e8707deb5)

**Delayed rejections** 
First email  was sent after the new format, I'm waiting to see a followup + the final email when the delay expires.

**Blocking**

I've noticed an email is sent immediately after the block from admin, yet it seems to be a problem, if I'm adding a blocking reason, the email is not sent. -> I'll file an issue.

![blocklisted](https://github.com/mozilla/addons-server/assets/33448286/bb4264e7-10cf-4b40-a8a0-a759aafb6b25)


I didn't get emails after blocking versions on -stage. But I don't know how it worked before, yet it could be a bug.

For all actions, looking on stage old e-mails had a footer with lots of links and information about subscriptions but I assume this goes away with the new format. 

I've still to:

Try to appeal for rejection/disable decisions, and it looks like blocking too.
Check on some reported extensions too so nothing's broken there.

**Comment by ioanarusiczki** [comment]
I've sent appeals and noticed that they show up in the DSA section like this:

![after sending appeals](https://github.com/mozilla/addons-server/assets/33448286/c263eb77-e8c6-43e7-90cc-b4f8f5749ed4)

Also I can see they're in Cinder too in [AMO dev addon infringement](https://stage.cinder.nonprod.webservices.mozgcp.net/queues/UXVldWVUeXBlOjI1/details)

I tested with abuse reports for extensions and themes reported for add-on policies, escalated to AMO or resolved from Cinder and I didn't see new issues.

**Comment by eviljeff** [comment]
@ioanarusiczki 
> what's " entity investigation view", should I see it by now in Cinder?
e.g. https://stage.cinder.nonprod.webservices.mozgcp.net/investigate/amo_addon/630523?tab=decisions
which, via a very tiny icon, links to a decision like https://stage.cinder.nonprod.webservices.mozgcp.net/decision/f1a99a4f-cf50-4b02-972f-e1ca02f25951

**Comment by ioanarusiczki** [comment]
I couldn't find the emails sent for delay rejections so I set up new rejections. For some reason on -dev I didn't get real emails, but I've seen the first one sent on[ fakemail](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/122840/change/).

**Comment by ioanarusiczki** [comment]
So emails have been verified. 

What I am not sure about is https://github.com/mozilla/addons-server/issues/22077#issuecomment-2056721076 

I rejected a version https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1025855 and the email was sent to [the developer](https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/154839/change/). 

With `f9b3ddfb-d84d-42eb-a364-ded0f5b6e9c7` I  tried to see https://stage.cinder.nonprod.webservices.mozgcp.net/decision/f9b3ddfb-d84d-42eb-a364-ded0f5b6e9c7 but it's "Decision not found"

![cannot see decision](https://github.com/mozilla/addons-server/assets/33448286/2dc756ba-3dd8-4cdc-84bd-ec62a5d8c911)

I've also permission denied on https://stage.cinder.nonprod.webservices.mozgcp.net/investigate

I sent the appeal too and as I see it as in the[ screenshot above](https://github.com/mozilla/addons-server/issues/22077#issuecomment-2051848194).  -> maybe UI is going to change about that adding more details

Tried the following: 

A version is rejected. Then ,with a new version submitted by the developer and approved + the appeal checked I got [this email ](https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/154843/change/) and I don't think the first part is correct because it wasn't reported for policies. 

A version is force disabled. Appeal sent by the developer. Addon is force-enabled , [this email is sent](https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/154847/change/).

Version stays rejected/disabled. If I check the appeal + clear needs human review I get[ an email](https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/154849/change/) that the extension has been restored which is incorrect.  

Let me know if you need followups or it's already known issues so I can mark this verified.

**Comment by eviljeff** [comment]
@ioanarusiczki can you file followups for:

> A version is rejected. Then ,with a new version submitted by the developer and approved + the appeal checked I got [this email ](https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/154843/change/)and I don't think the first part is correct because it wasn't reported for policies.

the wording isn't great in the first part, but also the following part where is says the previous decision was incorrect isn't necessarily true either - we could have been correct in our decision but they fixed something in a new version

> Version stays rejected/disabled. If I check the appeal + clear needs human review I get[ an email](https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/154849/change/) that the extension has been restored which is incorrect.

The email for this is wrong (because clear needs human review, counter-intuitively for appeals, is linked to approving content instead)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-782
