### ISSUE TITLE
Disco Pane programming module won't display a specific collection

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#2222]
We set programming for the AMO Disco Pane here: https://addons.mozilla.org/en-US/firefox/discovery/modules ... and we currently have the "Starter Pack" collection  -- https://addons.mozilla.org/en-US/firefox/collections/mozilla/starter/
 -- set to display, yet it does not display on the AMO Homepage. This is the only collection where I've encountered this issue.

**Comment by krupa** [comment]
My guess is that we usually show 4 things on the carousel at any given time and since Disco Pane has the 'New To Add-ons' panel in addition, the 4th panel is skipped.

This is complete guesswork on my part.

**Comment by devaneymoz** [comment]
Thanks, Krupa, but I don't think so. I tried numerous carousel combinations (including just two or three total items along with Starter Pack) and everything always shows except the Starter Pack. It's a modern tech mystery!

**Comment by andymckay** [comment]
Mat, could you take a look please?

**Comment by diox** [comment]
I don't have access in prod, but I guess this is because the "Starter Pack" discovery module is tied to a specific collection id that does not exist any more - Some of the discovery modules hardcode a specific collection id to load, some hardcode a specific collection slug + author name (generally "mozilla"), and "Starter Pack" does the former. 

I'll verify that I'm right in the morning and if I am, submit a patch to make that module use the "starter" slug, which should fix your issue.

Note that this is why it'd be nice to know which old modules we can remove in #2210, to clean up the remaining ones.

**Comment by devaneymoz** [comment]
Thanks, Mat. And with regard to #2210 I'm on that one. Should have a list of collections we can prune very soon.

**Comment by diox** [comment]
Alright, actually, it turns out everything is fine. The collection is loaded by its id, and it does exist on dev and prod... What's happening is [we have some javascript code to hide this specific promo (!) if the user has been on AMO a few times already](https://github.com/mozilla/addons-server/blob/682202ca9cb63f8167fe6944ed270a39845a08ac/static/js/impala/homepage.js#L34).

You can see the promo if you have been on the AMO homepage less than 5 times (there is no expiration, so it you saw it 5 times in the past 4 years, you're done). To see it again, open your developer tools console and do:
```
localStorage.removeItem('visitor-amo_home_promo_seen')
```
Then reload the page.

Not sure how to proceed from there. I could remove this code and always show it. Or tweak it ? You tell me.

**Comment by devaneymoz** [comment]
Ahhhh! Okay. Thanks for the investigative work, Mat! I was unaware of this feature specific to the Starter Pack collection (a very cool feature I would note). I don't think anything else needs to be done here.
