### ISSUE TITLE
Duplicate add-on ID found; failed validation

### ISSUE THREAD

**Issue by cjshawMIT** [mozilla/addons-server#2324]
Hi all, we have 3 add-ons that we want to sign, all unlisted in AMO (we distribute on our own site). We have one add-on per server that we support: -dev, -demo, and -production. I was able to upload and get preliminary validation for the -dev version of the add-on. However, when I try to upload the -demo and -production versions, I get an error:

```
    Your add-on failed validation with 1 error.
        Duplicate add-on ID found.
```

I've checked the `install.rdf` file inside of the .xpi packages, and the -demo and -production names differ from the "Name" field shown on my approved add-on page. The approved add-on is [here](https://addons.mozilla.org/en-US/developers/addon/mc3-dev/). My "submissions" page only shows a single approved package, so it's not clear to me if someone else already owns the same add-on names (they don't show up when I try https://addons.mozilla.org/en-US/developers/addon/X), or if there is another issue.

Can you help me troubleshoot this? What info can I provide, or how else can I troubleshoot it myself?

**Comment by wagnerand** [comment]
The error message is mentioning the ID, not the name. Please go to your developer hub, select the add-on you already uploaded, click _Manage Status and Versions_ and click _Add new version_.

**Comment by cjshawMIT** [comment]
@wagnerand thanks for the response. I'm unclear about the process here, apologies -- I'm not trying to upload a new version (i.e. 1.0.7), rather I'm trying to upload essentially a different add-on with a different internal configuration (that talks to our production server instead of our development server). If I click _Add new version_, doesn't that mean I want to create a 1.0.7 of the same "development" add-on?

**Comment by cjshawMIT** [comment]
Sorry, just a follow-on thought. I'm very new to add-on development -- another way to frame what I understood from your suggestion is: we should only have one version of our add-on (production), and when we want to test against our development server, 1) we bump the version / upload a development .xpi to the same (production) add-on, 2) test it, 3) create a production flavor, then 4) upload it back to the same add-on? Thanks for the education and info.

**Comment by wagnerand** [comment]
What you tried to do is upload a new add-on when there was already an add-on with that ID. As the ID must be unique, the submission aborted.
There are two options here
1. Make the add-on ID unique for each of your add-ons. If you serve updates to users using the `updateURL` tag in `install.rdf`, it might be complicated to get the right file shipped to the right users.
1. Upload a new version (=changed file, different version number) for the already existing add-on. Therefore, you don't need to change the add-on ID and can ship updates to existing users. Caveat: Make sure that the version number is always increasing for each version of your add-on, otherwise Firefox won't recognize this as an "update".

**Comment by cjshawMIT** [comment]
@wagnerand got it, thanks! I was using the Kango framework and assuming it would assign a new ID every time I built the app, but bad assumption.
