### ISSUE TITLE
Modify the opacity for unsupported Complete Themes

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2364]
Relates to #2355 

Steps to reproduce:
1. Go to Themes->Complete Themes page in AMO-stage https://addons.allizom.org/en-US/firefox/complete-themes/
2. Observe the incompatibles complete themes i.e. FT DeepDark 

Expected results:
It should be grey out, like add-ons are.

Actual results:
There look available.

Notes/Issues:
Verified on AMO-stage FF45(Win 7). Issue is reproducing on AMO-dev, stage and prod.
Screenshot for this issue: 
![2016-04-14_1238](https://cloud.githubusercontent.com/assets/15685960/14523765/0c2aec32-023e-11e6-947d-c577dd63db09.png)

**Comment by muffinresearch** [comment]
Looking at the old styles we didn't used to do that, but it would be nice for consistency and more visual immediacy.

**Comment by ValentinaPC** [comment]
We used to do that :smile: 
Please see the screenshot: 
![2016-04-14_1247](https://cloud.githubusercontent.com/assets/15685960/14524030/231a9f72-023f-11e6-8e83-f75db140aba0.png)

**Comment by muffinresearch** [comment]
> We used to do that :smile:

Ah ok I stand corrected . Removing the restyle CSS wasn't enough to bring that back. I wonder if the markup or js has changed?

@tofumatt I wonder also if it would be tricky revert the waffle removal since seeing the old site is pretty difficult and clearly removing the restyle css isn't enough as demonstrated here. I'm constantly finding I want to reference the old site design.

**Comment by tofumatt** [comment]
We could bring the waffle flag back if you like, yeah. I’d probably make it an “oldstyle” flag, as the redesign should be the default. But we could do it if it was really useful.

I liked the idea of ditching the code. You could always just check out an old tag/version, but if that’s more of a pain we could explore re-implementing the waffle bit.

**Comment by muffinresearch** [comment]
Checking out old code works up to a point but gets problematic as soon as there's migrations in the way. Also it makes it painful re: fixing something and having a checkout pointing back to historical code.

I guess the lesson learned here is that if we ever do this kind of thing again we should leave a waffle in place longer since it doesn't do any real harm and then only remove it once we're clear of the feature landing by several weeks since it's a good + quick way to know if a waffled feature is causing a regression or not.

**Comment by tofumatt** [comment]
Agreed, we went too fast on removing that code; it really wasn’t hurting much.
