### ISSUE TITLE
Preliminary addons cannot be made public.

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2388]
We are seeing this traceback:

olympia.editors.helpers in process_public
AssertionError: Preliminary addons cannot be made public.

Which is possibly due to the changes made in https://github.com/mozilla/addons/issues/68. It seems like some add-ons are failing to be signed.

**Comment by andymckay** [comment]
Lets' revert the changes in https://github.com/mozilla/addons/issues/68.

**Comment by diox** [comment]
This affects unlisted add-ons that were in preliminary reviewed or awaiting preliminary review state and uploaded a new version since the latest push where #2276 was introduced. I missed that case, and because all this code modifies the statuses directly the add-on ends up in an incoherent state and the reviewers helpers code refuses to modify the version status at upload time.

https://sentry.prod.mozaws.net/operations/olympia-prod/group/324821/
https://sentry.prod.mozaws.net/operations/olympia-prod/group/324837/

The faulty commit will be reverted.

**Comment by retorquere** [comment]
Any ETA on this revert being operational?

**Comment by diox** [comment]
This will go in prod later today. I'll update this bug when it does.

**Comment by andymckay** [comment]
This has gone into prod.

**Comment by AlexandraMoga** [comment]
This doesn't apply anymore since post review was introduced.
