### ISSUE TITLE
User is still able to log in after they deletes their AMO account

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2451]
**Steps to reproduce:**
1. From account settings page click on the delete account button or load this page: https://addons.allizom.org/en-US/firefox/users/delete
2. Observe the message displayed in the banner: " You will not be able to log into addons.allizom.org anymore. ", enter your email address and click the Delete my user account now button.

**Expected results:**
The user is deleted and not able to log in again using the same email address.

**Actual results:**
The message that the profile is deleted is displayed but the user is still able to log in using that email address.

**Notes/Issues:**
Verified in FF45(Win7) Issue can be reproduced in amo-dev, stage and prod.
Screencast for this Issue:
![userdelete](https://cloud.githubusercontent.com/assets/15685441/14677053/98c19f5e-0718-11e6-84aa-42b411e4902f.gif)

**Comment by mstriemer** [comment]
I tried this on -dev and it is actually creating a new account. It's never actually been the case that "you can no longer login" since you could register again but this makes it appear as though you are logging in.

We could update the copy and maybe reorder it so that it more accurately describes what will happen.

* Your reviews and comments will not be deleted but they will no longer be associated to you.
* Logging in with this email address again will create a new account that is in no way associated with this account.

**Comment by madalincm** [comment]
Verified as fixed in FF58(Win7) in amo-dev
The text now is clearly stating what happens after the user logs in with the deleted account:
![deleteaccount](https://user-images.githubusercontent.com/15685441/35616825-10c3a4c2-067f-11e8-80da-dca0d433f1ed.png)

Marking bug as verified fixed.
