### ISSUE TITLE
Tooltip text not correctly aligned after pressing Edit in Edit listing section

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2467]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to edit listing page for an addon (https://addons.allizom.org/en-US/developers/addon/6april/edit)
2.Observe the tooltips before pressing Edit button for a section
3.Press Edit button for a section(eg. Techincal Details)
4.Observe the tooltips again

Expected results:
Tooltips are corectly aligned

Actual results:
Tooltips not aligned

NOTE:Not reproducible on prod

Please see video for this issue : 
![tooltip](https://cloud.githubusercontent.com/assets/1583842/14712250/07e6b8de-07e5-11e6-8bcb-20c2888617c4.gif)

**Comment by eviljeff** [comment]
There are two issues at play here
1. the tooltip rendered after the editable content has been loaded isn't a jqueryui one, so extra whitespace isn't stripped.
2. the tooltip text is being extracted and localised with extra whitespace that doesn't exist in the [template](https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/addons/edit/technical.html#L22)

So the issue can either be fixed by 
1. changing the [javascript](https://github.com/mozilla/addons-server/blob/master/static/js/zamboni/devhub.js#L389) or
2. fixing <whatever is faulty with the extraction/rendering process>
or 
3. maybe stripping out the whitespace out in the [tip macro](https://github.com/mozilla/addons-server/blob/master/src/olympia/templates/includes/forms.html#L55)?

**Comment by wagnerand** [comment]
>  2. fixing << whatever is faulty with the extraction/rendering process >>

https://github.com/mozilla/addons-server/pull/2838 should take are of that.

We should still make this a jQuery tooltip, I guess...leaving this open to remind myself.

**Comment by wagnerand** [comment]
Note for QA:
Make sure the tooltip is styled not only in edit-mode, but also after clicking "Cancel"  or "Save Changes".
