### ISSUE TITLE
Browser crashes after installing a language pack

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2520]
**Steps to reproduce:**
1. Open: https://addons.allizom.org/en-US/firefox/addon/english-us-language-pack/ and install the language pack.
2. Restart the browser.

**Expected results:**
The language pack is successfully installed.

**Actual results**:
The browser crashes.

**Notes/Issues:**
We observed different crashes after installing this language pack:
Browser crash: 
![profilecrash](https://cloud.githubusercontent.com/assets/15685441/14859931/f82716e0-0cae-11e6-9df3-4fccceac6048.png)
Crash in about:addons : 
![aboutaddonscrash](https://cloud.githubusercontent.com/assets/15685441/14860305/e5cdf26e-0cb0-11e6-918b-af866d04bd4a.png)
Crash in about:config:
![aboutconfig_crash](https://cloud.githubusercontent.com/assets/15685441/14860312/ed3541c4-0cb0-11e6-92a4-d4210e994124.png)

At this moment we can't no longer install that language pack on a clean profile. The error message that we receive is that the addons is incompatible with FF46

**Comment by muffinresearch** [comment]
Looks like the downloaded addon is only compatible up to 45, but the version was bumped on amo:

<img src="https://cloud.githubusercontent.com/assets/1514/14860873/adad1e72-0ca2-11e6-899d-8053c7e5343a.png">

**Comment by andymckay** [comment]
This is pretty terrible and after some investigation is apparently because the language pack is not compatible with that version of Firefox. If that's the case this kind of error can occur. There's a patch in progress to fix up that particular language pack: https://bugzilla.mozilla.org/show_bug.cgi?id=1267847 so that it works for Firefox 46.

This isn't really an AMO problem, but a general language pack design problem that they can do so much damage. We should probably file a bug for that in bugzilla, although there's probably one already somewhere.

**Comment by ValentinaPC** [comment]
This is happening on on Firefox 46 too, after successfully installing https://addons.allizom.org/en-US/firefox/addon/english-us-language-pack/ the browser crashes. 

I know it isn't an AMO issue, but someone should fix this as soon as possible (from my point of view).

**Comment by AlexandraMoga** [comment]
No longer an issue
