### ISSUE TITLE
Migrated FxA user can delete their FxA account making their AMO account unsusable

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#2544]
I got this from a user report, so not sure it is 100% accurate. This is basically the opposite of #2451. STR:

1) create an FxA account
2) link it with your AMO account, which has add-ons
3) delete the FxA Account

Expected:
* Provide some way to recover the AMO account, or disallow deletion of the fxa account until the AMO account is unlinked

Actual:
* AMO account still exists and has add-ons, but can't log in

**Comment by andymckay** [comment]
The only way I could see this working is to try and block the FxA account deletion, but I'm not sure how we'd do that, it's not currently a feature of FxA that it will query every service to see if it can delete an account.

Not sure what there is to do here, but cc'ing @rfk incase he has any insight.

**Comment by kewisch** [comment]
I'd suggest that the password reset feature is modified so that if the fxa account has gone away, then email is sent to the user allowing to link against a new fxa account.

**Comment by andymckay** [comment]
Password reset on AMO or FxA?

**Comment by rfk** [comment]
Thanks for the heads-up @andymckay.  Trying to block FxA account deletion doesn't sound very pleasant to me, but if it helps, we do have an SQS stream of account deletion events that AMO could consume in order to try to do something with the account records on your side.  Would it make sense just to e.g. delete the AMO-side account data if the FxA account has been deleted?

The idea in https://github.com/mozilla/addons-server/issues/2544#issuecomment-216391206 of triggering a recovery flow seems promising, I wonder if this could use very similar mechanics to the current migration flow, for associating an existing AMO account with an FxA account.

**Comment by andymckay** [comment]
We don't actually want to delete anything when the account is deleted, because then you'd delete add-ons and that would be bad.

**Comment by kewisch** [comment]
I was thinking password reset on AMO. So when you try to log in with your ex-FxA account email on AMO, you get a message that your account is temporarily deactivated and have received instructions to reactivate your account via email. These instructions send you to a link to reconnect your account with a FxA account. Add extra hoops to prevent spam/hackers as needed.

**Comment by andymckay** [comment]
Bear in mind the whole point of using FxA is to remove all of this logic for password reset from AMO and those pages will be removed. Something custom would have to built using the logic set out in https://github.com/mozilla/addons-server/issues/2544#issuecomment-216425755

**Comment by eviljeff** [comment]
Couldn't you just recreate the FxA account with the same email address and it would work again?  Or is that too simplistic an assumption...

**Comment by kewisch** [comment]
That may actually work. But I am also on the fence if it is actually a good thing. Imagine the edge case that the user's email got compromised, the user therefore deletes the fxa account and creates a new one. The attacker could recreate the fxa account and then sign in to AMO.

**Comment by eviljeff** [comment]
>Imagine the edge case that the user's email got compromised

If the user's email account got compromised then any password reset email AMO sent (as [suggested](#issuecomment-216669763)) would also then be compromised.

**Comment by kewisch** [comment]
Ok, true, sorry about that. Just gives me an uneasy feeling that re-creating a deleted account would give back access to another system. I'll think of a better use case before I dig further.

**Comment by mstriemer** [comment]
> Couldn't you just recreate the FxA account with the same email address and it would work again?

I just tried this on -dev and it is indeed the case. The user gets a new FxA ID and we copy that into the database. The "Manage Firefox Account..." link this works as expected and shows the updated FxA ID.

Since we don't have a good way of verifying a user other than sending them an email this seems reasonable to me.

Closing this as it seems we already have a good solution. If there anyone has reasons this isn't good enough please comment or file a new issue.
