### ISSUE TITLE
Docker for Mac doesn't like the entrypoint bash script

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2616]
Using the (in beta) Docker for Mac, our script that creates a new `olympia` user fails for the worker image and means we can't boot docker/addons-server.

If I remove this line: https://github.com/mozilla/addons-server/blob/master/docker-compose.yml#L4

It's all fine; everything starts up no problem and I can run `make initialize_docker`, then navigate to `0.0.0.0` and get Add-ons site.

Not sure if that setting messes things up for Linux users who aren't using a VM, would love to know. But it might be a relic of the old Virtualibox way of using Docker which it seems is being phased out.

**Comment by muffinresearch** [comment]
Looking at the problem I think we need to wait for a fix on docker's side because we do still want that user change to prevent files being written to the volume  as if they are owned by root.

What is happening on the mac beta is the script that introspects the volume for the ownership sees it as if it's owned by root and then tries to create a user with root's uid which will fail because it already exists. 

A workaround could conditionally step overl the user creation stuff if it already exists. There's a forum post with more details here: https://forums.docker.com/t/new-file-sharing-uid-gid-permissions-break-image-portability/8586

**Comment by tofumatt** [comment]
Yeah, I assumed removing it was a “quick fix” for me, but not something we want to do forever. 😀

**Comment by muffinresearch** [comment]
> A more correct osxfs permissions model is under development and will be released in a beta, soon. 

Fortunately it does sound like it will get fixed in the beta in due course.

**Comment by andymckay** [comment]
I think I've got this working, but I'm blocked by #2596 I think.

**Comment by EnTeQuAk** [comment]
#2596 should be fixed with https://github.com/mozilla/addons-server/pull/2684 - once dockerhub build new images it should be fine.

**Comment by muffinresearch** [comment]
Update, I've tried this now docker for mac is out of beta and it still suffers the same problem. Passing the user uid via env var looks to be one way we could fix this. 

If we can find the user uid from the container some other way then that would be better, but I'm not sure that will be possible.
