### ISSUE TITLE
Minor UI issue in statistics pages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2717]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0

Steps to reproduce:
1.Go to https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30
2.Observe the Top Languages description under pie chart

Expected results:
No UI issues

Actual results:
Ui issues with the colored boxes from Deutsch and Francais languages

NOTES:
Also observe the "(US)" and "(en-us)" redundant descriptions near English language

Please see video for this bug:
![deutsch](https://cloud.githubusercontent.com/assets/1583842/15423184/032cf9b4-1e85-11e6-9e4e-acd7654f2414.gif)

**Comment by wagnerand** [comment]
Mentor is @kmaglione.

Would you mind adding some more details about the issue?

**Comment by kmaglione** [comment]
We should probably fix this by making the series dot an inline block element at the start of the `<td>` rather than a `float: left` element at the end:

https://github.com/mozilla/addons-server/blob/0f3f03ddbc4a52726583819247f2877c361ca676/static/css/impala/stats.less#L163
https://github.com/mozilla/addons-server/blob/0f3f03ddbc4a52726583819247f2877c361ca676/static/js/impala/stats/topchart.js#L122

See https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code for some pointers on getting started with our codebase.

**Comment by lavish205** [comment]
I would love to work on this bug.

**Comment by tofumatt** [comment]
@lavish205 Feel free to work on it; we can't assign you in GitHub because you aren't part of the Mozilla org, but consider it assigned to you 😄 

Thanks!

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/P3Y0kUY5Y
