### ISSUE TITLE
Accept CRX uploads in "Submit a new Add-on"

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2726]
Part of #2579, we should accept `.crx` files in the "Submit a new Add-on" flow.

CRX files are just zip files with some extra bit in the header, so we should be able to extract them and use them as add-ons the same as we do with `.xpi` files (zip archives) now.

**Comment by krupa** [comment]
test webextension: http://cl.ly/3n3n0e2E1k3L

## setup:
Set xpinstall.signatures.dev-root to true in about:config

## STR:
0. Download Amazon Storywriter webextension from Chrome store and directly upload the .crx file without any modifications. Approve the app from Editor tools.
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/amazon-storywriter/ on your Firefox dev edition 49.0a2 (2016-06-27). I'm using the de build,just fyi.
2. Install the webextension from #1 

## expected behavior:
install is successful 

## observed behavior:
install fails with the following error

1467067541299	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing permissions.5: Unexpected value {"fileSystem":["write"]}
Log.jsm:753
1467067541301	addons.xpi	WARN	Download of https://addons-dev.allizom.org/firefox/downloads/latest/amazon-storywriter/addon-492104-latest.xpi?src=dp-btn-primary failed: Error: Extension is invalid (resource://gre/modules/addons/XPIProvider.jsm:892:11) JS Stack trace: loadManifestFromWebManifest<@XPIProvider.jsm:892:11 < TaskImpl_run@Task.jsm:319:40 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < Promise*this.PromiseWalker.scheduleWalkerLoop@Promise-backend.js:747:11 < this.PromiseWalker.schedulePromise@Promise-backend.js:779:7 < this.PromiseWalker.completePromise@Promise-backend.js:714:7 < TaskImpl_run@Task.jsm:324:13 < promise callback*TaskImpl_handleResultValue@Task.jsm:395:7 < TaskImpl_run@Task.jsm:327:13 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < Promise*this.PromiseWalker.scheduleWalkerLoop@Promise-backend.js:747:11 < this.PromiseWalker.schedulePromise@Promise-backend.js:779:7 < Promise.prototype.then@Promise-backend.js:454:5 < TaskImpl_handleResultValue@Task.jsm:395:7 < TaskImpl_run@Task.jsm:327:13 < TaskImpl@Task.jsm:280:3 < createAsyncFunction/asyncFunction@Task.jsm:254:14 < Task_spawn@Task.jsm:168:12 < promiseLocales@Extension.jsm:963:30 < ExtensionData.prototype.initAllLocales<@Extension.jsm:992:25 < TaskImpl_run@Task.jsm:319:40 < TaskImpl@Task.jsm:280:3 < createAsyncFunction/asyncFunction@Task.jsm:254:14 < loadManifestFromWebManifest<@XPIProvider.jsm:888:23 < TaskImpl_run@Task.jsm:319:40 < promise callback*TaskImpl_handleResultValue@Task.jsm:395:7 < TaskImpl_run@Task.jsm:327:13 < TaskImpl@Task.jsm:280:3 < createAsyncFunction/asyncFunction@Task.jsm:254:14 < loadManifestFromZipReader<@XPIProvider.jsm:1426:21 < TaskImpl_run@Task.jsm:319:40 < TaskImpl@Task.jsm:280:3 < createAsyncFunction/asyncFunction@Task.jsm:254:14 < AddonInstall.prototype.loadManifest<@XPIProvider.jsm:5633:26 < TaskImpl_run@Task.jsm:319:40 < TaskImpl@Task.jsm:280:3 < createAsyncFunction/asyncFunction@Task.jsm:254:14 < AddonInstall.prototype.onStopRequest@XPIProvider.jsm:5947:9

**Comment by andymckay** [comment]
```
1467067541299 addons.webextension. ERROR Loading extension 'null': Reading manifest: Error processing permissions.5: Unexpected value {"fileSystem":["write"]}
Log.jsm:753
```

It's got a set of permissions we don't support. That's an app, not an extension.

**Comment by tofumatt** [comment]
Looks like we should try to flag that, I suppose in the linter.

I’ll aim to have a patch tomorrow so we can include it in the tag.

- tofumatt

On 27 June 2016 at 23:53:34, Andy McKay (notifications@github.com) wrote:

1467067541299 addons.webextension. ERROR Loading extension 'null':
Reading manifest: Error processing permissions.5: Unexpected value
{"fileSystem":["write"]}
Log.jsm:753

It's got a set of permissions we don't support. That's an app, not an
extension.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/addons-server/issues/2726#issuecomment-228900048>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAFi9y_4THjS6VViGsiUliO8lUqMe1_qks5qQFRtgaJpZM4IkuVZ>
.

**Comment by tofumatt** [comment]
I should be clear: https://addons-dev.allizom.org/en-US/firefox/addon/amazon-storywriter/ needs to be deleted, it will never work to be installed in Firefox. But if the add-on @krupa originally tried submitting is submitted now, it should fail validation.

**Comment by vcarciu** [comment]
Verified as fixed : 
![javascript](https://cloud.githubusercontent.com/assets/1583842/16458985/dc335f3c-3e29-11e6-9c13-65b9ec8182b4.png)
