### ISSUE TITLE
Cope with comments in manifest.json

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2734]
I think we'll need to strip comments out of the manifest.json file at least before validation. Perhaps it needs to happen in the validator:

https://bugzilla.mozilla.org/show_bug.cgi?id=1196283
https://hg.mozilla.org/integration/fx-team/rev/036c763dedca215c00853146dc050a766dfd1f04

Supports #2579.

**Comment by EnTeQuAk** [comment]
We will have to strip them in addons-server too, e.g for repacking, maybe updating some stuff in the manifest.json or who knows. Comments in JSON is a pretty bad idea imho, it's not a standard and I don't know any proper library that has any support for it... :disappointed: 

I don't think support for it in addons-linter is important to have for a first step but we have to keep it in mind that manifest files can contain comments.

**Comment by EnTeQuAk** [comment]
Oh, I noticed that this is something chrome added, nevermind my :disappointed: then :laughing:

**Comment by tofumatt** [comment]
The thing about it is the linter should really just be linting things but should be tolerant of things like comments and `update_url`.

The question is: which of the linter or addons-server should be the thing to modify WebExtensions to work on AMO?

The linter needs to scan them and parse them anyway, so I feel like it should do it. If we want it to be able to lint WebExtensions offline, on the CLI (which was an original goal) then we need to be able to understand/ignore Chrome-specific things.

I guess we need to have the code in two places. The linter needs to parse it but AMO needs to _remove_ it. I'm just trying to do it once, but I actually think that's not the best option here, even if it's more work.

**Comment by EnTeQuAk** [comment]
yeah, both will have to handle it since both are opening it and parsing it and both have logic to fetch some data from the manifest.

**Comment by tofumatt** [comment]
To clarify: we don't need to remove stuff, just be tolerant of the comments when parsing JSON.

Sorry I wasn't clear before.

**Comment by tofumatt** [comment]
I'm about to take this on, but if I remember correctly it's `addons-linter` that parses the `manifest.json` and supplies that info back to AMO. So if AMO never touches the `manifest.json` directly, this is already fixed by https://github.com/mozilla/addons-linter/pull/724.

@EnTeQuAk Any chance you can confirm the linter handles all JSON parsing?

**Comment by EnTeQuAk** [comment]
@tofumatt there are two places where AMO touches `manifest.json`

 * https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L239
 * https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L758

We don't get any information back from the addons-linter that we use. It would be nice though but I think it's also nice to have the tooling in AMO in case we have to touch it for some reason in the future. Afterall the linter should "lint" and not "extract metainformation" I guess, although it could be a perfect place because it already opens all those files.

**Comment by vcarciu** [comment]
Verified as fixed : 
![comments](https://cloud.githubusercontent.com/assets/1583842/15939710/a101f76e-2e81-11e6-915a-1a4b674366ce.png)

**Comment by muffinresearch** [comment]
@vcarciu that doesn't look like JSON to me :)

**Comment by vcarciu** [comment]
@muffinresearch  : I am sorry  , we tested with webextensions, but when I wanted to add the photo I added a modified install.rdf 

Here is the correctly validated JSON : 
![json](https://cloud.githubusercontent.com/assets/1583842/15942037/6743b878-2e8b-11e6-9cc3-7f7f43eb24f1.png)
