### ISSUE TITLE
Use large image for theme preview in discovery API

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#2756]
The preview image in the API is currently the image that is used on the homepage in the small grid. This is too small for the discovery pane. It would be better to return the larger image that is currently being used on the theme detail page.

Old: https://addons-dev-cdn.allizom.org/user-media/addons/362876/preview.jpg?1328800895
New: https://addons-dev-cdn.allizom.org/user-media/addons/362876/preview_large.jpg?1328800895

**Comment by diox** [comment]
It's actually coherent: `icon_url` is returning the small preview (as close as an icon size as we can), but in `theme_data` you have `previewURL` which points to the big one. That field is not properly documented though.

Do you prefer:
- A new field called `preview_url` ? I'm hesitant to add this because I don't want it to be mistaken with actual add-ons previews.
- Full documentation (and insurance that it's part of the stable API) for `theme_data` ?

**Comment by mstriemer** [comment]
I'm seeing 3 "preview" images returned, but 2 are the same and the large one isn't returned.

preview_small.jpg as `addon.icon_url` or `addon.theme_data.iconURL`
![preview.jpg](https://addons-dev-cdn.allizom.org/user-media/addons/362876/preview_small.jpg?1328800895)

preview.jpg as `addon.theme_data.previewURL`
![preview.jpg](https://addons-dev-cdn.allizom.org/user-media/addons/362876/preview.jpg?1328800895)

preview_large.jpg is not returned
![preview_large.jpg](https://addons-dev-cdn.allizom.org/user-media/addons/362876/preview_large.jpg?1328800895)

**Comment by diox** [comment]
Uh, ok, misread the data. I'll investigate.

**Comment by diox** [comment]
Ok, what's happening is, that theme is an old Persona. The new ones use the same image for medium and large previews. I'll make sure we always return the large version in `addon.theme_data.previewURL` no matter what.
