### ISSUE TITLE
Calculate e10s status on submission

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2772]
We need to calculate if an add-on is e10s compatible or not when it is submitted. There's really currently the following states for this:
* its WebExtension, yay!
* its set the https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#multiprocessCompatible flag (not sure how that works with jpm addons)
* its not

I think that's about it. There's stuff around the shim that we might be able to do but I'm not sure how reliable that is going to be.

We'll need to refer to this data later on, so we'll need to persist it somewhere. I think just doing it per add-on will suffice.

Supports #2770

**Comment by andymckay** [comment]
@jvillalobos is there anything else you think its worth trying to calculate?

**Comment by andymckay** [comment]
Following up, I don't think we need to do anything special for jpm, if you set `permissions.multiprocess` to `true` then this patch alters jpm to add that into the `install.rdf`. 

https://github.com/mozilla-jetpack/jpm/commit/316d282c406890ac0c7e86e0e1abfbaee5c2eaec

**Comment by jvillalobos** [comment]
We could detect SDK add-ons that only use high-level APIs and add the flag ourselves, but I suppose that's out of scope here. Otherwise looks okay.

**Comment by andymckay** [comment]
Following up, I don't think we need to do anything special for jpm, if you set `permissions.multiprocess` to `true` then this patch alters jpm to add that into the `install.rdf`. 

https://github.com/mozilla-jetpack/jpm/commit/316d282c406890ac0c7e86e0e1abfbaee5c2eaec

**Comment by andymckay** [comment]
Sorry for the noise, pressed wrong button.

**Comment by diox** [comment]
So what do we want to store and then display to users in #2770 : a simple boolean (and then display yes/no) or more values ?

**Comment by andymckay** [comment]
Let's not make it a boolean, there's 3 states right now (although admittedly webextensions might be stored elsewhere) and if we can figure out how to parse SDK add-ons for their use of high or low level APIs we might get more (as per Jorgevs comment).

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7).
1. Unknown (default) (add-on listed):
![addon full](https://cloud.githubusercontent.com/assets/15685960/15931429/6929f754-2e60-11e6-9a5e-5e6692f5c4c4.png)

2. Compatible because it's marked as such in install.rdf (add-on unlisted):
![addon_unlisted_set_compat](https://cloud.githubusercontent.com/assets/15685960/15931443/790162ac-2e60-11e6-858c-e8fa15978658.png)

3. Compatible because it's a web extension:
![bul](https://cloud.githubusercontent.com/assets/15685960/15931478/94558e66-2e60-11e6-89f8-9a72bbdb3a48.png)
