### ISSUE TITLE
Show e10s status to the developer

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2773]
When a developer comes to their devhub pages, we should show the status to the developer. Something like:

![image00](https://cloud.githubusercontent.com/assets/74699/15584264/ac1f8098-232e-11e6-968d-441e778438e9.png)

This is the addition of a line to the border on the left. Have to say it's not exactly obvious and we should probably do something a bit bigger and more obvious. Maybe with emoji.

Supports: #2770

**Comment by diox** [comment]
What values do we want to display ? Just "Compatible" / "Incompatible" ? or "Compatible" / "Shimmed" ? https://github.com/mozilla/addons-server/issues/2772#issuecomment-222162789 suggests not use a boolean for storage to get more insights in the data, but do we need to display more to the developer, and what do we tell them exactly ?

https://www.arewee10syet.com/ has more statuses but relies on user testing, and we don't since we rely on what the developer specified in his manifest.

**Comment by andymckay** [comment]
I think just Compatible (if WebExtension or marked as Compatible) or Incompatible will do for now and if we get more data from other sources, we can add it in.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7)
Postfix screenshot: 
![submission](https://cloud.githubusercontent.com/assets/15685960/15932761/8bf42a2a-2e65-11e6-85e0-327939ecc196.png)
