### ISSUE TITLE
Replace the "An unexpected error occurred" message with something less alarming

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2821]
When user uploads an invalid file, instead of showing "An unexpected error occurred" message, let us show something less alarming and probably more useful like-

"uh-oh, looks like there is something wrong with your file. Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at <link>"

An unexpected error makes it seem like it is our fault when it is more likely user error. We should only show the unexpected error only when we hit a 500.

**Comment by madalincm** [comment]
Verified in FF47(Win7) in addons.alliom.org
Do we still want to keep this line: "Error: Validation was unable to complete successfully due to an unexpected error."?  That is still displayed in the validation result page.  
Postfix screenshot:
![2821](https://cloud.githubusercontent.com/assets/15685441/15935209/343550d4-2e6f-11e6-985c-de4609c21e61.png)

**Comment by tofumatt** [comment]
That appears correct to me 👍

**Comment by madalincm** [comment]
Thanks tofumatt 
Marking as verified fixed
