### ISSUE TITLE
DE translations for discopane api content end the heading with a period

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2854]
See e.g. https://github.com/mozilla/addons-server/blob/master/locale/de/LC_MESSAGES/django.po#L6996

Because the period is after the subheading you end up with a very bold `.` ending the heading. It looks like this:

<img alt="add-ons_entdecken" src="https://cloud.githubusercontent.com/assets/1514/15817601/b92aedb8-2bd0-11e6-90a8-3c3eb6083ed4.png">

These aren't in the original string. If they need to remain they should move inside the `sub_heading` or just be removed otherwise.

**Comment by andymckay** [comment]
I'm not sure the l10n team follow addons-server, maybe ping the dev-l10n mailing list?

**Comment by wagnerand** [comment]
Adding @koehlermichael.

**Comment by koehlermichael** [comment]
Thank you for notifying me of this issue. There are [four strings](https://pontoon.mozilla.org/de/amo/LC_MESSAGES/django.po/?search=sub_heading) of similar structure, I now moved the period directly after _{addon_name}_ in all cases.

Could you please link to where exactly these strings appear? I couldn’t find them so far. I added the periods because the strings seemed like complete sentences to me, this might change if I understand the context.

Thanks again.

**Comment by muffinresearch** [comment]
@koehlermichael looks better now - thanks. 

I think you can probably remove all the periods them for consistency with the theme translations.

See https://github.com/mozilla/addons-server/blob/master/locale/de/LC_MESSAGES/django.po#L6994 for all the strings from the same file: src/olympia/discovery/data.py

**Comment by koehlermichael** [comment]
Here you go, I hope I caught all strings.

**Comment by muffinresearch** [comment]
@koehlermichael that's perfect. Thanks very much!
