### ISSUE TITLE
Download statistics are lower than usual since 2016.06.02 push

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/addons-server#2857]
It looks like download redirects changed in https://github.com/mozilla/addons-server/pull/2771, specifically the redirect with '/%/downloads/file/%' was removed. This was used for download statistics calculation.

We need to adjust the hive query in amoDownloadCountsFiltered.py to use a different path instead.

**Comment by diox** [comment]
Where does this code live ? I can't find any `amoDownloadCountsFiltered.py` in addons-server.

**Comment by jasonthomas** [comment]
The code is located on a IT metrics host, I believe it was placed there as part of bug 1089358. I am not sure if it lives in version control anywhere, but possibly in mozilla svn. 

I want to move them into github, but I need to verify if there are any hardcoded credentials.

**Comment by jasonthomas** [comment]
> I want to move them into github, but I need to verify if there are any hardcoded credentials.

There are passwords and hostnames that need to be cleaned up before I would consider moving it into a github repo. I will work on that today.

It looks like we still use URLs like '/%/downloads/file/%' in the versions page [1]. Since we still need these as part of the the download statistics we can't just replace the current query to use some variation of '/%/downloads/latest/slug/addon-id-latest.xpi'. Also any adjustments to the hive query to grab the addons.id instead of the files.id would require changes to download_counts_from_file.py [2].

Any recommendations on how to approach this? 

[1] https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/versions/
[2] https://github.com/mozilla/addons-server/blob/master/src/olympia/stats/management/commands/download_counts_from_file.py

**Comment by andymckay** [comment]
Just to note that not all download links have latest in them, for example the links on the version history page. They go direct to the add-on. I think you have to include either URL.

**Comment by mustaim** [comment]
Hello guys,

Now Daily Users is broken, too.

https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/statistics/?last=30

**Comment by mustaim** [comment]
Any feedback please?

**Comment by jvillalobos** [comment]
#2934 is the daily users issue.

**Comment by mustaim** [comment]
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/statistics/?last=90

this has been almost a month issue. downloads cut half.

**Comment by eviljeff** [comment]
I don't suppose counting the CDN download is possible?

**Comment by diox** [comment]
Jason gave me access to the scripts running on the hive side.

In that `amoDownloadCountsFiltered.py` file, it looks for logs containing `'/%/downloads/file/%'` and extracts the 4th component from the URL, which is the addon id. It then writes everything down to a tab-separated file which we then parse in `download_counts_from_file.py`.

There are 2 solutions here:
- Have the hive script also look for `/%s/downloads/latest/%s` *in addition to the one it's already looking for* and extract the 4th component again, giving it the add-on slug. Then modify `download_counts_from_file.py` on our side to work with both add-on slugs and ids.
or
- Have the hive script also look for `/%s/downloads/latest/%s/%s` but extract the 5th component, which is in the form of `addon-<addon id>-latest.xpi`, from which it can extract the id as normal.

One interesting gotcha is that we need to avoid counting the same thing twice. Before #2771 the latest link was a redirect to the real thing. Maybe we can ignore redirects if we have the status code, otherwise we'll need to add some kind of condition based on the date (from the date #2771 was pushed) or something.

To answer @eviljeff , we could count the CDN downloads, but that'd mean enabling logs on the CDN, collecting them in one place, then into HIVE... which would be messy and wouldn't solve the issue for the month we've been missing the data.
 
Final word: I don't quite understand yet why stats are only cut in half and not just completely flat at almost zero. The link users should be using is the `latest` one, so I have yet to understand where the other half comes from...

**Comment by wagnerand** [comment]
> One interesting gotcha is that we need to avoid counting the same thing twice.

That's what @mkaply mentioned to me in London.

**Comment by diox** [comment]
I understood why stats were not completely flat: the legacy API is still using the direct file links, which are parsed correctly. So any installs from the about:addons search in Firefox are still counted properly.

I have an idea how to fix the scripts parsing the logs, just making it look for `/downloads/` instead of `/downloads/file/`, and then simply handle add-on slugs in https://github.com/mozilla/addons-server/blob/master/src/olympia/stats/management/commands/download_counts_from_file.py ; I'll test that.

**Comment by diox** [comment]
Tested my idea locally and it seems to be working fine, so I'll submit a PR to do that. We'll then be able to recalculate stats (we can re-run the hive query for particular dates and re-run `update_counts_from_file` as well, it'll overwrite the existing data).

**Comment by mustaim** [comment]
FYI, stats broken completely today.
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/statistics/?last=90

**Comment by erosman** [comment]
Did the stats take another break on June 30?

ref: https://github.com/mozilla/addons-server/issues/2934

**Comment by EnTeQuAk** [comment]
We're working on fixing this in https://github.com/mozilla/addons-server/issues/3034 but this isn't live yet so the stats may still be broken. The ticket will be updated accordingly once things are fixed / updated.

**Comment by mustaim** [comment]
This is not professional. For 2 months statistics broken. It does not suit corporate Mozilla.

Seriously why do not you deploy in batch after everything is assured working?

2 months ago stats were working well. Why touch it?

**Comment by diox** [comment]
We didn't touch stats - we made a change to remove an unnecessary redirect in the download URLs (improving performance when installing add-ons), and because stats are processed on an external server we did not anticipate the issue before it went into production.

**Comment by diox** [comment]
I fixed the stats processing command on addons-server side in #3034 to allow slugs in URLs. Now we need to modify the hive queries to output slugs and regenerate the missing stats. As I put it in the pull request comments, the plan is to:

- Modify the hive queries. They live on a separate metrics server, and are versioned in the private repos [mozilla/addons-stats-scripts](https://github.com/mozilla/addons-stats-scripts/). I believe the only modification required is to change `amo_download_counts/amoDownloadCountsFiltered.py` line 41, from `request_url LIKE '/%/downloads/file/%'` to `request_url LIKE '/%/downloads/%'`. I'll double check.
- Regenerate the missing stats once the two pieces of the puzzle (updated hive queries + updated command to process them) are present. We should run the queries manually for each day, starting from **2016-06-02** (that's when it'll start adding add-on ids and slugs to the dumps this command processes, as needed to support the new download URLs)

**Comment by diox** [comment]
This should be completely fixed, @jasonthomas triggered a re-processing of all the old data with the new scripts and processing command. See https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=90 for an example of the fixed stats.
