### ISSUE TITLE
Add-on causing display issues in Search Tools add-ons category page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2882]
Steps to reproduce:
Load https://addons.mozilla.org/en-US/firefox/extensions/search-tools/

Expected results:
There are no layout issues.

Actual results:
The add-on has no icon and is causing layout issues in Search Tools category page.

Notes/Issues:
Verified on FF47(Win 7) in AMO-prod.
Screenshot fro this issue: 
![2016-06-09_2127](https://cloud.githubusercontent.com/assets/15685960/15941689/fe4249b2-2e89-11e6-8cab-5d0f4d8a5d82.png)

**Comment by andymckay** [comment]
Looks like the icon for that add-on is a 404 which is wierd and shouldn't happen. I set to a default icon. Also notice that the screenshots on that add-on seem to be half broken. Given that every add-on should have an icon, the real bug is how did that add-on get in that state and that I don't know.

**Comment by eviljeff** [comment]
if this is a one-off, going to close it.
