### ISSUE TITLE
Link with self-reference

### ISSUE THREAD

**Issue by milupo** [mozilla/addons-server#2968]
Hi, I don't know if the current state is intended: There is a link "View Mobile Site" under the big blue stripe below on e.g. following pages:

https://addons.mozilla.org/en-US/about
https://addons.mozilla.org/en-US/faq
https://addons.mozilla.org/en-US/review-guide
https://addons.mozilla.org/en-US/credits

If you click "View Mobile Site" the current page is shown again because this link shows to about#, faq#, review-guide# and credits# then. I think  here a special page should be shown with a title resp with content that corresponds to the label of this link. 

This is not with dsb and hsb only but e.g. also with de and en-US.

Michael

**Comment by andymckay** [comment]
This is because the "view on mobile site" sets a cookie that you'd like to view it in mobile, but that page has no mobile view at all. When you visit a page that requests mobile, you'll end up suddenly in the "mobile view".

The whole mobile view thing is a mess and I think our only chance is to rip all this cruft out and just replace our front end with a responsive design.

**Comment by milupo** [comment]
Ok, Andy, thank you for your quick reply.

**Comment by EnTeQuAk** [comment]
I am going to close this as we're in the process of redesigning / reimplementing our mobile pages anyway without any nasty hacks.
