### ISSUE TITLE
Add-on compatibility checker is not returning any warning for incompatible addons

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2987]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

Steps to reproduce:
1.Go to https://addons.mozilla.org/en-US/developers/addon/check-compatibility
2.Set the checker to check the addons against firefox 51
3.Select an addon with maxVersion 50 and check it for compatibility

Expected results:
Warning is returned saying that addon is not compatible with 51

Actual results:
No warning displayed and "Your add-on was validated with no errors or warnings." message is displayed

Please see video for this bug : 
http://screencast.com/t/kjJCCQ5B

**Comment by EnTeQuAk** [comment]
cc @wagnerand on this, I'm not sure if this is an actual error or supposed to be like that. Because afair the validator doesn't check against `maxVersion` and this is essentially how the bulk validation for bumping add-on versions work so an error here doesn't make much sense imho since you might want to check for compatibility for a future version (which you're doing in your example), e.g it's more about used APIs than the actual `maxVersion` (which is what *you* (the add-on author) believe to be the `maxVersion`)

**Comment by wagnerand** [comment]
@EnTeQuAk is correct.

**Comment by eviljeff** [comment]
looks like this is working as expected.
