### ISSUE TITLE
Don't show multiprocessCompatible warning in validator for non-extensions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2998]
The warning about the add-on not being marked as compatible with Firefox Multi Process is shown for non-extensions (dictionaries for instance), that is probably not very useful, we should not show it for them.

(The warning in devhub should already be hidden)

**Comment by madalincm** [comment]
Verified as fixed in FF47(Win7) in addons-dev.allizom.org
I've tried language pack, dictionary, complete themes and search engine and the e10s warning is not displayed.
![e10sdict](https://cloud.githubusercontent.com/assets/15685441/16490280/a12a9c76-3ee1-11e6-8ed3-461618102998.png)


![e10slangpack](https://cloud.githubusercontent.com/assets/15685441/16490286/a7d3bac6-3ee1-11e6-873a-4b992796f154.png)
