### ISSUE TITLE
Review fails to Display the file

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#3028]
Example:
`https://addons.mozilla.org/en-US/editors/review/ip-check`

**Compare** fails completely.
 **Contents** results in **That file no longer exists.** (<- this is the main concern)

Result of: `https://addons.mozilla.org/en-US/firefox/files/browse/461178/file/index.js#top`
https://postimg.org/image/s9bjvfq0h/

However, clicking "Download index.js" shows the file and I was able to download the XPI (and review it locally) without any issues.

**Comment by kewisch** [comment]
There is something fishy with those files. I get an empty file viewer for the older version 0.2.11-signed at https://addons.mozilla.org/en-US/firefox/files/browse/323756/. Comparing the latest 0.22 with 0.2.11-signed also gives me an empty source viewer. If I compare with other versions or just check the contents of 0.22, I also have no problems (whereas erosman does): https://addons.mozilla.org/en-US/firefox/files/browse/461178/

**Comment by wagnerand** [comment]
This is a multi-part issue.

Version 0.2.11 is no longer reviewable because the file is not accessible. We have no information on why or how this happened. We should investigate if it happens again. Until then, I'd consider it a one-off.

The second issue about `index.js` not being accessible when accessing its url directly seems fixed, I think by https://github.com/mozilla/addons-server/commit/fe62e320c5fdc5bc5724156663667e1e3278c552

**Comment by wagnerand** [comment]
@jasonthomas figured out how 0.2.11 became inaccessible. The author basically re-used that version number, which interfered when we had patched the file to sign it but kept using the original file name. I think we should file a new issue for that.
