### ISSUE TITLE
Don't allow developers to add a XUL add-on as an update to a webextension

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#3061]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1283443, there was a discussion about how versioncheck doesn't work when a webextension is updated with a XUL add-on. Since this is something we don't plan to support, we can warn the developer from doing it during the submission process.

**Comment by EnTeQuAk** [comment]
Should we warn or actually deny the user doing that? Imho we shouldn't even accept that if Firefox doesn't support it.

**Comment by andymckay** [comment]
My default answer is an error, but I'm worried about that because there will probably be a use case where its valid.

Also wondering if we should do something when the users first switch to a WebExtension and say something like "THERE'S NO GOING BACK!", that seems the more important place to do something.

**Comment by EnTeQuAk** [comment]
Hmm, imho no one reads warnings or even remembers them so we will have to make sure we don't accept invalid stuff. But you're right, there certainly will be a valid use-case.

So maybe this should be a warning and a very clear loud, red, pink, yellow blinking warning for reviewers?

**Comment by andymckay** [comment]
Agreed, warnings never get read. Let's see if @jvillalobos has any good ideas.

**Comment by jvillalobos** [comment]
If a XUL file is being submitted as an update to a WebExtension, that should cause an error because automatic updates won't work (IMO updates _should_ work, but that's a different discussion).

When submitting a WebExtension update to a non-WebExtension, I agree there should be a noticeable warning, and it would be best for it to be visible outside of the normal validation results to give it a chance of being noticed.

**Comment by shell15** [comment]
@deadsquid is working on if there is more we should do (Nick/Amy talk).  All agree that doing silently is not ideal. so at least document and submission notification.  @andymckay will work on word copy and someone to add.

**Comment by atsay** [comment]
I agree with @jvillalobos. There should be a prominent warning when updating to a WebExtension so people know they cannot go back. If they then try to update a WebExtension to a XUL extension, it should not be allowed.

If we think there might be edge cases, let's try to identify them. Maybe talk to a few devs in case there's a scenario we're not seeing. Definitely should not allow silent failures.

We should make this clear on MDN too!

**Comment by andymckay** [comment]
Bugzilla bug filed for MDN documentation: https://bugzilla.mozilla.org/show_bug.cgi?id=1286365

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52.0a1(Win 7)
Postfix screeshot: 
![webext addon](https://cloud.githubusercontent.com/assets/15685960/18703228/ad3f1e90-7fed-11e6-8770-0cb593a2489c.png)
