### ISSUE TITLE
Links to external sites are resolving to a 400

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#3073]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/tab-scope/?src=hp-dl-featured
2. Click on the link 'Add-on homepage'

## expected behavior:
The Add-on homepage loads

## actual behavior:
https://outgoing.stage.mozaws.net/v1/df3a83c1b4d2da1fa92023957e145b62b917e1cb2f74f4d33330de7164b55dc6/http%3A//www.xuldev.org/tabscope/ resolves to 400.

## screenshot
<img width="1440" alt="screen shot 2016-07-11 at 12 51 17 pm" src="https://cloud.githubusercontent.com/assets/301317/16744481/354da038-4766-11e6-9802-af0411ed7c8f.png">

**Comment by andymckay** [comment]
I believe that ops is working on moving outgoing to a new server. @jasonthomas might know more.

**Comment by bqbn** [comment]
@oremj can you confirm that the behavior that the new golang outgoing app doesn't support "%3A" in the url is expected? The redirection on the page mentioned in step 1 looks like this:

```
<a class="home" href="https://outgoing.stage.mozaws.net/v1/df3a83c1b4d2da1fa92023957e145b62b917e1cb2f74f4d33330de7164b55dc6/http%3A//www.xuldev.org/tabscope/">
```
the app would have had to change "%3A" into ":", then calculate the checksum in order to return 200 vs 400. The php app may be doing that, but the golang app does not.

**Comment by oremj** [comment]
I'm pretty sure I found the bug in outgoing.

**Comment by oremj** [comment]
@bqbn the fix should be in master.

**Comment by andymckay** [comment]
This link now works for me, thanks @oremj.

**Comment by bqbn** [comment]
@oremj it looks like for the old php program the same checksum works for both "%3A" and ":" cases. For example, try copy and paste the following to the address bar:

```
curl -I "https://outgoing.allizom.org/v1/df3a83c1b4d2da1fa92023957e145b62b917e1cb2f74f4d33330de7164b55dc6/http%3A//www.xuldev.org/tabscope/"
curl -I "https://outgoing.allizom.org/v1/df3a83c1b4d2da1fa92023957e145b62b917e1cb2f74f4d33330de7164b55dc6/http://www.xuldev.org/tabscope/"
```

Note that both above URLs contain the same checksum.

Does anyone know if the thing that generates the link consistently produces "%3A" and no ":"? If there are links that contains ":", then the new program probably needs to take care of both cases as well.

**Comment by andymckay** [comment]
Its addons-server that generates the links and stores them in db, so if at any time that code changes then you have to rummage through the database and alter all the urls. Its a pain, but we did this a while back to force everything to be https instead of http. It could be that code has changed and caused inconsistency in the links.

**Comment by bqbn** [comment]
Just verified the fix @oremj put in does work in both cases. Both below returned 200.

```
curl -I "https://outgoing.stage.mozaws.net/v1/df3a83c1b4d2da1fa92023957e145b62b917e1cb2f74f4d33330de7164b55dc6/http://www.xuldev.org/tabscope/"
curl -I "https://outgoing.stage.mozaws.net/v1/df3a83c1b4d2da1fa92023957e145b62b917e1cb2f74f4d33330de7164b55dc6/http%3A//www.xuldev.org/tabscope/"
```
I think we're good. :)

**Comment by madalincm** [comment]
Verified as fixed in FF47(win7) in addons-dev.allizom.org
Postfix screencast:
![outgoinglink](https://cloud.githubusercontent.com/assets/15685441/16796176/e821133c-48e9-11e6-9af2-9b28eaabb1ed.gif)
