### ISSUE TITLE
Remove Preliminary Review option for add-ons awaiting full review

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3086]
This is part of #3083.

Add-ons that are in the Full Review queue and Pending Updates queue should no longer have Grant Preliminary Review as an option in their reviewer page.

**Comment by ValentinaPC** [comment]
@eviljeff : the option to request preliminary review for add-ons awaiting full review is still available in "Manage Status & Versions" page, from Dev Hub (for old or new submission). The option is functional too.
Verified on AMO-dev FF47(Win 7 x64).
Please see the screenshot: 
![awpr](https://cloud.githubusercontent.com/assets/15685960/17394434/b097b336-5a31-11e6-8617-e3d425776d43.png)

I'll reopen this until further notice.

**Comment by eviljeff** [comment]
You need to enable a waffle switch - see https://github.com/mozilla/addons-server/issues/3084#issuecomment-235973353 (the first of the sub-issues of #3083).  Without the waffle switch enabled the functionality should be same as now.

**Comment by ValentinaPC** [comment]
@eviljeff : Ok, sorry for that!
After I've enabled the option and all things mentioned in this issue worked as expected.
I have a question, related to the next scenario:
- pick an add-on that is "awaiting full review"
- go to "Manage Status & Versions"
- click "Cancel Review Request"
My results are: version status turns into "awaiting preliminary review" ...intended or does not mater because add-on is already incomplete?
Thanks!

**Comment by eviljeff** [comment]
> I have a question, related to the next scenario:

I don't follow your question, but can you ask in #3085 if its related to devhub changes because this change just touches editors tools.

**Comment by ValentinaPC** [comment]
Thanks!
