### ISSUE TITLE
Please update django-mozilla-product-details to the most recent version

### ISSUE THREAD

**Issue by sylvestre** [mozilla/addons-server#3200]
As the SVN product detail is going away ( see https://bugzilla.mozilla.org/show_bug.cgi?id=1288171 for the meta bug), please switch to the latest version of django-mozilla-product-details (see https://bugzilla.mozilla.org/show_bug.cgi?id=1282494)

This will use the new product details platform: https://product-details.mozilla.org/1.0/

**Comment by sylvestre** [comment]
pmac did the change here:
https://github.com/mozilla/django-product-details/commit/4481a30a51deff1ad39afe135c83c1021f290ad5

**Comment by andymckay** [comment]
Just note that the last upgrade of django-product-details almost killed AMO. The version I upgraded to loads the product details off the filesystem and did not cache it. At the scale of AMO we had to remove it. 

Might be worth checking this and testing with @jasonthomas, since I might be misremembering or things changed since then.

I didn't enter too many details, but did file an issue here: #1121

**Comment by andymckay** [comment]
...and after linking to that other bug I see it did the opposite, using memcache not the filesystem. That was when we were also having memcache and general AWS issues though. Anyways.

![knowing](https://cloud.githubusercontent.com/assets/74699/17254152/8dc3f752-5581-11e6-8690-a5a883ccbc3e.jpg)

**Comment by EnTeQuAk** [comment]
We do have our own backend for `django-mozilla-product-details` now to restore the old behavior of having everything in-memory for performance reasons, see https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/product_details_backend.py for more details. This might need an update too.

**Comment by diox** [comment]
This should land in prod next week.
