### ISSUE TITLE
Incompatible add-on message displayed on hover makes addon list jump/shake

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/addons-server#3203]
1. Go to https://addons.mozilla.org/en-US/firefox/extensions/?sort=created&unreviewed=on&page=1 with Firefox 47.
2. Find an add-on which is incompatible and has a short summary (must not be the first in the list).
3. Move your mouse over it.

Actual result: List items get shifted and mouse might end up over a different addon because "Not available for Firefox 47.0" gets added to the listing and increases its height.

**Comment by ValentinaPC** [comment]
Happy to see this happening - https://github.com/mozilla/addons-server/issues/2366

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF47(Win 7 x64).
The flicker still happening for incompatible add-ons that have an "?" info mark. 
I'll provide 2 screenshots for an incompatible add-on with "?" and without and also 2 links for each, because I am not sure what is the difference:
-> https://addons-dev.allizom.org/en-US/firefox/addon/evernote-web-clipper/?src=search
![with_](https://cloud.githubusercontent.com/assets/15685960/17507455/594d3052-5e18-11e6-8e1c-450c19593c81.png)
-> https://addons-dev.allizom.org/en-US/firefox/addon/british-english-dictionary-/?src=search
![without_](https://cloud.githubusercontent.com/assets/15685960/17507456/597ede36-5e18-11e6-82f8-6d3ba6295f21.png)

Reopening until further notice.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48(Win 7 x64)
Postfix video: 
![incopat](https://cloud.githubusercontent.com/assets/15685960/17549376/91b1f258-5ef8-11e6-9b0d-08c2598367f5.gif)
