### ISSUE TITLE
Add-on with install.rdf and manifest.json is incorrectly marked as e10s compatible

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3255]
[This old add-on](https://addons.mozilla.org/addon/ign/) shows up as compatible with e10s in the developer hub. It looks like the problem is that the add-on has both an `install.rdf` and `manifest.json`, and the latter is used to determine compatibility. Add-ons like this one should not appear as compatible so we have accurate data.

**Comment by diox** [comment]
In 7d46c8c0f84acbc7236f6a2456c3d0528d5b46bc (#2450) we modified the XPI parsing code to make sure that if there were a `manifest.json`, we'd consider the add-on as a webextension no matter what. The linter then throws an error if it sees a `install.rdf`, but as far as addons-server parsing code is concerned, it's a web extension.

e10s compatibility relies on the same parsing code, so the add-on is considered compatible because it's considered a web extension at parsing time.

I'd like to avoid adding a hack for such an edge case - it only concerns a handful of add-ons that had been uploaded before the check was made at upload time, and we can alter the value we stored in the database for them - it's just a matter of finding them. This should get us started:
```
suspicious = [afc.addon for afc in AddonFeatureCompatibility.objects.filter(e10s=2) if afc.addon.current_version and not all([file_.is_webextension for file_ in afc.addon.current_version.all_files])]
```

**Comment by diox** [comment]
Full script to switch add-ons that have both files to "unknown":

```
import os.path
import tempfile

from olympia.files.utils import check_xpi_info, Extractor, extract_xpi, get_file, rm_local_tmp_dir


suspicious = [afc.addon for afc in AddonFeatureCompatibility.objects.filter(e10s=2) if afc.addon.current_version and not all([file_.is_webextension for file_ in afc.addon.current_version.all_files])]


def has_both_files(xpi):
    path = tempfile.mkdtemp()
    try:
        xpi = get_file(xpi)
        extract_xpi(xpi, path)
        return os.path.exists(os.path.join(path, 'manifest.json')) and os.path.exists(os.path.join(path, 'install.rdf'))
    finally:
        rm_local_tmp_dir(path)
    return False

for addon in suspicious:
    file_ = addon.get_latest_file()
    if file_:
        try:
            if has_both_files(file_.file_path):
                print "Switching %s back to incompatible" % (addon.name)
                addon.addonfeaturecompatibility.update(e10s=0)
        except Exception as e:
            print e
            print "can't parse addon %s" % (addon.name)
```

I ran this on stage, I'll ping an ops to run this on prod.

(I didn't want to bother checking if they were marked as compatible. I doubt they are, cause they wouldn't pass validation nowadays anyway, since the linter would complain, as mentioned in my previous comment)

**Comment by diox** [comment]
@jasonthomas ran the script on prod.

9021 addons were marked as compatible because they are a web extension. 217 were considered as suspicious by the script because they did not have the `is_webextension` flag set on all the files of their current version. 204 were switched back to "unknown" because they had both an `install.rdf` and a `manifest.json` file.

It's worth noting that some of those 204 add-ons might actually be compatible webextensions. Developers of such extensions need to resubmit a new version without the `install.rdf` and it'll be seen by addons-server as a valid webextension, switching back the e10s compatibility flag to "compatible".
