### ISSUE TITLE
[Request] Add Developer name to the Editors Queue Display

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#3285]
It would be useful to display the name of the developer in the queue listing eg under the addon name or a separate column.

**Comment by eviljeff** [comment]
why, do you avoid/focus on particular developers?

**Comment by erosman** [comment]
The extra information is helpful.

- There are addons by the reviewers (usually missed)

> https://wiki.mozilla.org/Add-ons/Reviewers
> Review privileges: full reviews and updates of add-ons and apps authored by reviewers are fast-tracked 

- There are addons by the same developers which could have similar code and can be reviewed together (e.g. I have 2 addons that have a very similar code)
- There are developers who tend to regularly include questionable code (requires closer attention)
- It shows flooding (when a developer uploads 10s of addons, I recall one that did 156 at one time)
- etc etc ....

There are all sort of reason ....... not all can be listed ;)

It would save time, bandwidth and resources (Mozilla & reviewer) to have the developer name, instead of opening the corresponding page to find it out. ;)

**Comment by jvillalobos** [comment]
We're trying to remove information from the queue view because it's very cluttered. We discussed this and decided we don't want to include the developer name because we don't think it will be much help to most reviewers. As for highlighting submissions by reviewers, we definitely want that, but we'll do it differently (since we don't expect reviewers to know each other's usernames.
