### ISSUE TITLE
Mail that unlisted addon got signed uses wrong (initial?) url stub for addon

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/addons-server#3297]
I uploaded a new addon to AMO which doesn't get listed. Then I received the mail that it got signed and can download the addon. This mail contains the link https://addons.mozilla.org/de/developers/addon/versions1/versions which returns a 404. It doesn't use use the url stub for the addon I assigned during upload. Manually fixing the url loads the page https://addons.mozilla.org/de/developers/addon/versions-by-aryx/versions

**Comment by eviljeff** [comment]
did you update the slug (the url sub) in step 3, or after the submission steps in edit listing?

**Comment by Archaeopteryx** [comment]
All changes during submission: I updated the add-on title (because I knew there would be a conflict), the url autoupdated, I had to shorten it (limit: 30 characters).

**Comment by eviljeff** [comment]
The email gets sent in the processing for step 2 after the upload is successful, so before step 3 when you can change the slug.  I can only assume we've not had earlier reports because changing the slug for an unlisted addon is rare.
I can think of a number of fixes (and ultimately being able to claim a slug for a non-public facing add-on doesn't make much sense anyway) though the easiest imo is using the addon pk (amo id) in the email link because that doesn't change.

**Comment by jvillalobos** [comment]
I think we should use the AMO id for any private communications (listed or unlisted), since it makes the URL resilient to slug changes, and some devs might dig though old email to try to find their add-ons.

**Comment by eviljeff** [comment]
> I think we should use the AMO id for any private communications (listed or unlisted), since it makes the URL resilient to slug changes, and some devs might dig though old email to try to find their add-ons.

changing a few lines to fix just this instance is pretty much a goodfirstbug; changing all references in all emails a bit more work.  Do you want to widen this issue or open a new open?

**Comment by jvillalobos** [comment]
Keep this one as a goodfirstbug and file a followup for the rest.

**Comment by wagnerand** [comment]
Mentor: @eviljeff 

Please refer to https://wiki.mozilla.org/Add-ons/Contribute if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by mattdrake** [comment]
I'd like to try to work this bug. How should I get started? Pretty new to this.

**Comment by eviljeff** [comment]
@jvillalobos is this bug still relevant? - in the new flow we won't allow the developer to change the slug for an unlisted add-on (unless they subsequently go into `edit listing|information` and change it)

**Comment by jvillalobos** [comment]
Since it's still editable, I think it's relevant. Changing the emails and other links to use the numeric ID is a precursor to getting rid of slugs for unlisted add-ons.

**Comment by eviljeff** [comment]
@mattdrake you need to change https://github.com/mozilla/addons-server/blob/master/src/olympia/editors/helpers.py#L628 to be `dev_ver_url = self.addon.get_dev_url('versions')` (as now) when `self.addon.is_listed` is true and `dev_ver_url = reverse('devhub.addons.versions', args=[self.id])` otherwise.  This will likely break a number of tests which you'll need to fix too.

To to fully test things locally see the [Contribute ](https://wiki.mozilla.org/Add-ons/Contribute) link Andreas provided has general background on how to set-up a local instance on AMO, in particular https://wiki.mozilla.org/Add-ons/Contribute/Code#Contribute_code_to_AMO.

**Comment by kewisch** [comment]
@mattdrake as we haven't heard from you I'd like to check in and see how things are doing? If you need any help let us know!

**Comment by wagnerand** [comment]
If anyone wants to work on this issue, feel free to do so.

**Comment by eviljeff** [comment]
If someone does decide to work on this again, comment first because some of the previous comments on how to address the issue may be invalid now because we've changed the devhub upload flow a lot recently.

**Comment by harikishen** [comment]
I would like to take this up.

**Comment by eviljeff** [comment]
@harikishen great.  You need to change the `dev_ver_url` variable in `get_context_data` (https://github.com/mozilla/addons-server/blob/master/src/olympia/editors/helpers.py#L536) to be dev_ver_url = reverse('devhub.addons.versions', args=[self.id]) if the version channel is unlisted, and keep it as self.addon.get_dev_url('versions') otherwise.  Easiest place is to put it next to the existing channel if here: https://github.com/mozilla/addons-server/blob/master/src/olympia/editors/helpers.py#L551

This will likely break a number of tests which you'll need to fix too.

To to fully test things locally see the Contribute link Andreas provided has general background on how to set-up a local instance on AMO, in particular https://wiki.mozilla.org/Add-ons/Contribute/Code#Contribute_code_to_AMO.

**Comment by harikishen** [comment]
@eviljeff How do I verify whether the fix works ?

**Comment by eviljeff** [comment]
If you've set up a local instance of AMO then `make test`  http://addons-server.readthedocs.io/en/latest/topics/install/docker.html#running-common-commands

I expect one or more tests will fail, in which case you can you just fix it/them and that's enough.

**Comment by harikishen** [comment]
[This](https://pastebin.mozilla.org/9021759) is the result when I run the tests without changes.

**Comment by eviljeff** [comment]
`addon.is_listed` was removed, yes - that was one of the changes I mentioned. The `is_listed` property has been replaced with a per-version `channel` property.

You have a lot of broken tests, probably because AMO hasn't been set-up correctly.  Did you do all the commands in http://addons-server.readthedocs.io/en/latest/topics/install/docker.html#setting-up-the-containers ?  If you'd already downloaded it before then http://addons-server.readthedocs.io/en/latest/topics/install/docker.html#updating-your-containers mentions how to update everything.

**Comment by harikishen** [comment]
yea i followed the steps in both

**Comment by harikishen** [comment]
but the tests succeed when i run `make test_failed`
https://pastebin.mozilla.org/9021910

**Comment by harikishen** [comment]
@eviljeff ???

**Comment by harikishen** [comment]
This is the change i've made at [editors/helpers.py](https://github.com/mozilla/addons-server/blob/master/src/olympia/editors/helpers.py) 
https://pastebin.mozilla.org/9022424
L579-L583

No tests seem to break. Just let me know if there is something wrong.

**Comment by ValentinaPC** [comment]
Verified this onAMO-dev, stage and production and I was not able to reproduce it. The link redirection is made correctly.
@eviljeff : I feel that I am doing something wrong... can you give me a hand?
Thanks!

**Comment by eviljeff** [comment]
@ValentinaPC when a listed version is submitted the email should be as before, with a slug in the url.  When you submit an unlisted version the email sent to say the xpi is signed url should contain the numeric add-on id instead.

**Comment by ValentinaPC** [comment]
True. Thanks!

Verified this on AMO-dev FF53(Win 7).
The activity mail for unlisted version contains the URL with the numeric add-on id.
Postfix screenshot:
![2017-05-25_1508](https://cloud.githubusercontent.com/assets/15685960/26449991/e046bca8-415d-11e7-82f6-5ad5a6a34fd2.png)
