### ISSUE TITLE
Random 500 Errors in circle CI tests

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3415]
We seem to intermittently see errors as follows in the circle CI tests.

~~Could this be that the service isn't ready prior to running the test?~~

```
_________ ERROR at setup of test_there_are_ten_most_popular_extensions _________

request = <SubRequest '_verify_url' for <Function 'test_there_are_ten_most_popular_extensions'>>
base_url = 'http://127.0.0.1'

    @pytest.fixture(scope='session', autouse=True)
    def _verify_url(request, base_url):
        """Verifies the base URL"""
        verify = request.config.option.verify_base_url
        if base_url and verify:
            response = requests.get(base_url, timeout=10)
            if not response.status_code == requests.codes.ok:
                raise pytest.UsageError(
                    'Base URL failed verification!'
                    '\nURL: {0}, Response status code: {1.status_code}'
>                   '\nResponse headers: {1.headers}'.format(base_url, response))
E               UsageError: Base URL failed verification!
E               URL: http://127.0.0.1, Response status code: 500
E               Response headers: {'ETag': '"6e6be9f80c675e14d4f487c43dc5dd49"', 'Date': 'Mon, 05 Sep 2016 17:20:36 GMT', 'Vary': 'X-Mobile, User-Agent', 'x-content-type-options': 'nosniff', 'Content-Type': 'text/html', 'Server': 'nginx/1.9.9', 'X-Frame-Options': 'DENY', 'Transfer-Encoding': 'chunked', 'x-xss-protection': '1; mode=block', 'Connection': 'keep-alive'}
```

**Comment by muffinresearch** [comment]
Sounds like this might be a dependency issue at our end we're investigating.

**Comment by EnTeQuAk** [comment]
A few more details on that and there isn't any obvious solution imho, so the problem is that we have hardcoded the addons/addons-server:latest docker image in our circleci config. Now this will always be built with our current master branch, so that pull requests that touch our requirements files and introduce new dependencies fail because those requirements aren't in the master branch yet.

A temporary fix for me in the django 1.8 branch was to set the tag to "feature_2176-django-1.8", e.g "addons/addons-server:feature_2176-django-1.8" - you can find the tags in the builds section in dockerhub, https://hub.docker.com/r/addons/addons-server/builds/ - but you have to remember to revert that change before merging.

Another possible fix could be to let circleci build the actual image but I doubt that's useful since those tests already take quite some time and building the image takes even longer. I'm also not sure if this can be easily done, I guess it is but I don't know.

**Comment by muffinresearch** [comment]
A quick fix would be to add `make update_dep`s in https://github.com/mozilla/addons-server/blob/master/scripts/setup-docker.sh

**Comment by EnTeQuAk** [comment]
Indeed that would fix most of our problems 😃

**Comment by muffinresearch** [comment]
This fix didn't solve the problem

**Comment by EnTeQuAk** [comment]
https://github.com/mozilla/addons-server/pull/3421 might, or not, we'll see

**Comment by EnTeQuAk** [comment]
Closing this, given that we don't use CircleCI for anything except image builds anymore.
