### ISSUE TITLE
New version update submission flow for Listed and Unlisted

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3469]
Part of #3465

The add-on version update submission flow will have a look and feel more consistent with the new add-on submission flow. Also, at this point it will be possible to choose a different channel for new versions, which means `channel` will no longer be set based on `is_listed`. UX for this new flow is in mozilla/addons#192.

**Comment by eviljeff** [comment]
Three parts to the QA here:
1.  Check the _new addon_ upload flow still works as expected - this patch changes the code used for new addon upload but functionally should work the same.
2.  Check the (new) new _version_ upload flow is working - Enable waffle switch `***` and upload a new version via devhub using any of the usual links.  You will only be able to upload a listed version on a listed addon, and an unlisted version on a listed addon.
3. [Advanced level] mixed unlisted and listed versions.  (see next comment)

**Comment by eviljeff** [comment]
### Mixed Unlisted & Listed Versions
Optional QA for the 2016-11-17 push but it would be good to know sooner rather than later if the flow is broken at least.

**Don't try this on prod** as the rest of the site can't handle mixed unlisted and listed versions on the same add-on yet.  You will need to enable waffle switch `mixed-listed-unlisted`.  

The key differences are the upload flow contains a link under the channel description to change it (goes back to a distribution step).  If you upload an unlisted version on a listed add-on not a great deal different happens during the flow; if you upload a listed version on an unlisted add-on then the details step should appear like you see during new add-on submission to collect missing metadata.

Right now there isn't a way to identify the different channels of the versions anywhere, but #3470 will add this.

**Comment by ValentinaPC** [comment]
@eviljeff : at point 2, in your comment, you wanted to say unlisted version on _unlisted_ add-on , yes? Thanks!

**Comment by eviljeff** [comment]
@ValentinaPC yes, I did.  corrected.

**Comment by ValentinaPC** [comment]
This can be marked as verified fixed, because all above bugs were fixed and verified.
Extra QA was made on this part.
