### ISSUE TITLE
Signing API: Uploading versions violates semantics of the HTTP PUT method

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#3492]
According to http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#uploading-a-version, you have to use `PUT` method yet send a `multipart/form-data` payload. I believed in a documentation mistake originally so I checked the [source code](https://github.com/mozilla/addons-server/blob/4ea328124e279b4e682c9a33f559aea424709bec/src/olympia/signing/views.py#L98) - and it is really expecting a crazy request like that.

As it is, this should really be a `POST` request. If the goal was making client developers' lives easier then it should be a proper `PUT` request - with file contents as request payload, no special encoding.

**Comment by EnTeQuAk** [comment]
Can you elaborate on why this shouldn't be a `PUT` but rather a `POST`? I don't see any problems with using a PUT especially since this endpoint fits more the description of the `PUT` method than `POST` if I'm not mistaken.

Especially in combination of file uploads?

**Comment by palant** [comment]
From https://tools.ietf.org/html/rfc7231#section-4.3.4:

>   The fundamental difference between the POST and PUT methods is
>   highlighted by the different intent for the enclosed representation.
>   The target resource in a POST request is intended to handle the
>   enclosed representation according to the resource's own semantics,
>   whereas the enclosed representation in a PUT request is defined as
>   replacing the state of the target resource.

What this usually means: the request body is what should be stored there, no special semantics like multipart encoding.

**Comment by mstriemer** [comment]
Are you suggesting the user send the file with `Content-type: application/zip` and just dump the binary in the request data? That would seem reasonable.

I think we did it with form data so that we could accept additional details later, such as if the file is to be listed or unlisted or something else we haven't thought of.

The documentation gives an example of an endpoint that serves `text/html` and is given `image/jpg`:
```
   For example, if the target resource is configured to always have a
   Content-Type of "text/html" and the representation being PUT has a
   Content-Type of "image/jpeg", the origin server ought to do one of:

   a.  reconfigure the target resource to reflect the new media type;

   b.  transform the PUT representation to a format consistent with that
       of the resource before saving it as the new resource state; or,

   c.  reject the request with a 415 (Unsupported Media Type) response
       indicating that the target resource is limited to "text/html",
       perhaps including a link to a different resource that would be a
       suitable target for the new representation.
```

So it seems like we're currently doing (b) by transforming the PUT representation from `multipart/form-data` to `application/zip`. This might not be conventional but I'm not sure if it's strictly wrong.

**Comment by palant** [comment]
> Are you suggesting the user send the file with Content-type: application/zip and just dump the binary in the request data?

Yes, that's how `PUT` requests normally work (I'd definitely accept `application/x-xpinstall` as content type however).

> I think we did it with form data so that we could accept additional details later, such as if the file is to be listed or unlisted or something else we haven't thought of.

Then maybe it should be a regular `POST`? After all, using `PUT` also means that the data should be available under that URL (also explained in the RFC) - but that's not the case here.

> So it seems like we're currently doing (b) by transforming the PUT representation from multipart/form-data to application/zip.

Nope, that would only apply if you accepted `multipart/form-data` *in addition* to `application/zip`.

**Comment by mstriemer** [comment]
> Yes, that's how PUT requests normally work (I'd definitely accept application/x-xpinstall as content type however).

I definitely like the idea of this. It seems unlikely we'll need to specify additional parameters and I would prefer us to put extra stuff in the XPI itself.

> After all, using PUT also means that the data should be available under that URL (also explained in the RFC) - but that's not the case here.

I believe that is still our intention, we just haven't implemented the `GET` API yet since we haven't needed it. I would guess that we implement this for the new admin tools at some point and maybe for the new frontend.

> Nope, that would only apply if you accepted multipart/form-data in addition to application/zip.

I don't see anything in the documentation stating that you need to accept the same content-type `PUT` that you do on `GET`, but maybe I missed it.

The documentation mentions adding a new version and having it update other URLs. That sounds pretty nice actually. Something like `PUT /api/v3/addons/@my-addon/versions/latest/` would probably be a nicer API and I believe is already consistent to what we refer to as "latest" and "current". (You wouldn't be able to upload the "current" version since it may need to be verified firsts, at least for listed add-ons)

**Comment by kumar303** [comment]
In a triage meeting we decided not to fix this even though we acknowledge that our API is not up to spec. The problem with changing it is that we'd need to also patch [web-ext](https://github.com/mozilla/web-ext) and [sign-addon](https://github.com/mozilla/sign-addon/) as well as write a blog post so that all developers using our API know to change their existing scripts and applications. Thanks for taking the time to file an issue and sorry about the confusion this caused.
