### ISSUE TITLE
Use Greenkeeper for node dependencies

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#3500]
I know we chatted about "owning a change up the dependency tree" awhile back, but why not automate it instead? ^_^

Filing this for posterity, I'm gonna enable this soon.

**Comment by EnTeQuAk** [comment]
:+1:

**Comment by muffinresearch** [comment]
I like the idea of automation, but if we go this route we'll have to make sure that landing greenkeeper commits with updates to the linter is done carefully and the changes are logged with associated issues if the updates require testing by QA - since PRs by themselves are pretty much invisible. 

We can try it out though - it should at least help with increasing the visibilty of package updates. 

Possibly a reminder comment could by posted by a bot when a greenkeeper addons-linter PR is posted, to prompt for issue-linkage if testing of the new features is required?

**Comment by tofumatt** [comment]
Good point. That bot idea works for me. If it's a linter patch it will show
the change log and issues in the commit at least, so it should be easy to
automate (and until then have the developer manually figure out which issue
was fixed).

- tofumatt
