### ISSUE TITLE
Another file is temporary loaded after a .zip file is selected using about:debugging

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3523]
Steps to reproduce:
1. Load about:debugging page
2. Load a webextension that it's a .zip file (the .zip file MUST be located in a folder together with other files among which there is also a manifest.json file)

Expected results:
The .zip webextension is loaded. If .zip file format is not allowed an error message is displayed.

Actual results:
It seems that the .zip file is loaded (because no error message is displayed) but actually the manifest.json is.

Notes/Issues:
Verified on **FF50.0a1 (Build ID 20160915030417)** using Windows 7 x64.
Screenshot for this issue: 
![wrong_name](https://cloud.githubusercontent.com/assets/15685960/18553776/7555625a-7b6a-11e6-9b9c-336d815bb833.png)

**Comment by muffinresearch** [comment]
@ValentinaPC This would be better filed on bugzilla since this isn't related to the AMO server code.

Fwiw according the to docs the the about:debugging page loads extensions from a directory. See https://developer.mozilla.org/en-US/docs/Tools/about:debugging#Loading_a_temporary_add-on 

I think that implies the code for the extension is in a directory not a zip which might explain what you're seeing.

**Comment by ValentinaPC** [comment]
@muffinresearch : if in that directory there is a .**xpi** file and a manifest.json, and I click to load temporary the xpi file, that one is loaded and **not the manifest.json**. 

I've put this here, because about:debugging section was discussed here too (see @tofumatt 's comment from #2727 ).
I will move this to Bugzilla.

**Comment by ValentinaPC** [comment]
Closing in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1303266 .
