### ISSUE TITLE
Android add-on returns XML page at install

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3581]
Steps to reproduce:
1. Load details page for an incompatible with desktop android add-on (search tool) i.e. https://addons.mozilla.org/En-uS/android/addon/google-dictionary-53151/?src=search
2. Click "Download now" or "Download anyway"

Expected results:
File can be downloaded or a message, saying that it cannot be, is displayed.

Actual results:
A page containing XML is displayed.

Notes/Issues:
Verified on FF48(Win 7). Issue is reproducing all around AMO servers.
Screenshot for this issue: 
![androidaddon](https://cloud.githubusercontent.com/assets/15685960/18747753/92a56b8a-80d7-11e6-870b-d2fd60b83514.gif)

**Comment by ValentinaPC** [comment]
@tofumatt May be a regression from #3414 ?

**Comment by ValentinaPC** [comment]
Reproducing also on Android 6.0.1 using FF52.
Please see video:
![videotogif_2017 03 13_16 24 43](https://cloud.githubusercontent.com/assets/15685960/23858850/8a3be018-080a-11e7-8242-3268cd59d324.gif)

**Comment by muffinresearch** [comment]
@ValentinaPC On desktop it looks like it works correctly if you have the xpinstall permission set.

For mobile when xpinstall is enabled it still breaks because the opensearch install is being handled as if it's a regular add-on. This should have bugs filed in mozilla/addons-frontend since it looks to me like the only bugs are in the new mobile site.

Fwiw: install looks to start correctly for the old mobile site.

**Comment by ValentinaPC** [comment]
> @ValentinaPC On desktop it looks like it works correctly if you have the xpinstall permission set

Not sure I follow :( , `xpinstall permission` meaning?

**Comment by muffinresearch** [comment]
> Not sure I follow :( , xpinstall permission meaning?

@ValentinaPC the permision to allow the site to install add-ons.

**Comment by muffinresearch** [comment]
@ValentinaPC actually I think I confused myself because now I see XML all the time, I thought I got a search to install correctly earlier in nightly.

**Comment by muffinresearch** [comment]
Ah ok now I see what I did, it works for searches that aren't experimental or incompatible. E.g. https://addons-dev.allizom.org/en-US/firefox/addon/google-dictionary-53151/

**Comment by muffinresearch** [comment]
Xpinstall is not involved here, ignore that part (comments edited to reflect that).

**Comment by ValentinaPC** [comment]
Looking around this issue I discovered that:
- this is reproducible only for Android Search Engines i.e. any of: https://addons-dev.allizom.org/en-US/android/search-tools/ 
Please let me know if I should move this to `addons-frontend` or here will do it?

**Comment by muffinresearch** [comment]
@ValentinaPC I think there's multiple problems 

* On addons-server the messaging is unclear and it's falling through to a link to the fall (presumably due to incompatibility) which results in this fallback to open the link instead of prompting an opensearch install the normal way.
* On Mobile pages there's no functionality currently for installing opensearch plugins at all afaict. 
  - A workaround would be to go to the desktop site instead assuming it's a compatible search install.

**Comment by EnTeQuAk** [comment]
This will be fixed in addons-frontend and will be fixed there once desktop-pages will be implemented there. The buttons logic on addons-server is complicated enough that it doesn't make sense to invest the time, especially since it's more of an edge-case of someone arriving with an incompatible version.
