### ISSUE TITLE
Usage stats on listing page should show active users only.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3632]
Currently, the _users_ number on an add-on listing page counts all installs, regardless of the status. However, a Firefox user who disabled the add-on isn't really a user of the add-on. We should display _active_ (`userEnabled`) installs only.

@deadsquid thought this is a good idea, adding @jvillalobos.

**Comment by jvillalobos** [comment]
I agree. This has some public impact, since most numbers will drop noticeably. We will need to inform developers and the public about the change. We also use ADI for sorting in certain places, so we need to change that too. We might also need to change some of the text in the stats dashboard so developers understand which numbers we're using publicly.

**Comment by wagnerand** [comment]
> We will need to inform developers and the public about the change.

Would a blog post suffice?

> We also use ADI for sorting in certain places, so we need to change that too.

What exactly needs to be changed?

> We might also need to change some of the text in the stats dashboard so developers understand which numbers we're using publicly.

Are we currently saying anywhere what numbers we use on the listing page?

**Comment by jvillalobos** [comment]
> Would a blog post suffice?

Yes, but we also need to escalate to @deadsquid and possibly others, since usage counts are sometimes used for marketing.

> What exactly needs to be changed?

I don't know, we should check how `average_daily_users` is being used in code. I suppose the idea would be to reuse that field and just assign it the new value, so hopefully things will continue to work.

We should also check the impact it could have on the add-on statistics dashboard and the [global statistics dashboard](https://addons.mozilla.org/statistics/).

> Are we currently saying anywhere what numbers we use on the listing page?

The listing page says "X users", and if there's a public dashboard, that links to the stats. The first page shown in the dashboard has ADI and downloads. So, it would be confusing if the numbers in the dashboard are much larger than the ones in the listing page. We could either try to clarify the discrepancy, or change the number in the main dashboard to use only enabled installs (which might also need some explanation in the page).

**Comment by wagnerand** [comment]
> Yes, but we also need to escalate to @deadsquid and possibly others, since usage counts are sometimes used for marketing.

He is aware and I think we should ping him again when this gets closer to being landed.

> I don't know, we should check how average_daily_users is being used in code. I suppose the idea would be to reuse that field and just assign it the new value, so hopefully things will continue to work.

That's exactly the plan :)

> The listing page says "X users", and if there's a public dashboard, that links to the stats. The first page shown in the dashboard has ADI and downloads. So, it would be confusing if the numbers in the dashboard are much larger than the ones in the listing page. We could either try to clarify the discrepancy, or change the number in the main dashboard to use only enabled installs (which might also need some explanation in the page).

If I remember the code correctly, the stats overview page also uses `average_daily_users`, so the numbers should be consistent.

**Comment by jvillalobos** [comment]
Since we use these stats to rank add-ons and these rankings are used both internally and externally, I think we should consider fixing this soon. More accurate rankings should help prioritize add-ons for the e10s and WebExtensions transitions.

Taking the public [AdBlock Plus stats dashboard](https://addons.mozilla.org/addon/adblock-plus/statistics/usage/status/?last=30) as an example, I see these issues with the current ADI count:
* We over-report usage because we count disabled installs (the original reason for which this was reported).
* We under-report usage because we're averaging user counts for a long amount of time.
* We under-report usage because we're not accounting for weekend drops.

With that in mind, I'm thinking we should calculate usage as an average of the enabled installs for the past 10 or so Wednesdays. I'm suggesting Wednesdays because they tend to show the most usage, but any weekday would work similarly. And I'm suggesting 10 sample days so the stats reflect recent history and don't vary wildly due to data flukes. /cc @benmiroglio to check if this makes sense or should be changed.

**Comment by benmiroglio** [comment]
I'd recommend using a 6-day window--so for a given date, take the average of that date + the past 6 days. This ensures that you use every weekday in the calculation once, making the calculation unbiased for any specific weekday.

Using the last 10 Wednesdays is essentially a 2.5 month window--meaning that any changes in usage will take a long time to surface. It is also biased since Wednesday's tend to show the most usage. 

I think a 6-day window would give us (and developers) the most representative/relevant number.

**Comment by jvillalobos** [comment]
Sounds good to me, and much simpler to implement.

**Comment by jvillalobos** [comment]
Let's increase the window to 13 days. Sometimes we've had stats collection failures that have taken 3-4 days to be corrected, which would have a huge impact on the smaller window.

**Comment by muffinresearch** [comment]
Assigned to @EnTeQuAk to get an idea of what needs doing to implement this.

**Comment by EnTeQuAk** [comment]
So, I started working on this, it's a bit of work to get the calculation right and properly stored / updated everywhere and think about a migration scenario but from what I see we do have all the relevant data in our database already so the implementation won't require touching our stats-pipeline.

This will still take a bit more time to implement since I am planning to update our local stats generation a bit so that it's easier to work on anything stats-related in the future. Going to file separate issues for that and use this issue as a meta-issue.

**Comment by EnTeQuAk** [comment]
cc @jvillalobos and @diox that the average_daily_users count is about to be changed which is in use for our auto-approval process. I should have numbers available soon I hope, latest end of this week to see what changes are required.

**Comment by EnTeQuAk** [comment]
So, currently we are calculating our average daily users over 7 (today + past 6 days) days for all installations.

We are now changing this to a window of 13 days (today + past 12 days) for all `userEnable`'d installations.

Just so that we summarize what we decided in the comments above.

**Comment by EnTeQuAk** [comment]
https://github.com/mozilla/addons-server/issues/5632 is now open for review and planned to land next week or should this be delayed because some preparations are needed (statistics, blog post etc?) @wagnerand @jvillalobos?

**Comment by jvillalobos** [comment]
I just need a heads up so I can give it a look on dev or stage, and also run some stats on prod so we can compare the before and after. The blog post doesn't take long to write and publish.

**Comment by EnTeQuAk** [comment]
perfect, then I'm going to merge this and run the commands on -dev once I'm back online tomorrow morning so that you can check some stats on -dev at least. I'll copy down a few stats from, say ublock or so before to one random add-on on -dev so that we can verify this a bit better.
