### ISSUE TITLE
[RTL]Number of users in add-ons details pages is not correctly aligned

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3649]
Steps to reproduce:
1.Open any add-on to its details page in Arabic language (https://addons-dev.allizom.org/ar/android/addon/priceblink/?src=hp-dl-featured)
2.Observe number of users in top left side

Expected results:
Number of users section is correctly aligned with ratings stars and user reviews

Actual results:
Number of users section is not correctly aligned 

Please see a photo of the issue: 
![users](https://cloud.githubusercontent.com/assets/1583842/18994066/c396d186-872e-11e6-884e-55ca5bee2949.png)

**Comment by eviljeff** [comment]
mentor @tofumatt
If this is your first bug please look at https://wiki.mozilla.org/Add-ons/Contribute/Code

**Comment by tsl143** [comment]
I think I can do this !

**Comment by tofumatt** [comment]
@tsl143 Go for it, I'll review the PR when it's ready.

**Comment by tsl143** [comment]
sure

**Comment by tsl143** [comment]
Unable to reproduce.
![screenshot from 2016-10-06 08 13 22](https://cloud.githubusercontent.com/assets/5318732/19138783/d483caa4-8b9c-11e6-8608-5076ac3b7f9e.png)

**Comment by vcarciu** [comment]
Strange ,this is not reproducible on Nightly , but it is still reproducible on Firefox Release

**Comment by tsl143** [comment]
I am using Ubuntu 14.04/Firefox 49 and it isn't reproducible.

**Comment by vcarciu** [comment]
@tsl143 - All our team reproduced this issue , with the condition of being logged in. I can see in your screenshot that you are logged in too, so I don't understand why this is not reproducible for you.

Can you please try on a new profile and maybe with another user?

Thanks

**Comment by tsl143** [comment]
I dont know what the problem is, but I tried on following systems (with new profiles)
Ubuntu 14.04/ Firefox 49
Ubuntu 14.04/ Firefox 52
Mac OS/ Firefox 49

Everywhere I am unable to reproduce it :(

Can you help me with some steps, or some environment where I can reproduce this?

![screenshot from 2016-10-11 12 06 14](https://cloud.githubusercontent.com/assets/5318732/19260963/aac9d538-8fab-11e6-8fab-112dfb1212c5.png)

**Comment by atiqueahmedziad** [comment]
@tofumatt number of users is not correctly reproducible due to [this image](https://github.com/mozilla/addons-server/blob/master/static/img/impala/stats.png) is hidden (also hidden is ltr). Should this image be display? or should we remove the image?
### Screenshot
<img width="960" alt="stats" src="https://cloud.githubusercontent.com/assets/8364578/21964893/a07b3ed6-db7e-11e6-8e7a-c9dbfd370294.png">

**Comment by atiqueahmedziad** [comment]
@tofumatt number of users is not correctly aligned due to [this image](https://github.com/mozilla/addons-server/blob/master/static/img/impala/stats.png) is hidden (also hidden is ltr). Should this image be display? or should we remove the image?
### Screenshot
<img width="960" alt="stats" src="https://cloud.githubusercontent.com/assets/8364578/21964893/a07b3ed6-db7e-11e6-8e7a-c9dbfd370294.png">

**Comment by tofumatt** [comment]
Oddly I get an ISE on the dev site for that address, not sure what's up but I'll check the page again once it's working!

**Comment by tsl143** [comment]
Hi,
Just rechecked this issue (got docker running up again on my machine)
So what I find is there are different codes at `addons-dev.allizom.org` and `addons.mozilla.org`.
The code at production has an `anchor` element(which contains an image) in `.daily-users` where as dev and local setup has direct text.

**Comment by eviljeff** [comment]
@tsl143 can you provide exact urls?

**Comment by tsl143** [comment]
https://addons.mozilla.org/ar/firefox/addon/privacy-badger17/?src=hp-btn-promo
<img width="1099" alt="screen shot 2017-07-20 at 4 38 47 pm" src="https://user-images.githubusercontent.com/5318732/28414572-f31bb6d4-6d69-11e7-9312-c2c31979bfae.png">


https://addons-dev.allizom.org/ar/android/addon/priceblink/?src=hp-dl-featured
<img width="1186" alt="screen shot 2017-07-20 at 4 38 38 pm" src="https://user-images.githubusercontent.com/5318732/28414579-fba302a8-6d69-11e7-850c-0ca6f5845d7d.png">

**Comment by eviljeff** [comment]
one of the add-ons has chosen to have their statistics dashboard publicly viewable, the other hasn't.

**Comment by tsl143** [comment]
Ohhh,
in that case the background image is overrided by 
<img width="347" alt="screen shot 2017-07-20 at 4 42 45 pm" src="https://user-images.githubusercontent.com/5318732/28414701-842f3880-6d6a-11e7-8bc6-d1e5eede615a.png">

**Comment by tsl143** [comment]
Are we planning to remove the image?

**Comment by eviljeff** [comment]
I think that image got removed during the style refresh last year so all references to it can go (and you can delete the image file in the fix)

**Comment by tsl143** [comment]
@eviljeff / @EnTeQuAk 
Can anyone please review this ? 
:)
