### ISSUE TITLE
API to return list of all category name/slugs

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#3676]
The API docs for http://addons-server.readthedocs.io/en/latest/topics/api/categories.html helpfully list all the categories for different app/add-on type combos, but in building out https://github.com/mozilla/addons-frontend/issues/1183 I realised there's no API to get all categories. It would be handy to have one so:

1. we have a single source of truth
2. we can request localised category names from the server rather than adding them to the frontend's translations.

**Comment by diox** [comment]
Ideally we'd generate a json export from the [static list we have](https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/categories.py#L36), and have the frontend consume that directly, adding that in the frontend bundle instead of calling an API. We've discussed that in the past but haven't built that yet.

**Comment by EnTeQuAk** [comment]
We could make that an actual API, that doesn't add any real overhead and allows 3rd parties to query it too. We could implement it in a way though that it can be downloaded by `addons-frontend` in a build-step somehow but imho that's premature optimization.

**Comment by tofumatt** [comment]
Yeah, adding it into the front-end to optimise could be a cool future thing
but I don’t think needed, and there’s no harm in an API anyway.
