### ISSUE TITLE
Layout issues for collections with description on multiples lines

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3681]
STR:
1. Sign in to AMO-dev 
2. Go to Collection homepage and click the "Create a Collection" button https://addons-dev.allizom.org/en-US/firefox/collections/
3. Complete all mandatory fields and enter a description on multiple lines
4. Save the changes 
5. Go to collection details page and observe the description
6. Go to collections sorting pages and observe the description

ER:
Description from step 6 has the same form as the one from step 5.

AR:
The description is causing layout issues because is not compacted. 

Notes/Issues:
Verified on FF49(Win 7). Issue is reproducing on all AMO servers.
Video for this issue:
![coll](https://cloud.githubusercontent.com/assets/15685960/19144611/4f0afff2-8bb3-11e6-92c1-36ce8eeeb206.gif)

**Comment by wagnerand** [comment]
Mentor: @wagnerand

We want make the collections sorting page look like the details page. That means, newlines should be replaced by spaces.

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by ValentinaPC** [comment]
This is happening for add-ons description too: in add-on details page a multiple-line description is not compacted - and look bad. 
This thing is not happening in "Edit Listing" page.
Please see the screenshot: 
![addons_description](https://cloud.githubusercontent.com/assets/15685960/19528582/43efa4e2-9635-11e6-8bf8-eee4c9f99fd4.png)

**Comment by jvillalobos** [comment]
That's a separate bug, and I don't know if we would want to fix this one, since developers have much more control over formatting the descriptions.

**Comment by ValentinaPC** [comment]
So...the first one you will not fix it or the one from my second comment? :smile:

**Comment by jvillalobos** [comment]
Heh, sorry for the confusing sentence. We want to fix this issue, in regards to collections, but probably won't fix it for listing descriptions.

**Comment by replaceafill** [comment]
I'd like to work on this. The issue seems to come from the nl2br filter being used in the [collection_listing_items.html](https://github.com/mozilla/addons-server/blob/master/src/olympia/bandwagon/templates/bandwagon/impala/collection_listing_items.html#L12) template for collections sorting pages and not for the collection details page in the [collection_detail.html](https://github.com/mozilla/addons-server/blob/master/src/olympia/bandwagon/templates/bandwagon/collection_detail.html#L58) template.

The [impala_collection_listing_items](https://github.com/mozilla/addons-server/blob/master/src/olympia/bandwagon/helpers.py#L23) helper seems to be used just in the [collection_listing](https://github.com/mozilla/addons-server/blob/master/src/olympia/bandwagon/views.py#L142) view so is it safe just remove the filter?

**Comment by jvillalobos** [comment]
@wagnerand may not be able to respond these days, so forwarding ping to @muffinresearch

**Comment by muffinresearch** [comment]
@ValentinaPC Do we actually have live descriptions that are looking problematic? 

Otherwise this seems to be an edge case and therefore very low priority especially in light of the upcoming work in q1/q2 to replace the frontend of the user-facing pages.

**Comment by ValentinaPC** [comment]
Nope. I did not see any live case.

**Comment by wagnerand** [comment]
@replaceafill are you still working on this issue? We think it's quite an edge-case and there might be better issues to work on. Maybe you want to have a look at one of the other good first bugs?

**Comment by replaceafill** [comment]
@wagnerand No, I'm not working on it anymore. I understood it wasn't necessary.

**Comment by wagnerand** [comment]
@replaceafill Ok, thank you for letting us know. We are closing this issue and encourage you to pick another good first bug to work on.
