### ISSUE TITLE
addusertogroup command no longer works; error: unrecognized arguments

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#3692]
### Describe the problem and steps to reproduce it:
- I initialized docker from scratch
- I registered an account via Firefox Accounts with `foo@place.com` (for example)
- I ran this to make myself an admin:

```
docker-compose run web python manage.py addusertogroup foo@place.com 1
```
### What happened?

```
manage.py addusertogroup: error: unrecognized arguments: foo@place.com 1
```
### What did you expect to happen?

It used to work 🍤 
### Anything else we should know?

I couldn't spot anything obvious. Maybe a recent Django upgrade broke this?

**Comment by eviljeff** [comment]
Does `python manage.py createsuperuser` work?  (afaik that's the recommended way of adding an admin)

**Comment by eviljeff** [comment]
Although, you may be right about a Django update breaking it- https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/#module-django.core.management - I'm not sure why we've not seem more breakage in the other commands tbh.

**Comment by kumar303** [comment]
Interesting. I only took a quick look but maybe we simply need to define `add_arguments()` in https://github.com/mozilla/addons-server/blob/master/src/olympia/zadmin/management/commands/addusertogroup.py

**Comment by EnTeQuAk** [comment]
I believe we don't see more breakage because most of the other commands don't accept arguments from the shell.

But I agree with @eviljeff that imho `createsuperuser` is the preferred way to make yourself a superuser which fails gloriously if the user already exists though. So I think there's room for both, especially if you just want to test some special group permission stuff.
