### ISSUE TITLE
Ex-editors get an email about the review they did but can't reply

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3727]
#3726

If an editor is on a review thread and there is a new message on it then the editor gets an email.  But if the editor is no-longer an editor they are blocked from replying, but still get the email.

**Comment by eviljeff** [comment]
@jvillalobos can you comment on desired behaviour here.

**Comment by jvillalobos** [comment]
They shouldn't be emailed when they are no longer in the reviewers group.

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed in FF52.0a1 (Wind7) in amo-dev.

**Before:** 
After a reply an email is sent to the reviewer.

Reply:
![devreply1](https://cloud.githubusercontent.com/assets/15885467/19687806/a92f260e-9acf-11e6-9743-09b40b43c2a1.png)

Fake Email:
![editor1](https://cloud.githubusercontent.com/assets/15885467/19687822/b62f28cc-9acf-11e6-9921-96697148834f.png)

**After:**
After a reply there is no email sent to the ex-reviewer.

Reply:
![devreply2](https://cloud.githubusercontent.com/assets/15885467/19687837/c739c4ce-9acf-11e6-99d8-3f98179bab04.png)

Fake Email:
![exeditor](https://cloud.githubusercontent.com/assets/15885467/19687846/d051796c-9acf-11e6-9e03-743f41e5755f.png)
