### ISSUE TITLE
Promo-banner navigation animates back to start (Bugzilla issue)

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3737]
Reference issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1229246

@designakt : Are you talking about this: 
![promobanner-nav](https://cloud.githubusercontent.com/assets/15685960/19305813/649e025c-907b-11e6-9ed4-4350cff80fbb.gif)

Because if you do, this is still happening and it is very annoying.
I've created a github correspondent to help.

**Comment by muffinresearch** [comment]
I don't think this is worth spending time on to get fixed ahead of replacing the front-end. It's not a bug per se - rewinding used to be a common pattern in carousels (although I agree continuous ones are definitely nicer).

If we have a carousel in the new desktop frontend then let's focus on making that do what we need it to instead, since this code will eventually get deprecated.
