### ISSUE TITLE
An admin is not redirected correctly at sign in while trying to access an "Admin Tools" page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3765]
Steps to reproduce:
1. Load an admin page on a profile you are not logged in with your admin account i.e. https://addons-dev.allizom.org/en-US/admin/models/
2. Enter you credentials for the admin account and sign in

Expected results:
User is redirected to the page he requested in the URL.

Actual results:
A 403 page is displayed.

Notes/Issues:
URL is not correctly changed after log in.
Verified on AMO-dev FF49(Win 7).
Screenshot for this issue:
![403](https://cloud.githubusercontent.com/assets/15685960/19388668/7a1157ce-9229-11e6-9889-97ee69b9088d.png)

**Comment by diox** [comment]
This is annoying but not worth fixing, IMHO. Something to consider with the new admin tools as we rewrite them.

**Comment by ValentinaPC** [comment]
This is also happening from the new Admin Tools page: https://addons-internal.dev.mozaws.net/en-US/admin/.
Video:
![admin](https://user-images.githubusercontent.com/15685960/28777816-5495ba4c-7605-11e7-8ad5-cb3272733249.gif)

Maybe now... worth fixing?

**Comment by ioanarusiczki** [comment]
@eviljeff Looks like the login/register is not working on dev right now (admin tools, dev tools or code manger). 

![logindev](https://user-images.githubusercontent.com/33448286/71513120-c220da00-28a1-11ea-9eed-aaf65325f124.gif)

I filed an issue here https://github.com/mozilla/fxa/issues/3764

**Comment by ioanarusiczki** [comment]
@eviljeff 
Right now the behavior is:
- I don't receive the error when I try to login to https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/ but it redirects to the general page https://addons-internal.dev.mozaws.net/en-US/admin/models/ (which is applicable to all other reports). 

![models page](https://user-images.githubusercontent.com/33448286/71903075-f59a1900-316b-11ea-86da-10e79ebd59ab.gif)

- I receive every time a 500 error when I log out because the URL is https://addons-internal.dev.mozaws.net/en-US/firefox/ instead of https://addons-internal.dev.mozaws.net/en-US/admin/ 

![logout](https://user-images.githubusercontent.com/33448286/71902549-fb432f00-316a-11ea-88ed-85d14251eff3.gif)

Should I reopen or file separate issues?

**Comment by eviljeff** [comment]
> I don't receive the error when I try to login to https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/ but it redirects to the general page https://addons-internal.dev.mozaws.net/en-US/admin/models/ (which is applicable to all other reports).

That's normal behaviour with django admin login.

> I receive every time a 500 error when I log out because the URL is https://addons-internal.dev.mozaws.net/en-US/firefox/ instead of https://addons-internal.dev.mozaws.net/en-US/admin/

The issue didn't mention logging out so I wasn't aware (locally there isn't a separate admin instance so we don't get the error during development).  If you think it's worth filing you can file an issue.  IMO though, it's lower priority than this issue (which was already borderline wontfix)
