### ISSUE TITLE
Signing an addon with --id auto-generates a GUID when it shouldn't

### ISSUE THREAD

**Issue by shubheksha** [mozilla/addons-server#3801]
### Describe the problem and steps to reproduce it:

The addons-server is auto-generating a GUID even when an ID is passed to it by a user while signing a web extension.

To reproduce this issue, I ran [web-ext sign --id custom-id@example](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign) and placed a couple of log statements before and after the [`sign()`](https://github.com/mozilla/web-ext/blob/master/src/cmd/sign.js#L50) function in web-ext. The value of `id` is being passed currently to the function. However `signingResult.id` has an auto-generated GUID. I expected `custom-id@example`.

After this I tried to inspect sign-addon by placing log statements in [`amo-client.js`](https://github.com/mozilla/sign-addon/blob/master/src/amo-client.js). However, here the `id` is being passed correctly to the addons-sever which was affirmed by logging the value of [`guid`](https://github.com/mozilla/sign-addon/blob/master/src/amo-client.js#L92).
### What happened?

In https://github.com/mozilla/web-ext/issues/479, an argument is passed to the `--id` option on the command line, but despite that, an auto-generated GUID is being returned as an ID.
### What did you expect to happen?

As described in https://github.com/mozilla/web-ext/issues/479, the expected behavior is that the GUID should not be generated in case a user specified an `--id` option on the commandline. The ID passed and not shouldn't be recorded on the AMO website and the `.web-extension-id` file. 
### Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
There are a few things that are unclear to make this easier to debug. Is this an already existing add-on you're trying to upload a new version for or is that a new add-on? Do you have an id in your `manifest.json`?

**Comment by shubheksha** [comment]
There is no id in the `manifest.json`. An `--id` option is being passed with the `web-ext sign` command.
The behavior I saw was: 
When I try to sign an add-on with my add-on credentials, say, apply-css, it is generating a GUID in the first go. If I try to do it again, without bumping up the version or modifying the add-on in anyway, a new GUID was generated and I could see two copies of the add-on in my account with different IDs despite passing the same `--id` option while signing.

**Comment by EnTeQuAk** [comment]
interesting, that helps a lot. Thanks!

**Comment by kumar303** [comment]
The intention of `web-ext sign --id custom-id@example` is to 1) bypass an ID in `manifest.json` and 2) bypass the ID auto-generation that the API server would otherwise be doing.

**Comment by kumar303** [comment]
@muffinresearch is this a bug someone could grab soon? It's a `web-ext` blocker.

**Comment by muffinresearch** [comment]
@diox hi, would you have some time to take a look at this?

**Comment by diox** [comment]
I'll take a look next week.

**Comment by diox** [comment]
Found the issue, working on a fix. For historical purposes:

The API was never designed for this use-case. The only way to pass a guid to the API is to call ` PUT /api/v3/addons/[string:addon-id]/versions/[string:version]/`, which is meant to create a new version of an existing add-on, not to create one from scratch. 

The fact that it does not return an error is kind of an accident: instead of creating a version, it falls back to creating the add-on because none is found, but by then forgets the id that was passed since it was never meant to be used in this scenario.

**Comment by diox** [comment]
> The intention of web-ext sign --id custom-id@example is to 1) bypass an ID in manifest.json and 2) bypass the ID auto-generation that the API server would otherwise be doing.

@kumar303  I have no problem with 2) but I find 1) a possible source of confusion. What would be the use-case ? It seems particularly weird to have a package with a specific guid set inside and have it signed with a different one.

**Comment by kumar303** [comment]
Actually, I was wrong about use case 1, you cannot do `web-ext sign --id=...` if the manifest already declares an ID. You will see [this error](https://github.com/mozilla/web-ext/blob/master/src/cmd/sign.js#L78-L79).

The number 2 use case is the important one. We are encouraging developers to *not* declare an ID in their manifest because it's no longer required by Firefox and this makes their extension more portable across platforms. By default, `web-ext` will save a hidden file containing an ID after the first time the AMO server auto-generates one (for re-use in subsequent `web-ext` commands). However, there are some team scenarios and / or recovery cases where you may not have that file which is why we need to override AMO's auto-generated ID with a custom one declared via `--id`.

**Comment by kumar303** [comment]
@diox thanks for digging in! I'll test it on dev when it lands
