### ISSUE TITLE
Blocklisting is not working in stage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3807]
Steps to reproduce:
1. Submit an add-on in AMO-stage i.e.  https://addons.allizom.org/en-US/developers/addon/sev1-window/edit
2. Create a blocklist item in stage for that add-on i.e. https://addons.allizom.org/en-US/admin/models/blocklist/blocklistitem/835/ 
3. Follow the steps from https://wiki.mozilla.org/Blocklisting/Testing#Testing_Staged_Blocklist and blocklist the add-on from step 1.

Expected results:
The add-on cannot be installed for severity 3 and can be installed but is disabled for severity 1.

Actual results:
The add-on is installed. The blocklist item is not listed in the blocklist.xml file from the profile folder.

Notes/Issues:
Verified on Nightly 52.0a1 19.10.2016 in AMO-stage.
Screenshots for this issue: 
![devhub](https://cloud.githubusercontent.com/assets/15685960/19523604/ae6dfe2a-9623-11e6-8318-784e95856abb.png)
![blocklistitem](https://cloud.githubusercontent.com/assets/15685960/19523792/462b2d0a-9624-11e6-8546-67f64ed353ed.png)
![blocklistdetails](https://cloud.githubusercontent.com/assets/15685960/19523798/4a2eea40-9624-11e6-86d3-cf1b42cf87ee.png)
![blocklistxml](https://cloud.githubusercontent.com/assets/15685960/19523800/4daaa858-9624-11e6-8ea1-ad3951b6c199.png)

**Comment by muffinresearch** [comment]
From irc jason mentioned the kinto sync is failing.

**Comment by jasonthomas** [comment]
@Natim I am seeing the following traceback for the json2kinto lambda job on stage: https://gist.githubusercontent.com/jasonthomas/c52c658b424d3c67d795bb430dfff1fa/raw/12a9478150ce9d3ff79c1f19afb38487a7496eaa/gistfile1.txt

leplatrem mentioned on irc "hum, we'll have to change the JSON schema then"

**Comment by Natim** [comment]
If `os` is not mandatory we can change the schema to make it optional.

**Comment by Natim** [comment]
I checked the JSON schema file and "os" is required only for gfx blocklist.

https://github.com/mozilla-services/amo-blocklist-ui/blob/master/amo-blocklist.json

**Comment by Natim** [comment]
After investigation, the problem was with this entry: https://addons.allizom.org/en-US/admin/models/blocklist/blocklistdetail/1239/

OS is mandatory for Gfx, also `Feature` is now check to be valid. And `DIRECT_3D` is not a valid `Feature`. Here are thevalid values: https://github.com/mozilla-services/amo-blocklist-ui/blob/master/amo-blocklist.json#L414-L432

**Comment by ValentinaPC** [comment]
@Natim : A wrong gfx blocklist can influence an add-on not to be blocked?

**Comment by Natim** [comment]
The answer is yes because we have one XML file for all the blocklist. And if one entry fails, the XML verifier will fail to validate the file.
However, we could decide to import all the valid entries and just error on invalid ones.
But you are right currently this is not the case. The importer will fail on first error.

**Comment by leplatrem** [comment]
> Here are the valid values: https://github.com/mozilla-services/amo-blocklist-ui/blob/master/amo-blocklist.json#L414-L432

There are based on this list in Gecko source: https://dxr.mozilla.org/mozilla-central/rev/f40960c63bfac865d510ec9da42eeed74c384082/widget/GfxInfoBase.cpp#308-351

**Comment by Natim** [comment]
This can be closed.
