### ISSUE TITLE
Let's add "Editor Review" and "Admin Manager" new options in Manage My Submission page under More

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3860]
Steps to reproduce:
1. Load Manage My Submissions page in AMO-dev https://addons-dev.allizom.org/en-US/developers/addons
2. Go to any available add-on and click "More"

Expected results:
The new options added in Edit Information page "Editor Review" and "Admin Manager" are listed.

Actual results:
The options are not listed.

Notes/Issues:
Verified on FF49(Win 7). Issue is reproducing on AMO-dev.
Screenshot for this issue:
![managemysubm](https://cloud.githubusercontent.com/assets/15685960/19684280/12737a4a-9abf-11e6-8f8e-1b0f911f5d1f.png)

Relates to #3782

**Comment by wagnerand** [comment]
I don't think we need that.

@jvillalobos.

**Comment by ValentinaPC** [comment]
All the other options are available in Manage My Submissions page also. I've log this for consistency, but of course, your choice.

**Comment by jvillalobos** [comment]
"Manage My Submissions" is for your own add-ons, so an admin would rarely need those options in that context. Reviewers can't open review pages for their own add-ons, so that link wouldn't generally work.

This issue makes total sense from a consistency perspective, but I agree that we don't need to fix it.
