### ISSUE TITLE
Bad performance for most reviewer pages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3864]
STR:
1) Open a [review queue page](https://addons.mozilla.org/editors/queue/new).
2) Open any of the review pages linked from there.

Observed:
All review pages are taking lots of time to load.

The review queues aren't doing very well these days and this issue is amplifying the problem. It looks like it started since last week's push, so it's probably a regression.

CC @wagnerand @eviljeff

**Comment by eviljeff** [comment]
@diox for his input

**Comment by diox** [comment]
Looking at the slow queries log I can definitely confirm it's because of the removal of the `latest_version` field. 7e8c249aa7e6530278eacb8c72caa0ecfbc81542 and 364a5eeca2bcf1c1f244b4e478f8020ab1ef8cdb altered the query to cope with the removal of the field and it's causing MySQL to evaluate a bunch of additional rows. The query was greedy before but that made it worse.

This is affecting all reviewer pages because they all load the count for each queue, and the query to get each count is simply a `SELECT COUNT(*) FROM ({the giant annoying query})` :(

**Comment by diox** [comment]
Thinking out loud, here are the alternatives:

1. Keep `addons.latest_version`, making it point to the latest listed version. This solves the listed reviewer queues query but then we have a problem for the unlisted one (and potential future channels) so we'd have to add a field for each channel.
2. Don't try to make everything in a single query, fetch `latest_version` separately for each row.
3. Have a `latest_for_channel` boolean property in `versions`, updated like `latest_version` is at the moment, and `JOIN` on that field in the giant query.

It'd be also useful to stop making the `COUNT(*)` on the giant query. The code @eviljeff ported from Marketplace in #3834 to get the position of the add-on in the queue does avoid it, but unfortunately the totals don't match exactly the current queues - the difference is acceptable in devhub but would be jarring in editor tools.

**Comment by JustOff** [comment]
Please pay attention that this problem affects not only reviewers, but [regular developers logged in @ DevHub too](https://discourse.mozilla-community.org/t/amo-devhub-problems/11711).

**Comment by diox** [comment]
#3766 already solves the problem for regular developers, that's what I'm talking about at the end of my last comment - we just haven't pushed that to production yet.

**Comment by diox** [comment]
Looked at this deeper and found a simpler solution. As @eviljeff pointed out, filtering on the file status should already fetch us the latest version, since all developer actions that could break that are supposed to update the file status.

A few add-ons are in weird state because they have been modified manually, but we should be able to fix those separately.

**Comment by ValentinaPC** [comment]
I've checked the functionality around Editor Tools pages and things seems to move/load faster on AMO-stage using FF49.0.2 (Win 7).
Not being able to check in -dev, because of the "Internal Server Error" message while accessing https://addons-dev.allizom.org/ .
Please let me know if something else needs to be checked here.

**Comment by wagnerand** [comment]
Several reviewers confirmed that performance is back to normal if not even better than before.
