### ISSUE TITLE
Old API page

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#3910]
@mstriemer Please redirect https://services.addons.mozilla.org/en-US/firefox/api/1.5/addon/noscript to https://addons.mozilla.org/api/v3/addons/addon/noscript/ or remove it.

I found the old link in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Add-ons_manager_API

At least put the new API link in top of the old page if you want to keep it.

**Comment by muffinresearch** [comment]
@davidhedlund Thanks for filing. 

I don't think it will make sense to redirect one versioned API endpoint to another since they're different. 

We'll need to know what's currently consuming this data and from there work out the next steps.

We should look at moving https://developer.mozilla.org/en-US/Add-ons/AMO/Add-ons_manager_API to readthedocs assuming there's a good reason to keep this API around along with relevant deprecation notices if we're eventually going to remove it.

**Comment by mstriemer** [comment]
It looks like @diox did some digging in the past in #1721 and the 1.5 API was used by Firefox. Because of that I'm guessing we'll want to keep it around until traffic dies down (I'm guessing we have this data somewhere?).

I'd say it's fine to keep the docs on MDN since this was a Firefox API and that's where you find Firefox documentation. We should probably add a note to the top of the page saying it is deprecated and link to v3 through. Perhaps we could provide a link to MDN from RTD if we'd like but since I'd say this is deprecated it might not worth it.

**Comment by mstriemer** [comment]
I'm also assuming that the update to the disco pane removed any usage of this in Firefox but that might not be the case...

**Comment by diox** [comment]
I guess this might still be used despite the dico pane update since about:addons can still search on AMO.

**Comment by andymckay** [comment]
It's still used by Firefox for the search and Thunderbird, SeaMonkey and so on for their discovery panes. Since MDN is just a wiki, I just changed the MDN docs to point out that we should probably call this API deprecated and point to the new API.

https://developer.mozilla.org/en-US/Add-ons/AMO/Add-ons_manager_API

**Comment by cosminbadescuSV** [comment]
The MDN docs have been updated accordingly with the deprecated status for the old API  and with a link for the new API  "new JSON API" as presented in the video: 
![deprecated](https://cloud.githubusercontent.com/assets/15885467/19961685/951f580c-a1bc-11e6-811d-e33b6c973c0a.gif)

**Comment by davidhedlund** [comment]
@cosminbadescuSV Thanks.
