### ISSUE TITLE
Stage Disco Pane is magnified

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3912]
Steps to reproduce:
1. Load FF 49.0.2 using a clean profile (or not)
2. Set disco pane pref extensions.webservice.discoverURL from about:config to load -stage (https://discovery.addons.allizom.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE% )
3. Load about:addons

Expected results:
There are no display or layout issues.

Actual results:
The content of the -stage disco-pane is magnified.

Notes/Issues:
Not reproducing for -dev or -prod.
Verified on AMO-stage FF49.0.2 and 52.0a1 (2016-11-01) using Win 7 x64.
Video for this issue: 
![discopane](https://cloud.githubusercontent.com/assets/15685960/19923991/b01d9ef4-a0f2-11e6-9bf4-d58ef6306a6d.gif)

**Comment by muffinresearch** [comment]
Possibly a deployment issue since -dev is happy. The cause is SRI hashes not matching.

None of the "sha512" hashes in the integrity attribute match the content of the subresource.

Looking at the responses from the request for CSS I see: `X-Cache:"Error from cloudfront"` as one of the reponse headers.

**Comment by muffinresearch** [comment]
@ValentinaPC I redeployed the tag and it looks to be ok now.

**Comment by ValentinaPC** [comment]
Verified as fixed on -stage FF49.0.2(Win 7)
Things look and work as expected.
Postfix screenshot: 
![2016-11-02_1418](https://cloud.githubusercontent.com/assets/15685960/19928477/43d2fd4c-a107-11e6-8d54-cc2b1c8aa69e.png)
