### ISSUE TITLE
API returns wrong e10s information

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3947]
### Describe the problem and steps to reproduce it:

Call:
https://addons.mozilla.org/api/v3/addons/addon/addictive_typing_lessons@tomkennedy.net/feature_compatibility/

### What happened?

Response:
```
{
    "e10s": "compatible"
}
```

### What did you expect to happen?

```
{
    "e10s": "unknown"
}
```

### Anything else we should know?

The latest public version (which is not marked as e10s-compatible) is 4.0.1-signed.1-signed.
There is a 4.1 which was rejected during review that is marked as e10s-compatible.

**Comment by wagnerand** [comment]
So, according to @diox, this is because e10s compatibility is being set on upload instead of on approve. He also mentioned there is no easy fix, it probably requires a model change. As it seems this is not going to happen in the near future I suggest we remove the feature entirely instead of showing unreliable data.

Any objections, @muffinresearch?

**Comment by andymckay** [comment]
Given that we are about to move to a huge cohort off add-ons to e10s for Firefox 50, I don't think removing this information now is a good idea. Can we show the version that the e10s was made on?

**Comment by wagnerand** [comment]
Not that I can think of. The e10s compatibility info is stored per add-on.

**Comment by diox** [comment]
There are 2 approaches to fixing this:
- Continue to store it per add-on, but update the flag each time a version status changes. This is really hard to do properly because of the way addons-server code is structured. It's also quite costly because you need to parse the manifest again each time you need to do that check. I really don't recommend going that route.
- Store it per Version (or per File). It's simpler to implement - we can keep doing it at upload time only - but still poses challenges: we then need to be careful to use the right version when we fetch the information. The listed/unlisted channel stuff will make that bit harder, since there won't be the concept of purely "unlisted" add-ons anymore, so it will be tough to figure out which version to use if the add-on has both listed and unlisted ones.

**Comment by andymckay-limited-access** [comment]
Second approach sounds good and provide all the information for all the
versions in the API response. Let's provide more information to the
consumer of the API and and let them figure out which versions they want to
use.

**Comment by shell15** [comment]
asking Felipe how system add-on determines MPC status to target for e10s eligibility.  If this impacts who can get e10 -this is a much bigger user impact.  scenario:  add-on updates to be e10s compatible, older versions flagged MPC=true (though it is not), users with older incompatible versions of that add-on get e10s activated starting Fx50 (if they have no other items blocking qualifying - which are getting less each release) @shell15

**Comment by andymckay** [comment]
I chatted with @shell15 and the changes in the system add-on are not related to this API. So basically no need to worry about that last comment.

**Comment by shell15** [comment]
talked to andy and where the system add-on is getting targeting info is different - so don't need to make P1 for that.

**Comment by muffinresearch** [comment]
I don't think we need this any more, please reopen it if we do.

**Comment by wagnerand** [comment]
@muffinresearch are we going to remove that information from the API?

**Comment by diox** [comment]
@wagnerand shouldn't we? Is there any reason to keep this information anymore at all with the impending switch to webextensions-only in Firefox 57?

**Comment by wagnerand** [comment]
@diox imho, we can remove it.

**Comment by muffinresearch** [comment]
There's this issue for that now: https://github.com/mozilla/addons-server/issues/7340
