### ISSUE TITLE
Stats data missing for Firebug for Nov 7th

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#3958]
### Describe the problem and steps to reproduce it:
1. Load https://addons.mozilla.org/en-US/firefox/addon/firebug/statistics/overview-day-20161107-20161107.json

OR
1. Go to https://addons.mozilla.org/en-US/firefox/addon/firebug/statistics
2. Click on Custom date range and choose nov 7th as the date range

### What happened?
There is no data available for nov 7th

### What did you expect to happen?
json returned is not empty.

**Comment by krupa** [comment]
looks like the data is available now.

**Comment by davehunt** [comment]
Looks like this is happening again today: https://addons.mozilla.org/en-US/firefox/addon/firebug/statistics/overview-day-20161108-20161108.json. If this is just a timing issue we could update the test to expect data from 2 days ago instead of 1. Let me know if you'd like me to make this change, @krupa.

**Comment by ValentinaPC** [comment]
Happening again, between `2016-11-28` -> `2016-12-01`.
Checked for Adblock Plus and Firebug in AMO-prod using FF50(Win 7).
Screenshots:
![adb](https://cloud.githubusercontent.com/assets/15685960/20829527/1e7ba428-b885-11e6-979f-f714448db121.png)
![firebug](https://cloud.githubusercontent.com/assets/15685960/20829528/1e7d9e40-b885-11e6-9ee5-e5750703bfae.png)
