### ISSUE TITLE
Expose WebExtensions permission on the add-on detail page

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3983]
Since WebExtensions provide the added benefit of having permissions we should expose that to the user prior to install so they know what to expect.

The current idea is to do something similar to the privacy policy where there is a link next to the install button that displays the permissions in a modal.

Depends on #3981.

**Comment by eviljeff** [comment]
@jvillalobos please check out the details pages and file follow-up issues for changes needed.
e.g.
https://addons-dev.allizom.org/en-US/firefox/addon/permissionsupdate123/ (webext with perms)
https://addons-dev.allizom.org/en-US/firefox/addon/easy-youtube/ (xul)
https://addons-dev.allizom.org/en-US/firefox/addon/easy-youtube-video-download-ea/ (webext no perms)
cc any appropriate ux person too.

**Comment by jvillalobos** [comment]
I don't know which of these are issues or not, so apologies in advance for the massive comment.

From https://addons-dev.allizom.org/addon/permissionsupdate123/

<img width="266" alt="perms-1" src="https://cloud.githubusercontent.com/assets/62568/23072796/aa096bf6-f4f8-11e6-8269-a32ac4ff3f44.png">
 
* The text should be centered vertically, like we do when an add-on has a privacy policy [in prod](https://addons.mozilla.org/addon/noscript/).

<img width="588" alt="perms-2" src="https://cloud.githubusercontent.com/assets/62568/23072858/efc716c0-f4f8-11e6-86c1-ddc49652e82c.png">

* Permissions like "identity" and "storage" only have one word. Does that mean the permission is missing a description? Do we know which permissions are missing this? Do we have a process thought out to deal with new permissions so we don't end with gaps like this?
* `Access your data for X website`. What happens if the list of websites has dozens of domains? What if the domains have masks, like `*://*.mozilla.org/*` or `https://*/path`? See [this doc](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/match_patterns) for more possible patterns. Do we make a distinction for when it's requesting access for all sites? Maybe we should group all website access permissions into one item (`Access your data for [list]`).
* Change `It can:` to `This add-on can:`.

From https://addons-dev.allizom.org/addon/fireftp/

<img width="416" alt="perms-4" src="https://cloud.githubusercontent.com/assets/62568/23073357/cfacd42c-f4fa-11e6-8c30-2057a3752ec5.png">

* The underline includes the space between the icon and the text.
* Alignment isn't great when there's no button: big left margin and little top margin. The spacing looks better when there's a button:
 
<img width="436" alt="perms-5" src="https://cloud.githubusercontent.com/assets/62568/23073454/3bab98b6-f4fb-11e6-8d83-bb9f461748ff.png">

From https://addons-dev.allizom.org/addon/easy-youtube-video-download-ea/

<img width="578" alt="perms-6" src="https://cloud.githubusercontent.com/assets/62568/23073521/7cf2e81a-f4fb-11e6-970f-55fee4e70337.png">

* This is a lot of text just to say `This add-on doesn't require any special permissions.`. Do we really need all the context in this case? Also makes me think that the list of permissions should be the first thing in the popup, with the optional explanation at the bottom, since it will be read once, at best.

/cc @designakt

**Comment by designakt** [comment]
Adding @devaneymoz for copy questions and @brassy- to the conversation.

We should only show permissions for which we decided they are worth being surfaced to the user (an not show others, e.g. idle, power, identity, storage), like we do in Firefox. The permissions that should be surfaced are listed in @devaneymoz copy doc:
https://docs.google.com/document/d/1-aLncxcKpinCNpvksmknwWZhrM2bEChDmQ3C422C6Vc/edit#heading=h.tbk9p7o80w90

I case of no permissions I would opt to not show the permissions link, as we do with privacy policy.

In case an add-on can modify data on multiple sites I would say that and provide a link to see a full list of those sites. Maybe similar to what Chrome does.
![chromeextensionpermissions_manywebsites](https://cloud.githubusercontent.com/assets/8145891/23074660/d53ade5e-f539-11e6-92e5-fc376122804d.png)
![chromeextensionpermissions_manywebsites_expanded](https://cloud.githubusercontent.com/assets/8145891/23074661/d53cf388-f539-11e6-9926-dc63cbba9098.png)
@devaneymoz can you please help with the copy on that.

**Comment by eviljeff** [comment]
Btw, at the moment the permissions are returned in this order:
1) match all urls (e.g. <all-urls>)
2) known permissions, in constants order (alphabetically),
3) match urls for sites
4) unknown permissions

Re: permission descriptions copy - we were planning to eventually keep them synced with Firefox (and localised) by extracting from mozilla-central automatically, but I noted that the [copy](https://docs.google.com/document/d/1-aLncxcKpinCNpvksmknwWZhrM2bEChDmQ3C422C6Vc/edit#heading=h.tbk9p7o80w90) was different than what's shown in [Firefox](https://dxr.mozilla.org/mozilla-central/source/browser/locales/en-US/chrome/browser/browser.properties#84-95).

**Comment by devaneymoz** [comment]
To chime in on a few items...

1.
I like @jvillalobos' suggestion to change "It can:" to "This add-on can:" ahead of the bullet points.

2.
Let's massage the message Chrome uses for website permissions to: "Read and change your data on various websites"

3.
In the intro to the Permissions popup, I think we should change "permissions" to "permission" (singular). So it should read like so: "Some add-ons ask for **permission** to perform certain functions...."

4. 
I agree we don't need to show that big block of text for add-ons that don't ask for permissions. However I thought the "Permissions" link on the Details page wouldn't even show for add-ons that don't ask them? 

But if it is a clickable destination, let's just kill the opening graph and display "This add-on doesn't ask for any special permissions." (note "ask for" is a copy tweak)

**Comment by eviljeff** [comment]
> I agree we don't need to show that big block of text for add-ons that don't ask for permissions. However I thought the "Permissions" link on the Details page wouldn't even show for add-ons that don't ask them?
But if it is a clickable destination, let's just kill the opening graph and display "This add-on doesn't ask for any special permissions." (note "ask for" is a copy tweak)

The PRD didn't specify, but we can just not have the link and dialog for webext with no permissions easily enough.

**Comment by designakt** [comment]
> I like @jvillalobos' suggestion to change "It can:" to "This add-on can:" ahead of the bullet points.

@devaneymoz I wonder if it will be strange for users if they have different copy for similar elements on AMO and in Firefox. There this text reads: 
`It requires your permission to:`

![webextension-firefox-permission-warning](https://cloud.githubusercontent.com/assets/8145891/23126917/3f538cb4-f779-11e6-9a58-e44e51bd0d4b.PNG)

Does using the term add-on in this cases contradict Michelle Heubuschs recommendation in here copy-guide:
![screen shot 2017-02-17 at 18 02 56_cut](https://cloud.githubusercontent.com/assets/8145891/23127102/08c2bb7e-f77a-11e6-84ae-6972f9cccfc1.png)
https://firefoxux.github.io/StyleGuide/#/writing

**Comment by jvillalobos** [comment]
Agree on using the same text as Firefox, though we'll probably want to replace `It`.

**Comment by eviljeff** [comment]
Just to mention again, the copy for all the permission descriptions in the document linked from the PRD differs than the copy shown in Firefox.  E.g. ["Read and modify bookmarks"](https://dxr.mozilla.org/mozilla-central/source/browser/locales/en-US/chrome/browser/browser.properties#84) vs "Access bookmarks". If we want the possibly of automatic updates they'll need to be the same.  (Unless some is volunteering to keep an eye on mozilla-central and file issues to update amo with new descriptions!)

Btw, "Read and change your data on various websites" is "Access your data...." in Firefox - though we can have different copy for the surrounding text that won't change if you want.

**Comment by devaneymoz** [comment]
If Firefox uses "It" though, and we want to keep the language the same between AMO and Firefox, that would seem to imply we need to keep using "It" or what am I missing? 

@eviljeff: Are you referring to this original [permissions copy doc](https://docs.google.com/document/d/1-aLncxcKpinCNpvksmknwWZhrM2bEChDmQ3C422C6Vc/edit)? If so, the discrepancies you're seeing are due to follow-up copy changes that happened concurrently in a myriad of locations (bugzilla, github, and the copy doc itself via side comments where the conversation is removed once the comment is "resolved"). As this project was unfolding I didn't make a point to track all copy changes in the doc, though in hindsight I wish I had scoped for that. 

If we need a copy doc that reflects all final copy let's discuss. I'd have to do quite a bit of digging around to find all instances of changes.

**Comment by eviljeff** [comment]
@devaneymoz if the descriptions are supposed to be the same, and the text in Firefox (i.e. in mozilla-central) is the canonical copy then that's all I need to know (and ideal - automating updates requires they are the same).

Some of the text that isn't strictly a permission description is slightly different too though:
 "Read and change your data for {name} website" is "Access your data for {name}" - is it "Read and change" or "Access"?  It's not going to be automatically updated so it can differ, it's just inconsistent currently, so confirming.

**Comment by jvillalobos** [comment]
> If Firefox uses "It" though, and we want to keep the language the same between AMO and Firefox, that would seem to imply we need to keep using "It" or what am I missing?

For me the difference is context. In the Firefox UI you see the add-on name immediately before "It". In the AMO UI there's a long explanation about permissions, followed by "It", so it feels out of place to me.

**Comment by devaneymoz** [comment]
> Some of the text that isn't strictly a permission description is slightly different too though:
"Read and change your data for {name} website" is "Access your data for {name}" - is it "Read and change" or "Access"? It's not going to be automatically updated so it can differ, it's just inconsistent currently, so confirming.

@eviljeff: We used "Access"

**Comment by eviljeff** [comment]
Changes have been made so calling this done. 
File new issues for any further copy changes.

**Comment by jvillalobos** [comment]
I gave this new version a try, and it's looking good. My only note is for the websites dropdown, which you can see in [this example](https://addons-dev.allizom.org/en-US/firefox/addon/permissionsupdate123/). Not sure if we want something that looks more clickable. At least would be good to have the hand pointer rather than arrow pointer when hovering over it. Not a blocker for me, leaving to @designakt to decide if it's worth filing a followup.

**Comment by designakt** [comment]
@pwalm could you please take a look at that list and see if we need some fixes?
