### ISSUE TITLE
Trying to Log in with a new account from a new tab will redirect the user to Firefox Accounts page.

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#3987]
Steps to reproduce:

1.Log in with valid credentials.
2.Log out.
3.Select Log in again.
4.In the Sign in page hover over “Use a different account” and open it in a new tab.

Expected results:
The Sign in page is displayed.

Actual results:
The Firefox Accounts page is displayed and the user is signed in.

Notes/Issues:
Verified on FF49.0.2(Win 7 64-bit).
Clicking it on “Use a different account” will redirect the user to the Sign in page.
Here is a video for this issue: 
![animation](https://cloud.githubusercontent.com/assets/15885467/20208042/11b94e62-a7f4-11e6-8bf6-4dd7da233f02.gif)

**Comment by muffinresearch** [comment]
@cosminbadescuSV It looks like opening a new tab is simply bypassing the click event, hence you're falling through to the actual link as opposed to a click which would perform an interaction. 

Since at this point you've not logged out it just showing you what you'd see going to https://accounts.firefox.com directly (which looks to always redirect to https://accounts.firefox.com/settings). 

That's an issue in FXA rather than AMO. Could you re-file on https://github.com/mozilla/fxa-content-server please?

**Comment by cosminbadescuSV** [comment]
I logged another one in the right place: https://github.com/mozilla/fxa-content-server/issues/4400
Thanks! @muffinresearch
