### ISSUE TITLE
Unusable "Upload file" button for an unlisted second version

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3992]
Prerequisites: enable the `step-version-upload` and `mixed-listed-unlisted` flags

Steps to reproduce:
1. Submit a listed add-on in AMO-dev and approve it i.e. https://addons-dev.allizom.org/en-US/developers/addon/disconnect-24-dev/edit
2. Upload a new unlisted version for that add-on with availability on "Windows"
3. Click the "Upload file" blue button displayed at the end of submission process

Expected results:
- User is redirected to manage version page from where he can upload a new file
or
- There is no "Upload file" button at the end of submission process

Actual results:
There is a "Upload file" button at the end of the submission process, but if clicked user cannot add another file for that version.

Notes/Issues:
Maybe this is happening because "Upload file" button should not be available for approved versions.
Issue is not reproducing when submitting an unlisted add-on at step 1.
Verified on AMO-dev FF49.0.2(Win 7).
Screenshots for this issue: 
![submission](https://cloud.githubusercontent.com/assets/15685960/20257834/e45ff25a-aa54-11e6-835d-4538fcb3bb6b.png)
![managepg](https://cloud.githubusercontent.com/assets/15685960/20257839/e985beea-aa54-11e6-8067-8438108042aa.png)

Relates to #3469

**Comment by eviljeff** [comment]
It's happening because we don't allow new files to be added to versions that have approved files so there is a test that checks `is_listed` and stops the new file being added for listed add-ons, while allowing it for unlisted add-ons.  The check isn't mixed listed/unlisted version aware though so it's not taking into account you are trying to add to an unlisted version (only that it's a listed add-on).

When the new file upload is changed to match new add-on and new version it'll be addressed then.  (It can _only_ happen when `mixed-listed-unlisted` is enabled and we won't enable that as the norm until all of the olympia codebase is fixed.

**Comment by eviljeff** [comment]
Is this still replicable?

**Comment by ValentinaPC** [comment]
Nope, this works as expected: _user can upload a new file, if there is a platform available, after ending the submission of an unlisted version_.
Postfix video: 
![upload](https://cloud.githubusercontent.com/assets/15685960/20661040/2c99c2c0-b555-11e6-9d88-b72aad206fc8.gif)
