### ISSUE TITLE
Prevent uploading a new version to the listed channel if the add-on is invisible

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4025]
Invisible add-ons have a special status. Their files are not reviewed, so uploading new ones does not make much sense, so we need to prevent uploading a new version to the listed channel if the add-on is invisible.

**Comment by jvillalobos** [comment]
Note that invisible in this case means `inactive=1`. Working off the new submission flow in https://github.com/mozilla/addons/issues/192, I think what should happen is that in the first step of the new version submission, the `Where to host` option should be set to `On your own`, the `Change` link shouldn't appear, and a message (in bold red letters, I think) should appear below this section explaining that an invisible add-on can only have self-hosted versions submitted to it.

**Comment by ValentinaPC** [comment]
This can be misleading while in production.
Please see screenshot:
![newvers](https://cloud.githubusercontent.com/assets/15685960/26151705/9e85867a-3b0c-11e7-84a8-b9cfcee0e532.png)

**Comment by diox** [comment]
I've followed https://github.com/mozilla/addons-server/issues/4025#issuecomment-261353145: The button is still displayed, but should only allow  you to upload unlisted versions if your add-on is invisible, regardless of what past versions you uploaded - the link to change where to host should be hidden in that case (and only in that case).

It should also be impossible to try to work around this by manually going to the "listed" upload URL or the distribution method selection page.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

When an add-on is set to invisible, you can opt only for the unlisted distribution method for new versions.

Trying to change the URL from unlisted to  listed during the submission process has no effect, i.e. you are redirected to the unlisted version distribution page.
Additionally, tweaking the page HTML to overcome this limitation won't work (you'll see an error message like in the following screenshot):

![image](https://user-images.githubusercontent.com/31961530/69430930-52b64880-0d3f-11ea-879e-b6a68b5183cc.png)


@diox If I submit a new version for an invisible add-on  through the signing API I have the following result:
1. Precondition: add-on is set as invisible and its latest version is listed
2. Upload a new version through the signing API - if `channel` is not specified, it will be picked up from the latest submitted version, which in my case is `listed`
=> new version is created under the listed channel

However, this version will not be auto-approved and its review page will look like this:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/devhub-listed-ext-
![image](https://user-images.githubusercontent.com/31961530/69430670-c9067b00-0d3e-11ea-919b-7e532cc0684a.png)

So, the problem is that the API has no knowledge of the limitation set for Invisible add-ons. It might be an edge case, but do you think we should do something about it?

**Comment by diox** [comment]
Yeah, please file a follow-up for that, I had a note to take care of this but totally forgot, it's worth raising an error at submission in the API as well.

**Comment by AlexandraMoga** [comment]
Filed #12943
