### ISSUE TITLE
Program can't change manifest

### ISSUE THREAD

**Issue by nitricware** [mozilla/addons-server#4080]
### Describe the problem and steps to reproduce it:
1. Try to submit an extension with a name already taken in manifest.js
2. Read warning that name is already taken
3. Edit name
4. Re-submit
5. Read same warning again (no matter to what name you change the extension name - like your name and your birthdate)

### What happened?
Program didn't save the new name I entered in the form.

### What did you expect to happen?
Expected the program to save the new name.

### Anything else we should know?
Tried it with ublock on and off.

**Comment by ValentinaPC** [comment]
There are 2 cases for the duplicate name situation: 
1. You can change the name in the manifest.json - than resubmit the extension and you will see the warning gone.
2. You can change the name in the AMO form and continue with started submission
- you finish with success the submission
- you are blocked because the extension is localized and you have to change the name in the manifest.json or message.json files.

Some questions:
1. Could you attache the used extension?
2. After step 3 you restarted the submission process or continued from that point?

**Comment by nitricware** [comment]
Yes, it is localized. That explains it. Maybe a more detailed explanation on the AMO form page could help future users.

**Comment by EnTeQuAk** [comment]
This should have been by #4095 when we dropped our (partially broken) uniqueness checks for add-on names.
