### ISSUE TITLE
Investigate viability of replacing syntax highlighter

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4149]
The current syntax highlighting lib for the review tools is imperfect, has been patched multiple times and the original lib isn't getting many updates.

To see if we can get rid of this problem we should see how much effort it would be to replace the current highlighter with highlight.js 

The biggest issue with that is ensuring parity in terms of functionality and have the new lib play nicely with the diff highlighting that needs to occur in addition to the syntax highlighting. 

The issue is to cover taking a look at how viable switching out the libs would be.

**Comment by EnTeQuAk** [comment]
Another idea is to use [Pygments](http://pygments.org/) for the highlighting part which has fabulous support for all the things and can be extended quite easily. Less JavaScript, more static rendering - not sure if that's something that would be reasonable since the reviewer tools are more or less javascript but afair the're not a SPA in the sense that they do load the files and highlighting separately on every click.

This would be quite a bit of work though but maybe not too much more than integrating highlight.js.

**Comment by muffinresearch** [comment]
@EnTeQuAk that's an interesting idea. Maybe the diffing piece could move server-side too?

**Comment by EnTeQuAk** [comment]
Yeah, I do remember implementing some highlighted diffs years ago with Pygments unless I'm mistaken (don't yet take my word for it, I'll have to look again).

**Comment by muffinresearch** [comment]
This is superceded by https://github.com/mozilla/addons-server/issues/7171
