### ISSUE TITLE
Layout issues when expanding collector's note during collection edit

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4210]
Steps to reproduce:
1.Create one collection and go to its edit page (https://addons.allizom.org/en-US/firefox/collections/asdasda/victor/edit/#addons-edit)
2.Expand the collector's note section(by drag and drop)

Expected results:
No layout issues

Actual results:
Layout issues present 

Please see an image with the problem:
![expandedcomment](https://cloud.githubusercontent.com/assets/1583842/21644850/3fcc1c0c-d298-11e6-80fa-6f3f37dd76ce.png)

**Comment by EnTeQuAk** [comment]
This can be a good first bug to fix, might be tricky or I'm not sure if it's important enough and should just be closed in favor of all future work going on in addons-frontend...

**Comment by wagnerand** [comment]
The mentor for this bug is: @eviljeff 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by jack17529** [comment]
I could not able to access the content on that address.Please help.

**Comment by ian-henderson** [comment]
What is the expected behavior here? Should the text box stop expanding in the x direction if it reaches a certain limit?

**Comment by eviljeff** [comment]
@ian-henderson yeah.  Or have the parent box expand too up to the page edge as long as it doesn't break the layout. It should be doable with css.

If you (or anyone else) is thinking of starting on this issue please be aware we are planning to replace this tool with a complete rewrite in the next 3-6 months so think about it as good practice rather than something that will be used for years.  Just like any other piece of web code really!

**Comment by ian-henderson** [comment]
@eviljeff Cool, I'll see what I can do with that, css-wise. This is will be my first pull request, so I definitely use the practice!

**Comment by vcarciu** [comment]
Verified as fixed : 
![collector](https://user-images.githubusercontent.com/1583842/31126626-0af11562-a855-11e7-9cb8-d61424b09e7c.gif)
