### ISSUE TITLE
[Devhub Landing] Add global link hover, visited styles

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#4274]
Supports mozilla/addons-frontend#1021

**Comment by EnTeQuAk** [comment]
Started working on it in https://github.com/mozilla/addons-server/tree/feature/4274-add-global-link-colors

**Comment by ValentinaPC** [comment]
Please add some STR or some mocks for us to check this. Thank you!

**Comment by EnTeQuAk** [comment]
Oops, sorry about that. It's hard to screenshot but basically:

 * regular links (not buttons) slightly fade on hover and get an underline
 * buttons darken a bit on hover
 * if you click a button (e.g long click) you see a slight outline around it
 * if you tab through links and buttons with `tab` key you see these effects as well

I think that's it, hope that helps.

**Comment by madalincm** [comment]
Verified as fixed in FF50(Win7) in addons-dev.allizom.org
"buttons darken a bit on hover
if you click a button (e.g long click) you see a slight outline around it: :
![devhubbuttons1](https://cloud.githubusercontent.com/assets/15685441/22336350/9f8621e8-e3ea-11e6-99dc-7da7ef128550.gif)

"regular links (not buttons) slightly fade on hover and get an underline" : 
![linkseffect](https://cloud.githubusercontent.com/assets/15685441/22336782/0fac4460-e3ec-11e6-96ed-455d2c58f62c.gif)

"if you tab through links and buttons with tab key you see these effects as well" This as well works correctly but only for buttons. When you find a link element with the tab no effects are displayed.
@EnTeQuAk Please have a look:

**Comment by madalincm** [comment]
For some reasons  I couldn't upload a gif for the issue I mentionet (gif…]()
 upload process kept failing :( )

So here is a screencast link: https://www.screencast.com/t/556oT9q14a

Reopening the bug

**Comment by EnTeQuAk** [comment]
Eh, sorry, that was me being wrong. If you just tab through the links you will see a (dotted) outline as you know it from many sites but explicitly no underline for links as this would look bad.

So, everything's fine :) Sorry for that.

**Comment by madalincm** [comment]
Thanks @EnTeQuAk . Marking as verified fixed.
