### ISSUE TITLE
Background images are not visible

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#4281]
On the new devhub pages apparently background images aren't correctly compiled.

**Comment by ValentinaPC** [comment]
How can I see if the background images from the new Dev Hub pages are correctly compiled? Thanks!

**Comment by EnTeQuAk** [comment]
Easiest one, check if the background image (the cubes and pyramid thingies) are in the overview (first section, https://www.dropbox.com/s/oszzk94kymc8muv/Screenshot%202017-01-26%2014.47.20.png?dl=0) Besides this one we aren't using that many background images and if they're broken they'd be broken all together.

**Comment by madalincm** [comment]
Verified as fixed in FF50(Win7) in addons-dev.allizom.org
Postfix screencast:
![devhubbg2](https://cloud.githubusercontent.com/assets/15685441/22336050/9d8aa1c6-e3e9-11e6-816c-eca663f61811.png)
![devhubbg1](https://cloud.githubusercontent.com/assets/15685441/22336049/9d87b7c2-e3e9-11e6-870c-07f76a22d7ea.png)
![devhubbg3](https://cloud.githubusercontent.com/assets/15685441/22336159/ec5c40d4-e3e9-11e6-9ef7-089c934965a0.png)
