### ISSUE TITLE
Clicked button to install Amazon's universal button

### ISSUE THREAD

**Issue by gwenhaven** [mozilla/addons-server#4300]
### Describe the problem and steps to reproduce it: Clicked the "Install for Firefox" button provided on the Amazon webpage: https://www.amazon.com/gp/registry/universal/
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
Hm, it's weird that https://addons.mozilla.org/firefox/downloads/latest/add-to-amazon-wish-list-button/addon-257015-latest.xpi?src=external-help 404's in one of my Firefox profiles and works just fine in another.

Also, browsing the source for the latest approved version 404's as well: https://addons.mozilla.org/en-US/firefox/files/browse/447431/

Maybe @jasonthomas has an idea?

**Comment by jasonthomas** [comment]
Is this add-on disabled? https://addons.mozilla.org/en-US/firefox/257015 returns 404.

**Comment by wagnerand** [comment]
Yes, it's _hidden_.

**Comment by jvillalobos** [comment]
@gwenhaven the add-on was disabled by Amazon, so there's nothing we can do about it on our side. It's up to them to enable it again if they want to.

Is there anything to do for this issue?

**Comment by muffinresearch** [comment]
@jvillalobos I don't think there's anything else for this issue short term. 

Longer-term I think we can improve this scenario if we provide tools for developers to communicate the reasons for disabling an add-on - although granted not everyone would necessarily use it.

This particular one we get asked about alot because the author is still linking to it here [1]. It also looks like the universal registry button is actually being replaced [2] with the amazon assistant [3].

[1] https://www.amazon.com/gp/registry/universal/
[2] https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=201485470
[3] https://www.amazon.co.uk/gp/BIT/AmazonBrowserBar

**Comment by wagnerand** [comment]
I'm still wondering why the file is sometimes available and sometimes it isn't, as per my first comment...

**Comment by diox** [comment]
Maybe because you were logged in as an editor ? Editors (and developers) can still download disabled files

**Comment by wagnerand** [comment]
@diox oh, right. That might be it.

**Comment by muffinresearch** [comment]
I've emailed Amazon to ask about them changing the page that links to the 404 on AMO - especially since as noted above it would appear that there's an alternative. Let's see how that goes.
