### ISSUE TITLE
Use yarn to install our nodejs dependencies for speed

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#4321]
This should actually speed-up our dockerfile building and test process by almost a minute (at least that's the performance difference locally) which is pretty awesome.

Let's see what we need for that.

* https://yarnpkg.com/en/docs/install#centos--fedora--rhel cc @bqbn on this if that's something we want to do in our docker files

cc @muffinresearch, anything important to take into account using yarn instead of npm? Afair addons-frontend is already using it right?

**Comment by muffinresearch** [comment]
We are still at the point of only using it locally, though we are in the process of moving to using it for production. This should probably wait until we've done it there since we can then apply anything learnt there here.

Unless something has changed I don't think it will buy anything for docker builds since you won't have a cache available when the build runs since you're starting from scratch and the npm/yarn install will be a new FS layer.

Its for this reason that a dep change in package.json causes that entire layer to be discarded and the deps to need to be installed from scratch.

**Comment by muffinresearch** [comment]
Here's the ticket to follow along https://github.com/mozilla/addons-frontend/issues/1391

**Comment by EnTeQuAk** [comment]
> Unless something has changed I don't think it will buy anything for docker builds since you won't have a cache available when the build runs since you're starting from scratch and the npm/yarn install will be a new FS layer.

That's precisely why I think yarn might bring advantages since (at least for me locally) it installs from scratch much more quickly than npm. Or am I confusing something?

**Comment by muffinresearch** [comment]
> That's precisely why I think yarn might bring advantages since (at least for me locally) it installs from scratch much more quickly than npm. Or am I confusing something?

The problem is if the layer in the fs is invalidated (e.g. package.json gets modified) *all* the changes made when running `yarn install` get blown away including the cache. Which is a fundamental issue with adding dependencies inside of docker at build time.

A different approach would be to do the install at run time, but then that would be the end-users responsibility so that's not that ideal either. Of course if you'd installed the deps with yarn a user running yarn install for new deps would benefit from the cache, but builds wouldn't.

I wrote with more detail about this problem here:  https://muffinresearch.co.uk/docker-and-dependencies/ - I don't think there's any great solutions available yet but then I've not been following the changes in docker that closely so it might be worth checking if something's changed there.

**Comment by EnTeQuAk** [comment]
Closing as this isn't not really a problem for us on addons-server and it makes more sense to work on something webpack related instead of switching to yarn imho.
