### ISSUE TITLE
the (AMO) and (Self) tags aren't localised

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#4398]
We show (AMO) and (Self) next to versions in a few places if an addon has both unlisted and listed versions.  But the text isn't localised.

**Comment by eviljeff** [comment]
@jvillalobos can you weigh in to confirm if 'Self' _should_ be localised - I'm guessing 'AMO' not.

**Comment by jvillalobos** [comment]
They are meant to be compact tags, so I would favor keeping them hardcoded as Self and AMO. But perhaps they should have a localized tooltip that explains their meaning.

**Comment by eviljeff** [comment]
Can you provide copy for the tooltips?  Also, can you mockup what you want it to look like - if not the standard (?) circle then what?

**Comment by eviljeff** [comment]
@jvillalobos ^

**Comment by jvillalobos** [comment]
* AMO: "Listed on this site after passing code review. Automatic updates are handled by this site."
* Self: "Signed for self-distribution. Updates are handled by you."

As for the look, I think we should keep it consistent with the rest of the dev hub and use the blue popup with white text. The only difference is that the popup would emerge from the tag rather than a separate (?) circle.
<img width="338" alt="tooltip" src="https://cloud.githubusercontent.com/assets/62568/22159728/e9d369c8-df07-11e6-8d0b-3d74474ea103.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7)
Postfix screenshots:
![amotooltip](https://cloud.githubusercontent.com/assets/15685960/22289789/0b78d714-e306-11e6-817d-b82f8ec3572e.png)
![selftooltip](https://cloud.githubusercontent.com/assets/15685960/22289790/0b7f3a8c-e306-11e6-8df4-bf92df24c071.png)
