### ISSUE TITLE
Inconsistent case in https://addons-dev.allizom.org/en-US/developers/ #1635

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#4400]
(Originally reported by @wbamberg in https://github.com/mozilla/addons-frontend/issues/1635; moved because this is the repo for that issue. 😄)

### Describe the problem and steps to reproduce it:
Visit https://addons-dev.allizom.org/en-US/developers/

### What happened?

The green button reads “Learn How to make an Add-on” - if we're using sentence case this should probably be "Make".

The second blue button reads "Sign in", but the third one reads "Sign In ... ". Should be consistent (probably "Sign In").

-----

#### @atsay's comments from that issue:

Under the header "Publish Your Add-on", the first sentence says, "Have you an add-on ready?" It should say, "Have an add-on ready?" 

In the signed out state, please change the text in the "Evolution in Add-on Development" box to:

WebExtensions are now the standard for add-on development in Firefox. You'll need to update your legacy add-ons to stay compatible.
Button: Learn how (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on)

**Comment by atsay** [comment]
Thanks @tofumatt!

**Comment by devaneymoz** [comment]
After conferring with @atsay, please change the page header to:

**Customize Firefox**

(we removed the "Your")

**Comment by ValentinaPC** [comment]
Verified as fixed in AMO-dev FF50(Win 7)
Postfix screenshots:
- > After conferring with @atsay, please change the page header to:
> Customize Firefox
![1](https://cloud.githubusercontent.com/assets/15685960/22140869/c4ed47ec-def7-11e6-81dd-faeb37b686e6.png)
- > Under the header "Publish Your Add-on", the first sentence says, "Have you an add-on ready?" It should say, "Have an add-on ready?"
![2](https://cloud.githubusercontent.com/assets/15685960/22140886/de2039e0-def7-11e6-98e6-f6cf94e91c2a.png)
- > The second blue button reads "Sign in", but the third one reads "Sign In ... ". Should be consistent (probably "Sign In").
![s1](https://cloud.githubusercontent.com/assets/15685960/22140933/1f9646c6-def8-11e6-890d-7e2a4e2ae8e6.png)
![s2s3](https://cloud.githubusercontent.com/assets/15685960/22140936/22cf97de-def8-11e6-9488-d4764feae923.png)
- > In the signed out state, please change the text in the "Evolution in Add-on Development" box to:
> WebExtensions are now the standard for add-on development in Firefox. You'll need to update your legacy add-ons to stay compatible.
> Button: Learn how (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on)
![3](https://cloud.githubusercontent.com/assets/15685960/22140957/3b238138-def8-11e6-9d0c-60a3d1d1ab49.png)
