### ISSUE TITLE
Beta version says it will be reviewed

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons-server#4456]
### Describe the problem and steps to reproduce it:
 - Upload new Beta channel version
 - Fill out all the info fields (changelog etc.)
 - Get to the success page

### What happened?
The success page says that the version will be available once reviewed. However beta versions are always directly available.

### What did you expect to happen?
The success page should have told me, that the beta version was now available in the extension's beta channel.

**Comment by eviljeff** [comment]
@jvillalobos can you mock something up for the success page with the required copy, links, etc?

**Comment by eviljeff** [comment]
Or just the replacement text is fine if it's otherwise as a non-beta listed version

**Comment by jvillalobos** [comment]
While submitting a beta version, I noticed that the help icon appears in a second line instead of next to the text: 
![beta](https://cloud.githubusercontent.com/assets/62568/22378558/a8a01892-e47b-11e6-9e86-9a332f4f65c5.png)

For the last step, I think we can just remove everything except "You're done!" on the first paragraph, for beta submissions:
![beta-end](https://cloud.githubusercontent.com/assets/62568/22378639/e8396562-e47b-11e6-9e63-ef16a030e83e.png)

I would also suggest skipping the description step (version notes and notes to reviewer) for beta versions, if it's a simple fix.

**Comment by eviljeff** [comment]
every small change is a simple fix, but it just creates more edge cases

**Comment by jvillalobos** [comment]
Let's be edgy, for now :).

**Comment by freaktechnik** [comment]
I think being able to set release notes for beta versions in the wizzard is useful. I agree that reviewer notes may be a bit useless.

**Comment by jvillalobos** [comment]
There's an Edit button in the last step that lets you do that. I'm thinking that beta versions are less likely to have note, and the Notes to Reviewer can cause additional confusion about the beta version being reviewed.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Win 7).
Details steps from submission are skipped. Also, reviews are not mentioned at the final step of beta-version submission.
Postfix screenshot: 
![finalstep-of_beta_submission](https://cloud.githubusercontent.com/assets/15685960/22458376/ec3eac4a-e7a4-11e6-8dc5-9702f49e18c3.png)
