### ISSUE TITLE
API to reviewer queues

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#4547]
Could we get an API to the reviewer queues?

Ideally I'd like to be able to authenticate to an API and then get a list of all add-ons and the link to their files. The query can be filtered by all the queue parameters. At this time that's all I need, although others may like more :)

**Comment by diox** [comment]
I'd love this, but let's keep in mind that the code behind the reviewer tools at the moment is kinda crazy: it has its own pseudo-ORM, making it hard to manipulate. As a result it's fairly difficult to build a proper API out of the existing code. One could make a quick and dirty JSON representation of the queues by taking the views and making them output JSON instead of HTML, but that wouldn't integrate well with our existing APIs, and force us to maintain something awful/unwieldy in the long run.

I'd suggest that if we do this, we do it properly, bypassing the custom ORM and either use ElasticSearch (it doesn't have all the data needed atm, but it's close - downside would be that there could be a small lag of a couple seconds max compared to the actual queues) or rebuild the queries using Django's ORM (I'm not sure 100% parity with the existing queues is possible here, there might be weird edge cases because the JOINs made would be different)

**Comment by jvillalobos** [comment]
I see authentication mentioned in the first comment, but just wanted to emphasize that we don't publish the review queue, so the API should only be available to users with certain permissions.

**Comment by muffinresearch** [comment]
Closing this since we're not currently planning to action it. However, we may revisit this in the future depending on the direction reviewer tools goes in.
