### ISSUE TITLE
[Dev Hub] After signing out of Dev Hub, take user to signed-out view of Dev Hub

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#4562]
When you sign out of Dev Hub, you are redirected to the AMO homepage.

Expected outcome: you are redirected back to the Dev Hub landing, but in the signed-out state.

**Comment by vcarciu** [comment]
You can see a discussion about this here : https://github.com/mozilla/addons-server/issues/4288#issuecomment-273240807

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, with FF59, Win10x64

[1] logging out from https://addons-dev.allizom.org/en-US/developers/
![dev hub log out](https://user-images.githubusercontent.com/31961530/38807453-4e5e0016-4185-11e8-8d67-b245f36fa560.gif)

@EnTeQuAk  When signing out  of [https://addons-dev.allizom.org/en-US/**developers/addons**](https://addons-dev.allizom.org/en-US/developers/addons), shouldn't the user also be redirected to DevHub homepage instead of AMO?

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk When signing out of https://addons-dev.allizom.org/en-US/developers/addons, shouldn't the user also be redirected to DevHub homepage instead of AMO?

Fair point, yes they should. I'll push a follow-up patch tomorrow morning to land this in this weeks milestone too. I forgot our legacy views :laughing:

**Comment by EnTeQuAk** [comment]
This probably won't land this weeks milestone, it's actually quite a bit of work and refactoring that is needed to get this working for the legacy legacy devhub page too.

**Comment by AlexandraMoga** [comment]
In order to keep things tidy, I'm going to mark this as verified fixed since it addressed the main request.
For the second scenario, I will file a new bug.
