### ISSUE TITLE
More data needed when generate_addons command is run

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#4575]
The addons created using the generate_addons command leave much to be desired. As I am moving a the UI tests that live here: https://github.com/mozilla/Addon-Tests, I need addons that are as close as possible to a real addon found on addons.mozilla.org.

So far in my testing I have found a few things missing from the addons:

1. There is no addon summary. searching the DOM for #addon-summary turns up empty.
2. 'About This Addon': does not contain any data.
3. No License information. This is in both 'Version Information' and the section to the right of 'About this addon'.
4. There are no tags in the 'TAGS' section.
5. 'Add on Home Page' link is missing.
6. 'Whats this' link in 'Version Information' is missing.
7. No addon with multiple authors.
8. 'Developer Comments' section is missing.
9. 'Development Channel' section is missing.
10. There is one 'Collection' but clicking on it leads to an invalid URL.
11. 'View the source' link in 'Version Information' is missing. 
12. 'Support Site' link is missing.
13. Number of users link does not lead to statistics page.
14. There is no 'promo box' as found on the dev and prod sites.

For #11 we would also need a page with '/files/browse' in the URL.

I will add more as I find them.

**Comment by eviljeff** [comment]
Yeah, `generate_addons` is pretty crappy - it should probably use the same code as `addon_factory` etc that's used in tests as a base so the add-ons at least contain the metadata currently required to be approved.  
Not all add-ons on AMO do have all of the data in the list though, either because it's optional (developer comments, etc) or old listings with crufty data (e.g. quite a number are missing their licenses due to a bug in the past)

**Comment by jrbenny35** [comment]
@eviljeff Is there a way I could call that command? I think we are going to be making our own addon, but that info would still help.

**Comment by eviljeff** [comment]
addon_factory isn't a command, it's a [method](https://github.com/mozilla/addons-server/blob/master/src/olympia/amo/tests/__init__.py#L622) used in tests.  It does very similar things to the code that generate_addons calls, but is slightly more maintained (because we need tests to keep working). Just throwing it out there - might not actually be a good idea to use test code in a pseudo-live environment.

**Comment by jrbenny35** [comment]
Since this #9289 is a thing now, I will go through and add more categories and such to complement the new frontend a bit better.
