### ISSUE TITLE
Don't show "Leave a reply " link for disabled versions

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4604]
Steps to reproduce:
1.Go to any add-on with disabled versions in AMO-dev
2.Press _Review history _ link

Expected results:
No _Leave a reply_ link should be displayed

Actual results:
There is a _Leave reply_ link and it will open Leave Reply section for your latest version

Please see video for this bug : 
![leavereply](https://cloud.githubusercontent.com/assets/1583842/22656963/80275bbc-ec9d-11e6-9639-0d52c597af74.gif)

**Comment by eviljeff** [comment]
A version that's rejected is disabled, and a developer may want to reply to the rejection.  The link exists so you don't have to go searching through all the versions to find the reply box for that channel; it's a link because only the latest version in that channel (rejected or not) can be replied to.
