### ISSUE TITLE
Add-on update forcing to set a new slug resulting in wrong add-on status

### ISSUE THREAD

**Issue by Donohue** [mozilla/addons-server#4607]
* On 2/1/2017 we submitted an update to the Instapaper Firefox add-on, version 1.0.2. The previous version was 1.0.1
* Previously, I had mistakenly uploaded an add-on with version 2.0.2 that I never submitted for review, and deleted completely before uploading the new 1.0 and 1.0.1 versions.
* On 2/2/2017 we got a notification that version 1.0.2 had failed to pass review because it was less than a previously uploaded version:

```
Comments:
This version did not pass the review because of the following issues:

1) 1.0.2 < 2.0.2 (Version 2.0.2 · December 16, 2016 · Deleted)
New uploads must have a higher version number than the previously uploaded versions otherwise those files do not propagate across our mirror network correctly, and many users will receive the old version, which they will be unable to install due to checksum mismatches.
```

* No further action was taken after receiving that message, however, we then received notifications via support that our add-on had been completely removed from the store, and were able to verify that the previously active link for version 1.0.1 was returning a soft 404.

* Issue was resolved by responding to the rejection email.

**Comment by wagnerand** [comment]
Somehow the add-on ended up in `Incomplete` state when it should have been in `Approved` state as there was still one public version left.

**Comment by wagnerand** [comment]
This had just occurred for another add-on.

In both cases, the developer was forced to enter a new slug (apparently the max length changed from 45 to 30 characters). It seems that the new mixed listed-unlisted flow is enforcing that.

@eviljeff can you please look into this and see whether this is the case and why add-ons end up in the wrong status?

**Comment by eviljeff** [comment]
Add-ons aren't forced to change their slugs and I can't see max-length has been changed from 30 since they were added [6 years ago](https://github.com/mozilla/addons-server/commit/5b501b8ec2eb7566618c5715cd28d2bb2ce0d285).  Slug length is also 30 in the database.  

Regardless, slugs aren't a trigger to change status - was summary or license missing perhaps?  Need some sort of STR or more details because this issue isn't making sense to me.

**Comment by wagnerand** [comment]
One of the affected developers provided the following screenshot:

https://www.dropbox.com/s/e45xh0fr9wfdnt1/Screenshot%202017-01-26%2010.49.50.png?dl=0

**Comment by eviljeff** [comment]
I'd put money on that not being their existing slug, but rather what the page is generating as a possible slug, based on the name.  (The over-eager javascript changing slugs is another issue).  Not connected to status changing.

Got any urls to the affected add-ons?

**Comment by wagnerand** [comment]
https://addons.mozilla.org/de/firefox/addon/instapaper-official/
https://addons.mozilla.org/en-US/firefox/addon/priceblink-price-comp-coupons/

The issue here is though they somehow the add-on ended up in a wrong status, which made it inaccessible.

**Comment by jvillalobos** [comment]
I manually fixed the statuses of the following add-ons: 8631, 663988, 679292, 700171, 716793, 775256. Looks like their add-on status is being set to `Awaiting Review` after the go through the description step, triggered by missing info (like a license) or old info that doesn't meet current restrictions (like the slug). In the case of the initial issue, I suspect rejecting the review lead to `Incomplete` because it was treated as an initial submission rather than an update.

**Comment by diox** [comment]
From @eviljeff in #4700:
> The slug issue is (iirc) an addon named `name` getting a slug of `name1`, because `name` exists; but then the page JS seeing the name is `name` and changing the slug to `name`, which then causes an error on submission (obvs). It's possible this only happens on the second attempt (e.g. you have some field error on the first submit of the page)
