### ISSUE TITLE
Review tools: Compare Jumps to the wrong file

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#4685]
### Describe the problem and steps to reproduce it:
Example: `https://addons.mozilla.org/en-US/editors/review/disconnect`

### What happened?
Compare jumps to comparing:
5.18.19 (2017-02-13 23:48:34) & 3.14.0.1-signed.1-signed (2014-05-12 14:06:28)

### What did you expect to happen?
It should compare with the last approved version:
5.18.19 (2017-02-13 23:48:34) & 5.18.17

### Anything else we should know?
The possible reason is that v5.18.17 had multiple OS entries.

**Comment by erosman** [comment]
Another example:
`https://addons.mozilla.org/en-US/editors/review/mutelinks`

Version 0.1.1 · February 12, 2017 · Awaiting Review
Compare: It is comparing v0.1.1 with v0.0.9 
`https://addons.mozilla.org/en-US/firefox/files/compare/589862...513307/`

But it should be comparing with v0.1.0

**Comment by EnTeQuAk** [comment]
I think that's the ideal or at least planned behavior. The compare automatically compares the currently listed version with the one you're reviewing. So, if a version update get's rejected or just another update happens while a version is in review you end up "ignoring" that version-update and I think that's alright since you'd miss some context otherwise because imho you want to see the diff from the currently listed version, especially if, say, another review reviews a version update compared to the one who reviewed the recently rejected one.

**Comment by erosman** [comment]
I am not sure I understand what you are saying.

The compare tool, sould compare the latest upload with the last approved vesion.


Example:
v1.4 Approved
v1.5 Approved
v1.6 Approved
v1.7 Unapproved
v1.8 Current Upload

Instead of comparing v1.8 with v1.6, sometimes it compares v1.8 with v1.5 (auto select the compare versions)

Is that planned behaviour?!!
