### ISSUE TITLE
Consider moving AMO API session auth to cookies

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#4687]
addons-frontend uses a JWT for logins but recently, in https://github.com/mozilla/addons-server/pull/4590 , ~~we had to tie the JWT ID to a database table to implement log out~~ we had to store a copy of the JWT in a cookie so it can be deleted on log out. 

As this [helpful flowcart](https://twitter.com/j4cob/status/831286673644216320) illustrates, this means we have essentially reinvented session cookies. 
 
The danger with sticking with JWTs is that they have a [poor security track record](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/) and are still a relatively new technology. Session cookies are battle tested. If we don't benefit from the JWT part, maybe we should switch? It will probably make the code a lot simpler.

There could be some cross-origin considerations since it's sometimes convenient to develop addons-frontend locally against a hosted dev API so I don't know if that makes traditional session cookies more difficult or not.

**Comment by kumar303** [comment]
@mstriemer I figured this was worth filing. I don't know the priority of looking into it though.

**Comment by diox** [comment]
CSRF would be an issue, though. Currently it's not precisely because cookies are not used, so the API does not need to defend itself against that.

**Comment by mstriemer** [comment]
Not using cookies was definitely a conscious decision to avoid CSRF issues as @diox mentioned. I guess the advantage of using a session cookie plus CSRF protection is that when implemented correctly an XSS attack could recover the CSRF token but not the cookie.

In our current implementation an XSS attack could potentially retrieve the JWT which is the only thing needed for authentication. That being said, if we think this is worth doing we don't need to switch off of JWTs to start using cookies and CSRF tokens.

This would likely mean that the new proxy method is the only way to run the addons-frontend. Which should be fine as we want development closer to production.

> addons-frontend uses a JWT for logins but recently, in #4590 , we had to tie the JWT ID to a database table to implement log out.

I don't think the JWT ID is tied to a database table. The logout API just clears the user's cookies since addons-frontend doesn't have access to the cookies (they're all `httpOnly`).

**Comment by kumar303** [comment]
> I don't think the JWT ID is tied to a database table. 

Oh whoops, I misunderstood since we talked about different solutions to this.

The main argument against them [here](http://cryto.net/%7Ejoepie91/blog/2016/06/13/stop-using-jwt-for-sessions/) is this:

> Stateless JWT tokens cannot be invalidated or updated, and will introduce either size issues or security issues depending on where you store them.

And, really, they make a fair point that you might as well just use traditional session cookies. We actually did run into multiple size related issues on the payments site with JWTs.

But, anyway, not sure if it's such a big deal to keep using JWTs without benefiting from them.

**Comment by muffinresearch** [comment]
Assuming a JWT does get compromised what options do we have?

**Comment by muffinresearch** [comment]
Another question raised by @psiinon was how long do the JWTs last for?

**Comment by diox** [comment]
> Assuming a JWT does get compromised what options do we have?
> How long do the JWTs last for?

For both questions, at the moment the answer is : exactly the same as our signed cookie sessions. If an attacker get hold of a signed cookie session or a jwt, we can't do anything beside changing the secret key, invalidating sessions for everyone. Both are valid for the same duration, 30 days.

**Comment by diox** [comment]
From vidyo discussion today: we want to keep authenticating via headers for the moment (reconsider that decision in the distant future where all AMO users are on a browser that supports same-site cookies). Still, we do want to improve security by:
- Investigating reducing the session duration. If the client can keep the fxa assertion and re-send it as needed the user would not need to re-enter their password to authenticate. https://github.com/mozilla/addons/issues/349
- Adding a randomly generated identifier in the `UserProfile` table for each user, and make the token (and possibly regular session cookie) depend on it. That would give us the possibility of resetting all existing sessions for a user we know was compromised. https://github.com/mozilla/addons-server/issues/4906
- Changing the token mechanism away from JWT for the internal API auth, to a simple signed-token solution. https://github.com/mozilla/addons-server/issues/4907
- Investigating whether we can get FxA to notify us when a user password changes, so that we can invalidate their session(s). https://github.com/mozilla/fxa-content-server/issues/4293

**Comment by diox** [comment]
Since all issues from previous comment are filed, I don't think there is anything left to do in this issue. 

Since then we've fixed 2 of those issues, moving away from JWT and adding an identifier on the profile that we can rotate when a user is compromised.
