### ISSUE TITLE
Inconsistent API urls

### ISSUE THREAD

**Issue by Akkuma** [mozilla/addons-server#4716]
### Describe the problem and steps to reproduce it:
At least one API requires a trailing slash, but others do not.

### What happened?
API provides a 301 response

### What did you expect to happen?
API completes as the trailing slash should not be relevant

### Anything else we should know?
Related to #4532

**Comment by diox** [comment]
Which URLs are you talking about ? Trailing slash should matter in most of our API URLs, it's part of the URL.

**Comment by Akkuma** [comment]
@diox http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#uploading-a-version vs http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#downloading-signed-files vs http://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#profile

I've used REST APIs quite a bit and never expect a trailing slash to matter, since I've never ran into a case until now that a trailing slash was required.

**Comment by diox** [comment]
If the only one without a trailing slash is the one to download signed files, then it makes sense as the extra stuff after the last slash is just to make it look more like a filename - as mentioned in the docs it's just for convenience.

Overall our APIs were built with a mandatory trailing slash in mind, because that's the default in the framework we use. I do agree that it could be slightly better - my personal preference is trailing slash for URLs returning multiple things, and no trailing slash the rest of the time - and I'm sorry, but it's unlikely to change at this point.
