### ISSUE TITLE
"Search bar" link from Search Tools homepage loads wrong Mozilla Support page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4757]
Steps to reproduce:
1. Load Search Tools homepage in AMO-stage: https://addons.allizom.org/en-US/firefox/search-tools/
2. Scroll down and click the "search bar" link from Additional Resources section

Expected results:
A Mozilla Support page is loaded.

Actual results: 
A wrong Mozilla Support page with a redirect link is loaded.

Notes/Issues:
- maybe we can link directly to the redirection link; instead of "[search bar](https://support.mozilla.org/t5/How-To/Search-bar/ta-p/15766)" link1 to load "[search bar](https://support.mozilla.org/t5/Learn-the-Basics-get-started/Use-the-Search-bar-in-Firefox/ta-p/894)" link2.
Verified on FF51(Win 7). Issue is reproducing on all AMO servers.
Video for this issue: 
![search-bar](https://cloud.githubusercontent.com/assets/15685960/23263254/5e112b88-f9e6-11e6-924d-42941d1ce14e.gif)

**Comment by diox** [comment]
> maybe we can link directly to the redirection link; instead of "[search bar](https://support.mozilla.org/t5/How-To/Search-bar/ta-p/15766)" link1 to load "[search bar](https://support.mozilla.org/t5/Learn-the-Basics-get-started/Use-the-Search-bar-in-Firefox/ta-p/894)" link2.

Agreed, that's the way to fix this, find the template the change the link.

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @diox

**Comment by bkzhang** [comment]
I'll pick this up

**Comment by kumar303** [comment]
Hi @bkzhang , sorry for the inconvenience but I had to revert this commit, see https://github.com/mozilla/addons-server/commit/0efeed55fb1c05050b7e0da99edde02cde6b92b5

Can you reapply the patch without the jétpack.xpi file?

The patch introduced a new file named jétpack.xpi even though an old one still exists. This is what github showed in the file list:
<img width="996" alt="screenshot 2017-04-10 14 59 42" src="https://cloud.githubusercontent.com/assets/55398/24880068/924057ee-1dfe-11e7-92fb-47906c2b38d5.png">

It looks like from your commit history that you accidentally deleted it and re-added it but I'm not sure why it was duplicated. Perhaps the encoding was different.

Due to the duplicate files, it was giving me a confusing git error (using git 2.12.2 on Mac OS 10.12.4).
````
$ git pull
Updating 5faa102619..0db5b066d1
error: The following untracked working tree files would be overwritten by merge:
	src/olympia/files/fixtures/files/jétpack.xpi
Please move or remove them before you merge.
Aborting
````

This is probably a git bug or a side effect of Mac OS file system encoding but I couldn't think of another way to fix it other than reverting. Sorry again!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix video:
![searchbar](https://user-images.githubusercontent.com/15685960/29418672-ab43e9e0-8375-11e7-83e7-f9a7201b89d2.gif)
