### ISSUE TITLE
Uploading a new version of a webextension with a changed name, will display the old name in Listing page and the new one on Add-ons manager

### ISSUE THREAD

**Issue by raresmsv** [mozilla/addons-server#4809]
*Environment*
Firefox: Nightly 54.0a1
Server: -dev
OS: Windows 10

*Steps to reproduce*
1. Run Firefox Nightly.
2. Submit and approve a webextension (with permissions).
3. Upload and approve a new version that has the name changed in the manifest file (besides the version number).
4. Go to the listing page of the webextension and compare it to the one on about:addons.

*Expected results*
The names displayed are the same.

*Actual results*
The name displayed in Listing is the initial one.
In the add-on manager the displayed name is the new one, as well as in the Permission prompt when installing the webextension.

*Notes*
1. Reproducibility: 5/5.

**Comment by jvillalobos** [comment]
This is, currently, the expected behavior. The name and localized versions can be edited independently from what the add-on package includes, and that's what ends up appearing in the Add-ons Manager. There's a plan to eventually tie the package name to the listing name, but that's longer term.

**Comment by krupa** [comment]
I don't think that the current behavior should be the expected behavior which makes this a valid bug. We should keep this open so that we can track this as something that needs to get done. I can see the current behavior being confusing to users who install the add-on and see a different add-on name be listed in the add-ons manager.

**Comment by eviljeff** [comment]
Closing this if there's no short term plan to implement.  Updating listing metadata from new versions would be a significant change in how the site works so needs a proper plan.

**Comment by krupa** [comment]
Please let us not close valid bugs just because it is a significant change to fix them. We can add a label like 'future' or 'hard to fix' but I don't think "requires proper planning" is a reason to close a bug as wontfix.

This is a user-facing bug which can lead to confusion. If we choose to wontfix the issue, please enumerate the thinking behind that reasoning which is not just "it has always been this way"

thanks!

**Comment by eviljeff** [comment]
Just _some_ of the problems with changing to rely on the current version's xpi data to be the source of truth for metadata are: we have extra data that isn't in the manifest (summary; categories; version notes; etc); multiple files per version which might have different names and other metadata;  all localisation of metadata would need to be in the xpi or AMO wouldn't know what to do about changes for locales not included; wanting to change metadata would require a new version with associated reviews to be needed.  I'm sure more edge cases would need to be worked through in the PRD, and the drawbacks accepted.  

Github is a very poor planning tool - I'd suggest something in Trello be created instead.  If, at some point in the future, a well thought out plan and PRD was created then new issues would be filed and this issue would be closed and duped to it anyway.

**Comment by ioanarusiczki** [comment]
I've investigated this issue on AMO dev and observed that it is also reproducible with static themes when Create a New Theme Version wizard is used.
If the name of the second version is changed during submission, the name displayed in listing is still the initial one.
The new name of the static theme is displayed only in the Themes Tab from Add-on manager after installation.

Verified on AMO dev using ff57 (Win10)
