### ISSUE TITLE
Addons detail contains empty author list

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4952]
See https://addons.mozilla.org/api/v3/addons/addon/eyes-in-the-clouds/

Would be good to understand is this is an expected state or if there's an underlying issue to allow the author list to end up empty.

See also https://github.com/mozilla/addons-frontend/issues/2073

**Comment by jvillalobos** [comment]
This is a [theme listing](https://addons.mozilla.org/addon/eyes-in-the-clouds/) associated to an author that was deleted. IIRC, we deleted the account for bad behavior, but deleting it didn't delete its themes. I thought we had filed a bug to clean those up, but I can't find it now.

**Comment by tsl143** [comment]
@muffinresearch I find it a bit odd (data inconsistency), in the same API response, the `authors` key is `null` but `theme_data.author` has value `MystMaker`(the author name).

**Comment by diox** [comment]
This inconsistency is because the author name gets copied over to a `display_username` field on the `Persona` instance at creation time and that's what is used by `theme_data`. This is terrible and should be changed to use the first listed author name. We would then have coherent data between `authors` and `theme_data.author`, though it would still be empty...

**Comment by eviljeff** [comment]
I think the underlying problem here is we should never delete a user profile that has addons (or themes) attached to them - they should be anonymized instead.  We're lucky if deleting the user is _only_ resulting in a theme with an empty author name.

**Comment by eviljeff** [comment]
I'm just going to close this as it relates to an old LWT that will soon be gone anyway.
