### ISSUE TITLE
Add checkbox to disclose whether add-on requires a payment

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4954]
Following up on the reviewer meetup last week, we need to add a flag for add-on developers to disclose whether a payment is required to use the add-on [1]. I think we could put it in the _Basic Information_ or _Add-on Details_ section on the _Edit Information_ page.

This probably part of the post-review initiative.

[1] or the service the add-on relies on, either upfront, after a trial period or in conjunction with a paid software.

//cc @jvillalobos

**Comment by muffinresearch** [comment]
To support mozilla/addons-frontend#2080 this will also need to be exposed in the API.

**Comment by wagnerand** [comment]
We are getting closer on publishing the new review process. Could we add those checkboxes to the submission flow and developer hub, so we can ask developers to tick it if necessary?

**Comment by kewisch** [comment]
> [1] or the service the add-on relies on, either upfront, after a trial period or in conjunction with a paid software.

...or hardware.

**Comment by jvillalobos** [comment]
What needs to happen here:
- [ ] Add a checkbox to the description step in the new add-on submission flow, under the Privacy Policy checkbox, with the text `This add-on requires payment, non-free services or software, or additional hardware.`. It should have a help icon, like the one for the Privacy Policy, with some additional information: `Check this box if this add-on's core features require some form of payment upfront or after a trial period in order to work.`.
- [ ] Add the same checkbox to the Edit Information page in the Developer Hub for add-ons. It can be added under Basic Information, under the Experimental flag.
- [ ] Expose the value of that flag in the review page for add-ons. It can be placed in the metadata section at the top, under the Privacy Policy. The label can be `Requires payment` and Yes/No the possible values. 

The end-user bits are in the frontend issue.

**Comment by muffinresearch** [comment]
@eviljeff would you have a moment to fit this around other things for next week?

**Comment by eviljeff** [comment]
@jvillalobos can/should I re-purpose the external software property?  Doesn't seem to be exposed anywhere outside of devhub anyway.

**Comment by wagnerand** [comment]
> @jvillalobos can/should I re-purpose the external software property? Doesn't seem to be exposed anywhere outside of devhub anyway.

I would advise against it. I kept this field to expose an external software requirement using nativeMessaging (see https://github.com/mozilla/addons-server/issues/3841#issuecomment-273118949)

**Comment by eviljeff** [comment]
@wagnerand "expose" it to who?  I read #3841 but it's not exposed anywhere outside devhub so the only person who sees it is the developer.

**Comment by wagnerand** [comment]
It's not exposed **yet**. I want to expose it to users to help them make an informed decision on whether to install the add-on, like with payment, privacy policy etc.

**Comment by jvillalobos** [comment]
Let's not re-purpose the field, since it might still be used in the future.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix screenshots:
![2017-07-17_1736](https://user-images.githubusercontent.com/15685960/28274312-3cf591ba-6b19-11e7-9316-07bb060bcfff.png)
![basicinfo](https://user-images.githubusercontent.com/15685960/28274380-68bb470e-6b19-11e7-8565-4527c82da2f5.png)
![revt](https://user-images.githubusercontent.com/15685960/28274393-6ebb4f5a-6b19-11e7-847f-285d409010c5.png)
![no](https://user-images.githubusercontent.com/15685960/28274523-d1e5aef4-6b19-11e7-8e8a-49f12687aec1.png)
