### ISSUE TITLE
Add-on review developer reply email subject is confusing

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#4961]
Since reviewer<>developer communication now happen in AMO and less via email/amo-editors, reviewers get emails about developers having replied.

The subject for these kind of messages is: "Mozilla Add-ons: addonnamegoeshere Updated". This subject is confusing since it has the same subject as update notifications, I therefore missed a couple of replies these past few days because I thought they were just update notifs.

I'd suggest to switch to something more relevant: "Mozilla Add-ons: add-onnamegoeshere Developer Reply" or similar.

**Comment by wagnerand** [comment]
I'd like to have the version number in the subject as well, for easy distinction between emails for the same add-on but different versions.

**Comment by eviljeff** [comment]
`Mozilla Add-ons: add-onnamegoeshere 1.1 Reply` ?
or
`Mozilla Add-ons: add-onnamegoeshere 1.1 Developer Reply` and `Mozilla Add-ons: add-onnamegoeshere 1.1 Reviewer Reply`

**Comment by wagnerand** [comment]
The latter if it's not too much of a hassle, otherwise the former :)

**Comment by ValentinaPC** [comment]
Verified in AMO-dev FF52(Win 7) using Admin Tools- Fake Mail logs page, but **no "developer reply"**, only "reply"+ add-on name and version number - is this ok?
Please see screenshots:
![version-listed](https://cloud.githubusercontent.com/assets/15685960/24042812/4eb2f814-0b1c-11e7-9f61-be3b23779cc3.png)

And, another thing, while adding a file to a version, a mail is generated every time a new file is added (the developer will receive 2-3 or 4 IDENTICAL mails). 
Because of automatic validation, in the case of unlisted add-on the mail received at version submission will look exactly the same as the one received during file submission.
Example: 
![new_file](https://cloud.githubusercontent.com/assets/15685960/24043212/39358bbc-0b1e-11e7-8dc6-fb176fddf5d5.png)

**Comment by eviljeff** [comment]
it's the subject line of the email, rather than the email body - it's in the headers in fakemail.

re: the emails you get for uploading new files - it will have been a bug since unlisted addons were first added and auto-approved.  (I guess few developers of add-ons with unlisted versions bother with multiple files).  Can you log an issue?

**Comment by ValentinaPC** [comment]
> - it will have been a bug since unlisted addons were first added and auto-approved.

For sure, but did not think is worth logging it until I saw this issue.

Logged #4985 

Regarding the initial issue, "reply" text is ok instead of intended "developer reply"?
I'll mark this verified-fixed, please reopen if other result is expected.
