### ISSUE TITLE
Add-on developer reply email has escaped characters

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#4962]
Received an email about a new developer reply, but the contents of their reply were partially escaped:
` So I&#39;d grateful` instead of `I'd`.

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-server/issues/6505#issuecomment-347204736

**Comment by jvillalobos** [comment]
We send these to developers all the time, so I'm bumping this up a bit.

**Comment by diox** [comment]
The activity templates are plain text, so we need to 1) make sure they are not sent as HTML 2) disable auto-escaping in them.

**Comment by eviljeff** [comment]
@ioanarusiczki this issue is about developer replies to an addon review, i.e. reviewer tools, not a user rating (which is still incorrectly referred to a review in some places.)

**Comment by ioanarusiczki** [comment]
@eviljeff I am sorry for misunderstanding the issue. 

I verified the dev replies for add-on reviews with the fakemail. 
The I'd issue is fixed. 
![fixedtext](https://user-images.githubusercontent.com/33448286/38627505-ce011d7a-3db7-11e8-8069-ad5370dd55b9.png)

First question:

HTML text is displayed as in the screenshot below. Please let me know if this is the expected behavior.
![html text](https://user-images.githubusercontent.com/33448286/38627739-59ef1742-3db8-11e8-85b8-2dab0ac65c38.png)
![html2](https://user-images.githubusercontent.com/33448286/38627917-c088133c-3db8-11e8-818b-bc798f9b1ce2.png)
 
Second question would be if should I file a new issue for the developer responses for the user reviews since the "I'd" issue is reproducible there.  

Thank you!

**Comment by eviljeff** [comment]
@ioanarusiczki they're sent as plain text so a bit of html syntax is fine - and likely will have been what the author of the message intended.

>Second question would be if should I file a new issue for the developer responses for the user reviews since the "I'd" issue is reproducible there.

Yes please.  Unfortunately the email's are generated in different ways so each instance needs to be handled separately.
