### ISSUE TITLE
Block Blank User Reviews

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#4964]
Recently, I have noticed a large number of blank user reviews. I suspect they are by some post-bots.
Blocking blank user reviews seems like a good idea.

**Comment by jvillalobos** [comment]
We're supporting blank reviews now. The recent ones come from the mobile site, which is the first one to support this. The desktop site will support it in the future as well.

**Comment by gumadozucia** [comment]
Please reconsider. The current review system is great and really makes it easier to choose add-ons which are well developed.

If you want to add rating which don't require a comment maybe you could implement them as a separate rating and allow only thumbs up/down votes, because this is what those useless reviews will amount to anyway.

**Comment by erosman** [comment]
The Blank reviewer has become the new method of spamming reviews.

The are scores of **Anonymous user ****** who register for the sole purpose of leaving good or bad reviews for competing addons.

I am not sure what purpose it serves to allows such spams.
