### ISSUE TITLE
Hide rating with empty reviews

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4966]
The new mobile design allows ratings without leaving a review, which confuses both users and reviewers, because they think it's spam.

Let's hide empty reviews on both the listing and reviews page, except your own.

**Comment by jvillalobos** [comment]
Note that this bug is about hiding ratings without a written reviews (except your own) in the desktop site.

**Comment by ParticleCore** [comment]
Found this after posting a thread regarding review spam by anonymous users.

Am I understanding correctly that this kind of situation is actually intended and will become a norm? https://discourse.mozilla-community.org/t/massive-review-spam-from-anonymous-users/14499

The most appealing and beneficial aspect of AMO, which was vastly superior to the Webstore, was that the reviews actually had to contain review content, which was a valuable feedback for other users and the developer, not just popularity star spam with no justified reason for giving 1 star ratings or 5 star ratings.

Is AMO suppose to become a facebook like-dislike style mess? If a user likes the add-on he gives 5 stars, if he doesn't he gives 1 star, none with no reason whatsoever.

Because if it is then I might as well just stop using AMO because with this aspect gone and with the excruciating long review queues of new add-on versions makes this entire ordeal worthless seeing that some of those reviews can be direct consequence of users not getting the updated add-on version which has been stuck in the review queues for over a month.

**Comment by jvillalobos** [comment]
> Am I understanding correctly that this kind of situation is actually intended and will become a norm?

Yes.

> Has there been any official announcement regarding what @wagnerand and @jvillalobos said?

No, the mobile site was launched very recently and we haven't made an official announcement about it because there are still some bugs being addressed before we're more comfortable talking about it broadly.

> I just checked and my add-on was marked as android compatible. Isn't there a way to exclude android in the manifest?

Not including Android compatibility is sufficient. When you submit, just make sure the Android checkbox isn't selected. If you need to retroactively change it for one of your add-ons, go to the Status & Versions page, click on the versions you want to change, and edit the Compatibility section for each.

**Comment by jvillalobos** [comment]
Let's also not hide empty ratings for users with the `Addons:Edit` permission. We need easy access to them to check for spam.

I should add that the effects of the new rating system on the desktop site were an oversight on my end, so I apologize for that.

**Comment by ParticleCore** [comment]
Thanks for replying, but I really think that this should be announced asap and be made very clear what the goal is and the reasons behind it. The confusion it has caused (and might cause further down the road) could be avoided by providing this kind of information.

**Comment by vcarciu** [comment]
Your own empty reviews are not displayed in listing pages, only on reviews pages. Same issue for users with Addons:Edit permission : 
![review](https://cloud.githubusercontent.com/assets/1583842/25441132/0c65f990-2aaa-11e7-96a8-5a1a65ef95f6.gif)

The rest of cases are fixed.

**Comment by eviljeff** [comment]
Yeah, that was a deliberate decision.  The listing page content is heavily cached and I didn't want to throw in a per-user change that may break that.  

On the listing page the top few reviews we show are always sans-empty-reviews; the full review page shows your own empty reviews, or all empty reviews for admins as specified.

@jvillalobos and @wagnerand can comment if that's okay

**Comment by jvillalobos** [comment]
It's okay with me.

**Comment by eviljeff** [comment]
closing as per https://github.com/mozilla/addons-server/issues/4966#issuecomment-297485034 then

**Comment by vcarciu** [comment]
Verfied as fixed then . Empty reviews are hidden in the other cases

**Comment by erosman** [comment]
Blank reviews nonetheless affect the graphical rating display which has created a new avenue for the spammers to spam AMO and alienate developers.
