### ISSUE TITLE
Developer cannot reply to rejected version

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4972]
### Describe the problem and steps to reproduce it:

After a version has been rejected, developers cannot reply to the rejection email.

### What happened?

They get the following email back when replying:

An email was received, apparently from you. Unfortunately we couldn't process it because of:
You can&#39;t reply to this email as the reply token is no longervalid because it&#39;s for an old version of the addon.

### What did you expect to happen?

Developers should be able to reply to a rejection email.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment]
Please include a link to the ~page~ addon

**Comment by wagnerand** [comment]
https://addons.mozilla.org/en-US/editors/review/scrapbook-x

**Comment by wagnerand** [comment]
Now, **I** am getting the same error for a different add-on:

I tried to reply to https://addons.mozilla.org/en-US/editors/review/mac-dot-kpm-at-kaspersky

but got an email saying:

An email was received, apparently from you. Unfortunately we couldn't process it because of:
You can&#39;t reply to this email as the reply token is no longervalid because it&#39;s for an old version of the addon.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF52(Win 7) and there are 2 cases:
- I was able to reply to the mail I receive after the **only version of my add-on was rejected** - no e-mail was received afterwords.
- If I've replied to the mail I received, after rejecting first version of an add-on, **that also has a second version** - I received an e-mail as @wagnerand mentioned in his comment.

I think this is happening because, in Dev Hub also, you can add a "reply" only to **last version** of an add-on.

@eviljeff Is the behavior correct? 

Add-on: https://addons-dev.allizom.org/en-US/developers/addon/activity-rejectvrs/edit

**Comment by eviljeff** [comment]
correct, you should be only able to reply to the last (non deleted, non beta) version of an add-on.

**Comment by ValentinaPC** [comment]
> correct, you should be only able to reply to the last (non deleted, non beta) version of an add-on.

From Dev Hub and from your Inbox, as well, correct?

**Comment by eviljeff** [comment]
yeah.  But the logic isn't defined in one place so there's a possibility they might be different (incorrectly)
