### ISSUE TITLE
Inconsistency between AMO and desktop description for host permission

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#5013]
**Steps to reproduce:**
1. Navigate to https://addons-dev.allizom.org/en-US/firefox/addon/promptable321/
2. Compare the permission description from desktop pop-up with amo pop-up.

**Expected results:**
Amo and desktop pop-ups display the same descriptions.

**Actual results:**
AMO pop-up specifies the entire url, including the “*” parts.

**Additional notes:**
- This issue reproduces on AMO-dev using Firefox 55.0a1 (2017-03-22) under Windows 10 64-bit.
- Please see the attached screenshot for this issue:

![2017-03-23_1150](https://cloud.githubusercontent.com/assets/18114210/24241962/1d5b8b44-0fbf-11e7-96b0-acdad71afafa.png)

**Comment by diox** [comment]
@eviljeff do we care?

**Comment by eviljeff** [comment]
It would be nice if they were the same - and Firefox's messaging is more user friendly - but I don't think it's essential.  
Also the problem is there isn't a written spec of how Firefox's permission UX is supposed to work so we're limited to copying how it appears to work (or reading all the code) then doing it again each time someone changes Firefox.

In this particular case, AMO is displaying the exact host permission text in the manifest, whereas Firefox is 'prettying' the output by just showing the host.

**Comment by muffinresearch** [comment]
> In this particular case, AMO is displaying the exact host permission text in the manifest, whereas Firefox is 'prettying' the output by just showing the host.

I think this is good enough.
