### ISSUE TITLE
Average ratings should be calculated using the latest review for each user only

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5059]
Steps to reproduce:
1. Leave two reviews to the same add-on on desktop 
2. Go to mobile page of this add-on i.e https://addons.allizom.org/en-US/android/addon/login/?src=ss
3. Verify the average rating stars

Expected results:
Average is calculated correctly.

Actual results:
Average is not calculated correct.

Notes/Issues:
- on mobile only the last review is displayed, even if the average is made after the number of reviews available on desktop, in this case 2.

Verified on Ff52(Android 6.0.1, Win 7). Issue is reproducing on stage and dev.
Video for this issue:
![videotogif_2017 03 29_17 55 28](https://cloud.githubusercontent.com/assets/15685960/24461945/6ae427e0-14ab-11e7-9c31-fdd40b330498.gif)

**Comment by ValentinaPC** [comment]
I just observed I've logged it in the wrong place...or...not?

**Comment by diox** [comment]
No, it's fine: the average rating calculations are done by addons-server.

**Comment by diox** [comment]
I've got [a branch that implements this](https://github.com/diox/olympia/tree/improve-reviews-aggregate-query), but I want to get a second opinion on this.

@jvillalobos doing this will lower the total reviews count (since older reviews from a given user would be ignored) and alter the averages (for the same reason). Does that seem ok to you ? It seems fair to me but at the same time changes the existing behavior, so I'd prefer to check with you.

**Comment by jvillalobos** [comment]
Yes, it makes ratings more accurate, so I'm okay with it.

**Comment by diox** [comment]
QA: note that the fix will only be applied once a new review/rating is posted for each affected add-on.
