### ISSUE TITLE
Make database migrations work locally in Docker

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#5102]
### Describe the problem and steps to reproduce it:

Get new code for development with a command like this:
````
git pull && docker-compose pull && docker-compose up -d && make update_docker
````

### What happened?

The database migrations fail. Every. Single. Time. (Well, it feels like it.) It's usually some kind of foreign key constraint because of mismatched column types. 

### What did you expect to happen?

I just want want my rug back, man. It really tied the room together. Does life need to be this hard?

### Anything else we should know?

Can we just sync docker mysql with production mysql somehow?

**Comment by kumar303** [comment]
Example: https://github.com/mozilla/addons-server/pull/5091#issuecomment-291648954

**Comment by diox** [comment]
> Can we just sync docker mysql with production mysql somehow?

That's super annoying to maintain. Sure, you can do this once, but it needs to work for a new env as well... So you'd have to hack something around which migration to start from, and hope for the best... The real solution is to sync production with the django models, and then use django migrations instead of schematic and stop this nightmare... but for that, we need time.

**Comment by kumar303** [comment]
I guess my real feature request is "make DB migrations work in Docker." I don't care how it happens.

**Comment by diox** [comment]
That's https://github.com/mozilla/addons-server/issues/3705
