### ISSUE TITLE
Multipack extension containing unsigned add-ons does not raise a warning at validation

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5119]
Steps to reproduce:
1. Submit a multi-pack extension containing unsigned add-ons

Expected results:
A warning about this is displayed during submission.

Actual results:
No warning.

Notes/Issues:
Verified on FF55(Win 7). Issue is reproducing on all AMO-servers.
Used extension: https://addons.allizom.org/en-US/firefox/addon/multipackaddon-test/

**Comment by EnTeQuAk** [comment]
is this referring to https://developer.mozilla.org/en-US/Add-ons/Extension_Packaging#Multi-item_extension_XPIs and the warning "From the release of Firefox 53, multiple item extension packages are no longer supported and will not load. As a consequence, these packages are no longer accepted by AMO."?

Given that we don't accept legacy add-ons anymore I assume this can be closed?

Please feel free to re-open if I misunderstood the issue here.

**Comment by ValentinaPC** [comment]
@EnTeQuAk : can we show this text at submission or is to much of a trouble? 
Also, my multi pack is a hybrid: an extension containing a complete theme, a legacy add-on and a webextension.
Thanks!

**Comment by EnTeQuAk** [comment]
That is indeed a good idea, I'll see if we can add a warning.

**Comment by EnTeQuAk** [comment]
I don't think we'll get to do this and given that submission of legacy add-ons has long been disabled now and they're even disabled I'm going to close this.
