### ISSUE TITLE
Upgrade bleach to version 3.x

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#5182]
See https://github.com/mozilla/addons-server/pull/4883 for a few more details.

blocked by mozilla/bleach#271

**Comment by eviljeff** [comment]
Bleach master now (apparently) has a fix ready https://github.com/mozilla/bleach/issues/271#issuecomment-422941487 https://github.com/mozilla/bleach/tree/a6b14bd994d47824e313d0f2ce3d1b487b2ef650 or later has the fix so first step will be swapping out the dep from pypi for the github commit and running it against our tests to see if everything passes (ideal!) or the output is otherwise reasonable now.

If we give the thumbs up a new release on pypi will follow soon and we can switch to it properly.

**Comment by eviljeff** [comment]
https://github.com/eviljeff/olympia/tree/5182-upgrade-bleach-test implements the new Bleach and 
we're down to one remaining failure: https://travis-ci.org/eviljeff/olympia/jobs/432833974#L2809

From some digging it's coming from `bleach.linkify` rather than `bleach.clean`:
`bleach.linkify('<foobaa>') == u'<foobaa></foobaa>'`.  I'm going to enquire with willkg but it's possibly something we can workaround or ignore.

**Comment by eviljeff** [comment]
Looks like the linkify issue has been reported mozilla/bleach#392 already

**Comment by eviljeff** [comment]
`PurifiedTranslation.clean_localized_string` (https://github.com/mozilla/addons-server/blob/master/src/olympia/translations/models.py#L195:L200) calls `urlresolvers.linkify_with_outgoing` which (as the name implies) does linkify, _then_ we do `bleach.clean`.  We would need to rewrite that to do the outgoing+linkify as a filter for clean

**Comment by eviljeff** [comment]
Bleach v3.0.0 is out https://pypi.org/project/bleach/ and the linkify issue appears to have been fixed anyway (mozilla/bleach#392) so we might not have much to do beyond https://github.com/eviljeff/olympia/tree/5182-upgrade-bleach-test

**Comment by AlexandraMoga** [comment]
@eviljeff is there any testing required here?

**Comment by eviljeff** [comment]
QA - bleach is used to sanitize all the user input to strip out html (or non-allowed html) and to wrap links with outgoing.xxx, so check the fields on addons (in devhub edit details) and by leaving a text review on a rating.  

Where html is not allowed it should all be escaped, and where some is allowed (there's always a note next to the field saying what's allowed) then only that should be allowed, an other html escaped.  Links should be wrapped.  Collection description shouldn't have _any_ links, either wrapped or in plain text.

**Comment by AlexandraMoga** [comment]
Verified on -dev with FF62, Win10x64

Results:
- links are wrapped
![image](https://user-images.githubusercontent.com/31961530/46718905-58ed8080-cc75-11e8-88fb-bd51a888c4b1.png)
- links are not allowed in collection descriptions
![image](https://user-images.githubusercontent.com/31961530/46718921-686cc980-cc75-11e8-9282-7a907ec26d56.png)
- all allowed html tags (as specified in the Add-on description field from dev hub edit information page) are rendered correctly 

@eviljeff regarding escaped html, I'm not sure I'm seeing the right behavior. For example, if my input in a text field is `&quot;`, I would expect the output (after saving) to be `&quot;` in plain text, not **"**
Here are some examples. Note that this was the same before the bleach upgrade.


1. **[Add-on Name - Dev Hub and details page - HTML not allowed]**
![image](https://user-images.githubusercontent.com/31961530/46719749-660b6f00-cc77-11e8-9eec-69b40d30a403.png)

2. **[Add-on Summary - HTML not allowed]**
![image](https://user-images.githubusercontent.com/31961530/46719782-77ed1200-cc77-11e8-9398-0f1781d0b0cc.png)

3. **[Add-on Description - some HTML allowed]**
![image](https://user-images.githubusercontent.com/31961530/46719807-8fc49600-cc77-11e8-9afd-f5625a9e8490.png)

4. **[Add-on Review - HTML not allowed]**
![image](https://user-images.githubusercontent.com/31961530/46719829-9e12b200-cc77-11e8-8028-5367ce0607b2.png)

I've also filed two issues - https://github.com/mozilla/addons-frontend/issues/6232 and https://github.com/mozilla/addons-frontend/issues/5828 - some time ago which might be related to this.

**Comment by AlexandraMoga** [comment]
Agreed with eviljeff that the current behavior is acceptable from a security perspective and since there weren't any regressions caused by the bleach upgrade, this issue can be marked as verified fixed.
