### ISSUE TITLE
Selectively import addon data from production

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#5199]
Following a discussion from ops re: data importing from production it was suggested the best approach would be for engineering to write some scripts to import selective data from production on a periodic basis. 

Open questions:

* Would we start -dev / stage from scratch when running this or just overwrite imported data?
* Aside from a list of required add-ons would we also want to improve fake data addon generation
* What data do we need aside from db data? Xpis etc?
* What provisions do we need to make to ensure we're only pulling public data.

This issue needs discussion to explore potential problems with such a script and to think through any additional considerations whilst also considering any other viable approaches.

**Comment by muffinresearch** [comment]
Pinging @diox + @EnTeQuAk for input.

**Comment by diox** [comment]
FWIW, a while ago it was decided to do the exact opposite on both Marketplace and AMO, because it was too hard to fully anonymize the data ; Sadly, the work to create the data from scratch was never truly completed on AMO.

That's probably still the main concern. Even if we did anonymize all personal information, there is still the matter of deciding whether or not to import disabled or even just unlisted files.

**Comment by muffinresearch** [comment]
Ok I think we need to start this over and kick off with the problems that we currently have wrt to data and then work out the best solutions to those problems - @andymckay has also raised concerns around moving prod data anywhere in any capacity. Any concerns around privacy etc are definitely very valid.
