### ISSUE TITLE
Discuss solutions for data differences between -dev and stage vs prod

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#5207]
Dev and stage currently run old and different data to production. We have a number of problems with this. 

The main one that comes up frequently is that it's very difficult to test the disco pane on -dev or stage because the addons that are setup by id don't necessarily exist on -dev or stage.

Another issue is that we don't test -dev and stage against something that's necessarily representative of production, for example the addon xpis on -dev and stage are different and that can cause misleading bugs if an issue is caused by an out of data xpi.

Let's collect all the problem cases that we currently have and then work out what might be viable solutions to them. 

Ideally we want to avoid anything that moves production data around in any capacity so that takes making selective import scripts off the table for now.

**Comment by muffinresearch** [comment]
Pinging @EnTeQuAk, @diox, @jasonthomas, @bqbn and @andymckay to add input to this.

**Comment by diox** [comment]
I don't have great insights, but I want to emphasize that any solution is not going to be trivial. There are a lot of different database tables and columns, lots of different states the various files can be in, etc. That makes generating proper data difficult and tedious, any solution will take some time to implement.

The way forward is properly to continue adding features to https://github.com/mozilla/addons-server/tree/master/src/olympia/landfill, adding real xpis, images etc when creating fake data, and switch to that source only (wiping dev/stage completely at some point, starting over).

Disco Pane is a bit of a special case, because if we're truly paranoid about testing it, we need prod data, no other way to do it. But I guess we could settle with just creating add-ons with the right id, and don't necessarily test how the xpis behave (since you'd need the real ones for that).

**Comment by diox** [comment]
Worth pointing out that Marketplace did exactly that for dev (keeping stage a prod copy) - at some point it switched from prod imports to generated data, and that seemed to work fine.

**Comment by jasonthomas** [comment]
I think we need QA input on here since they perform the majority of the testing. They may have additional scenarios in their testplan that are not covered here and it would be good insight to see what their needs are to validate the application. /cc @krupa

**Comment by vcarciu** [comment]
Another big difference between -dev , Stage and Prod is the absence of valid statistics data. If we want to keep the Stats as an important part of AMO, we should add accurate data for this section too.

**Comment by bqbn** [comment]
+1 for the above. This sounds like a data generation tool that's going to be more reliable and secure than dumping and restoring databases.

**Comment by eviljeff** [comment]
Missing all non-public add-ons (and non-public versions of those add-ons) seems a significant drawback.  Even among public add-ons and versions the long tail is where there will be the kind of edge cases that are most likely to break our carefully designed code.  For -dev that could be an acceptable loss; for stage it seems too much of a risk.

**Comment by bqbn** [comment]
Just to update that data ops team has reported that https://bugzilla.mozilla.org/show_bug.cgi?id=1450108 is done.

**Comment by willdurand** [comment]
Not sure if this is entirely related but fixtures data generated when developing on addons-server don't have a `guid` value, which breaks addons-frontend detail pages (and likely more stuff).
