### ISSUE TITLE
WebExtension compatibility label is not correctly RTL

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5224]
Steps to reproduce:
1. Load details page of a WebExtension i. e. https://addons-dev.allizom.org/en-US/firefox/addon/webext-simple/
2. Click on the "firefox57" tag
3. Change the language to a RTL one i.e. https://addons-dev.allizom.org/ar/firefox/tag/firefox57
4. Observe the "Compatible with Firefox 57+" label

Expected results:
Label is RTL.

Actual results:
Label is not correctly RTL.

Notes/Issues:
- I think the "`+`" mark should stay after "`57`", or at the end of the label after the "`+`" from the "Add to Firefox" button.

Verified on AMO-dev FF53(Win 7).
Screenshot for this issue:

![2017-04-21_1637](https://cloud.githubusercontent.com/assets/15685960/25280258/f90f4014-26b1-11e7-8f10-5ec400074b0a.png)

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 
@tofumatt

**Comment by atiqueahmedziad** [comment]
I think the web extension compatibility label is just fine. Because in RTL we read from right to left. When the label will be translated, then the label will be like this `+57 Firefox With Compatible ` (Read it from right to left). So, the `+` sign on the left side is fine for RTL since it is placed after `57`.
In **LTR**, 
`Compatible with Firefox 57+`
In **RTL**,
`+57 Firefox With Compatible`

Like above, in "Add to Firefox" button the `+` sign is before the word "Add to Firefox". So, in both LTR and RTL the `+` sign in placed before the word "Add to Firefox".
In **LTR**, 
`+ Add to Firefox`
In **RTL**,
`Firefox to Add +`

**Comment by ValentinaPC** [comment]
@atiqueahmedziad : as you can see in my screenshot, the `+` is not placed after `57` but in the opposite part.
Thanks for your reply!

**Comment by tsl143** [comment]
@ValentinaPC I think this is already fixed by some other patch :)

<img width="1222" alt="screen shot 2017-08-17 at 4 14 16 pm" src="https://user-images.githubusercontent.com/5318732/29408786-34016a14-8367-11e7-9cbd-da71981012f4.png">

<img width="1214" alt="screen shot 2017-08-17 at 4 14 22 pm" src="https://user-images.githubusercontent.com/5318732/29408809-4ad9f148-8367-11e7-8c58-ea2b272b1f1f.png">

**Comment by ValentinaPC** [comment]
As you can see in my screenshot, the problem is in listing pages, not add-on details: https://addons-dev.allizom.org/ar/firefox/search/?q=webext&platform=windows&appver=
![listing](https://user-images.githubusercontent.com/15685960/29412037-cd6a8f12-835f-11e7-81bb-7731909057a3.png)

Thanks a lot, for your reply!

**Comment by tsl143** [comment]
Oh, my bad :(
I will take this bug to fix  :)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix screenshot:
![rtl](https://user-images.githubusercontent.com/15685960/29459961-9966e1b4-842e-11e7-86c3-472a681de8cb.png)
