### ISSUE TITLE
All legacy add-ons (non-webextensions and themes) need a strict max version of Firefox 56.*

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5277]
Firefox 57 won't support legacy add-ons. Specifically:

* All extensions that aren’t WebExtensions.
* Complete themes.

All legacy add-ons will need to show up as incompatible with Firefox 57 and above. So, for legacy add-ons that don't already have strict compatibility set, we should set it to a `maxVersion` of `56.*`. This only applies to compatibility with desktop Firefox, since compatibility with Android will probably be handled differently.

**Comment by muffinresearch** [comment]
@jvillalobos do we have a target date for getting this done? Presumably 57 nightly (2017-08-07)?

**Comment by jvillalobos** [comment]
Yes, we should aim to have this before 57 hits Nightly.

**Comment by jvillalobos** [comment]
I should also add that we decided [Android will follow the same compatibility path](https://blog.mozilla.org/addons/2017/05/18/compatibility-update-android/), so this issue now applies for Firefox and Firefox for Android.

**Comment by diox** [comment]
List of things to do on the top of my head:
- Stop considering legacy extensions in compatibility bump task/tool
- Forcefully set max compatibility version to 56 in database for legacy extensions
  - Forcefully set strict compatibility on those files as well

**Comment by jvillalobos** [comment]
> Stop considering legacy extensions in compatibility bump task/tool

The bulk compatibility tool only works with legacy add-ons because it uses the old validator. We don't plan to continue using it with WebExtensions add-ons so I don't think any specific action is required here.

**Comment by yfdyh000** [comment]
A question, https://wiki.mozilla.org/Add-ons/Firefox57 says Firefox 57 allows Legacy Extension with pref in Nightly. Set the strict compatibility affect users to enable them with pref in Firefox 57? Whether the users must to disable the add-ons blacklist or create a specific preference to enable them.

**Comment by diox** [comment]
@jvillalobos : 

Current behavior for strict compatibility is to:
- Grey out the install button, add a small "Not available for Firefox xxx" text, as a well as a help message detailing why the add-on is not available
- When the greyed install button is clicked, display a warning and repeats the same help message, and allow installs through an "Install anyway" button.

Do we want to keep these 2 things for the 57 incompatibility of legacy add-ons? If so, should the help message change ? It currently says "Add-on has opted into strict compatibility checking." which would be technically untrue in this scenario.

See also @yfdyh000's question :)

Screenshot of current behavior described above (ignore the fact that it's for 56.0 and not 57.0):

![strict_compat](https://user-images.githubusercontent.com/187006/28172353-9ea2f19a-67eb-11e7-960b-21bf9f3bc5ad.png)
![strict_compat_install](https://user-images.githubusercontent.com/187006/28172577-38463d3e-67ec-11e7-9106-58497e324957.png)

**Comment by yfdyh000** [comment]
My question is whether the Add-on Manager will follow the strict compatibility, so users must disable a preference to enabled the installed add-ons.

**Comment by diox** [comment]
Add-on manager behavior is out of scope here, I can't tell you what it will do.

**Comment by jvillalobos** [comment]
> My question is whether the Add-on Manager will follow the strict compatibility, so users must disable a preference to enabled the installed add-ons.

I think the question is whether these changes on AMO will override that Firefox is doing. I think the answer is 'no'. Even if they did, there's a separate pref in Firefox to disable compatibility checking, which should be enough to turn off strict compatibility checking.

**Comment by jvillalobos** [comment]
For add-ons affected by this change, let's:

1) Remove the popup in the installation button. It should be greyed out and nothing happens if you click on it.
2) Keep the text below it. Change the contents of the tooltip to just `This add-on is not compatible with your version of Firefox.`.

**Comment by diox** [comment]
@jvillalobos : removing the popup and preventing the installation button to work entirely means that it won't be possible to nightly users to install those add-ons at all as soon as we turn that restriction on, though. Is that what we want?

Related question: should this be behind a waffle switch or can it go live as soon as it's ready?

**Comment by jvillalobos** [comment]
> Is that what we want?

They won't work anyway, so I don't see much use in allowing installation.

> Related question: should this be behind a waffle switch or can it go live as soon as it's ready?

Behind a waffle switch, please. We should enable this in tandem with the restriction being turned on on Nightly.

**Comment by diox** [comment]
@jvillalobos spent a lot of time trying to figure out the current compatibility code and I know have the beginning of a plan, but I need your approval on this:

- Fix search filtering on app version : filter out extensions with min version higher than app version or (if strict compatibility is enabled) max version lower than app version
- Default to disabling version compatibility filters entirely when searching on AMO with Firefox < 57
- Remove support for Firefox < 10.0 that still exist in AMO (!)
- Hide the install button for incompatible add-ons entirely (everywhere, unifying behaviour) when they are shown (i.e. in search when filtering is not applied, detail page/homepage, etc) and instead, show an expanded compatibility explanation and a link to the All Versions page.
- Remove the popup explanation about strict compatibility / binary components / etc when showing an incompatible add-on (the one that appears when you click on the "?" symbol in the compatibility text - remove that sympbol as well)
- Specifically for legacy extensions, set maximum version to 56.* and enabled strict compatibility (and don't let developers change it)


It's going to be quite tricky to do things behind a waffle, because the way the compatibility code is spread over all the codebase (html/js/python). Is it possible to implement everything directly instead except the second point (defaulting to no version incompatibility filtering when searching with Firefox 57)? That part would stay behind a waffle, ready to

**Comment by jvillalobos** [comment]
The list looks good. Just one note:

> Specifically for legacy extensions, set maximum version to 56.* and enabled strict compatibility (and don't let developers change it)

Some legacy add-ons may already have strict compatibility set with a max version that is lower than 56.*, so we should respect it in those cases.

> Is it possible to implement everything directly instead except the second point (defaulting to no version incompatibility filtering when searching with Firefox 57)?

That's okay with me, but I will need a heads up for when this will happen in case we need to publish something about it.

**Comment by diox** [comment]
There is a mechanism in place to add admin overrides to add-ons compatibility info (`CompatOverride`), but it's not an ideal tool for the job, because it's completely generic: it does not care why the override is there, it just applies it. It would not know whether a particular version is legacy or not and thus
whether or not the override should continue to be applied when a new version is uploaded.

I will therefore continue on my original plan.

@jvillalobos : I'll be adding an error at validation if a developer tries to upload a legacy extension that indicates it's compatible with Firefox 57 or newer. What should the message say ? So far I've got "Legacy extensions are not compatible with Firefox 57 or higher. Consider upgrading your extension to a WebExtension instead.".

**Comment by jvillalobos** [comment]
`Legacy extensions are not compatible with Firefox 57 or higher. Use a maxVersion of 56.* or lower.`

I think legacy devs are already tired of hearing about WebExtensions :|

**Comment by diox** [comment]
QA: 
* Legacy extensions should not be allowed at submission time if they target 57 or higher. Since it was already the case for new uploads (legacy uploads were not allowed unless targeting 53 strictly), this mainly concerns updates. Note that at the moment Complete Themes are not restricted at upload. I plan to do this in #5133
* At upload time, legacy extensions should have strict compatibility enabled for them without the possibility of changing it.
* At upload time, legacy extensions targeting `*` should be downgraded to targeting `56.*` as their `maxVersion` instead, silently.
* Developers should be prevented from setting any legacy extension as compatible with Firefox 57 or higher in devhub

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7) and obtained the following results:

> Legacy extensions should not be allowed at submission time if they target 57 or higher. Since it was already the case for new uploads (legacy uploads were not allowed unless targeting 53 strictly), this mainly concerns updates. Note that at the moment Complete Themes are not restricted at upload. I plan to do this in #5133

- Updates for legacy add-on are not allowed if new version is targeting 57.0 - a suggestive message is displayed;
- updates with `maxversion` like `56.0`/`56.*` or under are working;
![newvers-57](https://user-images.githubusercontent.com/15685960/29071086-bd9fc19a-7c4a-11e7-902e-3cac68b85c4b.png)

> At upload time, legacy extensions should have strict compatibility enabled for them without the possibility of changing it.

- not sure about this - "strict compatibility enabled for them without the possibility of changing it" - strict compatibility was set by me in `install.rdf`. I can also delete the option and submit a new version without any issues. Please give me more details. Thanks!

> At upload time, legacy extensions targeting * should be downgraded to targeting 56.* as their maxVersion instead, silently.

- updates having `maxversion - *` are successfully made, and changed in "Manage Status and Versions' page with `56.*` - i.e. https://addons-dev.allizom.org/en-US/developers/addon/saveas/versions/1532747

> Developers should be prevented from setting any legacy extension as compatible with Firefox 57 or higher in devhub

- `maxversion` in Dev Hub is `56.*`
![maxvers_in_dev_hub](https://user-images.githubusercontent.com/15685960/29071071-a6c62a4a-7c4a-11e7-88ef-e6f30f9c2748.png)

**Comment by diox** [comment]
> * not sure about this - "strict compatibility enabled for them without the possibility of changing it" - strict compatibility was set by me in install.rdf. I can also delete the option and submit a new version without any issues. Please give me more details. Thanks!

What I mean is that now, for legacy add-ons, even if strict compatibility is not set in `install.rdf` it will be set behind the scenes, *in the database*. It's what forces the add-on to then be hidden from search results if the client version is higher than the max version (when strict compatibility is enabled for an add-on, its max version is honored when searching and filtering w/ a Firefox version - otherwise it's ignored)

**Comment by ValentinaPC** [comment]
Thanks for the explanations!
While setting the `maxversion` for a new version of a legacy add-on to 56.0, deleting the `strictCompatibility` option from `install.rdf`, using a browser with version higher than `maxversion`, FF57, the legacy add-on will be hidden from search.
- Example: https://addons-dev.allizom.org/en-US/firefox/addon/saveas/?src=search

Based on this and the above comment this can be marked as verified fixed.
