### ISSUE TITLE
Querying saved reviews with the API is broken for admins

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#5288]
### Describe the problem and steps to reproduce it:

* log in to `addons-frontend` as an Admin (e.g. go to https://addons-dev.allizom.org/ and click 'View Mobile Site')
* go to an add-ons detail page
* select a star to rate it
* refresh the URL using the browser refresh button

### What happened?

The saved stars disappear

### What did you expect to happen?

The saved stars should appear just as you had selected them

### Anything else we should know?

This is a regression caused by: https://github.com/mozilla/addons-server/commit/b098079c45f#diff-e765b320da36dae52a4fb1bf0d08ada9R400

Displaying saved stars works by making an API request that looks something like this:

````
curl 'http://localhost:3000/api/v3/reviews/review/?user=1&addon=23&version=23'
````

If I comment out the code I linked to up above then it works. Also, logging in as a non-admin shows the saved stars as expected. Note that these review objects have a None type `body` because they are selected stars, not full text reviews.

**Comment by EnTeQuAk** [comment]
Assigning @eviljeff given that it's his commit and he probably knows best how to fix this. But please feel free to re-assign :)

**Comment by eviljeff** [comment]
Is the API request authenticated?  If it was the review should included because it's [your review](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviews/views.py#L397) (and because you're an admin)
Secondly, you're sure it only affects admins?  They [specifically](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviews/views.py#L396) shouldn't get any extra filtering.

**Comment by kumar303** [comment]
This will be fixed by https://github.com/mozilla/addons-server/issues/5297 so I'm closing it in favor of that one.
