### ISSUE TITLE
Version number of the add-on listed in the Auto-Approved queue is not correct

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5293]
Steps to reproduce:
1. Submit a new version for a listed public add-on that qualified for auto-approve i.e. https://addons-dev.allizom.org/en-US/developers/addon/webext-simple/versions (v12)
2. Go to Reviewer Tools - Queues - Auto Approved Add-ons - https://addons-dev.allizom.org/en-US/editors/queue/auto_approved
3. Observe the version number near the add-on name

Expected results:
Version number represents the number of the last auto approved version.

Actual results:
Version number represents the number of the first auto approved version.

Notes/Issues:
- time under "Last Review" column is displayed correctly.

Verified on AMO-dev FF53(Win 7).
Video for this issue:
![versionnumber](https://cloud.githubusercontent.com/assets/15685960/25534523/aff00fe0-2c3c-11e7-9dda-a2a2ce40fec0.gif)

**Comment by diox** [comment]
This is because of the `GROUP BY versions.addon_id` we're doing to exclude duplicate add-ons from the list. Not sure yet how I can fix it without subqueries.

Maybe just displaying the current approved version would be enough ? There could be edge-cases - it could be different from the latest auto-approved if it has been reviewed by a human since, or if the latest auto-approved versions has been disabled since, but that wouldn't be too bad.

To remove the first edge-case, maybe we should also exclude add-ons whose current version was reviewed by a human (i.e., add-ons that have been reviewed by a human after having been auto-approved). But I'm not a fan of doing this, the list would no longer represent all auto approved add-ons.

**Comment by diox** [comment]
**QA:** the version number displayed in that list is now the current public version. It will not necessarily have been auto-approved, but it's an edge case I'm willing to live with for the time being (in the future, all add-ons will be auto-approved anyway)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
The version listed in the `Auto Approved Add-ons` queue is the last public version of the add-on.
Postfix screenhsots: 
![queue](https://cloud.githubusercontent.com/assets/15685960/26000575/264bdf70-3732-11e7-91f6-98c163e1c2de.png)
![review](https://cloud.githubusercontent.com/assets/15685960/26000582/2c79184a-3732-11e7-91dd-fd703c61963e.png)
