### ISSUE TITLE
Signature Verification Error: the signature on this .jar archive is invalid because the certificate used to sign this file has an unrecognized issuer.

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#5300]
Running Firefox on Ubuntu 16.04.2 LTS with WSL. Tried installing my own Firefox 2 theme and it borks on `ignature Verification Error: the signature on this .jar archive is invalid because the certificate used to sign this file has an unrecognized issuer.`
https://addons.mozilla.org/firefox/downloads/latest/firefox-2-theme-for-firefox-3x/addon-6898-latest.xpi

```
1493459038098	addons.xpi	DEBUG	Download started for https://addons.mozilla.org/firefox/downloads/file/616874/firefox_2_the_theme_reloaded-1.0.14.1-fx.xpi?src=api to file /tmp/tmp-d2q.xpi
1493459038144	addons.xpi	DEBUG	Download of https://addons.mozilla.org/firefox/downloads/file/616874/firefox_2_the_theme_reloaded-1.0.14.1-fx.xpi?src=api completed.
Signature Verification Error: the signature on this .jar archive is invalid because the certificate used to sign this file has an unrecognized issuer.
1493459038257	addons.xpi	DEBUG	Starting install of {fd2f951f-77ea-4938-9493-0c892c027a13} from https://addons.mozilla.org/firefox/downloads/file/616874/firefox_2_the_theme_reloaded-1.0.14.1-fx.xpi?src=api
1493459038313	addons.xpi	DEBUG	Addon {fd2f951f-77ea-4938-9493-0c892c027a13} will be installed as a packed xpi
....nothing - can no longer cancel installation in this state. Meh. 
```

**Comment by EnTeQuAk** [comment]
see https://wiki.mozilla.org/Add-ons/Extension_Signing#FAQ that themes don't need to be signed and we don't do that on AMO so I asusme this is the reason why Firefox warns but still installs your theme properly.

If you want the warning to go away for unsigned themes it'd be better to file something in Bugzilla, http://bugzilla.mozilla.org/

I'm going to close this since there's nothing we can do on AMO in that regard.
