### ISSUE TITLE
Leftover strings suggest to put reviewer instructions in the NFR field instead of on the whiteboard

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#5303]
Title. I submitted an update to one of my add-ons and, during the submission process saw this pass by. There's a dedicated whiteboard field for this kind of data, but it still currently instructs developers to put credentials/reviewer instructions (how to review/use the add-on) in the Notes for Reviewers.

**Comment by diox** [comment]
TIL we have a `whiteboard` field...

**Comment by rctgamer3** [comment]
Bump

**Comment by wagnerand** [comment]
What is the exact text for that? What kind of information does the text mean?

**Comment by eviljeff** [comment]
Do we really need both a whiteboard _and_ notes to reviewer?  Can't we drop one of them?

**Comment by jvillalobos** [comment]
Since we're moving to the post-review model, I think it makes less sense to keep the notes to reviewer, since those can be added for each version, and there's no longer an expectation for each version to be looked at.

If the admins agree, we should look into the submission flows and dev pages to make sure we show the right fields and text suggestions at the right time and place.

**Comment by wagnerand** [comment]
I agree with Jorge. We can revisit this when we remodel the reviewer tools

**Comment by ValentinaPC** [comment]
@wagnerand : When will apply these changes?
Now, we still have the NTR during submission.
Thanks!
