### ISSUE TITLE
"Weekly downloads"are 0 for every search tool

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5372]
Steps to reproduce:
1. Load search Tools page on stage i.e. https://addons.allizom.org/en-US/firefox/search-tools/
2. Sort by "Weekly downloads"

Expected results:
Search tools have different weekly downloads numbers.

Actual results:
All search tools have 0 weekly downloads.

Notes/Issues:
- reproducing for CT also;
- it is interfering with testing :) ;

Verified on FF53(Win 7). Issue is **ONLY** reproducing on stage.
Screenshot for this issue:
![wd](https://cloud.githubusercontent.com/assets/15685960/25902248/ba4e79b8-35a1-11e7-8f50-fb3716923808.png)

**Comment by diox** [comment]
I think this is just because we don't have stats data for dev and stage - it's just luck that add-ons were imported with the weekly downloads numbers set correctly in most cases (or bad luck that they are not set for the search tools on stage...).

Not sure what we can do here, maybe set random numbers ? The stats pipeline definitely does not work on dev/stage and it's not trivial to set it up.

**Comment by EnTeQuAk** [comment]
indeed, the issue here is that we don't sync any data from production to stage and production. There is vague plans but until that stage is executed properly (and I assume we'll file separate issues accordingly) this won't ever work for -dev or -stage.

I'm going to close this, it's on our map but given the complexity will take quite some time to figure out.
