### ISSUE TITLE
"Top Rated" sort does not always sort correctly

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#5412]
1. Navigate to https://addons.mozilla.org
2. Type "Video WithOut Flash" into the search box
3. Search for said addon
4. Click "Top Rated"

Scroll down and you will see it is sorted fine until you get to "Flash Player for Youtube". This addon is rated a 5 but the addon before it, "Youtube and more – Easy Video Downloader" is rated a 4.

**Comment by diox** [comment]
I don't have access to the db in prod to check, but I bet this is not what it looks like. When you do a search on "top rated", it does not use the true average rating ; rather it uses a [bayesian average](bayhttps://en.wikipedia.org/wiki/Bayesian_average) to purposefully skew the results, essentially favoring add-ons with more reviews with a strong average rating.

Though "Flash Player for Youtube" is rated 5 (actually 4.5625), it has a low number of ratings, where "Youtube and more – Easy Video Downloader" (actually rated 4.4354 - quite close) has a lot more.

**Comment by diox** [comment]
(I'll add that we should expose the bayesian average rating through the API, it's useful information)

**Comment by jrbenny35** [comment]
But wouldn't think be confusing to the user? Currently one of my tests I am adding in #5363 will fail when tested on a deployed instance because the rating does not go from high to low.

**Comment by diox** [comment]
Maybe, but that's a product issue, I'm merely stating that it's not a bug :)

I'd be in favor of displaying the bayesian average everywhere instead of the actual average, but then we'd have to tweak copy slightly to remove indications that it's an average, because then *that* would confuse users who'd do the simple math and wonder why it does not match...

**Comment by diox** [comment]
Confirming that it's because of bayesian average. Ratings have changed a bit since this issue was opened, but "Easy Youtube Video Downloader Express" appears before "Flash Player for YouTube™" for the same reason I suspected earlier: though its raw average rating is lower, because it has a lot more reviews, and most of them are positive, it comes out on top.

@jvillalobos this can be confusing. Here are our options as I see it:
- Leave as is, either because we think the current behavior is ok or because we'll overhaul ratings later
- Change to remove bayesian average calculations, using raw average for sorting
- Change to display bayesian average as the rating displayed to users and not just the one used for sorting (would require some tweaks of the detail page, since currently it shows the number of reviews for each rating value)

**Comment by jvillalobos** [comment]
Exposing the bayesian average will lead to other users questioning why it doesn't match the average they would expect (in some cases), so I don't think that's much better than the current situation. And I think it makes sense to rank add-ons using it, so I would like to keep the current behavior.

Maybe in the future we can do something like what Yelp does, which is show the rating with a different tone when there are more ratings involved, helping to explain its results ranking. For now let's just keep it as it is.
