### ISSUE TITLE
Hide public source viewer links temporarily

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5431]
The public source viewer was taken down due to performance issues, which are being investigated in #5135. At the moment users are getting a confusing error message, which has lead to lots of bug reports.

Since the main issue may take a while to resolve, in the short term we should hide those links to prevent users running into those errors.

They are present on [listing pages](https://addons.mozilla.org/addon/adblock-plus/) in the Version Information section, [All Version pages](https://addons.mozilla.org/addon/adblock-plus/versions/), and [All Development Channel Version pages](https://addons.mozilla.org/addon/adblock-plus/versions/beta).

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Win 7).
- Source code links is hidden from add-on listing pages, All Version pages, and All Development Channel Version pages.
![untitled](https://cloud.githubusercontent.com/assets/15685960/26312580/b76ae8d0-3f10-11e7-97e3-e287fba8454c.png)

- source code is still available while accessed from add-on review page 
![source](https://cloud.githubusercontent.com/assets/15685960/26312515/8a67e73e-3f10-11e7-9058-3f147e6c9ea6.png)
@EnTeQuAk this is intended, because we are hiding only the "public" links, yes?

**Comment by EnTeQuAk** [comment]
Correct, only public links got removed for now. The file-viewer is still relevant for our editors doing reviews.

**Comment by Parudas** [comment]
Public link is still visible for me.
![spectacle ea4940](https://cloud.githubusercontent.com/assets/16246945/26379586/3cae81d2-401a-11e7-8c08-8143038f667b.png)

Clicking it results into:
![spectacle vs4940](https://cloud.githubusercontent.com/assets/16246945/26379596/521d177c-401a-11e7-8597-2515d69d39fd.png)

Maybe not the best wording when dealing with open source compliance, someone could think that he's getting denied the right to access the source code.

**Comment by diox** [comment]
@Parudas : the fix has landed in our master branch, but will only be deployed tomorrow (we tag every tuesday, deploy that tag every thursday)
