### ISSUE TITLE
"Not yet rated" for a reviewed add-on in Moderated Reviews queue

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5441]
Steps to reproduce:
1. Leave a reply to an add-on review i.e. https://addons.allizom.org/en-US/firefox/addon/speed-dial/reviews/714811/
2. Report the reply (I used another account to do this)
3. Go to Reviewer Tools - Moderated Reviews tab and search the report

Expected results:
Add-on name, review title, review author, review date, locale, review text, report motive, report author, date and time are displayed.

Actual results:
"Not yet rated" message is displayed after date of the review.

Notes/Issues:
- seems like the add-on is not rated
- I think it is because the reply of a review has no rating stars to be added

Verified on FF53(Win 7). Issue is reproducing on AMO-stage and -dev.
Screenshot for this issue:
![noyet](https://cloud.githubusercontent.com/assets/15685960/26201480/de300d66-3bdb-11e7-8fad-aa4e190d48c8.png)

**Comment by EnTeQuAk** [comment]
I might be misunderstanding the issue here but the locale is clearly visible, the report motive is visible in the red block, same as report author and the time. 

That "not yet rated" block is part of how the review is being displayed on the addons detail page too, we're using a similar view here so yes, if the add-on is not yet rated this appears, otherwise it'd be the stars.

Does that answer your question or am I missing something?

**Comment by diox** [comment]
Not a bug, per previous comment.
