### ISSUE TITLE
Screenshot captions configured for en-US are invisible for en-GB

### ISSUE THREAD

**Issue by sblask** [mozilla/addons-server#5459]
### Describe the problem and steps to reproduce it:
I added new screenshots and captions for https://addons.mozilla.org/en-US/firefox/addon/simple-form-fill/ in the default locale en-US (I don't want to localize anything)

### What happened?
By chance I had en-GB enabled when looking at the page, the screenshots are there, but no captions.

### What did you expect to happen?
The captions should always be visible (they are when choosing Spanish for example, but not when choosing en-GB)

### Anything else we should know?
This is how my localization settings look like: ![screenshot_2017-05-20_23-46-29](https://cloud.githubusercontent.com/assets/681955/26279523/ba5b6dfe-3db6-11e7-930e-ad4d765df1e7.png)

**Comment by diox** [comment]
Somehow this add-on ended up with empty en-GB translations for the captions, which is why the captions are showing up correctly in every language (no translation in that language -> it falls back to the default, which is en-US in this case) except en-GB.

Can you try the following:
- Go to the add-on edit page
- Choose edit captions
- Look at the localization menu: it should now change "English (British)" under "Existing Locales"
- Click the icon to "Remove this localization"
- Confirm my clicking "Delete locale"

**Comment by sblask** [comment]
I am pretty sure I tried just that already, but I just tried again and it's still the same problem. After deleting the localization, British English is not visible anymore, but when I then go back to editing images and click on the localization menu, it is back. Is that expected? 

Can it be related to being a webextension?

**Comment by diox** [comment]
Not what I expected no... Sadly I think this is just related to our developer hub and translations mechanism being old and buggy.
