### ISSUE TITLE
Facilitate finding legacy add-ons during transition to WebExtensions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5482]
AMO listing pages show the latest version of an add-on. When Firefox 57 starts riding the trains, blocking all legacy add-ons, users of older versions of Firefox and ESR will start running frequently into listings that have a WebExtensions version they can't use, and older legacy versions that they can use but can't easily find.

We should check if it's practical for AMO to figure out the latest compatible version of an add-on and offer that to the user. Alternatively, if it's easier, this could be limited to add-ons that have a WebExtensions version and older legacy versions, since that's the case we're concerned about.

**Comment by EnTeQuAk** [comment]
Given that our listings are primarily fetched from ElasticSearch and that we have a reasonably good integer representation for firefox-versions I'd say this should be possible. We also have `is_webextension` indexed as a last resort.

@diox any opinions about that?

**Comment by diox** [comment]
For the record, I don't think serving old versions of an add-on is such a great idea: that means users are potentially using an insecure or unmaintained add-on (without even knowing it!).

That being said... addons-server already supports filtering out incompatible add-ons from listings:
- The modern API and legacy search views do it directly in ES already. The parameter is [`appversion` for the modern API](https://github.com/mozilla/addons-server/blob/f74cf659602a1c4f066a537ba52c8d620111cda1/src/olympia/search/filters.py#L71-L101), [`appver` for the legacy search](https://github.com/mozilla/addons-server/blob/f74cf659602a1c4f066a537ba52c8d620111cda1/src/olympia/search/views.py#L370-L382). Legacy search passes that parameter down automatically by default.
- The [legacy API does it in (crazy) SQL](https://github.com/mozilla/addons-server/blob/f74cf659602a1c4f066a537ba52c8d620111cda1/src/olympia/legacy_api/utils.py#L160-L280) after the search has been performed for some reason, [removing them from the results](https://github.com/mozilla/addons-server/blob/f74cf659602a1c4f066a537ba52c8d620111cda1/src/olympia/legacy_api/views.py#L387-L402). The parameter is part of the URL.
- [The update service does it with custom SQL](https://github.com/mozilla/addons-server/blob/f74cf659602a1c4f066a537ba52c8d620111cda1/services/update.py#L218-L243) (also obeying strict compatibility, which I don't think other parts of the code do except the legacy API). The parameter is again part of the URL.

In any case, for all of this to work, the minimum version needs to be set correctly on the add-ons.

Note that, unless I haven't looked properly, I think that once we start displaying the add-on (i.e. it has not been filtered out of results already), we don't care any more. The means that it's not done on the detail page, or on the homepage, or category pages, or search pages when the user chooses to unselect the version in the sidebar.

**Comment by andymckay** [comment]
> For the record, I don't think serving old versions of an add-on is such a great idea: that means users are 
> potentially using an insecure or unmaintained add-on (without even knowing it!).

Not necessarily, its possible for the add-on author (I believe) to maintain an old version of an add-on by setting the compatibility properly.

**Comment by diox** [comment]
> Not necessarily, its possible for the add-on author (I believe) to maintain an old version of an add-on by setting the compatibility properly.

It's not possible right now because we don't care about compatibility on homepage/category pages/detail page, but I it would if we did, yes.

It would still be quite annoying for the developer, who would risk ending up serving a broken update (since we simply serve the most recent compatible version when serving updates) to their users if they mess it up. Please the versioning would be a nightmare...

**Comment by andymckay** [comment]
We have a very real problem coming up soon, if you could give us a better alternative, let us know.

**Comment by pwalm** [comment]
So, if we have two versions of the add-on (legacy and webextension) and we can check the user agent, can we just show the user the appropriate add-on for their browser version? That way the user gets the add-on they need and we don't need to do any other messaging. This would be the most painless option (for the user).

**Comment by Rob--W** [comment]
Jorge's initial report covers the situation in the future when Firefox 57 is stable; I am going to focus on the issues in the present.

> For the record, I don't think serving old versions of an add-on is such a great idea: that means users are potentially using an insecure or unmaintained add-on (without even knowing it!).

When a new version is at least as powerful as its predecessors, it makes sense to mark the old versions as obsolete. However, with WebExtensions this is different: WebExtensions are the only supported add-on type in Firefox 57, and their functionality is limited compared to legacy add-on types.

Consider the process of migrating a legacy add-on type to WebExtensions (see below for more details). Add-on author should be able to maintain both a WebExtension and a non-WebExtension version of the add-on, without penalties (loss of potential users) for doing so.

> Plus the versioning would be a nightmare...

The situation of an add-on gallery having to support two channels has occurred before: When Opera switched engines (from Presto to Blink), they also adopted Chromium's extension system. The add-on gallery allowed extensions of both types to be submitted, with the only requirement being that new uploads have a greater version number. This effectively allows an add-on author to publish (e.g.) "version 3.0" functionality by submitting version 3.0.0 (old extension type) and version 3.0.1 (new extension type). Users who visited the add-on listing would see 3.0.0 or 3.0.1, depending on the browser version.

### Add-on type migration process

An existing add-on that wants to stay functional in Firefox 57 without data loss has to submit updates to their add-on as follows:

- Version 1.0 - (powerful) legacy add-on (e.g. using the Add-on SDK).
- Version 2.0 - (powerful) legacy add-on with most of the functionality migrated to an [Embedded WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions) (the legacy part of the add-on only exists to support migration of data and settings from the legacy add-on to WebExtensions)
- Version 3.0 - (constrained) WebExtension add-on (this is identical to the embedded WebExtension from version 2.0, except there is no way to access the data from the previous versions of the add-on any more).

If version 2 is skipped, then version 3 will be completely oblivious of any previously stored data (from version 1). Hence it is important that version 2 of the add-on is not skipped in updates. To achieve this, an add-on dev can upload version 3 with [`strict_min_version`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications) set to "57", so that version 2 is used in Firefox 56 and earlier (and version 3 in Firefox 57 and later).
*[ if the dev is confident that all users have updated in time, and want some slack to allow for testing in the wild, then they could set a lower `strict_min_version` in version 3 and upload version 2 with a `strict_max_version` value. ]*

Today, with this example, AMO would mark the add-on as incompatible (with Firefox 53), even though it is clearly compatible. This leads to the loss of users and is a disincentive for add-on devs to migrate their add-ons ahead of time.

**Comment by jvillalobos** [comment]
> Not necessarily, its possible for the add-on author (I believe) to maintain an old version of an add-on by setting the compatibility properly.

I don't think this is possible because once you submit a WebExtension version you're not allowed to submit legacy versions anymore (#3061).

Having said that, we're talking about a window of a couple / few months, and not many add-ons update that often. There may be cases where developers have a problem with an old branch and can't update it, but those should be a small group and admins can override this behavior in the case of a critical fix.

Rob explained very well the kind of cases we want to cover here and why we need to do this. I hadn't contemplated the homepage and other pages, however, so I'd like to understand if there's a big performance impact in doing this across the site.

**Comment by muffinresearch** [comment]
As noted in the q3 planning doc the target for completing this work is 57 Nightly which is 2017-08-07.

**Comment by muffinresearch** [comment]
Having discussed this at length with @diox and @jvillalobos it seems likely that the next step would be to plan removing the filters from search for older FF versions and change the wording on the search results and details pages to make it clearer where other versions would be available.

This will mean users of older Firefox versions will be able to find _all_ add-ons and won't have addons with minVersion 57 filtered out. It will also mean that in order to find a compatible version they will need to look at the versions page. As a result of that improving the way we communicate how to find compatible versions is an important part of it.

* This avoids getting into big changes around search which would delay a viable solution.
* It makes the changes smaller to implement in general
* It means we're generally only changing the UX for the users of older browsers.

This work will be need to be completed in early Q3.

The next steps are to clarify precisely what the details of the search changes are and also what the UX will look like for highlighting the versions page link on search results and the details page.

**Comment by jvillalobos** [comment]
Here's a [more detailed proposal](https://docs.google.com/document/d/1ui9Zq1iCzIA5DIneHN5i1LzGhs9HOdN9h8532SuqavY/edit#) of what to do. I created a Trello card for this and put it up for UX review.
