### ISSUE TITLE
"Next listed version" link will return a 404

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5533]
Steps to reproduce:
1.Submit a new add-on and approve it
2.Submit a new version for the add-on 
3.Go to Manage Status & Versions page for this add-on and press the link next to "Next listed version"

Expected results:
We have 2 possibilities here. We can deactivate the link for the next listed version because it is not public and it will always return a 404 or we can display the awaiting review version for edit purposes

Actual results:
A 404 will be returned

Please see video for this bug : 
![nextlisted](https://cloud.githubusercontent.com/assets/1583842/26632531/223d7fec-4619-11e7-9ffb-007f98c9c666.gif)

**Comment by harikishen** [comment]
I would like to work on this.

**Comment by eviljeff** [comment]
@harikishen great.  I think the fix is just to change the link to point elsewhere - it's only shown when there is a version pending approval so it's never going to work.  Search for the link text 'Next Listed Version' to find where it's used and change to `addon.get_dev_url('addons.versions')` for the status & versions page.

**Comment by diox** [comment]
@vishal-chitnis submitted a PR fixing this. Thanks again!
