### ISSUE TITLE
Account settings is not completely RTL 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5589]
Steps to reproduce:
1.Login to AMO Stage and select Account Settings (https://addons.allizom.org/en-US/firefox/users/edit)
2.Set the language to any RTL language (ie. https://addons.allizom.org/ar/firefox/users/edit)

Expected results:
The entire page is in RTL

Actual results:
Info for every section is not RTL

Please see video for this issue:
![rtlaccountssettings](https://user-images.githubusercontent.com/1583842/26884175-d1fd7444-4ba7-11e7-8c4c-3e6affe7ec38.gif)

**Comment by zawadm** [comment]
I am working to fix it.

**Comment by eviljeff** [comment]
@zawadm Hi, are you still working on this?  You're welcome to but we should warn you that these pages are being replaced later this year with https://github.com/mozilla/addons-frontend/

**Comment by tsl143** [comment]
Also I find written `fuzzy` infront of the translate strings, does that mean something(I am not sure how translation works for this)
<img width="762" alt="screen shot 2017-07-23 at 10 43 44 pm" src="https://user-images.githubusercontent.com/5318732/28501384-883154be-6ff8-11e7-89fb-e2e3cdcbc695.png">

**Comment by muffinresearch** [comment]
This will be going away in Q4 so should be a low priority - if there's a fix in progress then it's ok to continue.

@tsl143 the fuzzy marker is there because the translation is a "fuzzy" match for the english key. This translation will not be used until a translator has a chance to update and fix the translation. When they do that they would typically remove the fuzzy marker. It's a useful feature since this often gives a localizer a headstart on a translation.

**Comment by wagnerand** [comment]
@tsl143 Did you have any chance to work on this yet? If not, maybe another issue might be better to take since the current design is going away quite soon which makes this issue obsolete.
Of course, if you have something already, feel free to send it our way, please :)

**Comment by tsl143** [comment]
@wagnerand I am not working on this right now.

**Comment by wagnerand** [comment]
No problem, we're closing this then.
