### ISSUE TITLE
API endpoint to report an add-on/flag an add-on

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5595]
The AMO frontend will soon have a "report a problem" button (we didn't have one before) but there is no API for reporting an issue with an add-on so we'll need one to implement that feature.

**Comment by eviljeff** [comment]
When will this likely be needed for?

**Comment by tofumatt** [comment]
It would be great to have it this quarter but I know I brought it up way late. We can’t have flag for abuse on new (optional) desktop pages or more importantly mobile at all until it’s implemented though.

- tofumatt

**Comment by eviljeff** [comment]
We're going to do this early Q3 as its possible some of the functionality may change due to [addon reporting plans](https://docs.google.com/document/d/1hVx-NbuVRc0wKXSdt8eHceObexY93YFzMXtqYC95nUs/edit#heading=h.st01cgqqxqnz)

**Comment by eviljeff** [comment]
@jvillalobos can you detail any additional requirements for the Abuse report API mentioned in the [Post-Review PRD](https://docs.google.com/document/d/1rZvM2QGk8WtkNUDRvLEvrbqZ190hvHfOle4zVRllQmw/edit#heading=h.hb0ltlokkuw7)?  From my reading it looks like it needs to support reporting based on GUID, and handle reports for non-AMO addons.  Anything else?

**Comment by jvillalobos** [comment]
I need to update the doc, but in talks with @andymckay we concluded it was best to have a page on AMO that does this, rather than have the Add-ons Manager interact with it directly. The underlying API is still needed, of course. And yes, the requirement is that it would take a GUID and could be an unlisted add-on or even something that isn't on AMO.

There's a separate issue that I'll file later where we want to give users a way to pick from predetermined abuse options ("This add-on is malware", "This add-on is misleading", etc.), but that's new work that we haven't planned out yet.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed".
Thanks in advance!
