### ISSUE TITLE
trouble shooting Azure connect sync wiht O365

### ISSUE THREAD

**Issue by RandyKowalczyk** [mozilla/addons-server#5648]
### Describe the problem and steps to reproduce it:

MIcrosoft cannot deliver helpdesk tools to verify sync as tools needed in browser
(Please include as many details as possible.)

### What happened?
https://configure.office.com/Scenario.aspx?sid=18&uid=454d41494c

-Per Mozilla
We're sorry, but we can't find what you're looking for.

The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

    If you typed in the address, please double check the spelling.
    If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

Or you can just jump over to some of the popular pages on our website.

    Are you interested in a list of featured add-ons?
    Do you want to search for add-ons? You may go to the search page or just use the search field above.
    If you prefer to start over, just go to the add-ons front page.

### What did you expect to happen?
Get plugin

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
This bug tracker is for https://addons.mozilla.org/ directly and I don't see how your report is relevant for this and don't even see the actual problem here. The link you posted is behind a login unfortunately, so not accesible too.

If you have more information to add please feel free to do so, I'm going to close this issue for now though.
