### ISSUE TITLE
Support locales for screenshot images

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5662]
Originally filed at https://github.com/mozilla/addons-frontend/issues/2596. Basically: we should support uploading screenshots for each locale and the API should return screenshots based on the locale. I guess falling back to `en-US`/default screenshots if no localised ones are available.

------

# Original issue

> Hi,
> 
> please allow different screenshots for different languages.
> 
> At the moment I can either upload screenshots showing the UI of my add-on in one language (but not the correct language for a lot of the users) or I have to upload the same screens in all languages so if my add-on is available in 8 languages the user see the same screens 8 times - 1x for every language. Both options are not great.
> 
> Since almost everything is localizable it would make sense to also allow screenshots in different languages.
>
> -- @cadeyrn

**Comment by jvillalobos** [comment]
Sounds reasonable. One thing to take into account is that screenshots also have captions, which *are* localized. So we would need to tie captions to specific screenshots (instead of having multiple localizations for each screenshot), so there isn't a mismatch there. We probably won't get to this until we do a developer tools overhaul next year, though.

Since listings have a default language, that should be the fallback one instead of `en-US`.

**Comment by EnTeQuAk** [comment]
I was about to start a discussion wether or not we need it but at least the bit two other app-stores support localized descriptions and - as requested here - localized screenshots (graphic assets).

It'll be a nightmare to implement though, our current translation system doesn't support files yet and as far as I can tell adding anything to our `translation` model adds a huge overhead to many many other translations. We'll need to look into the possibility of a different translation system for this, especially since it'd profit from whole localized models and not just separate fields.

> We probably won't get to this until we do a developer tools overhaul next year, though.

Sounds reasonable to me.
