### ISSUE TITLE
Popup Blocker Ultimate has been removed?

### ISSUE THREAD

**Issue by ander33x** [mozilla/addons-server#5704]
### Describe the problem and steps to reproduce it:
-I do not find the addon "Popup Blocker Ultimate"

### What happened?
-I can not find

### What did you expect to happen?
-That was available

### Anything else we should know?
-The page link is... http://www.popupblocker.ir/

**Comment by eviljeff** [comment]
Unless you have a url it's difficult to say - the developer may have removed it; it might have been re-named.

**Comment by ander33x** [comment]
Thanks for comment Jeff.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
"If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it. " (lead me here.)

I'd like to know if the extension was removed because it was flagged as being malicious or not, unfortunately, this has happened in the past with addons I've used, they just get removed with no sort of warning to users with the extension installed that it was removed for xyz reason.

I know the extension used obfuscated js, I am not a coder however, having had previous unsuccessful attempts at conversing with the author, where I asked that they provide regular changelogs and or published the source on mozilla to compare versions should the extension become compromised, this was quite a long time ago. I've had the extension disabled since it started nagging for ratings and donations in a way that I considered to be fishy.

Thanks. 

URL: https://addons.mozilla.org/en-GB/firefox/addon/popup-blocker-ultimate/?src=cb-dl-popular

<?xml version="1.0"?>
<RDF xmlns="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:em="http://www.mozilla.org/2004/em-rdf#">
    <Description about="urn:mozilla:install-manifest">
		<em:creator>Mojtaba Daneshi</em:creator>
		<em:description>Popup Blocker Ultimate</em:description>	
		<em:homepageURL>http://www.PopupBlocker.ir/</em:homepageURL>
		<em:id>{60B7679C-BED9-11E5-998D-8526BB8E7F8B}</em:id>
		<em:iconURL>chrome://popupblocker/skin/logo.png</em:iconURL>
		<em:optionsURL>chrome://popupblocker/content/options.xul</em:optionsURL>
		<em:name>Popup Blocker Ultimate</em:name>
		<em:version>6.8</em:version>
		<em:targetApplication>
			<Description>
				
				<em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id>
				<em:minVersion>2.0</em:minVersion>
				<em:maxVersion>51.0</em:maxVersion>
			</Description>
		</em:targetApplication>
	</Description>
</RDF>

**Comment by eviljeff** [comment]
@wagnerand

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
Very strange, now today Popup Blocker Ultimate is back with a sudden version bump from 6.8 to 8.0, no word from the author on the page, just what precisely is going on here? Interesting reviews as of recently:

"
Popup blocker nagging me with popups ! Rated 3 out of 5 stars

by joloda on July 12, 2017 · permalink

I didn't install a popup blocker to get harrassed by popups for donations or this "pray for Iran" crap.
EDIT : Then there's a bug, because I'm clicking on it at least once a week or so...

by Mojtaba Daneshi (Developer) on July 12, 2017 · permalink

That is a onetime notification, just click on "don't show me again" button,
Edit:Dear user, do you know my addon disabled and I realeased many versions to enable it again? And new version released and it included just onetime notification, older was for old versions, so after many works and mails to Mozilla I success to come back to store,and instead of sending review same as latest review that you can see, you send me a message about notifications and one star rating! It is nit a good treatment dear user, I worked hard for this addon. Please don't make me sad by your reviews, you just click two times on the don't show me again button and for that ,want to destroy my addon rating?
Sincerely"

Interesting argument, language barrier aside, when a user posts a review it says if the user is reviewing an older version, clearly they're not. This is what I'm saying, you flag an extension and don't alert users it's under review and let them continue to use it, even if it's cleared after. Surely there is a better way, alerting the user on extension update check perhaps. 

@wagnerand

**Comment by kewisch** [comment]
What the author chooses to disclose about the add-on is up to them, we will not be providing this information.

In the general case, if an add-on contains malicious code that is actively being exploited we can blocklist the add-on. There are cases where we do not blocklist the add-on but merely disable the listing, this can have a number of reasons of lesser severity.

For Popup Blocker Ultimate, the author has submitted a version that is in line with our policies and now available on the listing page.
