### ISSUE TITLE
Add author picture_url to add-on search/detail results

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5707]
For requests to `/addons/search/` http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search and `/addons/addon/:id/` it would be great if the `authors` array included an extra property for each author: their `picture_url`.

Our new mocks request the author's profile image in search and the detail page so once this was added I can add it into the site.

Not a huge rush on this but it would be a nice-to-have, hoping the performance hit isn't too bad.

**Comment by diox** [comment]
For the detail endpoint it's easy enough. For search it gets a bit more complicated:

It's doable, but slightly annoying because currently `picture_url` of a user depends on its `modified` property, to generate a query string that changes when the user changes their picture. We'd need to index that property and re-index the user add-ons whenever the user is saved to keep the URLs consistent across the site. To make things worse we currently update that `modified` property every time the user logs in (#5464)...

One good thing about doing that: it would also make changes to the author's name/username visible in search results, currently since we don't reindex the user add-ons at all the search API returns the old name/username if it changed.

Ideally the `picture_url` would instead depend on a separate `picture_hash` property that would change whenever the image changes, nothing more (see https://github.com/mozilla/addons-server/issues/2659 for a description of the same issue for add-on images). We'd index that, reindex the user add-ons only when the image, name or username changes, that'd be much better.

**Comment by eviljeff** [comment]
@diox change it to use the modified time of the file itself?

**Comment by diox** [comment]
You still need to store it in the database, you don't want to have to do a `stat()` on the file every time you want to display it (especially since it's stored on a remote storage, from the app server point of view). So you might as well store a hash instead.

**Comment by tofumatt** [comment]
As mentioned on IRC... in the mocks the image is `16px x 16px`. This is so small as to not be very useful: it looks good in mocks but there it's just a grey block. Compressing down a user's avatar to that size will be quite ugly.

I might say we just return it for the details page for now...

**Comment by vcarciu** [comment]
Where should we see the picture on details pages?

**Comment by tofumatt** [comment]
@vcarciu This is just an API change, sorry. No QA is needed for this one.
