### ISSUE TITLE
Expose tags/appversion faceting in the search API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5794]
The search API needs to expose which tags can be used to refine a particular query, like the desktop search does atm.

**Comment by diox** [comment]
It's worth asking whether we truly need this or not.

Currently, in search, you can refine your search with 3 different criteria:
- Categories. This is not done with real faceting, all categories are shown.
- Application Versions. This is done with faceting, but the end-user benefit is not clear to me. Why would I care to refine my search with add-ons compatible with Firefox 4.x or greater, just because it's the lower limit used by some add-ons in the results ?
- Tags. Also done with faceting, all tags are shown, regardless of whether they are developer-defined or ones we set ourselves. Is this really going to be useful? For instance when I search for "adblock" the tags shown are: jetpack, firefox57, adblock, block, ads, restartless, blocker, privacy, youtube, ad. Does selecting one helps me in any way?

**Comment by eviljeff** [comment]
@jvillalobos because `needs: product` label doesn't alert product

**Comment by jvillalobos** [comment]
I think category faceting would be useful, since filtering by a bunch of categories and getting nothing back is just wasted time.

We're not doing compatibility filtering at that level, and tags were removed from the MVP, so I think for now we can drop those.

**Comment by diox** [comment]
Dropping this for now as this was never part of the new frontend and tags & categories are getting redone in the future anyway.
