### ISSUE TITLE
Font color picker from theme submission is not working as expected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5795]
Steps to reproduce:
1 Go to submit page for a theme on AMO-stage https://addons.allizom.org/en-US/developers/theme/submit
2. Try to select a font color

Expected results:
Color wheel is white and not working as expected.

Actual results:
The color picker is working as expected.

Notes/Issues:
Verified on FF54(Win 10). Issue is reproducing on stage and dev.
Screenshot for this issue:
![color](https://user-images.githubusercontent.com/15685960/27703889-7bcd1022-5d11-11e7-83e9-88489ade8070.png)

**Comment by eviljeff** [comment]
Ugh... so, this is a bug in jingo-minify.  When it does the concatenation step for the css files it doesn't rewrite any urls referenced so if the source css|less|scss file isn't in the same folder as the destination bundle then the urls are wrong.
Possible solutions:
- copy both the `jquery.minicolors.css` and `jquery.minicolors.png` files to `statics/css/zamboni` instead of `node_lib`.  Downsides are it's mixing up library files and our sources again (something I tried to avoid); and it would need a .gitignore entry for just those files to avoid messiness if jquery.minicolors is upgraded.
- copy just the missing `jquery.minicolors.png` file to `static/css/zamboni/` too, in addition to `static/css/node_lib` (it needs to be in both places for local development).  Similar downsides to the previous, but at least the css will be separated.
- fix jingo-minify (lolno)
- assign jingo-minify to the :fire:

**Comment by madalincm** [comment]
Verified as fixed in FF54(Win7) in addons-dev.allizom.org
Postfix screencaast:
![colorpicker](https://user-images.githubusercontent.com/15685441/27866278-58c35f96-619e-11e7-8bb9-0338628a21c5.png)
Clsoing.
