### ISSUE TITLE
Expose `has_anonymous_username` for User

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5838]
If a user hasn't set their profile name, they have an ugly "anonymous-127537" type username, which will appear in the top of the page's UI on the frontend and across the app. This isn't a great UX, it would be better to expose simply "Anonymous User" or something similar based on a flag set saying they haven't set their username yet. If they haven't set it we could even use their email.

Apparently there's a `has_anonymous_username` method on the User profile we could use. This is problematic as if a user actually has a username that matches it we'd still display their email or "Anonymous User", translated.

Ultimately it would be nice if the first user `save()` done with an anonymous name had a flag explicitly set like `has_set_username` to be `false`. And then once the username was changed it was set to `true`. I think a migration that set all users with `has_anonymous_username() === true` as having that flag is fine but going forward I think that should be an explicit setting.

Then it would be good to expose in the API so we can decide how to expose a username in the frontend.

**Comment by tofumatt** [comment]
And if this is all just a TONNE of work you don't have time for, exposing the result of `has_anonymous_username()` for now would be fine until we can properly fix this.

**Comment by diox** [comment]
> Apparently there's a has_anonymous_username method on the User profile we could use. This is problematic as if a user actually has a username that matches it we'd still display their email or "Anonymous User", translated.

This is unlikely to happen though. If someone has really set their username to `anonymous-12345` on purpose I don't think we should really care... So I think just exposing `has_anonymous_username` in the API is enough.

**Comment by tofumatt** [comment]
I guess it's not a common username 😄 

I just would feel bad if someone's wanted username is "Annonymous-404" or something and it fit the regex and it might be a weird bug to track down. But just exposing the method, if my proposed alternative is a lot of (low-priority) effort, then yeah that's cool.

**Comment by eviljeff** [comment]
Are you displaying _username_ or _display_name_ (the latter I would have thought is more appropriate)?
And if `display_name` I wonder if `has_anonymous_display_name` is more appropriate?

p.s. the username generates a 16 bytes suffix, encoded as hex, so unless they want "annonymous-40440440440440440440440440440440" they'd be okay :)

**Comment by andymckay** [comment]
cc @mstriemer, if I remember, the reason for that suffix was to a concern that there was nothing distinguish different anonymous users. It might have been issue #1518.

**Comment by mstriemer** [comment]
Andy is right. We didn't want the reviews section for an add-on to be all "Anonymous User" so the number is included to show that it is a specific user that hasn't set a username. We only use the first few digits from the random suffix in this username so it isn't too long.

Also as Andrew said the display name should be checked too. I think we use `name` on addons-server which is essentially `self.display_name or self.username or self.anonymous_username`. This appears to be `user.name` in the reviews API, so you should already be getting the "Anonymous user 12345" name rather than "anonymous-12345678901234567890..."

If you're making the user edit page, then having the `has_anonymous_username` flag could be used to hide the value their username is set to and instead show a banner prompting them to set it. Since we don't require the username though, they could also just set `display_name` and you can check the presence of either with `has_anonymous_display_name`.

It would be good to do more prompting to get a user to set their username, especially if they're uploading add-ons or writing reviews, possibly preventing either of those until the username is set. The old flow for setting a username was too inconvenient to require that though.

If we want to reduce the number of anonymous users (this seems like a good idea to me) then we should file an issue to come up with one or more solutions. Some thoughts:

1. Put a button over the review stars similar to the log in button that opens a modal to set the username/display name
2. Add a step to the add-on submission flow that requires a username or display name to be set
3. Lower the ranking of anonymous reviews so that they appear below reviews by users with a `name` set

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
