### ISSUE TITLE
Hard-code locale in links to MDN

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5897]
Follow-up on https://github.com/mozilla/addons-server/pull/5890#issuecomment-314840612

Since there is no locale fall-back on MDN, we want to make sure all users see up to date docs, or even any docs at all, in case the MDN page does not exist in the user's locale.

We should hard-code the `en-US` locale in all links to MDN.

**Comment by EnTeQuAk** [comment]
warning, personal opinion ahead...

I'm -1 for a change like that. MDN does redirect for locales, even unsupported ones if you don't set anything specifically in the URL. If you do and MDN doesn't support it (technically not support it aka not being in this list https://github.com/mozilla/kuma/blob/master/kuma/settings/common.py#L130) it throws a 404 error. That can be fixed in MDN though if need be imho.

`curl -L https://developer.mozilla.org/Add-ons/WebExtensions/ -H "Accept-Language: eu"` redirects to en-US for me so that seems to be working, `de` shows the German article for reference.

Some comments from IRC:

> `<@muffinresearch> I feel it's a shame that we miss out on translated content if we side-step MDN's own lookup based on headers, but I can see the case for hard-coding en-US if the content does regularly get out of date and if that isn't obivious to end-users.`
> `<TheOne> muffinresearch: i feel the same way`

My opinion on that: we trust in our translator community for our discovery pane in firefox, something that now changes almost every month and I'm pretty sure isn't translated 100% in more than just a handful of languages and it's shown to much much more people around the world than our WebExtension docs, also, developers are usually much more forgiving if something isn't complete in my experience. If we want up-to-date translated articles we should encourage it, not hide it. If we never link to language specific pages, what's the point in having them.

**Comment by diox** [comment]
I'm also -1 on that, it feels like dealing a huge blow against MDN translators by completely ignoring their work. MDN does fall back correctly if the page does not exist, so it looks like it's only a problem of making sure the content is up to date, and I think that's something that should be done on the MDN side instead of harcoding all our links to use english.

**Comment by wagnerand** [comment]
I stand by my comment quoted above. I am torn on this.

Do we have a good strategy for getting/keeping localized WebExtension docs up to date? https://developer.mozilla.org/es/Add-ons/WebExtensions is a good example for a very outdated page and no notice about that.

**Comment by muffinresearch** [comment]
Seems like to move forward on this we need to understand how quickly translations get updated in MDN and whether these things can be prioritized in the future if gaps appear.

@atsay do you know who is the best person in MDN to ask about this?

**Comment by atsay** [comment]
Let's have wbamberg weigh in. I'll email him, since I can't find his gh handle.

**Comment by wbamberg** [comment]
This is a big can of worms for MDN.

I think ideally we'd have a higher barrier to publishing live pages in other locales, based on the completeness, quality, and freshness of translations. Ideally we'd have a pretty clear idea of which locales are sufficiently complete and up to date, a way to hide translations that are not, and a process for reassessing this periodically. We'd also have a strategy that can prioritise locales. We'd work with translators to help them succeed in keeping content up to date. I don't think we do any of this right now, and that's because we can't resource it.

"it's only a problem of making sure the content is up to date" - yes, but "only" is doing a lot of work there. Translated pages exist to make the experience better for users of MDN, and if they are not doing this (as in https://developer.mozilla.org/es/Add-ons/WebExtensions) then we're not doing anyone any favours by showing them.

Would it be possible/desirable to hardcode en-US for all but the handful of locales which do seem to be actively maintained? This would probably be: de, fr, ru, zh-CN. But it would take some more analysis to get a more informed answer.

Also @atopal: what do you think?

**Comment by atopal** [comment]
+1 to what Will said

One of our OKRs for this quarter is to measure the ROI of localization on MDN. We need to better understand where localization provides value, where it's detrimental, whether our current community model is the right one and where to invest our limited resources in the future. I don't expect any easy answers here. Different regions have different requirements. It's unlikely we'll act on this before Q4.

Since you need something concrete right away: I'd look at all the countries/regions you care about  and decide whether 
1) they'd benefit from localized content
2) the current localized content is well maintained
3) you're ready to invest the time and energy to engage the community to maintain a localized version of the documentation

If the answer to one of the questions is no, linking to the en-US content might be a better option. I'd always err on the side of users. Yes, we care deeply about localizers on MDN, but the localizations are not primarily for them.

**Comment by wagnerand** [comment]
I don't see how we can lock on a specific locale (or a set) from the AMO side. From my understanding, we can include (or omit) the locale for each link to MDN, but that would affect *all* locales for that link.

What am I missing?

**Comment by jvillalobos** [comment]
My understanding is the same, that it's all locales or just one, in which case I favor just going with `en-US`. If there are at least a couple more locales that are kept reasonably up to date, we could add some function that points to the localized page depending on the locale being used on AMO, and only for languages we know are good quality for MDN add-ons docs. We'll always need to point to `en-US` for policy docs, though, since those are more sensitive.

**Comment by atopal** [comment]
I think that's exactly what Will was suggesting 👍

**Comment by yfdyh000** [comment]
As localized original resources are scarce, I guess change to double line contrast is a good solution, but it is a radical change, I don't expect this to achieve easily.

As an example, http://eslint.cn allow users to instantly switch to Chinese, English or English & Chinese from Logo side. It's repo: https://github.com/smocean/eslint.cn, use jekyll and `_data`, etc to produce .md files.
![eslint.cn](https://user-images.githubusercontent.com/1769875/28336874-281de706-6c36-11e7-9db8-1c15aa35bd34.png), the screenshot from [the page](http://eslint.cn/docs/rules/no-console).

Note: original work editions is still expected if content is allowed to be inserted or new page.

**Comment by atsay** [comment]
Can this be closed out now? Sounds like the most prudent solution for the time being is to include en-US in all MDN links. We can reopen later if something changes.

**Comment by wagnerand** [comment]
@atsay so, why close this if we are going forward with it?

**Comment by atsay** [comment]
Cause I thought this issue was just for making the decision, and the implementation will be filed in other issues? Or other affected issues (like the [footer](https://github.com/mozilla/addons-server/issues/5888) one) will be reopened to address it?

**Comment by wagnerand** [comment]
I think we can use this issue keep track of implementation (which will be done in one or more pull-requests).

It's generally preferred to not change the scope of issues after they have been addressed, and https://github.com/mozilla/addons-server/issues/5888 has already been reopened due to some other issue.

I'm reopening this and we can focus on the MDN locale changes here.

**Comment by ValentinaPC** [comment]
Verified if links redirecting MDN pages are localized and seems like they arent't.
Verified in AMO-dev FF54(Win 7).
Tried for: 
- https://developer.mozilla.org/en-US/Add-ons/Distribution/Submitting_an_add-on
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on
- https://developer.mozilla.org/en-US/Add-ons
- https://developer.mozilla.org/en-US/Add-ons#Contact_us
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions
- https://developer.mozilla.org/en-US/Add-ons/Themes/Lightweight_themes
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension
- https://developer.mozilla.org/en-US/Add-ons/AMO/Policy
- etc.

Hope I did not miss a thing.
Postfix video:
![mdn](https://user-images.githubusercontent.com/15685960/28521097-d06ecd2e-707a-11e7-9e18-f186051ba5c8.gif)
