### ISSUE TITLE
Thunderbird: Addon page does not show a default dictionary for German

### ISSUE THREAD

**Issue by jannispinter** [mozilla/addons-server#5900]
### Describe the problem and steps to reproduce it:
Thunderbird does not come with a dictionary pre-installed. Upon installing a dictionary in Thunderbird, the following addon page is shown when the locale is set to German:
https://addons.mozilla.org/de/thunderbird/language-tools/

Here is a [screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8885563) of the addon page with the missing dictionary. For completeness, here is the [documentation](https://support.mozilla.org/en-US/kb/how-install-and-use-another-language-dictionary-th#w_install-a-new-language-dictionary) on how to install another dictionary in Thunderbird.

### What happened?
In contrast to other locales, the "Available in your locale" table does not have a dictionary for German (only a language pack). In order to install a dictionary, the user has to scroll down to "German (Germany)" and select the desired dictionary.

### What did you expect to happen?
A default German dictionary is shown besides the language pack.

### Anything else we should know?
I think that most users don't understand this and install the language pack instead. This is why the language pack has some [negative reviews](https://addons.mozilla.org/en-US/thunderbird/addon/deutsch-de-language-pack-thund/), claiming that the addon does not work.

I suggest using the following language packs as a default for these locales:

Locale | URL to language pack
-------- | -----------------------------
de | https://addons.mozilla.org/de/thunderbird/addon/german-dictionary/
de-de | https://addons.mozilla.org/de/thunderbird/addon/german-dictionary/
de-at | https://addons.mozilla.org/de/thunderbird/addon/german-dictionary-extended-for/
de-ch | https://addons.mozilla.org/de/thunderbird/addon/german-dictionary-switzerland/

I already opened a bug at [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1380222) and got redirected here.

**Comment by eviljeff** [comment]
There are a couple of issues here (take your pick which is the actual 'bug'
- TB is directing to https://addons.mozilla.org/de/thunderbird/language-tools/ rather than https://addons.mozilla.org/de-DE/thunderbird/language-tools/ (or otherwise), so we're only showing stuff which is strictly compatible with 'de', which is only the language pack.
- we don't show other connected locales at the top, only the exact match (rightly or wrongly; maybe we should highlight de-AT dictionaries too to users in Germany, maybe we shouldn't)
- I suspect that we can only target an add-on at a single locale, so we can't have the de-DE dictionary as the de dictionary too.  (untested hypothesis)

@wagnerand @kewisch @jvillalobos

**Comment by jvillalobos** [comment]
@jannispinter's suggestion won't work because we can only map add-ons to a single locale in the Language Tools page, and I don't think we want to change that.

It looks like `de-DE` redirects to `de` on AMO (`de-AT` does the same, for that matter), so maybe it would be reasonable to reclassify the add-ons on `de-DE` as `de`. However, then we get into a minefield of national and cultural differences that could cause more problems than they solve. I'd like to hear what Andreas and Philipp have to say before deciding if any action is needed.

**Comment by jannispinter** [comment]
> It looks like de-DE redirects to de on AMO (de-AT does the same, for that matter), so maybe it would be reasonable to reclassify the add-ons on de-DE as de

Would it be possible to not redirect `de-DE`, `de-AT` and `de-CH ` to `de`, but show individual pages for `de-DE` and `de-AT` with their individual dictionaries? For English, this works with `en-GB` and `en-US`. However, despite having individual dictionaries, `en-CA` and `en-AU` also redirect to `en`, which redirects to `en-US`.

**Comment by eviljeff** [comment]
Here are the locales AMO supports https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L155:L161 - anything not in that tuple isn't strictly supported.  I.e. neither `de-DE` nor `de-AT`, etc are supported at the moment, only `de` and there is code that supports the fallback from an unsupported long locale code into a short one.  (`en-GB` is directly supported, like `pt-PT`, where there isn't an clear default short locale code).

It's tempting to think the easy solution is adding more codes to that list but that's site-wide localisation of all text on the website, not just this page, so has bigger implications.

I think the correct solution is just showing more dictionaries/lang-packs when matching the current user's locales.  (Something we should look at in https://github.com/mozilla/addons-frontend/issues/2777 and https://github.com/mozilla/addons-server/issues/5803)

**Comment by eviljeff** [comment]
This page was been rewritten in our new front-end and the problem reported in this issue is fixed there.  Thunderbird doesn't use the new frontend as it's going to have it's own add-on site soon (supposed to be already up).  It'll be up to the maintainers of that site how this issue is fixed there but closing on addons-server as it's not relevant on this site any more.
