### ISSUE TITLE
A 208422399 bytes add-on is not automatically blocked from submission

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5926]
Steps to reproduce:
1.Go to AMO-dev and try to upload a a 208422399 bytes add-on 

Expected results:
Add-on is blocked with a "Your file exceeds the maximum size of 200.00 MB"

Actual results:
Add-on validation starts and is always failed with a 504 at random percentage

Notes:
Please see the add-on at https://www.dropbox.com/s/4kndxtn1p6so342/almost200MB.zip?dl=0 

Please see screenshot for this issue : 
![almost200error](https://user-images.githubusercontent.com/1583842/28267620-84f34130-6b03-11e7-9be3-8d3bf27b5944.png)

**Comment by EnTeQuAk** [comment]
Interesting, our nginx should return a `413` in case an add-on exeeds that limit. There might be a slight mismatch though, the javascript uploader is catching 200 Mebibytes (*1024, *1024), not 200 Megabytes (*1000 *1000). @bqbn to get this in sync, what's nginx configured to do at what exact limit?

Neither of this explains the 504 though… I'll debug this a bit more.

**Comment by muffinresearch** [comment]
@EnTeQuAk I think the 504 will happen if nginx's request time limit is exceeded. It would be good to check if the limits in -dev and stage match production and what the limit is.

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk I think the 504 will happen if nginx's request time limit is exceeded. It would be good to check if the limits in -dev and stage match production and what the limit is.

eh, good point. That'd explain the behavior and needs input from ops. I feel like we should catch that error and others too? Meh!

**Comment by bqbn** [comment]
Nginx is configured with ```client_max_body_size``` set to 200m, where ```m``` means Mebibytes (1024*1024).

As for timeouts, the same timeouts are used across the 3 envs at the Nginx level. The timeouts are:
```
uwsgi_read_timeout 120;
uwsgi_send_timeout 120;
```

What I've noticed is that the 504 is shown after more than 2 minutes have passed since the upload starts, usually 7-8 minutes after the upload starts.

**Comment by bqbn** [comment]
@vcarciu I changed ```uwsgi_read_timeout``` to 300 on -dev environment. Can you try uploading the same file again and see if there is any difference? Please post your IP address so that I can search its logs later.

**Comment by vcarciu** [comment]
@bqbn - yes, it is a difference now(validation passed), but the problem is that this add-on should fail instantly with "Your file exceeds the maximum size of 200.00 MB" .

**Comment by EnTeQuAk** [comment]
That file is only 198MB though unless I'm unable to calculate that correctly.

**Comment by vcarciu** [comment]
@EnTeQuAk : this file is actually 208422400 bytes : 
![greater200](https://user-images.githubusercontent.com/1583842/28370289-8f3bacc2-6ca2-11e7-852d-0fa995fb951d.png)

Please see also https://bugzilla.mozilla.org/show_bug.cgi?id=1374648#c10

**Comment by bqbn** [comment]
@vcarciu as @EnTeQuAk pointed out earlier, the javascript uploader uses Mebibytes as measurement unit, so 200 MB means 200*1024*1024 = 209715200 and is greater than 208422400, that's why it didn't fail and allowed the upload to continue.

Apparently Nginx uses Mebibytes too, so when we set ```client_max_body_size``` to 200m, it also means 209715200 bytes. https://bugzilla.mozilla.org/show_bug.cgi?id=1374648#c10 is incorrect in stating that 208422399 is greater than 200 MB. Sorry for the confusion.

**Comment by vcarciu** [comment]
Then we can close it. Thanks

**Comment by EnTeQuAk** [comment]
Thanks for verifying this @vcarciu!
