### ISSUE TITLE
Foxified add-ons crash our slug generation for unlisted add-ons

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#5955]
So, not sure if the max length is the real issue here but it could be. I'm talking about instances of 

* https://sentry.prod.mozaws.net/operations/olympia-prod/issues/371002/
* https://sentry.prod.mozaws.net/operations/olympia-prod/issues/378936/

which run into the `RuntimeError` at https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/models.py#L108-L125

I don't have access to the prod database to verify any of these instances but once I find someone who does I will.

*Edit: from recent discussions: This is happening because of foxified add-on that converts chrome add-ons to unlisted versions on AMO.

More Background: This essentially means that it's creating a new unlisted version for **every user** trying to convert an add-on. E.g, if 250 users install "My Cool Add-on" from chrome-store we have 250 new unlisted "My Cool Add-on" entities on AMO which are more or less identical.

**Comment by EnTeQuAk** [comment]
cc @satdav who reported this.

**Comment by diox** [comment]
Per IRC discussion: changing the algorithm won't fix it since there *are* 100 slugs in the database with that prefix already. 

It's likely it's the same developer or group of developers trying to submit the same add-on multiple times instead of submitting multiple versions.

What we should do is raise a custom exception and catch it in the API at least, returning a 400 error complaining we can't create the add-on because of slug issues.

**Comment by eviljeff** [comment]
We could change the algorithm to generate up to 999 I guess... but that's not really a fix.

As discussed in the meeting, I think the fix involves being smarter about allocating slugs based on the name to addons that have only unlisted versions.  We could:
* not allocate a slug at all (bad idea, as all our code expects one for non-deleted addons)
* give it a numeric slug equal to the add-on ID.  (better idea.  Assuming we don't have any code that baulks on numeric slugs because they're not supposed to exist for non-deleted add-ons)
* generate a guid-style slug (similar to chrome store.   Ugly though)
We'd then need to prompt|force the developer to set/change the slug if they submit a listed version later.  If no slug we would _need_ to force a change; if numeric or guid-style we probably should but meh.

**Comment by jvillalobos** [comment]
Long term, I think the solution is to make the slug optional, and only available to add-ons with listed versions (the aforementioned _bad_ idea). This requires a bunch of work, like making all developer and reviewer pages work exclusively with the numerical ID instead of the slug, which we should do anyway IMO. The slug is mutable and we shouldn't be relying on it for any internal workings. We might also need to make some changes to slugs if we eventually want to support private add-ons like the Chrome Store.

This specific issue is an edge case that I don't think should require a lot of work, so I think going up to 999 or just throwing a better error message should be sufficient.

**Comment by EnTeQuAk** [comment]
From recent irc discussions: The problem this issue should only solve is the fact that we have too many add-ons that get created with the same slug (via foxified or similar systems). I'd go the randomized route and prefix every (generated) slug with a short random string. That should fix our issues with mass add-on generators and only leaves us vulnerable to human beings creating hundreds of add-ons with the same identical slug (and picking them manually).

**Comment by EnTeQuAk** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/378936/

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or mark it as "qa: not needed" ?
