### ISSUE TITLE
[RTL] Blank horizontal scroll on addons details page

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-server#5965]
### Describe the problem and steps to reproduce it:
Navigate to https://addons.mozilla.org/ar/firefox/addon/privacy-badger17/?src=hp-btn-promo
After page load a horizontal scroll is observed.
Scroll left.

### What happened?
got a horizontal scroll on addons detail page, a blank space towards left of the page

### What did you expect to happen?
there should be no horizontal scroll.

<img width="1268" alt="screen shot 2017-07-20 at 6 23 49 pm" src="https://user-images.githubusercontent.com/5318732/28418444-563135fa-6d79-11e7-8d34-3dc5bb620e8b.png">

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by atiqueahmedziad** [comment]
Could be fixed hiding the body's overflow with css. Will that be the right choice?

**Comment by diox** [comment]
No, I don't think so. It hides the problem, but that's a hack. Let's find a better solution.

If I remove the following in [`reviews.less`](https://github.com/mozilla/addons-server/blob/master/static/css/impala/reviews.less), the scrollbar disappears:
```css
    .html-rtl & {
        transform: scale(-1, 1);
     }
```

This was something you added a while ago, in af42e54ccce13443ed7c19b96e0f8944c99150e5 ; maybe this can be changed into something else, or the rule made more specific to only target stars inside the popup, since the original problem it was meant to address had something to do with the review popup only and not the main page(s).

**Comment by vcarciu** [comment]
Verified as fixed : 
![noscroll](https://user-images.githubusercontent.com/1583842/30102581-ca32ec4c-92f8-11e7-8213-36e5fb94ac11.png)
