### ISSUE TITLE
Get rid of the Category model

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5981]
We shouldn't need the `Category` model, the `StaticCategory` constants should be enough, together with, say, a simple `JSONField` to store categories on `Addon`s.

**Comment by eviljeff** [comment]
I took a stab at this on code-quality-Friday.  Took the best part of a day to remove the obvious references to Category and `toStaticCategory`/`fromStaticCategory` and a huge number of tests fail at this point. I estimate it will take at least another day of work to have tests pass (plus some database migration work).  But, as the majority of the changes are in legacy code paths, then a) we're changing something that will be deleted in a few months and b) the legacy code is going to be poorly tested in the real world and potentially unstable in the meantime.  So I think it will be much easier to leave this until after legacy frontend is deleted.  

It _may_ be possible to bring some of the changes forward with devhub and reviewer tools but I'm not sure if it's worth it.

https://github.com/eviljeff/olympia/tree/5981-drop-category-model for reference

**Comment by eviljeff** [comment]
QA: check addons (each type) still have the same categories as before; that categories can be added/changed etc in devhub as before.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- I verified this on AMO dev and I did not find issues. - all extension and theme categories are displayed, also I could change them from dev hub.
- lang packs and dictionaries have the `general` category as before.
- at upload I could select categories, the form looks good.

- I've noticed that android theme categories throw an error now "Invalid category parameter" and the themes page show the recommended extensions on the see more shelves instead of themes. I know themes on android have been completely removed by @bobsilverberg and right now these URLs are hidden but in case that's an unexpected result please let me know. 
Thanks!

 
![android themes on desktop](https://user-images.githubusercontent.com/33448286/105856124-86e76200-5ff1-11eb-8aa1-3e0914801eb3.gif)

**Comment by eviljeff** [comment]
> * I've noticed that android theme categories throw an error now "Invalid category parameter" and the themes page show the recommended extensions on the see more shelves instead of themes. I know themes on android have been completely removed by @bobsilverberg and right now these URLs are hidden but in case that's an unexpected result please let me know.

Seems to happen on prod https://addons.mozilla.org/en-US/android/themes/ already so it's not a regression from this issue.

From a quick poke around, the cause is that the underlying search from a page such as:
https://addons.mozilla.org/en-GB/android/search/?category=causes&sort=recommended%2Cusers&type=statictheme
is:
https://addons.mozilla.org/api/v5/addons/search/?app=android&appversion=86.0&category=causes&promoted=recommended&sort=recommended%2Cusers&type=extension&lang=en-GB
i.e. **type=extension** rather than `statictheme` so the category doesn't match.

I'm assuming it was a side effect of removing non-extension support from frontend for Fenix as it only supports extensions.
