### ISSUE TITLE
Cannot search for 57+ addons *only*

### ISSUE THREAD

**Issue by ericjung** [mozilla/addons-server#6009]
### Describe the problem and steps to reproduce it:

I want to search AMO for addons that only work with Firefox 57 or above (WebExtensions)
https://addons.mozilla.org/en-US/firefox/search/?platform=mac&appver=57.0

### What happened?

I used https://addons.mozilla.org/en-US/firefox/search/?platform=mac&appver=57.0, and AMO displayed addons that were compatible with Firefox 56 and earlier.

### What did you expect to happen?

Only Firefox 57 (WebExtensions) would be in the result set.

### Anything else we should know?

Legacy addons should have an implicit maxVersion of 56.*

**Comment by diox** [comment]
Yeah, there is an issue with app version filtering that I noticed today - essentially it does not work as expected. You can work around that by searching for the `firefox57` special tag that we add to all WebExtensions: https://addons.mozilla.org/en-US/firefox/search/?platform=mac&appver=57.0&tag=firefox57

> Legacy addons should have an implicit maxVersion of 56.*

This is tracked in https://github.com/mozilla/addons-server/issues/5277

**Comment by diox** [comment]
QA: what has been fixed here is only the version filtering in the sidebar (altering max version for legacy extensions is covered in another issue). The versions displayed in the sidebar should depend on the search results themselves, and picking a version should refine the results and only show you add-ons which are compatible (*) with the version you picked.

(*) Where compatible means:
 - The add-on minimum version should be lower or equal to the version chosen
-  The add-on maximum version should be higher or equal than the version chosen **if `strictCompatibility` is enabled in the add-on `install.rdf`**, otherwise it should be ignored completely.

**Comment by ValentinaPC** [comment]
@diox : a couple or questions:
- `sidebar` is the "Filter Results" menu?
- `versions` are the Firefox versions you can select from the filter menu?
- I cannot submit an add-on with `maxversion` over 53, so even if I have `strict compat` set, I cannot put a `maxversion` over the ones listed in the filter menu - 54, 55, 56, 57...so the add-on will not be listed through results, nu?

Thanks in advance, Mat!

**Comment by diox** [comment]
- `sidebar` is the "Filter Results" menu?
- `versions` are the Firefox versions you can select from the filter menu?

Yes to both

- I cannot submit an add-on with `maxversion` over 53, so even if I have `strict compat` set, I cannot put a `maxversion` over the ones listed in the filter menu - 54, 55, 56, 57...so the add-on will not be listed through results, nu?

I don't follow. What's listed in the menu are the versions from the add-ons in the results...

**Comment by ValentinaPC** [comment]
> What's listed in the menu are the versions from the add-ons in the results...

How do I find add-ons compatible with older FF versions?

**Comment by diox** [comment]
It's not easy to do - the sidebar is meant to refine results, so that can't help you do that (it sucks, I know - IMHO the functionality is almost useless to end-users)

Your best bet is to find an existing legacy add-on and upload a new version (and approve it) with the restrictions that you want regarding compatibility.

**Comment by ValentinaPC** [comment]
> picking a version should refine the results and only show you add-ons which are compatible

**Case 1:** 
- new version for https://addons-dev.allizom.org/en-US/firefox/addon/video-downloader-player/?src=search
- `strictcompatibility` set 
- `maxversion` is 36 - lower than selected from the sidebar (54)
Results: the add-on is still displayed, but on grey, is this ok? shouldn't be removed entirely?

**Case 2:**
- new version for https://addons-dev.allizom.org/en-US/firefox/addon/firebug/?src=search
- `maxversion` is 56 - bigger than selected from the sidebar (54)
- `strict compat` set
Results: the add-on is removed entirely - shouldn't be displayed in this case?

**Case 3:**
- new version for https://addons-dev.allizom.org/en-US/firefox/addon/anonymox/?src=search
- `minversion` is 55 - bigger than selected (54)
- `maxversion` is 56  - bigger than selected from the sidebar (54)
- `strict compat` set
Results: the add-on is removed entirely

**Comment by ValentinaPC** [comment]
I think that was he problem! Things seem to work as expected for both Case 1 and 2.

Could you please select "Firefox 56" from the sidebar and see if Case 3 is working as expected?
Thanks!

**Comment by diox** [comment]
Case 3 seems to be working properly: when selecting 56.0 I see it, when selecting 54.0 I do not

(pro tip: you can manually set a version that is not displayed in the sidebar by manipulating the URL. So for instance this searches for anonymox using Firefox 54.0: https://addons-dev.allizom.org/en-US/firefox/search/?q=anonymox&platform=all&appver=54.0&page= )

**Comment by ValentinaPC** [comment]
> when selecting 56.0 I see it

It is ok to be grey? because of the value of the **minversion**, yes?

Thanks for the tip :)

**Comment by diox** [comment]
I'm using nightly (56), so it's not greyed out for me (it's marked as experimental, so I see yellow&black stripes)

Using release (54), it is indeed greyed out when it appears in search results (because I forced it through changing `appver` in the URL) - as expected, since it's not compatible with the actual version of Firefox I'm using.

**Comment by ValentinaPC** [comment]
I was also using FF54. I thought that the search will be refined while changing the filter option from the sidebar and the results will not care about the version browser that I am using, but only about what I've selected.

So, it seem like, everything works here, as you expect, yes?

**Comment by diox** [comment]
> I was also using FF54. I thought that the search will be refined while changing the filter option from the sidebar and the results will not care about the version browser that I am using, but only about what I've selected.

The results being returned or filtered out depend entirely on the sidebar (and the version pre-selected initially in the sidebar is your current version). But when displaying each result, the version of the browser you are using is used to determine whether or not you can install it and show you the appropriate button.

To give another example: you could technically search for Firefox 54 compatible add-ons using Chrome and playing with the sidebar and/or the URL. It should return add-ons compatible with Firefox 54.0, but then display the giant "Only with Firefox - Get Firefox Now!" button for each result instead of the regular install button.

> So, it seem like, everything works here, as you expect, yes?

Yes, I think so.

**Comment by ValentinaPC** [comment]
Thanks fro clarification!
I think we can follow the other dependencies, and mark this as verified-fixed.
