### ISSUE TITLE
Display slugs related to the guids in the find replacement admin tool

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6147]
The find replacement admin tool allows entering a guid to make a replacement via a path mapping. The downside of this is some guids are not obvious. 

To make it easier to know what the mappings represent it would be handy if the page could lookup and display the slugs related to the guid in the admin so that we know what's being replaced more easily.

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on FF57.0a1 and  FF55.0.2 under Wind 7 64-bit on -dev server.

The “Guid slug” column is displayed in the find replacement admin tool and contains the name of the Add-on from the Add-on URL path.

Please see the video:
![slugname](https://user-images.githubusercontent.com/15885467/29706431-80c983e4-898a-11e7-9641-71de36bac412.gif)
