### ISSUE TITLE
Add a test link to the admin tool for replacement addons

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6148]
It would be handy to show a test url for the replacements to be able to quickly test a replacement works as expected without needing to manually construct a URL.

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on FF57.0a1 and  FF55.0.2 under Wind 7 64-bit on -dev server.

The “Test” link is added in the “url” column and after you click on the link, it redirects the user to the inserted path.

Please see the video:
![replacement-addons](https://user-images.githubusercontent.com/15885467/29705606-7e7aa7b0-8987-11e7-8eb3-de5a6ae3aabc.gif)
