### ISSUE TITLE
Can I publish my test version for a limited number of users?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mozilla/addons-server#6151]
I can make a private listing on Chrome Store but looks like can not at AMO.

In Private Listing I mean that I can set emails of people that can open extension page on AMO (other users will see 404).

I need this during development phase of my extension.

**Comment by diox** [comment]
AMO does not support private versions like this no. Through AMO, you have the following possibilities:
- Submit an unlisted version of your add-on, then distribute it yourself. Note that if you want updates to work, you'll have to add support for them yourself since AMO is not handling distribution.
- Submit a beta version of your add-on (unfortunately only possible once you already have a public version of your add-on). AMO will have a separate update channel for users of the beta versions, but those are public - anyone can install them.

**Comment by jvillalobos** [comment]
You can also submit a listed version and mark it as experimental, which gives it less visibility on the site.

We may support private add-ons in the future, but it's not on this year's roadmap. We're focusing on the move to WebExtensions at the moment.
