### ISSUE TITLE
API does not surface custom license URL

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#6168]
### Describe the problem and steps to reproduce it:
See/blocks: https://github.com/mozilla/addons-frontend/issues/2589

The output of https://addons-dev.allizom.org/api/v3/addons/addon/fb-purity-cleans-up-facebook does not include a license URL but the Django app uses `addon.current_version.license_url()` to create one. If that URL should always just be `{addon_url}/license/{addon.current_version.version}/` then we can just generate it, but the API should be returning the correct license URL either way.

### What happened?
The license URL was not sent and we assumed none existed.

### What did you expect to happen?
The license URL was sent.

**Comment by diox** [comment]
There is a property of the `license` object that is supposed to be used for this, `url`. However it's currently returning `null` for custom licenses. Custom licenses should be displayed by AMO, as you noted it should be `{addon_url}/license/{addon.current_version.version}/`.

 I'll make the API return that for the `url` property instead of `null` when it's a custom license, but you'll need to implement that page in the frontend - the text of the license can be obtained by querying the [version detail API](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail) with the version id (something `current_version` does not give you for performance reasons)

**Comment by tofumatt** [comment]
Sounds good. Yeah, we would need to create the page as well, but for now we can at least add the link for mobile pages and they'll get the desktop fallback.

Thanks! 👍

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7, Android 7.2.1)
Custom License is displayed as a link and works as expected.
Postfix screenshots:
![license](https://user-images.githubusercontent.com/15685960/29404767-9ab1c0b0-8344-11e7-8ad7-630c7e7e092a.png)
