### ISSUE TITLE
When Firefox 57 releases, AMO Homepage should not present legacy extensions

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#6181]
Legacy extensions will not work in Firefox 57. As such, the AMO homepage shouldn't spotlight any legacy content whatsoever.

For manually programmed editorial areas, this is easy enough to address (https://github.com/mozilla/addons/issues/457).

But the AMO homepage has system-generated content buckets that require consideration. Namely, extensions sorted as **Popular** and **Up & Coming**.

**Comment by diox** [comment]
We can try to filter them out, but ultimately, it will look weird if we suddenly remove add-ons incompatible with 57 from these sections, especially if we do it now... Note that the homepage is cached and should not vary depending on the user-agent, so if we do any filtering it must apply to everyone (unless we do it in JavaScript after loading of the page, but that'd be janky)

/cc @jvillalobos for product input.

**Comment by jvillalobos** [comment]
I agree that we should do this, and also agree that the timing needs to be right. I'm thinking we could do this after 57 hits Beta, on September 26th.

**Comment by grahamperrin** [comment]
FWIW I reckon that the changes should be sooner. Maybe also change the servers' caching policies for a limited period. 

(IMHO it's weird to find a very prominently featured extension that's explicitly abandoned; to feature any extension that results in a yellow alert after installation; and so on.)

**Comment by diox** [comment]
Implementation thoughts:

Easiest fix is probably going to be filtering by `current_version__files__is_webextension`, and always do that, regardless of the client. The drawback is, that means adding a `.distinct()` to the relevant queries, which has an additional perf cost. Of course, that also means legacy extensions would disappear from the homepage forever.

**Comment by grahamperrin** [comment]
> … legacy extensions would disappear from the homepage forever.

If that's to happen, then maybe – to benefit users of ESR <57, and other special audiences – Mozilla should curate a **non**-featured collection that aims to capture some of the previously 'homed' legacy add-ons.

**Comment by diox** [comment]
So, doing this really by filtering in the database queries is going to hurt performance a bit. I'm not sure how noticeable it's going to be, hopefully not a lot because we fetch very few (6 to 10) add-ons, but until now the queries made for the homepage are kept simple with low impact.

I'm thinking about cheating and re-using the Frozen Addons functionality. Add-ons in that list are filtered out by their ids, and never appear in popular/up & coming. If we add the 20 or so most popular add-ons in that list, that should take care of the issue. The only drawback is that we then need to monitor them from time to time to check whether they uploaded a webextension (until the new frontend comes and solves this problem by having a completely different homepage).

Thoughts, @jvillalobos ? I can dig into the perf issue with the query further, but I'm not sure it's worth it just to keep a few add-ons from the homepage compared to re-using the frozen list.

**Comment by jvillalobos** [comment]
Managing the frozen add-ons list would be a manual chore, and the Up & Coming section doesn't show particularly popular add-ons, so it could be hard to keep up with what should or shouldn't be filtered out.

Having said that, maybe we don't need this issue anymore. The current plan is to release the new front-end before Firefox 57 is released. So we would need to ensure that we are handling this correctly in the new front-end rather than the old one. /cc @devaneymoz @muffinresearch

**Comment by diox** [comment]
New frontend should always be passing `app` and `appver` parameters to the the API and filter out incompatible extensions. I can see this happening on https://addons.mozilla.org/en-US/firefox/extensions/ when forcing my browser to load the new site (top rated and most popular appear, filtered).
