### ISSUE TITLE
Unlisted add-on not signed even though email received saying it was signed

### ISSUE THREAD

**Issue by mkaply** [mozilla/addons-server#6188]
Customer uploaded their add-on to AMO (unlisted) and received this email:

Your add-on, Anpassungen für Stadt Freiburg 1.1.5, has passed our
automatic tests and is now signed and ready for you to download at
https://addons.mozilla.org/de/developers/addon/695134/versions . Note
that you need to be logged in as a developer of the add-on before
downloading.

Upon downloading, the add-on is NOT signed. I have downloaded it and verified. There is no signing info in the XPI.

They tried two different times and neither is signed.

**Comment by jvillalobos** [comment]
I can reproduce this on -dev. Not sure what is going on here, since previous versions that were signed aren't very different. It's usually some manifest error, so it could be related to the very old compatibility range.

**Comment by mkaply** [comment]
Is this going to be looked at? This seems like a pretty big deal. Has anyone else reported issues?

**Comment by diox** [comment]
It's priority 2, so we are treating it as a pretty big deal. Nobody else has reported this kind of issue however, so it could be that only this particular add-on is affected.

**Comment by diox** [comment]
From the logs of my new upload on dev: 
Not signing version 1532773: not for a Firefox version we support :/data/olympia/src/olympia/lib/crypto/packaged.py:144

This is bad because it's a) only raised at signing time and b) silently ignored (though logged...). It happens for legacy extensions targeting a pretty old (< 37) version of Firefox as their max version in the manifest. It started happening because we set strict compatibility on all legacy add-ons in the database.

**Comment by diox** [comment]
This should be fixed on master, and will land on -dev shortly. It will be cherry-picked to land on prod on Thursday.

@mkaply : once the fix hits prod, will you need us to sign your version or can you delete the broken one(s) and upload a new one?

**Comment by mkaply** [comment]
> once the fix hits prod, will you need us to sign your version or can you delete the broken one(s) and upload a new one?

Deleting broken and reuploading should be fine. Thanks!

**Comment by vcarciu** [comment]
Verified as fixed by submitting a legacy extensions targeting an old (< 37) version of Firefox as max version in the manifest on AMO-dev. After downloading the extension, it was signed (verified with the same legacy extension on Stage where it was not signed) : 
![signed](https://user-images.githubusercontent.com/1583842/29619255-526db4b0-8823-11e7-97a7-1f09da5418e4.png)
