### ISSUE TITLE
Green install button for incompatible langpacks

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#6196]
Steps to reproduce:
1.Go to https://addons.mozilla.org/en-US/firefox/addon/english-us-language-pack/ on latest nightly
2.Try to install the lang pack from the green install button

Expected results:
If the lang pack is not compatible with Firefox version, the button should not be green

Actual results:
The button is green, but an incompatibility message is displayed when trying to install it and lang pack cannot be installed

Please see video for this bug:
![langpackgreenbutton](https://user-images.githubusercontent.com/1583842/29466353-4561ad58-8445-11e7-82f6-16328ca177d6.gif)

**Comment by diox** [comment]
Paging @jvillalobos and @wagnerand for input.

So, this is a langpack that was created for Firefox 55.0. It's marked as compatible with Firefox 55.0 and later on AMO.

*Technically*, AMO seems to be behaving as expected: it's considering the langpack as compatible by default since strict compatibility is not enabled for this add-on, so it presents a 57 user with a green install button. Should AMO behave differently? Is the fact that it's not installable a Firefox bug? Or is everything working as expected here?

**Comment by wagnerand** [comment]
For langpacks, it doesn't matter whether the author set the `strictCompatibility` flag or not. They are always strict-compatible.

Imho, the button should not be green and there should be a message about incompatibility.

**Comment by diox** [comment]
Ok, I'll force them to be considered as having strict compatibility always enabled then.

**Comment by vcarciu** [comment]
Verified as fixed : 
![lang](https://user-images.githubusercontent.com/1583842/29967740-dae2dd12-8f20-11e7-9313-eba2f5d32a18.png)
