### ISSUE TITLE
Daily users stats are broken since 16.08.2017

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons-server#6199]
### Describe the problem and steps to reproduce it:
The daily users stat count is 0 starting from 16.08.2017 for all extensions. This also includes all the substats like versions etc.

### What happened?
The usage stats say 0 users for every extension

### What did you expect to happen?
At least my usage of the extensions should show up (so the stats should have at least one user reported)

### Anything else we should know?
You can observe this for example in these stats: https://addons.mozilla.org/en-US/firefox/addon/justintv-stream-notificatio/statistics/usage/?last=30

**Comment by jvillalobos** [comment]
I can confirm on other add-ons as well.

**Comment by bqbn** [comment]
8/17 data on [1] is restored. 

8/16 has not because I don't have the privilege to run some of the scripts that can regenerate those data. I've asked for that privilege in a Bugzilla ticket. We'll have to wait for that.

[1] https://addons.mozilla.org/en-US/firefox/addon/justintv-stream-notificatio/statistics/usage/?last=30

**Comment by muffinresearch** [comment]
Duplicating to https://github.com/mozilla/addons/issues/510
