### ISSUE TITLE
Developer-disabled add-ons show in Featured Add-ons promo box

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6251]
We got a [report from a user](https://twitter.com/monzta/status/901124779729715200) that pointed out a disabled add-on showing up in the homepage. It turns out the add-on was disabled by the developer, but the Featured Add-ons promo box still displays it. We shouldn't show add-ons in that state when we're showing featured add-ons.

**Comment by diox** [comment]
Screenshot from that twitter post, in case it disappears:

![disabled_showing_up_in_featured](https://user-images.githubusercontent.com/187006/29867153-f9221128-8d7a-11e7-805d-68d207f62b35.jpeg)

My guess is that's because the promo modules work in their weird mysterious ways... The featured extensions list (e.g. https://addons.mozilla.org/en-US/firefox/extensions/?sort=featured) does not show disabled add-ons (they are cached for 10 minutes though), but the various old promo modules might.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF55(Win 7).
I've disabled some extension from the promo box, and they where no longer listed in there.
Example: https://addons-dev.allizom.org/en-US/developers/addon/web-developer/versions
Postfix screenshot: 
![2017-09-04_0957](https://user-images.githubusercontent.com/15685960/30014971-705e5956-9157-11e7-9503-6618e5c5f3a9.png)
