### ISSUE TITLE
Consider adding release notes to the add-on detail API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6268]
As of https://github.com/mozilla/addons-frontend/issues/2760 we will always display release notes for the current version (if they exist) on the add-on detail page. Currently this means we will have to make a separate API request to get the version detail object. 

Would it be possible just to include `current_version.release_notes` in the [add-on detail API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#detail)?

**Comment by diox** [comment]
Note: we need to tread carefully here. So far we've avoided loading translations from the `current_version` (and well, `current_beta_version`), to avoid extra queries when *listing* add-ons. We can probably live with the extra query on the detail endpoint, but until now we've re-used the same serializer almost everywhere.

The extra query per add-on is hard to avoid because we don't know about the version until late in the transformer (the rest of the translations are all fetched in a single query regardless of how many add-ons are in the queryset)

Because of this we'll probably need to limit this to the detail endpoint only, which means a new serializer, things like that.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
