### ISSUE TITLE
Weird add-ons around AMO

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6345]
Steps to reproduce:
Go to:
1. https://addons.allizom.org/en-US/firefox/addon/mongolian-language-dictionary/?src=search
2. https://addons.allizom.org/en-US/firefox/addon/photoxpress-search-pane/
3. https://addons.allizom.org/en-US/firefox/addon/slovar-za-slovenski-jezik/

Actual results:
1. Dictionary with type=2, unsigned (also found some other unsigned dictionaries)
2. Found between search tools but has an install.rdf and 3 installation buttons
3. No type, no signature

Notes/Issues:
Verified on AMO-stage and -prod using FF57(Win 7).

**Comment by diox** [comment]
Those add-ons are super weird. I'm not sure how they managed to get uploaded, but then again they are super old... @jvillalobos can we disable them? The files not matching what type AMO expects for the add-ons cause all sorts of issues...

**Comment by jvillalobos** [comment]
I disabled (1) and (2). (3) is okay in prod and just appears to be out of date in stage. I can disable it in stage if that helps.

**Comment by diox** [comment]
Thanks, I took care care of the 3rd one in stage. 

@ValentinaPC let us know if you find other weird add-ons like these so that we can clean them up - since the ones found so far are super old I'm not worried about bugs in the code yet, but if you find ways to submit such weird add-ons please file issues as well!
