### ISSUE TITLE
Detect WebExtension Language Packs and assign correct type

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6350]
This is part of #6297.

Per [bug 1365709](https://bugzilla.mozilla.org/show_bug.cgi?id=1365709), language packs can be identified by the `"langpack_id"` manifest entry.

Language packs are required to have both a `strict_min_version` and `strict_max_version`. Otherwise an error should be shown.

**Comment by diox** [comment]
@EnTeQuAk do you think we should have something in the metadata returned by the linter to do this, or just look at the manifest ourselves in addons-server ? See also https://github.com/mozilla/addons-linter/issues/1526

**Comment by EnTeQuAk** [comment]
Currently addons-server detects on its own so I guess it makes sense to keep it that way. afaik the server needs that information before the linter is run anyway so both should run their detection separate from each other.

**Comment by diox** [comment]
Ok, so it makes sense to have the detection part in addons-server. What about the requirement to have both `strict_min_version` and `strict_max_version` set ? It's up to addons-server to validate the versions, but ensuring the properties are present in langpacks feels more like a linter job to me.

**Comment by diox** [comment]
> Ok, so it makes sense to have the detection part in addons-server. What about the requirement to have both strict_min_version and strict_max_version set ? It's up to addons-server to validate the versions, but ensuring the properties are present in langpacks feels more like a linter job to me.

We discussed this on IRC. It makes sense to do that check in the linter so that it can be used independently of addons-server, for instance when generating the langpack in the first place. Note that the task on AMO that fetches langpacks does *not* run validation, and does *not* display errors since it's an automated task (they are logged, though).

**Comment by diox** [comment]
QA: because of the previous comment, to test this, only submit webext language packs with `min_strict_version` and `max_strict_version` set. Forcing those properties to be present will be done in mozilla/addons-linter#1526

**Comment by ValentinaPC** [comment]
@diox:
1. Webext Lang Packs should be auto-approved? (because submission steps are like for auto-approval)
2. Public webext lang packs - https://addons-dev.allizom.org/en-US/firefox/addon/polski-language-pack-test/ - take into account the strict_min/strict_max values, but the install button is still green.

What do you think?

**Comment by diox** [comment]
1. Not sure. @jvillalobos ? At the moment auto_approve ignores non-extensions
2. Not sure what the problem is. Your langpack is compatible with the Firefox version I'm using so the install button is green...

**Comment by ValentinaPC** [comment]
2. Sry. Was on the wrong place.

**Comment by jvillalobos** [comment]
Yes, language packs should be auto-approved, provided they pass the tests in https://github.com/mozilla/addons-linter/issues/1526

**Comment by diox** [comment]
Ok, I filed https://github.com/mozilla/addons-server/issues/6398 for that.

**Comment by ValentinaPC** [comment]
Due to above comments and separate tracking of the other issues we can mark this verified fixed.
