### ISSUE TITLE
Last pages for themes/collections after an empty search cannot be loaded

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6367]
Steps to reproduce:
1. Make an empty search on AMO-prod from Themes homepages https://addons.mozilla.org/en-US/firefox/search/?q=&cat=themes
2. Scroll down and go to the last page https://addons.mozilla.org/en-US/firefox/search/?page=20494&cat=themes

Expected results:
User is redirected to last page.

Actual results:
Even if the URL is changed and pointing to last page, the user is still on the first page.

Notes/Issues:
- reproducing for collections
- not reproducing for extensions

Notes/Issues:
Verified on AMO-prod FF55(Win 7).
Screenshot for this issue:
![2017-09-08_1251](https://user-images.githubusercontent.com/15685960/30209788-6b0cd9d4-94a2-11e7-8440-c945b1277d82.png)

**Comment by EnTeQuAk** [comment]
I'm marking this as fixed as we don't allow empty searches in the new frontend anymore and should have fixed most pagination related bugs by now. Please re-open at any time in case we didn't.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk I'm not sure what you mean by: 

> we don't allow empty searches in the new frontend anymore

From what I see, new AMO is still returning results when performing an empty search.

Regarding paginations, I found  bug  [#3887](https://github.com/mozilla/addons-frontend/issues/3887) which doesn't seem to be fixed yet. From my understanding, this should have been fixed by [#6919](https://github.com/mozilla/addons-server/issues/6919)

I'm not re-opening this case since it relates to an old frontend issue, but I think [#3887](https://github.com/mozilla/addons-frontend/issues/3887) mentioned above should be looked at.
