### ISSUE TITLE
Temporary solution to fix bad UX for downloading Containers in FF 57+

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/addons-server#6446]
### Describe the problem and steps to reproduce it:
In https://github.com/mozilla/addons-server/issues/6424 there is a proposal for giving Mozilla-signed legacy addons a better download/install UX.  In the meantime, the Containers addon has been released and is in the middle of a marketing cycle.  A blog post went out on Thursday (https://blog.mozilla.org/firefox/introducing-firefox-multi-account-containers/) and Snippets for FF55 and FF56 are going out today (https://bugzilla.mozilla.org/show_bug.cgi?id=1399272).  We had to hold off on FF57 snippets because of the poor download UX.  For now, we have the full webextension (and hence fully compatible with FF57) addon available from download on github.

As Firefox 57 moves to beta next week, we will have more users attempt to install the addon and get stuck by the following:
1) The scary warning that makes them think twice about installing
2) When the user clicks "Download Anyway" they are asked whether they want to save or open the download.  If they open it, they have to pick the right program to open it with.  If they save it, they have to find the location, and then pick the right program to open it in.  If there is more than one profile open, it may end up downloading in the wrong profile.

Would you be able to hack up an interim solution for this?  Either allow the download without the additional warning and poor UX, or offer the FF57 compatible addon for users who visit the website with FF57+.  Or an alternate solution?

### What happened?
User gets warning about legacy addon and "Add to Firefox" button is grayed out - https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

If user clicks Download Anyway, they are asked whether they want to save or open the download.  If open, they probably don't know what program to open with.  If save, they may not know how to fidn the saved download and install it.

### What did you expect to happen?
1) User can click Add to Firefox button on https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ and get either the pre-57 non-webextension addon, or the post 57 webextension addon.
If that's not possible..
2) The Download Anyway button properly installs the addon for the user, so they don't have to figure out what program to open and install it in.

### Anything else we should know?
Ideally, we would like something in place before FF57 beta is released on September 26th.  Thank you!

**Comment by diox** [comment]
> 1. User can click Add to Firefox button on https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ and get either the pre-57 non-webextension addon, or the post 57 webextension addon.

That's not possible. Though AMO tries hard to serves you a version that is compatible with your browser when doing updates, we don't do it in other pages because there would be a massive performance cost in doing this in all listing pages. And it's a lot of work, so it's unlikely it'd be ready in time.

There is a whole discussion about this in https://github.com/mozilla/addons-server/issues/5482 that lead to us adding "view more versions" link to link to the old versions page when the current version is incompatible. The rationale is that developers will upload a version compatible with the latest and greatest Firefox, and users of old versions will see a greyed button on the detail / listing pages, but still have the link to install older versions that are still compatible with their old Firefox.

> 2. The Download Anyway button properly installs the addon for the user, so they don't have to figure out what program to open and install it in.

The "Download anyway" link is not meant to install, it's meant to download when the version is not compatible, and as such tries hard to prevent installation when you click on it, on purpose. We could change that (cc @jvillalobos) but IMHO that's poor UX, especially because we have no way of knowing whether or not the add-on will install properly.

I think implementing #6424 is an easier and less problematic fix in the timeline we're given.

**Comment by jonathanKingston** [comment]
I think Tanvi was asking for my simpler fix mentioned in this comment: https://github.com/mozilla/addons-server/issues/6424#issuecomment-329814801

The fix should be a whitelist to allow that button to work, other changes can be done in the other bug perhaps?

**Comment by TanviHacks** [comment]
If 6424 will be done soon (it sounds like it will be done in the next week or two) then this issue is mute and we can close it.  I filed it just to see if there was a quicker/easier fix in the meantime.

**Comment by jvillalobos** [comment]
Closing this in favor of #6424.

> The fix should be a whitelist to allow that button to work, other changes can be done in the other bug perhaps?

Checking that an add-on is in a whitelist is probably as easy as checking that it's signed with the internal Mozilla certificate. The complexity comes from making the site work differently (and consistently) in that case.
