### ISSUE TITLE
remove /accounts/login API endpoint

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6448]
from #6415 
> we actually never use the login endpoint on the frontend..."

If it's not used on addons-frontend then its possibly/probably unused so we should remove it...?

**Comment by kumar303** [comment]
It's true that we don't currently use it (ops verified this by checking the access logs). This is because we call `accounts/login/start` which then redirects to Firefox Accounts, does magic, redirects to `addons-server` (which sets a cookie), and redirects again to `addons-frontend`. At this point the frontend has a cookie that we can pass to subsequent API requests for auth.

If @diox thinks we won't need the `login` endpoint in the future (if we change how this works) then we could remove it.

The internal auth docs could use some freshening up, at least this: https://github.com/mozilla/addons-server/issues/6452

**Comment by diox** [comment]
Removing it and documenting `/accounts/login/start` instead sounds good. I'd like to dig a little in the history to find what it was supposed to be for initially. Was it implemented for the new-but-then-removed admin tools that were in addons-frontend? Something else?

**Comment by kumar303** [comment]
> Was it implemented for the new-but-then-removed admin tools ... ?

Maybe? The frontend used to be calling it here but no one knows how this was being used. I suspect it was the admin. https://github.com/mozilla/addons-frontend/pull/3145/files#diff-9c6af2bc9310bfed1e429d02f827c559L191

**Comment by eviljeff** [comment]
I'm thinking I can remove `/internal/accounts/login/` too as it's following the same pattern.

**Comment by eviljeff** [comment]
Also, `/accounts/register` seems to be similarly unused.  (remove all the things)
