### ISSUE TITLE
Hide add-ons whose latest version has been manually reviewed in post-approval queue

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6479]
If the latest listed version of an add-on has been manually approved by a reviewer, the add-on shouldn't appear in the auto-approval queue anymore.

**Comment by diox** [comment]
Implementation thoughts: I thought I was going to do this by just comparing the auto-approved version `reviewed` date with the `last_human_review` date, but `Version.reviewed` date sucks, it's only set when we change the add-on status... I'm too scared to change that now, and using the `reviewed` on the file rows is annoying because of joins, so I'll probably add a simple boolean field on `AutoApprovalSummary` to show whether or not that particular auto-approval was approved, and filter on it...

**Comment by ValentinaPC** [comment]
Auto-approved add-ons that have latest version manually reviewed (approved, rejected) are no longer listed in the review queue.
Postfix example:
![no find](https://user-images.githubusercontent.com/15685960/30806544-ed9bc388-a1fe-11e7-9ac8-d88e27a6a4e8.gif)

**Comment by kewisch** [comment]
@ValentinaPC can you verify for a confirm approval also? Rejections were often not a problem even before this issue was fixed.

**Comment by ValentinaPC** [comment]
@kewisch : I've checked for every manual review, including confirm approval, but I put only a case in the video, because of the size.
Here is another video:
![conf-app](https://user-images.githubusercontent.com/15685960/30845959-554f7c5a-a29e-11e7-87f6-74c3e2ff63f9.gif)

**Comment by kewisch** [comment]
Perfect, thanks!
