### ISSUE TITLE
Find a way to monitor how auto_approve is doing

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6512]
We need to be able to monitor how `auto_approve` is doing. Even though it tries its best to not crash, it can happen (#6507) and we need to be notified when that happens to be able to react and not leave the queues completely stuck.

At the moment reviewers can note the new/updates counts growing in reviewer tools but soon they won't be able to, if https://github.com/mozilla/addons-server/issues/6508 is fixed. 

https://github.com/mozilla/addons-server/issues/5409 is related, but I don't think that's the right solution, because a) we'd need to constantly be monitoring datadog b) number of approvals depend on the number of submissions - it's hard to deduce when the script is stuck with that number.

**Comment by diox** [comment]
Maybe periodically look at how many versions are waiting to be approved, and warn if it goes beyond a specific threshold ?

**Comment by diox** [comment]
Random related idea: `auto_approve` could catch more exceptions. or fire up async tasks to approve add-ons. We'd just need to make sure we don't swallow errors.

**Comment by kewisch** [comment]
You could note the date before you start `auto_approve`, run the script, then check for all add-ons submitted before that date that have not been approved yet. If there are any, then it is probably stuck. Of course you'd need to leave a little room for add-ons not auto-approved due to reviewers having the page open or other factors. Maybe combine with a try/catch, it sounds to me like the problem is rather finding a good place to notify though :)
