### ISSUE TITLE
Language packs are not compatible with FF56

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#6543]
### Steps to reproduce:
1. Open https://addons.mozilla.org/en-US/firefox/language-tools/
2. Select any language pack and try to install it.

### Expected results:
Language packs can be installed.

### Actual results:
The install button is grayed out and the language pack can't be installed. If the user tries to download the language pack and try to install it via drag and drop the message that the add-on is not compatible is displayed.

### Notes/Issues
Verified in FF56(Win7) Issue can be reproduced in addons.mozilla.org
Screenshots for this issue:
![disabledbutton](https://user-images.githubusercontent.com/15685441/31014214-6d2bb042-a522-11e7-89f4-b66a980e1e0e.png)
![notcompatible](https://user-images.githubusercontent.com/15685441/31014218-6fb19ca0-a522-11e7-890e-2e5411545ed7.png)

**Comment by EnTeQuAk** [comment]
Hmm, importing them is still a manual process so maybe this got missed. Firefox 56 is fairly new.

@jvillalobos unless I'm mistaken the language pack import is in the admin (something around https://addons.mozilla.org/admin/langpacks/) and only needs to be started. With a bit of luck that'll fix it, they all seem to exist at https://ftp.mozilla.org/pub/firefox/releases/56.0/win32/xpi/ so that looks good.

**Comment by jvillalobos** [comment]
Oh, good call. The person who usually does this is currently unavailable.

I kicked off the process now.

**Comment by jvillalobos** [comment]
Looks like it's done.

**Comment by madalincm** [comment]
Verified as fixed in FF56(Win7)
Language packs can be installed in FF56. Marking bug as verified fixed.
![langpackcompat](https://user-images.githubusercontent.com/15685441/31077598-c17f932c-a787-11e7-8b95-ffb22c4a0fc1.png)
