### ISSUE TITLE
Auto-approval should stand down if the last version was rejected by a human.

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#6545]
### Describe the problem and steps to reproduce it:
Inside /queue/auto_approved, some reviewers feel that once a version has been rejected by a human, the very next submission should not get auto-approved. 

Multiple time in the past we saw new uploads getting rejected over and over again because the dev didn't understand or was not willing to do the requested changes. While it wasn't a problem before as the queues were all manually checked by human, it could be problematic with the new auto-approved queue.

Such case would end up in an infinite cycle : The dev uploading a new build again and again, getting visibility on AMO while reviewers are rejecting it after a few hours. This is especially true for malware, hive miners, etc.

If this is not something we want to implement, maybe one of the following option could be available for the reviewers : 
 1 - Setting an admin flag will stop the auto-approval so that an admin reviewer can verify what's going on.
 2 - Adding a set of rules in the new guidelines that will take care of such "cat & mouse" game.
 3 - Add a set of rule in the "weight" system that jump its position to the top of the queue if the latest submission was manually rejected.

Thanks!

**Comment by diox** [comment]
Note that past rejection history already increases the weight : each rejected version in the past year adds `10` to the weight, up to a maximum of `100`.

**Comment by jvillalobos** [comment]
I really don't want to create exceptions to the auto-approval process because it makes things much more complicated for everyone. As mat pointed out, past rejections increase the add-on's weight (which we can adjust in the future if we don't think is enough). Also, the moment a developer re-uploads something that was flagged to them, you should feel free to ask an admin to take down the listing.

Having auto-approval means developers have more responsibility about their actions, and that means we can be harsher if they misbehave.

**Comment by spoji** [comment]
I'm fine with this as having the addon's weight increased via previous rejection was one of my options. 

Thanks!
