### ISSUE TITLE
Add random sort ability to Search API

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#6560]
Hi,

In order to retrieve a list of featured add-ons, the addons-frontend project uses the [Featured endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#featured). Yet, this endpoint does not support other parameters like `appversion`, which we now need to only show compatible add-ons to the users.

The [Search API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search) has everything we need to retrieve a similar list of featured add-ons, **except** that we cannot get a random result set (the main point of the Featured endpoint).

By adding a new `sort` type (e.g. `random`), we could rely on the Search API endpoint in the frontend and stop calling the Featured endpoint, which could be then removed.

**Comment by diox** [comment]
We should be able to implement this using [Random Scoring](https://www.elastic.co/guide/en/elasticsearch/guide/current/random-scoring.html). However, we need some kind of protection to make sure we're not shooting ourselves in the foot, since random sort can be costly if not limited (we don't want the random scoring to be done on the whole index!). Maybe only accept if if `featured` is passed.
