### ISSUE TITLE
Up & Coming extensions has very old, incompatible add-ons

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6571]
Today, the [Up & Coming list](https://addons.mozilla.org/firefox/extensions/?sort=hotness), including the homepage show some very old add-ons, like [Fission](https://addons.mozilla.org/addon/fission/?src=hp-dl-upandcoming) (last updated in 2009), [Clipmarks](https://addons.mozilla.org/addon/clipmarks/?src=cb-dl-hotness) (last updated in 2010), and [SQLite Optimizer](https://addons.mozilla.org/addon/sqlite-optimizer/?src=cb-dl-hotness) (also 2010).

They all show a spike in their stats, so I'm not sure if unusual download counts triggered their Up & Coming ranking, or the other way around. Regardless, we should figure out how they got there. And we should probably have a hard limit of recency for Up & Coming add-ons. Maybe 6 months? /cc @devaneymoz

**Comment by diox** [comment]
We did some digging on IRC, and it's linked to... how Firefox used to handle compatibility.

Those old add-ons have been installed by some users for a while, but were disabled because their `maxVersion` was super old, older than `4.0` (this is a special case for compatibility that `services/update.py` does, regardless of `strictCompatibility` being enabled). However on September 21st we [bumped the compatibility for a bunch of add-ons](https://github.com/mozilla/addons-server/issues/6425), including those. This resulted in a spike of daily users visible in their stats, which in turn made their `hotness` score high, and they ended up in Up & Coming.

The quick workaround is to add them to `FrozenAddons` to hide them from the homepage, but we nee d to figure out what to do with them. If they still work (we're still receiving update pings, so presumably them being enabled didn't completely break Firefox for affected users...) maybe it's fine, but if not we should consider taking down those add-ons and adding them to blocklist to disable them remotely.

**Comment by muffinresearch** [comment]
@jvillalobos does this also impact https://github.com/mozilla/addons-frontend/issues/3312 ?

**Comment by jvillalobos** [comment]
Probably. I don't think we do any filtering regarding legacy/WE or compatible/incompatible for the front page.

**Comment by diox** [comment]
From standup today: we decided to lower the priority since the add-ons have been added to the frozen addons to prevent them from entering the homepage.

**Comment by devaneymoz** [comment]
So am I to understand "Up & Coming" won't be part of the redesign launch on 2 Nov? It is currently slated to be part of the overall Homepage content lineup for launch. 

Further, if filtering is an issue between legacy/WE that also affects "Most Popular" as well, correct? Also a significant part of the Homepage.

**Comment by jvillalobos** [comment]
> So am I to understand "Up & Coming" won't be part of the redesign launch on 2 Nov?

This doesn't really affect the launch. We manually removed the old add-ons from showing up in Up & Coming, and can do it for others if they bubble up. Fixing this issue (by setting a hard recency limit) should address this more reliably.

**Comment by diox** [comment]
> Further, if filtering is an issue between legacy/WE that also affects "Most Popular" as well, correct? Also a significant part of the Homepage.

The new frontend *will* filter out incompatible extensions when listing up & coming and popular, once https://github.com/mozilla/addons-server/issues/6560 is fixed and the corresponding API used in addons-frontend. 

The legacy fontend does not filter them out, because it fetches that data in a different way that makes it a lot harder (see https://github.com/mozilla/addons-server/issues/6181#issuecomment-330893810).

**Comment by muffinresearch** [comment]
@jvillalobos do we need to take any action on this on the basis it should cease to be a problem when we depreacate the legacy frontend?

**Comment by jvillalobos** [comment]
I think setting a recency limit to Up & Coming should help avoid this problem. As I understand it, the other issues just address the compatibility issue.

**Comment by grahamperrin** [comment]
> … the [Up & Coming list](https://addons.mozilla.org/firefox/extensions/?sort=hotness), …

FWIW, today: 

- includes legacy Classic Theme Restorer, when viewed with Waterfox 56.2.3 (on FreeBSD-CURRENT, without a UA override for AMO)
- shows only compatible extensions (the three rows of four), when viewed with Firefox 62.0

**Comment by EnTeQuAk** [comment]
Unless I'm misreading something here, I'm going to close this issue, as it's only regarding the legacy sites which we're going to remove (as @diox mentioned) - and all legacy add-ons are deprecated / disabled now anyway.

Feel free to re-open anytime though.
