### ISSUE TITLE
Allow Static Themes packages to be submitted via devhub

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6572]
[Tracker mozilla/addons/issues/501]

Actually, this should be possible already.  But we need specific support in the views/models to identify and treat these add-ons differently to extensions.

**Comment by eviljeff** [comment]
@jvillalobos so many questions here about the submission flow and what metadata we will and won't collect vs. a standard webextension (or compared to a xul complete theme, or a LWT).  Can you fill in some blanks?

**Comment by eviljeff** [comment]
refs https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme
https://developer.mozilla.org/en-US/Add-ons/Themes/Theme_concepts#Static_theme_approaches

**Comment by eviljeff** [comment]
@jvillalobos also, categories - same as LWT?  Same as Complete Themes?  Or some new set?

**Comment by jvillalobos** [comment]
Let's start the discussion with an edited version of what's in the [PRD](https://docs.google.com/document/d/1d9acBumpdK87sYg7Ah98BEKvL7b4tuO-RDpgqbm7FTs/edit#): 

* Themes will be submitted using the same submission flow as extensions, where the final theme package is uploaded.
* The existing submission flow will be enhanced with an option to use the simple lightweight submission form (upload header image, set colors) most theme designers are accustomed to use. We need to expand this form to support [some additional properties](https://docs.google.com/document/d/1KksEgOYPeg3erlFk8R_EXC5GhVuFvU7w8js2DOWNbcQ/edit?ts=59cc33f7#).
* Theme packages will be signed in the same way as extension packages.
* Upon completion of the upload, the add-on should be identified either as a theme or an extension.
* Themes shouldn’t require code validation beyond checking the package and manifest.

Compared to the existing add-on submission flow, for static themes:
* It won’t be required to have platform selection (or multiple files in a version), the experimental flag, a privacy policy, or notes to reviewer.
* The license should still be required, but AMO should list the content licenses shown for lightweight themes (variants of Creative Commons).
* The list of available categories should be the same one as for lightweight themes, and also restricted to a single category per theme.

**Comment by eviljeff** [comment]
thanks.  fwiw, I'm going to add the LWT style form separately because it'll pretty much have to be rewritten from scratch - this will just be making devhub's extension submission flow work.

**Comment by jvillalobos** [comment]
I [created a separate doc](https://docs.google.com/document/d/1NB5RNu_eoJmDAlb1V_BrT-4BpmHUc1ZvGjOEZS5hQvQ/edit) explaining the changes to the submission flow. Needs review by @atsay and @pwalm.

**Comment by ValentinaPC** [comment]
@eviljeff: Could you provide an example of static theme? I was looking around but could not find a proper one.
Thanks in advance!

**Comment by eviljeff** [comment]
I've been using one from https://github.com/mdn/webextensions-examples/tree/master/themes

**Comment by ValentinaPC** [comment]
Verified this on AMo-dev FF56(Win 7) and obtained the following results.

1. Themes will be submitted using the same submission flow as extensions, where the final theme package is uploaded - works as expected
_**2. The existing submission flow will be enhanced with an option to use the simple lightweight submission form (upload header image, set colors) most theme designers are accustomed to use - not added - will this be added separately as you mention in one of the above comments?**_
**_3. Theme packages will be signed in the same way as extension packages - - is this implemented already? because static theme is not found in any queue from Reviewer Tools_**
4. It won’t be required to have platform selection (or multiple files in a version), the experimental flag, the required payment flag, a privacy policy, or notes to reviewer - works as expected
5. The license should still be required, but AMO should list the content licenses shown for lightweight themes (variants of Creative Commons) - works as expected
6. The list of available categories should be the same one as for lightweight themes, and also restricted to a single category per theme - works as expected

What do you think, @eviljeff ? Thanks!

**Comment by eviljeff** [comment]
yep, the theme wizard and review tools support will be implemented separately.

**Comment by ValentinaPC** [comment]
Based on above comments, this can be marked as verified-fixed.
Verified on AMO-dev FF56(Win7).
Postfix screenshots:
![details](https://user-images.githubusercontent.com/15685960/31892483-ccdd9abc-b811-11e7-9807-8faa4fa15d41.png)
![ff_range_vrs](https://user-images.githubusercontent.com/15685960/31892484-ccfeaea0-b811-11e7-94cd-95343e6054a4.png)
![static_theme_issue2_-_no_continue_using_old_form](https://user-images.githubusercontent.com/15685960/31892485-cd1fc3b0-b811-11e7-9c51-af364a3f3399.png)
![untitled](https://user-images.githubusercontent.com/15685960/31892678-52b7bc9e-b812-11e7-9818-a53028daad9c.png)
