### ISSUE TITLE
Reviewer leaderboard is broken

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#6573]
Title. Points seem to be double the amount the real value is. If a user has 100k points, he/she is listed in the leaderboard as having ~200k points.

**Comment by erosman** [comment]
Note: The error is only on `Leaderboard`

I see the correct amount on `https://addons.mozilla.org/en-US/editors/queue/updates`

**Comment by jvillalobos** [comment]
I'm thinking this is related to us moving to the post-review system. @erosman was onboarded (added to the `Senior Add-on Reviewers` group) and has double points, while Teo hasn't been onboarded yet and shows a normal amount. Could be that the query is double-counting because of the presence in two reviewer groups.

**Comment by diox** [comment]
Yes, that's it. The query does not expect the same reviewer to be present in both `Add-on Reviewers` and `Senior Add-on Reviewers` groups. Same goes for `Persona Reviewers` vs `Senior Persona Reviewers`.

**Comment by diox** [comment]
@jvillalobos you can fix it by not having the same user in those 2 groups, so I'm closing the issue and letting you handle that.
