### ISSUE TITLE
Investigate trend of add-on updates served to Firefox < 45

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6612]
Firefox has supported a JSON add-on update manifest since version 45, but support for the old RDF format [can't be dropped](https://bugzilla.mozilla.org/show_bug.cgi?id=857458) until add-ons stop using it. In particular, AMO needs to start serving the JSON updates.

We need to figure out if it's worth supporting both formats for some time, to support Firefox < 45, or just do a clean switch. Just looking at the [stats for AdBlock Plus](https://addons.mozilla.org/addon/adblock-plus/statistics/usage/applications/?last=30), there are hundreds of thousands of clients older than that. However, legacy add-ons are getting updated less and less now, so it might not be worth supporting updates for those clients (ESR is already at 52).

What I'd like to know is _how many add-on files are actually served_ to Firefox < 45 clients, how it compares to Firefox >= 45 and what the trend is. @bqbn, do we have logs that can get us that information?

**Comment by bqbn** [comment]
Our Nginx access logs contain clients' user-agent headers. UA header sent by a Firefox browser includes the Firefox version. Thus I think we should be able to pull the info you want from the access logs. I don't know what criteria defines "an add-on file is served" in particular though.

That said, I think the best way to obtain the info is to work with our BI team, since they already have the tools and infrastructure to process and analyze the access logs for various statistics.

**Comment by jvillalobos** [comment]
We weren't able to get a good response here, so I'm closing this issue.
