### ISSUE TITLE
(Advanced) Search in new queues

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#6615]
Title. It's a bit hard to search by developer name/add-on name etc. right now if looking for a particular add-on or developer in the new queues.

**Comment by caitmuenster** [comment]
+1 on this -- I tried to search for an extension that had been rejected to find its risk assessment and did not have much luck doing that. :(

**Comment by wagnerand** [comment]
@caitmuenster That's because it's a queue, not a log. Add-ons that don't need a review don't show up in there (and they shouldn't).

I do agree that our search needs improvement. We have to spec what exact use cases we have.

**Comment by caitmuenster** [comment]
Ah, that makes sense! Thanks for the reminder about the log. :)

**Comment by wagnerand** [comment]
I believe a similar search that is not limited to the queue is planned for the upcoming reviewer tools work.

@jvillalobos can you confirm?

**Comment by jvillalobos** [comment]
We have a website where you can search for add-ons :P

The reviewer tools plans includes a tool for searching add-on code, but nothing new otherwise. You can search for add-ons in the queue, and you have some filtering options in the log. Looking for old reviews can be challenging sometimes, but adding a search tool just for that may be overkill.

**Comment by wagnerand** [comment]
Closing based on Jorge's last comment. If we really need this, let's come up with a user story and file a new issue.
