### ISSUE TITLE
Celery 4: remove pickle serialization

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6642]
In #6625 we added and defaulted to json serialization but kept accepting pickle for backwards compatibility.

Let's remove `pickle` serialization once the upgrade is done and seems stable.

**Comment by diox** [comment]
QA: This affects all asynchronous tasks on the site. So check that things like add-on validation is still working, as well as sending emails, indexing add-ons for search, uploading themes, uploading previews, etc.

**Comment by AlexandraMoga** [comment]
We have tested several actions that could have been affected by this change, like:
- submitting various add-on types and checking the validation results
- performing various actions that would trigger emails (i.e. add-on submissions, review actions, developer replies, abuse reports, user reviews etc)
- submitting add-ons and checking that they are indexed for search, i.e they can be found in search results after several minutes
- submitting themes and theme updates
- uploading and deleting pictures, like add-on icons and screenshots, user profile pictures

Since there are no issues to report with the above actions, I'm going to mark this issue as verified fixed on dev and stage with FF60, Win10x64
