### ISSUE TITLE
Redirect old contributions pages to listing page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6689]
As part of #6069, we removed some pages, like the developer profile and roadblock pages. Some developers were linking to them directly from their add-ons and possibly their websites. Let's set up redirects for those pages so they go back to the listing page instead of being a 404.

**Comment by ValentinaPC** [comment]
Added those pages in an add-on description and clicking on them will reload add-on details page.
Verified this on AMO-dev/stage FF56(Win 7).
Postfix video:
![contrib](https://user-images.githubusercontent.com/15685960/31723367-56df70f8-b427-11e7-9e8b-3f4970ad2f1b.gif)

@eviljeff : Was this fixed in stage too?

**Comment by eviljeff** [comment]
@ValentinaPC It was fixed in dev and stage (and will be in prod after the deploy tomorrow)

**Comment by ValentinaPC** [comment]
My question was made because I could not reproduce the issue (before the fix) in both dev and stage.
Things work ok in production too.
Marking this verified-fixed.
