### ISSUE TITLE
Allow donating to Mozilla via donate.mozilla.org

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#6692]
There used to be an option to donate to Mozilla, which is gone with the new contribution URL. We could either add donate.mozilla.org to the whitelist, or go some steps further to restore this feature in a simple way.

It would be great if donate.mozilla.org/ and donate.mozilla.org/thunderbird would work.

**Comment by jvillalobos** [comment]
Adding `donate.mozilla.org` as a supported domain sounds good to me. Since this works for Firefox and Thunderbird, and covers different payment methods, I think it makes sense to include it, rather than chasing MoFo people to get direct links. Also, having it in the list of supported domains should be enough to hint at developers who want to donate to us.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
The "donate.mozilla.org" domain was added and redirects as expected. 
Postfix screenshots:
![2017-10-19_1103](https://user-images.githubusercontent.com/15685960/31760482-8100580c-b4bd-11e7-9d11-a840df5dbf8f.png)
![2017-10-19_1104](https://user-images.githubusercontent.com/15685960/31760483-811feaaa-b4bd-11e7-94ee-30641d7995de.png)
