### ISSUE TITLE
API response to indicate that add-on has been disabled by its developers

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6757]
### Describe the problem and steps to reproduce it:

Request an add-on that has been disabled by the developer, such as:

```
curl https://addons.mozilla.org/api/v3/addons/addon/firefm/
```

### What happened?

401 response:

```json
{
   "detail" : "Authentication credentials were not provided."
}
```

### What did you expect to happen?

The response should include something like "This add-on has been removed by its author" (or disabled by an admin) since that's what the old site displayed: https://addons.mozilla.org/en-US/firefox/addon/firefm/

<img width="968" alt="screenshot 2017-10-23 17 10 18" src="https://user-images.githubusercontent.com/55398/31915708-1283b3aa-b815-11e7-80b5-7d4a80ab9f56.png">

### Anything else we should know?

frontend issue: https://github.com/mozilla/addons-frontend/issues/2261

**Comment by diox** [comment]
Safest way to do that is probably to handle that directly in the `AddonViewSet` when returning the 401 or 403, i.e. not modify the permission class, because the permission classes might be used elsewhere where we do want to make sure we keep the 401/403...

**Comment by diox** [comment]
@kumar303 I've added `is_disabled_by_developer` and `is_disabled_by_mozilla` to the 401/403 responses returned by the add-on detail API.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7).
If I disabled as an admin, the result is correct.
![2017-10-27_1256](https://user-images.githubusercontent.com/15685960/32098703-3ea17df6-bb16-11e7-9703-d9c7d55bcc4e.png)

**As a developer of an add-on**, I've disabled the only version of an add-on from "Manage Status & Versions" page from Dev Hub, but the API response lists `is_disabled_by_developer` as  `false`. 
Example: https://addons-dev.allizom.org/en-US/developers/addon/csimple-webext-test/versions
@diox Is this ok?

**Comment by diox** [comment]
This is the kind of edge case I was worried about regarding `is_disabled_by_mozilla`... I'll look into it. In this case, both properties should be `false` : disabling the last version is not the same thing as doing a developer disable on the add-on, so `is_disabled_by_developer` being `false` is right, it's just that `is_disabled_by_mozilla` should not be `true`.

**Comment by diox** [comment]
Eh actually I misunderstood, I thought your screenshot was for the second add-on you were talking about. Everything is OK here: for `csimple-webext-test`, since it has no version left, it's incomplete (not the same thing as the developer disabling the add-on itself) so both `is_disabled_by_mozilla` and `is_disabled_by_developer` are `false`. That's normal.

**Comment by ValentinaPC** [comment]
@diox How its an add-on disabled by its developer?

**Comment by diox** [comment]
By switching `Listing visibility` to `Invisible` in devhub (I know, worst naming ever)

**Comment by ValentinaPC** [comment]
Yes...I should have understood from the first comment/screenshots :)
Verified this case also and seems to work as expected.
Example: https://addons-dev.allizom.org/en-US/developers/addon/webext-invalid-date/versions

Still have a case:
- marking each version as disabled by Mozilla, from admin page - https://addons-internal.dev.mozaws.net/en-US/admin/addon/manage/webext-invalid-date/ - will not set the api response for "is_disabled_by_mozilla" to true, I guess because, add-ons status turns into Incomplete, are we ok with this?

**Comment by diox** [comment]
> marking each version as disabled by Mozilla, from admin page - https://addons-internal.dev.mozaws.net/en-US/admin/addon/manage/webext-invalid-date/ - will not set the api response for "is_disabled_by_mozilla" to true, I guess because, add-ons status turns into Incomplete, are we ok with this?

Yes.

**Comment by ValentinaPC** [comment]
Marking this verified-fixed based on above comments.
