### ISSUE TITLE
src parameter is not reflected in add-on version install URL

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6758]
### Describe the problem and steps to reproduce it:

Make a request with a `src` parameter for an add-on like this:

```
curl 'https://addons-dev.allizom.org/api/v3/addons/addon/awesome-screenshot-plus-/?src=dp-btn-primary'
```

### What happened?

The install URL of the version does not include the same `src` parameter:

```js
"files" : [
         {
            "id" : 253549,
            "url" : "https://addons-dev.allizom.org/firefox/downloads/file/253549/awesome_screenshot_plus-7-an+fx.xpi?src=",
         }
      ]
```

### What did you expect to happen?

Since I made a request using a `src` parameter I expected it to be included in the install URL like:

```
https://addons-dev.allizom.org/.../awesome_screenshot_plus-7-an+fx.xpi?src=dp-btn-primary
```

### Anything else we should know?

Is my expectation of what should happen correct? I was basing it on this from the [docs](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail-object):

> **files[].url** (string) – The (absolute) URL to download a file. An optional src query parameter can be added to indicate the source page (See download sources).

Note that this is not a critical bug because we probably will always need to adjust the `src` ourselves. I was just surprised that this isn't working. Maybe the docs need updating?

**Comment by diox** [comment]
The docs are poorly worded, you're supposed to add the `src` parameter yourself - the doc is merely stating that you can add it to the URL.

I'm not sure it's a good idea to have the API automatically add it for you, because it encourages clients to call the API with different URLs depending on the situation, ruining potential caching (that we don't have right now, I'll admit) and the bug here is more the fact that it adds an empty `src` parameter in the first place...

**Comment by kumar303** [comment]
aha! That makes way more sense. You can either close this or clarify it in the docs (which would have helped me).

**Comment by vcarciu** [comment]
Can we add "qa: not needed" on this one ?
