### ISSUE TITLE
Bad link?

### ISSUE THREAD

**Issue by CjBots** [mozilla/addons-server#6784]
clicked on the link in 1. Click on the "Add to Firefox" button You will find this button on the mozilla add-ons for firefox page at https://support.ant.com/hc/en-us/articles/210106706-How-to-install-the-video-downloader-for-Mozilla-Firefox

I got an 'unknown' message

Wanted to download Ant video downloader

**Comment by EnTeQuAk** [comment]
I can't seem to find this add-on on our site so maybe it got disabled or removed by the author. There are a few other alternatives though if you take a look at https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=video+downloader

I'm closing this bug since from my perspective there's nothing we can do.
