### ISSUE TITLE
Search: Remove (accidental) negative boosts 

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6838]
Supports #2661 

We currently have negative boosts for a few things like:

* `match_phrase` on `summary` and `description` (0.8 and 0.3)
* `match` on `tags` (0.1)
* analyzed fields of `summary` and `description` (0.6)

which appear random and accidental. Let's either remove them (keep the search but remove the boosts) or make them positive boosts as they were probably thought to be.

This will be *very* hard to test.

**Comment by diox** [comment]
> This will be very hard to test.

Actually, from testing I've been doing for https://github.com/mozilla/addons-server/issues/9551 it might be easier than we thought. If the index we're testing against is completely empty, then document scores should be consistent across test runs - so we just need to make sure the test index is empty before running the relevant unit tests.

And locally, I've been able to confirm this while working on #9551 : scores are definitely lowered because of those boosts, and the explain API confirms that the boosts are multiplied, which is why a value between 0 and 1 *decreases* the score.

**Comment by diox** [comment]
QA: We've made matches against summary & description have more impact on the position of add-ons in search results (including translation in the current language if there is one), and removed matching against tags, but ultimately it's difficult to test. Do a few searches for terms that appear in descriptions & summaries and see if it matches your expectations as a user.

**Comment by AlexandraMoga** [comment]
Verified on AMO stage with FF62, WIn10x64

Here are my test results (as relevant as they can be when searching on stage):

Results - as expected:

- [cross-site scripting](https://addons.allizom.org/en-US/firefox/search/?platform=windows&q=cross-site%20scripting) - [Result](https://screenshots.firefox.com/a3IQVlTkMhsLfVFr/addons.allizom.org)
- [keyboard scroll](https://addons.allizom.org/en-US/firefox/search/?platform=windows&q=keyboard%20scroll) - [Result](https://screenshots.firefox.com/bJ6xsAZmhiWEHOFA/addons.allizom.org)
- [show country flag](https://addons.allizom.org/en-US/firefox/search/?platform=windows&q=show%20country%20flag) - [Result](https://screenshots.firefox.com/PjpDsIAKpS7bsN97/addons.allizom.org)
- [make the web faster](https://addons.allizom.org/en-US/firefox/search/?platform=windows&q=make%20the%20web%20faster) - [Result](https://screenshots.firefox.com/xEJ1SHjPSl87AptF/addons.allizom.org)
- [tab browsing](https://addons.allizom.org/en-US/firefox/search/?platform=windows&q=tab%20browsing) - [Result](https://screenshots.firefox.com/yush921Fk0oPV8Gh/addons.allizom.org)
- [image search](https://addons.allizom.org/en-US/firefox/search/?platform=windows&q=image%20search) - [Result](https://screenshots.firefox.com/VhMDZl4A6w1k2n8t/addons.allizom.org)
- [besten Preise online](https://addons.allizom.org/de/firefox/search/?platform=windows&q=besten%20Preise%20online) - [Result](https://screenshots.firefox.com/b8U757uyzv9Nm4Yy/addons.allizom.org)
- [bloqueur de nuisances](https://addons.allizom.org/fr/firefox/search/?platform=windows&q=bloqueur%20de%20nuisances) - [Result](https://screenshots.firefox.com/7m5wwx1ZMXeQGzhR/addons.allizom.org)

Results - not as expected

- `"Hide your IP address"` - finds [Stealthy](https://addons.allizom.org/en-US/firefox/addon/stealthy/?src=featured)  while `"Hide IP address"` - doesn't find it at all because is missing the `"your"`
- `"word of the day"` - expected to find [Disconnect](https://addons.allizom.org/en-US/firefox/addon/disconnecttet/?src=homepage-collection-featured) as it has the searched string in the description => found it only on the second page of results
- `"find best deals"` - finds [Ciuvo price checker](https://addons.allizom.org/en-US/firefox/addon/ciuvo/?src=search) while `"find deals"` doesn't find it at all because is missing the `"best"`
- `"Website vertrauen"` - expected to find [WOT - Sicher surfen](https://addons.allizom.org/de/firefox/addon/wot-safe-browsing-tool/?src=search) higher in search results => found at the bottom of page 3

Conclusion: there seem to be some enhancements in search suggestions, but there still is room for improvement. 
I'm marking the issue as verified fixed for now, remaining to also check prod once this lands.

**Comment by diox** [comment]
@AlexandraMoga : can you file individual bugs for these 4 results ? File them in addons-server, tag them as `search`, I'll look into each later.

**Comment by AlexandraMoga** [comment]
I have filed 4 new bugs, as requested and linked them all to this issue.
