### ISSUE TITLE
Remove name_sort field

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6899]
We implemented `name.raw` in #6895 so now `name_sort` is not needed anymore.

* [ ] Change default field that is being used in `SortingFilter` to `name.raw`
* [ ] Remove field from addons.indexers

**Comment by SeanPrashad** [comment]
Hey there! I'd love to tackle this if it's still available!

**Comment by diox** [comment]
Thanks, @SeanPrashad !

QA: make sure sorting by name when searching addons still works. You can't do that on the new frontend, but it should be possible on the legacy site and in the API.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, FF58 (Win10x64)

Results:
1. Sort by Name on the legacy site still works as expected; checked for extensions, themes, search tools, collections, DevHub (My Add-ons)
2. Sort in the API (I guessed you were referring to v3.0) :
 - extension search - in general sorting by name will show the correct results but there are some inconsistencies; the below request, for example, will list two extensions - **id 492376 and id 494543** which shouldn't be listed on page 8; the connection between the two is that both have localized names:
```
GET https://addons-dev.allizom.org/api/v3/addons/search/?sort=name&type=extension&tag=firefox57&page=8
```
   - persona search - first 8 pages will display themes with 'blank' names; if I'm looking for one of these themes in the frontend, the details page won't load because there are no version published; should these themes appear as search results?
From page 9 - 1000 sorting seems to be working well, although page 1000 will only reach letter 'B'
```
GET https://addons-dev.allizom.org/api/v3/addons/search/?sort=name&type=persona/
```
@diox what do you think about the 2 point mentioned above?

**Comment by diox** [comment]
Name sorting does not take translations into account, it uses english (if no english translation is available, it uses the one in the add-on's default locale).

**Comment by diox** [comment]
Also, blank name personas with no versions are weird, but that's not something coming from these changes. Please file a new issue about these so we'll take a look.

**Comment by AlexandraMoga** [comment]
The two add-ons I've mentioned (id 492376 and id 494543) both had an English (en-US) translation in their locales file and both had default_locale set to en-US. They are listed among add-ons starting with "C" while their (english) names are starting with "G" respectively "D". 
This is what I don't really understand. 

For the second point, I will open an new issue as suggested.

**Comment by diox** [comment]
@AlexandraMoga : ok, that's bad. It's not a regression though, it's yet another issue. I think it's because we don't explicitly set which translation to use when indexing the name we use for sorting purposes (for the affected add-ons, some translations do start with a "C") . It's a minor problem since very few add-ons provide translations for their name and we don't care much about sorting by name anyway, but it should be filed.

**Comment by AlexandraMoga** [comment]
Thanks, @diox 
I will file  a separate issue for this point then.

Since no other problems specifically connected with name sort were spotted, I will mark this one as verified fixed.
