### ISSUE TITLE
Approved Content Review page still shows "Approve" button.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6901]
See https://reviewers.addons.mozilla.org/en-US/editors/review-content/classgerman :

![png image 1238 x 305 pixels](https://user-images.githubusercontent.com/873258/32726725-467a8286-c87a-11e7-8bd4-8c06388ddcbf.png)

**Comment by diox** [comment]
As mentioned on IRC this was done on purpose, because it works like confirm approval for post-review, which also has this behavior. cc @jvillalobos for input.

Note that the add-on is correctly excluded from the content review queue for a year - so you'd have to have kept the link or craft it yourself.

**Comment by jvillalobos** [comment]
I think it could be useful for a second reviewer (like an admin) to reaffirm some content review after it's been questioned. I'm not opposed to removing that option, though.
