### ISSUE TITLE
Some global statistics occasionally report zero

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#6918]
https://addons.mozilla.org/statistics/addons_in_use/?last=30
https://addons.mozilla.org/statistics/addons_downloaded/?last=30

Almost every other day, the "add-ons in use stat" reports zero. Same for add-ons downloaded, but it happens less frequently.

**Comment by Croydon** [comment]
Yes, this is incredible annoying.

**Comment by jvillalobos** [comment]
The global stats pages are going away with the old front-end pages. They haven't been updated for years and are known to be broken in a few ways. The missing data is probably related to the general stats problem (https://github.com/mozilla/addons/issues/510), but we're not making any changes to these pages since they're going away.

**Comment by Croydon** [comment]
@jvillalobos Are you saying that there won't be any statistics data anymore at all?

**Comment by jvillalobos** [comment]
The stats dashboards for individual add-ons, [like this one](https://addons.mozilla.org/firefox/addon/adblock-plus/statistics/), will continue to exist. The [global stats](https://addons.mozilla.org/statistics/addons_in_use/) will eventually go away.
