### ISSUE TITLE
Provide a link to an extension's repository

### ISSUE THREAD

**Issue by emceeaich** [mozilla/addons-server#6922]
Enhancement: provide an explicit way to include a link to an extension's repository so that its source may be inspected by someone considering installing it

From https://bugzilla.mozilla.org/show_bug.cgi?id=1417151

**Comment by diox** [comment]
Hi,

This is a good idea, but add-on developers can already use the homepage field for this, no need to add a new one (the number of fields the developers can/must fill is already pretty large).

**Comment by sanbor** [comment]
I love to check repositories because it's where I can see if a project is active, the commit history, open bugs, etc.

@diox suggested that "add-on developers can already use the homepage field". This is misleading for both add-on users and developers. As a user I often find difficult to find a link to the repo in many websites. I just went to https://addons.mozilla.org/en-US/firefox/ and picked three random extension homepages: https://www.ghostery.com/, https://www.soeren-hentzschel.at/firefox-webextensions/new-tab-override/ and http://piro.sakura.ne.jp/xul/_treestyletab.html.en As you can see, none of those homepages provide a link to the repository. So the purposed workaround seems to fail in practice.

Moreover, a developer might think that as she/he doesn't have a proper homepage for the project to leave that field blank, while she/he might didn't realize that the github repo of the extension could serve for the purpose of a "homepage".

I feel that it would be very useful to have a link to the repo. It would save time, it would be intuitive, and it would promote good free software practices.

I hope you will reconsider your position 🙂
