### ISSUE TITLE
Return theme descriptions from Discovery Pane API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6953]
This supports https://github.com/mozilla/addons-frontend/issues/3892

The Discovery Pane API should return descriptions for all add-ons. Currently it doesn't return descriptions for themes.

This was requested in https://github.com/mozilla/addons-frontend/issues/3892#issuecomment-344332866 so that any theme installed via Discovery Pane will show up in the Firefox Add-ons Manager with a description.

Note that additional frontend work is needed but the first step is to get this data in the API response.

**Comment by eviljeff** [comment]
So, what happens right now is all constant (non-recommendation driven) extensions have descriptions written by Scott.  There aren't any descriptions written for LWT (because the disco pane doesn't show them).  So, excluding recommendations (which are an edge case, and I think still a pilot), we don't technically return the _addon summary_ for any results.

Is this just about returning `addon.summary` as the string `description` in `results[]` for those addon results that don't have one already defined?  (i.e. extensions from recommendations and LWT)  Or returning the summary for all addons in the `addon` object?

**Comment by kumar303** [comment]
Well, I just wanted to make sure the API is including theme descriptions when they exist. If it already does then maybe we can close this bug?

**Comment by AlexandraMoga** [comment]
@eviljeff could you please add some steps to verify this issue?
https://github.com/mozilla/addons-frontend/issues/3892 is still reproducing, so I am guessing this not what I'm supposed to verify at this point.
Thanks!

**Comment by eviljeff** [comment]
https://addons-dev.allizom.org/api/v3/discovery/ should have `description` for any themes in the list that have descriptions defined on AMO.  E.g. the first one, https://addons-dev.allizom.org/en-US/firefox/addon/swirley-purple/ does.
If mozilla/addons-frontend#3892 is still happening there's some work needed on the frontend side, I guess -  @kumar303

**Comment by eviljeff** [comment]
(This is assuming I've understood the problem correctly!)

**Comment by AlexandraMoga** [comment]
I've verified the API changes on stage and the theme description field is now populated when a theme has a description in AMO.

Here are some examples:

![image](https://user-images.githubusercontent.com/31961530/37395239-72432e8c-277e-11e8-8331-0ca91dbe9d6a.png)
