### ISSUE TITLE
`current_version` is somehow not the latest public listed version on some add-ons

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#6962]
### Describe the problem and steps to reproduce it:
Today (2017-11-20) we had two developers complaining that their latest approved version of their extensions are not visible on their listing page.

Version 0.3 of [keyword-search-webextension](https://reviewers.addons.mozilla.org/en-US/editors/review/keyword-search-webextension) is on AMO for two days now. However, the listing page still shows version 0.2

Version 3.0 of [open-tab-count-resurrected](https://reviewers.addons.mozilla.org/en-US/editors/review/open-tab-count-resurrected) has been pushed to AMO 3 hours ago (from what the dev told me). Their listing still shows up version 2.0 (which is an old version not Quantum compatible). This could be a cache related issue as this new version is just a couple of hours old.

### What did you expect to happen?
We start receiving quite a lot of questions from devs regarding this on IRC (in addon-reviewers). Maybe showing up a warning to the devs as CWS do could be helpful here. CWS warns the devs that it could take up to 60 minutes to see the new version of the listing page.

While it's understandable that cache can take a while to be cleared out of the listing page, 2 days seem a bit long for sure.

**Comment by mkaply** [comment]
Keyword search has actually been over a month (Oct 17)

**Comment by spoji** [comment]
Ouch, you're right.. It's more than a month old.

**Comment by diox** [comment]
Similar cause to https://github.com/mozilla/addons-server/issues/6960 . I only know of those 2 add-ons, it'd be interesting to find out if there are any more.

The `_current_version` is not set correctly on those add-ons for some reason. It should be set when the latest version is made public, in the same transaction, so that's very weird.

**Comment by mkaply** [comment]
Note I did upload those two versions very fast (one after the other). Maybe that's the cause?

**Comment by diox** [comment]
I thought about that but it's unlikely. Your upload of 0.3 was 8 minutes after 0.2 had been approved, that's plenty of time. 

The only thing that is suspicious in your case is that 0.3 was manually auto-approved by @spoji instead of auto-approved because it's a webextension, but that didn't happen with open-tab-count-resurrected.

**Comment by mkaply** [comment]
I have a new version to update. Can I submit it? Do you understand the problem enough to not need my usecase?

**Comment by diox** [comment]
@mkaply feel free to submit it. We're not aware of other add-ons affected for now, but even if the problem goes away we still have the logs.

**Comment by muffinresearch** [comment]
@spoji are you still seeing this show up as an issue?

**Comment by spoji** [comment]
@muffinresearch yes. 

Version 0.3 of [keyword-search-webextension](https://reviewers.addons.mozilla.org/en-US/reviewers/review/keyword-search-webextension) uploaded by @mkaply was approved months ago on AMO. However, the listing page still shows version 0.2.

**Comment by muffinresearch** [comment]
Would be good to understand what's happening here. @diox is there a manual fix to this or are we dependent on a new upload?

**Comment by diox** [comment]
We can manually fix this from a prod django shell/database shell. I really have no idea how this happened in the first place though.

**Comment by vcarciu** [comment]
I was able to reproduce this today on -dev, but unfortunately, I don't have any special steps. I normally uploaded a second version for a webext : 
https://addons-dev.allizom.org/en-US/developers/addon/wretzalark-penat-doldfis/versions

**Comment by diox** [comment]
I have a theory that it's because some task/cron is overwriting the fields on the add-on, because those don't use transactions and may have started before the version was changed by the approval (either auto-approve or manual reviewer approval).

**Comment by diox** [comment]
If that theory is right, STR for dev would look like:
- Submit an add-on, wait for it to be auto-approved
- Submit a new version **between minutes 16 and 19**. Wait for **minute 21**, refresh in devhub

If the bug is present, you'll see the wrong version being presented as the current public one. Since it's all dependent on timing and luck it's hard to be sure the STRs will work though.

**Comment by vcarciu** [comment]
@diox : I will try your theory and I will come back with the results

**Comment by diox** [comment]
The existing affected add-ons should be fixed by admins using raw SQL or something to update the `_current_version` - or hopefully just submitting and approving a new version should work.

We're not sure my change fixes the problem as QA hasn't been able to reliably reproduce the original issue, so we'll just hope for the best and re-open if we still see it in the wild.
