### ISSUE TITLE
Prevent listed submissions for an add-on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6990]
Some add-ons can't or won't align with our content policies, which is why they need to be entirely unlisted.
For those, we need to prevent any listed version submissions. We don't want to admin-disable the add-on because unlisted versions are ok.

**Comment by jvillalobos** [comment]
I think this should be merged with #6989, since it's essentially the same idea. There should be a way for admins to restrict auto-approval of new listed versions without having to admin-disable (which just disables everything). If the developer submits a new listed version it stays pending review and it'll be up to an admin to decide if it should be unflagged.

We'll also need some place to show these add-ons for admins to review them. Maybe we should just reuse the legacy queue, but that remains to be seen. I'm including this in the larger Q1 plans for the reviewer tools, so I'm leaving the `needs: product` flag.

**Comment by wagnerand** [comment]
Closing this based on the discussion in #6989. It's not the same feature, but we can use the feature for #6989 and try to make it work for this use-case too.
