### ISSUE TITLE
Review email to developers contains wrong reply-to address

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6992]
A developer tried to reply to the review email we sent, but the `Reply-To` field seems to be wrong. It contains the wrong hostname. (I redacted the token.)
```
Reply-To: reviewreply+XXX@olympia.prod.mozaws.net
```

They tried to replied and that email bounced:

```
----- The following addresses had permanent fatal errors -----
<reviewreply+XXX@olympia.prod.mozaws.net>
    (reason: 550 5.1.2 Recipient address reviewreply+XXX@olympia.prod.mozaws.net not accepted.)
```

I can provide the token in private if needed.

**Comment by wagnerand** [comment]
This might need help from @bqbn.

**Comment by bqbn** [comment]
A complete header of the email will help.

In general, our email infrastructure doesn't set the Reply-To header, it is up to the application to do that.

**Comment by eviljeff** [comment]
The server in the reply-to field is taken from `settings.INBOUND_EMAIL_DOMAIN`, which is `INBOUND_EMAIL_DOMAIN = env('INBOUND_EMAIL_DOMAIN', default=DOMAIN)` - i.e. unless it's overridden by env, it's settings.DOMAIN

**Comment by bqbn** [comment]
How to fix the issue?

It sounds like all we need to do is to set the correct default value for settings.INBOUND_EMAIL_DOMAIN in the code, which I think is reasonable, because the domain rarely changes anyway.

If you prefer Ops to set the value in /etc/olympia/settings.env (the env file), we can do that too. Please let me know how we want to proceed.

**Comment by bqbn** [comment]
Actually, I don't think this is a domain problem, because the domain `olympia.prod.mozaws.net` is configured with correct MX, i.e.,

```
$ dig +short olympia.prod.mozaws.net MX
10 mx.socketlabs.com.
```

What happens is if someone sends email to `reviewreply+XXX@olympia.prod.mozaws.net`, socketlabs gets it first, then it processes it and posts it to our endpoint, `https://addons.mozilla.org/api/v3/activity/mail/`.

I think we probably should look into if our endpoint responded something that made socketlabs refuse the message.

Also is the `XXX` in `reviewreply+XXX@olympia.prod.mozaws.net` literal Xs, or are they place holders? Anyways, a complete header will help troubleshoot.

**Comment by eviljeff** [comment]
The API only checks the shared secret key and, if set, `settings.ALLOWED_CLIENTS_EMAIL_API` (a list of IP addresses, the value from an env variable of the same name).  The rest of the processing is asynchronous in a celery task - the domain name isn't verified fwiw.  I think we'll need more details to be able dig out any logs to confirm.

But, even if the API was accepting the email, the issue is still valid as written - the reply-to address is supposed to be the public facing domain name, not the internal one.

**Comment by bqbn** [comment]
> But, even if the API was accepting the email, the issue is still valid as written - the reply-to address is supposed to be the public facing domain name, not the internal one.

I filed a ticket with Socketlabs to ask why emails sent to `@olympia.prod.mozaws.net` get bounced.

However, I do notice that for the same recipient, if the domain is `@addons.mozilla.org`, it goes through. So I think you're right that the real issue to be fixed here is that the domain name of the reply-to address being `olympia.prod.mozaws.net`. I'm not an expert for this, but based on the comment earlier, it sounds like all we need to do is to set the correct default value for `settings.INBOUND_EMAIL_DOMAIN` in the code.

**Comment by eviljeff** [comment]
@bqbn is `DOMAIN` in the env intentionally set to something other than `"addons.mozilla.org"` (the default is defined here https://github.com/mozilla/addons-server/blob/master/src/olympia/conf/prod/settings.py#L34).  Giving `INBOUND_EMAIL_DOMAIN` a default in settings.py is easy enough.

**Comment by ValentinaPC** [comment]
I've verified this on AMO-dev using Fake Email Logs page - https://addons-internal.dev.mozaws.net/en-US/admin/mail
Leaving a developer reply - for example - from AMO-dev, will generate a reply to address ending with "@addons-dev.allizom.org".
![2017-12-07_1729](https://user-images.githubusercontent.com/15685960/33723219-c49d3052-db74-11e7-8d6f-9f76a0ac063c.png)

I've also tried to sent a test e-mail from a personal account to that address and did not receive any errors back.

Is there anything else we should check here, @eviljeff ?

**Comment by eviljeff** [comment]
lgtm
