### ISSUE TITLE
Dead link to addons.mozilla (colourful tabs previous versions)

### ISSUE THREAD

**Issue by piecevcake** [mozilla/addons-server#7003]
https://addons.mozilla.org/en-US/firefox/1368/history/

link was at about:addons page - screenshot below

![x](https://user-images.githubusercontent.com/32110576/33173785-4962eb4e-d0ba-11e7-8246-7fd41d25edb1.png)

**Comment by diox** [comment]
The add-on is very old (was created in October 2005!) and if that URL ever existed it must have been broken for the past 8 years or so... I went as far back as 2010 in our repos and I could not find any references to it. It's part of the add-on description, it's not a URL we reference anywhere, so it should be fixed by the developer.
