### ISSUE TITLE
Show that a review has already been flagged (Review API)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7037]
### Describe the problem and steps to reproduce it:

Here are STRs on `addons-frontend`

* Sign in as a developer
* Go to one of your add-ons
* Read all reviews
* Flag some reviews as bug reports, etc
* Get a snack, switch computers (or just reload the page)
* Sign in again to finish flagging reviews

### What happened?

As soon as you reload the page, there is no indication that you have flagged any reviews.

### What did you expect to happen?

the UI should show that you already flagged a review so you don't have to flag it again.

### Anything else we should know?

We need additional info from the API for this.

Originally reported by a developer here: https://github.com/mozilla/addons-frontend/issues/3952

Maybe the [review object](https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#detail) can include a flagged reason for the authenticated user but I know things like that introduce caching challenges. We could query a separate endpoint but this would add an additional API request of course.

**Comment by eviljeff** [comment]
it's a similar problem to #6863

**Comment by AlexandraMoga** [comment]
The [rating details endpont](https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#get--api-v4-ratings-rating-(int-id)-) can be used now with the `show-flags-for` parameter in order to find out if the authenticated user has already submitted a flag report for the queried review. 
For example:
```
GET https://addons-dev.allizom.org/api/v4/ratings/rating/564062/?show_flags_for=<user_id>
```
![image](https://user-images.githubusercontent.com/31961530/48763642-648d8780-ecb6-11e8-90ec-854cc9bfbb65.png)
