### ISSUE TITLE
Auto Approved Add-ons/Content Review number differ between homepage and corresponding pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#7047]
Steps to reproduce:
1. Load Reviewer Tools unified dashboard https://reviewers.addons-dev.allizom.org/en-US/reviewers/
2. Observe Auto Approved Add-ons/Content Review number
3. Click on any of these 2 links
4. Repeat step #2

Expected results:
Numbers are the same in both places.

Actual results:
Numbers differ.

Notes/Issues:
Reproducing on AMO-dev using FF57(Win 7).
Video for this issue:
![number](https://user-images.githubusercontent.com/15685960/33323262-93087b7c-d454-11e7-8b18-227a270773eb.gif)

**Comment by diox** [comment]
Ah, yes. The dashboard does not exclude admin review add-ons, but the queues do.

**Comment by ValentinaPC** [comment]
The bigger number is on the queue side, jfyi.

**Comment by diox** [comment]
Yeah, it's because you're an admin reviewer and the queries actually _default_ to excluding add-ons under admin review when no information is passed. The dashboard does not pass that info so the add-ons are excluded, but the queues do pass that info so the add-ons are not excluded because you're an admin reviewer.
