### ISSUE TITLE
Changes for Describe form for themes

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7071]
Followup for #6860.

They're a bunch of (I think) small fixes, so I'm just bundling them in one issue. Feel free to branch it out:
* [x] Don't use bold for the licensing questions.
* [x] In the licensing questions, I see the bottom of some letters (like "g") being cut off.
* [x] The help popups in the licensing section are cut off to the left.
* [x] The default state for the checkboxes should be all of them being not selected. If that's not possible, default to the first checkbox being set to "No".

**Comment by AlexandraMoga** [comment]
Verified all 4 points enumerated above and all seem fixed now:
![image](https://user-images.githubusercontent.com/31961530/34882051-f70f6414-f7bd-11e7-91db-6ab1a9cd1f99.png)


@eviljeff I suppose that in order to solve point 3 (help popups) the licence selection section had to be re-positioned to the right, which leaves this empty space in the left margin.  
In my opinion, this affects a bit the overall look of the submission form. Isn't there a different workaround?
![image](https://user-images.githubusercontent.com/31961530/34882033-e59e2e5e-f7bd-11e7-9dd1-b4cb164f1421.png)

Verified on AMO-dev, FF57 (Win10)

**Comment by eviljeff** [comment]
> I suppose that in order to solve point 3 (help popups) the licence selection section had to be re-positioned to the right, which leaves this empty space in the left margin.

yes
> In my opinion, this affects a bit the overall look of the submission form. Isn't there a different workaround?

suggestions welcome 😉

**Comment by jvillalobos** [comment]
Can you try setting the margin only for the radio buttons (and not include the questions), and apply the same to the license options so they look consistent?

I suppose that if we can't make it work, we could drop the tooltips and link to some documentation.

**Comment by eviljeff** [comment]
I tried just with the labels when I was doing it and it looked worse.

What would the link be to documentation?

**Comment by jvillalobos** [comment]
How about this:
* Drop the margins.
* Drop the tooltips, except for "Yes, as long as they share alike". That's the item that is hardest to understand and presumably is not affected by the cropping issue.
* Add a new line to the box that says "Your add-on will be released...". The new line should have this link: [More information on Creative Commons licenses](https://creativecommons.org/licenses/).

**Comment by AlexandraMoga** [comment]
Considering that the desired changes have been implemented, I figured it would be better to track the last issue separately, in order to mark this as verified fixed.
New issue [#7308](https://github.com/mozilla/addons-server/issues/7308)
