### ISSUE TITLE
Restrict more add-on IDs ending in "mozilla.org"

### ISSUE THREAD

**Issue by mythmon** [mozilla/addons-server#7103]
Today, [add-on IDs ending in `@mozilla.org` require special permissions](https://github.com/mozilla/addons-server/blob/6e06b078a497d011a1c9466ee522f43728efb6f1/src/olympia/signing/views.py#L139-L144). This protection does not apply to `mozilla.com` or to `@subdomain.mozilla.org`.

Shield studies have started using `@shield.mozilla.org`, and Pioneer studies have started using `@pioneer.mozilla.org`. Normandy (the delivery platform for Shield and Pioneer) will soon enforce these add-on ID patterns. Some may also be using `.com` endings as well. These should also be restricted to users with the correct permission.

I propose that all add-ons matching `/@.*\.mozilla\.(com|org)$/` be restricted, to prevent confusion. Any existing add-ons on AMO that match this pattern should probably also be audited.

**Comment by eviljeff** [comment]
What would be the impact of someone uploading an add-on with an id ending `@shield.mozilla.org`, exactly?  #4688 was because system add-ons aren't uploaded to AMO and are signed independently so potentially an add-on could be signed that way and signed again via AMO causing a conflict.  How are Shield and Pioneer studies signed?

IMO, the significant scope increase to everything `@mozilla.com|org` seems unjustified.  IDs are historically supposed to be arbitrary strings so having an ID foo@baa.org is in no way an indication that the developer or submitter is connected to baa.org.  MDN recommends `username.addons.mozilla.org`, for example https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Generating_GUIDs

**Comment by mythmon** [comment]
Shield and Pioneer studies are usually signed using a similar mechanism to system add-ons, but with a different key. I would expect they would have the same conflicts. Maybe the restriction here should actually be that signed add-ons can't be uploaded to AMO?

The original idea here was to enforce, as best we could, that Shield studies always had an ID of `@shield.mozilla.org` (which helps telemetry analysis), and enforce that all add-ons that an ID of `@shield.mozilla.org` are actually Shield studies. (Same for Pioneer). The idea was to help build clarity both among users and the people working on studies about what was and wasn't a study. Maybe AMO enforcement isn't actually a problem here though.

**Comment by eviljeff** [comment]
Okay, so this seems the same deal as system add-ons.  System add-on submissions aren't re-signed because we detect the signature and don't strip out the existing signature.  We don't block signed xpis from being submitted to ease the development flow - often developers sign it via web-ext first.

So, we can block `@shield.mozilla.org` and  `@pioneer.mozilla.org` from non-Moco users, like we do already with system add-ons.

I got a lookup of add-ons using `@shield.mozilla.org` and there are two listed on AMO already (three if we disregard status and visibility) - they would have been re-signed using the standard cert though.  Is that a problem?  I would guess so if they have to be signed using Mozilla internal signing.  (If not... I'd be confused why we're going through the complicated process of internal signing them)

**Comment by mythmon** [comment]
I'd have to see the list of add-ons that are `@shield.mozilla.org` on AMO. It's possible they are pre-57, in which case they wouldn't have needed to be specially signed. At least for now, all Shield studies need to be legacy add-ons, because they need access to Telemetry.

**Comment by eviljeff** [comment]
https://addons.mozilla.org/en-US/firefox/addon/looking-glass/
https://addons.mozilla.org/en-US/firefox/addon/firefox-guide/
(and https://addons.mozilla.org/en-US/developers/addon/firefox-guide-study-1/ )

firefox-guide is super old so I guess you don't care about it.  Looking Glass (the infamous) version 1.0.4 was detected as a Mozilla Signed Extension - this was the same file as the Shield Study distributed, I assume - 1.0.5 isn't, though is also not a legacy add-on.

So, looks like AMO will already bypass re-signing signed Shield Study xpis if you submit them to AMO.  (You might want to confirm this by uploading a signed xpi as unlisted)

**Comment by mythmon** [comment]
@eviljeff thanks for the list of add-ons. None of those worry me. I think we should go ahead with blocking `@shield.mozilla.org` and `@pioneer.mozilla.com` for non-Moco users. I don't think any other changes are needed at this time.

**Comment by AlexandraMoga** [comment]
@eviljeff One question: was this restriction implemented eventually only for guids ending in `.org` or `.com` as well?
In your initial comments, I saw that `.com` was also taken into consideration.

**Comment by eviljeff** [comment]
only `.org` and only `@shield.mozilla.org` and `@pioneer.mozilla.org` specifically.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF57 (Win10)
![image](https://user-images.githubusercontent.com/31961530/34612280-ca0b4fe6-f231-11e7-9909-d6e2b61680a6.png)
