### ISSUE TITLE
Add-on created with no versions when a file submitted using the API fails validation

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7135]
### Describe the problem and steps to reproduce it:

When a file that fails validation gets submitted via the API, we create an `Addon` object (including a `slug` etc). We prevent that when trying to submit using the web page.

STR:
1. Create a new legacy add-on.
2. Submit it using the API.

### What happened?

Add-on gets created with no versions and files. It should appear in the devhub.

### What did you expect to happen?

No add-on should be created.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by rafspiny** [comment]
I would like to contribute on this one, if it is still valid.

**Comment by diox** [comment]
Alternative STR:
- Create a new webextension with an invalid guid in the manifest
- Submit it via the API (can use web-ext)

Expected:
- The add-on fails validation, an error is returned and the add-on is never created in AMO

Actual:
- The add-on fails validation, an error is returned but an add-on instance with no versions is created.

**Comment by diox** [comment]
As discussed over IRC, the main issue with this is that the signing API includes the add-on guid in its URLs. This is a problem because, before the guid is only assigned definitely for an add-on once the `Addon` instance has been created - before that, it's not reserved.

We have a few options:
1. Deprecate the signing API entirely, starting fresh with a new API. The signing API has always been an outlier, doing things its own way, and we've always wanted to replace it by something closer to the rest of our APIs but never found the time. The problem with that approach is that we'd have to leave the existing API with its problematic handling of add-ons for quite some time, and writing a new API is not a trivial task.
2. Don't validate the guid in the API URL for uploads. Indeed, we already have the upload identifier, we don't need a second one. This would be similar to what Github is doing when it lets you load arbitrary commits coming from forks using the upstream repo URL or vice-versa. The downside is that it's ugly and kinda unexpected, it may have consequences later.
3. Store the guid in a different table, linked to the `FileUpload`. We'd validate the `guid` early, and then copy it to the `Addon` table when it gets created. The downside is that it means moving a bunch of code and because we still need `guid` on `Addon`, there would be some duplication and we'd need to be careful about it.

In any case, that's not a trivial problem to handle. I got a branch that goes quite far into unifying devhub and API but it's blocked by this problem.

In the meantime, we may want to clear old `Addon` instances with no `Version` (including soft-deleted ones) from the database in a cron, the same way we clear old `FileUpload`s.

**Comment by wagnerand** [comment]
Why was this closed as not planned without any comment?

**Comment by kplotnik** [comment]
The issue is related to the legacy signing API. Closing as not planned.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-152
