### ISSUE TITLE
Static theme submission wizard has layout issues in Italian

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7147]
STR:

1. Log in to Developer Hub and change your locale to Italian
2. Go to submit a new add-on and select the option to Create a new theme
3. Observe the layout of the static theme submission wizard 

Expected result;
Static theme wizard has no layout issues

Actual result:
One of the optional color fields is misaligned 

Notes:
<li>reproduced on AMO-dev, with FF57 (Win10)</li>
</br>

![image](https://user-images.githubusercontent.com/31961530/34049532-6bee3d46-e1c0-11e7-90e9-6d7b1580fc67.png)

**Comment by eviljeff** [comment]
The changes requested in #7070 will shorten these labels so it shouldn't be a problem any more.

**Comment by ioanarusiczki** [comment]
@eviljeff  I am still reproducing this issue on AMO dev. Did you closed it because it remains traceable in the bug  #7070 that you mentioned above?
If that is the case, I will mark this as duplicate. Thank you!
![static theme wizard](https://user-images.githubusercontent.com/33448286/34821546-ccc041b6-f6cc-11e7-9c77-9a75718f3c35.png)

**Comment by eviljeff** [comment]
yes
