### ISSUE TITLE
During Addon upload, if you have a 'strict_max_version' too far in the future, it's hard to debug

### ISSUE THREAD

**Issue by gregglind** [mozilla/addons-server#7160]
Minor: `strict_max_version` gave unhelpful feedback.

Possible solution:

1.  "cannot find min/max" could list to the supported versions page. 

- https://github.com/mozilla/addons-server/blob/7dc2b45d01b0c3ec0cd22b312b3f17c0129414c9/src/olympia/files/utils.py#L455-L460  could link to: 
- https://addons.mozilla.org/en-US/firefox/pages/appversions/

2. Have more appversions approved :)  

Impact:

- I have no idea of people are using this feature.  If they are, I would not be surprised if it they are thinking more than 3 versions out.

**Comment by jvillalobos** [comment]
It should be rare for WebExtension add-ons. I think the check should only make sure the version is valid and no longer look for it on a list. I was planning on including that as part of a larger work on developer tools (which may begin in Q2), but maybe this fix is small enough that it doesn't need to wait that long.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I tested this issue with a langpack and kept changing the strict_min_version and strict_max_version. - FF64 (Win10) 
I uploaded it on stage to see the problem and then on dev to see the fix, here are my results:

- On both AMO dev and AMO stage strict_min_version is minimum 42 or else validation fails with a red error message.

![minimum 42](https://user-images.githubusercontent.com/33448286/50518316-c616f200-0abd-11e9-97b5-4c2724948dee.png)

- On AMO stage if the strict_max_version is >  69* the upload fails 

![upload fails](https://user-images.githubusercontent.com/33448286/50518478-7be24080-0abe-11e9-9723-e2b166c93ea2.png)

- The issue is no longer reproducible on AMO dev, I tested with "strict_max_version": "69.*" "strict_max_version": "70.*" "strict_max_version": "80.*" "strict_max_version": "90.*"  "strict_max_version": "100.*"

Result:

![max version 90 allowed](https://user-images.githubusercontent.com/33448286/50518565-f612c500-0abe-11e9-9d44-7ec50f4e4bf1.png)

I also tried to check with  "strict_max_version": "1000.*" and  "strict_max_version": "10000.*" to see if strict_max_version has a limit and it is displayed when the upload fails.  Perhaps, the red message should mention something else. Let me know what you think.

![max version is too big](https://user-images.githubusercontent.com/33448286/50518874-c2389f00-0ac0-11e9-895e-9dfac12ae1c0.png)

**Comment by ioanarusiczki** [comment]
I filed https://github.com/mozilla/addons-server/issues/10299 for the strict_max_version issue that I've noticed so I think this can be closed because the upload is successful when a realistic strict_max_version is used.
