### ISSUE TITLE
It should not be possible to submit a new version with version number lower than current public version

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#7161]
The autoapproval script currently auto-approves anything. Even a submission/update that have a lower version number than the previous one.

Example:
1.0.15
1.0.16
1.2.8
1.0.17
1.0.18

**Comment by wagnerand** [comment]
So, what would happen with those submissions if they're not approved?

**Comment by spoji** [comment]
CWS deny the devs from uploading a new build with a lower or equal version number. Is this something that could be implemented on AMO that would solve this issue?

**Comment by wagnerand** [comment]
Yes, that is what I am thinking about. If I remember correctly, we talked about that in the past and decided against it, but I can't remember why. Also, this would apply to listed versions only.

**Comment by spoji** [comment]
https://github.com/mozilla/addons-server/issues/4635 shows a similar ongoing issue.

**Comment by jvillalobos** [comment]
We support uploading older versions for compatibility reasons. That way extensions can have more than one compatibility branch. Granted, it's always been problematic because the listing page shows the latest version regardless of version number.

This isn't very useful now that we're only supporting WebExtension add-ons. From a recent discussion I also recall that we're not supporting WebExtension add-ons to have their legacy branch updated. I think it's okay to introduce this restriction, as long as:
1) It's done during submission rather than auto-approval. So, we just show an error and don't allow the submission to continue.
2) Admins can still use the override option to push it through.

**Comment by wagnerand** [comment]
Sounds good to me.

**Comment by AlexandraMoga** [comment]
Having a lower version number as the current listed version can also break check for updates in addons manager.
See example - https://addons.allizom.org/en-US/firefox/addon/teamweek-button/versions/
I'f I've installed version 1.11.18, I won't receive an update to the latest 1.11.13 version

**Comment by wagnerand** [comment]
This issue is still valid.

**Comment by diox** [comment]
Fixed in https://github.com/mozilla/addons-server/issues/19788

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-153
