### ISSUE TITLE
Cannot list collection add-ons after adding it to a collection (because of caching)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7173]
### Describe the problem and steps to reproduce it:

STR

Add an add-on to a collection: https://addons-server.readthedocs.io/en/latest/topics/api/collections.html#collection-add-ons-create

List add-ons in the collection: https://addons-server.readthedocs.io/en/latest/topics/api/collections.html#collection-add-ons-list

See https://github.com/mozilla/addons-frontend/issues/2768 for the user flow.

### What happened?

The newly added add-on does not show up immediately. It shows up after 30-60 seconds.

### What did you expect to happen?

The add-on should show up immediately in the listing so the UI can easily indicate that the add-on has been added to the collection.

### Anything else we should know?

As of https://github.com/mozilla/addons-server/issues/7167 we may be using a different API endpoint to list the add-on.

If we need to work around the caching issue we can but that kind of code tends to be complex and buggy.

**Comment by diox** [comment]
So, it turns out the issue is (again) caching `COUNT(*)`. cache-machine caches calls to count without ever invalidating them, because it's not tied to model instances so it never knows when to do the invalidation. Instead, they are cached for 5 minutes.

This caused issues in the ratings endpoint and the solution was to avoid `COUNT(*)` entirely when user+addon+version parameters were passed, since there could only be one or zero results.  In this case, even if we implement #7167 we won't be able to use that workaround, because we might need pagination (if the user adds the same add-on to multiple collections).

**Comment by diox** [comment]
I implemented #7167 so there is a workaround. But it turns out that this is also fixed because I had to [remove cache-machine from collections](https://github.com/mozilla/addons-server/commit/a89e66f79579550b23641b9b3c26c798c5945985) as well :)

**Comment by AlexandraMoga** [comment]
This was also reported as a frontend issue in [#3938](https://github.com/mozilla/addons-frontend/issues/3938)

Verified as fixed on all AMO-servers with FF57, Win10

![collections](https://user-images.githubusercontent.com/31961530/34866827-90130ea0-f786-11e7-8fe4-c421cb5caad2.gif)
