### ISSUE TITLE
AMO RSS feeds do not have any entry body formatting

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#7182]
https://addons.mozilla.org/extensions/format%3Arss?sort=updated
These feeds are very useful. Items in feeds like these however, do not have any text formatting included, which made the descriptions look spammy until i found out the entry bodies do not include CRLF/LF/<br>'s at all.

**Comment by eviljeff** [comment]
@jvillalobos where do RSS feeds fit on the long term roadmap?  Is this fix-worthy?

**Comment by jvillalobos** [comment]
We don't have plans to reimplement the RSS feeds. We have the API as a sort of replacement.

**Comment by alainsr** [comment]
@jvillalobos end users like me follow me extensions and updates through RSS (along with many other automated similar feeds) using Feedly or similar online services or local software. I don't have to (know how to) code to follow an RSS feed. But I do if my only option is an API. Why can't non-tech-savvy users be allowed the same information in the same friendly way as we used to receive? Mozilla is making unfriendly decisions like this a bit too often and this is really frustrating, saddening and disappointing for users like me.

**Comment by willdurand** [comment]
@alainsr there is an extension for that: https://addons.mozilla.org/en-US/firefox/addon/latest-on-amo/

**Comment by atomGit** [comment]
an extension is not an optimal solution - many people use RSS/XML feeds to be able to keep track of web content updates and eliminating the AMO feed is, IMO, a poor decision

**Comment by jvillalobos** [comment]
I wouldn't call RSS feeds a tool for non-tech-savvy users. Tech-savvy users would just go to about:addons, the AMO front page, or directly to a listing page via a search engine. 

While RSS feeds can be handy, they aren't as popular as they were when they were implemented originally for the site, and it's one of many features we've decided to drop in order to reduce complexity and  streamline development. I'm sorry you're losing this functionality, but there are alternatives to them, even if they aren't optimal.
