### ISSUE TITLE
Create a spam filter on movie keywords

### ISSUE THREAD

**Issue by nt1m** [mozilla/addons-server#7183]
See this screenshot: 
<img width="755" alt="screen shot 2017-12-23 at 9 54 50 am" src="https://user-images.githubusercontent.com/1795135/34320894-7800ea12-e7c8-11e7-9eef-736c97fbf3ae.png">

The solution would either be: catching this spam through the validator (using the keywords in the title), or having a 5-minute manual content review for every submission before it appears live on AMO.

**Comment by jvillalobos** [comment]
We already have a keyword filter, but its function is somewhat limited. The plans to fight spam via admin tools (including a more effective filter) are specified in https://github.com/mozilla/addons-server/issues/7176. Dependencies for specific tasks will be filed soon.

However, none of these tools will completely block spam add-ons from showing up on the site, at least for a short time, since that will lead to submission slowdowns like we had in the pre-review times.
