### ISSUE TITLE
Discuss advanced searching

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#7215]
Following on from https://github.com/mozilla/addons/issues/567 it looks like our current search will return matches for any terms supplied since afaict ES uses `OR` by default.

E.g. a search term like "foo bar baz" will return matches for foo `OR` bar `OR` baz.

 * Could we surface some syntax in the API to allow for exact matches that maps to the relevant `AND` in ES? (_**Update** as @diox points out the AND search should probably be the default_)
* In a similar way it would be nice to also surface the ability to quote for exact phrase matches. 
* Should we consider allowing searching specific fields? E.g. could you just search by add-on/theme author for example or title etc.
* Should we consider any other ES query syntax to be mapped to the API e.g `NOT`.

This issue is to discuss what would make sense. We don't want to make it too complicated but improving relevancy and passing some of the power to the users is going to be really helpful for surfacing the right content to our users.

**Comment by diox** [comment]
IMHO any special syntax that the user needs to know - things like quotes, special keywords etc is a bad idea. Search should "just work" (tm). IMHO multiple words queries should give results that use all of the words and not just any of them, the fact that it's not is a bug.

**Comment by muffinresearch** [comment]
> IMHO any special syntax that the user needs to know - things like quotes, special keywords etc is bad UX. Search should "just work" (tm). I also think multiple words queries should give results that use all of the words and not just any of them, the fact that it's not is a bug.

I definitely like the idea of having the most useful results as a default 👍

Thinking about search engine searches, I sometimes use quoting for exact phrase matching, but not much else. FWIW Looks like DuckDuckGo uses AND by default https://duckduckgo.com/?q=duckduckgo+syntax+cheat+sheet&ia=cheatsheet&iax=1

**Comment by EnTeQuAk** [comment]
I definitely agree that the default should be `AND`, funny thing is that it never was but hey, who knows what magic was at play earlier.

That could actually be a low-hanging-fruit.

Surfacing any search specific syntax is a potentially good idea but we'd have to figure something out, spec it and then implement it. ElasticSearch does have some defaults inherited from lucene but we're not using that interface but rather throw the search string manually against all sorts of analyzed, unanalyzed, exact and other searches.

I am personally a fan of how the github search works and how it exposes specific searches in specific fields which we don't currently. We simply search for the term in addon-name, tags, and translations. I'm guessing especially translations can give weird results here.

We could make use of a default `AND` instead of `OR` and give that a shot, if there are no complains I can take that up tomorrow.

**Comment by muffinresearch** [comment]
Closing on the basis that I think we've filed bugs and actioned this.
