### ISSUE TITLE
Content Review Canned Responses

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7218]
This is a request to add canned responses for content review actions. 

Text for the canned responses can be found here: https://docs.google.com/document/d/1AQMWwQtPgvEoxj7s_Y-K4zijqL93tlYjxx74hjrhOKQ/edit#

**Comment by jvillalobos** [comment]
I think this involves creating a new type of canned response. We have an `Add-on` type that we use for code reviews, but we should create a new `Content` type, since there probably will be multiple different canned responses for content reviews just as with regular add-on reviews.

**Comment by wagnerand** [comment]
This would be mostly for hiding technical canned responses on the content-review page. Technical reviewer would still need the content canned responses, since content review is part of the add-on review.

For now, I think we can just add them to the `Add-on` type.
Some time, we can also think about grouping them by topic (content, security, privacy...) instead of action (approve, reject, reply)

**Comment by jvillalobos** [comment]
There will be some duplication, yes, but I think that's preferable over having a bunch of canned responses you need to tell reviewers they can't use.

I like the idea of grouping them by topic rather than action.

**Comment by wagnerand** [comment]
For now, I added the canned responses from https://docs.google.com/document/d/1AQMWwQtPgvEoxj7s_Y-K4zijqL93tlYjxx74hjrhOKQ/edit to the list.

<img width="353" alt="screen shot 2018-01-09 at 21 43 26" src="https://user-images.githubusercontent.com/873258/34739844-40460d34-f586-11e7-94bb-cb0f5c48cd7e.png">
