### ISSUE TITLE
Replacement add-on admin tool

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7253]
Part of #7176. [PRD section](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.3wbd4ya878ev).

Currently lives in `/admin/staff-models/addons/replacementaddon/`. The following things need to change:
- [ ] Give users with `Addons:Edit` access to the list (read-only).
- [ ] Give full edit/delete access to users with the `Content:Curate` permission.

**Comment by diox** [comment]
I gave this a shot but #7848 is a blocker - the way permissions are handled now it's very hard to have any granularity in the admin tools.

**Comment by AlexandraMoga** [comment]
After testing this functionality, I have the following results:

**Working:**
1. Users with `Addons:Edit` have view access to Replacement add-ons tool (tested with `Staff` group)
2. Users with `Admin:Curation` have edit/delete access to Replacement add-ons tool (tested with `Content Curators` group)
3. Users with `Addons:Edit` or `Admin:Curation` can view only Replacement add-ons tool in the django admin page.

**Needs info:**
@diox Replacement add-ons list is updated slowly when new add-ons are added (wait time can last several minutes). The `Paths` are also not rendered correctly - instead of the URL entered, the path will display the guid again.  Not sure if this is happening only on -dev, On stage I could not reproduce the path issue on stage.. 

![image](https://user-images.githubusercontent.com/31961530/38233407-299271fc-3723-11e8-8b5d-5445add657bb.png)

**Comment by diox** [comment]
@AlexandraMoga I only touched the permissions, so I don't think this is because of my changes. Can you open a new issue for this?

**Comment by AlexandraMoga** [comment]
I've filed #7963 to cover the observed issue.

I'm going to mark this issue as verified fixed based on the  test results mentioned above (Working section)
