### ISSUE TITLE
User admin tool

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7268]
Part of #7176 

- [x] Users with `Users:Edit` should see all user data in the admin page:
  * User ID.
  * Email address.
  * Link to profile page.
  * Metadata: username, description, image, location.
  * Last time of activity.
  * Ratings posted.
  * Collections, public or private.
  * Add-ons created, regardless of status and type.
  * Activity history.
  * Known IP addresses (last login, and used for ratings).
  * Abuse reports reported by this user.
  * Abuse reports reported for this user.
- [x] Users with `Addons:Edit` should be able to click on any add-on on the list and go to its admin page (`/admin/addon/manage/SLUG/`).
- [x] Users with `Collections:Edit` should be able to click on any collections listed in a user admin page to go to their view page.
- [x] Users with `Users:Edit` should be able to ban a user account, which **disables** all of its content (add-ons, ratings, collections) and blocks the user from creating any new content (this can be done by logging them off and blocking future log in attempts).
- [x] Users with [`Admin:Advanced`](https://github.com/mozilla/addons-server/issues/7249) should be able to delete a user account, deleting all of its content (add-ons, ratings, collections).
- [x] Users with `Users:Edit` should be able to search for AMO users by email address, ID, username.
- [x] Users with `Ratings:Moderate` should be able to ban multiple user accounts in bulk, using their user ID, username, or email address.
- [x] Users with `Users:Edit` should be able to delete a user picture.

See also https://github.com/mozilla/addons-frontend/issues/5134 for the frontend work.

**Comment by wagnerand** [comment]
Is there a permission or way that lets admins access the devhub pages for any add-on? That proved to be very useful in the past.

**Comment by jvillalobos** [comment]
It's `Addons:Edit`, I believe, which isn't changing for this phase. Future phases should cover add-on admin.

**Comment by diox** [comment]
I've split the base admin tool in #8191 and will start with that first, then implement the actions on top of it once it's built:

**Comment by diox** [comment]
> Users with `Users:Edit` should be able to search for AMO users by email address, ID, username, or description.

@jvillalobos what kind of matching do we want for this search? We can do exact (case-insensitive), prefix (the value needs to start with the string searched to match) or full text. Currently the functionality exists already (except for description, what is description for a user profile?) but it's a prefix search, i.e. the email/username needs to start with the string used for search. Is that ok or should it be changed? Support full text search would require a lot more work, because of the perf implications.

**Comment by jvillalobos** [comment]
I think I'm referring to the bio when I write description. Doing prefix search should work for now (and including the bio in this case probably won't be useful). We can see later if we need something more powerful.

**Comment by diox** [comment]
Couple more questions for you @jvillalobos :+1: 
> Users with `Reviews:Edit` should be able to ban a user account, which disables all of its content (add-ons, ratings, collections) and blocks the user from creating any new content (this can be done by logging them off and blocking future log in attempts). 
> Users with `Reviews:Edit` should be able to ban multiple user accounts in bulk, using their user ID, username, or email address.

I edited your description to replace `Reviews:Edit` with `Ratings:Moderate`, because `Reviews:Edit` doesn't exist, but is that right? Do we want a new permission - in which case it'd be `Ratings:Edit` - or do we want to re-use the permission used to moderate ratings atm?

Also : it's difficult for us to allow users with that permission to access just this action and nothing else. Can we consider that people that need this action will also have `Users:Edit` ? `Users:Edit` would allow them to see the user admin pages, and then they'd need the other permission above to access the ban action.

> Users with Admin:Advanced should be able to delete a user account, deleting all of its content (add-ons, ratings, collections).

- What about the anonymize action that is available through the legacy frontend right now? Do we want that action to be available in the django admin as well? To who?

- Are we sure we want that deletion to delete add-ons? What about add-ons with multiple authors ?

**Comment by jvillalobos** [comment]
> Can we consider that people that need this action will also have `Users:Edit`? 

I think the `Reviews` permission was a copy-paste error. Doesn't seem to make sense that review moderators would be the ones banning accounts. I changed it to `Users:Edit`, like you pointed out.

> What about the anonymize action that is available through the legacy frontend right now?

I don't think we need anonymizing anymore. Banning and deleting should cover all use cases we need.

> Are we sure we want that deletion to delete add-ons? What about add-ons with multiple authors ?

It should delete add-ons if the user being deleted is the only one associated with them.

**Comment by vcarciu** [comment]
I verified this on AMO-dev Admin pages using the permissions from description and we can mark this as verified, but I still have one questions in order to see if we need follow up bug for it: 

1.With Collections:Edit permission, we can see regular collections for any user, but "My favorite addons" collections will return "Oops" page when trying to view it on site. Should I file an issue for this?

**Comment by diox** [comment]
Yes, please file a separate issue for that oops (and any other you may find :)
