### ISSUE TITLE
Add a deadline for requests for information

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7283]
Part of #7172 

Reviewers can send information requests to developers, but the deadline isn't clear to either, so admins end up doing a lot of work clearing them up. Implementing a concrete deadline makes things clearer for both developers and reviewers:

* [x] Replace the "Is more info requested?" checkbox with a "Require developer to respond in 7 days" checkbox. Users with `Reviews:Admin` should be able to change the number of days.
* [x] When a developer uploads a new version for an add-on that has a pending info request, show it in the description step, with a checkbox indicating "This request for information has been resolved". The checkbox will clear the request and log a developer response indicating it.
* [x] Modify the request for information email to include the deadline.
* [x] Send another email to the developer a day before the deadline expires, explaining the add-on may be disabled if they don't respond.
* [x] Add button to "Clear information request" to the More Actions section (#7282), if the user has `Reviews:Admin` and the add-on has a pending info request. This should log an event in the review history.

**Comment by diox** [comment]
Some implementation notes:
- The current flag is stored per version, but that's not very useful (it's never displayed per version). Especially since clearing the flag is going to be an explicit action from the developer at upload.
- The best place to put the new flag is probably in `AddonReviewerFlags` model.
- The new flag should probably just be a `DateTimeField` field, indicating the date & time of the request

@jvillalobos do we want to automatically remove obsolete (> 7 days) info request flags?

**Comment by wagnerand** [comment]
As a side note: Another way for the developer to clear the flag is by replying to a reviewer message, either using email or the interface in the devhub.

We won't remove expired flags, admins will follows up with them. So, there needs to be some view for admins to look at the expired ones. A simple filter in the queue view would work just fine, for example.

**Comment by jvillalobos** [comment]
> @jvillalobos do we want to automatically remove obsolete (> 7 days) info request flags?

Sorry, forgot to include anything about expired flags. They should behave like a regular flag in that it can be cleared by an action by the developer (replying, submitting and clicking on the checkbox), and admins can also clear them in the "More Actions" section. We will need an "expired need info" icon to show in the review queue, like Andreas mentioned.

**Comment by diox** [comment]
> When a developer uploads a new version for an add-on that has a pending info request, show it in the description step, with a checkbox indicating "This request for information has been resolved". The checkbox will clear the request and log a developer response indicating it.

@jvillalobos Should the checkbox be checked by default?

**Comment by diox** [comment]
>  When a developer uploads a new version for an add-on that has a pending info request, show it in the description step, with a checkbox indicating "This request for information has been resolved". The checkbox will clear the request and log a developer response indicating it.

@jvillalobos is this the only way for a developer to clear the info request? A reply (by e-mail or through devhub) does not clear it?

**Comment by jvillalobos** [comment]
> Should the checkbox be checked by default?

No.

**Comment by diox** [comment]
@jvillalobos do we need a migration for existing information requests ? if so, with what deadline ?

**Comment by jvillalobos** [comment]
I'm thinking there are lots of old needinfo's that we never cleared, so doing a migration could have unintended consequences. What would be the outcome of not migrating them?

**Comment by diox** [comment]
Not migrating them would mean they'd no longer be flagged as needing info in the queues. Reviewers would still view the request for info in the activity log for the relevant version, but it would look as if the request had been cleared by the developer at some point.

**Comment by diox** [comment]
QA:
> Send another email to the developer a day before the deadline expires, explaining the add-on may be disabled if they don't respond.

This isn't automated yet, so please test the rest first, and when everything is ok I'll enable this.

**Comment by jvillalobos** [comment]
> Not migrating them would mean they'd no longer be flagged as needing info in the queues.

Then I think we should migrate the most recent ones, which should still be valid. Maybe all the ones that were created in the previous 3 weeks. We could also coordinate with reviewers to have needinfo's mostly cleared by the time the migration is run. @wagnerand, thoughts?

**Comment by wagnerand** [comment]
Generally, I'd rather migrate all of them than missing an important one. 

@diox what unintended consequences do you have in mind?

**Comment by diox** [comment]
@jvillalobos said that, not me :)

One thing to keep in mind is that fetching the original date of the request in SQL is difficult.  So giving every add-on that had an info request a deadline of {push date + 7 days} works, but anything more adds more work, as it probably means writing a one-off command.

**Comment by wagnerand** [comment]
Oops, you're right. So, @jvillalobos anything specific you had in mind?

> One thing to keep in mind is that fetching the original date of the request in SQL is difficult.

Yep, I was going to write that but then deleted it. You'd have to deal with the activity log :(

I am fine with giving every add-on we migrate a deadline of 7 days, if that makes your life easier.

**Comment by jvillalobos** [comment]
My concern would be add-ons that have open info requests that are no longer valid - and may be months or years old - suddenly getting notified about expired info requests. If that's not the case or the admins can spend some time to clear the old ones, it's no problem to migrate them all.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, FF58, Win10x64
**1. tested and working:**
  -  "Require developer to respond" checkbox - shows a fixed 7 days deadline for non admin users; deadline can be modified by users in Reviewers:Admin group
 - "Clear information request" button added in "More Actions", working for users in Reviewers:Admin group; when used, an event is triggered in the Add-on review log
  - Developers can clear the request info flag by checking the box available at new version submission, by replying to reviewer emails or leaving a reply in DevHub

**2. need more info**
 - The new template for request info, which also includes the deadline info [a] was not sent when I used a user with 'Reviews:Admin' and 'Addons:Review' permission. Will this be available once [#7441](https://github.com/mozilla/addons-server/issues/7441) lands?
 - when developers check the "This request for information has been resolved'' box at new version submission, there is no entry displayed in Add-on review summary to mark this developer action [b]

[a] - email sent
![image](https://user-images.githubusercontent.com/31961530/36422559-3d5ee264-1645-11e8-92ae-a3630b709d35.png)
<br>
[b] - no developer action in addon review history 

![image](https://user-images.githubusercontent.com/31961530/36422592-5bf3965c-1645-11e8-9fdc-0fdd945a9272.png)


**3. unable to test yet**
- "Add-ons with expired information requests" [c] which has been added as a new queue in Reviewer's Dashboard. There are currently no add-ons with expired deadline in this queue. Do you have the means to populate this list with some examples? Otherwise, I will have to wait until tomorrow when some of my request will expire.

[c] - new expired deadline queue
![image](https://user-images.githubusercontent.com/31961530/36422629-865ced4e-1645-11e8-91e2-6fcd1757896b.png)

@diox, could you please have a look at point 2 and 3?

**Comment by wagnerand** [comment]
> My concern would be add-ons that have open info requests that are no longer valid - and may be months or years old - suddenly getting notified about expired info requests. If that's not the case or the admins can spend some time to clear the old ones, it's no problem to migrate them all.

Yes, some are years old. Admins can go through them and clear the invalid ones, but going through 5000 add-ons will take a while.

As a workaround, could we migrate every item with a deadline that already expired? Would that send out any emails? This would only negatively impact the add-ons that had their need-info added in the past week. That's 40 add-ons and we can easily go through them.

**Comment by diox** [comment]
@wagnerand actually I just realized... I have a flag that I set when we send the "one day left" notification, to avoid sending that twice. So we could set whatever deadline we want *and* set that flag to True to avoid sending any notification.

**Comment by diox** [comment]
@AlexandraMoga : 

2) [a] It's possible yeah. Because of #7441 if your user does not have `Addons:Review` for now it will not use the right email template. So please test with that permission for the moment. I'm going to try to land a fix for #7441 in the tag.

2) [b] I'll look into that.

**Comment by wagnerand** [comment]
> @wagnerand actually I just realized... I have a flag that I set when we send the "one day left" notification, to avoid sending that twice. So we could set whatever deadline we want and set that flag to True to avoid sending any notification.

That works for me too. As long as we don't send any emails for the ones we migrate (but all other ones that get flagged after the migration).

**Comment by diox** [comment]
@AlexandraMoga FWIW I've manually trigged the last warning notification email on dev, and a few were sent and should be available in the fake mail admin for you to check.

**Comment by AlexandraMoga** [comment]
I've checked again today to see if the deadline template is sent and this time it worked with the same user I used yesterday. Below is an example:
- deadline notification
![image](https://user-images.githubusercontent.com/31961530/36478130-5606415a-170c-11e8-9a31-766d8a7f35dd.png)

I was also able to look into the Add-ons with expired information request queue and observed that a new custom flag is present to point out the add-ons that belong to this queue:

- Expired deadline flag and the new queue
![image](https://user-images.githubusercontent.com/31961530/36478237-b93d22ca-170c-11e8-877f-b154a465db2f.png)

@diox 
> when developers check the "This request for information has been resolved'' box at new version submission, there is no entry displayed in Add-on review summary to mark this developer action [b]

I could open a new issue for this situation so you can follow up on that.

**Comment by diox** [comment]
@AlexandraMoga please do that, linking the add-on you've been testing on.

**Comment by AlexandraMoga** [comment]
This can be marked as verified fixed based on the above test results.
