### ISSUE TITLE
Arabic (rtl) add-on names cause a weird title layout on review page

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7332]
Here's a screenshot of what a content reviewer sees when reviewing an extension with an Arabic title: 

![screen shot 2018-01-17 at 1 58 05 pm](https://user-images.githubusercontent.com/23342476/35070546-7ceb7780-fb92-11e7-9fb9-2f08d6e32de3.png)

I was a little confused by the anglicized "1" for the add-on name and was wondering if this was intentional or if there might be a better way to display Arabic extension titles.

**Comment by eviljeff** [comment]
link?

**Comment by caitmuenster** [comment]
Arg, I totally failed to grab a link and I'm having a hard time tracking it down. 

[This](https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/%D8%A8%DB%8C%D9%85%D9%87-%D8%A2%D8%B3%DB%8C%D8%A7) is another extension with an Arabic title where the name is not anglicized at all. I had an easier time understanding what I was looking at in this example. 

![screen shot 2018-01-18 at 9 11 10 am](https://user-images.githubusercontent.com/23342476/35111209-95c33ed0-fc2f-11e7-85b0-66c3ffb5df8f.png)

If this is a bug, it is probably low priority.

**Comment by EnTeQuAk** [comment]
Sorry, it's still unclear to me what's actually expected here. If an add-on only has an arabic title, we show that, but that's not the problem we're talking about here right? :thinking:

**Comment by eviljeff** [comment]
The title is supposed to be  "Content Review `addon.name` `addon.version` (Listed)" but with Arabic (and other RTL locales, I guess) it ends up being rendered as "Content Review `addon.version` `addon.name` (Listed)" which reads strangely.  In the template "Content Review `addon.name`" and `addon.version` are two separate spans but due to the joy of l10n and mixing rtl and ltr on the same line they get switched around.
