### ISSUE TITLE
IP address logging is unreliable

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7333]
This is an old problem, but I don't see it filed on this repo. There are a couple of problems in the way we log IP addresses for login attempts and user reviews:
- [ ] There's no IPv6 support ([originally filed here](https://bugzilla.mozilla.org/show_bug.cgi?id=975888)).
- [ ] A significant portion of user accounts have no `last_login_ip` set (only ~16% of accounts created since Jan 2017 have it set). IIRC, this was related to Firefox Accounts, but I don't remember the details.

Admins use IP addresses as one tool to identify spammers, so we need this to work reliably.

**Comment by wagnerand** [comment]
Another path that misses IP address logging is submissions through the API, which is what a lot of harmful add-ons use for signing.

**Comment by diox** [comment]
I suspect the core problem is that we don't call `login()` when you register or when you use the signing API (in the latter case, it's because we're not actually logging you in). Need to double-check if that's the case, investigate the IPV6 part, and fix all of those points. 

We may need to re-implement django's `login()`, depending on what we're interested in having, because we don't want to create a session etc when using the JWT-tokens based API.

**Comment by diox** [comment]
> Also, we should be passing the ip when going through our JsonFormatter, as well as the user id, so that's also something we need to investigate. IPs should be available in kibana afterwards.

It's present in raw logs under `remoteAddressChain`, so it's gotta be an issue with how kibana / the logging pipeline is set up on the ops side. Interestingly though, the `uid` is set to `<anon>`, maybe because we don't set the core user in that thread when registering - something to fix as well.

**Comment by AlexandraMoga** [comment]
@diox @EnTeQuAk 

I can try to verify this by looking in `/admin/models/users/userprofile/<12345>/` where the 'Last login' and 'Last login ip' fields are present, but I'm not sure how reliable this source is for testing this implementation.
Is there a better way to check this?

**Comment by EnTeQuAk** [comment]
> I can try to verify this by looking in /admin/models/users/userprofile/<12345>/ where the 'Last login' and 'Last login ip' fields are present, but I'm not sure how reliable this source is for testing this implementation.

That's perfect and ideal to test this imho.

**Comment by ioanarusiczki** [comment]
Verified fixed with FF61(Win10), FF63 (Win10) on AMO dev - I tested the login for some accounts and then I made some tests for new accounts (the register).  I looked into the /admin/models/users/userprofile/<12345>/ and checked that the information is accurate for Last login: and Last login ip: fields

**Comment by AlexandraMoga** [comment]
I've also submitted an add-on though the API and the last login field was populated with the date and time of the submission. 

Based on these results, I think we can mark the issue as verified fixed
