### ISSUE TITLE
Remove multi-process status (AddonFeatureCompatibility code)

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#7340]
With Firefox 57 everything is multi-process now, so we can probably remove this visual indicator in devhub:

![screenshot 2018-01-18 11 11 10](https://user-images.githubusercontent.com/74699/35116468-718a6550-fc40-11e7-9c10-35303fcc31be.png)

Or perhaps we want to wait for Thunderbird and Seamonkey to move off.

Also there's an API that could maybe go?

http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#add-on-feature-compatibility

**Comment by diox** [comment]
Does anyone know if it's safe to remove the API ?

**Comment by diox** [comment]
cc @shell15 to find someone to answer that question ^ It'd be great if we could remove the API completely.

**Comment by shell1** [comment]
I think we need to leave this until at least ESR 52 EOL (late August).   I will verify in a stand-up meeting next week if we need to keep beyond that (I think not). @shell1 

In Firefox 50-56 and ESR 52 (https://bugzil.la/1329752), there is a "system add-on" that controls if e10s is enabled (changes preference setting) based on users having only webextensions or add-ons marked MPC=true (in the install.rdf).   This isn't full e10s enabled, but many of the early improvements (excluding actually running on more than one process).

We don't expect any new developers to be setting MPC=true at this point, but existing ESR 52 users could have e10s disabled if we remove this flag.  There were a few large add-ons marked MPC=true that are not yet webextensions (ex: downthemall! and TabMixPlus).  And we wouldn't know about any enterprise specific add-ons - so not worth the risk since until ESR 52 EOL.

The tag that will be relevant on older versions of Firefox (at least through the end of the 2018) is "compatible with 57+", that is based off an API that checks AMO Extension type (which needs to stay).

**Comment by shell1** [comment]
@diox  Confirmed that this code can go away when ESR 52 EOL (Aug 28th) - needs to stay until then.   

Shell filing bug with Will to remove the developer documentation on MPC now.  We don't want to expand the use, since the probe was meant during Fx50-56 transition releases.  We're just supporting it until end of life to avoid any weird behavior changes (of turning off partial e10s for some users).

**Comment by diox** [comment]
Ok thanks. Lowering priority for now.

**Comment by EnTeQuAk** [comment]
Upping the priority as this is safe to go now I think.

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @EnTeQuAk

**Comment by son-vyas** [comment]
Hi everyone, I am completely new to the mozilla community. Can I give it a try?

**Comment by Hyperion101010** [comment]
hi there i am undergrad student of computer science course 
i am keen to help and learn collabrative development ,i would like to work on this 
@EnTeQuAk but i am in a doubt 
where can i find code for this ,(any file location might be helpful)
also as i have understood for now it requires removing that
1) add-on 
2)the es10 api support if found

**Comment by Hyperion101010** [comment]
i have the most updated build so i'll be able to find the required file

**Comment by caitmuenster** [comment]
Hey @son-vyas and @Hyperion101010 -- are either of you currently working on this bug?

**Comment by miphilomath** [comment]
Is this Issue still open to work? Or, Should I wait a little longer for other contributors to push their commits?

**Comment by caitmuenster** [comment]
Hey @miphilomath! Since we haven't heard from the other folks, please feel welcome to pick this up and start working on it!

**Comment by caitmuenster** [comment]
Hi @miphilomath, since we haven't heard from you in awhile, I'm going to open this issue up for other contributors to work on.

**Comment by ajupazhamayil** [comment]
Hi, I am new to the Open source world. 
I hope still this issue is open and I would like to take it. Please give a green signal!

Instead of waiting I am moving forward with setting up the docker and other required things to get things started.

I have gone through commits 20935f6, 23dd285 and 6f40a30. As far as I understood, I need to start by removing AddonFeatureCompatibility from models.py and resolve the problems that arise because of this removal. Please correct me if I am wrong.

**Comment by ajupazhamayil** [comment]
I was following steps from https://addons-server.readthedocs.io/en/latest/topics/install/docker.html and I am getting an error like 'ImportError: No module named local_settings' frequently and getting a final error like this.
![firefx](https://user-images.githubusercontent.com/14087896/49732671-6343ef00-fca5-11e8-9c8b-40bfb5d1d5e0.png)

![error2](https://user-images.githubusercontent.com/14087896/49732740-925a6080-fca5-11e8-81e9-5bb9ecf0d860.png)

Please help me to get out of this.

**Comment by diox** [comment]
The `ImportError: no module named local_settings` exception is caught, you can safely ignore it.

The second one indicates an installation problem. [Our documentation has a possible workaround for this particular problem](https://addons-server.readthedocs.io/en/latest/topics/install/docker.html#connectionerror-during-initialize-docker-elasticsearch-container-fails-to-start), give it a try.

**Comment by ajupazhamayil** [comment]
Thank you @diox, 'sudo sysctl -w vm.max_map_count=262144' command helped me!

**Comment by ajupazhamayil** [comment]
Hi @diox, I have removed all the code related to multi-process status except message ids in django.po files (In locale folder).
I have initialized the docker with my new code and it is working fine for me locally.
Please give me a direction to complete an extensive testing such that I can move forward with my First PR?

**Comment by ajupazhamayil** [comment]
Hi @diox @caitmuenster,
As discussed in #amo channel with @cgrebs, I am submitting a PR marked with 'Work in progress'. Please review it.
