### ISSUE TITLE
Name and date of last update are changed when installing webextensions from addons manager search results:

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#7395]
Steps to reproduce:
1.Go to about:config and set everything for Staging server (xpinstall.signatures.dev-root to true, extensions.getAddons.search.url to https://services.addons.allizom.org/%LOCALE%/firefox/api/%API_VERSION%/search/%TERMS%/all/%MAX_RESULTS%/%OS%/%VERSION%/%COMPATIBILITY_MODE%?src=firefox)
2.Go to about:addons and from Extensions tab, search for "webext"
3.From search results list , try to install any add-on

Actual results:
Name of the webextension and date of last update are not changed

Actual results:
Name of the webextension and date of last update are changed and this is very confusing (name is probably changed to name from manifest and last update date is changed with installation date , which is not correct)

NOTES:
Reproducible also in prod

Please se video for this bug : 
![addonsmanager](https://user-images.githubusercontent.com/1583842/35396375-57bc0d76-01f5-11e8-967b-24cca09ca8be.gif)

**Comment by jvillalobos** [comment]
"Last updated" is probably switching from "Last updated on AMO" to "Last updated in this profile". The name change can also be due to inconsistencies between what's in the manifest and what's on AMO. There's a project to eliminate those inconsistencies, but it won't happen this quarter. We'll probably tackle it in Q2. Closing this for now.
