### ISSUE TITLE
"Credentials were not provided" message is displayed and collection is never loaded after logging out 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#7396]
Steps to reproduce:
1.Be sure that you are logged in 
2.Go to https://addons.allizom.org/en-US/firefox/collections/mozilla/bookmark-managers/
3.Log out and then refresh the page

Expected results:
No credentials are required and collection is displayed

Actual results:
"Credentials were not provided" message is displayed and collection is never loaded

NOTES:
Tested on Windows10x64, Firefox Release
Possible related to #7388 

Please see video for this bug
![credentialsnotprovided](https://user-images.githubusercontent.com/1583842/35405412-b8437864-020e-11e8-8d8e-048fe60ee2d1.gif)

**Comment by diox** [comment]
I think that's intended, since it's a private collection. If something else is expected then it should be a frontend bug then.

That allowed us to discover another issue though, which was the fact that the cookies still weren't cleared correctly on logout, because we were trying to clear the same cookie on multiple domains, which is actually not allowed!

We changed the name of the cookie completely to work around the problem once and for all, in https://github.com/mozilla/addons-server/pull/7397

**Comment by vcarciu** [comment]
I will keep this open in order to understand why is this collection visible in homepage

**Comment by eviljeff** [comment]
The collection is likely visible because it's supposed to be a public collection and it was until someone tinkered with the setting (likely to test something else).  In any case, there isn't anything more to be done on addon-server so closing.  You should probably log something on frontend about the handling of the error though - I agree it doesn't look great.
