### ISSUE TITLE
don't start up autograph in travis jobs where we don't sign xpis

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7454]
We currently set up autograph (i.e. download go; download autograph; start it up) for every travis job, even though only a few tests in some of the jobs do any signing where autograph would be needed.  Some, like docs and assets, don't have any tests yet have autograph set up.  Removing that step would save 30 seconds.

**Comment by jrbenny35** [comment]
I think travis build steps would solve this well.

**Comment by diox** [comment]
I've tried this, and there are only a dozen tests that need it, all in `main`. All in `src/olympia/lib/crypto/tests/test_packaged.py` in fact.

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-server/issues/7468

**Comment by eviljeff** [comment]
I think we should move the signing related tests out of `main` - maybe into `addons` or `devhub`? - because it's the largest and slowest right now.

**Comment by EnTeQuAk** [comment]
@ulfr @krupa So the current plan with the waffle is:

We can switch the waffle on by default for everyone once everything is configured correctly or configure only a certain set of people by username or group to make use of the new autograph server.

We could also do a rolling release, the problem here is that waffle looks at all users and not just developers so I honestly don't know if that's worth doing.

There's also a separate metric in DataDog, I'll see to update the Dashboard to add the autograph stats in there.
