### ISSUE TITLE
Make use of the localisations from the linter.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#7515]
Update the integration with the linter so that the localized messages can be shown for a matching web locale.

**Comment by EnTeQuAk** [comment]
Not so easy, unfortunately, this needs to be done carefully since the messages retrieved from the linter are saved in the database and have to be readable by a reviewer too.

So, if the user submits his add-on with a French locale we have to save both versions somehow or - much much more complicated - sync the localized strings to addons-server and translate them on demand. I'm not sure what path to take, maybe we can discuss this next week during our Team Week.
