### ISSUE TITLE
Clarify what is `addon-id`, how it looks like

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mozilla/addons-server#7519]
I am about this page
https://github.com/mozilla/addons-server/blob/master/docs/topics/api/signing.rst

Signature:
`/api/v3/addons/[string:addon-id]/versions/[string:version]/`

In the example I see url `https://addons.mozilla.org/api/v3/addons/@my-addon/versions/1.0/` but as I understand `addon-id` is a UUID?

**Comment by diox** [comment]
So, this is confusing because of terminology differences between AMO and Add-ons in general. In add-ons documentation on MDN, Add-on id is defined as the `id` you put in your add-on install manifest, and it's either:
-  A [GUID](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Generating_GUIDs)
- A string formatted with {optional-string}@{string}`.

However, AMO also has add-on ids that are just the primary key of the add-on in our database. It's exposed in the API should you need it, and the API accepts it in a lot of places, but it's different from the add-on id as defined above, which in AMO terminology is the `guid`... even when it's in the email-like format.

That particular doc should clarify that it wants the add-on id from manifest, so what AMO calls a `guid`.
