### ISSUE TITLE
Fall back to non-empty version release notes, regardless of locale

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7535]
### Describe the problem and steps to reproduce it:

- Set your locale (in the URL) to `en-GB`
- Submit an add-on to devhub
- Manage the version and enter in some *Version notes* such as a list of things you changed
- Wait for auto-approval
- View the detail listing in the **en-US** locale

### What happened?

You do not see any *Release notes* section on the page

### What did you expect to happen?

You should see the *Release notes* containing the text from the `en-GB` locale

### Anything else we should know?

This is due to how locales works in the API. You can compare these two API requests:

```
$ curl 'http://localhost:3000/api/v3/addons/addon/sound-control/?lang=en-US' | jq .current_version.release_notes
null
$ curl 'http://localhost:3000/api/v3/addons/addon/sound-control/?lang=en-GB' | jq .current_version.release_notes
"- Changed some stuff\n- Fixed some bugs"
```

For the case where no string exists in the requested locale but we still have some string in another locale, can we fall back to it? Isn't there a concept of a default locale?

I think this is going to bite us for many things, not just version notes.

Originally reported in https://github.com/mozilla/addons-frontend/issues/4340

**Comment by diox** [comment]
> Isn't there a concept of a default locale?

[There is](http://addons-server.readthedocs.io/en/latest/topics/development/translations.html). When you request something in a specific locale, we fall back to the default locale of the object, or the default locale of the server if no default locale exist on the object.

So it should work here, if the add-on default locale is set to `en-GB`... unfortunately, there is an nasty gotcha: the default locale needs to be set on the same model. Release notes is a property of `Version`, which does not have a default locale field, so we fall back to `en-US` instead.

It's super annoying to fix because the translations mechanism is generic, and does not know about the relation between `Addon` (where the default locale is stored) and `Version`. We'd need to either patch it to allow the default locale to be fetched from a different table, making another join, or duplicate the default locale field to `Version`, keeping it in sync with the one on `Addon`.

See also https://github.com/mozilla/addons-server/issues/4599 which I suspect comes from the same core problem.

**Comment by kumar303** [comment]
OK, thanks, I see. So for things like `Collection` where the default locale is on the model, we probably won't see this issue. That's good.

**Comment by diox** [comment]
Also worth noting: a while ago there was an attempt to fix this by magopian, by adding a third condition falling back to whatever language available. Unfortunately this caused issues with things that needed to sort by a translated field and that idea had to be abandoned. We could revisit this but I think it's too much of an investment compared to the 2 other possible workarounds I describe above.

**Comment by diox** [comment]
Yeah AFAIK it only happens with the Version release notes and the License name/text (if a custom one is picked).

**Comment by eviljeff** [comment]
I don't think dropping localization each time it highlights a bug is the solution (and it's never that trivial to do).  Unless we're going to drop localization from _all_ user provided data we need to fix the underlying issue instead. I filed #8816 to do this.

**Comment by bobsilverberg** [comment]
I agree that we shouldn't necessarily drop localizations in order to address a bug if there are other/better solutions, but I do think we should consider dropping any localizations that we don't need/use, which is why I solicited @jvillalobos's input.

I understand that there is a significant amount of work involved in dropping localizations, but I also think that adding workarounds to allow us to keep storing unneccesary data isn't particularly productive and in fact adds to the technical debt these unused localizations represent.

**Comment by jvillalobos** [comment]
I think the bug is that we secretly localize all these fields without users / developers knowing that they are, and that leads to all sorts of problems. I agree with Bob that "unlocalizing" them is the better solution. Having said that, I don't know how hard that is compared to alternatives, or whether the alternatives will cause more issues.

**Comment by eviljeff** [comment]
We _do_ show a locale selector in devhub though and localisation is a known thing for addon submissions so, unlike ratings and profile data, I wouldn't call it secret localisation.  In this case the bug is as @diox detailed above - that there is a flaw in how we determine default locale and how we set the localisation.

If everything else about an addon that's show on the detail page can be localised, IMO it's inconsistent to not be able to localise the version notes.

**Comment by jvillalobos** [comment]
The field is not localizable during submission, which is pretty much the only way it's being entered. I honestly didn't remember it was localizable on devhub, and I doubt developers use this feature intentionally.

I don't think everything in the listing should be localizable, even if it's inconsistent. Localizing fields like version notes, support URL, etc. just lead to bugs and confusion.

**Comment by mstriemer** [comment]
This is affecting Firefox too, which I think would be expected. It looks like we'll find release notes and show the Release Notes button but then there's nothing there once it loads. Reported in [bug 1564497](https://bugzilla.mozilla.org/show_bug.cgi?id=1564497), but the reporter noted that this has been happening for a while.

**Comment by mstriemer** [comment]
For reference, Firefox is going through these requests (this is for the GB spell checker that the bug was reported for):

  * https://addons.mozilla.org/versions/updateInfo/4823513/en-US/ -> 301
  * /en-US/firefox/versions/updateInfo/4823513/en-US/ -> 301
  * /en-US/firefox/addon/461570/versions/2.75/updateinfo/ -> 301
  * /en-US/firefox/addon/british-english-dictionary-2/versions/2.75/updateinfo/ -> 200

The initial request seems to dictate locale that's checked, based off of the `Accept-Language` header, not the locale in the URL. The initial URL is what we got from the version check API at https://versioncheck.addons.mozilla.org/update/VersionCheck.php.

**Comment by grahamperrin** [comment]
:100: 

https://github.com/rNeomy/auto-tab-discard/issues/163#issuecomment-787783433

… and so on. 

Is [SponsorBlock for YouTube - Skip Sponsorships](https://addons.mozilla.org/addon/sponsorblock/) `2.0.13.1` bugged by this issue?

![image](https://user-images.githubusercontent.com/192271/114501703-67d89380-9c22-11eb-8940-aeff2bef0f42.png)

https://addons.mozilla.org/en-GB/firefox/addon/sponsorblock/versions/

Incidentally there should (I think) be a policy for developers of Mozilla-recommended extensions to always provide release notes. No notes sets a bad precedent to other developers.

**Comment by grahamperrin** [comment]
From <https://github.com/mozilla/addons-server/issues/7535#issuecomment-404595214>: 

> … I don't think everything in the listing should be localizable, even if it's inconsistent. Localizing fields like version notes, support URL, etc. just lead to bugs and confusion.

Realistically … of the developers who want (and are willing) to write notes in multiple locales:

* how many do **not** have an _external_ site where they can provide multiple sets of notes? 

----

The *Release Notes* tab of **about:addons** in Firefox `87` does allow presentation of linked URLs, for example: 

![image](https://user-images.githubusercontent.com/192271/114503996-10d4bd80-9c26-11eb-9f2a-ba7b712d9b47.png)

Kicking the ball around, maybe: 

* have a non-localised _Release notes_ field (use this phrase (not _Version notes_) for consistency with what appears in Firefox)
* add encouragement for the field to include a link to additional information.

**Comment by grahamperrin** [comment]
Cross-reference: 

* Mozilla bug [1668869 - Addon release notes visible in en-US locale but not-en-GB](https://bugzilla.mozilla.org/show_bug.cgi?id=1668869)
* [AMO Bug? Release notes not shown on en-GB install pages? - Add-ons / addons.mozilla.org - Mozilla Discourse](https://discourse.mozilla.org/t/amo-bug-release-notes-not-shown-on-en-gb-install-pages/53608?u=grahamperrin)

**Comment by grahamperrin** [comment]
Re: https://github.com/rNeomy/auto-tab-discard/issues/163

As usual, the `add0n.com` interface fails to present localised release notes (to me in the UK). There is, however: 

![image](https://user-images.githubusercontent.com/192271/145927217-81d916cf-40f7-4a27-bb38-d86333271287.png)

* an obscure link to https://github.com/rNeomy/auto-tab-discard/commit/fd6edd257897b87f114d8642227dfbc04faecb70

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-155
