### ISSUE TITLE
Say 'custom URL' instead of 'slug' in collection error messages

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7547]
We display collection slug validation messages (from the API) to the user. However, the UI refers to a slug as a *custom URL*, not a slug. Can we update these error messages to use the term *custom URL*?

<img width="691" alt="screenshot 2018-02-12 11 48 26" src="https://user-images.githubusercontent.com/55398/36111298-49139ed4-0feb-11e8-95ca-df6af41a634b.png">
<img width="691" alt="screenshot 2018-02-12 11 49 09" src="https://user-images.githubusercontent.com/55398/36111303-4b5fef9e-0feb-11e8-9b13-06a55053fee8.png">

**Comment by eviljeff** [comment]
Hmm.  But the API field _is_ called `slug` so, as an API validation error message, it's correct.  Is this the first time this problem has come up?

**Comment by kumar303** [comment]
> But the API field is called slug

Yes, well, it would be nice to change the field to `custom_url` but I could live without that part.

>  Is this the first time this problem has come up?

It's the first time we've built a frontend screen using this API field so yes. The legacy site referred to this data as a "slug" but I don't think that's a term we should expect users to understand.

The alternative to patching the API for this change is to maintain the localization string on the frontend and fix it there. However, that gets tricky because we'd have to match something in the API error message (a stable key) in order to replace it with a different localization. I think it would be better to fix it in the API since the API pretty much only exists for the frontend anyway.

**Comment by eviljeff** [comment]
`slug` isn't a particularly user friendly term, I agree, though if we change it for collections then arguably it should be consistent and changed for add-ons too and I'm less than convinced that changing `slug` to `custom_url` everywhere in the API and docs would make it easier to understand, especially when add-ons are returned as part of a collection API response.

If we _don't_ change it to `custom_url` then, as a policy, should the API be tailoring the error messages to how the frontend displays them - even if they make less sense for the pure API use?

API errors and messages are pretty inconsistently returned at the moment - some are localised, many aren't (I don't know if DRF's in-built validation responses are localised, I suspect not). Ideally I'd suggest all l10n for user displayable messaging it done on the frontend, but I'm not sure how viable that is, as front-end doens't know all the possible error messages.

Thoughts @diox @EnTeQuAk ?

**Comment by diox** [comment]
> I don't know if DRF's in-built validation responses are localised

They definitely are.

IMHO any API error that could be returned to *users* of the frontend should be localized. Some of our errors are not, but for most of them it's errors that should not happen unless something is seriously wrong with the client - things like an invalid combination of parameters in the search API, for instance.

We're still wildly inconsistent (mostly because even on the server it's hard to know about all possible error messages, we rely on the defaults from DRF for the most part), and that's an issue.

Going back to the original problem: if error messages about a specific field were shown next to the field in question in the frontend, it would help, IMHO. I'd certainly prefer to avoid having to customize all error messages...

**Comment by kumar303** [comment]
Even though things are inconsistent, I think it would be a pragmatic fix to simply tailor the localized error messages to the frontend when we need them -- this would fulfill the ultimate goal of shipping a good product to end users.

However, if now is a good time to dive into a more robust fix then we'd need some kind of code that we can differentiate from a normal string. For example, here's what [error responses](https://addons-server.readthedocs.io/en/latest/topics/api/overview.html#bad-requests) tend to look like:

```json
{
    "username": ["This field is required."]
}
```

We would need a code like:

```json
{
    "username": [{"code": "FIELD_IS_REQUIRED"}]
}
```

With that, we could begin to write and maintain our own localized error messages on the frontend.

**Comment by diox** [comment]
We do something like this for authentication related errors already (exposing both a human readable error message and a code) but having to do this for every single error would get tedious...

 In this particular case those are error messages that are completely under our control. Saying "Custom URL" instead of "slug" is not so bad, and it should still be obvious it refers to the `slug` since the error messages are attached to the field anyway. I'll implement that.

**Comment by vcarciu** [comment]
Verified as fixed : 
![serverslug](https://user-images.githubusercontent.com/1583842/36549638-f4560558-17fb-11e8-8efd-2828e9b249f9.png)
