### ISSUE TITLE
"Top-rated extensions" filtering needs variety

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#7548]
We often feature "Top-rated extensions" on the homepage. While the displayed content is indeed top-rated (usually showing nothing less than 4.5 star-rated stuff), we tend to see the same four top-rated extensions featured in the shelf for days on end. It looks like this:

![screen shot 2018-02-12 at 11 16 46 am](https://user-images.githubusercontent.com/8496249/36115674-a5baaab8-0fe8-11e8-9587-fb116851b8df.png)

While **pakku: bilibili danmaku filter [Language: Chinese]** may be a beloved extension, it's obviously intended for a narrow audience. And **Octotree** is only useful to developers (not average users). 

Can we adjust this filtering so that a fresh mix of top-rated content bubbles up randomly with each visit to AMO?

**Comment by jvillalobos** [comment]
We could have a set of extensions of which a small number are randomly selected for that module. What is the lowest rating you think should an add-on have to qualify? 4.0, 4.5, something else? Would it suffice to have the 20 top-rated add-ons to make the module random enough?

Caching may be a technical limitation here. So ti could be that the selection is random but it only changes every day or so instead of every time it's shown.

**Comment by devaneymoz** [comment]
We currently have around 70 5-star extensions with a minimum user base of 1,000. How about randomizing from that set? 

Further, unless there are concerns about randomizing from a set that's too large, what if we went with a pool that was extensions with min. 4.5 star rating and 1,000 users? That would ensure an even broader cross-section of content.
