### ISSUE TITLE
Theme name field is not updated when changing the image

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7646]
STR:
1. Load AMO dev and from Dev Hub submit a static theme using the wizard by clicking on Create a theme.
2. Click on the Browse button and select an image from your folder. 
3. Click on Select a different header image and choose another file.
4. Observe the "Theme name" field from the Theme generator page.

Expected result:
The name of the second image is displayed. 

Actual result:
The name of the first uploaded image is still displayed.

Notes:
This issue is reproducible on AMO dev with FF58 (Win10).

![switching images](https://user-images.githubusercontent.com/33448286/36602126-e00c6190-18bf-11e8-876a-3d98428f7c04.gif)

**Comment by SeanPrashad** [comment]
Hey everyone - I'm going to take a crack at this in the next few days!

**Comment by EnTeQuAk** [comment]
Awesome @SeanPrashad! 

Just so that we're clear on what the bug here really is: Imho it's almost a feature that we don't randomly overwrite the theme name. So we'd have to store some information if the users have overwritten the theme name but even then I'm unsure if the current behaviour is still preferable.

Any opinions on this? I don't want you to waste too much time on something that - at least for me - looks perfectly fine.

**Comment by SeanPrashad** [comment]
Hey @EnTeQuAk! I've just begun inspecting code but from the GIF in the OP, it looks like the theme name is being populated based on the uploaded header image filename.

From my perspective, if I were a user who wanted to create a new theme, say `Octocat`, but my header image was named `Monkey.png`, it would be an extra step in my workflow to correct the contents of that form control. Now in reality, most of the users who are developing Add-ons are probably savvy enough to make the correction after the image upload but it's definitely food for thought!

Do you think it would be wise to still investigate this?

**Comment by SeanPrashad** [comment]
Just an update @EnTeQuAk - I've opened a PR with my take on what a possible solution would be.

Like I mentioned earlier, I don't think we should populate the Theme name with the header image name at all. More than likely, the header image's file name isn't professional and doesn't necessarily reflect the name that the creator would want to have. If I'm not mistaken, this Theme name is what will be used to allow end-users to search for the theme and as such, should be manually specified without surprises!

If you think we should take a different path, I'll be happy to update my PR to reflect the desired functionality!

**Comment by EnTeQuAk** [comment]
Alrighty, so I discussed this with @eviljeff and we actually like the current behaviour. It gives the form a good default and doesn't overwrite any manual changes.

That's why I'm just going to close this issue, although I'm really sorry for all the work and brain you put into this. Thanks a lot for this!

Sorry for getting back to this issue so late.
