### ISSUE TITLE
Collection API returns encoded HTML entities

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7648]
### Describe the problem and steps to reproduce it:

STR: Create a collection with the `&` character in the description. See https://github.com/mozilla/addons-frontend/issues/4375

### What happened?

The API endpoint returns HTML encoded entities such as `&amp;`. Example:

```
curl 'https://addons-dev.allizom.org/api/v3/accounts/account/kumar-krsti%C4%87/collections/small-collection/?lang=en-US' | jq .description
"Things &amp; stuff and “quotes”\n\n£1,000\n\n&lt;not-a-tag&gt;"
```

### What did you expect to happen?

Well, I'm not sure. If this is expected then we can deal with it on the frontend. I thought to file a bug because the reviews endpoint is not returning encoded entities. Example:

```
$ curl 'https://addons-dev.allizom.org/api/v3/reviews/review/?addon=sound-control&api=&filter=without_empty_body' | jq '.results[0].reply.body'
"This is a reply & stuff"
```

Maybe the reviews endpoint should be returning encoded HTML entities?

**Comment by diox** [comment]
The `description` field for Collections is a bit wonky, it cleans up links inside the description to fight against spam, and to do this it forces the input to go through `bleach`. As a result the `description` field always return escaped content. Changing that behavior is annoying, especially since we'd need to retroactively fix all existing content on top of changing the way the link removal code works.

This was filed as https://github.com/mozilla/addons-server/issues/7368 before and wontfixed in favor of handling this in the frontend in https://github.com/mozilla/addons-frontend/issues/4213

**Comment by kumar303** [comment]
That works for me! I already have a patch to deal with it (https://github.com/mozilla/addons-frontend/pull/4447). I was just confused when I checked to see if I had to fix any other pages. I guess not.

**Comment by diox** [comment]
Re-opening because of https://github.com/mozilla/addons-frontend/issues/10179, and also because the inconsistency with the rest of our API is annoying (especially as we don't even document this weird behavior)

**Comment by diox** [comment]
The query to find the collections that would need to be migrated to the new logic would look like this:
```sql
SELECT localized_string, localized_string_clean, collections.*
FROM collections
LEFT JOIN translations ON translations.id = collections.description
WHERE description is NOT NULL
AND localized_string_clean LIKE '%&%'
AND localized_string_clean != localized_string;
```

Although I'm still getting results that don't seem to need any further tweaking (because they are so old they predate the change that caused us to store HTML) so it needs to be refined a bit. There are less than 3000 of them in any case.

**Comment by ioanarusiczki** [comment]
@diox 
Using Create collection endpoint I created a couple of collections using the following strings for `description`:
- "description": { "en-US": ""this & that"" } where "&" is displayed fine, this is the [collection](https://addons-dev.allizom.org/en-US/firefox/collections/10641574/test8/)
- "description": { "en-US": "<script>alert('problem')</script>" } -> looks the same on AMO -> [Collection](https://addons-dev.allizom.org/en-US/firefox/collections/10641574/test9/)
-  I used the HTML paragraph tag ->  [Collection](https://addons-dev.allizom.org/en-US/firefox/collections/10641574/test10/)

I tested this on AMO dev. 

Please let me know if this covers the testing for the issue. If not, some guiding would be nice. 
Thanks!

**Comment by diox** [comment]
Should be good! I've marked the companion frontend issue as not needing QA so that you don't need to repeat the testing.
