### ISSUE TITLE
ratings_url isn't actually a URL

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-server#7682]
### Describe the problem and steps to reproduce it:
Fetch addon details and refer to the ratings_url property added in #7534 

### What happened?
The ratings_url is just the path part of the URL without the protocol or hostname.  eg, for ublock origin it is:
```
"ratings_url": "/en-US/firefox/addon/ublock-origin/reviews/"
```

### What did you expect to happen?
Expected to see the full URL including `https://addons.mozilla.org/` (or whatever is appropriate) at the start.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Yeah, good point.

We need to pass that through our `absolutify()` helper like we do for other URLs.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF60.0a1 Win10x64

![image](https://user-images.githubusercontent.com/31961530/36895650-5486e04c-1e18-11e8-914b-01e3c4ed0df8.png)

Also looked in add-ons manager, where the issue was first spotted, and the link is redirecting correctly:

![verif-rev-count](https://user-images.githubusercontent.com/31961530/36895681-768251f4-1e18-11e8-950e-fadb8b6b2785.gif)
