### ISSUE TITLE
Allow signing api validation override parameter

### ISSUE THREAD

**Issue by Callek** [mozilla/addons-server#7745]
<mat> Callek: can you file an a bug over on https://github.com/mozilla/addons-server for an admin validation override parameter to the signing API?

For more context, releng would like the ability to ensure that all langpack submissions produced by actual automation during a release are signed, regardless of any issues/bugs in the validation API. So providing the ability for a release engineering user to mark the submission as not needing validation could increase the release stability once we start submitting to AMO as a blocking part of the release pipeline.

**Comment by jvillalobos** [comment]
Most of the blocking issues brought up by the linter have to do with corrupt files or other errors that would make the add-on not installable. Just want to make sure you're comfortable with potentially pushing broken files to users this way.

**Comment by EnTeQuAk** [comment]
I don't see the reason behind this. Since you're able to lint the langpacks locally too you get about 90% of the checks that we do and can make sure that the langpacks are in good quality.

Given that you shouldn't need an override parameter, that just opens the door for more folks asking about something like that and lessens the control over quality that we have. If you have any specific issues, these should be fixed but avoiding linting shouldn't be an option imho.

**Comment by muffinresearch** [comment]
@Callek See the responses above. Are the any specific linting issues you're regularly hitting that we can look at fixing?

**Comment by Callek** [comment]
@muffinresearch - Not currently, no. The qbtq here is that release automation sends to AMO, and requires signed langpacks to be returned or it blocks (or could delay) the release. This could be very very bad in a case of a chemspill, doubly so if it happens on a weekend or holiday when the AMO team cannot respond to the urgency.

I feel like we would want to prevent AMO from needing to do deploys to unblock
