### ISSUE TITLE
Theme preview is not always an exact representation of how the theme will look in the browser

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7804]
STR:

1. Visit a static  theme details page i.e. https://addons-dev.allizom.org/en-US/firefox/addon/more-bckg-preview-3/
2. Look at the theme preview in the screenshots section
3. Install the theme and compare the browser view with the screenshots

Actual result:
Theme preview is not an exact representation of what the theme will look in the browser once installed

Expected result:
Theme preview should offer a clear representation of how the theme will look in the browser after installation

Notes:
- follow up from [#7729](https://github.com/mozilla/addons-server/issues/7729)
- the following can be observed in the next screenshots:
 [1] - background alignment is not rendered correctly in theme preview
 [2] - the preview shows a transparency in the left corner which is not visible in the browser

[1] - https://addons-dev.allizom.org/en-US/firefox/addon/more-bckg-preview-3/
![image](https://user-images.githubusercontent.com/31961530/37413398-a5dc1f7a-27af-11e8-86e1-9211cd672ac8.png)

[2] - https://addons-dev.allizom.org/en-US/firefox/addon/additional-bckg-standard-3/
![image](https://user-images.githubusercontent.com/31961530/37413433-ba3efc12-27af-11e8-9d37-fbe4ff7984a7.png)

**Comment by eviljeff** [comment]
@AlexandraMoga I don't understand [2] - what transparency?

Btw, the guidence from UX & Product was to render a "typical" Firefox UI with default toolbar and view options - i.e. without the Menu and Bookmarks toolbar being visible.

**Comment by AlexandraMoga** [comment]
>  I don't understand [2] - what transparency?

@eviljeff If you compare the theme screenshot with the actual view from the browser, you can see that in the preview the **_orange_** color looks more "transparent" and sort of blends in with the rest of the design, while in the browser the **_orange_** shows no "transparency" and ends abruptly. I think the preview is showing the theme more "beautiful" than it actually looks once installed. Does this make more sense?





> Btw, the guidance from UX & Product was to render a "typical" Firefox UI with default toolbar and view options - i.e. without the Menu and Bookmarks toolbar being visible.

The fact that certain menus are not visible in the preview is not part of the issue I raised. My concern was strictly related to how the design is rendered in the two areas.

**Comment by eviljeff** [comment]
@AlexandraMoga it appears it's just how wide the browser it and how wide the images are - if it's smaller the images overlap so the top one (with the insect) fades into the orange one (the preview is rendered at 680px).

Here is the browser at about 110px wide:
![screenshot 2018-03-16 19 07 41](https://user-images.githubusercontent.com/768592/37517778-7f9e264c-294d-11e8-88e9-e285221eb889.png)

**Comment by eviljeff** [comment]
actually, [1] seems to be the same - it's a really weird rendering that I wouldn't have guessed from the manifest... but resize the window to about 872px and the preview matches Firefox

![screenshot 2018-03-16 19 20 48](https://user-images.githubusercontent.com/768592/37518232-4a41f7ba-294f-11e8-8fc8-e0ce275a3226.png)

**Comment by AlexandraMoga** [comment]
@eviljeff indeed, resizing the browser will show the theme design exactly as in the preview. 
However, for most of the cases the users will use the browser at its full size, so the differences could still prove misleading. 
LWT previews by comparison offered a more accurate representation in general.
Maybe showing theme previews for different screen sizes could be a solution(?)

**Comment by eviljeff** [comment]
LWT previews are 680x100 but half scale so effectively showing 1360x200 of theme - showing more width but also showing twice as much height than the average user would see*.  Static theme previews are 680x100 but full scale.  It's difficult to know what is "normal" size for users but for an average user with a 680px wide browser window static theme previews are more accurate than LWT's previews.  At wider window widths, perhaps not.

Different previews for different screen sizes would be a lot of complexity for frontend so we want to avoid that if possible.  We could render a wider width at half scale (e.g. 680x50) but the Firefox UI might be hard to understand; we could render a generally wider browser preview e.g. 1300x100 but I don't know how frontend would scale that for users browsing on smaller screens.

I'm closing this issue because the preview is functioning as we agreed in meetings with UX and Product .... but cc'ing @jvillalobos so he's aware of the limitations with current previews.  He can open/re-open and issue if we need to do something different with previews than now.

* (unless they're one of the outliers who try to make Firefox look like older versions by showing the menu and bookmarks toolbar)

**Comment by krupa** [comment]
I am going to reopen this issue and let @jvillalobos close the issue once he comments with his thoughts. Keeping the issue in the open queue makes it easier for QA to track it.
