### ISSUE TITLE
Synchronize dev marketing email setting with Basket

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7808]
We send developer marketing email to developers who check that box in their user profile ("stay up-to-date with news and events"). Sending the email is done through Salesforce, which has its own unsubscribe mechanism. After every mass mailing, we need to manually synchronize the unsbuscribe requests we get via that system with the AMO setting. For practical (and also legal) reasons, we need to make this synchronization automatic.

A system called Basket has been setup so we can do this easily. Quoting pmac:

> I think the easiest way forward will be to use basket's newsletter subscribe API endpoint[0] with the "sync" option. What this does is to tell basket to handle the request now rather than in an async task after the request has returned (which is the normal way it works for other subscribe forms). Because it does the subscription during the request it can and will return the user's token in the response. AMO could then store this token for use in creating the link to the email preference center on www.mozilla.org. Alternately you could use said token in a call to the unsubscribe[1] endpoint on behalf of the user if you'd rather.
>
> Because of the load to basket and the sensitive info returned when "sync" mode is on an API key is required when making this kind of call. I can generate such a key for AMO to use.
>
> If you'd like to just make a simple subscribe call when the user clicks the box and then fetch the token later that is also possible via the lookup-user endpoint[2]. An API key is also required for lookup-user when called with an email address.
>
> If your backend is written in Python we do have a client library you can use for these calls[3], but it's just simple HTTP POST requests if you need to write them yourself.
>
> [0] http://basket.readthedocs.io/newsletter_api.html#news-subscribe
> [1] http://basket.readthedocs.io/newsletter_api.html#news-unsubscribe
> [2] http://basket.readthedocs.io/newsletter_api.html#news-lookup-user
> [3] http://basket-client.readthedocs.io/en/latest/usage.html

And a followup:

>> So, whenever the user loads their user management page on AMO, it would be best if AMO calls lookup-user to determine the state of the setting?
>
> You can do it that way, or better would probably be to have it behind another interaction that they had to do in order to tell the system that it needs to query their state. The lookup-user endpoint will return a list of subscribed newsletters, so you can check if they're subscribed or not. 
>
>> Would we need an initial dump of the tokens for all subscribed users? 
>
> I guess you would. We can provide you with a dump of users subscribed to a particular newsletter and you can load that state into your db. Said state can change however if users update their subscriptions via the email preference center linked at the bottom of every newsletter.

**Comment by diox** [comment]
@jvillalobos is there any deadline for this?

**Comment by jvillalobos** [comment]
There's a hard deadline from Legal that I don't remember right now (maybe @caitmuenster does), but this is planned as a Q2 project, which should be within their requirement.

**Comment by caitmuenster** [comment]
We need this by the time GDPR kicks into effect on May 25.

**Comment by diox** [comment]
I'm bumping the priority then, to ensure it will be fully ready by then.

**Comment by diox** [comment]
@jvillalobos can we get a test server for dev, and api keys for dev and stage/prod ?

**Comment by jvillalobos** [comment]
@pmac can you help diox set this up?

**Comment by EnTeQuAk** [comment]
@pmac Do you have some more information regarding a test server for dev and api keys for dev and stage/prod?

**Comment by pmac** [comment]
Oh. Hi. Yes. My apologies for apparently missing a ping a while back. I'm happy to help. Perhaps we should setup a meeting on vidyo or IRC to fully hash out requirements and move from there. I need to know what kinds of requests you expect to send from your various instances.

**Comment by EnTeQuAk** [comment]
@jvillalobos just to clarify: The salesforce <-> basket integration will only be happening for developer announcements, I won't touch any of the other notification-types (e.g "my add-on is reviewed by a reviewer", "someone writes a review of my add-on" etc). We can implement them incrementally but I guess they're less relevant from a legal perspective? Can you confirm that?

**Comment by jvillalobos** [comment]
Correct. We only care about the development announcements at present.

**Comment by EnTeQuAk** [comment]
QA: This feature is behind a waffle-flag, I'll update the issue once it is properly configured on -dev, -stage and later -prod. (We need the API keys set before it can be flipped on).

Please make sure that without the flag, all user notifications are selectable and unselectable. Same with the flag. There isn't a good way to trigger a newsletter except via SalesForce once the flag flipped, we might want to test that the data is properly received in SalesForce by @caitmuenster or @jvillalobos once we configured things correctly.

![screenshot from 2018-05-09 06-42-30](https://user-images.githubusercontent.com/139033/39795987-3748a6fc-5354-11e8-9f33-f30a1e059b7d.png)

**Comment by AlexandraMoga** [comment]
@EnTeQuAk  I have checked the Developer notifications section on AMO-dev, without a flag (since there is no flag set yet) and everything seems to be working as expected. I've also checked that the developer receives an email when a user writes a review for one of his add-ons. 

Let me know once the flag is set so we can cover the second part of this test.

**Comment by EnTeQuAk** [comment]
The API keys have been deployed by ops so that -dev and -stage can be tested. Please make sure that checking and unchecking "stay up-to-date with news and events related to add-on developers" works properly.

All other notifications have not been touched but can be verified to be working properly.

Checking and unchecking should already cover most of this issue. Once you check the "stay up-to-date with news and events related to add-on developers" notification on devhub you should see some changes to your account on SalesForce too. @pmac can help checking that.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk I've checked the Developer notifications section on -dev and stage and I have not observed any issues with checkbox responsiveness

@pmac could you please check my account activity in Salesforce?
You should look for the following user: 
- dev:  _email_ - amoga@mozilla.com, _username_ - 4m0g4_D3v
- stage: _email_ - amoga@mozilla.com, _username_ - Amoga_stage

Let me know if you need any other details.
Thanks

**Comment by pmac** [comment]
I don't see that email address in salesforce at all. Are we sure that's the one it is sending?

```bash
$ curl "https://basket.mozilla.org/news/lookup-user/?email=amoga@mozilla.com&api-key=XXXX-XXXXX-XXXXX-XXXXX"
{"status": "error", "code": 3, "desc": "User not found"}
```

**Comment by EnTeQuAk** [comment]
My bad! The configs have been deployed but I didn't flip the switch. It's flipped now!

Both on -dev and -stage, I tested on my account cgrebs@mozilla.com on stage and that account now exists on basket.

**Comment by pmac** [comment]
I'll also recommend the [RestMail](http://restmail.net/) service for testing all of this. I've got that domain set to automatically add a "testing" flag in Salesforce, and it's nice to not subscribe so many times with your own email address. It works like this:

1. Sign up for a thing with `<any-username>@restmail.net` (e.g. the-dude-2018-05-16@restmail.net)
2. Go look at the mailbox on restmail.net (e.g. http://restmail.net/mail/the-dude-2018-05-16@restmail.net). It's a JSON representation of the mail recieved at that address.
3. ...
4. Profit!

It's good to use a unique email address like that so that you can see the whole flow including double-opt-in and welcome messages if you need to.

**Comment by jessilyndavis** [comment]
Hey y'all - Jess here Basket/Salesforce keeper.

Basket Dev is not setup for this newsletter ID. I recommend we continue testing to make Basket Stage work (which heads up: does point to Salesforce Production).

I checked cgrebs@mozilla.com in Prod - he *is* in Salesforce - but the newsletter subscription for the id "about-addons" is not checked. The code in AMO is not working.

I just did an API call for "about-addons" to subscribe a test user. And it worked: 

https://www.allizom.org/en-US/newsletter/existing/0c3620eb-6171-4ea9-82b7-a0c2209d8106/

**Comment by jessilyndavis** [comment]
UPDATE: We're blocking on enabling Basket stage and prod until this has been tested in Basket Dev.

No code will work until I get the configs set up in Basket Dev.

**Comment by diox** [comment]
I don't follow: you want us to test on Basket Dev but you mention above that it's not set up for this newsletter ID. How can we test this on dev then ?

**Comment by EnTeQuAk** [comment]
The basket integration has been configured and tested on basket stage,
that was a decided to not needlessly rely on a development system and
stage worked great so far. Why dev?

On Fri, May 18, 2018, at 10:37 PM, Mathieu Pillard wrote:
> I don't follow: you want us to test on Basket Dev but you mention
> above that it's not set up for this newsletter ID. How can we test
> this on dev then ?> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].
Links:

  1. https://github.com/mozilla/addons-server/issues/7808#issuecomment-390325400

**Comment by diox** [comment]
It seems to be working from AMO's perspective on stage, in the sense that submitting the form causes us to store a basket token for the user and refreshing the page shows the right checkboxes being checked. It does not appear to be synced with https://www.allizom.org/en-US/newsletter/existing/{token} however.

@jessilyndavis @pmac : I'm confused as to what's happening and where we should be testing here. As we said before we have been testing on stage before, is it not what we were supposed to do ?

**Comment by jessilyndavis** [comment]
Stage did not work when I tested it on Friday. If the newsletter subscription is not showing on https://www.allizom.org/en-US/newsletter/existing/{token} - then that subscription setting was not stored for that contact in Salesforce. 

Said another way: while the checkboxes appear to be working in AMO, and an API call is successfully talking to Basket to at least pass over a contact's email address and have a token created, the key piece of information (newsletter subscription/email setting) is not working.

Since it did not work on Stage, we need to debug the integration in a Dev environment before we potentially bork Production Salesforce data - which is used to manage relationships and send emails.

I'm working on getting Basket Dev to work as my P1 today. @pmac I'm talking you on IRC as we speak

Once the "about-addons" id is live and working on Dev (I will test through a direct API call to Basket Dev) then you'll be able to test the integration on your Dev site.

**Comment by jessilyndavis** [comment]
Test scripts:
**1) Check box to opt-in from AMO interface - existing contact in Salesforce.**

Make sure contact has in Salesforce:
“AMO Email Opt-in?” = True
Double Opt-in = True
Subscriber = True
Email Opt-out = False

Make sure contact has in Email preference center:
About:addons = Subscribed

**2) Check box to opt-out from AMO interface.**

Make sure contact has in Salesforce:
“AMO Email Opt-in?” = False
Double Opt-in = True
Subscriber = True
Email Opt-out = False (Will be true if you “globally unsubscribe” from email pref center)

Make sure contact has in Email preference center:
About:addons does not show (because you are unsubscribed and cannot opt-in from the email preference center)

**3) Check box to opt-in from AMO interface - new contact in Salesforce from AMO.**

Contact is created in Salesforce

Make sure contact in Salesforce has:
“AMO Email Opt-in?” = True
Double Opt-in = True
Subscriber = True
Email Opt-out = False
Email Format will default to H
Language will default to EN

Make sure contact has in Email preference center:
About:addons = Subscribed

**4) Check box to opt-out from Email preference center.**

Make sure opt-in flag is unchecked in AMO Dev interface.

Make sure contact has in Salesforce:
“AMO Email Opt-in?” = False
Double Opt-in = True
Subscriber = True
Email Opt-out = False (Will be true if you “globally unsubscribe” from email pref center)

Make sure contact has in Email preference center:
About:addons does not show (because you are unsubscribed and cannot opt-in from the email preference center)

**Comment by diox** [comment]
@jessilyndavis : on stage, I see in our logs "invalid newsletter" when trying to subscribe / unsubscribe to about:addons. (As far as our code is concerned the identifier of that newsletter in basket is `about-addons`)

**Comment by jessilyndavis** [comment]
@diox  - the newsletter config has been deactivated on stage until it is proven to work as expected on Dev.

Do you have automated tests running on stage? Or are the errors from manually testing?

**Comment by diox** [comment]
That was manually testing.

**Comment by diox** [comment]
@AlexandraMoga : you can test again on dev and stage. A few things to note though:
- Use the email center to see if it's sync-ed up with AMO. The URL is `https://www-dev.allizom.org/en-US/newsletter/existing/{token}` and `https://www.allizom.org/en-US/newsletter/existing/{token}` for dev and stage, respectively. You'll need your user basket token, you can ping a dev on IRC to get it (I'll add it to the user admin page later to ease debugging). Note that about:addons does not show up in that page if the user is not subscribed to it.
- There might be a slight delay before changes are processed. I had to wait a couple minutes in my own testing on stage.
- Follow @jessilyndavis testing plan above. In particular, test with both an existing and a new user.

**Comment by AlexandraMoga** [comment]
I have followed the recommended steps and re-tested this feature on -dev and stage.
Dev could not be verified as no tokens were generated. Waiting to receive the required tokens in order to complete testing on -dev as well. 

**For -dev:**
1. user **4m0g4_D3v** (amoga@mozilla.com) - old account with active subscription - _token not received yet_
2. user **basket-dev** (basket-dev@restmail.net) - new account, subscribed to notifications after the account was created - _token not received yet_

**For stage:**
1. user **Amoga_stage** (amoga@mozilla.com) 
  => old account with active subscription 
  => checked that the status for`about:addons` newsletter in the [email preference page](https://www.allizom.org/en-US/newsletter/existing/2e0e40b6-cf50-4283-8a3e-2c8150042da1/) was _Subscribe_ 
  => opened my AMO account page and unsubscribed from developer notifications then checked if the status for `about:addons` newsletter is  _Unsubscribe_
2. user **basket-stage** (basket-stage@restmail.net) - 
  =>new account, subscribed to notifications after the account was created
  =>checked that the status for`about:addons` newsletter  in the [email preference page](https://www.allizom.org/en-US/newsletter/existing/b19dad5e-0cb7-4495-8ea6-bf6ff7383311/) was _Subscribe_

**Comment by diox** [comment]
Note: I made some changes in https://github.com/mozilla/addons-server/issues/8314 that should land on dev shortly, that makes most errors received from basket cause a "oops" in AMO, making it more obvious when something goes wrong. Worth re-testing with that.

**Comment by jessilyndavis** [comment]
@AlexandraMoga - I could not find either user in -dev Salesforce. It looks like Dev is not working. @diox - can you debug?

For stage: your test results validates test cases 1, 2, 3.

Can you test Scenario 4? With someone who's currently subscribed, go to the email preference center and unsubscribe from "about:addons" from the email preference center. Then check to make sure you're unsubscribed in the AMO interface.

Question: if someone subscribes to "about:addons" from the email preference center, and is not an AMO Developer, will there be any issues with this integration trying to find and update an AMO Dev user that does not exist? Please test this use case. You can subscribe one of my test accounts if that's helpful: https://www.allizom.org/en-US/newsletter/existing/52e16051-c494-1bca-e98f-2768978a7d89/

**Comment by diox** [comment]
Could dev suffer from the same issue we had with stage before and async requests, with workers not processing stuff? From my testing it seems that once I enabled the sync mode (@AlexandraMoga did their testing before that) I suddenly was able to get tokens, but not before.

I don't think we care anywhere whether the user that has subscribed to this is actually a developer.

**Comment by jessilyndavis** [comment]
Thanks @diox ! That could be it. @AlexandraMoga - can you give a quick test on Dev again now that the sync requests are enabled?

Also, glad to hear that this integration won't send y'all errors if a non AMO Dev user subscribes/unsubscribes from the email pref center. Brilliant!

**Comment by pmac** [comment]
Updates to/from the email pref center on bedrock will take a few seconds to happen. I'd imagine there is also some level of caching on the AMO side for these kinds of things. All that to say I would not expect these settings to sync between these systems as quickly as they're expected to in the attached GIF. I'd try refreshing for 30s or so to see if it eventually comes through.

**Comment by jessilyndavis** [comment]
@AlexandraMoga - thanks for the gif! That is incredibly helpful to see. When you click "unsubscribe" for about:addons in the email preference center, are you scrolling down to the bottom of the page and clicking the "Save Preferences" button? You'll need to do that for the setting to be saved from Basket -> Salesforce.

**Comment by AlexandraMoga** [comment]
@jessilyndavis thanks for drawing the attention to the 'Save Preferences' button, You are right, I forgot to click it when I tested that part.

I've re-run the scenario and now the changes are successfully applied on the email preference center. However, after waiting ~15 mins, the new status was still not reflected on AMO. I've also logged out and logged back in.

![image](https://user-images.githubusercontent.com/31961530/40429357-33972878-5eab-11e8-8926-726b0c641ef4.png)




Cc @pmac and @diox to hear what they think about this

**Comment by pmac** [comment]
Did the change definitely apply in the email pref center? Try a hard refresh (hold shift and refresh) on that page to ensure that it's really unsubscribed. Or I can look in basket itself if I can get the token.

**Comment by jessilyndavis** [comment]
@diox - better question: when the AMO Dev user settings page is displayed, are you fetching the latest subscription info from Salesforce to display opt in/out status?

**Comment by jessilyndavis** [comment]
@AlexandraMoga - did you have the unsubscribe issue on stage? (where you unsubscribe from email preference center, and still are subscribed in AMO interface)

**Comment by AlexandraMoga** [comment]
@jessilyndavis I've tried both on -dev and stage, and for both cases, I'm still subscribed in AMO.
FYI, 
- on -dev I have tested this part with user basket-dev-new@restmail.net  - https://www-dev.allizom.org/en-US/newsletter/existing/86f48bf1-66aa-4744-ac1a-367cf16510b4/
- on stage - user - amoga@mozilla.com - https://www.allizom.org/en-US/newsletter/existing/2e0e40b6-cf50-4283-8a3e-2c8150042da1/

**Comment by diox** [comment]
AMO fetches the state from basket before displaying the edit page.

**Comment by jessilyndavis** [comment]
@AlexandraMoga - did you retest today on stage?

**Comment by vcarciu** [comment]
@jessilyndavis : Yes, Alexandra retested today on Stage, but right now she is not at the office anymore and will continue to test tomorrow if anything else is needed.

**Comment by diox** [comment]
There is definitely something wrong in the way we display the state we got from basket. Looking into it...

**Comment by AlexandraMoga** [comment]
I've retested the the scenario on -dev and stage and these are my new results:

**For dev** - Unsubscribing from `about:addons` in the email preference center seems to be working. The subscription checkbox from AMO account page is unmarked. The `about:addons` newsletter is no longer displayed in the email preference center:
![image](https://user-images.githubusercontent.com/31961530/40468990-c23dc21c-5f37-11e8-8eb8-423019aa3346.png)

**For stage** - Unsubscribing from `about:addons` in the email preference center is still not working. The subscription checkbox from AMO account page remains marked. The `about:addons` newsletter is still  displayed in the email preference center, but with status _Unsubscribe:_

![image](https://user-images.githubusercontent.com/31961530/40469101-1432dd96-5f38-11e8-8b1f-942477c911f8.png)

@diox, I should be able to test your latest change in stage as well, isn't it? It seems, however, that stage is still not aligned. 
Also, the fact that on -dev, the `about:addons` newsletter is no longer listed among the options in the email preference center once the user unsubscribes, while on stage it is still displayed has drawn my attention.

**Comment by diox** [comment]
@AlexandraMoga I haven't yet cherry-picked the change I made late last night for stage, so the difference in behaviour is normal. The fact that on dev `about-addons` disappears from the email preference center is also normal I think, it's a configuration difference on salesforce side.

**Comment by diox** [comment]
@AlexandraMoga you can retest on stage.

**Comment by AlexandraMoga** [comment]
Stage is working as well:

![image](https://user-images.githubusercontent.com/31961530/40484467-65b88748-5f64-11e8-8e8c-98652e606758.png)

Since no other problems have been noticed in the meantime, I'm going to mark this issue as verified fixed on AMO -dev and stage with FF60, Win10x64

**Comment by jessilyndavis** [comment]
Brilliant! Glad to hear stage is working! 

I'm setting up Basket Prod now with the "about-addons" configuration now. I'll comment here when it's ready.

The showing/disappearing difference between stage and dev on the email preference center is expected and controlled on the Basket/Salesforce side. In production the newsletter will show whether someone is subscribed or not, to allow other email subscribers to opt-into this email program if they'd like.

**Comment by jessilyndavis** [comment]
"about-addons" is live in Prod and showing in the email preference center for someone I just subscribed via API call:

https://www.mozilla.org/en-US/newsletter/existing/675fd639-f956-4f34-8629-7d64c4c4af11

Please enable this in prod when you're ready and let me know how testing goes!

**Comment by jessilyndavis** [comment]
Thanks @pmac! Right now it's EN only - but I'll work with @caitmuenster if/when it's ready to be l10n'ed to file the bedrock bug and setup all the Salesforce/Basket l10n goodness.

**Comment by caitmuenster** [comment]
Hi @diox, @cgrebs , and @AlexandraMoga -- the Salesforce/AMO sync will be complete as of Friday, May 25 at 3pm PDT. Can you please turn it on and test it on Monday? (If things are not going well after it is turned on, you can turn it off.) 

@jessilyndavis and I will be observing a US holiday on Monday but will be able to jump in and help troubleshoot first thing on Tuesday. 

Thanks!

**Comment by jessilyndavis** [comment]
@diox - did this go live yesterday?

**Comment by diox** [comment]
No. We didn't get an answer from QA when we asked yesterday on IRC.

**Comment by EnTeQuAk** [comment]
No it didn't, QA wasn't around yesterday because of a national holiday. We'll flip this on today if nothing's in our way.

**Comment by caitmuenster** [comment]
Awesome! Flip away!

**Comment by jessilyndavis** [comment]
@EnTeQuAk @diox - are we live? Things working ok? I saw: https://github.com/mozilla/addons-server/issues/8320#issuecomment-393074892

**Comment by EnTeQuAk** [comment]
This is now live.

**Comment by AlexandraMoga** [comment]
@jessilyndavis @EnTeQuAk This is verified on prod as well. I've managed to subscribe to 'about:addons' from AMO and unsubscribe is possible both from the email preference center and from AMO.
