### ISSUE TITLE
Support Chrome-style color fields and syntax for static themes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7845]
According to https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme some of the color fields have Chrome equivalents and support an additional syntax as well as standard css formats.  Our previews should translate/support these too, because Firefox does.

**Comment by AlexandraMoga** [comment]
@eviljeff in order to test this, I've submitted a static theme with the following properties - https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme#Chrome_compatibility
and verified that previews are generated based on the values used. 

Here is one of the examples I've created: https://addons-dev.allizom.org/en-US/firefox/addon/st-with-chrome-properties-7/

If this does not cover everything, please add additional suggestions.

**Comment by eviljeff** [comment]
lgtm.

**Comment by AlexandraMoga** [comment]
In that case, this can be marked as verified fixed on AMO-dev with FF59, Win10x64.
- theme previews are generated
- themes are correctly handled in Reviewer Tools
- themes can be installed
