### ISSUE TITLE
Create migration script to migrate existing LWT to static themes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7847]
Existing lightweight themes should become static themes so AMO doesn't have to support the code for both.

<<Needs more details about migration strategy and what we will do for clients <Fx53 that don't support static themes>>

**Comment by jvillalobos** [comment]
See [PRD](https://docs.google.com/document/d/1d9acBumpdK87sYg7Ah98BEKvL7b4tuO-RDpgqbm7FTs/edit#heading=h.ph0yhtsx9uv6) and [migration cases](https://docs.google.com/document/d/18Wyc7l7Na2pVtaU1j4VhCM63nbawziOzIFJC_giRk74/edit) for an overview. I can post more specifics here later, but this week is crazy.

**Comment by eviljeff** [comment]
From a quick read the PRD seem possible... but one concern is around supporting backwards conversion from LWT we've converted to static themes.  

It may be a considerable amount of work to implement this and it's enabled only at the end of Q2 (or late in Q2).  How long will this be used for when we're planning to remove support on AMO generally for old Firefox versions in Q3 after the ESR is out of support (i.e. delete all the legacy addons).  

If it's it's a few months we could just wait a few months to migrate LWTs to static themes.  Or decide that supporting LWT for ESR isn't a requirement and drop support early.

**Comment by eviljeff** [comment]
Might be best to discuss the above in a meeting with everyone who needs to be involved ^

**Comment by jvillalobos** [comment]
Stuart and I talked about this yesterday, and I agree the timing doesn't make much sense. I'll update the docs (maybe), and we'll meet next week to talk about this.

**Comment by eviljeff** [comment]
@jvillalobos can you confirm which LWT statuses we will be migrating?  Personas can have the following statuses:
    STATUS_NULL: _(u'Incomplete'),
    STATUS_PENDING: _(u'Pending approval'),
    STATUS_PUBLIC: _(u'Approved'),
    STATUS_DISABLED: _(u'Disabled by Mozilla'),
    STATUS_DELETED: _(u'Deleted'),
    STATUS_REJECTED: _(u'Rejected'),
    STATUS_REVIEW_PENDING: _(u'Flagged for further review'),

Any LWT that aren't migrated will eventually be removed.  In theory any of them could be migrated, but it's more complexity, and some statuses are obviously of questionable value.

If, for example, we didn't migrate STATUS_PENDING we could just make sure to clear the queues before the migration script.

**Comment by eviljeff** [comment]
@jvillalobos another question: localisation - in theory LWT could have been localised (name and description are TranslatedFields; the Persona wizard has a l10n selector) but generating localised xpis is more difficult, and more likely to result in broken output given the state of some localisation.

**Comment by AlexandraMoga** [comment]
@eviljeff does this implementation introduce anything that requires QA attention?
Thanks

**Comment by eviljeff** [comment]
It does, but ops need to run the migrate command on the server.  Can you select a few existing personas that are on dev and stage (so you can compare after the migration) and we'll ask ops to migrate those few.

**Comment by eviljeff** [comment]
@AlexandraMoga I asked ops to migrate the first four of those (I wanted some back-ups in case something went wrong and broke the existing themes).  

New frontend seems to error if you aren't logged in (I don't know if there an issue already logged about static theme detail pages failing to load) but after logging in, or using legacy frontend, shows them.

If someone is wrong or some data should be migrated and isn't (I just realised we may want to do something about existing ratings) it'd be good to get follow up issues logged.

n.b. we don't plan on running this on prod until late Q3.

**Comment by AlexandraMoga** [comment]
@eviljeff I have verified the details page for the first four themes in the list and checked the details migrated. So far we have: theme name, author, description, preview, more info card.
I have filed follow up issues for what I've considered worth mentioning. It might be that some of these observations are already in your implementation plan, but since the [PRD](https://docs.google.com/document/d/1d9acBumpdK87sYg7Ah98BEKvL7b4tuO-RDpgqbm7FTs/edit#heading=h.w64xax5t65re) and [frontend/tracker-issue#4899](https://github.com/mozilla/addons-frontend/issues/4899) referred mostly to general statements, I thought it's better to have them tracked in separate issues.

Issues filed so far:
#8266
[frontend-issue#5015](https://github.com/mozilla/addons-frontend/issues/5015)
[frontend-issue#5016](https://github.com/mozilla/addons-frontend/issues/5016)
[frontend-issue#5017](https://github.com/mozilla/addons-frontend/issues/5017)
[frontend-issue#5018](https://github.com/mozilla/addons-frontend/issues/5018)

Regarding your observations:


> New frontend seems to error if you aren't logged in (I don't know if there an issue already logged about static theme detail pages failing to load) but after logging in, or using legacy frontend, shows them.

We know about this and have filed [frontend-issue#3601](https://github.com/mozilla/addons-frontend/issues/3601)  a while back



> (I just realised we may want to do something about existing ratings)

I have logged issue #8267 to cover this aspect

I'm going to mark this issue as verified fixed on AMO-dev with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/40113725-1653acde-5913-11e8-9af1-48aa6b6aa6d9.png)

**Comment by eviljeff** [comment]
@AlexandraMoga thanks!
