### ISSUE TITLE
New static theme version is listed in the 'New Add-ons' queue if all previous versions are disabled

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7853]
Follow up for #7765 

STR:

1. Log in to Developer Hub and submit a new static theme
2. Go to the theme's review page and reject it 
3. Go back to Developer Hub and submit a new version for the same theme
4. Check Static Theme queues in Reviewer Tools to see in which list your theme is pending for review

Actual result:
The new submitted version is listed in 'New Add-ons' queue, even if it had a previous disabled version -
 [see example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/276_image_8yyy)

Expected result:
I would expect to find the new submitted version in 'Add-on Updates' queue, since the new version belongs to a theme that was already reviewed once

Notes:
- reproduced on AMO-dev, with FF59, WIn10x64

**Comment by diox** [comment]
It's slightly annoying but not specific to static themes

**Comment by eviljeff** [comment]
Yeah, this is standard behaviour for all add-ons.  Unless there is already a public, approved, version (so the addon status is public) then submissions are counted as new submissions rather than updates.

I'm not aware of any plan to change that behaviour in general, and we don't want to unnecessarily special case static themes, so closing this as wontfix.
