### ISSUE TITLE
Remove content reviewers from being cc'd on emails to developers 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7857]
One of the content reviewers reported that he receives notifications when other reviewers take action (request more info, etc) on extensions he has content reviewed. ([Example](https://www.dropbox.com/s/7w3ze5x0n3t6e7o/2018.03.20%20-%20%20Fwd-%20Mozilla%20Add-ons-%20Action%20Required%20for%20Time%20to%20Decimal%201.0%20copy.pdf?dl=0).) The content reviewer also reported that he had not opted in to receive these notifications. 

These notifications aren't relevant to content reviewers. I'd like them to be removed from receiving those notifications. (If someone could tell me how they can opt out of these notifications, I'd be happy to pass that on, too!) 

**Edited to add:** This may also be related to [issue #609](https://github.com/mozilla/addons/issues/609) on the addons repo.

**Comment by wagnerand** [comment]
Removing them would mean they wouldn't get a notification for replies to their own need-infos either. If we are not going to split that flag into separate flags (content vs add-on) like discussed in https://github.com/mozilla/addons/issues/609 I'd prefer if they just ignore those instead instead of missing out on potential relevant ones.

**Comment by caitmuenster** [comment]
Good point. Should I close this issue, then, in favor of mozilla/addons#609 ?

**Comment by wagnerand** [comment]
https://github.com/mozilla/addons/issues/609#issuecomment-358418371 is a little bit different from this one and the suggested fix for that (which is actually not separating the `need-info` flag wouldn't solve this issue.

Yet both of these issues are linked together as I believe separating the `need-info` flags would fix both.

Otherwise, we'll have to find a separate fix for this one.

**Comment by diox** [comment]
Discussed in standup meeting, it's annoying but not a p2 - the solution is not entirely clear here, we need to decide whether we want separating the flag or not.

**Comment by jvillalobos** [comment]
Would this be fixed by not including content reviewers in review updates if the version has been content approved? It seems unnecessary to keep a reviewer in the loop after their participation as content reviewer has ended.

**Comment by diox** [comment]
mmm maybe yeah. The content approval is not directly stored on the version, it's just a date linked to the add-on, but maybe we can still do something similar to that idea.

In order to gather the list of reviewers that need to receive the email, we fetch all `ActivityLog` objects for the given `version`, and look if they came from someone with any kind of reviewer permission. We could simply exclude `ActivityLog` that have the `APPROVE_CONTENT` action...

However, there are 2 drawbacks with this approach:
- If the version has been content approved, but the reviewer did something else on that specific version, they'll receive the email because of that other activity.
- If the version has been content approved, but then content rejected by a different reviewer for some reason, the original content reviewer will not receive the email.

If those drawbacks are tolerable we could implement it this way, it should be fairly straightforward.

**Comment by jvillalobos** [comment]
> If the version has been content approved, but the reviewer did something else on that specific version, they'll receive the email because of that other activity.

What about this: if the version has an `APPROVE_CONTENT` action, only message users with code reviewer permission.

> If the version has been content approved, but then content rejected by a different reviewer for some reason, the original content reviewer will not receive the email.

That's okay with me, but I'd like to hear from @wagnerand for other cases we may be overlooking.

**Comment by diox** [comment]
> What about this: if the version has an `APPROVE_CONTENT` action, only message users with code reviewer permission.

I think that'd work, yeah.

**Comment by wagnerand** [comment]
> What about this: if the version has an APPROVE_CONTENT action, only message users with code reviewer permission.

So, if content-reviewer A sends an information request and content-reviewer B content-approves before the developer replies, none of them will get the developer reply email. Hm. 

> If the version has been content approved, but then content rejected by a different reviewer for some reason, the original content reviewer will not receive the email.

I am particularly interested in this use-case. This happens usually when the first reviewer made a mistake or missed something. In that case, I think we should really let them know so they can adjust and remember that next time.

**Comment by jvillalobos** [comment]
> So, if content-reviewer A sends an information request and content-reviewer B content-approves before the developer replies, none of them will get the developer reply email. Hm.

Doesn't content approval generally mean the info request isn't needed anymore?

>  This happens usually when the first reviewer made a mistake or missed something.

The second reviewer would need to be an admin, right? Does it happen often enough that they original reviewer can't be pinged directly?

**Comment by wagnerand** [comment]
> Doesn't content approval generally mean the info request isn't needed anymore?

We can only assume that if the person who approved the content is the same person who requested the information. Otherwise, it is likely but not guaranteed.

> The second reviewer would need to be an admin, right? Does it happen often enough that they original reviewer can't be pinged directly?

As far as I know, you don't need to be an admin for that. Pinging the original reviewer is fine if the second reviewer is an admin, but if not, admins likely won't notice.
