### ISSUE TITLE
Force enable\disable addon is not working for some extensions

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#7886]
Steps to reproduce:
1.While being logged with an admin account, go to https://reviewers.addons.allizom.org/en-US/reviewers/review/noscript
2.Click Force Enable\Disable button

Expected results:
Addon is enabled\disabled without any issue

Actual results:
Button becomes grayed out and no action is performed

NOTES:
Not reproducible for another tested extensions

Please see a video for this bug : 

![force](https://user-images.githubusercontent.com/1583842/37768602-ddcaf050-2dd6-11e8-9ea7-196a27e99ed9.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/3363302/

`OperationalError/api/v3/reviewers/addon/{pk}/enable/`
`error(1213, 'Deadlock found when trying to get lock; try restarting transaction')`

That's weird...

**Comment by diox** [comment]
@bqbn is there any way I could get permission to run `SHOW ENGINE INNODB STATUS` when I want to on stage to debug this? Without it it's hard to understand why a simple `UPDATE` with the primary key would result in deadlocks that consistently.

**Comment by diox** [comment]
Thanks, it's working, that'll help

**Comment by diox** [comment]
Spent more time on this but it's tricky. 

The deadlock appears to be caused by fetching the add-on data itself - but it should be the same transaction, so I don't get it.

The obvious thing to try is [`select_for_update()`](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#select-for-update), but with django-cache-machine in play, you can't control the query that fetches data (caused by `FETCH_BY_ID` mode, which is enabled) so it's not practical.

The alternative is to move transaction pieces around to manually do `transaction.atomic()` later rather than rely on `ATOMIC_REQUESTS` but I'd like to avoid that if possible.

Somehow it doesn't seem to affect other add-ons and we haven't seen it on prod so I vote for waiting to get rid of cache-machine.

**Comment by diox** [comment]
I can't find a trace in sentry right now but this is still happening : the XHR call returns a 504 (!). Maybe it's tied to the number of versions attached to the add-on somehow, depending on the callbacks that are fired when disabling/enabling an add-on.

We don't have cache-machine anymore so we could do the `select_for_update()`, but I'd like to understand why this is taking so long before (otherwise we risk locking something for a long time).

**Comment by diox** [comment]
Strongly suspect this is caused by `watch_disabled` which tries to hide/unhide files for a disabled add-on synchronously. This can take a while on add-ons with lots of versions.

**Comment by diox** [comment]
Worth noting: maybe https://github.com/mozilla/addons-server/issues/7158 will help for some occurrences of this. For add-ons with lots of versions though, we're better off not moving the files synchronously and do it using the `hide_disabled_file` cron or through celery.
