### ISSUE TITLE
Listen to FXA SQS queue to process account deletions

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#7922]
To conform with GDPR we need to listen to the FXA SQS message queue and delete a user's account in response to a user deleting their FXA account.

Work to listen to the SQS queue is already in progress [1] so fixing this issue would be about adding the relevant code to specifically listen to the deletion message and action it.

[1] https://github.com/mozilla/addons-server/issues/6451

**Comment by eviljeff** [comment]
What does AMO need to do when it gets the SQS message that the linked FxA has been deleted?  Just delete the account straight away?  Do we need to inform the user in any way?  Afaik we don't email users when their account is deleted right now (because we ask for confirmation on the site and warn them, etc)

Probably a different issue, but what about all existing AMO accounts that relate to deleted FxA accounts?  (And AMO accounts prior to FxA integration)

**Comment by diox** [comment]
Also, what happens to their add-ons? Currently you can't delete your user account if you're still a developer of a non-deleted add-on.

**Comment by eviljeff** [comment]
We could delete the add-ons too, I suppose.  Though as that's a very non-reversible thing I'd be somewhat worried about doing it automatically as a result of a message from FxA (or any 3rd party service) because we don't know what warnings they've been given.

**Comment by eviljeff** [comment]
so, users who are developers and delete their FxA account, we could either:

A. not delete their AMO account, because of their add-ons - which is probably breaching GDPR.  We could do something like email the user to tell them we've not deleted their account and why but for them to fix it and delete the add-ons they'd have to recreate the FxA account and log into AMO which seems a crappy experience. 

Or

B. delete their add-ons too, if they're the only developer listed.  For add-ons with only unlisted versions or that aren't approved it's probably a no-brainer to just delete them. But for approved and publicly listed add-ons it's more tricky - we require all add-ons to have an owner to be able to contact them, and AMO's code is written with the assumption that there's always >1 owners for every add-on (and bugs like #4952 happen otherwise).  Our "soft-delete" doesn't actually clear all the Addon data in the database [*] but some content _is_ deleted (user ratings, previews, some compatibility settings) and the slug is cleared and immediately available to be used by another add-on, making it a non-reversible action.  For a user "only" deleting their FxA account, this may be a very unexpected outcome.

**Comment by jvillalobos** [comment]
Do we know what the UX is like when deleting a FxA account? Is there a message explaining everything will be nuked?

Given this is a legal matter, I suspect A won't be an option. The main loss for developers in the case of accidental deletion would be the ratings and reviews for the add-on. The rest can be replicated by the devs (except maybe slugs). I think that's something we can live with.

**Comment by muffinresearch** [comment]
@jvillalobos it looks like this:

<img width="637" alt="firefox_accounts__delete_account" src="https://user-images.githubusercontent.com/1514/38384362-d7b81158-3906-11e8-9ad6-cc41d4207c49.png">

So there's nothing to make it clear that a deletion will have impact beyond FXA.

Following further discussion with @eviljeff I would like to check if we really need to make this change.  Maybe the facility existing on AMO is good enough from a GDPR perspective - we'll need legal to confirm. 

If we do need to connect FXA deletions to AMO this then this is going to have broader implications for FXA to communicate what is happening more clearly.

**Comment by rfk** [comment]
> Do we know what the UX is like when deleting a FxA account?
> Is there a message explaining everything will be nuked?

FYI we're investigating UX/messaging requirements on the FxA side right now in https://github.com/mozilla/fxa/issues/289.  It sounds like it might suffice for us to say to the user "go visit all the places you used your account, and make sure you delete things there as well", but we're waiting on final designs and confirmation there.

**Comment by muffinresearch** [comment]
Thanks @rfk. I'm going to close this for now, and we can re-open it as and when there's an action to take on the AMO side.

/cc @eviljeff
