### ISSUE TITLE
Only show public (and pending) add-ons in 'Expired Info Requests' queue

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8008]
Rejected or deleted add-ons don't need to show up in the "Expired Info Requests" queue as their is nothing to be done for reviewers.

Instead we should only show public (and pending for legacy/auto-approval disabled) ones.

**Comment by ioanarusiczki** [comment]
@wagnerand I verified this issue on AMO dev (Win10). 
1. Deleted or rejected add-ons don't need to show up in "Expired Info Requests" queue.

2. I tested with an add-on the auto approval disabled scenario. First version was auto approved and the second version disabled, v3 is awaiting review because Has auto-approval disabled flag set. I also requested a super review. I don't see the add-on in  "Expired Info Requests" queue.
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/hedger

![requested super review](https://user-images.githubusercontent.com/33448286/38616425-aae937e8-3d9c-11e8-962b-507718769e4f.png)

Please let me know if I should file an issue or some further testing is needed. 
Thank you!

**Comment by wagnerand** [comment]
> Add-ons from expired info request queue are still displayed after setting the invisible status from dev hub (they are no longer public). Please let me know if I should file an issue for this scenario.

Yes, please do. It's an easy patch, low effort.

**Comment by ioanarusiczki** [comment]
I filed https://github.com/mozilla/addons-server/issues/8059 
Also checked the third issue auto-approval disabled status with more information request expired will show up in the queue.
