### ISSUE TITLE
[Review Tools] Change "New Add-ons" to "New Themes" on Theme Review Homepage

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#8022]
On the theme reviewer homepage, the queues for static themes are referred to as "New Add-ons," "Add-on Updates," and "Add-on Review Log." 

It would be great to swap out "add-on" for "theme" or "static theme" in those instances before this goes live. :) 

![reviewer tools - theme view](https://user-images.githubusercontent.com/23342476/38583088-b79e9216-3cc6-11e8-9d29-29b0fc5b4616.png)

**Comment by eviljeff** [comment]
The reviewer tools for static themes _are_ the add-on review tools though - you would just see either static themes or non-static themes in the queues depending on which permissions you have (and both types in the same queue if you had both permissions).  Static themes are add-ons and it's been a deliberate choice to [consolidate](https://github.com/mozilla/addons-server/issues/7385#issuecomment-371195269) to a single set of tools rather than to build new separate ones.

This page specifically though, (the dashboard) is manually constructed so I can change the headings and link text if you want.  However, as soon as they get to the queues themselves, and the review pages inside, everything is generically referred to as add-ons.  Something to highlight to the reviewers.

@jvillalobos fyi

**Comment by caitmuenster** [comment]
Ok, cool. The headings should be clear from that homepage, though. I'll give the theme reviewers a heads up about encountering more "add-ons" terminology.

**Comment by jvillalobos** [comment]
Could just be renamed to `New`, `Updates`, and `Review Log`. Keep it generic.

**Comment by eviljeff** [comment]
![screenshot 2018-04-13 16 52 58](https://user-images.githubusercontent.com/768592/38725873-2d23eaba-3f3b-11e8-85fb-d02148db959b.png)

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF59, Win10x64

[1] theme reviewers:
 
![image](https://user-images.githubusercontent.com/31961530/38805284-f63486be-417d-11e8-8b65-301701543e6f.png)
--
[2] legacy reviewers:

![image](https://user-images.githubusercontent.com/31961530/38805419-6c06a8e0-417e-11e8-96d9-da0d5b86720f.png)
--
[3] Admin reviewers:

![image](https://user-images.githubusercontent.com/31961530/38805439-78c3aa4c-417e-11e8-8c68-265739e40a25.png)
