### ISSUE TITLE
Restrict content reviewers from using add-on reviewer canned responses

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#8028]
Content reviewers are currently able to use code review canned responses when rejecting an extension. To help prevent confusion and potential slip ups, I'd like to restrict them to only being able to select content review related canned responses. 

The canned responses that apply to content review are: 
- Add-on not suitable for listing 
- Spam
- Acceptable Use Policy (which I think we wanted to retire?) 
- Trademark Violation 

Current list of options: 
![screen shot 2018-04-11 at 12 10 55 pm](https://user-images.githubusercontent.com/23342476/38638432-16e2bca4-3d83-11e8-88d3-3f0aab2dc83e.png)

cc: @jvillalobos, @wagnerand, @kewisch

**Comment by wagnerand** [comment]
Yes, that totally makes sense.

Although that might alter the scope of this issue a bit, I believe we could hit two birds with one stone here and that might actually make this easier to fix:

One of the things that have been cumbersome from the beginning for both developers and reviewers is how we have to *reject all versions* when we find a listing to be inappropriate.
The issue for developers is that they usually have to submit a new version to enable their listing (and thus unnecessarily ship an update to all existing users), even though in the majority of cases, there was an issue outside of the add-on file, as content-review checks the listing and not the add-on file.

My suggestion is that we implement a proper action "Reject listing" that does not unnecessarily mess with the files but just disables the listing. The upside is that we can assign different canned response to that new action, and make sure the other ones are not shown.

Why am I suggesting this? Because the canned responses shown are tied to the action you select. Unless we want to do any more hacks for the content-review page [1], we need to create a new action anyway, so we can tie those canned responses to it.

We could provide a simple button that re-enables the listing reviewers can click after they have confirmed that developers have made the requested changes.

I know this sounds like a bit more work in total, but before we discard this idea, I'd appreciate if we could confirm with @mat or @eviljeff whether this looks doable. Rejecting all versions has lead to confusion and complaints from developers in the past, so that should be fixed either way. I probably should have already filed an issue for it.

[1] This week I have resolved one of the hacks we introduced for content-reviewers because it back-fired. Another one that I am going to tackle is #8027.

**Comment by eviljeff** [comment]
From a code point of view, Add-ons are not approved, Files are.  So adding another property which controls the Add-on status would either be a significant change (if done properly) or add some nasty hacks elsewhere in codebase (if done in the easiest way).  E.g. we add another Addon status == everywhere in the code has to handle the extra status; we add another disabled property that determines the Add-on is rejected for content review == there are now disabled-by-the-user and disabled-by-admins and disabled-by-content-reviewers that have to behave the same in most cases but have to be special cased in a few others.

@wagnerand can you detail some examples where the content review finds something that doesn't require a new xpi being submitted?  @caitmuenster's examples of 
>    Add-on not suitable for listing
    Spam
    Acceptable Use Policy
    Trademark Violation

seem to all be cases where we'd not expect any follow-up, or would require code changes.  The changes coming this quarter to fetch most add-on metadata from an xpi, update the data with new versions, and disable devhub editing would mean most AMO data would require a new xpi.  If it's just something like privacy policy you wouldn't reject anyway, I assume.

**Comment by wagnerand** [comment]
> From a code point of view, Add-ons are not approved, Files are. So adding another property which controls the Add-on status would either be a significant change (if done properly) or add some nasty hacks elsewhere in codebase (if done in the easiest way).

A wild hope would be that maybe we would be able to get away with just re-using `ADDON_STATUS_INCOMPLETE`. Maybe not.

> @wagnerand can you detail some examples where the content review finds something that doesn't require a new xpi being submitted? @caitmuenster's examples of

Hah, I had a longish paragraph about that in my earlier comment which I removed because the whole comment was already quite long :)


> Add-on not suitable for listing
   Spam
   Acceptable Use Policy

For those, there is usually no follow-up possible or allowed.

> Trademark Violation

usually requires follow-up by the developer, which involves at least submitting a new version (and thus trigger another content-review) in order to remove the Mozilla trademark from the add-on name in the manifest.

**Comment by eviljeff** [comment]
> A wild hope would be that maybe we would be able to get away with just re-using ADDON_STATUS_INCOMPLETE. Maybe not.

Addon status will automatically update to the correct status if there's a change on the versions (there are many changes that trigger the update status method), unless it's set to `STATUS_DELETED` or `STATUS_DISABLED`.  So setting it to `STATUS_INCOMPLETE` is no guarantee it will stay unavailable.

This should be spun off into a separate issue really, as @caitmuenster's request is easily doable without adding a new disable listing feature.  With some example use cases where a new upload won't be needed.
