### ISSUE TITLE
When signing out of /developers/addons the user should land on DevHub homepage instead of AMO

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8071]
Follow up for #4562 

STR:

1. Log in to Developer Hub
2. Navigate to https://addons-dev.allizom.org/en-US/developers/addons
3. Sign out

Actual result:
User is redirected to AMO homepage when signing out of /developers/addons

Expected result:
User is redirected to DevHub homepage when signing out of /developers/addons

Notes:
reproduced on all AMO servers with FF59, Win10x64

![dev hub log out](https://user-images.githubusercontent.com/31961530/38918057-44bd0ffe-42f5-11e8-8258-cf5ad8710597.gif)

**Comment by AlexandraMoga** [comment]
@piyushmittal25 @EnTeQuAk I've verified this on AMO-dev but it seems that the issue is not fixed , or not on -dev yet? I'm still landing on AMO when signing out of /developers/addons.

**Comment by EnTeQuAk** [comment]
Indeed, that's because Jinja2 (and Django for that matter) doesn't allow overwriting blocks from includes. So that the block has to be around the actual include of `user_login` and we'll have to pass in some context to actually set a proper overwrite somehow. This might get a bit more tricky.

If you're up for it @piyushmittal25, please let us know. You may have to research that a bit and stumble through http://jinja.pocoo.org/docs/2.10/.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60, Win10x64. Logging out from a page set under /developers/ will redirect to DevHub homepage 

![devhub logout](https://user-images.githubusercontent.com/31961530/41456055-0316aa36-7088-11e8-904d-7f0046c36dd4.gif)
