### ISSUE TITLE
Unbroken strings in add-on name are causing layout issues on DevHub landing page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8166]
Split up from #6698 

STR:
1. Log in to Developer Hub - https://addons-dev.allizom.org/en-US/developers/
2. Submit a new add-on with a long unbroken name
3. After submission, go back to DevHub landing page

Actual result:
The addon name is not wrapped causing layout issues on the DevHub landing page

Expected result:
Unbroken add-on names should be wrapped on DevHub landing page

Notes
Reproduced on all AMO servers with FF59, Win10x64

![image](https://user-images.githubusercontent.com/31961530/39580865-d5b2665e-4ef2-11e8-842a-fbfc6d218044.png)

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @muffinresearch

**Comment by iamkhush** [comment]
Hey, I am interested to work on this. 
I have looked into this and it looks we can fix this with either using jinja truncate tag (http://jinja.pocoo.org/docs/2.10/templates/#truncate)  or using css.
Not sure whats the best way . Suggestions?

**Comment by muffinresearch** [comment]
@iamkhush CSS would be preferred in this case.

**Comment by AlexandraMoga** [comment]
@iamkhush this issue doesn't look completely fixed on my side. You can see that my view doesn't fully match the screenshot provided by you after the fix:
![image](https://user-images.githubusercontent.com/31961530/41019819-0553eaf0-6969-11e8-8e4e-82c44b7fa8c4.png)

**Comment by EnTeQuAk** [comment]
@iamkhush hey, do you have time to look into the other issue @AlexandraMoga just reported? Seems like the title is pushing the add-on metadata to the side.

Please us know if you have any questions.

**Comment by iamkhush** [comment]
@EnTeQuAk sure. I will take a look at it.
@AlexandraMoga I checked it on firefox and chrome . Which browser is this screenshot from?

**Comment by AlexandraMoga** [comment]
@iamkhush the screenshot is taken from FF 60.0.1, and I have the same view in Chrome.

**Comment by eviljeff** [comment]
From a bit of debugging I _think_ it's just due to the difference in length of text between "Created" and "Last Updated" - 76% is enough to allow the text in the `.DevHub-MyAddons-item-modified` span to not line wrap; because "Last Updated" is slightly longer it does wrap.

I can't establish why @iamkhush is seeing "Created" instead of "Last Updated" dates, but it's a side effect - and non-English locales may be longer too (e.g. German).

**Comment by iamkhush** [comment]
@eviljeff thanks for looking into it. 
I tested with some other solution. Instead of setting width for `.DevHub-MyAddons-item-details` I set width for `.DevHub-MyAddons-item-modified` . Curently I set this up to `210px` so that the date doesnt fall off to the next line. I am not sure about other languages though. But then it seems like a tough problem to crack.
Attached screen shot in the new PR  https://github.com/mozilla/addons-server/pull/8489

**Comment by AlexandraMoga** [comment]
The wrapping issue reported is now fixed. There are still some issues with the alignment when selecting several locales but I filed #8565 to track this separately. 
Verified on AMO -dev with FF60, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/41583670-dfbc52b0-73ad-11e8-9bc7-5006b9515dd9.png)
