### ISSUE TITLE
[Question] What happened to the Statistics API?

### ISSUE THREAD

**Issue by ghost** [mozilla/addons-server#8169]
### Describe the problem and steps to reproduce it:
I was about to work on a project which relies on the AMO Stats API. I saw sometime last week there was documentation for this API ([here's a Wayback Machine link to said documentation](https://web.archive.org/web/20170930213829/http://addons-server.readthedocs.io:80/en/latest/topics/api/stats.html)). When I checked this week, the Stats API seems to have been removed.

Just wondering if this change is permanent - I wasn't able to find anything that talked about the stats api being removed. Thanks!

**Comment by EnTeQuAk** [comment]
I removed the statistics API as part of https://github.com/mozilla/addons-server/issues/7991 because it was unused and hasn't been thought through when we originally implemented it.

While we're at it, what are you trying to solve with a statistics API? That might help thinking about another implementation in the future.

**Comment by eviljeff** [comment]
Going to close this for now as no answer from the reporter in almost a month.  We can re-open.
