### ISSUE TITLE
Compare link for reviewers doesn't show the proper diffs

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#8220]
### Describe the problem and steps to reproduce it:
Using the AMO "Compare link" for CardBook 28.8 : https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/950590...947955/ shows that the entire codebase has been changed. However, if you download manually submissions 950590 and 947955 and compare them using Beyond Compare, the changes are minimal. 

@kewisch had the same issue yesterday with https://reviewers.addons.mozilla.org/en-US/reviewers/review/enigmail on version 2.0.3.

Note that both are XUL add-ons for thunderbird. Maybe it's related.

### What happened?
The compare feature on AMO shows a result between versions that are different then downloading manually the versions and compare them with Beyond Compare.

### What did you expect to happen?
Compare link on AMO should give a similar results as Beyond Compare.

**Comment by wagnerand** [comment]
This is because for some weird reason, the file viewer can't "find" file id `947955`, see (https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/947955/ reporting 404).

I have seen this a couple of times lately, I know @EnTeQuAk has been looking into this.

**Comment by EnTeQuAk** [comment]
Also to confirm: This works fine after a few minutes (or hours) right?

**Comment by wagnerand** [comment]
I'm not sure.

**Comment by kewisch** [comment]
Same here, I reviewed enigmail about a week ago and still have the issue: https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/949849...922649/

**Comment by spoji** [comment]
Note that right now, I can't reproduce the issue anymore; https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/947955/ extract properly for me. The original issue (compare via https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/950590...947955/ ) is not there anymore on production.

**Comment by spoji** [comment]
@EnTeQuAk Now file id [950590](https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/950590/) is reporting 404, which is quite weird because this file was available when this bug was submitted 8 days ago. 

It feels like sometimes, when a new version is uploaded by the dev, the second last file id becomes unavailable.

**Comment by diox** [comment]
From IRC discussion:

Looking into the database/filesystem right away when someone sees the error for the first time would be useful to debug. But I noticed a few things that look fishy in the code:

https://github.com/mozilla/addons-server/blob/5777fe9ca061473121c5f3617619cdba3a8cfba5/src/olympia/files/views.py#L107 and https://github.com/mozilla/addons-server/blob/5777fe9ca061473121c5f3617619cdba3a8cfba5/src/olympia/files/views.py#L161 can trigger a 404 if `get_default()` returns an empty dict. It turns out that [it *can* return an empty dict when an `IOError` or `OSError` is raised in `get_files()`](https://github.com/mozilla/addons-server/blob/5777fe9ca061473121c5f3617619cdba3a8cfba5/src/olympia/files/templatetags/jinja_helpers.py#L302)... which swallows those errors.

Also, we [memoize](https://github.com/mozilla/addons-server/blob/5777fe9ca061473121c5f3617619cdba3a8cfba5/src/olympia/files/templatetags/jinja_helpers.py#L361) the results of `_get_files()`... This might be a red herring but worth keeping in mind.

The first thing to do will be to stop swallowing the `IOError` and `OSError`. If they are triggered for whatever reason, hiding them is not going to help, IMHO. Let's just raise them for now, that should help us figure out what's happening.

**Comment by spoji** [comment]
I'll poke one of you (diox / EnTeQuAk) on IRC next time I get this problem so you can check this live.

**Comment by EnTeQuAk** [comment]
Short status update: We added more stuff so that exceptions should be more visible but they still aren't. Kibana is empty and Sentry too, so we're not tending towards less of errors that are ignored somewhere (though also investigating) towards debugging potential race-conditions / concurrency problems.

Stay tuned

**Comment by EnTeQuAk** [comment]
So, we published more things that should potentially help to fix or to mitigate the problem.

It'd be great if you could look out for more cases of where you receive either an unexpected 404, wrongfully changed/unchanged files etc and report them as soon as you see anything.

**Comment by spoji** [comment]
@EnTeQuAk With a new version of CardBook pushed to AMO by the dev today, I now got a different result now when using compare  https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/976451...972478/ . 

I'm getting a "Oops! We had an error." message.

**Comment by EnTeQuAk** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4374099/

And https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4374098/ is very much related / the same.

So, from what I can see it feels like some files get deleted (or… marked as deleted) mid-extraction / reading which then results in this IOError.

**Comment by wagnerand** [comment]
The file exists on the filesystem in the expected place.

```
$ ll cardbook.properties
... Jun  4 12:18 cardbook.properties
```

**Comment by EnTeQuAk** [comment]
Then maybe we're still talking about some kind of race-condition which I thought all-along and which would be super-hard to prove. We do have a lock-file and we - in theory - verify that the files exist on disk after extraction, which at the point of the traceback already happened. This is all quite confusing or at least unclear currently.

**Comment by EnTeQuAk** [comment]
![screenshot from 2018-06-04 17-51-55](https://user-images.githubusercontent.com/139033/40928129-de23d150-6820-11e8-8f5b-768a12095013.png)

**Comment by spoji** [comment]
Added notes from today's conversation on #amo : 

I've received a HTTP 400 error for CardBoook via https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/980734...976451/ done at 2018-06-07 @ 10:10AM EDT

Note that the dev just updated the new version on AMO a few minutes ago. I've just received an email that a new version is available for review.

**Comment by spoji** [comment]
More logs!

Got a 504 (took too long to respond) on ublock-origin via https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/985780...968516/

This was at 2018-06-13 9:26AM PST.

**Comment by EnTeQuAk** [comment]
We're working on a ops-side solution to this: https://bugzilla.mozilla.org/show_bug.cgi?id=1468709

**Comment by EnTeQuAk** [comment]
I'm closing this issue for now.

We deployed the solution mentioned in [bug 1468709](bugzilla.mozilla.org/show_bug.cgi?id=1468709) to production yesterday and we hope that this will fix extraction problems once and for all.

There may be some degraded extraction-performance but even that doesn't seem to be the case from what I see.

Please feel free to report any further issues that you see. Either by commenting on this issue or by opening a new one.
