### ISSUE TITLE
Delete the user image file when an account is deleted.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#8222]
When a user account is deleted we should delete any image file rather than just delete the db reference to it.

We should also consider how to clean-up orphaned images if they're not already being reaped at some point.

Needs to be in the 2018.05.24 push at the latest.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Hi Chris, I verified this issue on AMO dev and AMO stage with FF60 (Win10) like this:
- signed in using a new account (on dev - cephicloph@2anom.com, on stage - anna.banc34@gmail.com) and I went to Edit profile and added a profile photo, then from Edit profile page I deleted the account.
- to check if the profile picture was deleted I signed back (because it allows you to, a known issue) and went on the View profile and Edit profile pages - the previous uploaded photo before deleting the account is no longer available,  just the placeholder is displayed.

Problem is that this worked on stage too and it is Monday so I'm thinking if my verification is correct or there is another way to check this.
Please let me know if it's alright.

**Comment by EnTeQuAk** [comment]
> to check if the profile picture was deleted I signed back (because it allows you to, a known issue) 

This should create a completely new account for you, we're not also clearing the link to FxA. So it's expected that your profile photo isn't there anymore.

What you can do

* Create an account
* Upload profile picture
* View the raw profile picture in the browser (right-click on it, "view image")
* delete account
* make sure the previously opened link doesn't work anymore and 404s. This could take a few minutes but should be fairly immediate.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk  Hi Chris, I made one test following the above steps and I managed to get 404 but not on the same profile where I deleted the account (pasted the link in a new profile, also if I send the link to someone else it's a 404) This is it https://addons-dev-cdn.allizom.org/user-media/userpics/10/10641/10641629.png?modified=1526482992
Same in Chrome or Edge.
![404notfound](https://user-images.githubusercontent.com/33448286/40165036-b6fa2748-59c3-11e8-9195-7135c8363c46.png)

This should be alright. Unfortunately I cannot make some further testing today because I am blocked right now by https://github.com/mozilla/addons-server/issues/8281
I'm marking this verified fixed on AMO dev with FF60(Win10).
