### ISSUE TITLE
Featured Extensions `src` not being tracked in all cases 

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#8263]
Go to the AMO homepage. Content programming changes frequently, but typically we have a "Featured extensions" shelf somewhere on the page. 

If you find it, click one of the featured extensions in the module display. For example, I see Enhancer for YouTube, I click it, I go to its detail page, and the URL looks like so:

https://addons.mozilla.org/firefox/addon/enhancer-for-youtube/?src=featured

Now, go back to the homepage. This time, instead of clicking on an individual featured extension in the shelf, click the "See more featured extensions" link on the far right of the module. Find Enhancer for YouTube and click thru to its detail page. The URL will look like so:

https://addons.mozilla.org/firefox/addon/enhancer-for-youtube/?src=search

It appears we're tracking the discovery flow differently (featured vs. search) when in truth they both should be the same -- src=featured

It will be difficult to measure the effectiveness of AMO's primary "Featured Extensions" collection if portions of its effect are measured as "search" results.

**Comment by jvillalobos** [comment]
When you click on "See more featured extensions", you land on a search page, which is why the `src` changes to `search`.

Would it make sense to use the `featured` value whenever the search page has the "featured only" checkbox selected?

While testing this, I also noticed that if you go directly to the featured add-ons collection and click on an entry, the `src` is `collection`, so we might want to special-case the `src` from that collection as well.

**Comment by devaneymoz** [comment]
I think it does make sense to use the "featured" value whenever the search page has the "featured only" checkbox selected, since that's effectively taking the same action as navigating to the featured collection.

**Comment by muffinresearch** [comment]
@devaneymoz if you could file these issues on mozilla/addons-frontend in future it would be handy since that repo is where changes would need to be made to `src` params.

**Comment by diox** [comment]
Re-filed on the frontend : https://github.com/mozilla/addons-frontend/issues/5475
