### ISSUE TITLE
Collection add-ons list API returns inaccurate results when sorting

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#8354]
I'm working on a feature to sort the add-ons in a collection for https://github.com/mozilla/addons-frontend/issues/3991 and I have found that the results I get back are problematic in two ways:

1. They don't seem to be sorted using the sort sequence I requested. I tried both `name` and `popularity` and both seem to return results in a random order.
2. I am getting duplicates for a number of add-ons. I.e., I get 5 results in the result set for a particular add-on.

Both these issues are blocking the ability to implement https://github.com/mozilla/addons-frontend/issues/3991.

**Comment by diox** [comment]
To sort by name using the database I think we have to use `order_by_translation`, just sorting on `addon__name__localized_string` won't cut it. No idea about what's going on with the rest, but it may have to do with the way to tables are joined together.

**Comment by AlexandraMoga** [comment]
I've verified the available collection sort options on AMO -dev and here are the results:
- _sort=name_ - returns the add-ons in a collection sorted by their names. Localized add-on names are also sorted according to the `lang` parameter sent in the URL:
`https://addons-dev.allizom.org/api/v3/accounts/account/AlexandraMoga1/collections/kelpie/addons/?sort=name&lang=de`
- _sort=popularity_ - due to the lack of data on -dev, this functionality could not be fully tested.
- _sort=added_ - lists add-on based on the date they were added to the collection, in an ascending order
`https://addons-dev.allizom.org/api/v3/accounts/account/AlexandraMoga1/collections/kelpie/addons/?sort=added`

Marking issue as verified fixed on AMO-dev
