### ISSUE TITLE
Stop computing average_daily_downloads

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8367]
We compute both `average_daily_users` and `average_daily_downloads` for every add-on. There is a big difference however: only the former is computed on the last couple of weeks. `average_daily_downloads` is computed over the entire time the add-on has existed, making it largely irrelevant. Unsurprisingly, it's not exposed anywhere in the site except the admin page.

Let's get rid of it?

**Comment by diox** [comment]
AFAIK, no. Look at adblock-plus for instance:
https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/

Nowhere is the /total/ average number of daily downloads displayed. Even if you select a custom range and go far in the past (in which case the data would be recalculated anyway), we only display the total number of downloads and the average number of daily users, but not the average number of daily downloads.

**Comment by championshuttler** [comment]
I would like to work on it :)

**Comment by AlexandraMoga** [comment]
I've checked the Addon admin pages and the `average_daily_downloads` filed is no longer displayed in the Stats section. 

![image](https://user-images.githubusercontent.com/31961530/41354770-7abd63ec-6f28-11e8-9fec-ff364e623342.png)

Since this seems to be the only affected part that can be verified, I'm going to mark this issue as verified fixed on AMO -dev with FF60, Win10x64
