### ISSUE TITLE
Allow the ability, via API, to specify a langpack is not appropriate for android

### ISSUE THREAD

**Issue by Callek** [mozilla/addons-server#8381]
c.f. https://bugzilla.mozilla.org/show_bug.cgi?id=1462689

This would ideally be part of the upload/signing API but is acceptable seperately. The underlying issue is that when release engineering uploads Language Packs AMO is then declaring the language packs as compatible with Android.

I'm told the compat flag is per-upload (version) so is not feasable to do via web UX every release.

**Comment by muffinresearch** [comment]
@diox would it be feasible to add something to the signing API to make this possible?

**Comment by diox** [comment]
It's feasible, but not trivial at all, we are going to bump into the longstanding issues around platforms vs applications that we have in the codebase.

- The signing API currently [hardcodes](https://github.com/mozilla/addons-server/blob/ca259238f23be0dc2d85742d3921a1800aea1ac0/src/olympia/devhub/tasks.py#L123) platform compatibility as `PLATFORM_ALL`, causing every upload going through it to be compatible with all platforms.

- In addition addons-server has this notion of applications, and confusingly, Firefox for Android is an application separate from Firefox, but is also a platform. Because webextensions don't specify in their manifest what app they are compatible with, we [set any webextension as compatible with both Firefox and Firefox for Android](https://github.com/mozilla/addons-server/blob/ca259238f23be0dc2d85742d3921a1800aea1ac0/src/olympia/files/utils.py#L407).

Both issues need to be addressed to fix this at upload time. It's all a matter of being able to propagate the information down to the relevant methods, and keep the two consistent with each other.

This also affects devhub itself, it's been notoriously difficult for developers to change this in devhub as well. See these bugs (some might be dupes):
- [No way to upload/create a WebExtension without Android support](https://github.com/mozilla/addons/issues/348) (which is causing [Add-on is Android compatible but does not have an Android install file](https://github.com/mozilla/addons-server/issues/6576))
- [Change submission upload step to allow application selection](https://github.com/mozilla/addons-server/issues/6067)
-[Cannot set Desktop only]( https://github.com/mozilla/addons-server/issues/4868) and [User is forced to select an option from Android categories for not compatible WebExtensions with Android](https://github.com/mozilla/addons-server/issues/2830)
- [Compatibility isn´t updated if you remove "android" from the addons listing](https://github.com/mozilla/addons-server/issues/2572)

**Comment by Callek** [comment]
I'm ok with a temporary work-around API that allows me to set a version as "not for Android" that I call seperate to (and sometime very shortly after) the version upload.

**Comment by diox** [comment]
I'd prefer to avoid that. 

It's currently possible through devhub but as the last issue I linked to (https://github.com/mozilla/addons-server/issues/2572) mentions, it doesn't entirely work (*), so I'd prefer the data to be correct from the beginning instead of hacking around it after the fact. 

(*) I haven't investigated into why yet - on top of the platforms vs applications I mention above, there are a few other things that come into play: addons-server weird generic caching layer, the specific cache for application compatibility, and search indexing.

**Comment by diox** [comment]
We discussed this further on IRC. Ideally, there would be something in the manifest indicating what applications the add-on is compatible with but alas, there isn't (and Firefox does not like arbitrary properties it doesn't know about).

However, langpacks are currently completely not working in Firefox for Android. There are some plans to support similar functionality in the future, but nothing is decided yet, we can decide that they will have to take a different form, allowing us to identify them separately from desktop langpacks.

That means I can add something in the code that generates the version to set langpacks as compatible with desktop only, fixing the issue.

**Comment by AlexandraMoga** [comment]
@diox I could use some more details to better understand what changed exactly with this patch.
So far, I've seen that in the submission steps, the 'Android' platform checkbox is disabled but I assume there should be more than that.
![image](https://user-images.githubusercontent.com/31961530/40917118-c781026c-680a-11e8-981e-8bd9aedf816a.png)

**Comment by diox** [comment]
@AlexandraMoga : that's almost it, except that:
- Submission should work after that, and the add-on should not be marked as compatible with Firefox for Android
- It should also apply if the language pack is uploaded through the API ( the add-on should not be marked as compatible with Firefox for Android - previously it was)
- Submission of other types of add-ons should work as it did previously.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO -dev with FF60, Win10x64 and Android 7.0

- language packs can be submitted without Android compatibility, result also visible in dev hub (also applicable to new versions for older lang packs)
- other add-on types can be submitted with Android compatibility
- a language pack submitted through the API will also be set as incompatible with Android
- Android incompatibility is also specified on the language pack details page

![image](https://user-images.githubusercontent.com/31961530/40972881-da5c0e66-68ca-11e8-97de-5e834581b7ad.png)

![image](https://user-images.githubusercontent.com/31961530/40972889-e1c5f446-68ca-11e8-8584-a52dd2fa9e11.png)
