### ISSUE TITLE
Do not allow administrators to maintain collections

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#8479]
The collections API currently gives anyone with the `Collections:Edit` permission access to edit a collection, delete a collection and maintain the add-ons in a collection. As per our conversation about privileged APIs, nobody other than the owner, or a collaborator, should be able to maintain a collection via the API.

The issue of collaborators can be handled separately, but for now we should update the API to disallow access to users with the `Collections:Edit` permission who are not the collection's owner.

**Comment by eviljeff** [comment]
I think we need to work out what to do about collaborators first -  one of the suggestions was to (effectively) drop a list of collaborators per collection in favour of a permission (e.g. `Collections:Edit`) so frontend could use that permission as a way of seeing if the collection could be edited and show the appropriate edit button.  So that would be the opposite change for editing (could still drop delete access though).

**Comment by eviljeff** [comment]
@diox is this a dupe now?

**Comment by diox** [comment]
Yeah, dupe of https://github.com/mozilla/addons-server/issues/8509
