### ISSUE TITLE
Collection name and description display different values specific to the locale used when the fields were edited

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8490]
STR:

1. Log in to AMO -dev 
2. Go to My Collections and select one of your collections to view its details page
3. Switch to a different locale
4. Edit the collection name and description
5. Switch back to the previous locale

Actual result:
The updated collection name and description are not displayed

Expected result:
Updated collection name and description should be displayed regardless of the locale used when the fields are edited

Notes:
- a localization issue (#https://github.com/mozilla/addons-frontend/issues/4793) was was also reported for the legacy edit collection page, currently in use
- reproduced on AMO -dev with FF60, WIn10x64

![coll loc](https://user-images.githubusercontent.com/31961530/41231445-c27ef432-6d8b-11e8-99d0-a5d383c504dc.gif)

**Comment by EnTeQuAk** [comment]
I'd say this is working as expected? It might not be completely obvious that you're editing the name for German only in this case so some helper-message or so might help the user being aware of this.

**Comment by diox** [comment]
In devhub we display a widget allowing you to see / edit localized fields in all languages. The API was designed for this as well, returning all translations if you don't pass a `lang` parameter. So the frontend can implement something like this.

In any case, it's a frontend bug. @AlexandraMoga can you refile it there? The bug is really that the frontend should let you know which locale you're editing and possibly let you see/edit other locales at the same time.
