### ISSUE TITLE
Some extension localizations are not imported in AMO

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8516]
STR:

1. Log in to AMO and submit and extension with a significant number of localizations (see attached .xpi)
2. After the extension is approved, compare the number of localizations imported in AMO with the number of localization files from the package

Actual result:
There are 37 localizations imported in AMO, while the package contains 56 files

Expected result:
AMO should support more locales available for an extension

Notes:
- for this extension example the following locales are missing: `bn, cv, et, eo, fil, fy, gl, hi, hr, kk, kn, lt, lv, ml, mr, nb, no, ta, sr`. A good part of these locales are not available on AMO, but there a few which are supported but haven't been imported: `'fy'` as `'fy-NL'`, `'nb'` as `'nb-NO'`, `'no'` as `'nn-NO'` 
- extension example: 
[ext.localizations.zip](https://github.com/mozilla/addons-server/files/2101455/ext.localizations.zip)

**Comment by EnTeQuAk** [comment]
This is interesting, I'd be more interested to see if that works
in Firefox?
Because we're using more or less all the languages that Firefox itself
is localised in and don't support anything on top of it because we're
unable to show them anyway because we can't show our own content -
strings, numbers, date/time formatting etc - in languages that neither
Django, Babel (library were using for formatting dates/times and
numbers) or especially Firefoy support.
Do you have any insight in that?


On Thu, Jun 14, 2018, at 10:44 AM, Alexandra Gal-Moga wrote:
> STR:


>  1. Log in to AMO and submit and extension with a significant number
>     of localizations (see attached .xpi)
>  2. After the extension is approved, compare the number of
>     localizations imported in AMO with the number of localization
>     files from the package> Actual result:
>  There are 37 localizations imported in AMO, while the package
>  contains 56 files> Expected result:
>  AMO should support more locales available for an extension


> Notes:


>  * for this extension example the following locales are missing: bn,
>    cv, et, eo, fil, fy, gl, hi, hr, kk, kn, lt, lv, ml, mr, nb, no,
>    ta, sr. A good part of these locales are not available on AMO, but
>    there a few which are supported but haven't been imported: 'fy' as
>    'fy-NL', 'nb' as 'nb-NO', 'no' as 'nn-NO'
>  * extension example: ext.localizations.zip[1]> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].
Links:

  1. https://github.com/mozilla/addons-server/files/2101455/ext.localizations.zip
  2. https://github.com/mozilla/addons-server/issues/8516

**Comment by EnTeQuAk** [comment]
I assign this to me to do a bit more research on this, not necessarily to fix it.

**Comment by EnTeQuAk** [comment]
Haven't looked at this too much in detail but given that we removed django-product-details support recently adding new locales should fairly simple to do.

I'm unassigning myself though.
