### ISSUE TITLE
Use memcached in our unittests by default

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8602]
We are using LocMemCache in our unittests, potentially for performance reasons. The problem is that we won't run into any of memcached problems, e.g a max cache-key length of 250 characters and others. (e.g https://github.com/mozilla/addons-server/issues/8598)

Let's use memcached by default.

**Comment by diox** [comment]
That would also be good to find issues like https://github.com/linsomniac/python-memcached/issues/79 before they hit dev/stage/prod.

In fact, note that this particular python-memcached issue has been fixed recently, so when we move our tests to memcached, it'll be a good occasion to also stop pinning version 1.53 (1.59 has the fix for the issue linked above)

**Comment by EnTeQuAk** [comment]
Indeed.

I have a working branch for this, the only thing that needs actual work is rewriting our throttling-tests to work with this and avoid them to wait for a minute :)

With a bit of luck I'm able to finish this by tomorrow.

**Comment by diox** [comment]
Bonus point if you write a test that would fail with the broken version of python-memcached to prove that the issue is fixed :)
