### ISSUE TITLE
"Oops..." page returned when accessing user profile page in legacy site

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#8605]
Steps to reproduce:
1.Go to legacy AMO-dev site and login with some valid credentials
2.Go to  "My profile" page

Expected results:
Profile page is displayed without issues

Actual results:
"Oops..." page is displayed

Notes : 
Not reproducible on the new AMO site

**Comment by eviljeff** [comment]
This was due to an add-on* that had an incorrect type (type=theme, which is a LWT, and the addon was actually an extension).  Given it's -dev I believe it was someone (with at least `Addon:Edit` permission) tinkering with the type in devhub or django admin.

I changed the type of the add-on to `extension` and the profile page worked again.

*https://addons-dev.allizom.org/firefox/addon/wharwhal-groadge-snaillam/
