### ISSUE TITLE
Add-ons deleted from featured-personas collection are not removed from AMO featured themes

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8673]
STR:

1. Log in to AMO with an admin user
2. Open the featured-personas collection and remove a theme from the list - https://addons.allizom.org/en-US/firefox/collections/mozilla/featured-personas/edit/#addons-edit
3. Save the updates
4. Go back to AMO homepage and click on the More featured themes shelf
5. Check if the theme deleted from the collection is also removed from AMO

Actual result:
The theme deleted from featured-personas collection is not removed from AMO featured themes

Expected result:
Theme deleted from the featured-personas collection is also removed from AMO featured themes

Notes:
- reproduced on all AMO servers with FF60, Win10x64

![delete from featured](https://user-images.githubusercontent.com/31961530/41978523-bb703434-7a2a-11e8-8bb7-6c21b249317f.gif)

**Comment by diox** [comment]
Pretty sure this is because the featured cache is not fully cleared when an add-on is removed from a featured collection. We do force an add-on re-index, but get the old featured cache value.

As seen here: https://github.com/mozilla/addons-server/blob/31be530b52db9fd49203b49543ff32013ff13208/src/olympia/bandwagon/models.py#L361

Clearing the featured cache for just `None`, `None` is not enough to clear it in all app/locale combinations.

**Comment by diox** [comment]
This is annoying but has always been the case.

**Comment by AlexandraMoga** [comment]
I didn't reproduce the issue anymore when deleting a theme from the featured-personas collection in the frontend.
