### ISSUE TITLE
Stuck with Add-on Distribution Agreement

### ISSUE THREAD

**Issue by xeonchen** [mozilla/addons-server#8696]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
1. Login into AMO, try to submit a new add-on
1. Agree Add-on Distribution Agreement by checking all check boxes and submit

### What happened?
Redirected to Add-on Distribution Agreement again, check boxes are unchecked.

### What did you expect to happen?
Start to fill some info about the new add-on

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Logout and re-login, then it works.

**Comment by diox** [comment]
I reproduced this with a new account in prod :(

**Comment by diox** [comment]
As reported, logout and re-login works, but also just waiting for a bit and retrying. Replication lag in datadog is looking fine, but even if it wasn't we do database pinning through a cookie, so that should save us anyway... 

Also, I can't reproduce locally... Maybe cache-machine related?

**Comment by jasonthomas** [comment]
This should now be resolved. 

Our redis cluster failed over due to some instance issues and our configuration does not account for failover. Since we use cache machine redis backend to manage the flush lists new flush entries were not being entered and so we weren't invalidating cache. Eventually the cached object in memcached would be evicted and it would recover and that is why we were seeing weird behavior.

**Comment by diox** [comment]
Verified by myself and jason after it was fixed.

Worth noting that we're planning to get rid of cache-machine entirely next week. That's https://github.com/mozilla/addons-server/issues/7743
