### ISSUE TITLE
Theme artist or Add-on developer should be displayed on the user's info card only after the add-on or theme is approved

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8726]
transferring https://github.com/mozilla/addons-frontend/issues/5457

STR:
1.  Create a new account and sign in
2.  Submit an extension and approve it - notice that before approving it the Add-on developer is already displayed on the card but the card is public only after the first add-on or theme is approved
3.  Submit a lightweight theme for the new account then with an admin account reject it
4.  Go to View my profile page and sign out

Expected result:
Theme artist is not available on the info card because the card does not display a theme.

Actual result:
Theme artist is displayed on the card which is public since it contains a submitted add-on.

Notes:
This issue is reproducible on AMO dev with FF60(Win10).

![issue555](https://user-images.githubusercontent.com/33448286/42205127-35c2b11e-7eac-11e8-8b3c-dd7d60a95c03.png)

**Comment by diox** [comment]
Code for `is_artist` (and `is_developer` / `is_addon_developer`) changed in a3b9bcd009e but the problem already existed before.

Do we really care? Need to be careful about changing the definition of this property (and the other `is_*`) because they could be used to determine what the user itself will see elsewhere like in devhub.
