### ISSUE TITLE
Allow translations of localised API fields to be deleted

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8816]
Our current API implementation has trouble clearing translations of localised fields:
* if a field is required then an update that sends a translation locale=None is treated as an invalid input.
* if the field isn't required then just sending None (i.e. a flat string style input, but None) is ignored by DRF (will be fixed in  /v4/ see #8794)
* you can set a translation for the default_locale of the object to be None but you shouldn't be able to if there are other translations in other locales (or ever if it's a required field)

From testing during #8794 it's not clear if sending locale=None to delete locales is working properly at all, even in the general case (the `Translation` objects still exist, for example).  But needs more investigation.

**Comment by eviljeff** [comment]
I have a seemingly working patch that'll I'll link to for reference: https://github.com/eviljeff/olympia/tree/8816-deletable-translated-field-l10n (it needs some more tests to prove it handles all scenarios around required fields).

However, if we're dropping the remaining few places (see #8701) where we set a localised values in the API then we don't need this issue to be fixed until we add new APIs that do set localised values again.  So I'm unassigning myself and dropping this to p5.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I've tested this with POST create, new version and PATCH addon details, addon versions -> because they all accept localized fields.

- I could send "description":{"en-US":"testing this and that", "ro":null} but for {"en-US":null, "ro":"test"} it will throw an error
 "A value in the default locale of \"en-US\" is required if other translations are set."
- setting "ro":null will delete the translations (into PATCH requests). 
- required fields cannot be null -> resolved by https://github.com/mozilla/addons-server/issues/19055

- I tried to cover testing with all localized fields for all the possible requests. The only thing noticed today is not an API problem but a dev hub issue https://github.com/mozilla/addons-server/issues/19205. The other was https://github.com/mozilla/addons-server/issues/19196
