### ISSUE TITLE
Previews is missing from disco results so a static theme image can't be displayed

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-server#8863]
### Describe the problem and steps to reproduce it:
It seems that the previews field is missing from disco results so there is no static theme image to show when it's this type. Can this be added?

![Alt text](https://monosnap.com/image/3pKYcBuiEgSzsjwJRHGMNrRgGex98Q.png)

### What did you expect to happen?
to have this field available if possible : )

**Comment by AlexandraMoga** [comment]
I've verified the discovery API endpoint on -dev and theme previews with all sizes are returned in the response.
The image URLs are also rendered correctly. 

`https://addons-dev.allizom.org/api/v4/discovery/`

![image](https://user-images.githubusercontent.com/31961530/42759146-98b51cd2-890e-11e8-81a8-0f45c8e5dd9a.png)

@eviljeff the sample theme set in discopane for testing purpose will still have no preview. Should this sample theme be reset in order to observe the changes in discopane as well?

**Comment by AlexandraMoga** [comment]
The discopane part will be fixed by https://github.com/mozilla/addons-frontend/issues/5568

Marking this issue as verified fixed on AMO -dev
