### ISSUE TITLE
Add UTM parameter to "heading" links returned by the discovery API endpoint

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#8884]
xref: https://github.com/mozilla/addons-frontend/issues/5346

---

Link to add-on listing on each Disco Pane entry:

- utm_source=discovery.addons.mozilla.org
- utm_medium=firefox-browser
- utm_content=discopane-entry-link
- src=api (not an UTM parameter, but it's used internally by AMO to track downloads in the stats dashboards for developers; looks like we dropped it at some point)

**Comment by vcarciu** [comment]
Verified as fixed in AMO-dev : 
![utm](https://user-images.githubusercontent.com/1583842/47094439-e14ec100-d233-11e8-9212-570e2f175801.png)

We observed that the utm_source is discovery.addons.mozilla.org even if we are on AMO-dev disco pane , but we will log a different issue on this since it will not affect the prod after push.
