### ISSUE TITLE
Update help text to show that "by [author]" is appended to the addon name.

### ISSUE THREAD

**Issue by feer56** [mozilla/addons-server#8890]
This is for the Disco-TAAR shield study discovery item. @muffinresearch recommended me to file this issue. 

### Describe the problem and steps to reproduce it:
Include a 'Custom addon name' for a discovery item. 

### What happened?
In the preview, the "by [author]" shows up beside the custom add-on name within the subheading

Example:
Custom addon name: Privacy Badger by EFF
Custom heading: Stop sneaky trackers {start_sub_heading}with {addon_name}{end_sub_heading}
Preview: Stop sneaky trackers with Privacy Badger by EFF by EFF Technologists

### What did you expect to happen?
The add-on name to not be displayed again within the subheading. 
The preview for the above example should've returned: Stop sneaky trackers with Privacy Badger by EFF

**Comment by muffinresearch** [comment]
@eviljeff since mat is out this week would you have a chance to take a look at this, it will help a lot with getting data into the admin for the upcoming TAAR changes.

**Comment by muffinresearch** [comment]
P1 only in the sense that if it's a simple change and we can get it in this week's push that would be appreciated.

**Comment by muffinresearch** [comment]
Looking at this further this isn't a bug per se, the "by [author]" part is automatically added and you shouldn't add it to the custom addon name. This is because the addon author is not translatable. The "by" string is translated but this is handled as the link is built up.

The fix to this bug is to improve the help text to make this clearer.

**Comment by feer56** [comment]
From what I understand, based off of a previous discussion with Scott and the PRD, unless something has changed since, the author's name would not be pulled in and will be manually entered.

**Comment by muffinresearch** [comment]
> From what I understand, based off of a previous discussion with Scott and the PRD, unless something has changed since, the author's name would not be pulled in and will be manually entered.

That's not the case - we're following the existing data conversions used on the disco pane. 

We'll need all the "by [author]" strings removed from the custom add-on name since that content is *not translated* as noted in the help text in the admin so it can't contain any content that needs to be localized e.g. the word "by".
