### ISSUE TITLE
Add an `exclude_collections` query parameter to the autocomplete endpoint

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#8925]
In order to support https://github.com/mozilla/addons-frontend/issues/5126, which will exclude add-ons from the autocomplete box if they are already present in a collection, we need a way to tell the server to exclude all add-ons in a particular collection. We cannot use `exclude_addons` for this because we only ever have a single page of add-ons for a given collection. 

I suppose another possibility would be to enhance the collection detail response to include a list of all add-on ids in the collection, but that would be unnecessary information most of the time, which we'd just end up passing from the server to the client in order to pass it back to the server via `exclude_addons`. This is why adding a new query param for `exclude_collections` seems like a better approach.

**Comment by diox** [comment]
That seems difficult, for 2 reasons:
- We don't index what collections add-ons are a part of (it might be quite costly to do so, add-ons can be part of a large number of collections, having to re-index add-ons each time they get added/removed from one would be annoying)
- The search endpoint works without any authentication, it doesn't care about the user at all

**Comment by bobsilverberg** [comment]
> That seems difficult, for 2 reasons:
> - We don't index what collections add-ons are a part of (it might be quite costly to do so, add-ons can be part of a large number of collections, having to re-index add-ons each time they get added/removed from one would be annoying)

Do we have to re-index add-ons for this? Can we not just look at the collection data to see which add-ons to exclude?

> - The search endpoint works without any authentication, it doesn't care about the user at all. **Edit:** I was thinking about auth because it might leak information about a private collection. Not sure if we care about that since you'd need the collection id in the first place...

There is no longer such a thing as a private collection, so this may no longer be relevant.

If #1 is considered too much of an issue, do you have any other suggestions for how we can accomplish what we'd like to do?

**Comment by diox** [comment]
> Do we have to re-index add-ons for this? Can we not just look at the collection data to see which add-ons to exclude?

We could look up the collection add-ons before making the search query, and then exclude the add-ons, yeah. I'm not a super fan of that because that makes the search endpoint depend on the database, which is something we tried very hard not to do cause that slows us down... What do you think @EnTeQuAk @eviljeff ?

> There is no longer such a thing as a private collection, so this may no longer be relevant.

Technically, collections are still somewhat private if you don't share the URL publicly, right?

BTW: is this for the search endpoint, the autocomplete endpoint, or both?

**Comment by bobsilverberg** [comment]
> BTW: is this for the search endpoint, the autocomplete endpoint, or both?

Currently we only need it for the autocomplete endpoint, but I was under the impression that they're both based on the same code. You're right though, I should have specified that it was for autocomplete.

**Comment by diox** [comment]
It's currently the same code underneath, yes. Might not be in the future though (though with requirements like this, it's more and more likely to stay the same), so that's why I wanted to know.

**Comment by eviljeff** [comment]
I'm -1 for this. The autocomplete endpoint is supposed to be super fast and
low impact on resources and it does this by being pure Elasticsearch. As
collections aren't in ES we'd have to change it to do a db query instead.

Storing collection membership per add-on on ES seems not viable - imagine
how many collections AdblockPlus is on. And yeah, the reindexing isn't a
no-op either each time an add-on is added/removed to/from a collection.

Btw, we _do_ still have private collections as it stands. You just can't
make any new collections private because it's deprecated.

My vote would just be to get 50 add-ons per page and use them. Collections
with large numbers of add-ons in them aren't worth supporting, imo.

**Comment by diox** [comment]
Yeah, @bobsilverberg maybe you can increase the page size just for when you're editing a collection, so that you do have pretty much all the add-ons ids and can exclude them ? I don't think it's terrible to show add-ons already part of the collection in autocomplete results if the collection is super large.

**Comment by bobsilverberg** [comment]
Fair enough, this sounds like a reasonable approach. @jvillalobos @pwalm Do you have any issues with changing the "Edit collection" screen to display 50 add-ons by default, and only using those 50 add-ons displayed to determine which add-ons to *not* include in the autocomplete results of the select box that's used for adding an add-on to the collection?

**Comment by kumar303** [comment]
Some other options:
- We could just not do this UI feature 😁 I think the error message you currently get is pretty clear.
- You could *totally* fetch all pages and get all collection add-ons because [we have a helper](https://github.com/mozilla/addons-frontend/blob/0369a39b0a4f7a8fff06f8aeb379292c47f91ffc/src/core/api/index.js#L301)! Not saying that's a good idea, just an idea.

**Comment by bobsilverberg** [comment]
> You could totally fetch all pages and get all collection add-ons because we have a helper! Not saying that's a good idea, just an idea.

I am aware of the helper, but didn't think it was a good idea to do that.

**Comment by eviljeff** [comment]
we already support requesting up to 50 addons per collection so it's a wontfix on the server side.  mozilla/addons-frontend#5126 is still open to increase it to 50 there.

**Comment by pwalm** [comment]
@bobsilverberg No issues here
