### ISSUE TITLE
Bug in Thunderbird Add Ons

### ISSUE THREAD

**Issue by subh-asish** [mozilla/addons-server#8929]
When I am trying to click on any themes from thunderbird the link is redirecting and opening in the browser and when I try to install it says not found.

**Comment by diox** [comment]
Hi,

I can reproduce this, but thunderbird add-ons have moved to https://github.com/thundernest/addons-server so it's best to re-file that issue there.

(I'm not sure where that issue is coming from, it might not be a recent regression - it seems that in the legacy discovery pane we link to add-ons with their IDs, and not their slugs, and somehow on addons.thunderbird.net that fails, at least for the ones I tried - like https://addons.thunderbird.net/en-US/thunderbird/addon/10900/ should work and redirect to https://addons.thunderbird.net/en-US/thunderbird/addon/thunderbird-suave/ but doesn't)
