### ISSUE TITLE
Empty version notes for Tab Counter Plus

### ISSUE THREAD

**Issue by Loirooriol** [mozilla/addons-server#8950]
### Describe the problem and steps to reproduce it:
Go to https://addons.mozilla.org/en-US/firefox/addon/tab-counter-plus/versions/2.5/updateinfo/

This is the URL that about:addons fetches when Tab Counter Plus is updated and you click "Show Release Notes"

### What happened?

You get an empty page. Or, if you load it via about:addons, no release notes are displayed.

### What did you expect to happen?

The page contains the release notes. You can see them in https://addons.mozilla.org/en-US/firefox/addon/tab-counter-plus/versions/

The page works for other add-ons, e.g. https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/versions/3.1/updateinfo/

### Anything else we should know?
Right now this seems to happen for all versions of Tab Counter Plus. Not entirely sure if it ever worked, but I'm fairly sure it hasn't been working at least since I published version 2.2 (July 3, 2018).

Not sure if related, for the initial versions I accidentally published the version notes for the Catalan locale instead of en-US. Then I removed that locale.

**Comment by diox** [comment]
> For the initial versions I accidentally published the version notes for the Catalan locale instead of en-US. Then I removed that locale.

I suspect it's related, I just can't figure out how at the moment. I think somehow we're picking that deleted translation (it's NULLed but still present because of the way our translations app is set up) instead of the english one. The weird thing is, it should definitely pick up the english one. Also, why would that be happening for *all* versions of this add-on ?

See also https://github.com/mozilla/addons-server/issues/4599 and https://github.com/mozilla/addons-server/issues/7535

**Comment by diox** [comment]
It's not directly related to that actually. Rather, it has to do with the fact that this version has multiple files, and the way to get the version instance from the queryset.

We use the related manager `addons.versions` and that seems to not play well with the transformer for some reason, when there are multiple results. Adding a `.distinct()`, reworking the queryset to use `Version.objects.filter(addon=addon)` or using `.last()` instead of `qs[0]` all seem to fix the issue.

I'm going to spend a bit more time on Monday trying to figure out what's going on exactly...

**Comment by vcarciu** [comment]
Verified as fixed : 
![relnotestext](https://user-images.githubusercontent.com/1583842/43145051-261f4ca6-8f67-11e8-9804-610ec5a59eed.png)
