### ISSUE TITLE
Collect stats for disabled add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8975]
#8947 enables admins to see stats for disabled add-ons. However, the information is currently not even collected/generated.

We need to collect stats for disabled add-ons, so we can show them.

@diox suggested to collect stats on all add-ons except add-ons that have `STATUS_DELETED` or `STATUS_NULL` for performance reasons.

**Comment by AlexandraMoga** [comment]
@wagnerand , @EnTeQuAk I'm not sure how I could test this on -dev or stage. As far as I know, statistics are not captured on these servers.
If you have any suggestions, that would be great.

**Comment by AlexandraMoga** [comment]
@diox thanks for the heads up.

**Comment by AlexandraMoga** [comment]
In order to verify this I did the following:
- I've looked for some add-ons on AMO dev for which stats were collected
- I took a note of the stats available at that moment (Aug 06)
- I've installed the add-ons
- I've changed their status to Disabled or Invisible
- I have checked the statistics for the installed add-ons on Aug. 07 and observed that: **number of downloads increased by 1, number of average daily users increased by 1**

**[Before install]**
![image](https://user-images.githubusercontent.com/31961530/43783206-d19b0bb2-9a69-11e8-9228-f8e46739db51.png)


**[After install - next day]**
![image](https://user-images.githubusercontent.com/31961530/43783224-d9b72ae2-9a69-11e8-90d4-89c0020bd4e2.png)

![image](https://user-images.githubusercontent.com/31961530/43783241-e3c53eb6-9a69-11e8-8318-6e79adbf7d1c.png)

@wagnerand please let me know if the testing method is valid for your case

**Comment by wagnerand** [comment]
@AlexandraMoga Can we check tomorrow again? That "1" might have come from August 6, before you disabled it. What we need to cover is a full day of where the add-on was disabled and make sure there is still usage collected for that day.

**Comment by AlexandraMoga** [comment]
@wagnerand sure, I will have another look tomorrow.

**Comment by AlexandraMoga** [comment]
@wagnerand I've had a look at the same add-ons today and I can see an increase for the average daily users compared to yesterday. The number of downloads stays the same.
This does look like some usage is collected for the day when the add-on was disabled. 

![image](https://user-images.githubusercontent.com/31961530/43837820-5a22fa5e-9b22-11e8-8ff6-8bdd82868b19.png)

![image](https://user-images.githubusercontent.com/31961530/43837876-84a34d6a-9b22-11e8-90c5-f8d48fb67473.png)
