### ISSUE TITLE
The warning for slug already used is not displayed anymore during submissions

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#8986]
Steps to reproduce:
1.Submit an extension(without id) to amo stage
2.Try to submit again the same extension

Expected results:
A warning saying that the slug is already used should be displayed in Step 2 of submission flow(after validation)

Actual results:
The warning is not displayed and "slugname" is automatically changed to "slugname1"

NOTES:
Possibly related to #7506 

Please see a video for this bug: 
![slugwarning1](https://user-images.githubusercontent.com/1583842/43211242-c2b4f732-9039-11e8-9c8d-f1a569ce9dac.gif)

**Comment by eviljeff** [comment]
I mentioned this in #7506 
> The downside is potentially a few more submissions won't be prompted to change their slug in the detail slug, and will instead get a slug like 1234-1234-1234-12345 if the name only has nonsense characters **(or the auto-generated `name1` when `name` isn't nonsense, but already exists)**.

So it's a known change, to me anyway.  Before the javascript  knowingly changed the slug to something not valid - and you only get the error message after you submit the form.  @jvillalobos can comment if it's desirable though.

**Comment by jvillalobos** [comment]
We should show some warning message if the name or slug are duplicated for the same dev, since it's very likely a mistake.

**Comment by eviljeff** [comment]
To note, the slug can't be duplicated on initial upload, because the user can't specify the slug until the detail step which is after the slug has been generated and it's already been generated as a valid one.  (The name can be duplicated, but AFAIK preventing duplicate names has never been a thing on AMO.)

The flow is this:
An addon is created from the upload and the slug is set from the name; if it's already taken -1 (-2, etc) is added.
The details step is shown to the user with the name and slug generated.

That flow in django hasn't changed.  But prior to #7506 the javascript then re-generated the slug from the name client-side immediately on page load - without knowing about existing add-ons with the same slug (because it's client side and can't know) - so if the user then submitted the form they'd get an error that the slug was taken.  Only _after_ the form was submitted though.

**Comment by eviljeff** [comment]
@jvillalobos can you clarify what change you want here - is it some highlight about the generated slug being not the same as just the name? (UX plz)
Reverting/amending the javascript change in #7506 so the slug is generated as the name again (which would then return a validation error on submit)?

**Comment by jvillalobos** [comment]
This seems like a bigger issue than #7506, so I propose to revert that fix. I'll give more thought to how we should deal with accidental duplication and include it in future submission flow updates.

**Comment by vcarciu** [comment]
Verified as fixed : 
![slug](https://user-images.githubusercontent.com/1583842/43829957-e0fa7b84-9b08-11e8-8bfb-2a6df27f96bd.png)
