### ISSUE TITLE
Can't access file for user-disabled add-on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8988]
### Describe the problem and steps to reproduce it:

On https://addons-internal.prod.mozaws.net/en-US/reviewers/review/poper-blocker-pop-up-blocker version 4.0.7.3:
https://addons-internal.prod.mozaws.net/firefox/downloads/file/973764/popup_blocker_for_firefox_poper_blocker-4.0.7.3-an+fx.xpi?src=reviewer returns 404
https://addons-internal.prod.mozaws.net/en-US/firefox/files/browse/973764/ shows the file contents correctly.

I should have been able to download the file.

**Comment by wagnerand** [comment]
Looks like this is related to the domain used.

https://addons.mozilla.org/firefox/downloads/file/996648/blocksite-4.0.3-an+fx.xpi?src=reviewer works fine.

Paging @bqbn.

**Comment by bqbn** [comment]
It's not [1] that returns 404. It is [2] that returns 404 (you need to look at the awesome bar to see [1] is changed to [2] when you click on [1]). So I'm guessing the reason you're seeing 404 is because this file is in the "guarded-addons" area.

[1] https://addons-internal.prod.mozaws.net/firefox/downloads/file/973764/popup_blocker_for_firefox_poper_blocker-4.0.7.3-an+fx.xpi?src=reviewer 
[2] https://addons-internal.prod.mozaws.net/en-US/firefox/mnt/efs/addons-internal.prod.mozaws.net/guarded-addons/834829/popup_blocker_for_firefox_poper_blocker-4.0.7.3-an%2Bfx.xpi

**Comment by wagnerand** [comment]
I think you're almost right. I am not sure why I didn't see the redirect when I tried initially. Now, I get the redirect too, but the reason we end up with 404 is because AMO redirects to `guarded-addons` but in fact the file is not there but in `files/...`.

**Comment by diox** [comment]
>  the reason we end up with 404 is because AMO redirects to guarded-addons but in fact the file is not there but in files/.... 

It's a variation of https://github.com/mozilla/addons/issues/324. This is a lot trickier to fix than you'd think initially, because we need to move all files everytime the `status` / `disabled_by_user` field changes... and that needs to happen instantaneously... We don't do it correctly for every scenario, but in theory the crons to move the disabled files should fix that after a couple hours max...

**Comment by bqbn** [comment]
> but in fact the file is not there but in files/....

FWIW, the said file is in the `guarded-addons/` directory.

```
$ ls -l /mnt/efs/addons-internal.prod.mozaws.net/guarded-addons/834829/popup_blocker_for_firefox_poper_blocker-4.0.7.3-an+fx.xpi
-rw-r--r-- 1 olympia olympia 1069951 Jun 14 03:29 /mnt/efs/addons-internal.prod.mozaws.net/guarded-addons/834829/popup_blocker_for_firefox_poper_blocker-4.0.7.3-an+fx.xpi
```

**Comment by wagnerand** [comment]
> FWIW, the said file is in the guarded-addons/ directory.

It was not when I checked...

**Comment by diox** [comment]
That's probably because the cron fixed the problem once it fired. Can you access the file now ?

**Comment by wagnerand** [comment]
No, not using https://addons-internal.prod.mozaws.net/firefox/downloads/file/973764/popup_blocker_for_firefox_poper_blocker-4.0.7.3-an+fx.xpi?src=reviewer .

**Comment by diox** [comment]
So now we're back to something related to the domain, since it works on addons.mozilla.org, right ? @bqbn could it be that on this domain the `X-Accel-Redirect` doesn't work properly?

**Comment by bqbn** [comment]
Nginx configuration for this domain hasn't changed for over a year, thus I doubt it that this is due to a regression of Nginx config change.

That said, I noticed there is a similarity of this issue and https://github.com/mozilla/addons-server/issues/9005, i.e. both have `firefox/downloads/` as the prefix of the endpoint.

However, as I commented in https://github.com/mozilla/addons-server/issues/9005#issuecomment-408487856, `reviewer.a.m.o` doesn't recognize `firefox/downloads/...` was the reason for that issue.

Same thing here, as you can see from https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.internal.conf.erb#L22-L63, the `addons-internal.prod.mozaws.net` domain doesn't recognize the `firefox/downloads` endpoint, that's the cause for 404.

I think we need to figure out where the `firefox/downloads/...` came from first, and if it is a legit endpoint to be served by both domains, then please file a bugzilla ticket to add it.
