### ISSUE TITLE
Support transferring collections to Mozilla account with Admin:Curation permission

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9001]
In the old collections system, privileged users could create a collection and then transfer it to the [official Mozilla account](https://addons.mozilla.org/user/mozilla/). Since we removed collaborators, we now need a way to replicate this behavior.

We need an admin tool, available to users with `Admin:Curation`, that allows them to transfer any collection to the official Mozilla account. If it's easier, it can be limited to collections created by that user (the curator).

/cc @devaneymoz

**Comment by eviljeff** [comment]
#8743 will address this.

**Comment by diox** [comment]
#8743 will allow users with `Collections:Edit` to do it. However, I'm keeping this issue separate to see what I can do about `Admin:Curation`.

I'm thinking, allow users with `Admin:Curation` to transfer their own collections, and then allow them through that permission to edit mozilla collections in the admin as well (through that permission they can already edit them in the frontend)

**Comment by ioanarusiczki** [comment]
@diox 
> I'm thinking, allow users with Admin:Curation to transfer their own collections, and then allow them through that permission to edit mozilla collections in the admin as well (through that permission they can already edit them in the frontend)

 I added 2 accounts to Admin:Curation group for testing on AMO dev. - FF61(Win10)
1. I tried to transfer a collection created by the curator to Mozilla by going to the Author field and clicked on _Lookup_ - "Oops not allowed" message is displayed meaning I don't have access.  ([the collection I tried to modify](https://addons-internal.dev.mozaws.net/en-US/admin/models/bandwagon/collection/5497424/change/)) - won't work for me
2. About editing Mozilla collections I tested with "fall-themes" and "youtube-boosters" and I could edit those in the admin except for adding or removing add-ons because the "Collection addons" section is not available for curators. 
3. I've noticed that with these accounts I cannot create a collection from admin tools.  Same problem - I tried to add the author into The Author field's  -  "Oops not allowed". - I don't know if it's intended or it's a problem here too

**Comment by diox** [comment]
@ioanarusiczki can you link the user account you were testing with ?

**Comment by diox** [comment]
Re-opening to investigate.

**Comment by diox** [comment]
Ok, so:
1. Is not a blocker. If you don't have the rights to do the lookup, you can still paste a user id in there. It's cumbersome, but it works.
2. That's a bit more annoying. Can you file a follow-up issue for this ?
3. If it's just the author thing blocking you, again, you should be able to just paste a user id in there.

**Comment by ioanarusiczki** [comment]
@diox 
1&3 work as you said, I pasted the ID and then the collections created by the user can be transferred to Mozilla. Also if I paste the user's ID I can create a new collection from admin tools. This needs a followup to fix the lookup too, I think we should track the lookup into a new issue.

for 2 I already filed https://github.com/mozilla/addons-server/issues/9368

**Comment by ioanarusiczki** [comment]
Ok, after discussion no followup for 1&3 is needed, it's a general issue that the lookup won't work. If you can't modify users you won't see the popup for users.
I marked this verified fixed. -AMO dev FF62(Win10)
