### ISSUE TITLE
Source code files not available to reviewers, throw 403

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9005]
### Describe the problem and steps to reproduce it:

Links to source code files throw a 403 for admins:

Some examples:
https://reviewers.addons.mozilla.org/en-US/reviewers/review/lastpass-password-manager (v4.6.0.13): https://reviewers.addons.mozilla.org/firefox/downloads/source/2483113

https://reviewers.addons.mozilla.org/en-US/reviewers/review/sourcegraph (v1.7.39): https://reviewers.addons.mozilla.org/firefox/downloads/source/2483084

https://reviewers.addons.mozilla.org/en-US/reviewers/review/ext-saladict (v6.8.3): https://reviewers.addons.mozilla.org/firefox/downloads/source/2483670

### What happened?

403

### What did you expect to happen?

Access to the file

### Anything else we should know?

Not sure if it is a coincidence but it seems those files were uploaded around or after yesterday's push.

**Comment by wagnerand** [comment]
I looked into the file permissions on the file system and it seems the ones that are failing have 600, the ones that are working have 644.

**Comment by bqbn** [comment]
I'm not sure where you find those links, but please note that currently the `reviewers.a.m.o` site only accept the following endpoints: https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.reviewers.conf.erb#L19-L34

Everything else is either denied or send back to `a.m.o`.

In your case, the `firefox/downloads/source/<number>` is not one of the allowed endpoints on `reviewers.a.m.o` domain and was sent back to `a.m.o`.

I think that you can either 

(a) file a bugzilla ticket to have `firefox/downloads/source/<number>` to be served by the `reviewers.a.m.o` domain, if that's the correct link.

or

(b) make sure those files don't have a wrong link, for example, maybe some code or config changed, and they got linked to `reviewers.a.m.o` incorrectly. Or maybe the link was supposed to be `<locale>/firefox/files/...` (which reviewers.a.m.o serves), but got incorrectly set to `firefox/download/...`.

**Comment by diox** [comment]
The domain & locale don't matter here. 

Each of these URLs:
* https://addons.mozilla.org/en-US/firefox/downloads/source/2483113
* https://reviewers.addons.mozilla.org/en-US/firefox/downloads/source/2483113
* https://reviewers.addons.mozilla.org/firefox/downloads/source/2483113 

all redirect to https://addons.mozilla.org/firefox/downloads/source/2483113 and *that* URL returns a 403.

`/downloads/` has always been a locale-less URL, the redirects are correct. The end URL should not 403. It may be a red-herring but we believe it does so because the permissions are incorrect on the file, as @wagnerand said in his previous comment. This doesn't happen for all the files however for some unknown reason.

**Comment by bqbn** [comment]
> The domain & locale don't matter here.

Yep, I'm not saying domain & locale matter either. I'm just saying that `firefox/downloads/source/<number>` is not served by either `reviewers.a.m.o` or `a.m.o` Nginx virtual servers, by just looking at the configuration.

However, if the application sends back a x-accel-redirect header for this endpoint, then it's possible Nginx still serves it, because we configure a few location that's used for the x-accel purpose. [1]

Maybe I can ask this question, when a user visits `/firefox/downloads/source/2483113` endpoint, what x-accel-redirect header does the application send back to Nginx?

[1] https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L251-L276

**Comment by diox** [comment]
> However, if the application sends back a x-accel-redirect header for this endpoint, then it's possible Nginx still serves it, because we configure a few location that's used for the x-accel purpose. [1]
> Maybe I can ask this question, when a user visits /firefox/downloads/source/2483113 endpoint, what x-accel-redirect header does the application send back to Nginx?

It *is* served by [a view](https://github.com/mozilla/addons-server/blob/f11c64b3d7f03adc95037318fac8c217b8a8e764/src/olympia/versions/views.py#L99-L146) that sets the `X-Accel-Redirect` redirect header (this is the actual header that the view is using)

**Comment by bqbn** [comment]
Ok, thanks for the above link. Although I think you might mean [this view](https://github.com/mozilla/addons-server/blob/f11c64b3d7f03adc95037318fac8c217b8a8e764/src/olympia/versions/views.py#L172) for the `/firefox/downloads/source/2483113` endpoint.

Anyways, I've located the file and updated its permission bits, and the file is now able to be downloaded.

**Comment by diox** [comment]
Eh yeah I meant that view.

The question is: how did those files end up with the wrong permissions in the first place? It seems to happen for quite a few files and we don't know why.

**Comment by bqbn** [comment]
I have no answer for that question at the moment. 

I saw another 15 out of 11K files that don't have the correct permission in the same directory of this file. Out of the 16 files, the oldest modification time is Jul 26 16:56 UTC.

Given the fact that these files are in `/shared_storage/uploads/version_source/...` directory, will any of the cron jobs touch them, or is there any view code that may touch the permission bits?

**Comment by diox** [comment]
AFAIK there is no cronjob or view code that touch the permission bits on those files. The only place in addons-server that touches permissions is in the file viewer, a completely different part of the code (plus it's to set directories to 755 anyway)

**Comment by diox** [comment]
We could try setting `FILE_UPLOAD_PERMISSIONS` to work around the issue, but a) I'm not sure it will be enough b) I'd still like to understand why this is (suddenly?) happening.

**Comment by diox** [comment]
Something we noticed with @wagnerand : the files that have the wrong permissions have all a) been created after the push with the django upgrade b) a relatively high size.

Our theory is that something changed in the way django deals with higher size files. To upload them, it first creates a temporary file and then moves it to the final destination. It has always worked like this, but maybe something specific in that process changed and that's causing our problem.

Going to investigate more and see what we can do about it.

**Comment by diox** [comment]
QA:
- Try uploading source code for add-ons with different sizes of zip files, below and above 2.5 MB in particular.
- Try accessing those source links from a reviewer account.

**Comment by diox** [comment]
@bqbn : between now and next push which will have the fix, can you monitor that `version_source` directory and manually fix the permissions from time to time ?

**Comment by bqbn** [comment]
I set up a cron job that runs every 30 minutes to find files with wrong permission bits and correct them as needed.

**Comment by vcarciu** [comment]
Uploaded multiple zip files as source code and I was able to see them all in AMO-dev as a reviewer
