### ISSUE TITLE
Add-on homepage + support URLS should not link to AMO

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#9012]
Looking at broken links on AMO Raphael noticed that some Add-ons are linking the homepage back to AMO with an id. In some cases this is without a slash and causes multiple redirects only to see the same page you were already looking at.

Since I don't think there's a good use-case to link to pages on AMO for the homepage or support URL we should look at the following changes:

* Update the validation on the details edit pages to prevent links to AMO in the homepage and support fields. 
* Remove all entries in the DB that have addons.mozilla.org as the host part of the link.
* Consider if there are any other url fields that might have similar issues.

### Update for QA

The purpose of this issue is to NOT allow AMO links in the following fields (on Dev Hub):

- homepage
- contribution URL
- support URL

> * Remove all entries in the DB that have addons.mozilla.org as the host part of the link.

This will be addressed in another issue: see #9735.

**Comment by jvillalobos** [comment]
The support URL has the same issue. There are [over 500 listings](https://sql.telemetry.mozilla.org/queries/57643/source) affected by this.

**Comment by rraue** [comment]
If you clean up the DB now, is there a cronjob doing this regularly, so we wont have this problem again in 6 month?

**Comment by diox** [comment]
> If you clean up the DB now, is there a cronjob doing this regularly, so we wont have this problem again in 6 month?

We also want to add extra validation preventing developers to enter such URLs in the first place (see first action item in the description).

**Comment by willdurand** [comment]
> Remove all entries in the DB that have addons.mozilla.org as the host part of the link.

@diox how do we plan to clean up the DB? Do we have to write a migration/script for that?

**Comment by willdurand** [comment]
> We need to write something to do that yes. It probably needs to be a task fired from the `process_addons` command.

Ok, so I'll file a new issue for that then (and try to decipher what needs to be done 😄)

**Comment by willdurand** [comment]
> Consider if there are any other url fields that might have similar issues.

The contribution URL is also protected now.

User profiles have a `homepage` field. Do we want to add validation on this field too? If so, should we validate it in the API or in the frontend?

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF62, Win10x64

Linking to AMO website is forbidden in the following fields during add-on submission or editing via Dev Hub:
- Homepage 
- Support Site
- Contributions URL

However, it is possible to set a `"homepage_url"` pointing to AMO in the manifest and since the linter is not imposing any restrictions on this property, the addon will pass.
I've opened https://github.com/mozilla/addons-linter/issues/2253 to address this use case. 

![image](https://user-images.githubusercontent.com/31961530/47355552-599d0280-d6ca-11e8-9cb3-9872103f8675.png)

![image](https://user-images.githubusercontent.com/31961530/47355564-60c41080-d6ca-11e8-8dd6-d923ad1ac2bc.png)


@willdurand I've noticed that forbidden URLs are restricted to the server you're currenltly logged into, i.e. If I'm working on -dev, I can point my add-on homepage to https://addons.mozilla.org without any errors. I guess that this is a normal behavior, but I prefer to have your confirmation as well. 

Also, could you raise your question regarding the `homepage` field in user profiles in a separate issue maybe?

**Comment by willdurand** [comment]
> @willdurand I've noticed that forbidden URLs are restricted to the server you're currenltly logged into, i.e. If I'm working on -dev, I can point my add-on homepage to [addons.mozilla.org](https://addons.mozilla.org) without any errors. I guess that this is a normal behavior, but I prefer to have your confirmation as well.

Yep, that's what we want.

> Also, could you raise your question regarding the homepage field in user profiles in a separate issue maybe?

Yep.

**Comment by willdurand** [comment]
> Also, could you raise your question regarding the `homepage` field in user profiles in a separate issue maybe?

@muffinresearch @jvillalobos should we add the same validation on the `homepage` field in user profile edit pages?

**Comment by muffinresearch** [comment]
> @muffinresearch @jvillalobos should we add the same validation on the homepage field in user profile edit pages?

Yes that sounds like a good idea 👍

**Comment by willdurand** [comment]
> Yes that sounds like a good idea 👍

Ok, I filed https://github.com/mozilla/addons-server/issues/9790
