### ISSUE TITLE
Upgrade to Django 1.7

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#905]
This is the GitHub tracking issue for https://bugzilla.mozilla.org/show_bug.cgi?id=1164477

TODOS:

* [x]  locale/templates/LC_MESSAGES/{django,djangojs}.pot get updated on extract
* [x] Get rid of mysql-pool and use CONN_MAX_AGE config
* [x] https://github.com/mozilla/zamboni/pull/3038/files#diff-aa9311318d4c8ebf2b5495d72c7f356dL41
* ~~get rid of happyforms~~ (https://github.com/mozilla/olympia/issues/1569)

Other cleanup stuff I noticed:
* ~~olympia.services.utils has some weird import hacks :confused:~~ (https://github.com/mozilla/olympia/issues/1570)

General updates, things to notice:

* `tower` has been replaced by puente (https://github.com/mozilla/puente)

Verify the following dependency updates to exist in wheelhouse:

* [x] django-waffle==0.11
* [x] django-cache-machine==0.9.1
* [x] Jinja2==2.8
* [x] MarkupSafe==0.23
* [x] Django==1.7.11
* [x] jingo==0.8
* [x] django-babel==0.4.0
* [x] puente==0.4
* [x] pytz==2015.7

Most are so this is mostly for documentation reasons.

**Comment by diox** [comment]
django-product-details will need to be updated. 0.8.1 has a bug however, so we'll have to wait for a new version with a fix for https://github.com/mozilla/django-product-details/issues/49 before changing our requirements and updating wheelhouse.

**Comment by diox** [comment]
Also, the latest plan is to:
- Merge the module refactor from https://github.com/mozilla/olympia/pull/1081 first to master. It fixes all the imports, which helps because Django 1.7 app loading code requires all imports to be consistent.
- Rebase #914 with master once that module refactor landed in master. Use a "core" app in it that removes the need for startup.py / olympia.py hacks. manage.py can be completely cleaned up of any amo code/imports then
