### ISSUE TITLE
Update Celery to 4.2.x

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9068]
We should update Celery to 4.2.x

There already was a PR that did this but we didn't have the time to fix the tests yet: https://github.com/mozilla/addons-server/pull/9026

**Comment by EnTeQuAk** [comment]
When tackling this, we should at least partially trying to add one or more tests actually testing the worker and not just using eager-mode. http://docs.celeryproject.org/en/latest/userguide/testing.html

**Comment by diox** [comment]
I'm kinda stuck on a celery issue that's linked to this so I thought I'd post a comment summing up the situation.

Here is what's happening at upload time currently:
- We build a task chain composed of a validation task decorated with `@validation_task` that calls the linter, a "save" task that saves the result, and optionally an akismet task before.
- We set a `on_error` on the validation task so that when an exception is triggered, we return a generic error message as the result instead ("Sorry, we couldn't load your extension")
- We `delay()` the chain and wait for it to be finished to display results to the user

Fun twist: `@validation_task` *also* has its own internal error handling which does the same thing our `on_error` handler does. Exceptions thrown from that task are caught and never bubble up. This means that currently, the `on_error` we set actually does nothing, and we still get error handling thanks to the decorator. Which is good, because I noticed that __in Celery < 4.2, which we're currently using, `on_error` in chains is completely discarded by celery and never fires__.

Unfortunately, for a security issue I'm working on, I want to add a new task to the chain, that can't be decorated with `@validation_task`. So I need `on_error` to work. I've tried upgrading us to 4.2 and locally, that fixes that issue, but I then ran into 2 problems:
1. With Celery 4.2, a few of our tests don't pass. We get `RuntimeError: Never call result.get() within a task!` which is weird because we either don't do that, or do that just because we're doing a `retry`. Using `autoretry_for` instead of our custom retry code doesn't fix it, but it might be only an issue with tests, that are fired in eager mode.
2. Another issue is that even with Celery 4.2, it seems the `on_error` task is not triggered in tests (which, again, use eager mode - that may or may not be related) and so a few tests that depend on error handling failed in my branch where I'm adding a new task to the chain.

**Comment by willdurand** [comment]
@EnTeQuAk what's the status of this issue? thanks!

**Comment by EnTeQuAk** [comment]
I do have a working branch that I needed to pause to get some other stuff into the tag. I'll continue working on it after the tag and hope to have a PR up and running on Wednesday or Thursday at the latest

**Comment by willdurand** [comment]
@EnTeQuAk great, thanks. Could you please share a branch so that I can see the changes and build on-top of it?

**Comment by EnTeQuAk** [comment]
You can checkout https://github.com/mozilla/addons-server/commits/9068-upgrade-celery-43 - but I won't guarantee any heavier changes are about to land. I'm currently looking into correcting the task error handling that mat mentioned in #8487 which may affect you but ideally it shouldn't.

**Comment by willdurand** [comment]
@EnTeQuAk can we close this issue?

**Comment by EnTeQuAk** [comment]
Absolutely, this has been fixed by https://github.com/mozilla/addons-server/pull/12073 - apparently I forgot to link them together.

**Comment by AlexandraMoga** [comment]
Does this require QA?

**Comment by willdurand** [comment]
@AlexandraMoga yep, could you please verify that the features relying on celery tasks continue to work? I am thinking about addon submissions right now but there is probably more.

**Comment by EnTeQuAk** [comment]
Yes, these parts touch this particular celery upgrade:

* Add-on submission (upload, linting and actual submission)
* Add-on signing
* email sending (of any kind, although I'm unsure how -dev and -stage are configured in this regard tbh, do we send mails from dev and stage?)

There's many more but these should be fine for testing, have the most public impact and are already testing the update as much as possible (as our submission pipeline is the most complex celery-task)

**Comment by diox** [comment]
- Add-on indexing (changes made to the add-on should be reflected in search results)

**Comment by AlexandraMoga** [comment]
Verified fixed on stage:

>Add-on submission (upload, linting and actual submission)
- I've uploaded listed and unlisted extensions, as well as other add-on types
- I've covered linting warnings and errors

>Add-on signing
- made sure that add-ons are correctly signed after manual*/auto-approval
*for recommended add-ons, where the `mozilla-recommendation.json` is present as well

>Add-on indexing (changes made to the add-on should be reflected in search results)
- verified that new add-ons are found in search
- updates to add-on metadata are reflected in search
- deleted/disabled add-ons are not found in search

Regarding emails, on -dev and stage we can verify that emails are received when some specific actions are performed (via Fake mail) but we do not have the ability to send emails out from these servers.
