### ISSUE TITLE
Disable legacy extension version submissions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9147]
On September 6th, we need to stop accepting new legacy extension version submissions. Developers will be notified in advance of this event.

In the upload step of the submission process, if a legacy extension is detected, an error should be shown with the message: "Legacy extensions are no longer supported in Firefox."

This applies to both listed and unlisted versions, whether they are new add-ons or updates. It only applies to extensions, since legacy dictionaries are still accepted. The admin override in the upload step should still work.

**Comment by jvillalobos** [comment]
This applies for complete themes as well.

**Comment by EnTeQuAk** [comment]
@eviljeff I think we should try and target an earlier milestone to add this behind a waffle flag and test it upfront.

**Comment by eviljeff** [comment]
@entequak we could do. Though i think it will be a pretty straightforward change.

**Comment by jvillalobos** [comment]
Another condition to take into account here are internally-signed extensions, some of which are still legacy. I believe we special-case them for upload anyway, and we should continue to support that for the time being.

**Comment by ioanarusiczki** [comment]
@eviljeff @jvillalobos 
I made some tests on AMO dev FF52 ESR and FF61 and here are the results:
1.  Submission of  legacy extensions and complete themes, listed and unlisted versions is no longer possible.
                                     
- waffle switch disabled Message displayed: " Starting with Firefox 53, new add-ons on this site can only be WebExtensions."
- waffle switch enabled Message displayed:  "Legacy extensions are no longer supported in Firefox."

2. Uploading a new version for a legacy extension, complete theme 
- waffle switch disabled, uploading a **_listed_** version, Message displayed: "Your add-on was validated with no errors and 17 warnings. for listed versions". The upload can be done.
- waffle switch disabled, uploading an _**unlisted**_ version, Message displayed: "Starting with Firefox 53, new add-ons on this site can only be WebExtensions" Uploading new unlisted version is not possible. "Continue" button is inactive.
-waffle switch enabled, uploading a new listed or unlisted version, Message displayed: "Legacy extensions are no longer supported in Firefox".

3. The admin override is allowed with disallow-legacy-submissions enabled.
![admin override works](https://user-images.githubusercontent.com/33448286/44989345-37261d00-af96-11e8-9cb1-e2fcc8444d20.gif)

4. With disallow-legacy-submissions enabled, legacy dictionary submission or new version upload still can be made. 

5. The only untested part is 

> Another condition to take into account here are internally-signed extensions, some of which are still legacy. I believe we special-case them for upload anyway, and we should continue to support that for the time being. 

Could you give an example of such extension?  I don't know what internally signed extension is.

**Comment by eviljeff** [comment]
> Could you give an example of such extension? I don't know what internally signed extension is.

afaik they're "mozilla signed extensions" - #5619 was the implementation issue so I guess they'll be details of how to submit there.

**Comment by ioanarusiczki** [comment]
@eviljeff 
Thanks for mentioning https://github.com/mozilla/addons-server/issues/5619. I used the sample-mozilla-extension-stage.xpi and sample-mozilla-extension-prod.xpi from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1369532)  
The only modifications I've made in the install.rdf is deleting from frontend metadata the <em:updateURL> row because I was receiving an error and the ID to avoid duplicates 

![banned](https://user-images.githubusercontent.com/33448286/45030369-423f8280-b054-11e8-93e5-30bdc856024a.png)

The condition is to be logged in with a mozilla account. If not the submission cannot be done.

![mozilla signed extension](https://user-images.githubusercontent.com/33448286/45030583-ffca7580-b054-11e8-8ed1-bd4fa5a6bb17.png)

I logged in using a Mozilla account on AMO dev and tested the submission then the upload of new versions (both listed and unlisted) . 
I could submit and upload these extensions with the disallow-legacy-submissions waffle switch enabled the same way as before when the waffle switch was disabled.

This is the validation message
![validation signed](https://user-images.githubusercontent.com/33448286/45030955-305edf00-b056-11e8-9c90-e51be7576f11.png)

I hope it's alright because I expected to receive the "Package already signed message" as mentioned in https://github.com/mozilla/addons-server/issues/5619

I tested on AMO dev with FF61, FF52ESR (Win10)

Attaching samples 

[sample-mozilla-extension-stage.zip](https://github.com/mozilla/addons-server/files/2348578/sample-mozilla-extension-stage.zip)
[sample-mozilla-extension-prod.zip](https://github.com/mozilla/addons-server/files/2348580/sample-mozilla-extension-prod.zip)

**Comment by eviljeff** [comment]
@ioanarusiczki maybe that validation message was fixed in the validator in the meantime.  If you can upload the file okay, and after approving the version the xpi is the same as before (i.e. it wasn't resigned with the normal signing certificate) then it's working okay.

**Comment by ioanarusiczki** [comment]
@eviljeff It's alright then. I re-checked the signature - it's the same before and after upload. Besides, now I've noticed that in the full validation report the "Package already signed" is there 
![package signed](https://user-images.githubusercontent.com/33448286/45094265-759d1280-b123-11e8-809d-0684af300752.png)

I don't know why unlisted versions cannot be uploaded for legacy extensions/complete themes without enabling the waffle switch but since this is the expected behavior in makes no sense filing an issue.

If you agree, I think this can be marked verified fixed. 
Thanks!

**Comment by ioanarusiczki** [comment]
After discussions, I filed an issue for the unlisted version upload problem https://github.com/mozilla/addons-server/issues/9352 
This can be marked as verified fixed on AMO dev with FF61(Win10)
