### ISSUE TITLE
Implement captcha in front of devhub submission

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9171]
To fight spam add-on submissions we want to add a captcha in front of new add-on submissions temporarily (behind a waffle flag).

Ideally, this should happen at account creation but there's much more product planning needed for that. Maybe @jvillalobos can see to put that into respective pipelines?

**Comment by EnTeQuAk** [comment]
QA: 

There is a new captcha at the developer agreement submission step, this step is only visible for first-time add-on submissions.

This is behind the 'addon-submission-captcha' waffle switch.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk 

After enabling the `addon-submission-captcha` switch (verified both dev and stage) there is no additional step in the first add-on submission flow.

Moreover, nothing happens when clicking on 'Accept" after the checkboxes are marked:

![no captcha](https://user-images.githubusercontent.com/31961530/44197862-85d75880-a148-11e8-91cc-5f6727f58561.gif)

**Comment by EnTeQuAk** [comment]
> Moreover, nothing happens when clicking on 'Accept" after the checkboxes are marked:

Indeed, I can reproduce this. I'll investigate.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64
![captcha dev](https://user-images.githubusercontent.com/31961530/44207404-c98c8b00-a165-11e8-8fe6-80ade983bbbd.gif)

**Comment by AlexandraMoga** [comment]
Stage also verified
