### ISSUE TITLE
"Oops..." page returned when trying to submit extensions with empty name for some languages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#9180]
Steps to reproduce:
1.Go to https://addons.mozilla.org/ro/developers/ (please note that language is imporant)
2.Try to submit a new extension with an empty name

Expected results:
"This field is required" message should be displayed

Actual results:
"Oops... " page displayed

NOTES:
Reproducible also on Stage for ro language and probably for some other languages too
Not reproducible for en-US for example

Please see a video of the issue:
![ro](https://user-images.githubusercontent.com/1583842/44223215-a70f6780-a18f-11e8-93f9-4c93cfaa33d5.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4506153/ which should be easy to fix - hopefully it's just a matter of using `unicode` strings instead of `str`, by using the `u` prefix.

(We also have https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4498299/ but that seems to be a different problem).

**Comment by diox** [comment]
Should have been fixed by #9204

**Comment by vcarciu** [comment]
Verified as fixed : 
![emptyro](https://user-images.githubusercontent.com/1583842/44451608-e2c98780-a5fc-11e8-9f5f-2ff43ce3f008.gif)
