### ISSUE TITLE
Can't install theme in Thunderbird

### ISSUE THREAD

**Issue by PRDormer** [mozilla/addons-server#9214]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I'm trying to install a theme in Thunderbird.  Selecting themes from Thunderbird brings up a themes page in my browser but when I select the install In Thunderbird button it goes to a page not found

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please file issues about addons.thunderbird.net at https://github.com/thundernest/addons-server/issues.

If you think this issue has been closed erroneously please re-open or comment on the issue and provide as much information as possible so that we can assist you.

**Comment by PRDormer** [comment]
When I got the error message, this is where it told me to make the report.  I suspect, having seen other bug reports, that attempting to install add-ons in Thunderbird instead attempts to install them in Firefox, but as I don't have Firefox installed on this machine, that's why I got the error.
