### ISSUE TITLE
Reviewer's page - "Header file" should be displayed for the image used as headerURL

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#9228]
STR:
1. Load AMO dev and login with an admin account
2. Go to the Listed review page of a static theme with additional background pictures such as this [one](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/centertopst3) or this [one](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/st3center-top)
3. Observe the display for the image used as headerURL below the Theme Image previews

Expected result:
Header file 1 of 2 for the headerURL image is displayed.

Actual result:
Background file 1 of 2 is displayed for the headerURL which could be confusing for the reviewer.

Notes:
This issue is reproducible on AMO dev with FF61(Win10). 

![header file](https://user-images.githubusercontent.com/33448286/44465136-5bdcd500-a625-11e8-8f40-c4c3f90eb323.png)

a second example where the header is displayed the second after the background image
![second example](https://user-images.githubusercontent.com/33448286/44465211-99d9f900-a625-11e8-822b-991936d52c15.png)

**Comment by eviljeff** [comment]
Background files is just all the files in a folder that were extracted during the version submission - i.e. we know they were background image files but at this point not what they were for.  

It would be quite a large change to either extract the manifest again and attempt to match up the files or store a copy of the manifest somewhere.  If it's just because it _might_ be confusing for a theoretical future reviewer I'm going to wontfix this for now.  If it comes up as a much needed request from theme reviewers we can reconsider.
