### ISSUE TITLE
Give admin reviewers access and delete options to user reviews (incl for disabled add-ons)

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9248]
### Describe the problem and steps to reproduce it:

When an add-on gets disabled, the public listing pages (including the user reviews page), becomes unavailable. The add-on review tools page links to the user reviews page.

Admin reviewers 

### What happened?

Accessing that user reviews page for a disabled add-on returns 404.

### What did you expect to happen?

Admins should have access to user reviews for any add-on including disabled disabled ones. Having the option to delete several reviews at once would be good, so we can take action if necessary.

### Anything else we should know?

Ideas on implementation:
* I am imagining exposing the number of ratings on the admin add-on page that links to a new view that shows the ratings for this add-on. That view should include the columns of the 'reviews' database table and allow hiding of deleted reviews ('deleted' column) and/or developer replies ('reply_to' column). It should also be possible to sort the table (for example by 'ip_address', 'created', 'user_id', 'flag' etc).
* Mass-delete ratings: Ability to select some or all reviews of an add-on and delete them in one go.

**Comment by diox** [comment]
We should try to take advantage of the django admin for this if possible, adding the necessary fields to what's being displayed in that admin.

**Comment by wagnerand** [comment]
Any chance we can reprioritize this? I keep running into it and I am unable to even look at them, let alone delete the fake ones (for when the add-on becomes public again).

**Comment by AlexandraMoga** [comment]
@diox the Ratings tool from Django Admin is returning a server error (500) when I'm trying to access it:

see https://addons-internal.dev.mozaws.net/en-US/admin/models/ratings/rating/

This will also happen when I want to access the ratings page from the admin addon edit:

https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/494655/change/
![2018-11-26_10-48-27](https://user-images.githubusercontent.com/31961530/49004404-df4e1b00-f16c-11e8-854b-ae1703d13e17.gif)

As far as I can tell, this is happening for addons that have or had ratings with empty body. For example, if an add-on had only written reviews, its admin ratings page was available. If I left an empty review for the same add-on, the ratings page becomes unavailable i.e. returns a server error.

**Comment by diox** [comment]
@AlexandraMoga I merged a fix for this, it will be on dev shortly.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF63, Win10x64

- the Ratings management tool can now be accessed from the django admin tools list or from and add-on edit page by Admin users (belonging to the [Admins](https://addons-internal.dev.mozaws.net/en-US/admin/models/access/group/1/change/) group
- the ratings management tool can also be opened for disabled add-ons
- there are new columns, with a filter option, in the ratings report

![2018-11-26_16-26-08](https://user-images.githubusercontent.com/31961530/49020039-27366780-f198-11e8-9c55-4093495368c2.gif)


@wagnerand these new functionalities are available only to full site Admins, belonging to [this group](https://addons-internal.dev.mozaws.net/en-US/admin/models/access/group/1/change/). I'm mentioning this because you refered in the issue description to Admin Reviewers, i.e. [this group](https://addons-internal.dev.mozaws.net/en-US/admin/models/access/group/50097/change/).

**Comment by wagnerand** [comment]
@AlexandraMoga Would you mind filing a follow-up about the permissions? Thanks.
