### ISSUE TITLE
"Get add-on" button privacy

### ISSUE THREAD

**Issue by da2x** [mozilla/addons-server#9298]
The [Get Firefox add-on buttons](https://blog.mozilla.org/addons/2015/11/10/promote-your-add-ons-with-the-get-the-add-on-button/) don't really fit within the [Mozilla websites privacy policy](https://www.mozilla.org/en-US/privacy/websites/). The `mozilla.net` domain isn't even mentioned.

So what privacy policies govern the use of these badges? As far as I can tell, no Mozilla website sets any cookies for the `mozilla.net` domain. Are IPs and referrer headers logged? and for how long? And other post-GDPR questions.

**Comment by atsay** [comment]
I'm asking around for this info--will update when I find out.

**Comment by atsay** [comment]
@da2x Thanks for prompting us to look into this. It brought up two things--one is that we've updated the blog post to only encourage people to save the image and host it themselves rather than calling it directly from our servers. It's a better practice in general. The second is that our [Website Notice](https://www.mozilla.org/privacy/websites/) applies to any Mozilla domain and what you see there is not meant to be an exhaustive list (because there are many), but we'll include mozilla.net in our next update of that page.

**Comment by atsay** [comment]
@da2x We have a developer newsletter that goes out every quarter, and it's probably the easiest way to learn about this type of thing. We're working on an easier way to sign up, but for now just go to https://addons.mozilla.org/firefox/users/edit and make sure the last checkbox in the Notifications section, "Stay up-to-date with news and events..." is checked.

**Comment by dessant** [comment]
Hi @atsay, would it be possible to share the SVG version of the Firefox add-ons download badge? Other stores offer SVG, EPS and AI badge assets, and it would be great to also use HiDPI buttons for promoting Firefox add-ons.

**Comment by kewisch** [comment]
Hey @dessant, do you mean the one on this page? There is a link to a SVG version as well. Let me know if you need more information, feel free to reach out via email. https://extensionworkshop.com/documentation/publish/promoting-your-extension/

**Comment by dessant** [comment]
Hi @kewisch, I did not notice that article, it is exactly what I've been looking for. Thanks a bunch!
