### ISSUE TITLE
Can't download any theme

### ISSUE THREAD

**Issue by vitalka333** [mozilla/addons-server#9332]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
Can't download any theme
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
