### ISSUE TITLE
Remove user profile links on DevHub activity feed

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9339]
From https://github.com/mozilla/addons-frontend/issues/6118, there are two places where we're still linking to arbitrary user profile pages. There's the Recent Activity column in `/developers/addons`, and the activity feed in `/developers/feed`. Those usernames should show up without a link.

**Comment by eviljeff** [comment]
This is a dupe-ish of #6044 - one should be closed.

**Comment by championshuttler** [comment]
Can I take this up?

**Comment by eviljeff** [comment]
@championshuttler you can, sure.  It'll need some tests changing, at least.  (maybe some adding too)

**Comment by shiri1248** [comment]
is this issue still open ?

**Comment by caitmuenster** [comment]
@championshuttler, this one's all yours. @eviljeff will help mentor the test changes. :)

**Comment by championshuttler** [comment]
@caitmuenster I am not well :/ . @shiri1248 please feel free to take this up :) . ATB :+1:

Shivam
(Sent from Mobile)

**Comment by shiri1248** [comment]
thanks @championshuttler  for confirmation.

**Comment by shiri1248** [comment]
@caitmuenster  can you help me in setup for the  the local build. I  am stuck  with docker configuration.

**Comment by eviljeff** [comment]
@shiri1248 it'll probably be easier to come talk to us on #amo on irc if you followed the steps on https://addons-server.readthedocs.io/en/latest/topics/install/docker.html fully

**Comment by SIMRAN1** [comment]
@jvillalobos May I work on this issue ??

**Comment by eviljeff** [comment]
@SIMRAN1 looks like the other people who've expressed an interest have become stuck actually setting up addons-server fully.  So make sure you can run and submit an add-on through devhub on your local addons-server.  (links in previous comments).

I'll note we didn't say this was a good first bug, both because it requires a fully set up local addons-server, and also because it will possibly involve writing some tests (or possibly just changing some)

**Comment by SIMRAN1** [comment]
I have done the setup and now trying to solve this issue!

**Comment by eviljeff** [comment]
@SIMRAN1 great, let us know how you get on and if you have any difficulties.

**Comment by bobsilverberg** [comment]
@eviljeff / @jvillalobos This issue is part of the project: [Add-ons Q4 2018: Legacy frontend removal dependencies](https://github.com/orgs/mozilla/projects/19), and as such I believe it's something we want to be completed fairly soon. It seems that a number of contributors have expressed an interest in working on it, but not much has been accomplished. Is this something we should work on ourselves to just get it taken care of? How important is this to removal of the legacy site?

**Comment by eviljeff** [comment]
yeah I agree - it's not a blocker to removing the legacy pages.  (perhaps shouldn't be in the project at all)

**Comment by championshuttler** [comment]
Here you go @vaibhavk! , You can try to work on it to get started with AMO :)

**Comment by championshuttler** [comment]
Here you go @abhi-khandelwal
