### ISSUE TITLE
Restrict approval for internally signed add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9343]
Internally signed add-ons come with a lot of power, so we want to automatically disable auto-approval for them.

* Auto-approval should be disabled through the regular way (which means admins will be able to click the "Enable auto-approval" button on the review page, if they see fit).
* A note should be added to the version that this file has been internally signed.
* The add-on should be automatically flagged for admin review.

**Comment by diox** [comment]
> Auto-approval should be disabled through the regular way (which means admins will be able to click the "Enable auto-approval" button on the review page, if they see fit)

Auto-approval is disabled per add-on, internal signature is per file. Do we need to do anything special when a new version *without an internally signed file* is uploaded on an add-on that had its previous version internally signed and had auto-approval disabled ? 

Said differently: at the moment we don't know the reason behind auto approval being disabled for such an add-on, do we need to start recording that it was done automatically so that we can revert the flag if a "normal" version gets uploaded later?

> A note should be added to the "Private Whiteboard" that this is an internally signed add-on.

Do we overwrite any existing info present in the private whiteboard ? Or append ? prepend ? Do nothing ?

**Comment by wagnerand** [comment]
> Auto-approval is disabled per add-on, internal signature is per file. Do we need to do anything special when a new version without an internally signed file is uploaded on an add-on that had its previous version internally signed and had auto-approval disabled ?

> Said differently: at the moment we don't know the reason behind auto approval being disabled for such an add-on, do we need to start recording that it was done automatically so that we can revert the flag if a "normal" version gets uploaded later?

That would be nice, but given the amount of internally signed add-ons is very low currently, it's probably not worth the effort. Admins can re-enable auto-approval manually when an add-on switches from the internal cert to the regular one.

> Do we overwrite any existing info present in the private whiteboard ? Or append ? prepend ? Do nothing ?

To simplify things, I changed it to add a note the version instead of the whiteboard. That way we don't have to deal with updates that change this state or existing content etc.

**Comment by diox** [comment]
Main issue with this is the following scenario:
- Add-on is created with internally signed version, so auto-approval gets disabled
- Admin reviewers enables auto-approval for this add-on
- New version gets uploaded, it's internally signed

At this point, I suppose the admin decision should stick, but since auto-approval is the default, we currently have no way of making the distinction. We'll have to add a different value for `auto_approval_disabled`, but it's a boolean, so it's messy...

**Comment by diox** [comment]
@wagnerand could you tell me if the last solution proposed in my previous comment would work for you ? That'd be ideal. Otherwise I'll implement one of the other two.

**Comment by wagnerand** [comment]
@diox the third approach sounds ok to me.

**Comment by diox** [comment]
Should we do this for all types of add-ons ? I'm worried that it might break release engineering's expectations for langpacks, for instance. Granted, it will only be for new ones, but still might affect the release process if new langpacks can stay unapproved for a while because they're internally signed and therefore don't get auto approval initially.

**Comment by jvillalobos** [comment]
I think it's okay to exempt language packs.

**Comment by AlexandraMoga** [comment]
@diox  do you know where can I find a Mozilla signed webextension? The only examples I know of are legacy extensions (mentioned in #5619), which means auto-approval will have no effect on those

**Comment by diox** [comment]
I don't. But you can see the state of the flag controlling whether or not auto-approval is enabled in the review page if you're an admin reviewer, regardless of whether or not the current version of the add-on is a legacy or webextension.

**Comment by AlexandraMoga** [comment]
I've uploaded a mozilla sigend extension on stage and these are my results:

- at add-on submission, a Note to Reviewers is added automatically to mark the fact that the add-on is internally signed
![image](https://user-images.githubusercontent.com/31961530/45759197-1285a280-bc30-11e8-8ab2-e7d1424d2092.png)

- after submission, in Reviewer Tools, the add-on is marked with an Admin Code review Flag and auto-approval is disabled (the button state is set to Enable auto-approval)

![image](https://user-images.githubusercontent.com/31961530/45759360-6f815880-bc30-11e8-9bf9-f16eb9168790.png)




>  Only disable auto-approvals on internally signed add-ons once, for the initial upload. After that, don't touch the value at all at upload time.

After manually approving the add-on, I've submitted a new version (internally signed) which was also marked with an auto-apprval disabled flag. I've replaced the instal.rdf with a manifest.json file to make it a webextension (not sure if it is the best approach) but my intent was to see if the next version will be auto-approved

This is the extension - https://reviewers.addons.allizom.org/en-US/reviewers/review/mozilla-signed

**Comment by diox** [comment]
The flag does not change. If you want to see the next version being auto-approved, you'll have to enable auto-approval and then submit a webextension, but doing so will make the signature invalid (unless you do have a valid internally signed webext) - I don't know if we check that, though.

**Comment by AlexandraMoga** [comment]
I think I did manage to 'artificially' create a mozilla signed webextension by using the contents of a legacy package and replacing the install.rdf with a manifest.json

This is the example (which will now look auto-approved because I've enabled auto-approval): https://reviewers.addons.allizom.org/en-US/reviewers/review/mozilla-signed2

The submission went as expected:
- 1st version had an auto-approval disabled flag
- was marked for admin review automatically
- included a note to reviewers to mark it as mozilla internally  signed

After enabling auto-approval from the add-on review page, the second submitted version was auto-approved.

I'm marking this issue as verified fixed on stage with FF62, WIn10x64
