### ISSUE TITLE
Make reviews not tied to a particular add-on version, from the perspective of the API

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#9393]
This is a follow-on to https://github.com/mozilla/addons-frontend/issues/4529. From the front end's perspective, we would like each add-on to have one review per user. When we request reviews we would not pass a `version` parameter, and we would expect to get back one review per user. When we create or update a review we would likewise not pass a `version` and would expect the "single" review for the user to be created or updated.

We could make this work on the front end with the current APIs, but feel that it would be more efficient to have it taken care of by the back end. We are considering this feature for delivery this quarter, but it might get pushed to Q4.

@diox Can you comment on the likelihood of this being implemented this quarter/next quarter?

**Comment by diox** [comment]
We'd need to delete "duplicate" reviews from the database before doing this, since we have a lot of reviews that were posted on different versions - we'd need to delete them and only keep the last one for each user+addon. Then rework the code and database indexes.

I doubt this will happen this quarter, it'd take a few days of work to get everything sorted out. It would be a lot easier to do without the legacy site in the way, too.

**Comment by bobsilverberg** [comment]
Thanks @diox. I believe we are planning to address this issue with a frontend fix in the near future, but it would be nice to implement a "real" fix in the back end eventually.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-167
