### ISSUE TITLE
Dark theme not found

### ISSUE THREAD

**Issue by RobeDesign** [mozilla/addons-server#9404]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Theme download does not exists.

### What happened?

no download page from "add to thunderbird" button in "https://addons.thunderbird.net/en-US/thunderbird/addon/macos-sierra-dark/"

### What did you expect to happen?

theme download

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment]
Hi, unfortunately the Thunderbird add-ons site currently has the wrong link for filing issues.

Please can you re-file this issue here: https://github.com/thundernest/addons-server/issues/new

The corrected link for filing issues on addons.thunderbird.net has been merged and should be deployed in the not too distant future.
