### ISSUE TITLE
Akismet reports are recorded when editing an unlisted add-on from dev-hub

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9479]
STR:

1. Log in to Developer Hub
2. Submit an unlisted add-on
3. Edit its metadata from dev hub - Edit information page
4. With an admin account check the records from Akismet reports

Actual result:
There is a report logged when editing unlisted add-ons'  metadata

Expected result:
Since unlisted add-ons are not analyzed with Akismet during submission, there shouldn't be a report logged if their data is changed via dev-hub

Notes:
- reproduced on AMO -dev with FF62, Win10x64
- a report is recorded also for unedited metadata (i.e a report for summary is sent even if only the name was changed)

![unlisted edit report](https://user-images.githubusercontent.com/31961530/45877168-9dd47480-bda5-11e8-9333-f8901cc6b7e7.gif)

**Comment by eviljeff** [comment]
This was also a deliberate choice - there's an edge case with add-ons that have unlisted and then listed versions.  Here's what happens now:
- submit an addon xpi as unlisted - we don't comment_check the addon metadata, but do save them to the Addon listing on AMO.  The metadata contains a spammy name and/or summary.
- submit a later xpi as listed - we _do_ check the xpi, but don't use the metadata in that xpi for the Addon listing, because it's a new version rather than a new add-on.
- the details step is shown because the addon is missing a category.  We now check the name and summary because it's shown in the form so we catch the spam. 
-  If there was already a category set we wouldn't show the details step though (so the spam would get through), which you can only do in the edit screen, so we're checking there on unlisted to prevent spammy metadata being set on an unlisted-only addon.

There are other solutions to the edge case (with their own drawbacks) but I figured unlisted-only add-ons wouldn't generally be changing their details in devhub anyway because those details aren't exposed anywhere.
