### ISSUE TITLE
So much middleware

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#949]
Does the API really need all this middleware? Can we have the API end points served with less middleware? 

```
   # AMO URL middleware comes first so everyone else sees nice URLs.
    'django_statsd.middleware.GraphiteRequestTimingMiddleware',
    'django_statsd.middleware.GraphiteMiddleware',
    'amo.middleware.LocaleAndAppURLMiddleware',
    # Mobile detection should happen in Zeus.
    'mobility.middleware.DetectMobileMiddleware',
    'mobility.middleware.XMobileMiddleware',
    'amo.middleware.RemoveSlashMiddleware',

    # Munging REMOTE_ADDR must come before ThreadRequest.
    'commonware.middleware.SetRemoteAddrFromForwardedFor',

    'commonware.middleware.FrameOptionsHeader',
    'commonware.middleware.StrictTransportMiddleware',
    'multidb.middleware.PinningRouterMiddleware',
    'waffle.middleware.WaffleMiddleware',

    'csp.middleware.CSPMiddleware',

    'amo.middleware.CommonMiddleware',
    'amo.middleware.NoVarySessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'commonware.log.ThreadRequestMiddleware',
    'apps.search.middleware.ElasticsearchExceptionMiddleware',
    'session_csrf.CsrfMiddleware',

    'api.middleware.RestOAuthMiddleware',
    # This should come after authentication middleware
    'access.middleware.ACLMiddleware',

    'commonware.middleware.ScrubRequestOnException',
```

**Comment by diox** [comment]
Here is a detailed analysis of why we need each of those middlewares.

```
    'django_statsd.middleware.GraphiteRequestTimingMiddleware',
    'django_statsd.middleware.GraphiteMiddleware',
```

Needed for datadog dashboards. Would be nice if they were combined into a
single middleware, though.

```
    'olympia.amo.middleware.SetRemoteAddrFromForwardedFor',
```

Needed to make `REMOTE_ADDR` correct.

```
    'dockerflow.django.middleware.DockerflowMiddleware',
```

Not currently on master, but soon will be. Needed for logging. It sends the request.summary event log that our logging
platform expects.

```
    'olympia.amo.middleware.LocaleAndAppURLMiddleware',
```

Needed for app/locale URLs redirections. The API skips some of this, but still
needs part of it to activate the right language.

```
    'mobility.middleware.DetectMobileMiddleware',
    'mobility.middleware.XMobileMiddleware',
```

Should go away with https://github.com/mozilla/addons-server/issues/5055

```
    'olympia.amo.middleware.RemoveSlashMiddleware',
```

Only active for 404s. I don't like it and would like to remove it, though.

```
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
```

Needed for security-related HTTP headers

```
    'multidb.middleware.PinningRouterMiddleware',
```

Needed to keep requests following a write on the primary database replica

```
    'waffle.middleware.WaffleMiddleware',
```

Needed for more complex waffles doing partial rollouts with cookies. Not sure
how useful it is, but it's inactive if we don't use those features.

```
    'csp.middleware.CSPMiddleware',
```

Needed to set CSP headers.

```
    'corsheaders.middleware.CorsMiddleware',
```

Needed to set CORS headers.

```
    'olympia.amo.middleware.CommonMiddleware',
```

Mostly useful for ETag calculations. Could also partly replace
`RemoveSlashMiddleware` if we were to enable `APPEND_SLASH` (our version does
a little more work, though)

```
    'olympia.amo.middleware.NoVarySessionMiddleware',
```

Needed for sessions. Since we use signed cookies for sessions this doesn't do
much when we don't use sessions like in the API.

```
    'django.contrib.messages.middleware.MessageMiddleware',
```

Needed for temporary messages. Doesn't do much if you are not using them.

```
    'olympia.amo.middleware.AuthenticationMiddlewareWithoutAPI',
```

Needed for auth. API skips this and uses its own thing.

```
    'olympia.search.middleware.ElasticsearchExceptionMiddleware',
```

Needed to catch elasticsearch exceptions and display an error message. Not
very useful but doesn't really hurt either.

```
    'session_csrf.CsrfMiddleware',
```

Needed for CSRF protection.

```
    'olympia.access.middleware.UserAndAddrMiddleware',
```

Needed to persist user and ip in the current thread, which logging uses.

```
    'olympia.amo.middleware.ScrubRequestOnException',
```

Needed to clean up potential passwords etc in exceptions.


My conclusion to that is that most of those are useful and perf gains will have
to be gained elsewhere, I don't believe maintaining a second set of middlewares
(which would mean setting up a different settings module to serve API requests)
is worth the maintenance hassle. 

From looking at newrelic, the most time we lost in middlewares in API requests is 2ms total for some requests and that's *entirely* in `LocaleAndAppURLMiddleware`, because it's activating a language. The rest never show up.
