### ISSUE TITLE
version is missing in the response to a PATCH when you have updated a reply

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#9550]
STR:

Submit a PATCH request to the `/api/v4/ratings/rating/` endpoint for a *reply*.

Expected result:

The response contains a full rating object as documented at https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#edit.

Actual result:

The rating object returned is missing the properties for `version.id` and `version.version`.

Note that I am not sure if this is actually expected or not. From our perspective we don't in fact need it for a reply, but I noticed it was missing and that is not documented.

**Comment by diox** [comment]
Ah yeah, it's because it's using the reply serializer, and it does omit those fields. We could refactor things out to use the full one, but it might be messy. I'd be in favor of just documenting it.

**Comment by bobsilverberg** [comment]
> I'd be in favor of just documenting it.

That works for me, @diox.

**Comment by AlexandraMoga** [comment]
Documentation updated with the missing references:

I see that the issue was referring to the https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#edit endpoint but the documentation was more accurately updated in the https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#reply section.


![image](https://user-images.githubusercontent.com/31961530/48426722-fefa4200-e76f-11e8-8610-1fadf47b1200.png)
