### ISSUE TITLE
Prevent unsupported image types being selected in the wizard file selector

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#9667]
One of the theme reviewers noticed that [this theme](https://addons.mozilla.org/en-US/firefox/addon/whatsapp-mitlesen/) looks extremely pixelated in the "preview image" on AMO, but it looks fine when it is installed. 

Could we get the pixelation from preview to match how it appears upon installation? That would really help out the theme reviewers and end users.

**Comment by eviljeff** [comment]
They've used a `.ico` file for the header (an icon file -wtf?!) for some reason only known to the person who uploaded it.  It's not a supported format on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme and I'm surprised it works at all (either in the preview or in Firefox).

**Comment by caitmuenster** [comment]
Thanks @eviljeff for fixing my bad grammar in the title of this issue. :) 

Good to know that it was an .ico file! Can we restrict the types of files to only be the ones that are supported? I'm thinking that if you upload a file type that isn't supported, the dev should see a message that says "This file type is not supported" and they shouldn't be able to proceed with the submission.

**Comment by eviljeff** [comment]
I can add a restriction to the file selector in the wizard but that's only a partial fix - can you log an issue on https://github.com/mozilla/addons-linter too to stop xpis with unsupported image types from being submitted at all?

**Comment by caitmuenster** [comment]
Thanks! [Issue filed](https://github.com/mozilla/addons-linter/issues/2243).

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @eviljeff

**Comment by miphilomath** [comment]
Hey @caitmuenster @eviljeff, I would like to work on the issue. Can you please guide me through this? 

Thanks

**Comment by eviljeff** [comment]
@miphilomath hi, after you've gone through the steps in the link @caitmuenster provided, the changes are pretty small.  Just change the attribute name in the html here https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/addons/submit/wizard.html#L38 to `accept` from `data-allowed-types` and change the string to be comma `,` separated instead of pipe `|`.  (and `image/svg` should be `image/svg+xml`.

After that, we should have a bit of javascript validation really, as it's easy for a user to override the file selector dialog and select another file.  The JS that selects the file is https://github.com/mozilla/addons-server/blob/master/static/js/zamboni/static_theme.js#L11:L14 - if we return `null` from that function if it's a non-image file I think that's enough.

**Comment by miphilomath** [comment]
Okay! I will send the patch ASAP and will ping if need any help :)

**Comment by AlexandraMoga** [comment]
@eviljeff since https://github.com/mozilla/addons-linter/issues/2051 is a p2 now, shouldn't we increase the priority for this issue as well?

**Comment by eviljeff** [comment]
IMO, no, this issue is just adding a bit of extra validation to be more user friendly. You can't ever trust client-side JavaScript to block invalid submissions - especially when the wizard is just a wrapper around the normal zip file upload so you could upload through there.  The linter issue is the priority.

**Comment by eviljeff** [comment]
@AlexandraMoga it's a bit of an edge case, and I'm not sure we can detect it client side, but you can file a follow-up (likely a p4)
