### ISSUE TITLE
LWT migration - newly migrated themes are showing as trending

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9725]
After migrating some really old themes (like, 10 years old) they are suddenly showing as trending on the homepage.  It might be something weird with -dev stats, or it might be a flaw with how statistics are being migrated from the LWT to the static theme.

Part of #9673

**Comment by jvillalobos** [comment]
As a reminder, there's https://github.com/mozilla/addons-server/issues/7088 open for the "hotness" metric not working correctly for themes. Don't know if that could be related.

**Comment by diox** [comment]
Because of what's going on in #7088 (hotness is 0 for all existing personas because we never handled that, and static themes uploaded by users, because too recent) any hotness value is going to make the affected add-ons show up at the top of the trending list.

It should fix itself once all personas are migrated, but also note that you need at least 1000 users in the past week to have a hotness of more than 0 at the moment.

**Comment by eviljeff** [comment]
> <@eviljeff>so to simplify your explanation it's because we calculate a hotness value during the migration but it's been calculated incorrectly (because no check about >1000 users)
> <@diox>yes
> really the value we copy (Persona.movers) is not bad, it's just not in line with what we do for the rest of the add-ons we have

**Comment by AlexandraMoga** [comment]
I've checked AMO -dev and there are no static themes listed on the Trending themes shelf on Themes Homepage or Category pages:
![image](https://user-images.githubusercontent.com/31961530/47291748-76273500-d60d-11e8-958d-7010bcb0707e.png)

Also, there are no static themes on top of the Trending + Themes search results list:
https://addons-dev.allizom.org/en-US/firefox/search/?sort=hotness&type=statictheme%2Cpersona

based on these results, I'm marking the issue as verified fixed.
