### ISSUE TITLE
Remove all entries in the DB that have addons.mozilla.org as the host part of the link

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#9735]
See also: #9012 

---

We should remove AMO links in the following fields:

- add-on homepage
- contribution URL
- support URL

Quoting @diox:

> We need to write something to do that yes. It probably needs to be a task fired from the process_addons command.

**Comment by diox** [comment]
Note that we should not do this for *all* entries. Linking to AMO in a description is perfectly fine, for instance. The problem is linking to AMO in a field meant for a single URL, such as the support site URL or homepage URL for addons.

Because of this and because those fields are translated and the data lives in the `translations` table, you can't blindly write a migration for this, and that's why it probably needs to be a task fired from the `process_addons` command.

**Comment by willdurand** [comment]
> Note that we should not do this for _all_ entries. Linking to AMO in a description is perfectly fine, for instance. The problem is linking to AMO in a field meant for a single URL, such as the support site URL or homepage URL for addons.

ah right, I have updated the issue description.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF63, Win10x64

- links pointing to AMO were removed from the following fields: support site, homepage
- AMO links added in other text fields, (i.e summary, description) were not affected

**Comment by AlexandraMoga** [comment]
Verified fixed in stage as well
