### ISSUE TITLE
LWT Migration - theme delete email is being sent for migrated LWTs

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9761]
From monitoring Kibana logs I noticed we're sending out the delete email when we delete the LWT after it's been migrated to a static theme 🐼 

Part of #9673

**Comment by AlexandraMoga** [comment]
@eviljeff  I guess this can also be verified only after https://github.com/mozilla/addons-server/issues/9673 is fixed.
We could migrate one of my themes to test it, but I figured that this would require extra work from your side.

**Comment by eviljeff** [comment]
yeah let me/us know if you want to verify this now.

**Comment by AlexandraMoga** [comment]
@eviljeff ok, so if it is not too much trouble, you could try to migrate these themes (they are mine). 

- id = 495369 - https://addons-dev.allizom.org/en-US/firefox/addon/test-theme-icon-urls/
- id = 495371 - https://addons-dev.allizom.org/en-US/firefox/addon/test-theme-icon-url-three/

If the issue is fixed, I shouldn't see any delete confirmation notifications in Admin Fake email log,

**Comment by AlexandraMoga** [comment]
There are no Theme deletion emails received in the Fake email log.

I'm marking this issue as verified fixed
