### ISSUE TITLE
Search: searching for "Website vertrauen" doesn't find WOT - Sicher surfen highest in search results

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9804]
Follow up for #6838 

1. Load AMO stage
2. Do the following search: https://addons.allizom.org/de/firefox/search/?q=Website%20vertrauen

Expected result:
[WOT - Sicher surfen](https://addons.allizom.org/de/firefox/addon/wot-safe-browsing-tool/?src=search) is found highest in search results list, because it includes the "Website vertrauen" string in its description

Actual result:
[WOT - Sicher surfen](https://addons.allizom.org/de/firefox/addon/wot-safe-browsing-tool/?src=search) can be found only on [page 3](https://addons.allizom.org/de/firefox/search/?page=3&q=Website%20vertrauen)

![image](https://user-images.githubusercontent.com/31961530/47484019-50837100-d843-11e8-905b-b78787d28b15.png)

**Comment by diox** [comment]
The results that appear first have "Website" in their name, but not "vertrauen". Need to investigate this more, I wonder if this is because of the fuzzy match on the name (which does *not* specify `"operator": "and"`). Will know more by reproducing locally and looking at the explanation for the score.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO stage with FF63, Win10x64

WOT - Sicher surfen is now found when searching for "Website vertrauen"

![image](https://user-images.githubusercontent.com/31961530/48825634-a3801380-ed70-11e8-9098-c5dd75a44e24.png)
