### ISSUE TITLE
Remove compatibility-related database tables

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9831]
Following #9515, these database tables are no longer used and should be removed:
- `compatibility_reports`
- ~~`compat`~~
- `compat_totals`

cc @wagnerand to confirm that we can do that.

**Comment by wagnerand** [comment]
* `compatibility_reports` should be fine to get removed.
* `compat` I couldn't find.
* `compat_tools` I am not sure what it was used for, but it seems it was updated last in August 2016.

**Comment by diox** [comment]
Ah, `compat` didn't truly exist, it was just a trick to use the model, so we're fine :)

**Comment by diox** [comment]
@championshuttler it's all yours.

**Comment by championshuttler** [comment]
Hi @diox , I am opening it (because we do not have much good first bugs to working on) up for new contributors who might be interested in working on it. I am providing some info about how to go with this bug. 

We need to add new `SQL` file under `/src/olympia/migrations` with name something like `1053-remove-compatibility-related-tables.sql` with code like:
```
DROP TABLE `compatibility_reports`;

```

Make sure that we need to add more SQL queries for other tables mentioned [above](https://github.com/mozilla/addons-server/issues/9831#issue-374755384. 

@diox can you please remove the `contrib:assigned` lable and correct me If i mentioned something wrong here. Thanks

**Comment by championshuttler** [comment]
@miphilomath Go for it!

**Comment by miphilomath** [comment]
> Hi @diox , I am opening it (because we do not have much good first bugs to working on) up for new contributors who might be interested in working on it. I am providing some info about how to go with this bug.
> 
> We need to add new `SQL` file under `/src/olympia/migrations` with name something like `1053-remove-compatibility-related-tables.sql` with code like:
> 
> ```
> DROP TABLE `compatibility_reports`;
> ```
> 
> Make sure that we need to add more SQL queries for other tables mentioned [above](https://github.com/mozilla/addons-server/issues/9831#issue-374755384).
> 
> @diox can you please remove the `contrib:assigned` lable and correct me If i mentioned something wrong here. Thanks smile .

Just to understand the code ethics better of this project, what decides the file name to be added under `./src/olympia/migrations`?

**Comment by championshuttler** [comment]
> Just to understand the code ethics better of this project, what decides the file name to be added under `./src/olympia/migrations`?

File name I mentioned in comment looks good I guess.
