### ISSUE TITLE
Redirect thunderbird addon urls without the locale too

### ISSUE THREAD

**Issue by ClivePerk** [mozilla/addons-server#9836]
Clicked on Download in Mozilla Support page to get add-on ImportExport Tools for Windows Mail

got message - couldnt find link

**Comment by eviljeff** [comment]
I'm guessing the page was https://support.mozilla.org/en-US/kb/switching-thunderbird and the addon was https://addons.mozilla.org/thunderbird/addon/importexporttools/

@ClivePerk thanks for letting us know (though, to be honest, it would have been quicker to diagnose your problem if you'd included some links to whatever page/link didn't work).  The correct link is https://addons.mozilla.org/en-US/thunderbird/addon/importexporttools/

**More detail**
We have nginx redirects for thunderbird/seamonky addon urls, but only for the full url, including locale code.  The full url is https://addons.mozilla.org/<locale>/<app>/addon/<slug>.   It used to work because addons-server still supported Thunderbird underneath so django would redirect https://addons.mozilla.org/thunderbird/addon/<slug>/ to https://addons.mozilla.org/en-US/thunderbird/addon/<slug>/ and then that would be redirected by nginx. 

But after #8958 dropped Thunderbird support from addons-server the middleware didn't "know" about Thunderbird any more so stopped redirecting.

We need to update https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L209 to redirect a url like https://addons.mozilla.org/thunderbird/addon/importexporttools/ direct to thunderbird addons too.  (Or a second rule)

**Comment by eviljeff** [comment]
#6390 was the original issue

**Comment by jvillalobos** [comment]
I've seen a couple of reports of this, so it's likely many Thunderbird users are hitting these broken URLs.

**Comment by Mannshoch** [comment]
especially at these times where lightning isn't anymore compatible with the actual thunderbird version. :thinking:

**Comment by vcarciu** [comment]
Verified as fixed in both Stage and -dev.
