### ISSUE TITLE
Explore the possibility of returning the file path of jsi18n.js as "/static/js/jsi18n-%locale%.js", or generating it as a physical file at deployment time

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#9861]
### Describe the problem and steps to reproduce it:
This relates to https://bugzilla.mozilla.org/show_bug.cgi?id=1501687.

We'd like to request for the -dev team to explore the possibility of either returning the file path for jsi18.js as `/static/js/jsi18n-%locale%.js` (as requested in that ticket), or, generating physical versions of this file and put it in `static/js/` directory at deployment time.

This helps avoid having to configure Nginx for special cases, as well as making accessing this file consistent as other script files (from Nginx point of view).

### What happened?
n/a

### What did you expect to happen?

Just to see if you can do this or not. If it's not feasible to do it in the app, we can fall back to do it at the Nginx level.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
I think we can do it.

We'd make a management command (with `requires_system_checks = False` to avoid database connections) that wraps what the view does, for each language we support, and dump the resulting files in the `static/` directory. It would be called [after compiling `.mo` files, but before the `collectstatic` step](https://github.com/mozilla/addons-server/blob/5397f97c32e7c9ffa57f102208d2a20bf3a7148f/Dockerfile.deploy#L97) when building the image.

Then we could just use the `{{ static() }}` function in templates when calling it, since it'd be just a regular static file. Maybe write a wrapper to avoid concatenating the locale in the path in templates.

**Comment by AlexandraMoga** [comment]
@diox could you please add some STR for this issue?

**Comment by diox** [comment]
Verified manually earlier on dev. 
```
<mat> (...) now you can see addons-server pages load the new jsi18n directly from the CDN, as a normal static file https://addons-dev-cdn.allizom.org/static/js/i18n/en-US.js?b=5ca6f5d2-5c3dd3ac in english, https://addons-dev-cdn.allizom.org/static/js/i18n/fr.js?b=5ca6f5d2-5c3dd3ac in french
```
