### ISSUE TITLE
A search for `ublock` should return `uBlock Origin` as the 1st result, and not `µBlock`

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-server#9876]
### Describe the problem and steps to reproduce it:
1. Search AMO for `ublock`.

### What happened?
1st result is [µBlock](https://addons.mozilla.org/en-US/firefox/addon/ublock/)
2nd result is [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)
<details>
 <summary>Screenshot</summary>

![screenshot_2018-11-03 search results for ublock add-ons for firefox en-us](https://user-images.githubusercontent.com/8336638/47935437-4bd45200-df00-11e8-874d-76891e4e9d13.png)

</details>

### What did you expect to happen?
Given that the search query `ublock` is a substring of `uBlock Origin` but not `µBlock`, and that the former has much higher downloads and better rating than the latter, I expect it to be the first result.

### Anything else we should know?
There are [multiple](https://twitter.com/gorhill/status/1019975271443771392) other [good](https://github.com/gorhill/uBlock/wiki/uBlock-Origin-is-completely-unrelated-to-the-web-site-ublock.org) reasons to avoid promoting `µBlock` over `uBlock Origin` but I get that AMO might not want to concern itself with these.

**Comment by diox** [comment]
They are currently relatively close in terms of matching for "ublock". Neither get the boost for an exact match, because neither is an exact match against the "ublock" string without any transformations, but they both benefit from other rules we apply with the normalization added. Crucially, µBlock also gets a boost from matching against the author name. We do boost with popularity (not on ratings, which is an interesting idea), but that's not enough to overcome the difference (and I'm planning to reduce the popularity boost anyway).

I'm going to keep this opened for now to look at this later once we're done with all the improvements we have planned for search, because it's possible it might affect this slightly (the consequences of what the work in https://github.com/mozilla/addons-server/issues/6898 might have an impact, even if both still won't be an exact match) and give uBlock origin the advantage. Frankly though, and I say this as a big fan of uBlock origin myself, I don't think this is really a bug. You can easily make the case that users searching for "ublock" want µBlock as the first result as much as uBlock origin.

**Comment by jvillalobos** [comment]
wfm now
