### ISSUE TITLE
Allow upload of source code (and release/reviewer notes) using the API

### ISSUE THREAD

**Issue by ElectronicManuel** [mozilla/addons-server#9913]
When uploading an addon using the API (https://addons-server.readthedocs.io/en/latest/topics/api/signing.html) there is no way to upload the source files automatically.

Steps:
1. push new version of the addon to repo
2. automated deployment deploys version to the mozilla store using the api
3. I navigate to the developer hub and upload the sources manually

It would be nice to have an api for uploading the source files in order to reduce manual intervention.

**Comment by stoically** [comment]
It might also be nice to allow attaching release- and reviewer-notes when uploading, so publishing could be completely automated.

**Comment by IgnusG** [comment]
Any update on this issue? Just curios since it has been a while

**Comment by nhedger** [comment]
I'd like to help to implement this feature but I am unfamiliar with the codebase. Would anyone care to guide me through?

**Comment by AlexandraMoga** [comment]
@eviljeff I've verified the new API properties on -dev and these are my results. Please have a look at the source code section in particular because I feel the documentation is not very clear about it or I'm not understanding it fully. 

Release Notes:
- release notes can be set at add-on submission time by adding a `"version":{"release_notes":{"lang":"string"}}` field in the JSON request data
- release notes can be added when a new version is submitted for an existing add-on and can also be edited by sending a version PATCH request


Source code Upload:
- source code can't be uploaded at add-on creation time (i.e. when we post the JSON request data for the first add-on version); if I want to add source code to the first version, I must send a [PATCH request](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#patch--api-v5-addons-addon-(int-addon_id|string-addon_slug|string-addon_guid)-versions-(int-id)-) with the source file after the version has been created :question:
- source code can be uploaded when a new version is created; I can provide the `source` file and the `upload` uuid as form parameters in the [version POST request form data](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#post--api-v5-addons-addon-(int-addon_id|string-addon_slug|string-addon_guid)-versions-); the documentation says that other fields can be set at this stage as well, such as `compatibility` or other fields from version creation, but so far I wasn't able to send them; for example, for `"compatibility": ["firefox"]` I'm getting a  `"compatibility": ["Invalid value"]` error :question:
- version source code files can be updated through a version PATCH request :heavy_check_mark: 
- only supported archives (`.zip, .tar.gz, .tgz, .tar.bz2`) can be uploaded  :heavy_check_mark:


As a side note, there is a small error in the [API docs](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#post--api-v5-addons-addon-(int-addon_id|string-addon_slug|string-addon_guid)-versions-):
![image](https://user-images.githubusercontent.com/31961530/152815730-d038479f-5c16-4db2-8b66-937bdc4f0886.png)
I think this field was reversed and should be `source: string|null`.

**Comment by eviljeff** [comment]
> @eviljeff I've verified the new API properties on -dev and these are my results. Please have a look at the source code section in particular because I feel the documentation is not very clear about it or I'm not understanding it fully.
> 
> Release Notes:
> 
>     * release notes can be set at add-on submission time by adding a `"version":{"release_notes":{"lang":"string"}}` field in the JSON request data
> 
>     * release notes can be added when a new version is submitted for an existing add-on and can also be edited by sending a version PATCH request
> 
> 
> Source code Upload:
> 
>     * source code can't be uploaded at add-on creation time (i.e. when we post the JSON request data for the first add-on version); if I want to add source code to the first version, I must send a [PATCH request](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#patch--api-v5-addons-addon-(int-addon_id%7Cstring-addon_slug%7Cstring-addon_guid)-versions-(int-id)-) with the source file after the version has been created ❓

Interesting.  I can't see any particular reason why it wouldn't work, but I didn't add tests for it. Can you file a follow-up issue?

>     * source code can be uploaded when a new version is created; I can provide the `source` file and the `upload` uuid as form parameters in the [version POST request form data](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#post--api-v5-addons-addon-(int-addon_id%7Cstring-addon_slug%7Cstring-addon_guid)-versions-); the documentation says that other fields can be set at this stage as well, such as `compatibility` or other fields from version creation, but so far I wasn't able to send them; for example, for `"compatibility": ["firefox"]` I'm getting a  `"compatibility": ["Invalid value"]` error ❓

How are you specifying the values with a formdata formatted request?  (I'm a little unclear myself on how complex data structures that are easy in JSON format would be specified as formdata)
 
> As a side note, there is a small error in the [API docs](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#post--api-v5-addons-addon-(int-addon_id%7Cstring-addon_slug%7Cstring-addon_guid)-versions-): ![image](https://user-images.githubusercontent.com/31961530/152815730-d038479f-5c16-4db2-8b66-937bdc4f0886.png) I think this field was reversed and should be `source: string|null`.

whoops, yeah

**Comment by AlexandraMoga** [comment]
> > ```
> > * source code can't be uploaded at add-on creation time (i.e. when we post the JSON request data for the first add-on version); if I want to add source code to the first version, I must send a [PATCH request](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#patch--api-v5-addons-addon-(int-addon_id%7Cstring-addon_slug%7Cstring-addon_guid)-versions-(int-id)-) with the source file after the version has been created ❓
> > ```
> 
> 
> Interesting.  I can't see any particular reason why it wouldn't work, but I didn't add tests for it. Can you file a follow-up issue?
> 
> 
> > ```
> > * source code can be uploaded when a new version is created; I can provide the `source` file and the `upload` uuid as form parameters in the [version POST request form data](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#post--api-v5-addons-addon-(int-addon_id%7Cstring-addon_slug%7Cstring-addon_guid)-versions-); the documentation says that other fields can be set at this stage as well, such as `compatibility` or other fields from version creation, but so far I wasn't able to send them; for example, for `"compatibility": ["firefox"]` I'm getting a  `"compatibility": ["Invalid value"]` error ❓
> > ```
> 
> 
> How are you specifying the values with a formdata formatted request?  (I'm a little unclear myself on how complex data structures that are easy in JSON format would be specified as formdata)

@eviljeff I think this all boils down to your last question, because I haven't found the best way to send JSON with a multipart/form-data request yet. I'm using Postman, which has an integrated feature that allows you to specify the content type for each `key:value` sent, but I'm not sure how to use this for our case, since there is no `key` to encompass the whole JSON data we'd like to send when creating a new add-on. 

![image](https://user-images.githubusercontent.com/31961530/152973734-7c7bfe61-72e1-4c57-ad5e-07613de0b429.png)

**Comment by eviljeff** [comment]
@AlexandraMoga I've played around locally in tests and I'm not there _is_ a way to submit complex (lists or objects with nested values) without using JSON.  
(If there is, for version create then the key would be the object key, e.g. `release_notes` and I guess the value would be `{"en-US": "release notes!"}`, with the content type of `application/json`, but I'm not confident that'll work - I couldn't get it to work in test cases and my postman foo is weak)

Currently, I can't think of any way that source could be submitted as a nested value - i.e. during addon create, so I think that's an unsupported use-case.  If there's no way to specify complex values at the same time as specifying a source file either (i.e. for version create/update) I'll update the api docs to make that clear.

**Comment by eviljeff** [comment]
> So basically, if I want to attach source code, I'm limited to sending only the source file and the `upload:uuid`:
> 
> > I'll update the api docs to make that clear.
> 
> Does this mean that you will update the [Version sources docs](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-sources) to no longer include the `compatibility` bit from the required Form parameters section?

yeah.  Only simple values can be sent in a multipart form, so `upload` and `license` (because it's a slug). And sending the source during an Add-on create doesn't work.
