### ISSUE TITLE
Determine Android compatiblity for static themes

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#9967]
In FF 65, a first step to support static themes (ST) on Android will be available (see also: https://bugzilla.mozilla.org/show_bug.cgi?id=1429488). This is a limited support (only header images, no Firefox Color compatibility) but it highlights a potential issue for AMO: we don't know which ST will be supported on Android.

For the frontend, we'd need to know which ST are compatible with Android because listing a ST that does not work on Android is bad UX.

**Comment by eviljeff** [comment]
In `parse_addon` we should look in the manifest and add the appropriate application compatibility - i.e. if it has a headerURL then it's compatible with fennec 65 (or whatever), but if it doesn't, or uses additional_backgrounds, then it's not.  In the future when/if fennec supports more features we can add further criteria (e.g. if supports UI colors in 68 then we'd add Android 68+).  

The existing API functionality for searching for compatible add-ons with an `app` and `appversion` should work with this.

addenda:
-we could do with knowing this sooner rather than later so the migrated themes are added as fennec compatible with an appropriate min-version
-backfilling user submitted static themes with the correct compatibility is another task.

**Comment by nt1m** [comment]
It will be Firefox 65, since uplift has been denied.

**Comment by eviljeff** [comment]
I moved implementing basic support to #10020 because that's uncontroversial but there's a decision to made here - what criteria (if any) will we use to decide if a given static theme is compatible with Android.  

To summarize: UI colors aren't supported, and neither are additional backgrounds.  Lack of UI colors will most likely just mean the look will be different; additional backgrounds are the bigger problem because normally that would be where the content is (i.e. the headerURL would be absent or an empty transparent image)

As I see it we've got 3 options:
A) assume all static themes are compatible with Android65+.  Some themes will look crappy and/or very different to the preview.
B) detect "additional_backgrounds" property in the manifest and then don't add support for Android at all.   May be some false positives.
C) detect "additional_backgrounds" property in the manifest and add a higher minimum app version.  Problem here is we don't have a future target date for full support on Android and AMO doesn't support having higher target app versions that at least the current nightly (afaik)

If we don't take any further action, #10020 will do A); C) is impractical (impossible?) with a target Firefox version... but do we want to do B)?

@jvillalobos for product decision.

**Comment by jvillalobos** [comment]
Let's just go with A. If it turns out to be problematic, we'll consider B.

**Comment by nt1m** [comment]
@eviljeff @jvillalobos I think checking if headerURL/theme_frame is present regardless of additional_backgrounds is simple enough to check if a theme works on Android... additional_backgrounds might slightly vary the result, but I wouldn't worry too much about it...

**Comment by eviljeff** [comment]
Checking for headerURL is a variant on B that will also have false positives (false negatives?) where the headerURL is an empty transparent image - that was the recommended solution when Firefox had headerURL as a required property and showed it on top of the additional backgrounds.  

Although that may be enough to filter out the colour-only themes that users of Firefox Color are submitting (Firefox Color also, afaik, uses additional backgrounds by default, making it doubly incompatible with Android)

**Comment by eviljeff** [comment]
going to close this issue for now as per jorge's https://github.com/mozilla/addons-server/issues/9967#issuecomment-440050962 - we can reopen if it becomes a problem.
